### ISSUE TITLE
Any example for Tensor<CUDAContext> or CUDAContext 

### ISSUE THREAD

**Issue by alexge233** [facebookarchive/caffe2#1004]
Hi,

I'm trying to understand how to load, copy or construct a `TensorCUDA` from a `cv::cuda::GpuMat`.
I can work with cuda primitives if needed, albeit there is a `cv::cuda::PtrStepSz<float>` which I can use.
My question is how do I assign, copy or construct a `TensorCUDA` in c++? I can't seem to find any examples, other than the ones where one is copying a `TensorCPU` to a `TensorCUDA`.

**Comment by salexspb** [comment]
If you already have memory allocated, you should be able to use Tensor::ShareExternalPointer to make a tensor point to it. You will have to take care of the pointer lifetime. There are several examples in the repo on using this function.

Also there is a function Context::Copy which allows to copy between devices / on the same device in a general way.

**Comment by alexge233** [comment]
@salexspb Many thanks! I'll try and post a snippet of how I've done it if I can get it to work with `cv::cuda::GpuMat`.

**Comment by salexspb** [comment]
I am going to close this for now. Please let us know how it goes and reopen if the issue still exists!

**Comment by alexge233** [comment]
@salexspb I've tried with `Tensor::ShareExternalPointer` however, it fails to link because my guess is there's no specialisation for `cv::cuda::GpuMat`.
If you guide me to the files that actually do the specialisation (or where it should be done) I'm willing to contribute.

Here's what I have:

```
struct tensor_wrapper
{
    /// @brief float data per channel BGR
    const std::vector<cv::cuda::GpuMat> data;
    // @brief Caffe2 Tensor using CUDA 
    caffe2::Tensor<caffe2::CUDAContext> tensor;

    /// @brief construct with float BRG data
    tensor_wrapper(std::vector<cv::cuda::GpuMat> arg,
                   unsigned int channels,
                   unsigned int rows,
                   unsigned int cols);
};

tensor_wrapper::tensor_wrapper(std::vector<cv::cuda::GpuMat> arg,
                               unsigned int channels,
                               unsigned int rows,
                               unsigned int cols)
: data(arg)
{
    std::vector<caffe2::TIndex> dims({1, channels, rows, cols});
    tensor.Reshape(dims);  
    tensor.ShareExternalPointer(arg.data(), channels * (rows * cols));
}
```

The error itself is:

```
(tensor.cpp.o): In function `tensor_wrapper::tensor_wrapper(std::vector<cv::cuda::GpuMat, std::allocator<cv::cuda::GpuMat> >, unsigned int, unsigned int, unsigned int)':
tensor.cpp:(.text+0x2de): undefined reference to `long caffe2::TypeMeta::Id<cv::cuda::GpuMat>()'
collect2: error: ld returned 1 exit status
```

Unless of course, I should be using `caffe2::TypeMeta` instead, in which case do you have any advice?
The pre-processing is done using `std::vector<cv::cuda::GpuMat>` but it can also be done using a `cv::cuda::GpuMat` directly.

The idea is that pre-processing takes place on the GPU using OpenCV's `cuda` functions, and thus there is no reason to download the float BGR data to host, only to re-upload to GPU.

**Comment by salexspb** [comment]
Sorry for a slow reply, I was out of office. Here you are trying to create a tensor out of cv::cuda::GpuMat, while tensors should be created out of float*. You need to provide a float pointer to ShareExternalPointer function.

**Comment by alexge233** [comment]
Just an update;
- I've managed to solve this by using the caffe2 allocated memory, and then telling OpenCV to use it for image processing. 
- So, caffe2 does the allocation, OpenCV the pre-processing, Caffe2 the processing, all using the same memory
- The repository is https://github.com/alexge233/espresso-maker
- The exact lines of interest are https://github.com/alexge233/espresso-maker/blob/master/espresso.cpp#L120

Hope it helps anyone stuck at a similar problem.
