### ISSUE TITLE
Link Error: undefined reference to `caffe2::VectorDB::DataRegistryMutex()'

### ISSUE THREAD

**Issue by StatML** [facebookarchive/caffe2#1006]
Hi, when I build caffe2 from source on Ubuntu 16.04.4/G++5.4/Python3.5, I met the following link error. Is there anyone knows how to fix it? Thx a lot!

> [ 81%] Linking CXX executable binaries/blob_test
CMakeFiles/blob_test.dir/core/blob_test.cc.o: In function `caffe2::(anonymous namespace)::ContentChunks_Serialization_Test::TestBody()':
blob_test.cc:(.text+0x3899d): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/blob_test.dir/core/blob_test.cc.o: In function `caffe2::VectorDB::registerData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&&)':
blob_test.cc:(.text._ZN6caffe28VectorDB12registerDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEOSt6vectorISt4pairIS6_S6_ESaISB_EE[_ZN6caffe28VectorDB12registerDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEOSt6vectorISt4pairIS6_S6_ESaISB_EE]+0x26): undefined reference to `caffe2::VectorDB::DataRegistryMutex()'
blob_test.cc:(.text._ZN6caffe28VectorDB12registerDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEOSt6vectorISt4pairIS6_S6_ESaISB_EE[_ZN6caffe28VectorDB12registerDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEOSt6vectorISt4pairIS6_S6_ESaISB_EE]+0x4a): undefined reference to `caffe2::VectorDB::Data[abi:cxx11]()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/blob_test.dir/build.make:145: recipe for target 'caffe2/binaries/blob_test' failed
make[2]: *** [caffe2/binaries/blob_test] Error 1
CMakeFiles/Makefile2:1310: recipe for target 'caffe2/CMakeFiles/blob_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/blob_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Derekglk** [comment]
Same issue. Nobody's handling this?

**Comment by PaulSzymanski** [comment]
Same issue on Centos 7.
My last successful build was on commit 859ab4846c6bf5ecdcbfc3da1f91d50bd0f485a3.
On commit cbcc0bd76ca229acbe4d5bd0470acfbf98c703b0 the build would fail. So the issue was introduced somewhen inbetween.

**Comment by timmyofmexico** [comment]
Recent commit 4b1bee1c2d784b4472e2d07da3a8ff13d4976034 should fix this problem.

**Comment by Yangqing** [comment]
This should be fixed - feel free to reopen.
