### ISSUE TITLE
Is snpe supported by caffe2 now?

### ISSUE THREAD

**Issue by daquexian** [facebookarchive/caffe2#1008]
Since snpe runtime has been released, is snpe supported by caffe2 now? If so how could I use snpe by caffe2?

Thanks in advance.

**Comment by Yangqing** [comment]
cc @bwasti . The example code is here: https://github.com/caffe2/caffe2/tree/master/caffe2/contrib/snpe-fb Although we will need a proper CMakeLists file right now - pull requests are appreciated :)
