### ISSUE TITLE
How to use nnpack accelerate? Can I select MKL ?

### ISSUE THREAD

**Issue by actinks** [facebookarchive/caffe2#1009]
Hello, I am a new user of caffe2, and I got a lot of problems.
When I use caffe framework, I can choose MKL or OpenBlas to accelerate my net. And I can use "export MKL_NUM_THREADS" to assign threads num. Now I don't know how to use nnpack and how to choose mkl.
I have run a model transferred from caffe, I got this warning :
W0803 10:48:50.294745 26961 conv_pool_op_base.h:554] You are hitting a case where Caffe's legacy padding calculation is hit. This leads to inefficient and sometimes incorrect results. We are keeping this behavior for backward compatibility, but you are strongly recommended to move away from it.
And caffe2 is slower than caffe, this is my test result:
caffe MKL use 4 threads :63.7196612358   caffe2 NNPACK : 81.6432404518

Could anyone know how to solve those problems, thank you very much !

**Comment by deepali-c** [comment]
To build with MKL - `cmake .. -DBLAS="MKL"`

**Comment by Yangqing** [comment]
-DBLAS="MKL" is the right way to go.

For NNPACK, you can set the engine of the operators to "NNPACK" and it should be able to use the nnpack ops then.
