### ISSUE TITLE
run caffe2 for android 

### ISSUE THREAD

**Issue by wuyubuaa** [facebookarchive/caffe2#1016]
When I run the code "./scripts/build_android.sh" on ubuntu via, it showed that "Did you set ANDROID_NDK variable?", I have installed the NDK, and the environment variables are configured.
How to solve it?

**Comment by lhCheung1991** [comment]
Just **export ANDROID_NDK=/path/to/Android/sdk/ndk-bundle** will fix it. @wuyubuaa

**Comment by wuyubuaa** [comment]
Thanks, but I have added it in .bashrc like this:
export NDK=/home/wuyu/sdk/ndk-bundle
export PATH=${PATH}:$NDK
export ANDROID_NDK=/home/wuyu/sdk/ndk-bundle
but it also showed "Did you set ANDROID_NDK variable?".
