### ISSUE TITLE
AddGradientOperators giving unexpected error.

### ISSUE THREAD

**Issue by dyigitpolat** [facebookarchive/caffe2#1017]
I'm trying to train over my pre-trained VGG16 model and I followed MNIST-LeNet tutorial to implement my own training script. However I could not manage to make it work, I'm struggling with the below error for days and couldn't understand what the issue is.

my code, cropped the related parts:
https://gist.github.com/dyigitpolat/26dba5265056c6de2d24e86ccefb40ba

some helper functions of mine:
(**brewing** is done here, so probably more related)
https://gist.github.com/dyigitpolat/0b90d886278ad368f5ee9d72e470b9a7  
     
    
    
**Error output:**

<pre>
Traceback (most recent call last):
  File "prune.py", line 84, in <module>
    <b>AddTrainingOperators( train_model, last_out, label)</b>
  File "/home/yigit/caf2/caffe2-yigit/caffe2/python/examples/modeltrainer.py", line 100, in AddTrainingOperators
    <b>model.AddGradientOperators([loss])</b>
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/model_helper.py", line 331, in AddGradientOperators
    self.grad_map = self.net.AddGradientOperators(*args, **kwargs)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 1769, in AddGradientOperators
    self._net.op[skip:], ys)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 1075, in GetBackwardPass
    return ir.GetBackwardPass(ys)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 950, in GetBackwardPass
    forward_op_idx, all_input_to_grad)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 904, in _GenerateGradientsForForwardOp
    forward_op_idx, gradient_ops, g_output, g_input)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 566, in BuildGradientGenerators
    s, g_output, fwd_op_idx, locally_generated_blobs)
  File "/home/yigit/caf2/caffe2-yigit/build/caffe2/python/core.py", line 509, in CheckGradientOperatorInput
    ) + versionMismatchInfoOut(grad_op_input)
<b>RuntimeError: Gradient operator needs output "fc7" at version 4, but currently we have version 5.</b>
  
  
  
DEBUG HELP:
<b>Maybe you use same output blob twice for different ops?</b>
== Version history of blob [fc7]
Version (out) 0 <-- input: "fc6"
input: "fc7_w"
input: "fc7_b"
output: "fc7"
type: "FC"
prune: 1

Version (out) 1 <-- input: "fc7"
output: "fc7"
type: "Relu"
prune: 1

Version (out) 2 <-- input: "fc7"
output: "fc7"
output: "_fc7_mask"
type: "Dropout"
arg {
  name: "ratio"
  f: 0.5
}
arg {
  name: "is_test"
  i: 1
}
prune: 1

Version (out) 3 <-- input: "fc6"
input: "fc7_w"
input: "fc7_b"
output: "fc7"
name: ""
type: "FC"
arg {
  name: "use_cudnn"
  i: 1
}
arg {
  name: "order"
  s: "NCHW"
}
arg {
  name: "cudnn_exhaustive_search"
  i: 0
}

Version (out) 4 <-- input: "fc7"
output: "fc7"
name: ""
type: "Relu"
arg {
  name: "cudnn_exhaustive_search"
  i: 0
}
arg {
  name: "order"
  s: "NCHW"
}
engine: "CUDNN"

Version (out) 5 <-- input: "fc7"
output: "fc7"
output: "_fc7_mask"
name: ""
type: "Dropout"
arg {
  name: "mask"
  s: "_fc7_mask"
}
arg {
  name: "order"
  s: "NCHW"
}
arg {
  name: "cudnn_exhaustive_search"
  i: 0
}
engine: "CUDNN"
</pre>

**Comment by mfawzymkh** [comment]
can you try printing / visualizing the network and attach a screen shot, please?

**Comment by dyigitpolat** [comment]
yes, here is the network graph:
![graph](https://user-images.githubusercontent.com/9355857/29002382-f4bd4244-7aa9-11e7-809b-fc8042b28145.png)

**Comment by dyigitpolat** [comment]
the graph above was from the predict_net.
below proto defines the training model:
(they look compatible)
<pre>
op {
  input: "data"
  input: "conv1_w"
  input: "conv1_b"
  output: "conv1"
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 7
  }
  prune: 1
}
op {
  input: "conv1"
  output: "conv1"
  type: "Relu"
  prune: 1
}
op {
  input: "conv1"
  output: "norm1"
  output: "_norm1_scale"
  type: "LRN"
  arg {
    name: "size"
    i: 5
  }
  arg {
    name: "alpha"
    f: 0.000500000023749
  }
  arg {
    name: "beta"
    f: 0.75
  }
  arg {
    name: "bias"
    f: 2.0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  prune: 1
}
op {
  input: "norm1"
  output: "pool1"
  type: "MaxPool"
  arg {
    name: "stride"
    i: 3
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "legacy_pad"
    i: 3
  }
  prune: 1
}
op {
  input: "pool1"
  input: "conv2_w"
  input: "conv2_b"
  output: "conv2"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 5
  }
  prune: 1
}
op {
  input: "conv2"
  output: "conv2"
  type: "Relu"
  prune: 1
}
op {
  input: "conv2"
  output: "pool2"
  type: "MaxPool"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "legacy_pad"
    i: 3
  }
  prune: 1
}
op {
  input: "pool2"
  input: "conv3_w"
  input: "conv3_b"
  output: "conv3"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "kernel"
    i: 3
  }
  prune: 1
}
op {
  input: "conv3"
  output: "conv3"
  type: "Relu"
  prune: 1
}
op {
  input: "conv3"
  input: "conv4_w"
  input: "conv4_b"
  output: "conv4"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "kernel"
    i: 3
  }
  prune: 1
}
op {
  input: "conv4"
  output: "conv4"
  type: "Relu"
  prune: 1
}
op {
  input: "conv4"
  input: "conv5_w"
  input: "conv5_b"
  output: "conv5"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "kernel"
    i: 3
  }
  prune: 1
}
op {
  input: "conv5"
  output: "conv5"
  type: "Relu"
  prune: 1
}
op {
  input: "conv5"
  output: "pool5"
  type: "MaxPool"
  arg {
    name: "stride"
    i: 3
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "legacy_pad"
    i: 3
  }
  prune: 1
}
op {
  input: "pool5"
  input: "fc6_w"
  input: "fc6_b"
  output: "fc6"
  type: "FC"
  prune: 1
}
op {
  input: "fc6"
  output: "fc6"
  type: "Relu"
  prune: 1
}
op {
  input: "fc6"
  output: "fc6"
  output: "_fc6_mask"
  type: "Dropout"
  arg {
    name: "ratio"
    f: 0.5
  }
  arg {
    name: "is_test"
    i: 1
  }
  prune: 1
}
op {
  input: "fc6"
  input: "fc7_w"
  input: "fc7_b"
  output: "fc7"
  type: "FC"
  prune: 1
}
op {
  input: "fc7"
  output: "fc7"
  type: "Relu"
  prune: 1
}
op {
  input: "fc7"
  output: "fc7"
  output: "_fc7_mask"
  type: "Dropout"
  arg {
    name: "ratio"
    f: 0.5
  }
  arg {
    name: "is_test"
    i: 1
  }
  prune: 1
}
op {
  input: "fc7"
  input: "fc8_w"
  input: "fc8_b"
  output: "fc8"
  type: "FC"
  prune: 1
}
op {
  input: "fc8"
  output: "prob"
  type: "Softmax"
  prune: 1
}
op {
  input: "reader"
  output: "data_nhwc"
  output: "label"
  name: ""
  type: "ImageInput"
  arg {
    name: "std"
    f: 128.0
  }
  arg {
    name: "scale"
    i: 256
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "batch_size"
    i: 250
  }
  arg {
    name: "use_cudnn"
    i: 1
  }
  arg {
    name: "use_caffe_datum"
    i: 1
  }
  arg {
    name: "mirror"
    i: 1
  }
  arg {
    name: "crop"
    i: 224
  }
  arg {
    name: "mean"
    f: 128.0
  }
}
op {
  input: "data_nhwc"
  output: "data"
  name: ""
  type: "NHWC2NCHW"
}
op {
  input: "data"
  output: "data"
  name: ""
  type: "StopGradient"
}
op {
  input: "data"
  input: "conv1_w"
  input: "conv1_b"
  output: "conv1"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 7
  }
  engine: "CUDNN"
}
op {
  input: "conv1"
  output: "conv1"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv1"
  output: "norm1"
  output: "_norm1_scale"
  name: ""
  type: "LRN"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
}
op {
  input: "conv1"
  output: "pool1"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "stride"
    i: 3
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "pool1"
  input: "conv2_w"
  input: "conv2_b"
  output: "conv2"
  name: ""
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 5
  }
  engine: "CUDNN"
}
op {
  input: "conv2"
  output: "conv2"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv2"
  output: "pool2"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "pool2"
  input: "conv3_w"
  input: "conv3_b"
  output: "conv3"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  engine: "CUDNN"
}
op {
  input: "conv3"
  output: "conv3"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv3"
  input: "conv4_w"
  input: "conv4_b"
  output: "conv4"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  engine: "CUDNN"
}
op {
  input: "conv4"
  output: "conv4"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv4"
  input: "conv5_w"
  input: "conv5_b"
  output: "conv5"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  engine: "CUDNN"
}
op {
  input: "conv5"
  output: "conv5"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "conv5"
  output: "pool5"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "stride"
    i: 3
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "pool5"
  input: "fc6_w"
  input: "fc6_b"
  output: "fc6"
  name: ""
  type: "FC"
  arg {
    name: "use_cudnn"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
}
op {
  input: "fc6"
  output: "fc6"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "fc6"
  output: "fc6"
  output: "_fc6_mask"
  name: ""
  type: "Dropout"
  arg {
    name: "mask"
    s: "_fc6_mask"
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  engine: "CUDNN"
}
op {
  input: "fc6"
  input: "fc7_w"
  input: "fc7_b"
  output: "fc7"
  name: ""
  type: "FC"
  arg {
    name: "use_cudnn"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
}
op {
  input: "fc7"
  output: "fc7"
  name: ""
  type: "Relu"
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
}
op {
  input: "fc7"
  output: "fc7"
  output: "_fc7_mask"
  name: ""
  type: "Dropout"
  arg {
    name: "mask"
    s: "_fc7_mask"
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  engine: "CUDNN"
}
op {
  input: "fc7"
  input: "fc8_w"
  input: "fc8_b"
  output: "fc8"
  name: ""
  type: "FC"
  arg {
    name: "use_cudnn"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
}
op {
  input: "fc8"
  output: "prob"
  name: ""
  type: "Softmax"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "cudnn_exhaustive_search"
    i: 0
  }
  engine: "CUDNN"
}
device_option {
  device_type: 1
  cuda_gpu_id: 0
}
external_input: "data"
external_input: "conv1_w"
external_input: "conv1_b"
external_input: "conv2_w"
external_input: "conv2_b"
external_input: "conv3_w"
external_input: "conv3_b"
external_input: "conv4_w"
external_input: "conv4_b"
external_input: "conv5_w"
external_input: "conv5_b"
external_input: "fc6_w"
external_input: "fc6_b"
external_input: "fc7_w"
external_input: "fc7_b"
external_input: "fc8_w"
external_input: "fc8_b"
external_input: "reader"
external_output: "prob"
</pre>

**Comment by dyigitpolat** [comment]
I am now guessing that Caffe2 does not let me do in place computations the way I brew the net.

**Comment by mfawzymkh** [comment]
I'm thinking if you print the graph with backward pass as well (not the predict_net), it will become clear why this is failing.  Can you please do that?

**Comment by dyigitpolat** [comment]
i cannot manage to get to that stage

**Comment by mfawzymkh** [comment]
my guess is that because you're doing in-place update for the blobs (each time you write to the blob, its version is incremented), but when you try to add the gradient op,  it checks if we are using the same version of the blob the forward pass  op used.

**Comment by mfawzymkh** [comment]
yes, the problem is that you are doing the in-place update (using the same blob output ) for DropOut  Operator.   when calculating the Gradient, you will need to override the same blob in the input, and this will cause the version mismatch. 


Can you please try to use a different blob name for the output of your DropOut operator (for both fc6 and fc7)   and let me know if it works?

**Comment by dyigitpolat** [comment]
That error is disappeared after seperating the dropout output. You can close the issue.
But I still cannot do what I want to do.
I have ilsvrc2012 dataset and VGG16 pretrained network. (init_net and predict_net files) and I want to train/finetune it further with caffe2. why is this so hard and have no examples?

**Comment by mfawzymkh** [comment]
dyigitpolat, sorry to hear that.   Can you please open an issue about having more examples for this use case.  I think it will be valuable to have something like that.

**Comment by clingsz** [comment]
Hi, @dyigitpolat, I am running into the same problem. Is there any follow up on this issue? Thanks!

**Comment by LMerCy** [comment]
same problem,and i am doing the same thing with Alexnet, from so far still no official examples for fine-tuning.
And what do you mean by seperating the dropout output?
@dyigitpolat 
And i found a problem , when i change the output("fc6") of dropout(op#17) to "fc6_drop", the next fc operator(op#18) will connect to output of op#16 , so i change the input of op#18 to "fc6_drop", it works finnally.
