### ISSUE TITLE
AI Camera demo on Android 

### ISSUE THREAD

**Issue by wuyubuaa** [facebookarchive/caffe2#1033]
I have build the android environment uses the code "./scripts/build_android.sh" on ubuntu. How I can run the AI Camera demo on android phone? 
https://github.com/bwasti/AICamera says the dome can be built using build_android.sh in the Caffe2 source. But the demo's file do not contains the "build_android.sh ",what should I do next?

**Comment by lzx1413** [comment]
you should use build_android.sh to build the static library and put them in the jniLibs folder of the AS project

**Comment by wuyubuaa** [comment]
@lzx1413 Thanks!But I want to ask some question about the demo, and I have send you an email , I hope you can give me some advises.

**Comment by wuyubuaa** [comment]
@lzx1413 I did not use build_android.sh to build the static library and put them in the jniLibs folder of the AS project, and I opened the AI project, that means I do not use the caffe2 library, but it can run successfully on my android phone,why?

**Comment by lzx1413** [comment]
@wuyubuaa it is because that there are libraries in the jinLibs already

**Comment by wuyubuaa** [comment]
@lzx1413 Get it ! Thanks!
