### ISSUE TITLE
Linking CXX shared library libCaffe2_CPU.so Error

### ISSUE THREAD

**Issue by StatML** [facebookarchive/caffe2#1034]
Hi, I met the following problem when building from source. Does anyone know how to fix it? Thx!

OS:   Ubuntu 16.04.4
G++: 5.40

>  [49%] Linking CXX shared library libCaffe2_CPU.so
> `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf' referenced in section `.note.stapsdt' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o: defined in discarded section `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf[_ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf]' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o
> `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf' referenced in section `.note.stapsdt' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o: defined in discarded section `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf[_ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf]' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o
> `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf' referenced in section `.note.stapsdt' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o: defined in discarded section `.text._ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf[_ZN6caffe210BlobsQueue12blockingReadERKSt6vectorIPNS_4BlobESaIS3_EEf]' of CMakeFiles/Caffe2_CPU.dir/queue/queue_ops.cc.o
> collect2: error: ld returned 1 exit status
> caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:5247: recipe for target 'caffe2/libCaffe2_CPU.so' failed
> make[2]: *** [caffe2/libCaffe2_CPU.so] Error 1
> CMakeFiles/Makefile2:1483: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/all' failed
> make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by deepali-c** [comment]
Please` clean and build` once.

**Comment by ezineo** [comment]
@StatML hi, I meet the same error. Did you solve that problem?

**Comment by ghost** [comment]
i solved by https://github.com/caffe2/caffe2/pull/1029/commits, i think they will fix it soon

**Comment by StatML** [comment]
Hi, @deepali-c I had tried `clean and build`, it did not work.

**Comment by StatML** [comment]
Hi @ezineo Until now, this issue is still not solved...

**Comment by Knight-X** [comment]
#1029 deal with this issue

**Comment by Yangqing** [comment]
This should be fixed by 707aed36e89ab9e2041de25166a4930fc4e24ee7 - thanks so much for checking this guys!

**Comment by StatML** [comment]
Thanks @Yangqing ! :)
