### ISSUE TITLE
Build failure on MacOS X

### ISSUE THREAD

**Issue by JammyZhou** [facebookarchive/caffe2#1036]
Follow instructions from https://caffe2.ai/docs/getting-started.html to download and build Caffe2 on MacOS X, but the build failed with error below.

```
caffe2/caffe2/perfkernels/typed_axpy_avx2.cc:19:15: error: use of undeclared identifier '_cvtsh_ss'
    *(y++) += _cvtsh_ss((*(x++)).x) * a;
              ^
caffe2/caffe2/perfkernels/typed_axpy_avx2.cc:40:21: error: use of undeclared identifier '_cvtsh_ss'
      y[current] += _cvtsh_ss(x[current].x) * a;
                    ^
2 errors generated.
make[2]: *** [caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/typed_axpy_avx2.cc.o] Error 1
make[1]: *** [caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/all] Error 2
make: *** [all] Error 2
```
It looks like the clang version check for __APPLE__ in caffe2/perfkernels/cvtsh_ss_bugfix.h seems not accurate. The clang version on my system is 8.0.0, but don't have _cvtsh_ss intrinsics.
```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Yangqing** [comment]
Interesting, we haven't covered all cases (clang 8.1.0 seems to have that fixed). Could you change
  #if defined(__APPLE__) && (__clang_major__ < 8)
to something like
  #if defined(__APPLE__) && ((__clang_major__ < 8) && (__clang_minor__ < 1))

and see if that addresses the issue? A pull request would be highly appreciated.

**Comment by JammyZhou** [comment]
Pull request: https://github.com/caffe2/caffe2/pull/1047

**Comment by Yangqing** [comment]
Thanks! Merged.
