### ISSUE TITLE
How to use Nvidia GPU in ARM?

### ISSUE THREAD

**Issue by actinks** [facebookarchive/caffe2#1037]
Hello, If caffe2 only supports cuda8.0? But cuda8.0  not supports arm !

Thank you !

**Comment by Yangqing** [comment]
If you run on TX1/TX2, https://github.com/caffe2/caffe2/blob/master/scripts/build_tegra_x1.sh is a good starting point - not aware of other platforms that might have ARM + nvidia gpu though.
