### ISSUE TITLE
How to develop my own operators?

### ISSUE THREAD

**Issue by hpsoar** [facebookarchive/caffe2#1039]
I want to add my operators, I know how to add them.

My problem is how should I do debugging/profiling?

In the past, I usually use Visual Studio/Xcode to do it.

Currently, I'm able to generate the Xcode project with cmake.

I wonder how you do it, is there a guide or best practice for this?

**Comment by pietern** [comment]
There is no guide on how to use Xcode for developing operators. You can look at any one of the operators in caffe2/operators as an example and add your own next to them.
