### ISSUE TITLE
relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by lucasjinreal** [facebookarchive/caffe2#1043]
Building using Scripts/build_local.sh, nothing changes got this error:

```
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2_pybind11_state.dir/build.make:150: recipe for target 'caffe2/python/caffe2_pybind11_state.so' failed
make[2]: *** [caffe2/python/caffe2_pybind11_state.so] Error 1
CMakeFiles/Makefile2:1385: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/all] Error 2
Makefile:140: recipe for target 'all' failed

```

Any idea about how to solve this?it's there a one script build or should I build all the depencies? Why caffe always have a lot depencies? This is not really good.

**Comment by Yangqing** [comment]
This seems to be that your gflags library is not built with PIC. Which platform are you building this on? You can either turn off gflags support (-DUSE_GFLAGS=OFF) or rebuild your gflags library so it is with -fPIC.

**Comment by lucasjinreal** [comment]
Thanks am building on Ubuntu16.04 gflag and protobuf can be build success but always not properly recognized by caffe2
