### ISSUE TITLE
Building on Windows : scripts/build_host_protoc.bat now fails (where are third_party files?)

### ISSUE THREAD

**Issue by WilfR** [facebookarchive/caffe2#1045]
Hi Guys, 
  I'm following the [Windows Build from Source](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) procedure. 
  I clone https://github.com/caffe2/caffe2 into a fresh local repository, and try to run scripts/build_host_protoc.bat. It now fails with error message 

CMake Error: The source directory "C:/home/Tools/caffe2/third_party/protobuf/cmake" does not exist.

I am reasonably sure that this batch file used to work on earlier versions of Caffe2 but I guess it is possible that I am misremembering. Is something broken, or did something change, or am I doing something wrong? 

EDIT: In fact it looks like there are no files at all under caffe2/third_party in my new local repository. I can see the folders exist, but there are no files under them at all. 

Thanks!

**Comment by jackyko1991** [comment]
you need to git clone in recursive mode to download protobuf submodules

**Comment by WilfR** [comment]
Oh dammit! Thank you @jackyko1991, I am sure that's my problem. I appreciate your taking the time to help a noob!
Cheers,
Wilf
