### ISSUE TITLE
caffe2 multi-machine rendezvous

### ISSUE THREAD

**Issue by githubgsq** [facebookarchive/caffe2#1050]
hi, @pietern it mentioned in the gloo readme file that 
https://github.com/facebookincubator/gloo/blob/97bd6aae370622a574775260e361fb0d354d9f22/README.md
MPI is for coordinating machine rendezvous through MPI
so is it possible just using MPI as rendezvous but not redis or nfs?
MPI is used to create context for rendezvous, right?
But I tried with command:
mpirun -machinefile addr.conf -npernode 1 python /home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/gaosiqi/projects/practice/resnet/imagenet_cars_boats_train/  --num_shards=2 --db_type lmdb --num_gpus 4 --batch_size 32 --epoch_size 6400  --num_epochs 1

errors occured:
E0808 15:10:11.940057  8517 common_world_ops.h:90] Caught store handler timeout exception: [/home/gaosiqi/caffe2Env/caffe2/caffe2/distributed/file_store_handler.cc:132] Wait timeout for name(s): allreduce_0_cw_op/1

It seems that nfs is needed for rendezvous by default.

I have compiled gloo with "USE_MPI=ON" according to
https://github.com/facebookincubator/gloo/blob/511ca3ea1b1afba8c236a10373a03318e5c8bd31/docs/rendezvous.md

Do you have any advice? Why MPI can not be used as rendezvous directly?
Both nfs and redis can run successfully as rendezvous, I'm curious about whether MPI can play the rendezvous role and what's the mechanism?

**Comment by Yangqing** [comment]
@pietern

**Comment by pietern** [comment]
@githubgsq It is possible from Gloo, but this is not hooked up to Caffe2 yet. I'm working on adding this.

**Comment by githubgsq** [comment]
OK，thanks！

**Comment by pietern** [comment]
Since #1190 you can use mpirun to launch `resnet50_trainer.py`.

If you want to add this functionality to your own trainer you can check out [this part of the diff](https://github.com/caffe2/caffe2/commit/7a9a93cb11d4f11da34474be5a02ba239646dba3#diff-a8d23b923c9f225d91efe7a4f068f986).
