### ISSUE TITLE
how to obtain computation time and communication time respectively in caffe2?

### ISSUE THREAD

**Issue by githubgsq** [facebookarchive/caffe2#1051]
Hi, @Yangqing @pietern is there any method to obtain computation and communication cost respectively under multi-machine scenarios?

**Comment by ugionet** [comment]
https://github.com/caffe2/caffe2/issues/921

**Comment by githubgsq** [comment]
@ugionet Hi, is there any python function please?
Moreover, how to separate the calculation time from the communication time when running a multi-node instance?

**Comment by ugionet** [comment]
@githubgsq I have a python function for Caffe2  ... The run times are pretty much the same for C++ and Python runs .

**Comment by githubgsq** [comment]
@ugionet hi, is there any caffe2 profiler? How do you test mpi communication time, cpu computation time, gpu computation time, gpu communication time, please? Any advice would be appreciatedO(∩_∩)O

**Comment by ugionet** [comment]
After loading all your Network models (init_net, predict_net etc.) and specify your working environment (CUDA, MKL etc. for your network to run on), you have many different options to time the process of running a network on some input data (e.g., OpenCV with : getTickCount, getTickFrequency, or in python you can simply use time) . 
Moreover you can use the : workspace.BenchmarkNet, which provides for each layer the latency it produced in the overall run...
In C++ you can use the Intel Profiler or Nvidia profiler to achieve better understanding as to which one of the operations require CPU/GPU Resources, and how much of them.

**Comment by githubgsq** [comment]
@ugionet  Thanks a lot:)

**Comment by githubgsq** [comment]
@ugionet hi, where was work.BenchmarkNet() defined? 
I just found BenchmarkNet in module caffe2.python.workspace
and BenchmarkNet = C.benchmark_net
but no detailed instructions about the input parameters and output values.
https://caffe2.ai/doxygen-python/html/namespaceworkspace.html#top
could you send me the website where BenchmarkNet was descripted in detail please?

**Comment by githubgsq** [comment]
@ugionet  hi, where was workspace.BenchmarkNet() defined?
I just found BenchmarkNet in module caffe2.python.workspace
and BenchmarkNet = C.benchmark_net
but no detailed instructions about the input parameters and output values.
https://caffe2.ai/doxygen-python/html/namespaceworkspace.html#top
could you send me the website where BenchmarkNet was descripted in detail please?

**Comment by ugionet** [comment]
vector<float> SimpleNet::TEST_Benchmark  .... 
This is the function that is called from the PYTHON Interface. 
Where this function is declared in core/net.h, and It is defined in core/net.cc . 

To call it from python, simply execute: 
warmup_runs = SOME_INTEGER (e.g., 50)
main_runs = SOME_INTEGER (e.g., 1000)
run_individual = True
stats = workspace.BenchmarkNet(net_def.name, warmup_runs, main_runs, run_individual)

Hope it helps.

**Comment by githubgsq** [comment]
@ugionet Thanks;)
