### ISSUE TITLE
Failed to download model on MacOS

### ISSUE THREAD

**Issue by JammyZhou** [facebookarchive/caffe2#1059]
Failed to download pre-trained model as described in https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb
```
$sudo python -m caffe2.python.models.download -i squeezenet
/Applications/anaconda/bin/python: No module named caffe2.python.models
```
Then I switched to use caffe2/python/models/download.py directly, but still failed.
```
$ sudo python download.py -i squeezenet
Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [HTTP Error] 404: Not Found.
Cleaning up...

```
And digging further, I tried to use wget to download predict_net.db, failed again. Any suggestions?
```
$ wget https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
--2017-08-09 11:09:34--  https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Resolving s3.amazonaws.com... 52.216.82.171
Connecting to s3.amazonaws.com|52.216.82.171|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-08-09 11:09:37 ERROR 404: Not Found.
```

**Comment by JammyZhou** [comment]
The same problem happened on my Linux box.

**Comment by Elhassouny** [comment]
the same happened with me on Mac

**Comment by jerryzh168** [comment]
The link should be https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/predict_net.pb

**Comment by jerryzh168** [comment]
We just updated the download link recently, so if you reinstall caffe2 from source, the problem should be resolved.

**Comment by JammyZhou** [comment]
Great. It works for me now.
