### ISSUE TITLE
opencl

### ISSUE THREAD

**Issue by wm901115nwpu** [facebookarchive/caffe2#1064]
caffe2/caffe2/contrib/opengl

  does not contain a CMakeLists.txt file.

**Comment by Yangqing** [comment]
Yup, there is an issue in our sync script that stripped it off - for now check Yangqing/caffe2 for the missing files.

**Comment by Yangqing** [comment]
Fixed in f0ea8046c26d9c324dc34deb2bfd8e3738e9f02c
