### ISSUE TITLE
Error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’

### ISSUE THREAD

**Issue by StatML** [facebookarchive/caffe2#1067]
Hi, I met the following problem when building from source. My platform is Ubuntu 16.04.4, G++ 5.4.0, Python 3.5.2. Does anyone know how to fix it? Thx!

> [ 12%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/context.cc.o
> In file included from caffe2-git/caffe2/contrib/gloo/common_world_ops.cc:1:0:
> caffe2-git/caffe2/contrib/gloo/common_world_ops.h: In member function ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice()’:
> caffe2-git/caffe2/contrib/gloo/common_world_ops.h:72:26: error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’
>                  device_->getTimeout()) {
>                           ^
> caffe2-git/caffe2/contrib/gloo/common_world_ops.h: In instantiation of ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice() [with Context = caffe2::CPUContext]’:
> caffe2-git/caffe2/contrib/gloo/common_world_ops.cc:33:1:   required from here
> caffe2-git/caffe2/contrib/gloo/common_world_ops.h:71:13: error: ‘class gloo::Context’ has no member named ‘getDevice’
>              backingCommonWorld->getDevice()->getTimeout() <
>              ^
> caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:158: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common_world_ops.cc.o' failed
> make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common_world_ops.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:1515: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/all' failed
> make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by dbermond** [comment]
What is the caffe2 version that you're using to compile?
v0.8.1? git master?

**Comment by StatML** [comment]
Hi @dbermond git master

**Comment by dbermond** [comment]
That's really strange because we were having the same error, we are using the same compiler, and recent commits on git master fixed it for me but not for you. Sounds like a problem on the build tree or something of that sort.

Just to make sure, what's the output of `git describe --long --tags`?

**Comment by StatML** [comment]
Hi @dbermond Yes, that's really strange... the output of `git describe --long --tags` on my machine is `v0.8.1-30-g7561327`

**Comment by dbermond** [comment]
Ok, so it's updated.

You can try to do these steps to make sure that everything is fine with your build tree.

First of all, try to remove gloo if you installed it system wide. Caffe2 will build it and this will avoid any conflict with any possibly outdated system wide gloo files. Secondly, if you are using a compiler cache (like ccache), disable it or clear the compiler cache.

Then, delete your build directory and try to do a clean build. In my case, my build directory is `<caffe2-src-tree-dir>/build`.

If this does not work, try to delete your entire caffe2 source tree and and do a completely new git clone. Yes, depending on your connection speed this can take a lot of time, but it will make sure that your build tree will be clean and fine.

**Comment by StatML** [comment]
Hi @dbermond Doing a complete new git clone solves the problem. Thanks a lot! :+1:

**Comment by dbermond** [comment]
> Hi @dbermond Doing a complete new git clone solves the problem. Thanks a lot! :+1:

Nice news! Good to know.
