### ISSUE TITLE
how caffe2 synchronize? per batch_size or per epoch?

### ISSUE THREAD

**Issue by githubgsq** [facebookarchive/caffe2#1071]
@Yangqing @pietern hi, I'm curious about how caffe2 synchronize, after finishing one batch_size or one epoch iteration or other strategies please?

**Comment by davinwang** [comment]
I use a workaround: create a mini model that only has DB read, run the model for several times before running the actual model, so the actual model will skip the data. However this is of low efficiency.

**Comment by Yangqing** [comment]
Not sure what your question means, but caffe2 syncs after every batch (i.e. net run).

**Comment by githubgsq** [comment]
Thanks!
