### ISSUE TITLE
Cannot build caffe2 IOS with NNPACK anymore

### ISSUE THREAD

**Issue by power0341** [facebookarchive/caffe2#1072]
after the latest update, (adding ios metal support), the ios build script seems to be corrupted, when I turned on USE_NNPACK flag, I got errors like this:

```
CMake Error: Cannot determine link language for target "CAFFE2_NNPACK".
CMake Error: CMake can not determine linker language for target: CAFFE2_NNPACK
```

**Comment by Yangqing** [comment]
Could you start a fresh library, check out master and rebuild? I think this should be fixed right now - contbuild is showing green. If it does not work, could you report the build environment you are under, and also a detailed build output?

**Comment by Yangqing** [comment]
(feel free to assign back)

**Comment by power0341** [comment]
@Yangqing well, the error has occurred due to CMake found no source code for target CAFFE2_NNPACK, then I realized that I should update the 3rd party libraries as well. 
`git submodule update` solves the problem.
