### ISSUE TITLE
How are group convolutions implemented?

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1077]
I am trying to understand how group convolutions are implemented but so many `context`s and `CuDNNWrapper`s really confuse me. Can anyone tell me whether group convolutions are implemented using CuDNN with multiple CUDA streams or using serialized CuDNNs? Thank you. :)

**Comment by lukeyeager** [comment]
It's just a loop. Serialized in the same stream.
https://github.com/caffe2/caffe2/blob/v0.8.1/caffe2/operators/conv_op_cudnn.cc#L504

**Comment by slayton58** [comment]
cuDNN v7 also introduces the concept of handling the grouping directly with cuDNN. I have a version of that implemented locally, I'll try and get a PR issued today for it.

**Comment by slayton58** [comment]
See #1079

**Comment by ghost** [comment]
Thank you all, now I understand it!
