### ISSUE TITLE
Fetching Submodule "club" failed in cloning

### ISSUE THREAD

**Issue by graykevinb** [facebookarchive/caffe2#1081]
Running `git clone --recursive https://github.com/caffe2/caffe2.git` I got the following error:

error: Server does not allow request for unadvertised object b1370adb972a8345de92e2d69e61daf7f9bce43e
Fetched in submodule path 'third_party/cub', but it did not contain b1370adb972a8345de92e2d69e61daf7f9bce43e. Direct fetching of that commit failed.

**Comment by futuyao** [comment]
Save problem here. Anybody know how to solve this?

**Comment by netfish88** [comment]
same here.

**Comment by yuanzhong90** [comment]
Same here.

**Comment by lubtd** [comment]
Same here on macOS.

**Comment by rauscheck** [comment]
same problem, macOS sierra

**Comment by tegg89** [comment]
same here on Ubuntu 16.04

**Comment by lukeyeager** [comment]
Fix is coming: https://github.com/caffe2/caffe2/pull/1089

**Comment by pietern** [comment]
Thanks for reporting!
