### ISSUE TITLE
Cannot download squeeznet

### ISSUE THREAD

**Issue by graykevinb** [facebookarchive/caffe2#1091]
Running `python -m caffe2.python.models.download -i squeezenet` gives the following error:
`Abort: Could not download model. [HTTP Error] 404: Not Found.`

I tried downloading the files manually from here: https://caffe2.ai/docs/zoo, but the same error occurred.

**Comment by ZhidongLin** [comment]
I encountered the same error and I think it arises from download.py at: caffe2/caffe2/python/models/download.py. 
If you open this. py file by notepad++, you could see the link to download squeezenet:
![uyiw3h6 _gzmj3 1cgfikr](https://user-images.githubusercontent.com/30132859/29304808-bc3b3e24-81c7-11e7-91bd-0e6feb7b7bf0.png)
I opened the link and found that it is almost blank, I guess this link has been invalid. I suggest that you could try to replace the link with the link of your own copy of github cloning link like "https://github.com/XXXX/models.git" to see if it works.

**Comment by harouwu** [comment]
cc: @aaronmarkham

**Comment by erik-dreyer** [comment]
To fix this, just clone the caffe2 models from the official caffe2 github repo to your caffe2/caffe2/python/models/ directory:

`git clone https://github.com/caffe2/models.git`

**Comment by jerryzh168** [comment]
The BASE_URL is updated to https://s3.amazonaws.com/download.caffe2.ai/models/, if you update your local caffe2 repo and reinstall caffe2 from source, you should be able to use "python -m caffe2.python.models.download -i squeezenet" again.

**Comment by graykevinb** [comment]
thank you!
