### ISSUE TITLE
Conda packaged caffe2 still requires LD_LIBRARY_PATH for CUDA

### ISSUE THREAD

**Issue by ezyang** [facebookarchive/caffe2#1115]
Steps to reproduce:
1. Build and install Caffe2 using the conda packaging
2. Run this:

```
python -c "import caffe2.python.core"
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcudart.so.8.0: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: libcudart.so.8.0: cannot open shared object file: No such file or directory
(python2) [ezyang@home ~/local/pytorch] LD_LIBRARY_PATH=/usr/local/cuda/lib64 python -c "import caffe2.python.core"
```

Expected result: it's not necessary to add LD_LIBRARY_PATH to CUDA directory

Actual result: it is necessary

I am not familiar with how Caffe2's Python library looks for these libraries so I don't know if there's some mechanism that should be triggering that is not. Possibly the notice that CUDA is not supported by this build is related.

**Comment by pietern** [comment]
This is expected, since we currently don't add an RPATH to the built libraries. I'm looking into this.

**Comment by lukeyeager** [comment]
FYI, recent CUDA packages do this for you:
```
cuda-cudart-8-0: /etc/ld.so.conf.d/cuda-8-0.conf
cuda-cudart-9-0: /etc/ld.so.conf.d/cuda-9-0.conf
```

**Comment by ezyang** [comment]
OK, I'm going to close this
