### ISSUE TITLE
rasbian build error in workerspool.h

### ISSUE THREAD

**Issue by Knight-X** [facebookarchive/caffe2#1135]
In file included from /home/pi/workspace/caffe2/caffe2/utils/threadpool/ThreadPool.cc:2:0:
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h: In member function ‘void caffe2::WorkersPool::Execute(const std::vector<std::shared_ptr<caffe2::Task> >&)’:
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:364:60: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
     std::for_each(++tasks.begin(), tasks.end(), [this, &n](auto& task) {
                                                            ^~~~
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h: In lambda function:
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:365:37: error: request for member ‘get’ in ‘task’, which is of non-class type ‘int’
       workers_[n++]->StartWork(task.get());
                                     ^~~
In file included from /usr/include/c++/6/algorithm:62:0,
                 from /home/pi/workspace/caffe2/caffe2/core/common.h:4,
                 from /home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:1,
                 from /home/pi/workspace/caffe2/caffe2/utils/threadpool/ThreadPool.cc:2:
/usr/include/c++/6/bits/stl_algo.h: In instantiation of ‘_Funct std::for_each(_IIter, _IIter, _Funct) [with _IIter = __gnu_cxx::__normal_iterator<const std::shared_ptr<caffe2::Task>*, std::vector<std::shared_ptr<caffe2::Task> > >; _Funct = caffe2::WorkersPool::Execute(const std::vector<std::shared_ptr<caffe2::Task> >&)::<lambda(int&)>]’:
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:366:6:   required from here
/usr/include/c++/6/bits/stl_algo.h:3769:5: error: no match for call to ‘(caffe2::WorkersPool::Execute(const std::vector<std::shared_ptr<caffe2::Task> >&)::<lambda(int&)>) (const std::shared_ptr<caffe2::Task>&)’
  __f(*__first);
  ~~~^~~~~~~~~~
In file included from /home/pi/workspace/caffe2/caffe2/utils/threadpool/ThreadPool.cc:2:0:
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:364:70: note: candidate: caffe2::WorkersPool::Execute(const std::vector<std::shared_ptr<caffe2::Task> >&)::<lambda(int&)>
     std::for_each(++tasks.begin(), tasks.end(), [this, &n](auto& task) {
                                                                      ^
/home/pi/workspace/caffe2/caffe2/utils/threadpool/WorkersPool.h:364:70: note:   no known conversion for argument 1 from ‘const std::shared_ptr<caffe2::Task>’ to ‘int&’
caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:4745: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/utils/threadpool/ThreadPool.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/utils/threadpool/ThreadPool.cc.o] Error 1
make[2]: Leaving directory '/home/pi/workspace/caffe2/build'
CMakeFiles/Makefile2:2590: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make[1]: Leaving directory '/home/pi/workspace/caffe2/build'
Makefile:141: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by agarwal-ayushi** [comment]
I am facing the same issue. Couldn't find much on the internet and the forums regarding this issue. Can someone help?

**Comment by Knight-X** [comment]
I have just make a pull request for this issue. It is not a bug. It is just a c++14 feature, but we compile caffe2 with c++11.

**Comment by agarwal-ayushi** [comment]
Yes, I saw the pull request before commenting. I understood its a declaration issue. 
However, since I am new to Caffe2, is there a way to compile the caffe2 with c++14 by passing it in the argument as --std=c++14??

**Comment by Knight-X** [comment]
Well, I think that newest commit "076a4a99f6c4026" has solved this issue. It should work. You just need to pull new version of caffe2 and build with c++11.
