### ISSUE TITLE
Question of "--allow-root" when installed caffe2 on Docker Toolbox in windows 10

### ISSUE THREAD

**Issue by qians17** [facebookarchive/caffe2#1141]
Hi,

I am working on install caffe2 by dockers on windows 10. I am following the instruction from https://caffe2.ai/docker/caffe2-docker-usb/readme.html. Because it claims that it has a hyper-V issue, I use docker Toolbox instead. Right now I am facing an issue that when I try to run:
"docker run -it -p 8888:8888 c2.gpu.tutorial.0.7.0 sh -c "jupyter notebook --no-browser --ip 0.0.0.0 /caffe2/caffe2/python/tutorials""

It will show an error that:
[I 17:27:25.979 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[C 17:27:26.001 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.

I google the general solution to add  --allow-root flag on dockers but none of them run in windows and use Docker Toolbox but not Docker. I am new to caffe2 and Docker. Could anyone tell me how to fix this issue?

Thanks,

**Comment by Yangqing** [comment]
Seems to be a jupyter issue running in a docker container. Quick google search revealed the following:

https://github.com/jupyter/notebook/issues/2375
https://github.com/jupyter/notebook/issues/1539
