### ISSUE TITLE
Operator Min is missing?

### ISSUE THREAD

**Issue by iteal** [facebookarchive/caffe2#1145]
I found the operator Max : https://caffe2.ai/docs/operators-catalogue.html#max
but not the operator Min, is it missing? Thanks!

**Comment by iteal** [comment]
It was added ! https://github.com/caffe2/caffe2/commit/8c7d1bd9c24a1d3f1554563df5ed502177a2ff1b#diff-466a478e6c6e70d96253a4f76441a555
It would have been nice to update this ticket for notice.

**Comment by orionr** [comment]
Thanks for closing!
