### ISSUE TITLE
gloo error: error: ‘__T0’ was not declared in this scope

### ISSUE THREAD

**Issue by szm-R** [facebookarchive/caffe2#1146]
Hi everyone,
I get the error mentioned in the title when I try to build Caffe2. This is the exact error:
Caffe/caffe2/third_party/gloo/gloo/common/linux.h:26:26: error: ‘__T0’ was not declared in this scope
 const auto kPCIClass3D = PCIClassMatch{0x030200, 0xffff00};

I don't even know what this __T0 mean as I couldn't find it in the code mentioned (linux.h). Someone has encountered an error about memcpy in issue #286 again in gloo which seems to have been resolved. In the mentioned issue @pietern suggests to set USE_MPI to OFF to solve these kinds of errors but I don't know what features will I lose if I do that! As I want to try Caffe2 because it supports NNPACK and I want to see whether it gives me an inference time boost or not (I've been working with Caffe for over a year now). 

Thanks in advance for your help

**Comment by pietern** [comment]
Hi @szm2015, thanks for reporting. This is not related to #286. I have never seen this particular error before. Can you tell more about your build environment? Can you post your Caffe2 build summary that is printed after running cmake? If you're only interested in NNPACK you can disable the Gloo build by configuring CMake with `-DUSE_GLOO=OFF`.

**Comment by szm-R** [comment]
Here is my build summary:
-- ******** Summary ********
-- General:
--   Git version           : 
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   CXX flags             :  -fopenmp -std=c++11 -O2 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_OPENMP            : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done

Can you please tell me what does Gloo do in Caffe2?

**Comment by pietern** [comment]
Thanks, I'll see if I can repro with GCC 5.4.0.

Gloo is used for multi-machine training so not relevant for pure inference.

**Comment by szm-R** [comment]
Thank you for your help. I was able to build caffe2 successfully with
USE_GLOO option turned off.

**Comment by soumith** [comment]
@pietern 
Another data-point with the same error emmitted from Gloo: https://github.com/pytorch/pytorch/issues/2626

**Comment by pietern** [comment]
@soumith Any ideas what could be causing this? No clue so far...

**Comment by soumith** [comment]
the bug report https://devtalk.nvidia.com/default/topic/856954/bug-nvcc-and-gcc-4-9-3-get-into-conflict-over-unnamed-type-template-parameters/ points to the fact that it's an nvcc 7.5 bug with compilers after gcc 4.9.2 (or whatever 7.5 officially supports).

**Comment by pietern** [comment]
@soumith Thanks, this is useful.

@szm2015 Are you sure you're compiling with nvcc 8.0 in your case?

**Comment by szm-R** [comment]
Well you saw the summary I sent, I'm using Cuda 8.0

در تاریخ ۱۴ سپتامبر ۲۰۱۷ ۳:۱۵ قبل‌ازظهر، "Pieter Noordhuis" <
notifications@github.com> نوشت:

**Comment by pietern** [comment]
@szm2015 I see the summary, but there is an off chance the summary is wrong, so I want to double check.

**Comment by pietern** [comment]
The gloo bump and therefore the fix for this problem is now merged.
