### ISSUE TITLE
Request: Tutorial on training models with FP16 operators 

### ISSUE THREAD

**Issue by slothkong** [facebookarchive/caffe2#1169]
I'm just started using Caffe2. I'm very interested the on work that is being done to support FP16 training. However, there is no Documentation or code samples to be found around. If someone could at least provide a code template, I would gladly test it out until I get it working and prepare some explanation of the code that could be later used for the Tutorials Web Page site.

**Comment by lukeyeager** [comment]
The `resnet50_trainer.py` script supports fp16 (as of https://github.com/caffe2/caffe2/pull/1093). You can look through the diff in that PR to see what I had to change to enable fp16. That should help with the code samples.

**Comment by slothkong** [comment]
@agrawaldevesh
