### ISSUE TITLE
Euclidean Loss Layer

### ISSUE THREAD

**Issue by lizabelos** [facebookarchive/caffe2#1201]
Hi !

I can't find any Euclidean Loss Layer or equivalent.
My neural network output one value, and I know the value that should have been returned.

Thanks :)

**Comment by jwatte** [comment]
"loss" is simply a value, so you can use a "Sub()" operator followed by an "Abs()" operator to get absolute distance in 1D space.
For N-D space, I use:

    Sub([output, label], diff)
    Abs(diff, adiff)
    Dot([adiff, adiff], loss)

This calculates distance-squared in Euclidean space. If you want plain distance, add a square root (power of 0.5).
