### ISSUE TITLE
Share Library in Windows

### ISSUE THREAD

**Issue by WindAzure** [facebookarchive/caffe2#1217]
Is there any possible build caffe2(CUDA mode) into share library in Win10?
I'm trying to make new VS 2017 C++ project to import this library(might be .dll or .lib).
Thanks for help!

**Comment by Yangqing** [comment]
I have an ongoing effort that is about 95% there. Two issues at the moment:

(1) cmake for windows dependent libraries, which we can resolve, and
(3) cuda 9.1 and windows vs 2017 (15.5) does not work together yet. See https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/ .

I'll loop back when the cuda shared library mode works.

**Comment by Yangqing** [comment]
Combining this issue with #774.
