### ISSUE TITLE
char_rnn.py: error: argument --train_data is required

### ISSUE THREAD

**Issue by wxie2017** [facebookarchive/caffe2#1220]
When following the training
[RNNs and LSTM Networks](https://caffe2.ai/docs/RNNs-and-LSTM-networks.html)

After I have the following:
`~/work/caffe2/caffe2/python/examples# ls
char_rnn.py  lmdb_create_example.py  resnet50_trainer.py  shakespeare.txt`

I run the command
`python char_rnn.py --train-data shakespeare.txt`

The error comes like

> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
usage: char_rnn.py [-h] --train_data TRAIN_DATA [--seq_length SEQ_LENGTH]
                   [--batch_size BATCH_SIZE]
                   [--iters_to_report ITERS_TO_REPORT]
                   [--hidden_size HIDDEN_SIZE] [--gpu]
char_rnn.py: error: argument --train_data is required

What's could be the problem?

best regards,
wxie

**Comment by bddppq** [comment]
The flag is `--train_data`, with an underscore in the middle.

**Comment by wxie2017** [comment]
Yes, train_data works. I see the web also changed.

Close it.
wxie
