### ISSUE TITLE
Does the license of caffe2 suffer the same problem of react?

### ISSUE THREAD

**Issue by x10000year** [facebookarchive/caffe2#1236]
Does the license of caffe2 suffer the same problem of react? Should we use caffe2 in any serious production?

**Comment by Yangqing** [comment]
Currently we don't think there is any concern in using things in production - the license has been OK'ed by several big companies including Google and Amazon.

However I do acknowledge that there is a concern from the community about the license. I am in a discussion with our legal team regarding future steps, and can share more details if there are updates. In the meantime - yes, you should be able to use Caffe2 in production without concern.

**Comment by Yangqing** [comment]
(temporarily closing this issue, will follow up when I have updates.)

**Comment by Yangqing** [comment]
FYI - I have communicated to our legal team, and we are going to **move the Caffe2 license to Apache 2.0** in the next few days, pending the logistics that are needed for licensing.
