### ISSUE TITLE
AICamera demo failed with latest caffe2 on Android

### ISSUE THREAD

**Issue by rlegithub** [facebookarchive/caffe2#1244]
Hi,

I am trying to run the [AICamera demo app](https://github.com/bwasti) with latest caffe2 built but it failed with either USE_MOBILE_OPENGL ON or OFF. So I think the problem may not be from the new GL backend USE_MOBILE_OPENGL. Anyone has been successfully run AICamera demo app with latest caffe2 built?

Thanks

**Comment by Yangqing** [comment]
Which build error message do you have? cc @bwasti

**Comment by rlegithub** [comment]
It's not an build error. But the AI Camera app crashed with the caffe2 libs built from caffe2 tip repo while it ran well with the pre-built libs provided with the AICamera repo.

So I think there may be some compatibility between the AICamera app and latest Caffe2 tree.

So I am not sure if anyone has been successfully integrate the latest AICamera app & latest caffe2 libs?

**Comment by bddppq** [comment]
@rlegithub I just tried with current [HEAD](https://github.com/caffe2/caffe2/commit/3806419d7decff02f7a2ee3195896adcbe709cee) of caffe2, with USE_MOBILE_OPENGL turned off (`./scripts/build_android.sh -DUSE_MOBILE_OPENGL=OFF`) it works. I have updated the caffe2 version in my fork: https://github.com/bddppq/AICamera

**Comment by donchenko-oleksandr** [comment]
I got the same runtime error even with  USE_MOBILE_OPENGL turned off 
./scripts/build_android.sh -DUSE_MOBILE_OPENGL=OFF
Someone has any idea?

here is a callstack:

`SIGSEGV (signal SIGSEGV: address access protected (fault address: 0xffffffffa5524fe0))

std::function<void (void*)>::function(std::function<void (void*)> const&) functional:2410
void std::__shared_ptr<void, (__gnu_cxx::_Lock_policy)2>::reset<void, std::function<void (void*)> >(void*, std::function<void (void*)>) shared_ptr_base.h:1029
caffe2::Tensor<caffe2::CPUContext>::raw_mutable_data(caffe2::TypeMeta const&) tensor.h:520
caffe2::GivenTensorFillOp<float, caffe2::CPUContext>::GivenTensorFillOp(caffe2::OperatorDef const&, caffe2::Workspace*)
std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > caffe2::Registerer<std::string, caffe2::OperatorBase, caffe2::OperatorDef const&, caffe2::Workspace*>::DefaultCreator<caffe2::GivenTensorFillOp<float, caffe2::CPUContext> >(caffe2::OperatorDef const&, caffe2::Workspace*)
std::_Function_handler<std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (caffe2::OperatorDef const&, caffe2::Workspace*), std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (*)(caffe2::OperatorDef const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, caffe2::OperatorDef const&, caffe2::Workspace*)
caffe2::(anonymous namespace)::TryCreateOperator(std::string const&, caffe2::OperatorDef const&, caffe2::Workspace*)
caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int)
caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*)
caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*)
caffe2::CreateNet(caffe2::NetDef const&, caffe2::Workspace*)
caffe2::Workspace::RunNetOnce(caffe2::NetDef const&)
caffe2::Predictor::Predictor(caffe2::NetDef const&, caffe2::NetDef const&, caffe2::Workspace*)
::Java_facebook_f8demo_ClassifyCamera_initCaffe2(JNIEnv *, jobject, jobject) native-lib.cpp:56`

**Comment by rlegithub** [comment]
Thanks a lot for the pointer @bddppq. I will give it a try with your fork and will let you know the result.

**Comment by rlegithub** [comment]
@bddppq I have tried your fork but it does not work. Could you share which device you was able successfully run the app with latest Caffe2?

Thanks

**Comment by rlegithub** [comment]
Add a bit more debug infor here:
When running with new libs saw this in adb logcat: A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xd15003e4 in tid 8498 (AsyncTask #1)

**Comment by bddppq** [comment]
@rlegithub I was running it on a Galaxy S7. Which device did you use?

**Comment by rlegithub** [comment]
@bddppq I ran on Asus Zen. Precisely, I actually could run the app built from your fork. However, when I tried to copy the caffe2 libs from your fork to replace the libs in the original AICamera repo then the app failed! Did you do anything special with your fork helped it work?

**Comment by bddppq** [comment]
@rlegithub You need to not only copy the new libs files (both the caffe2 libs and protobuf libs) but also the header files.
Actually let's merge my fork to the main repo, we need the newer version of caffe2 for another use case anyway.

**Comment by rlegithub** [comment]
Ah that explains it. Yeah, I think if your fork is stable & good, we should merge it to the main.

Thanks,

**Comment by bddppq** [comment]
@rlegithub It has been merged to the main repo now. Thanks to @bwasti .
