### ISSUE TITLE
caffe2 build issue on MacOS v10.12.16

### ISSUE THREAD

**Issue by jhuihe** [facebookarchive/caffe2#1246]
Hi,

I am building the caffe2 on MacOS following the guideline of https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile, I have tried with both Anaconda and Homebrew path, but both got below same issue:

[  1%] Built target gmock
[  2%] Built target gmock_main
[  2%] Built target gtest
[  3%] Built target gtest_main
[  3%] Linking CXX shared library libbenchmark.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [third_party/benchmark/src/libbenchmark.dylib] Abort trap: 6
make[2]: *** Deleting file `third_party/benchmark/src/libbenchmark.dylib'
make[1]: *** [third_party/benchmark/src/CMakeFiles/benchmark.dir/all] Error 2
make: *** [all] Error 2

would you help to look at it? thanks in advance.

Regards,
jhuihe

**Comment by Yangqing** [comment]
A quick search shows that it might be an Xcode issue:

https://forums.developer.apple.com/thread/87097
https://trac.macports.org/ticket/54875

So it might be a mac issue. Maybe try downgrading your Xcode?
