### ISSUE TITLE
How to run Caffe2 without Cudnn?

### ISSUE THREAD

**Issue by abhi1212** [facebookarchive/caffe2#1273]

**Comment by lukeyeager** [comment]
See https://github.com/caffe2/caffe2/issues/887

**Comment by abhi1212** [comment]
Hey Luke,
Can you please tell me how* can we change the Gemm Batch sizes in the
Cublas GemmBatched Api* Caffe 2 uses.
I have been stuck on this issue for a long time and your help would be much
appreciated.

Thanks and Regards
Abhishek Nikam
​
