### ISSUE TITLE
build GPU failed on windows with visual studio 2015

### ISSUE THREAD

**Issue by aligoglos** [facebookarchive/caffe2#1275]
i can build caffe2 CPU but when want build GPU this error occur :
```
2>D:/Software Instaltion/caffe2\caffe2/utils/GpuBitonicSort.cuh(45): error : expected an identifier
2>            detected during:
2>              instantiation of "void caffe2::bitonicSort<Comparator,K,V,Power2SortSize,ThreadsPerBlock>(K *, V *, const Comparator &) [with Comparator=caffe2::LTComp<float, caffe2::TIndex>, K=float, V=caffe2::TIndex, Power2SortSize=4096, ThreadsPerBlock=256]"
2>  D:/Software Instaltion/caffe2\caffe2/operators/top_k_heap_selection.cuh(213): here
2>              instantiation of "void caffe2::Heap<K, V, ThreadsPerBlock, HeapSize, Dir>::reduceHeaps() [with K=float, V=caffe2::TIndex, ThreadsPerBlock=256, HeapSize=512, Dir=true]"
2>  D:/Software Instaltion/caffe2\caffe2/operators/top_k_heap_selection.cuh(269): here
2>              instantiation of "void caffe2::selectRowsViaHeap<V,IndexType,OutIndexType,ThreadsPerBlock,HeapSize,Dir>(const V *, V *, OutIndexType *, V, IndexType, int, int, int) [with V=float, IndexType=caffe2::TIndex, OutIndexType=caffe2::TIndex, ThreadsPerBlock=256, HeapSize=512, Dir=true]"
2>  D:/Software Instaltion/caffe2/caffe2/operators/top_k.cu(105): here
```
on this lines in GpuBitonicSort.cuh :
```
 static_assert(math::integerIsPowerOf2(Power2SortSize),"sort size must be power of 2");
 static_assert(math::integerIsPowerOf2(ThreadsPerBlock),"threads in block must be power of 2");
```
how can fixed that ?

**Comment by mattm401** [comment]
Were you able to find a solution?

**Comment by mattm401** [comment]
Looks like this has been patched in some future version of Caffe2 as you can see from this post: https://github.com/caffe2/caffe2/issues/997

I am using v0.8.1 and updated these lines to:

  static_assert(math::integerIsPowerOf2(
                std::integral_constant<int, Power2SortSize>()),
                "sort size must be power of 2");
  static_assert(math::integerIsPowerOf2(
                std::integral_constant<int, ThreadsPerBlock>()),
                "threads in block must be power of 2");

**Comment by aligoglos** [comment]
hi Matthew i cant solve this problem.
i also test your solution "std::integral_constant " but not work for me.

**Comment by mattm401** [comment]
Depending on your version of Caffe2 and Windows (I'm running 10), you might need to trace through this PR thread https://github.com/caffe2/caffe2/pull/1042

I made the suggested edits to recurrent_op_cudnn.cc, logging.cc, Cuda.cmake, logging_is_google_glog.h, top_k_radix_selection.cuh, GpuBitonicSort.cuh, and math.h and was able to successfully build. The solution above got me to a different set of errors, so just looking through the various edits and applying them seemed to work things out.

**Comment by mattm401** [comment]
I am, however, now getting an a new error when trying to use the .pyd files

>python char_rnn.py --train_data shakespeare.txt --gpu
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: DLL load failed: The specified module could not be found.
CRITICAL:root:Cannot load caffe2.python. Error: DLL load failed: The specified module could not be found.

My previous CPU only .pyd had worked fine.

**Comment by aligoglos** [comment]
hi Matthew, i apply changes according Bug fixes
<https://github.com/caffe2/caffe2/pull/1042/files> and recompile GPU but
now this error occur :

*  too few arguments for class template "std::integral_constant"*

i replace
Power2SortSize
to
std::integral_constant<int, Power2SortSize>::value
std::integral_constant<int, Power2SortSize>()

both have same error.

**Comment by mattm401** [comment]
Hmm, not sure. I'd check to make sure that you made all the correct updates; however, even if you get it to compile it might not work... the resulting python bindings in my case aren't working.

**Comment by mattm401** [comment]
I was able to follow the instructions using v0.8.1 here and compile:
http://research.wmz.ninja/articles/2017/05/build-caffe2-on-windows-10-gpu.html

The error mentioned above appears to be, in my case, related to not being able to find: cudnn64_5.dll
After copying this file into my caffe2\build\  folder I was able to run the example code (char_rnn.py) using the GPU.

That being said, I am still having issues getting the build to work with opencv, which I am going to look into next.

**Comment by mattm401** [comment]
I figured out why OpenCV integration was failing for me, the window binaries for OpenCV 3.0 didn't have a build for Visual Studio 15 (vc14) at the time they were released; I tried to rebuild through cmake, but it was taking a very long time. I ended up just installing OpenCV 3.3, which resolved the issue immediately.

So what looks like worked for me:

1. Clone Caffe2 and switch/checkout the release tagged 0.8.1
2. Follow: https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile and http://research.wmz.ninja/articles/2017/05/build-caffe2-on-windows-10-gpu.html
3. Test that the CPU version is working before trying to enable GPU; fix the bugs that might pop up here.
4. Apply patches https://github.com/caffe2/caffe2/pull/1042; set GPU Options, compile, test, debug.
5. If you get a DLL error, ensure access to the appropriate CUDA DLLs (e.g., cudnn64_5.dll in my case since as I am using v8)
6. Install windows binaries for OpenCV 3.3, enable OpenCV options, and compile.

**Comment by aligoglos** [comment]
thanks all. after i apply all changes in [#1042](https://github.com/caffe2/caffe2/pull/1042) i can successfully compile caffe2 in static library. but when i want use caffe lib to my project this runtime error occur :
`[F operator.h:644] You might have made a build error: the Caffe2 library does not seem to be linked with whole-static library option. To do so, use -Wl,-force_load (clang) or -Wl,--whole-archive (gcc) to link the Caffe2 library.`

i test DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS but not solved.

**Comment by mattm401** [comment]
Hmm, I have not seen that particular error before and I am still struggling with OpenCV support as well.
