### ISSUE TITLE
why use .h not .cc  in some files ' extension

### ISSUE THREAD

**Issue by ChenZhaobin** [facebookarchive/caffe2#1278]
such as  conv_op_impl.h  why not  conv_op_impl.cc  since it include  conv_op.h and implements function of 
 RunOnDeviceWithOrderNCHW()   and  RunOnDeviceWithOrderNHWC

**Comment by harrysummer** [comment]
This would make the definition inline, and would achieve better performance.

**Comment by yinghai** [comment]
Because it's templated implementation and it has to included. So to tell the difference, we have `_impl.h` instead of shoving everything in `.h`.
