### ISSUE TITLE
MPI_Comm_free() was called after MPI_FINALIZE was invoked

### ISSUE THREAD

**Issue by lukeyeager** [facebookarchive/caffe2#1283]
I consistently get this error when a multi-node training job (with MPI rendezvous) tries to shut down.
```
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```
Sadly, this means my `nvprof` profiles end up empty.

**Comment by lukeyeager** [comment]
If I comment out [this line](https://github.com/caffe2/caffe2/blob/a07786cb8a/caffe2/contrib/gloo/common_world_ops.h#L77), I get a warning from MPI instead:
```
mpiexec has exited due to process rank 0 with PID 16 on node <node> exiting improperly.
```
And my profiles are generated properly. That unblocks me for now.

**Comment by Applepleple** [comment]
Hi Luke,

I meet the same error when I tried to launch caffe2 distribution with mpi. I saw the pull request you created is closed. Is there gonna be any official fix?

Thanks

**Comment by lukeyeager** [comment]
Fixed in https://github.com/facebookincubator/gloo/pull/94 and https://github.com/caffe2/caffe2/pull/1295.
