### ISSUE TITLE
Linking to Caffe2/protobuf in Visual Studio C++ project

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1291]
I'm trying to use Caffe2 in a C++ application. The tutorial for setting up Visual Studio misses out a lot of steps, but I've managed to get it working: I can import a trained squeezenet and run it on images passed in from OpenCV. 
Now I'm trying to run my own trained net, however it fails when I try to initialise a predictor using the init and predict NetDefs. I've tried to follow through what's happening, and I've narrowed down the failure to a CAFFE_ENFORCE in the CreateOperator function.
I'm assuming this means there is a problem with one of the operators in my net, so I want to list them. I can access the operators through NetDef.op(index), however when I call OperatorDef.Name() or OperatorDef.Type() I get the following unresolved external symbol errors:
`Error	LNK2001	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::internal::GetEmptyStringAlreadyInited(void)" (__imp_?GetEmptyStringAlreadyInited@internal@protobuf@google@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	`
`Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::internal::ArenaStringPtr::GetNoArena(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *)const " (__imp_?GetNoArena@ArenaStringPtr@internal@protobuf@google@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBV56@@Z)`
Additionally, if I try to call NetDef.op_size() I receive the following:
`Error	LNK2001	unresolved external symbol "__declspec(dllimport) protected: int __cdecl google::protobuf::internal::RepeatedPtrFieldBase::size(void)const " (__imp_?size@RepeatedPtrFieldBase@internal@protobuf@google@@IEBAHXZ)`
I have included Caffe2_CPU.lib, Caffe2_GPU.lib, libprotobuf.lib, libprotobuf-lite.lib, libprotoc.lib, and Caffe2_PROTO.lib in the project's additional dependencies, and these seem to be referenced properly as other proto stuff can be resolved. Visual Studio will even show me the definitions of the supposedly unresolved functions.

**Comment by ghost** [comment]
It turns out the unresolved symbol errors were due to my header file having the line '#define PROTOBUF_USE_DLLS 1' at the top.

**Comment by ghost** [comment]
How can I view the details of a caffe2 EnforceNotMet exception?

**Comment by zzz197** [comment]
__declspec(dllimport)    this macro may be defined differently  between PROTOBUF project and Caffe2 project, thus the function definitions are different.  Or try to build static Caffe2_CPU.lib and link it to your project？

**Comment by pietern** [comment]
Closing since this was solved.

**Comment by Kandarp2516** [comment]
@m00nkeh you mentioned in first comment that there is a lot missing in the Visual Studio tutorial. Can you please suggest what all I need to do? Any references will be useful. I think I can successfully include headers from caffe2 but I get unresolved external symbol error LNK2019 when I try to use anything from Caffe2. I think I need to add Caffe2 and ProtoBuf project in visual studio solution for my project and build them, is that right? Is there any alternative to this?
