### ISSUE TITLE
Compatibility with old Caffe

### ISSUE THREAD

**Issue by grib0ed0v** [facebookarchive/caffe2#13]
Hi @Yangqing , 
Are you planning to add Caffe2 -> Caffe translator which allows us to convert Caffe2 description & snapshots to old Caffe .prototxt & .caffemodel?

**Comment by Yangqing** [comment]
Hi @AlexGruzdev - right now there is no plan for backward port yet, since caffe2 is intended to be a superset of Caffe (e.g. different storage orders). This being said, it would be great to hear what features of caffe that you like best / need most, so we can try to prioritize the caffe2 development :)

**Comment by cbalint13** [comment]
@Yangqing ,

Permit to ask if by a chance the new "blob/storage" layout would be compatible with OpenCV n-dim cv::Mat internal blob:
- See at "Detailed Description " within this page: http://docs.opencv.org/trunk/d3/d63/classcv_1_1Mat.html#gsc.tab=0

**Comment by Yangqing** [comment]
Hi @cbalint13 - Yes, the underlying binary array should be compatible with cv::Mat as long as the cv::Mat stores the data contiguously.

**Comment by bhack** [comment]
@Yangqing And for UMAT?

**Comment by Yangqing** [comment]
@bhack I have not used UMAT myself before, so I cannot say for sure. However, Caffe2 and Caffe uses a very simple memory assumption: it is a C-contiguous chunk of memory with the dimensionality data associated to it. So any class that wraps around a C-contiguous memory would be compatible here - I guess this will be the case for UMAT. To do so for a tensor object t, you can obtain the raw pointer using `t.data()` and its dimension using `t.dims()`.

(Note that I have a slow re-factoring coming up that will make the tensor class data type independent, so in the near future one might need to use `t.data<float>()` for a float pointer, or `t.raw_data()` for a raw `void*` pointer.)

**Comment by bhack** [comment]
@Yangqing I don't know if make sense in caffe2 to have a transparent cpu/gpu tensor as Umat in Opencv trasparent API. What do you think?

**Comment by Yangqing** [comment]
I've actually been thinking about that - the same idea originated from Caffe where we have a syncedmem that hosts both cpu and gpu. It has some advantages (e.g. one does not need to explicitly do memcpy), but in caffe what eventually happens is that everything runs either on cpu or gpu, and for cases where an implicit copy is involved, either there will be a performance cut or the copy can be done manually. So right now I was doing explicit separations, although one can do simple copy like:

// say we have Tensor<CUDAContext> t_cuda
// we can get it to CPU with
Tensor<CPUContext> t_cpu(t_cuda)

Does that make sense? There seem to be advantages and disadvantages for both approaches (and even caffe and caffe2 differ in this sense), so I haven't got a crystal answer either.

**Comment by Yangqing** [comment]
(One disadvantage of Caffe's syncedmem is that it does not scale very well to more than 2 contexts: we hard-coded the CPU and GPU case, and even that was creating some headache for us with all the `#ifdef`s flying around. For example, adding an OpenCL device would potentially be a bit intrusive in the Caffe case. Not sure how OpenCV solves this, though)

**Comment by bhack** [comment]
@naibaf7 Do you have a plan to transparently design a GPU/CPU  blob in your caffe(1) device abstraction proposal?

**Comment by bhack** [comment]
@Yangqing a related discussion started recently on caffe(1) at https://github.com/BVLC/caffe/pull/3138

**Comment by naibaf7** [comment]
@bhack 
Actually yes, through a common polymorphic wrapper (dev_ptr) on top of CPU, CUDA and OpenCL memory. Fragments of it are already in my repository.

So it will be Blobs/Tensors on top of multidevice (autocopy) Syncedmem featuring dev_ptr pseudopointers.

**Comment by bhack** [comment]
@Yangqing I think that what @naibaf7 is reasoning and starting to develop on device abstraction could also be useful on caffe2. <offtopic> Generally I don't know anymore where new development need to be addressed. @BVLC public activity on Caffe1 is very low, project seems in maintanance / bug fix only mode. At the same time I don't see any BVLC member active in caffe2 redesign.</offtopic>

**Comment by bhack** [comment]
We need also to think about what is the concept of copy between gpu-cpu (or computing devices) in the HSA/HUMA paradigm.

**Comment by Yangqing** [comment]
@naibaf7 Fabian, could you point me to your syncedmem code? I am quite interested.

**Comment by naibaf7** [comment]
@Yangqing 
It's not very nicely wrapped up at the moment - device abstraction for synced mem and GPU math functions is still in progress - the theory and plan stands though and I can walk you through some details if you are interested.
I'm currently doing some research with HHMI Janelia on specific networks, so I don't know when it will be finished (can't give time estimates).

**Comment by bhack** [comment]
@naibaf7 @Yangqing Can we discuss this ideas in a new ticket? Can you open a new one with some short preamble?
