### ISSUE TITLE
Failed to compile with CUDNN v5.1 (master branch)

### ISSUE THREAD

**Issue by jiayiliu** [facebookarchive/caffe2#1302]
Hi  
I got the following error when run `make`.

```
..../caffe2/caffe2/operators/pool_op_cudnn.cu(386): error: identifier "CUDNN_POOLING_MAX_DETERMINISTIC" is undefined
```

The problem can be solved by updating my CUDNN to v6.0.
Please either change the documentation for the dependency or change the pool_op_cudnn.cu to remove the dependency.

Thanks,
Jason

------------
System info:
Ubuntu 14.10
CUDA 8.0
CUDNN 5.1
Pyhton 2.7

**Comment by pietern** [comment]
cc @slayton58

**Comment by pietern** [comment]
I've seen this as well. I think there is no reason to continue support for CuDNN < v6, seeing as v6 has been out for a year (?) and v7 has been released recently as well.

**Comment by pietern** [comment]
I opened #1607 to gauge interest in reviving support (though I recommend people use a newer version).

**Comment by Yangqing** [comment]
Fixed by https://github.com/caffe2/caffe2/commit/55f6fea3a93a4e9e1d1256e1ec51afa1d4ce6f70 although we might not support cudnn 5.1 in the long term, so you might want to consider updating cudnn.
