### ISSUE TITLE
Which IDE or tools  have you used to create this project ?

### ISSUE THREAD

**Issue by ChenZhaobin** [facebookarchive/caffe2#1306]
Could you provide me some  information  about how the  project was first created including  some basic files?Anyway when it became opensource,it is too complex to follow with.it will be very appreciated

**Comment by pietern** [comment]
There is no preferred IDE for this project.

Most people I know who work on Caffe2 do so with a simple editor and terminal.

**Comment by galv** [comment]
For anyone wondering about the daunting task of jumping into the codebase as an outsider, I'll share some of my personal experience.

I use emacs. Installing dumb-jump mode made my productivity multiply by ~5 when I was starting off as it allowed me to jump to the definitions of various symbols very quickly.

**Comment by ChenZhaobin** [comment]
@pietern   I changed some codes,such as including headers' path   ,now ,I can build caffe2 from scratch using vs2015.
It's more convinient to use vs2015 for learning purpose ,because we can easily manage packages(protobuf ,glog,openblas) ,debuging,using IntelliSense ,and look into how functions implemented.
![image](https://user-images.githubusercontent.com/16506634/31654256-061c9ca6-b358-11e7-8811-adab15012a6f.png)
![image](https://user-images.githubusercontent.com/16506634/31654356-6e71e5c2-b358-11e7-8549-f4753e585ef4.png)
