### ISSUE TITLE
As of now, what can we expect from caffe2 on mobile devices?

### ISSUE THREAD

**Issue by wswfc** [facebookarchive/caffe2#1312]
Does caffe2 support running on ARM cpu?  What about mobile GPU support, such as Mali GPU, via the openCL? Seems I cannot find a doc with more detailed info. Would appreciate such. Thanks.

**Comment by sasikiran** [comment]
On iOS, Metal APIs are/will be supported. On Android, Qualcomm SNPE.  See here - https://github.com/caffe2/caffe2/issues/283

**Comment by wswfc** [comment]
Thanks! Looking forward to more back-end support!

**Comment by lamia482** [comment]
Hi, @wswfc   have you succeeded in running caffe2 on Android device with MALI GPUs activated?

**Comment by wswfc** [comment]
@laMia482 Nope.  Still CPU only...

**Comment by lamia482** [comment]
@wswfc  Ooooooops, I've made it but running caffe2 with OpenGL on Android device(CUN-AL00) seems takes more times than just CPU...

**Comment by twerdster** [comment]
@laMia482 can you give pointers on how to get it to run using OpenGL? I have compiled the opengl caffe2 libbrary and can see that opengl is being initialized but it fails to run. What network did you use? What code did you add to native-lib.cpp?

**Comment by lamia482** [comment]
@twerdster see my [repo](https://github.com/laMia482/caffe2_android.git), not tested for latestet caffe2
