### ISSUE TITLE
Error compiling caffe2_gpu under Visual Studio 2017

### ISSUE THREAD

**Issue by WinfredHuang** [facebookarchive/caffe2#1322]
My environment: Windows 10, VS 2017, CUDA 9.0.176, cuDNN 7. NVIDIA GTX850M, driver version 386.XX.
Below is the output when compiling caffe2_gpu: 
```
1>Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/core/Release/caffe2_gpu_generated_context_gpu.cu.obj
1>-- Removing E:/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/core/Release/caffe2_gpu_generated_context_gpu.cu.obj
1>"D:/Program Files/CMake/bin/cmake.exe" -E remove E:/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/core/Release/caffe2_gpu_generated_context_gpu.cu.obj
1>-- Generating dependency file: E:/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/core/caffe2_gpu_generated_context_gpu.cu.obj.NVCC-depend
1>D:/NVIDIA/CUDA/bin/nvcc.exe -M -D__CUDACC__ E:/caffe2/caffe2/core/context_gpu.cu -o E:/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/core/caffe2_gpu_generated_context_gpu.cu.obj.NVCC-depend -ccbin "D:/Microsoft Visual Studio/2017/Enterprise/VC/bin" -m64 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DGFLAGS_IS_A_DLL=1 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=useless_using_declaration -Xcudafe --diag_suppress=set_but_not_used -Xcompiler -MT -Xcompiler -openmp --expt-relaxed-constexpr -DNVCC -ID:/NVIDIA/CUDA/include -IE:/caffe2/build -IE:/caffe2 -IE:/caffe2/third_party/cub -IE:/caffe2/third_party/pybind11/include -ID:/Anaconda2/lib/site-packages/numpy/core/include -ID:/Anaconda2/include -IE:/caffe2/third_party/eigen -ID:/opencv/build/include/opencv -ID:/opencv/build/include -ID:/Anaconda2/Library/include -ID:/Anaconda2/Library/Include -IE:/caffe2/third_party/protobuf/src
1>CMake Error at caffe2_gpu_generated_context_gpu.cu.obj.Release.cmake:215 (message):
1>  Error generating
1>  E:/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/core/Release/caffe2_gpu_generated_context_gpu.cu.obj
```
Since I can't switch to VS 2015, it's not possible to use CUDA 8.0+cuDNN 6 as a workaround. 
I have also checked Cuda.cmake to ensure it has CUDA 9.0 support. 
Please help me since using GPU is the only way to run most projects in actual use.

**Comment by zzz197** [comment]
try update your  cuh headers?

**Comment by WinfredHuang** [comment]
I'm using the latest source code. Is there any additional modification I should do?

**Comment by WinfredHuang** [comment]
Well...I have followed the steps on #1042 . Still can't solve the problem. @zzz197 @willyd 
I have updated the output information to cover more details.
Also, I tried switching to CUDA 8.0+cuDNN 6, but with no luck.

**Comment by WinfredHuang** [comment]
I have traced the problem to `caffe2_gpu_generated_context_gpu.cu.obj.cmake.pre-gen`, about Line 67:
`set(CUDA_HOST_COMPILER "$(VCInstallDir)bin")`
which will point to a non-existent path. 
I think this variable should point to the C++ compiler path, which should possibly be (under x64 arch, may vary depending on version):
`D:\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x64`
Since Visual Studio 2017 has changed the path of `cl.exe`, I don't know if there are more to be modified in the entire repository. I hope if there are someone who can help me and potentially more people to make Caffe2 work on Visual Studio 2017. @willyd @pietern

**Comment by zzz197** [comment]
I've uploaded my caffe2 .sln project to my repo. The project is a alpha version, some configurations haven't been finished yet. The path of header files and libs are put to a common upper folder.  
  Have a try if you are interested.

**Comment by WinfredHuang** [comment]
哎呦喂。会说汉语啊。不错噢。
OK. I've set the CUDA_HOST_COMPILER on CMake. Now this problem is solved. 
However, compilation still can't complete due to other problems. I think it's better to open up another issue.

**Comment by WinfredHuang** [comment]
Well...I doubt that the problem may have something to do with Visual Studio 2017 version. CUDA 9.0 may not support VS2017 with updates (Version 15.1, 15.2,...etc.), only RTM version is fully supported. However, whether it will affect compilation is still unknown. @zzz197 你用的什么版本？如果你有兴趣的话可以私聊吗？@pietern @willyd It may be a bit annoying to "at" you, but I'm very concerned about it, and there may be many more people who're expecting a solution, though they haven't addressed their frustration yet.

**Comment by willyd** [comment]
@AurusHuang Sorry can't help you much here, I haven't tried CUDA 9 and Visual Studio 17 yet. The error message above is not so helpful... I looks like it was generated while trying to compile some cuda file. Usually if you dig a little more in your build log you can find the "real" error message.

I don't have time to dig into this, but keep watching #1042 I will update the PR whenever I go back to making Caffe2 with GPU working on Windows.

**Comment by WinfredHuang** [comment]
Thank you for your kind response. Your comment is exactly what I'm doing. I'll dig it deeper to see where the real problem lies. I'll report my findings as soon as possible.

**Comment by WinfredHuang** [comment]
I think one of the errorneous codes that prevent me from compiling is this:

`template <typename T>`
`inline void MakeStringInternal(std::stringstream& ss, const T& t) {`
  `ss << t;`
`}`

It is located in `logging.h`. Sometimes an argument of type `vector` will be passed, which has no overloaded operator of "<<". 
But since I don't know if it is what it should be or it is an error, so I can't modify the source code myself. @willyd

**Comment by zzz197** [comment]
I'm building on win10 cuda9 176. cudnn 7.  vs2017 15.4.1  with Gflgas.  without glog.   CUDNN_MAJOR and CUDNN_VERSION_MIN macros may produce errors in relevant .cpps.

**Comment by selimarikan** [comment]
I had the same problem and changed the `CUDA_HOST_COMPILER` parameter to `C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe` in the `\caffe2\build\CMakeCache.txt` file.

**Comment by YeLyu-whu** [comment]
On windows10 vs2015 with cudnnv6.0, cuda8.0, I can compile project caffe2, but I cannot compile caffe2_gpu. When I trace the problem, I find the following codes( in file: caffe2/core/logging.h ) result in the error, making .cu file unable to be compiled.
`template <typename T>
inline void MakeStringInternal(std::stringstream& ss, const T& t) 
{
	ss << t;
}`
this code results error:
 `no operator "<<" matches these operands
`
If I delete `ss<<t`, then .cu file can be compiled.
I do not know what is wrong with this code. If I build a cuda program myself, using CUDA C/C++ as item type, this operand has no problem at all, even for template variable.

**Comment by Yangqing** [comment]
Seems that cuda 9.1 and msvc 2017 do not work well together; for the rest of the windows build updates, please kindly check #774 for updates. Recent PR #1793 should make us closer to build everything properly.

**Comment by Yangqing** [comment]
(closing this to reduce duplication)
