### ISSUE TITLE
compilation error with observer

### ISSUE THREAD

**Issue by fbadaud** [facebookarchive/caffe2#1324]
good morning ,  
I pull caffe2 this morning  and try to recompile it but I got following issue  relative to perf_observer.cc, I might missing something , can you help ?

 thanks in advance

 here is the error:
###############################################
[ 89%] Built target proto_utils_test
make[3]: Entering directory '/home/b2bot/Project/caffe2/caffe2/build'
Scanning dependencies of target Caffe2_CPU_OBSERVER
make[3]: Leaving directory '/home/b2bot/Project/caffe2/caffe2/build'
make[3]: Entering directory '/home/b2bot/Project/caffe2/caffe2/build'
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/net_observer_reporter_print.cc.o
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/observer_config.cc.o
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/perf_observer.cc.o
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc: In member function ‘virtual bool caffe2::PerfNetObserver::Start()’:
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:54:15: error: ‘class caffe2::OperatorBase’ has no member named ‘AddObserver’
           op->AddObserver(caffe2::make_unique<PerfOperatorObserver>(op, this));
               ^
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc: In member function ‘virtual bool caffe2::PerfNetObserver::Stop()’:
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:77:58: error: no matching function for call to ‘caffe2::OperatorBase::GetObserver(caffe2::ObserverBase<caffe2::NetBase>*&) const’
                          op->GetObserver(observerMap_[op]))
                                                          ^
In file included from /home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:7:0:
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:237:31: note: candidate: caffe2::ObserverBase<caffe2::OperatorBase>* caffe2::OperatorBase::GetObserver()
   ObserverBase<OperatorBase>* GetObserver() {
                               ^
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:237:31: note:   candidate expects 0 arguments, 1 provided
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:241:37: note: candidate: const caffe2::ObserverBase<caffe2::OperatorBase>* caffe2::OperatorBase::GetObserver() const
   const ObserverBase<OperatorBase>* GetObserver() const {
                                     ^
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:241:37: note:   candidate expects 0 arguments, 1 provided
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:87:42: error: no matching function for call to ‘caffe2::OperatorBase::RemoveObserver(caffe2::ObserverBase<caffe2::NetBase>*&)’
       op->RemoveObserver(observerMap_[op]);
                                          ^
In file included from /home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:7:0:
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:192:8: note: candidate: void caffe2::OperatorBase::RemoveObserver()
   void RemoveObserver() {
        ^
89%] Built target proto_utils_test
make[3]: Entering directory '/home/b2bot/Project/caffe2/caffe2/build'
Scanning dependencies of target Caffe2_CPU_OBSERVER
make[3]: Leaving directory '/home/b2bot/Project/caffe2/caffe2/build'
make[3]: Entering directory '/home/b2bot/Project/caffe2/caffe2/build'
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/net_observer_reporter_print.cc.o
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/observer_config.cc.o
[ 89%] Building CXX object caffe2/share/contrib/CMakeFiles/Caffe2_CPU_OBSERVER.dir/observers/perf_observer.cc.o
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc: In member function ‘virtual bool caffe2::PerfNetObserver::Start()’:
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:54:15: error: ‘class caffe2::OperatorBase’ has no member named ‘AddObserver’
           op->AddObserver(caffe2::make_unique<PerfOperatorObserver>(op, this));
               ^
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc: In member function ‘virtual bool caffe2::PerfNetObserver::Stop()’:
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:77:58: error: no matching function for call to ‘caffe2::OperatorBase::GetObserver(caffe2::ObserverBase<caffe2::NetBase>*&) const’
                          op->GetObserver(observerMap_[op]))
                                                          ^
In file included from /home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:7:0:
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:237:31: note: candidate: caffe2::ObserverBase<caffe2::OperatorBase>* caffe2::OperatorBase::GetObserver()
   ObserverBase<OperatorBase>* GetObserver() {
                               ^
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:237:31: note:   candidate expects 0 arguments, 1 provided
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:241:37: note: candidate: const caffe2::ObserverBase<caffe2::OperatorBase>* caffe2::OperatorBase::GetObserver() const
   const ObserverBase<OperatorBase>* GetObserver() const {
                                     ^
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:241:37: note:   candidate expects 0 arguments, 1 provided
/home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:87:42: error: no matching function for call to ‘caffe2::OperatorBase::RemoveObserver(caffe2::ObserverBase<caffe2::NetBase>*&)’
       op->RemoveObserver(observerMap_[op]);
                                          ^
In file included from /home/b2bot/Project/caffe2/caffe2/caffe2/share/contrib/observers/perf_observer.cc:7:0:
/home/b2bot/Project/caffe2/caffe2/caffe2/core/operator.h:192:8: note: candidate: void caffe2::OperatorBase::RemoveObserver()
   void RemoveObserver() {

**Comment by sarahRochat** [comment]
Hi!
I'm experiencing exactly the same error. 
Thank you in advance for your help!

**Comment by pietern** [comment]
This was fixed by this revert commit 3h ago: 4479d781cfb88ebf83a0b89ccf5588116b426843

**Comment by fbadaud** [comment]
thanks Pietern for your prompt support, I pull again the repository this morning 10/13/17 and build then  python loading of "core"  is OK
