### ISSUE TITLE
Failure during installing Caffe2 on macOS

### ISSUE THREAD

**Issue by kostyaby** [facebookarchive/caffe2#133]
Hey there!

I faced some problems while installing Caffe2 on macOS. I'd be grateful if you could help me to resolve them.

The compilation asserts in the very beginning with the following error:

```
[  1%] Performing build step for 'nccl_external'
ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
ls: /usr/local/cuda/lib64/libcudart.so.*: No such file or directory
Compiling src/core.cu                         > /Users/kostya_by/Programming/aimatter/caffe2/third_party/nccl/build/obj/core.o
src/core.cu(717): error: expected an expression

src/core.cu(717): error: expected an expression

2 errors detected in the compilation of "/var/folders/n6/s4c7zx0s5f3fflgh_dl7qtc80000gn/T//tmpxft_000022bd_00000000-11_core.compute_52.cpp1.ii".
make[3]: *** [/Users/kostya_by/Programming/aimatter/caffe2/third_party/nccl/build/obj/core.o] Error 2
make[2]: *** [nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
make[1]: *** [CMakeFiles/nccl_external.dir/all] Error 2
make: *** [all] Error 2
```

I checked my `/usr/local/cuda` directory. There is no `lib64` subdirectory there, only `lib`. And there is no entity matching the `libcudart.so.*` pattern, only `libcudart.8.0.dylib`, `libcudart.dylib` and `libcudart_static.a`.

I have the following software installed on my Mac: 

macOS version: 10.12.3
CUDA driver version: 8.0.53

Thanks!

**Comment by Yangqing** [comment]
Ah, so right now we haven't tried building on a Mac with cuda support yet, and you can set -DUSE_CUDA=OFF to turn off the whole thing. NCCL does not support build on mac yet, I have a pending PR here:

https://github.com/NVIDIA/nccl/pull/62

**Comment by Yangqing** [comment]
Feel free to reopen this if things does not work :)

**Comment by kostyaby** [comment]
@Yangqing Just wanted to confirm, that it worked! Thanks!
