### ISSUE TITLE
libcaffe2_cpu.so not found

### ISSUE THREAD

**Issue by paul-mesnilgrente** [facebookarchive/caffe2#1332]
Hi everyone,

I have built caffe2 with cuda-9 and cudnn-7. It went well. However when I try to compile a project that was compiling before, it prints me this error: `libCaffe2_GPU.so not found`.

And effectively, when I do `sudo ldconfig -p | grep caffe`, it is printing:

```text
libcaffe2_gpu.so (libc6,x86-64) => /usr/local/lib/libcaffe2_gpu.so
libcaffe2.so (libc6,x86-64) => /usr/local/lib/libcaffe2.so
```

I watched in the flags available for a "CPU" module in the `CMakeLists.txt` of caffe but I have not found anything apart from "CPU_FLAGS". So my question is: Is it the project that I try to compile who has a problem or it is the compilation of Caffe2 that is missing a library ?

Thank you very much.

**Comment by paul-mesnilgrente** [comment]
I saw in another issue that I should try to clean and recompile. So I did:
```bash
sudo make clean
make -j7
cd build
sudo make install
sudo ldconfig
```

But I still don't have `libcaffe2_cpu.so`

**Comment by galv** [comment]
In #1300, the name of the .so file was changed from libcaffe2_CPU.so to libcaffe2.so

It could have been better publicized, but alas.

**Comment by paul-mesnilgrente** [comment]
Okay I have changed the name of the library in my project to match the new name. Notice that `libCaffe2_GPU.so` has been changed into `libcaffe2_gpu.so` too. To summarize:

- `libCaffe2_GPU.so` -> `libcaffe2_gpu.so`
- `libCaffe2_CPU.so` -> `libcaffe2.so`

Thank you very much.
