### ISSUE TITLE
What is the relationship between MPI GLOO Rendezvous, file_store_path, and Redis Rendezvous?

### ISSUE THREAD

**Issue by shijieheping** [facebookarchive/caffe2#1339]
This questions is about how to use MPI GLOO in Caffe2. I bulit it with Intel MPI and without Redis.
Again for my following command line, "--file_store_path" seems to be mandatory, as my cluster training cannot start without it.

I know file_store_path is 
"alternative to Redis, (NFS) path to shared directory to use for rendezvous temp files to coordinate between each shard/node"

Is it used for cluster kickstart or synchronization even for my MPI build? If so, then what the light-weight MPI wrapper module is compiled for? Only for raising python process in cluster simultaneously?
I know GLOO MPI is not for allreduce and bcast communication. But why I still need file_store_path, even I've already have MPI_WORLD context?
Did I used wrong parameter stack?

> bs=64 if=mlx5_1 tr=ibverbs traindata="/lustre/cfdata/imagenet_cars_boats_train" testdata="/lustre/cfdata/imagenet_cars_boats_val" filestore="/lustre/tmp"; mpirun -host g1 -n 1 python resnet50_trainer.py --train_data $traindata --test_data $testdata --num_gpus 2 --batch_size $bs --num_shards=3 --shard_id=0 --run_id=1234 --file_store_path $filestore --distributed_transport=$tr --distributed_interface=$if 

Sorry to ask so many issues in a row, I just want to make it clear for Caffe2 users.
Thanks

**Comment by thyeros** [comment]
the latest caffe2+gloo seems not requiring file_store_path for rendezvous. either MPI or Redis should be able to perform rendezvous (at least mpi worked for me).

**Comment by shijieheping** [comment]
@minsikcho I guess I need to use OpenMPI for mpirun, as the sample script used env variable OMPI_COMM_WORLD_SIZE for judging runtime environment.
Now working on it.

**Comment by shijieheping** [comment]
@minsikcho Thanks you. After rebuild with OpenMPI, MPI redezvous works, without shared file_store_path now.
Issue closed
