### ISSUE TITLE
Can caffe2 support  armv8-a?

### ISSUE THREAD

**Issue by 103yiran** [facebookarchive/caffe2#1346]
I am compiling caffe2 on an android device whose chip is armv8-a arch. "float16x4_t"  is used in DataTranfer.cc and NNPACK, while I notice that  armv8-a's arm_neon.h does not declare that type.

**Comment by 103yiran** [comment]
Finally, I resolve this by replacing the android.toolchain.cmake with the file from android-ndk-r15c, which default using clang.

**Comment by Maratyszcza** [comment]
Yes, Caffe2 and NNPACK do support ARMv8-A, but it requires a recent Android NDK version (e.g. r15c).

**Comment by cheetah132** [comment]
jamunjadap
