### ISSUE TITLE
GCC 6.0 is forced to be prohibited even if CUDA 9.0 supports it

### ISSUE THREAD

**Issue by WinfredHuang** [facebookarchive/caffe2#1356]
As compiling still fails under Windows, I'd like to try it on Linux. However, it fails even before compilation, saying CUDA 8.0 is not supported by gcc 6. However, my CUDA version is 9.0.176. 
I can't find any information about CUDA-gcc compatibility on the web, and it seems to be a man-made restriction. 
My OS is Ubuntu 17.04, all packages updated to latest version by apt. I'm sure that CUDA 9.0 is installed correctly.

**Comment by pietern** [comment]
I haven't tried gcc 6 with CUDA 9. @slayton58 can you comment?

**Comment by slayton58** [comment]
CUDA 9 supports gcc 6.x out of the box (see `$CUDA_HOME/include/crt/host_config.h`)

Your message ("CUDA 8.0 is ....") suggests that the wrong CUDA version may be getting picked up by cmake.

**Comment by WinfredHuang** [comment]
I'm also confused that I do install CUDA 9.0, not 8.0. How could this come out?

**Comment by Maratyszcza** [comment]
Probably you have both CUDA 8 and CUDA 9 installed. Try `locate cuda_runtime_api.h` to see possible locations.

**Comment by WinfredHuang** [comment]
/usr/local/cuda-9.0/targets/x86_64-linux/include/cuda_runtime_api.h
/usr/local/cuda-9.0/targets/x86_64-linux/include/thrust/system/cuda/detail/guarded_cuda_runtime_api.h
That's what I have found. @Maratyszcza @slayton58

**Comment by WinfredHuang** [comment]
There is a workaround to enable CUDA 9.0 with gcc 6.0: 
Modify `cmake/Dependencies.cmake` at about line 329:
`if (CMAKE_C_COMPILER_ID STREQUAL "GNU" AND`
`        NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 6.0 AND`
`        CUDA_HOST_COMPILER STREQUAL CMAKE_C_COMPILER)`
to
`if (CMAKE_C_COMPILER_ID STREQUAL "GNU" AND `
`        NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 6.0 AND `
`        CUDA_HOST_COMPILER STREQUAL CMAKE_C_COMPILER AND `
`	CUDA_VERSION VERSION_LESS 9.0)`
Now at least, building is smooth without issues. 
I hope someone could do this for me since I'm a noob of Git. @slayton58

**Comment by pietern** [comment]
This was fixed by @dbermond in 70d226563c2c6b55107f8e0df55d397d3851ab5a.
