### ISSUE TITLE
The behavior of 'data_parallel_model.Parallelize' function with one CPU

### ISSUE THREAD

**Issue by sergey-serebryakov** [facebookarchive/caffe2#1359]
The `data_parallel_model.Parallelize` [function](https://github.com/caffe2/caffe2/blob/master/caffe2/python/data_parallel_model.py) works with one or multiple GPUs just fine. Should it work with one CPU when Caffe2 is ran is CPU mode (`CUDA_VISIBLE_DEVICES=`)?
I think what can happen is that on line 123 the `devices` list may end up being empty. This can result in zero division error on line 169.
Thanks.

**Comment by asaadaldien** [comment]
Currently you must explicitly specify devices for cpu mode. For one cpu you can do `devices=[0], cpu_device=True`.
