### ISSUE TITLE
[Build] Define `EIGEN_MPL2_ONLY`

### ISSUE THREAD

**Issue by christoph-conrads** [facebookarchive/caffe2#1371]
Caffe2 is distributed under the Apache 2.0 License and it can be built with Eigen3 as BLAS back-end. Eigen3 is a header-only library containining some [GNU LPGL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) code. Without defining the preprocessor symbol`EIGEN_MPL2_ONLY` during compilation, Caffe2 may incorporate LGPL code and thus become licensed under LGPL instead of the Apache 2.0 License (see the file [`COPYING.README`](https://github.com/RLovelett/eigen/blob/4e79cb69b9425f5f8c3a84be4350d4ab75b5fd9d/COPYING.README) in the Eigen repository). Currently, Eigen headers are always included in the build (see #1355) and the only way to guarantee that no re-licensing takes place is to export the environment variable `CXXFLAGS` containing `-DEIGEN_MPL2_ONLY`, e.g.,:
```sh
env CXXFLAGS=-DEIGEN_MPL2_ONLY cmake -- /path/to/caffe2
```

Please define the preprocessor symbol `EIGEN_MPL2_ONLY` for all builds with Eigen code.

**Comment by Yangqing** [comment]
Thanks! We intended to use that indeed (https://github.com/caffe2/caffe2/blob/eea00f1554d41c9fecdbaabb7f57bac6cc625136/cmake/Dependencies.cmake#L237) but did not set the macro. #1372 fixes this.
