### ISSUE TITLE
Caffe2 Python 3 build still doesn't work quite correctly

### ISSUE THREAD

**Issue by ezyang** [facebookarchive/caffe2#1386]
I'm opening this ticket to track the reversion of #1240 

I actually observed that Python 3 builds within Conda were working a week ago (I believe it was f78759698514a0d5974e5c3e5c20871a49239602) with the following cmake invocation:

```
PYTHON_ARGS="$(python ./scripts/get_python_cmake_flags.py)"
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_PREFIX_PATH="$PREFIX" $CONDA_CMAKE_ARGS $PYTHON_ARGS ..
```

but this command did not work with HEAD and cmake 3.6.3; cmake was finding the system Python 2.7. TBH, I am not sure how this ever worked without #1240  because the FindPythonInterp call is clearly requesting Python 2 versions only, but I subsequently applied the patch and it was still finding the wrong interpreter.

What DID work in the end was to explicitly pass `-DPYTHON_EXECUTABLE=$(which python)`.

**Comment by WinfredHuang** [comment]
Officially, Caffe2 doesn't support Python 3. 
Use Python 2.7 instead.

**Comment by pietern** [comment]
We now run CPU only Python 3 builds for every commit: https://ci.pytorch.org/jenkins/job/caffe2-master/
