### ISSUE TITLE
Building auxiliary programs failed due to linking warning LNK4049/LNK4217 and error LNK2001/LNK2019

### ISSUE THREAD

**Issue by WinfredHuang** [facebookarchive/caffe2#1390]
I have posted a few issues about building Caffe2 under Visual Studio 2017, and now it comes to this error. 
With a few fixes on latest version of Caffe2, the Caffe2 library and Caffe2 GPU library can be built without serious errors. However, when it starts to build miscellaneous programs like `convert_db`, THOUSANDS of warnings LNK4049/LNK4217 and error LNK2001/LNK2019 appear all of a sudden. 
Examples:

> 3>caffe2.lib(proto_utils.obj) : warning LNK4217: locally defined symbol ?snextc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ (public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::snextc(void)) imported in function "public: bool __cdecl std::basic_istream<char,struct std::char_traits<char> >::_Ipfx(bool)" (?_Ipfx@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAA_N_N@Z)
3>caffe2.lib(index_ops.obj) : warning LNK4049: locally defined symbol ?snextc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ (public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::snextc(void)) imported
...
3>caffe2.lib(net_dag.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl std::basic_ostream<char,struct std::char_traits<char> >::basic_ostream<char,struct std::char_traits<char> >(enum std::_Uninitialized,bool)" (__imp_??0?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@W4_Uninitialized@1@_N@Z)

I'm building Caffe2.lib, Caffe2_gpu.lib with `/MT`, which means multithread static library. These programs also compile with `/MT`. 
Also, strangely, these two paths appear in "Additional Library Directories": 
`C:/Program Files/Caffe2/lib`
`C:/Program Files/Caffe2/lib/$(Configuration)`
which I don't have apparently. 
In "Additional Dependencies", there are: 

> -WHOLEARCHIVE:E:/caffe2/build/caffe2/Release/caffe2.lib;-WHOLEARCHIVE:E:/caffe2/build/caffe2/Release/caffe2_gpu.lib;..\..\third_party\protobuf\cmake\Release\libprotobuf.lib;D:\Anaconda2\Library\lib\glog.lib;D:\Anaconda2\Library\lib\lmdb.lib;D:\Anaconda2\Library\lib\leveldb.lib;D:\Anaconda2\Library\lib\snappy.lib;E:\opencv\build\x64\vc14\lib\opencv_world330.lib;E:\opencv\build\x64\vc14\lib\opencv_world330.lib;E:\opencv\build\x64\vc14\lib\opencv_world330.lib;E:\opencv\build\x64\vc14\lib\opencv_world330.lib;D:\Anaconda2\Library\Lib\gflags.lib;shlwapi.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib

where "E:\caffe2" is my Caffe2 root directory, "D:\Anaconda2" is my Anaconda directory, and "E:\opencv" is my OpenCV root directory. 

Please help me to find out where is wrong. Thanks in advance.

**Comment by willyd** [comment]
I am not sure in what configuration I would get locally defined symbols imported but I am pretty sure they were all flags and the error was due to the fact that gflags was used as DLL and caffe2 was built as a static library. 

You most probably have a problem with you anaconda libraries being built with /MD and caffe2 being built with /MT.

**Comment by WinfredHuang** [comment]
Thank you. I uninstalled Gflags and Glog installed by Anaconda and now I build them manually. 
Although it's more complicated, I can control the build options by myself. 
I think this issue can be closed, and I'll post all problems I met in #1415 .
