### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by encore2020** [facebookarchive/caffe2#1400]
[ 80%] Built target caffe2_pybind11_state
make[3]: Entering directory '/home/ubuntu/caffe2/build'
make[3]: Leaving directory '/home/ubuntu/caffe2/build'
make[3]: Entering directory '/home/ubuntu/caffe2/build'
[ 80%] Linking CXX executable ../bin/fully_connected_op_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `cv::String::allocate(unsigned long)'
../lib/libcaffe2_gpu.so: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
../lib/libcaffe2_gpu.so: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/fully_connected_op_gpu_test.dir/build.make:130: recipe for target 'bin/fully_connected_op_gpu_test' failed
make[3]: *** [bin/fully_connected_op_gpu_test] Error 1
make[3]: Leaving directory '/home/ubuntu/caffe2/build'
CMakeFiles/Makefile2:1171: recipe for target 'caffe2/CMakeFiles/fully_connected_op_gpu_test.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/fully_connected_op_gpu_test.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu@ubuntu-Z270N-WIFI:~/caffe2$ 

----
Does it mean that opencv is not right?

my cuda is 9.0, cudnn7,

ubuntu@ubuntu-Z270N-WIFI:~$ pkg-config --modversion opencv 
3.1.0
ubuntu@ubuntu-Z270N-WIFI:~$

**Comment by PkuRainBow** [comment]
I got the same error log! Could you share me how to solve it ?

**Comment by tiktoktita** [comment]
Did you finally solve the mentioned "undefined reference" problem?  I wonder if it is the version of opencv that matters? 
--------------------------------------------------------
Well, I just solved this by remove the 2.4.9 libopencv-dev and use my original built-from-source opencv 3.2 and finally success☺.
