### ISSUE TITLE
Training models without a database file

### ISSUE THREAD

**Issue by yweweler** [facebookarchive/caffe2#1404]
**Is there any way to train models by feeding the training data and labels on the fly?**

I am looking for a way to train/test models without using any databases like lmdb's or lelvedb's. Using `TensorProtosDBInput` with these databses requires me to have very large databses and a time consuming generation process.

Therefore I would like to generate and feed the data on the fly.
The only thing I am able to do currently is to use `DequeueBlobs` (like below).

```
def AddInput(model, batch_size):
    data_queue, label_queue = generate_data( ... )
    input_blob = model.net.DequeueBlobs(data_queue, "data")
    labels = model.net.DequeueBlobs(label_queue, "label")
    return input_blob, labels
```

Sadly I have to enque all my training data **before** trainig.
Is there a way to supply this data during training?

**Comment by davinwang** [comment]
you may follow MNIST example, use Predict Extractor and AddExternalInput and FeedBlob

**Comment by yweweler** [comment]
Thanks for your help.

So far I added external inputs to my network as you suggested.
```python
def AddInput(model):
    data = train_model.net.AddExternalInput("input_data")
    label = train_model.net.AddExternalInput("input_label")
    return data, label
```

Using exemplaric data I can now feed traing data into the network. 
```python
data = np.array([
    [ np.array( ... ) ], # Image 1
    [ np.array( ... ) ], # Image 2
]).astype(np.float32)

label = np.array([
    1, # Label 1
    2  # Label 2
]).astype(np.int32)

for i in range(total_iters):
    workspace.FeedBlob("input_data", data)
    workspace.FeedBlob("input_label", label)
    workspace.RunNet(train_model.net)
    accuracy[i] = workspace.FetchBlob('accuracy')
    loss[i] = workspace.FetchBlob('loss')
    print(accuracy[i], loss[i])
```
I am not entirely shure however when the parameters  (weights, biases) are updated.
Do I also have to trigger updates of the model parameters manually in order for the network to learn?

**Comment by davinwang** [comment]
The parameters are updated during training, also defined in model. please find the line in MNIST with WeightedSum
`    # Now, for each parameter, we do the gradient updates.
    for param in model.params:
        # Note how we get the gradient of each parameter - ModelHelper keeps
        # track of that.
        param_grad = model.param_to_grad[param]
        # The update is a simple weighted sum: param = param + param_grad * LR
        model.WeightedSum([param, ONE, param_grad, LR], param)`

**Comment by yweweler** [comment]
Thanks for your support.
