### ISSUE TITLE
float16 and enable-tensor-core are not working

### ISSUE THREAD

**Issue by renganxu** [facebookarchive/caffe2#1408]
Hi, I am trying to run resnet50 example with float16, but it has error. I was using 4 Volta GPUs on my server and therefore the float16 and tensor core are supported. I also used CUDA 9, CUDNN 7 and NCCL 2.0 to compile Caffe2. The command I used to run resnet50 example is:
```python -m caffe2.python.examples.resnet50_trainer \```
  ```  --train_data ${DATASET_DIR}/ilsvrc12_train_lmdb/ \```
   ``` --test_data ${DATASET_DIR}/ilsvrc12_val_lmdb/ \```
   ``` --gpus 0,1,2,3 \```
  ```  --batch_size 256 \```
   ``` --epoch_size 1280000 \```
 ```   --num_epochs 1 \```
 ```   --dtype=float16 \```
    ```--enable-tensor-core```

But the example could not finish as it has the following errors:
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 1
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 2
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 3
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 1
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 2
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:data_parallel_model:Model for GPU : 3
WARNING:root:You are creating an op that the ModelHelper does not recognize: FloatToHalf.
INFO:resnet50_trainer:Starting epoch 0/1
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at tensor.h:507] IsType<T>(). Tensor type mismatch, caller expects elements to be float while tensor contains caffe2::__f16 Error from operator:
input: "gpu_0/data" output: "gpu_0/data_fp16" name: "" type: "FloatToHalf" device_option { device_type: 1 cuda_gpu_id: 0 }
** while accessing input: gpu_0/data
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.

I was using the latest caffe2 commit "fc6c92a7577bf79639f459808c47280be6645762".
Does anyone know how to solve it? Thanks in advance.

Regards,
Rengan

**Comment by Maratyszcza** [comment]
cc @slayton58 @pietern

**Comment by slayton58** [comment]
This was broken by @akyrola 's commit https://github.com/caffe2/caffe2/commit/bab5bc -- The cast terms added in caffe2/python/models/resnet.py are extraneous and causing the type mismatch.

**Comment by akyrola** [comment]
Sorry about that, will fix today

Sent from my iPhone

On Nov 1, 2017, at 05:32, Simon Layton <notifications@github.com<mailto:notifications@github.com>> wrote:


This was broken by @akyrola<https://github.com/akyrola> 's commit bab5bc<https://github.com/caffe2/caffe2/commit/bab5bc> -- The cast terms added in caffe2/python/models/resnet.py are extraneous and causing the type mismatch.

**Comment by akyrola** [comment]
I just landed a fix.

**Comment by renganxu** [comment]
@akyrola Thanks very much. I will try that soon.

**Comment by kramimus** [comment]
I had the same fp16 issue on a V100 and this fixed it, thanks.
