### ISSUE TITLE
Syntax error building in Windows

### ISSUE THREAD

**Issue by ctraina** [facebookarchive/caffe2#1421]
I am trying to build in Windows 10 (VS 2017).  I did a clean clone from the repo today.  I ran build_host_protoc.bat, which completed with no issues.  However, when I run build_windows.bat, I get the following error(s):

"E:\Projects\NeuralNets\caffe2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\Projects\NeuralNets\caffe2\build\caffe2\caffe2.vcxproj" (default target) (5) ->
(ClCompile target) ->
  E:\Projects\NeuralNets\caffe2\caffe2\core\plan_executor.cc(147): error C2059: syntax error: 'template' [E:\Projects\NeuralNets\caffe2\build\caffe2\caffe2.vcxproj]
  E:\Projects\NeuralNets\caffe2\caffe2\core\plan_executor.cc(148): error C2039: 'global_ws_id_blob': is not a member of 'caffe2::Tensor<caffe2::CPUContext>' [E:\Projects\NeuralNets\caffe2\build\caffe2\caffe2.vcxproj]
  E:\Projects\NeuralNets\caffe2\caffe2\core\plan_executor.cc(148): error C2059: syntax error: 'template' [E:\Projects\NeuralNets\caffe2\build\caffe2\caffe2.vcxproj]

**Comment by ctraina** [comment]
Well, I was able to resolve the syntax error and build.  In plan_executor.cc, changed:
    global_ws_id_blob->template GetMutable<TensorCPU>()->template Resize();

To:
    global_ws_id_blob->template GetMutable<TensorCPU>()->template Resize<>();

But now I am back to this when I try to run tutorial_blob:
[F operator.h:628] You might have made a build error: the Caffe2 library does not seem to be linked with whole-static library option. To do so, use -Wl,-force_load (clang) or -Wl,--whole-archive (gcc) to link the Caffe2 library.

If I change the /WHOLEARCHIVE flag to apply to all libraries (not just caffe2.lib), I get a bunch of multiply defined symbol errors for __NULL_IMPORT_DESCRIPTOR.  Otherwise, I always get the above error message (even with /WHOLEARCHIVE for caffe2.lib).

**Comment by ctraina** [comment]
Related to #1415

**Comment by Mourdraug** [comment]
I have the exact same errors I'm not using Visual Studio, but Visual C++ Build Tools 2017 tho.

**Comment by Mourdraug** [comment]
Got same erros, but I had outdated clone. It seems to be fixed with https://github.com/caffe2/caffe2/pull/1442

**Comment by ctraina** [comment]
@Mourdraug - thanks for the suggestion.  I cloned the latest commit and I can no longer even get past building the protocol buffers (see #1528).  I tried switching to the actual commit referenced in #1442, and I have the same issue (protocol buffer link errors).  Did you have to make any modifications to the build scripts to get your build to work in Windows?

**Comment by ctraina** [comment]
It turns out my latest build attempts were fighting with the version I downloaded/built using VCPKG in an attempt to circumvent the previous errors.  It is working now (with commit afc0d96b89776eff874b548240e6931be5b6c42d).
