### ISSUE TITLE
google::protobuf::internal::ArenaStringPtr

### ISSUE THREAD

**Issue by YangBain** [facebookarchive/caffe2#1424]
When I run make && cd build && sudo make install.I get the following error. 
%%%%%%%%%%%%%%%
 google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
make[3]: *** [bin/blob_gpu_test] Error 1
make[3]: Leaving directory `/home/beans/caffe2/build'
make[2]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
make[2]: Leaving directory `/home/beans/caffe2/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/beans/caffe2/build'
make: *** [all] Error 2

So how can I fix these problems. Any help from you will be appreciated. Thank you very much.

**Comment by pietern** [comment]
Given that the first line of the output you posted had to do with protobuf I'm going to assume this was a protobuf build issue. Can you post your CMake version, CMake summary output, compiler version, operating system, and other relevant details about your environment?

If this is no longer a problem, please feel free to close the issue.

**Comment by pjh5** [comment]
@YangBain are you still having this issue?

**Comment by pjh5** [comment]
The cmake logic for protobuf has changed significantly since this issue was created, so I will close this issue. If you encounter any problems in the future, please open a new issue.
