### ISSUE TITLE
Hi, I want to train a model on mobile but I don't find something helpful. Thus, I want to know how to implement my ideas.

### ISSUE THREAD

**Issue by Jason-cs18** [facebookarchive/caffe2#1432]

**Comment by Jason-cs18** [comment]
@Yangqing

**Comment by Jason-cs18** [comment]
@sophiebits

**Comment by sasikiran** [comment]
@jacksonly The way people do is, they train the model on a computer and then use the trained model on the mobile for inference.

**Comment by orionr** [comment]
@sasikiran is correct. Feel free to ask more questions if you'd like, but closing. Thanks!
