### ISSUE TITLE
Fix weird CSS bug in the website

### ISSUE THREAD

**Issue by chsasank** [facebookarchive/caffe2#1444]
Hi,

I'm checking out your tutorials and I saw that code blocks are rendered weirdly with line separating code and line nos shifted to right . 
I'm attaching the screenshot. 

![screen shot 2017-11-10 at 11 23 30](https://user-images.githubusercontent.com/9305875/32644774-b632933e-c609-11e7-960c-ec3cafd2ca90.png)

**Comment by arogozhnikov** [comment]
https://github.com/caffe2/caffe2/pull/1457 should resolve the problem

**Comment by arogozhnikov** [comment]
PR was merged, so this issue can be closed.
