### ISSUE TITLE
python-opencv not included in dockerfile

### ISSUE THREAD

**Issue by svohara** [facebookarchive/caffe2#1453]
Can we add python-opencv to the caffe2 docker images that are supposed to include all the "nice-to-have" optional dependencies? Specifically caffe2ai/caffe2:latest does not have the python opencv bindings installed, and neither does c2v0.8.1.cuda8.cudnn7.ubuntu16.04.

**Comment by pjh5** [comment]
This was a while ago, and it looks like the Ubuntu dockers now come with libopencv-dev
