### ISSUE TITLE
Bug: spatial_BN op cannot be saved by predictor_exporter

### ISSUE THREAD

**Issue by davinwang** [facebookarchive/caffe2#1456]
save the predict net by
`pe.save_to_db(SAVED_NET)`  
and load it with
`predict_net = pe.prepare_prediction_net(SAVED_NET)`  
got following error  
`RuntimeError: [enforce fail at net.cc:77] . op SpatialBN: Source for input norm1_rm is unknown for net policy_deploy_7_1, operator input: "conv1" input: "norm1_s" input: "norm1_b" input: "norm1_rm" input: "norm1_riv" output: "norm1" name: "" type: "SpatialBN" arg { name: "is_test" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 0 cuda_gpu_id: 0 } `

**Comment by pietern** [comment]
I believe this error message indicates that the net you have created doesn't include an "external input" marker for the blobs that one of its ops tries to use.

**Comment by sbuslovsky** [comment]
@davinwang @pietern can you provide more details on how to solve this?

I'm having a similar issue.
I used a model based on ResNet50 from models/resnet.py.
It has a Spatial BN layer:
```
brew.spatial_bn(
        model, 'conv1', 'conv1_spatbn', 16, epsilon=1e-3, is_test=is_test
)
```
During training, when the model is being saved with _pe.PredictorExportMeta_, I can see only 2 blobs being outputted: _conv1_spatbn_s_ and _conv1_spatbn_b_ .
And then when trying to load model _pe.prepare_prediction_net_, I'm getting the following error
> RuntimeError: [enforce fail at net.cc:77] . op SpatialBN: Source for input conv1_spatbn_rm is unknown for net ttrsc_deploy_1, operator input: "conv1" input: "conv1_spatbn_s" input: "conv1_spatbn_b" input: "conv1_spatbn_rm" input: "conv1_spatbn_riv" output: "conv1_spatbn" name: "" type: "SpatialBN" arg { name: "is_test" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "epsilon" f: 0.001 } arg { name: "order" s: "NCHW" } 

Seems like *_rm* and *_riv* parameters are not being outputted.

Do I need to initialize the spatial_bn layer in some other way for deploy model?

**Comment by sbuslovsky** [comment]
I was able to solve this by exporting those _rm and _riv blobs manually:
`extra_params = [b for b in workspace.blobs if b.endswith("_rm") or b.endswith("_riv")]`

But I still think we need more documentation/clarity on exporting and using Spatial BN layers in deploy models.

**Comment by davinwang** [comment]
@pietern Shall we reopen this issue ? According to @sergbuslovsky reported workaround.

**Comment by zhouyongxiu** [comment]
@sergbuslovsky  I have the a similar issue as yours when I try to save the resnet50 model, could you pls share your train and save script. I am not familiar with caffe2, after I trained the model as resnet50_trainer.py, I don't know how to save and use it.

**Comment by sbuslovsky** [comment]
```
  # save procedure
  def save_model(model, path, data_blob='data', softmax_blob='softmax'):
    # construct the model to be exported
    # the inputs/outputs of the model are manually specified.
    extra_params = [b for b in workspace.blobs if b.endswith("_rm") or b.endswith("_riv")]
    export_params = []
    if gpu:
      for b in data_parallel_model.GetCheckpointParams(model):
        if 'dbreader' not in str(b):
          export_params.append(str(b))
    else: 
      export_params = [str(b) for b in model.params] + extra_params
    
    shapes = {'data':workspace.FetchBlob(data_blob).shape, 'softmax':workspace.FetchBlob(softmax_blob).shape}
    for p in export_params+[data_blob,softmax_blob]:
      try:
        blob = workspace.FetchBlob(p) 
        if hasattr(blob,'shape'):
          shapes[str(p)] = blob.shape
      except:
        pass

    pe_meta = pe.PredictorExportMeta(
        predict_net=model.net.Proto(),
        parameters=export_params,
        inputs=[data_blob],
        outputs=[softmax_blob],
        shapes=shapes
    )

    # save the model to a file. Use minidb as the file format
    pe.save_to_db("minidb", path, pe_meta)
    print("The deploy model is saved to: " + path)
```

**Comment by zhouyongxiu** [comment]
@sergbuslovsky thank you, the input model should be train_model or deploy_model? I am not clear about the condition 'gpu', it seems that if I use gpu, the extra_params doesn't work.

**Comment by shiyongde** [comment]
I also get this when run test_net.py
E0421 15:55:40.369242 15564 net_dag.cc:188] Exception from operator chain starting at '' (type 'Conv'): caffe2::EnforceNotMet: [enforce fail at blob.h:81] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/conv1_spatbn_rm.
Error from operator:
input: "gpu_0/conv1" input: "gpu_0/conv1_spatbn_s" input: "gpu_0/conv1_spatbn_b" input: "gpu_0/conv1_spatbn_rm" input: "gpu_0/conv1_spatbn_riv" output: "gpu_0/conv1_spatbn" name: "" type: "SpatialBN" arg { name: "is_test" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "epsilon" f: 0.001 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 cuda_gpu_id: 0 }
