### ISSUE TITLE
Undefined reference to atof with NDK build of AICamera demo

### ISSUE THREAD

**Issue by aquastill** [facebookarchive/caffe2#1465]
Hi, I try to integrate the prebuilt libs (armeabi v7) from AICamera app to my own project through Android.mk  for abi_v7. All building and linking work fine except I got NDK error of Undefined reference to atof, strtof and etc. from libCaffe2_CPU.a and libprotobuf.a .
My NDK version is r11c and I am using its own gnustl, just wonder what is the root cause of this linking error? Is a particular version of NDK or STL required? Thanks.

**Comment by Yangqing** [comment]
This seems to be a really old issue that should not be present today... See for example

https://stackoverflow.com/questions/14571399/android-ndk-cant-find-atof-function

If the problem persists, you can add an atof implementation like mentioned in the link. Usually newer NDK versions shouldn't have this issue any more.
