### ISSUE TITLE
Caffe2 benchmark test

### ISSUE THREAD

**Issue by dlwtojd26** [facebookarchive/caffe2#1468]
Hi I am trying to run convnet_benchmark.py on Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz. Ubuntu 16.04

I read this page **https://software.intel.com/en-us/blogs/2017/04/18/intel-and-facebook-collaborate-to-boost-caffe2-performance-on-intel-cpu-s** 

In this page indicates  OMP_NUM_THREADS changes the performance.

How could I get this result on my CPU

I tried this command on my machine
python convnet_benchmark.py --model Alexnet --caffe2_omp_num_threads=1 .. 2 .. etc

but no change.

 Can someone help me?

**Comment by china-cat** [comment]
i had same problem 
do u solve the problem?
