### ISSUE TITLE
undefined reference to cudaStreamCreate

### ISSUE THREAD

**Issue by szm-R** [facebookarchive/caffe2#1471]
Hi, I encounter the following error when the making process has proceeded up to 99 percent:
CMakeFiles/core_overhead_benchmark.dir/core_overhead_benchmark.cc.o: In function `BM_cudaStreamWaitEventThenStreamSynchronize(benchmark::State&)':
core_overhead_benchmark.cc:(.text+0x2e2): undefined reference to `cudaStreamCreate'

Here is the build summary:

-- ******** Summary ********
-- General:
--   Git version           : v0.8.1-667-gbd5bb22-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   CXX flags             :  -fopenmp -std=c++11 -O2 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_OPENMP            : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF

I don't think anything is wrong with my cuda installation as I'm using it both in Caffe and other codes and it works without a problem. And also I had another caffe2 that I have git cloned around a month ago, this one also builds and passes the tests without a problem, so the new one that I have git cloned today seems to have an issue! I appreciate any help greatly.

**Comment by Yangqing** [comment]
Hmm this looks weird, could you run cmake with -DCMAKE_VERBOSE_MAKEFILE=ON and paste the output? Thanks!

**Comment by szm-R** [comment]
Hi, sorry for the delay, I have attached the cmake output with the flag you said
[CMakeOutput.txt](https://github.com/caffe2/caffe2/files/1484722/CMakeOutput.txt)

**Comment by pietern** [comment]
@szm2015 Really weird. The CMakeOutput does not contain clues. Can you check if you still see the same link error with the latest code?

**Comment by Yangqing** [comment]
Looping back on this one - after the cmake config, could you run make and paste the output too?

**Comment by szm-R** [comment]
Hi everyone, sorry for the long absence, I've been working on some other projects. I git cloned the latest caffe2 and was able to make and build it without a problem :) I don't know what was the issue last time and I have also changed some of the other dependencies (like updating cuda and cudnn,...) in my system.
