### ISSUE TITLE
Input must be of type numpy array

### ISSUE THREAD

**Issue by eva-thientran** [facebookarchive/caffe2#1481]
Hello
I have following the tutorial at https://caffe2.ai/docs/zoo.html when I try running following the code below

```
from caffe2.python import workspace, model_helper

with open("exec_net.pb") as f:
    init_net = f.read()
with open("predict_net.pb") as f:
    predict_net = f.read()

p = workspace.Predictor(init_net, predict_net)
img = 'dog.png'
results = p.run([img])
print(results)
```
I get a error RuntimeError: [enforce fail at pybind_state.cc:667] PyArray_Check(input.ptr()). Input must be of type numpy array. 

Anyone have suggestion for that. Thanks

**Comment by ilkarman** [comment]
Your input to the predictor is a string ("dog.png"), you have to load the image like [here](https://caffe2.ai/docs/tutorial-image-pre-processing.html), e.g

```
import skimage
img_arr = skimage.img_as_float(skimage.io.imread("dog.png")).astype(np.float32)

```

**Comment by pietern** [comment]
Thanks for pitching in @ilkarman!
