### ISSUE TITLE
The error of the compling, like"libCaffe2_CPU.so：对‘google::protobuf::io::CodedInputStream::PushLimit(int)’未定义的引用"

### ISSUE THREAD

**Issue by wuzhijiexia** [facebookarchive/caffe2#149]
The libs of protobuf were placed on the default path(/usr/local/lib), the version was 3.1.0. After the operation "cmake ../", the value of PROTOBUF_LIBRARY is "/usr/local/lib/libprotobuf.so" in the file CmakeCache.txt. According to it, I thinks caffe2 should can link to the protobuf libs. But there are problems about the link of the protobuf libs.
![image 10](https://cloud.githubusercontent.com/assets/19603119/22925844/2e7e7a9a-f2e5-11e6-916d-0a823f593fd0.png)
I hope you can give me some messages to help me.

**Comment by Yangqing** [comment]
Could you clean the cmake directory, do 

cmake -DCMAKE_VERBOSE_MAKEFILE=1 [your other cmake args]

and then make? A paste of the output would then give us the build string.

**Comment by wuzhijiexia** [comment]
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not set - defaulting to Release
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Using protobuf compiler /usr/local/bin/protoc.
-- The BLAS backend of choice:Eigen
-- Found GFlags: /usr/local/include  
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.so)
-- Found system gflags install.
-- Found Glog: /usr/local/include  
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found system glog install.
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WZERO_AS_NULL_POINTER_CONSTANT
-- Performing Test HAVE_CXX_FLAG_WZERO_AS_NULL_POINTER_CONSTANT - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Performing Test BENCHMARK_HAS_CXX03_FLAG
-- Performing Test BENCHMARK_HAS_CXX03_FLAG - Success
-- Found LMDB: /usr/include  
-- Found lmdb    (include: /usr/include, library: /usr/lib64/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib64/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib64/libsnappy.so)
-- Could NOT find RocksDB (missing:  RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
CMake Warning at cmake/Dependencies.cmake:114 (message):
  Not compiling with RocksDB.  Suppress this warning with -DUSE_ROCKSDB=OFF
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)


-- OpenCV found (/usr/lib64/cmake/OpenCV)
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.5", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7") 
-- Found NumPy: /usr/lib64/python2.7/site-packages/numpy/core/include (found version "1.11.1") 
-- NumPy ver. 1.11.1 found (include: /usr/lib64/python2.7/site-packages/numpy/core/include)
-- Found MPI_C: /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpifort.so;/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/release_mt/libmpi.so;/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpigi.a;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpicxx.so;/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpifort.so;/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/release_mt/libmpi.so;/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpigi.a;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/include
-- MPI LINK flags path: 
-- MPI libraries: /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpicxx.so/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpifort.so/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/release_mt/libmpi.so/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpigi.a/usr/lib64/libdl.so/usr/lib64/librt.so/usr/lib64/libpthread.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Warning at cmake/Dependencies.cmake:223 (message):
  Not compiling with OpenMP.  Suppress this warning with -DUSE_OPENMP=OFF
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)


CMake Warning at cmake/Dependencies.cmake:245 (message):
  Not compiling with CUDA.  Suppress this warning with -DUSE_CUDA=OFF
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)


CMake Warning at cmake/Dependencies.cmake:253 (message):
  If not using cuda, one should not use NCCL either.
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)


-- Performing Test CAFFE2_LONG_IS_INT32_OR_64
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64 - Success
-- Does not need to define long separately.
-- Performing Test HAS_BUILTIN_CPU_SUPPORTS
-- Performing Test HAS_BUILTIN_CPU_SUPPORTS - Success
-- This compiler has builtin_cpu_supports feature.
-- Including MPI binaries
-- Including OPENCV binaries
-- NCCL operators built due to no CUDA support
-- CUDA RTC operators built due to no CUDA support
-- Including image processing operators
-- Excluding mkl operators as we are not using mkl
-- Automatically generating missing __init__.py files.
-- 
-- ******** Summary ********
-- General:
--   Version               : 
--   Git                   : 
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   Protobuf compiler     : /usr/local/bin/protoc
--   CXX flags             :  -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY
-- 
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--   USE_CUDA              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--     glog version        : 
--   USE_GFLAGS            : ON
--     gflags version      : 
--   USE_LMDB              : ON
--     LMDB version        : 0.9.18
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.12
--     Snappy version      : 1.1.0
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.5
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : ON
--   USE_NCCL              : OFF
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhengwu/caffe2/build

**Comment by wuzhijiexia** [comment]
[make-j32.txt](https://github.com/caffe2/caffe2/files/775966/make-j32.txt)

The partial content:
/usr/bin/c++    -std=c++11 -fPIC -Wno-narrowing -O3 -DNDEBUG    CMakeFiles/init_test.dir/core/init_test.cc.o  -o binaries/init_test -rdynamic libCaffe2_CPU.so -lpthread /usr/local/lib/libglog.so /usr/local/lib/libgflags.so -llmdb -lleveldb -lsnappy -lopencv_imgproc -lopencv_highgui -lopencv_core /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpicxx.so /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpifort.so /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/release_mt/libmpi.so /opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpigi.a -ldl -lrt -lpthread ../third_party/googletest/googlemock/gtest/libgtest_main.so ../third_party/googletest/googlemock/gtest/libgtest.so -lpthread -Wl,-rpath,/home/zhengwu/caffe2/build/caffe2:/usr/local/lib:/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/release_mt:/home/zhengwu/caffe2/build/third_party/googletest/googlemock/gtest: 
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long, google::protobuf::io::CodedOutputStream*)'

When creating the dynamic library libCaffe2_CPU.so, there is not the linking of the protobuf-libs.

**Comment by Yangqing** [comment]
Very interesting - what cmake version are you using?

@bwasti I suspect this is a similar issue to what we encountered - cmake might have changed its internal Protobuf vs PROTOBUF naming convention.

**Comment by wuzhijiexia** [comment]
The cmake version which I am using is 2.8.12.2.

**Comment by Yangqing** [comment]
I just realized - are you building with Cygwin / mingw on a Windows machine? That might trigger the local build of protobuf which is not intended. Windows support is currently flaky.

**Comment by wuzhijiexia** [comment]
Do I need the newer version cmake?

**Comment by Yangqing** [comment]
For now, if you are building on windows, try to remove "OR WIN32" here and see if fix your problem:

https://github.com/caffe2/caffe2/blob/master/cmake/ProtoBuf.cmake#L4

**Comment by wuzhijiexia** [comment]
I am building on Linux.

**Comment by bwasti** [comment]
It looks as though CMake 2.8 sets `PROTOBUF_LIBRARY` (https://www.apt-browse.org/browse/ubuntu/trusty/main/all/cmake-data/2.8.12.2-0ubuntu3/file/usr/share/cmake-2.8/Modules/FindProtobuf.cmake line 226) whereas the later version of CMake sets `Protobuf_LIBRARIES` / `PROTOBUF_LIBRARIES` (https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake#L415).

This may fix it https://github.com/caffe2/caffe2/pull/152

**Comment by wuzhijiexia** [comment]
Thanks very much, @Yangqing and @bwasti . The problem has solved according to update ProtoBuf.cmake.

**Comment by yanxp** [comment]
@wuzhijiexia hello,I miss the same problem. how to update ProtoBuf.cmake?thanks

**Comment by wuzhijiexia** [comment]
It looks as though CMake 2.8 sets PROTOBUF_LIBRARY (https://www.apt-browse.org/browse/ubuntu/trusty/main/all/cmake-data/2.8.12.2-0ubuntu3/file/usr/share/cmake-2.8/Modules/FindProtobuf.cmake line 226) whereas the later version of CMake sets Protobuf_LIBRARIES / PROTOBUF_LIBRARIES (https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake#L415).

This may fix it #152
