### ISSUE TITLE
Multi-GPU training speed test?

### ISSUE THREAD

**Issue by MatthiasDING** [facebookarchive/caffe2#1492]
I know caffe2 have achieved up to 7.7x speed up using 8 GPUs with batch_size 64 on Resnet-50.  https://developer.nvidia.com/caffe2

But I'm a little confused about the setting of batch_size in the speed test. We should set total batch_size as 64*8  or just 64,  when 8 GPUs are used?

**Comment by pietern** [comment]
The batch size you specify as argument to the resnet50_trainer program is the total batch size, so 512.

Is this the speed test you're referring to?

**Comment by MatthiasDING** [comment]
yes，I just want to test the speedup ability of multi-gpus on my own machine. thank you @pietern
