### ISSUE TITLE
Make ERROR with NVCC(nccl)

### ISSUE THREAD

**Issue by lyuweiwang** [facebookarchive/caffe2#1499]
Hello,

When I make caffe2 on **Ubuntu 16.04, with cuda8.0, cudnn6.0 and nvidia375.66**, I meet one make error.

[ 15%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at gloo_cuda_generated_nccl.cu.o.Release.cmake:203 (message):
  Error generating
  /home/lyuwei/caffe2/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o

third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/build.make:77: recipe for target 'third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o' failed

---------------------------------------

I have checked my nccl.

../nccl/build/test/single/all_reduce_test 100000
 Using devices
  Rank  0 uses device  0 [0x02] TITAN X (Pascal)
   Rank  1 uses device  1 [0x81] TITAN X (Pascal)

                                                 out-of-place                    in-place
      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
      100000        100000    char     sum    0.064   1.55   1.55    0e+00    0.099   1.01   1.01    0e+00
      100000        100000    char    prod    1.827   0.05   0.05    0e+00    0.269   0.37   0.37    0e+00
      100000        100000    char     max    0.300   0.33   0.33    0e+00    0.253   0.40   0.40    0e+00
      100000        100000    char     min    0.380   0.26   0.26    0e+00    0.970   0.10   0.10    0e+00
      100000         25000     int     sum    1.967   0.05   0.05    0e+00    0.482   0.21   0.21    0e+00
      100000         25000     int    prod    3.297   0.03   0.03    0e+00    0.640   0.16   0.16    0e+00
      100000         25000     int     max    0.055   1.82   1.82    0e+00    0.068   1.48   1.48    0e+00
      100000         25000     int     min    0.055   1.82   1.82    0e+00    0.115   0.87   0.87    0e+00
      100000         50000    half     sum    0.062   1.62   1.62    0e+00    0.075   1.33   1.33    0e+00
      100000         50000    half    prod    0.062   1.62   1.62    0e+00    0.075   1.34   1.34    0e+00
      100000         50000    half     max    1.164   0.09   0.09    0e+00    0.106   0.95   0.95    0e+00

---------------------------------

So would anyone tell me what the problem is? Thank you all.

Lyuwei

**Comment by bfortuner** [comment]
I'm having the same issue. Specs the same.

**Comment by yytdfc** [comment]
I find out it is a cmake bug. #1397

**Comment by pietern** [comment]
We can continue in #1397.
