### ISSUE TITLE
Please consider merging with DMLC/MXNet

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#15]
No offence intended. Everybody respects that you created the great Caffe. Thank you very much!

But the current design seems a mix of the original Caffe and the [radically differently designed MXNet](https://mxnet.readthedocs.org/en/latest/#open-source-design-notes). The latter has implemented many features in [your road map](http://tutorial.caffe.berkeleyvision.org/caffe-cvpr15-improving.pdf) and is gaining more momentum than this project in terms of GitHub contributors, pull requests/issues, stars, forks and watches. If you would like to combine the two independent efforts like the Avengers and [lead the joint project](https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md#become-a-comitter), you as team will certainly create more rapidly a more impactful next generation distributed deep learning framework that many people have heard of but had no access to for three years [1].

[1] Jeffrey Dean, Greg S. Corrado, Rajat Monga, Kai Chen, Matthieu Devin, Quoc V. Le, Mark Z. Mao, Marc’Aurelio Ranzato, Andrew Senior, Paul Tucker, Ke Yang, and Andrew Y. Ng. Large Scale Distributed Deep Networks. In Proceedings of Neural and Information Processing Systems (NIPS), 2012, Lake Tahoe, Nevada, United States, December, 2012.

**Comment by futurely** [comment]
Now everyone knows [what happened](https://github.com/tensorflow/tensorflow).

**Comment by Yangqing** [comment]
Sorry I had to stay silent till the release - thanks for your inerest though, and I definitely like the mxnet effort. It's great to see more people devoting to open source!

**Comment by futurely** [comment]
Google has great leaders. The initial numbers in the first few hours suggest that TensorFlow's popularity will overwhelm that of Caffe, MXNet and anything alike combined by the end of this week.
