### ISSUE TITLE
Why can not import? Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [facebookarchive/caffe2#1501]
![_20171121154422](https://user-images.githubusercontent.com/4702353/33060385-fe296560-ced2-11e7-86b1-df3cc16eced5.jpg)

![_20171121154827](https://user-images.githubusercontent.com/4702353/33060515-743c6554-ced3-11e7-9666-94fdb8779573.jpg)

**Comment by bddppq** [comment]
I guess it's because your python file is named "caffe2.py" which causes the first statement "import caffe2" importing your `caffe2.py` instead of the real caffe2. To verify, add "print(caffe2)" between your first import and second import to see what's the thing it has imported.
