### ISSUE TITLE
error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’

### ISSUE THREAD

**Issue by chongyang-xu** [facebookarchive/caffe2#1521]
I met the similar issue with https://github.com/caffe2/caffe2/issues/1067
I don't have globally installed gloo. And I try to re-clone,but it didn't work.

here is the information:

- centos7.3
- gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
- Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
- $git describe --long --tags 
v0.8.1-0-g32f023f

I follow instructions from https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud
when “sudo make install”,it prints:

Scanning dependencies of target Caffe2_CPU
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File `caffe2/CMakeFiles/Caffe2_CPU.dir/flags.make' has modification time 86045 s in the future
[ 19%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/allreduce_ops.cc.o
[ 19%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/barrier_ops.cc.o
[ 19%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/broadcast_ops.cc.o
[ 19%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common.cc.o
[ 19%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common_world_ops.cc.o
In file included from /home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.cc:1:0:
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h: In constructor ‘caffe2::gloo::CreateCommonWorld<Context>::CreateCommonWorld(const caffe2::OperatorDef&, caffe2::Workspace*)’:
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h:37:16: error: ‘class gloo::transport::Device’ has no member named ‘setTimeout’
       device_->setTimeout(std::chrono::milliseconds(timeout));
                ^
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h: In member function ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice()’:
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h:72:26: error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’
                 device_->getTimeout()) {
                          ^
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h: In instantiation of ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice() [with Context = caffe2::CPUContext]’:
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.cc:33:1:   required from here
/home/chongyang/ddl/caffe2/caffe2/caffe2/contrib/gloo/common_world_ops.h:71:59: error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’
             backingCommonWorld->getDevice()->getTimeout() <
                                                           ^
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common_world_ops.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make: *** [all] Error 2
[chongyang@gpu2 build]$

**Comment by pietern** [comment]
This must be some kind of repository skew. Did you try a fresh clone of the entire repository, including submodules? Also please try master instead of 0.8.1, we need to tag a new release soon anyway.

FWIW, we test builds on CentOS 7, but only with system Python, not Anaconda Python. I see the version of GCC in your Anaconda setup is quite old (4.4) and is not a compiler we test for.

**Comment by chongyang-xu** [comment]
I  tried a fresh clone of the entire repository again.
And I switch to system Python(2.7.5 gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )
I get the following error that not happen in 0.8.1
```
[ 13%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at gloo_cuda_generated_nccl.cu.o.Release.cmake:203 (message):
  Error generating
  /home/chongyang/ddl/caffe2/caffe2/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o


make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o] Error 1
make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all] Error 2
make: *** [all] Error 2

```
This error is in Makefile "gloo_cuda_generated_nccl.cu.o.Release.cmake:203",whitch has been mentioned by other people.The error is missing some "-I" on linking Paths
Though this Makefile is generated automatically,I tried to fix it manually.After fixing one or two similar errors.I get the error above "gloo::transport::Device’ has no member named ‘setTimeout’".

And I will try with higher version of GCC.

**Comment by pjh5** [comment]
@giantpoplar are you still getting this issue on the most recent code? The cmake mechanism that finds gloo has been changed recently.

**Comment by chongyang-xu** [comment]
@pjh5 It could be built successfully now.Thank you.
