### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by paul-mesnilgrente** [facebookarchive/caffe2#1526]
Hi everybody,

I have compiled the lastCaffe2 commit with CUDA 9 support and CUDNN 7. It compiled well. The problem comes when I execute a program that is using it, below is the error:

```text
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at conv_op_cudnn.cc:580] status == CUDNN_STATUS_SUCCESS. 9 vs 0. , Error at: /home/paul/.libs/caffe2/caffe2/operators/conv_op_cudnn.cc:580: CUDNN_STATUS_NOT_SUPPORTED Error from operator: 
input: "data" input: "conv1_w" input: "conv1_b" output: "conv1" type: "Conv" arg { name: "stride" i: 2 } arg { name: "pad" i: 0 } arg { name: "kernel" i: 7 } device_option { device_type: 1 }
```

Do you have any idea of what is means? It seems that there is check of SUCCESS but it is not supported, why? Is it going to be supported soon or... ?

**Comment by pietern** [comment]
Hi! This means the input parameters to the cudnn call are somehow inconsistent/incompatible. It also means we're missing some kind of check on the Caffe2 side that can give a more helpful error message.

@slayton58 Do you have a clue?

**Comment by pietern** [comment]
I have seen the same error when running the `test_convolution_gradients` test (see [conv_test.py](https://github.com/caffe2/caffe2/blob/1277f9a79c3580278cd7007d14c8ae0953e61706/caffe2/python/operator_test/conv_test.py#L190)) with:

```
@seed(302934307671667531413257853548643485645)
```

I saw it first in [caffe2-linux-xenial-cuda9-cudnn7-test#203](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/caffe2-linux-xenial-cuda9-cudnn7-test/203/). It likely has something to do with a RNG that has been re-seeded, causing the test to fail where it didn't fail before.

**Comment by pietern** [comment]
@paul-mesnilgrente Also, can you provide the input shapes to the operator at the time of failure?

**Comment by galv** [comment]
I just want to comment that the CUDNN developer manual actually does specify a list of possibilities for what went wrong for a specific error code, for each function. This is it for cudnnConvolutionForward in the cudnn7 pdf manual (behind a login wall, unfortunately):

"""
CUDNN_STATUS_NOT_SUPPORTED
At least one of the following conditions are met:
‣ xDesc or yDesc have negative tensor striding
‣ xDesc, wDesc or yDesc has a number of dimensions that is not 4 or 5
‣ yDescs's spatial sizes do not match with the expected size as determined by
     cudnnGetConvolutionNdForwardOutputDim
‣ The chosen algo does not support the parameters provided; see above for exhaustive list of parameter support for each algo
"""

The "exhaustive list of parameter support for each algo" is so exhaustive that I'm not going to paste it here. Hopefully that helps with finding the erroneous input combination.

**Comment by pietern** [comment]
Thanks for the pointer @galv

**Comment by slayton58** [comment]
@pietern I can't get `conv_test.py::TestConvolution::test_convolution_gradients` to fail locally (CUDA 9, cudnn7, r384 driver) with your seed.

@paul-mesnilgrente Seconding Pieter's request for the dimensions of the input / output -- given these I should be able to work out what's failing.

**Comment by pietern** [comment]
@paul-mesnilgrente Could this be related to 436402074ddf3a56dc7ea930ac61f442f8f37936, i.e. are you using NCHW or NHWC?

**Comment by paul-mesnilgrente** [comment]
Hi, sorry to answer only now, I was debugging the software for two days and another 2 days off. Apparently, there was a data corruption because of threads that were managed correctly. So the data received by CUDNN was probably corrupted. The problem does not come from you.
Thank you very much.
