### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [facebookarchive/caffe2#1538]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by pietern** [comment]
We don't do any specific packaging for Caffe2 at the moment and have no plans to pick favorites. If you like to add support for this particular one, you can always contribute it and put it in contrib/ for example.
