### ISSUE TITLE
Trying benchmarking ConvNets in PyCaffe2 fails.

### ISSUE THREAD

**Issue by kostyaby** [facebookarchive/caffe2#154]
Hi there!

I'm currently trying to run a Python script located at`caffe2/python/convnet_benchmarks.py`. Unfortunately, it breaks in runtime. My OS is Ubuntu 16.04 this time. It'll nice if you could help me out here. 

I built `caffe2` framework with no GPU support and now executing the following script from the `<caffe2-home>/build` directory: 

```
PYTHONPATH=.:$PYTHONPATH PATH=<caffe2-home>/build/caffe2:$PATH python caffe2/python/convnet_benchmarks.py --batch_size 128 --model AlexNet
```

It fails with the following message: 

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
AlexNet: running forward-backward.
Traceback (most recent call last):
  File "caffe2/python/convnet_benchmarks.py", line 657, in <module>
    Benchmark(model_map[args.model], args)
  File "caffe2/python/convnet_benchmarks.py", line 564, in Benchmark
    workspace.RunNetOnce(model.param_init_net)
  File "/home/kostya_by/git-repos/caffe2/build/caffe2/python/workspace.py", line 151, in RunNetOnce
    return C.run_net_once(StringfyProto(net))
RuntimeError: [enforce fail at operator.cc:106] op. Cannot create operator of type 'XavierFill'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "conv1_w" name: "" type: "XavierFill" arg { name: "shape" ints: 64 ints: 3 ints: 11 ints: 11 } device_option { device_type: 1 cuda_gpu_id: 0 }
```

A help message in the header of the script suggests to add `../gen` path to the `PYTHONPATH` variable, but I believe this suggestion is a bit outdated as no `gen` directories are generated during the current framework installation process.

Thanks in advance!

**Comment by Yangqing** [comment]
Would you mind elaborate a bit?

**Comment by kostyaby** [comment]
@Yangqing Hi! Sorry I mistakenly reported the issue before I even started describing it. The details are added now.

**Comment by Yangqing** [comment]
(closing this for now, please feel free to follow up)
