### ISSUE TITLE
caffe2_pybind11_state.so:  undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs

### ISSUE THREAD

**Issue by xiaobogaga** [facebookarchive/caffe2#1543]
Build successfully, but when run with:

```
python -c "from caffe2.python import core" 2>/dev/null && echo "success" || echo failure
```

shows error:

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
CRITICAL:root:Cannot load caffe2.python. Error: caffe2/python/caffe2_pybind11_state.so: 
undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs
```

I don't know why, although I find little same issue like #197, #346, their solution seems not useful.
help wanted...

platform information:
* centos 7
* python 2.7.5
* gcc 4.8.5

**Comment by landscape-ooo** [comment]
@pietern @Maratyszcza 
` python -m caffe2.python.operator_test.relu_op_test
`

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /home/work/caffe2_bin/caffe2/python/caffe2_pybind11_state_gpu.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs
CRITICAL:root:Cannot load caffe2.python. Error: /home/work/caffe2_bin/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs

```
platform information:

- centos 7
- python 2.7.14 （virutabl_env --no-site-packages ）then (pip install -r  req.txt) where req.txt  is copyfrom   [req.txt](https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud#null__python-dependencies)
- gcc 4.8.5
- cuda 8.0.61  cudnn 6.0.21
- cmake 3.10 
======cmake config 
 `
/home/yourname/caffe_build/cmake/bin/cmake3.10  -DCUB_INCLUDE_DIR=/usr/local/cub/  -DUSE_REDIS=ON -DUSE_GLOO=ON -DUSE_OPENMP=ON -DUSE_MPI=ON -DCMAKE_INSTALL_PREFIX=/home/yourname/caffe_build/caffe2_bin_new1_withcub_success/ -DMPI_CXX_INCLUDE_PATH=/home/yourname/caffe_build/openmpi/include -DMPI_CXX_LIBRARIES=/home/yourname/caffe_build/openmpi/lib -DMPI_C_INCLUDE_PATH=/home/yourname/caffe_build/openmpi/include -DMPI_C_LIBRARIES=/home/yourname/caffe_build/openmpi/lib  ..
`
====os config 
```
(caffe2_vm) [host1 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
(caffe2_vm) [host1~]$ uname -a 
Linux host1 3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
(caffe2_vm) [host1 ~]$ 

```
=====python config 

Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Abhinesh88** [comment]
`from caffe2.python import core`

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /usr/local/caffe2/python/caffe2_pybind11_state_gpu.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs
CRITICAL:root:Cannot load caffe2.python. Error: /usr/local/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKSs

```

Environment - 

- python - 2.7.6
- gcc 4.8.4
- Ubuntu 14.04.3
- cuda 8.0.61
- cudnn 6.0.21

**Comment by s455176** [comment]
Build successfully, and run the following command: 
```
from caffe2.python import core
```
got error: 
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: caffe2/python/caffe2_pybind11_state_gpu.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
CRITICAL:root:Cannot load caffe2.python. Error: caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6caffe26script15CompilationUnit6defineERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

Environment:

- Python 2.7.12
- gcc 5.4.0 
- Ubuntu 16.04.2
- cuda 8.0.61
- cudnn 6.0.21

**Comment by dzhulgakov** [comment]
#1540 is a fix I sent last night, will take a moment to merge

**Comment by dzhulgakov** [comment]
This fixes this build issue for me - please reopen if it's still a problem

**Comment by samarjeet** [comment]
I am still having the same issue 
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
CRITICAL:root:Cannot load caffe2.python. Error: libcaffe2.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by Maratyszcza** [comment]
@samarjeet Could you please try `execstack --clear-execstack /path/to/libcaffe2.so` and tell us if it works?

**Comment by qyou** [comment]
@samarjeet
If you find your *.so files are right in `/usr/local/lib`, try to `ldconfig` your new dynamic lib to make it available at once.
```bash
sudo ldconfig  # then the new addin *.so will be available
```
