### ISSUE TITLE
Failed to build on ubuntu16.04 due to error about image_input_op_gpu.cc.o

### ISSUE THREAD

**Issue by Marxlp** [facebookarchive/caffe2#1556]
Hi, I am building caffe2 from source, per instructions here https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile, and it has problem gpu related stuff. Here is the output:
[ 77%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/image/image_input_op_gpu.cc.o
In file included from /home/marxlp/anaconda3/gcc/include/c++/vector:64:0,
                 from /home/marxlp/anaconda3/gcc/include/c++/bits/random.h:34,
                 from /home/marxlp/anaconda3/gcc/include/c++/random:50,
                 from /home/marxlp/anaconda3/gcc/include/c++/bits/stl_algo.h:65,
                 from /home/marxlp/anaconda3/gcc/include/c++/algorithm:62,
                 from /home/marxlp/github/caffe2/caffe2/core/registry.h:24,
                 from /home/marxlp/github/caffe2/caffe2/core/flags.h:39,
                 from /home/marxlp/github/caffe2/caffe2/core/logging.h:26,
                 from /home/marxlp/github/caffe2/caffe2/core/common_gpu.h:41,
                 from /home/marxlp/github/caffe2/caffe2/image/image_input_op_gpu.cc:17:
/home/marxlp/anaconda3/gcc/include/c++/bits/stl_vector.h: In instantiation of ‘class std::vector<double>’:
/home/marxlp/anaconda3/gcc/include/c++/bits/random.h:5299:22:   required from here
/home/marxlp/anaconda3/gcc/include/c++/bits/stl_vector.h:210:11: internal compiler error: Segmentation fault
     class vector : protected _Vector_base<_Tp, _Alloc>
              ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:1055: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/image/image_input_op_gpu.cc.o' failed
make[3]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/image/image_input_op_gpu.cc.o] Error 1
make[3]: Leaving directory '/home/marxlp/github/caffe2/build'
CMakeFiles/Makefile2:2310: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/marxlp/github/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/marxlp/github/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pietern** [comment]
The error looks like an internal compiler error. Not much we can do on the Caffe2 side.

What are the specs of the machine you are trying to compile on? Perhaps you're running out of memory?

**Comment by Marxlp** [comment]
@pietern ,thanks for your reply. I solved this problem by creating a new virtual environment by python3's venv while my original build was based on anaconda3, which libraries may not be compatible with caffe2.
My machine's specs: Ubuntu 16.06 x64 and GetForce 850M with 4GB memory.
