### ISSUE TITLE
Build with glog, gflags, LMDB, OpenCV on Windows 10

### ISSUE THREAD

**Issue by hiperz** [facebookarchive/caffe2#1568]
I'm trying to build caffe2 with glog, glags, lmdb, opencv together.
but cmake can't find them although I specified their path in build_windows.bat file.

What I found from "FindXXXX.cmake", it calls "find_package(XXXX NO_MODULE)" in case of MSVC always.
Should I create "glog-config.cmake", "gflags-config.cmake" and so on by myself??
or is there any easy way to build them together?
I'm not familiar with CMAKE, so please help me~!

![image](https://user-images.githubusercontent.com/28654452/33548261-fed54a4a-d929-11e7-9d15-4db6c7c8d2f4.png)

**Comment by LMerCy** [comment]
the same problem，build_windows.bat cannot find lmdb，i have compiled lmdb from source. I can find lmdb from make GUI by add
//Path to a file.
LMDB_INCLUDE_DIR:PATH=/Users/your_username/anaconda/envs/ml/include/

//Path to a library.
LMDB_LIBRARIES:FILEPATH=/Users/your_username/anaconda/envs/ml/lib/lmdb.lib
But it still goes wrong
