### ISSUE TITLE
Do we have below things in caffe2?

### ISSUE THREAD

**Issue by kingofoz** [facebookarchive/caffe2#1574]
I know caffe2 has Android/iOS support, but generally mobile devices have very limited storage, memory and computation resources. Does caffe2 have any optimization in these aspects? I know Song Han has a paper about deep compression which is implemented in caffe.

**Comment by orionr** [comment]
Hi @kingofoz. Caffe2 does a variety of things for performance on mobile. Some of this is within Caffe2 (using an NNPACK or MPSCNN backend for example) while others are model-specific. Compression, quantization, or other low-precision adjustments are typically done at the model level. Hope that helps!
