### ISSUE TITLE
Calling operators within an operator

### ISSUE THREAD

**Issue by mohamedadaly** [facebookarchive/caffe2#1593]
Hi

Is there a way to call other "operators" from within the implementation of a new operator? 

Thanks.

**Comment by pietern** [comment]
Only very hacky ways. This is not recommended usage :)

What are you trying to do?

**Comment by mohamedadaly** [comment]
I am trying to implement a custom C++ operator for something similar to Yolo's last detection layer, and it has inside it softmax, sigmoid, exp, and other operators on slices of the input. So I was thinking one way would be to slice the input, and pass them to already-implemented operators.

So I guess a better question: what is the recommended way to "compose" operators in C++ to form a new custom operator?

**Comment by pietern** [comment]
@mohamedadaly I would recommend doing just that. Slice the input and run the ops you need against the different chunks. As long as you use the DAGNet executor and have enough threads, the ops will run in parallel.

**Comment by pietern** [comment]
And sure, you can implement this as a single op and then dispatch from there, but then you're effectively replicating what Caffe2 can already do for you through the DAGNet executor.
