### ISSUE TITLE
make install failed " ../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'" "../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'"

### ISSUE THREAD

**Issue by beanliao** [facebookarchive/caffe2#1601]
make install failed : " ../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'" "../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'"

I used "cd build && cmake .." and "make install". there're errors. 
i tried install NCCL from third-party/nccl folder in caffe2 package. But issue exists.

[ 91%] Linking CXX executable ../bin/logging_test
[ 91%] Linking CXX executable ../bin/common_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cpuid_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cpuid_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/timer_test] Error 1
make[1]: *** [caffe2/CMakeFiles/timer_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/fixed_divisor_test] Error 1
make[1]: *** [caffe2/CMakeFiles/fixed_divisor_test.dir/all] Error 2
[ 91%] Linking CXX executable ../bin/proto_utils_test
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/tutorial_blob] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/tutorial_blob.dir/all] Error 2
make[2]: *** [bin/convert_db] Error 1
make[2]: *** [bin/predictor_verifier] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/convert_db.dir/all] Error 2
make[1]: *** [caffe2/binaries/CMakeFiles/predictor_verifier.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/fatal_signal_asan_no_sig_test] Error 1
make[1]: *** [caffe2/CMakeFiles/fatal_signal_asan_no_sig_test.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/convert_caffe_image_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/convert_caffe_image_db.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/run_plan] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/run_plan.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/inspect_gpus] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/inspect_gpus.dir/all] Error 2
[ 91%] Linking CXX executable ../bin/event_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/init_test] Error 1
make[1]: *** [caffe2/CMakeFiles/init_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/common_test] Error 1
make[1]: *** [caffe2/CMakeFiles/common_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/logging_test] Error 1
make[1]: *** [caffe2/CMakeFiles/logging_test.dir/all] Error 2
[ 92%] Linking CXX executable ../bin/registry_test
CMakeFiles/proto_utils_test.dir/utils/proto_utils_test.cc.o: In function `caffe2::ProtoUtilsTest_SimpleReadWrite_Test::TestBody()':
proto_utils_test.cc:(.text+0x31): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/proto_utils_test] Error 1
make[1]: *** [caffe2/CMakeFiles/proto_utils_test.dir/all] Error 2
[ 92%] Linking CXX executable ../bin/simple_queue_test
[ 92%] Linking CXX executable ../bin/context_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/event_test] Error 1
make[1]: *** [caffe2/CMakeFiles/event_test.dir/all] Error 2
[ 92%] Linking CXX executable ../bin/conv_op_cache_cudnn_test
[ 92%] Linking CXX executable ../../bin/db_throughput
[ 92%] Linking CXX executable ../../bin/print_core_object_sizes
[ 92%] Linking CXX executable ../bin/smart_tensor_printer_test
[ 93%] Linking CXX executable ../../bin/print_registered_core_operators
[ 93%] Linking CXX executable ../../bin/split_db
[ 93%] Linking CXX executable ../../bin/make_mnist_db
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/registry_test] Error 1
make[1]: *** [caffe2/CMakeFiles/registry_test.dir/all] Error 2
[ 93%] Linking CXX executable ../../bin/make_cifar_db
[ 93%] Linking CXX executable ../bin/event_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/simple_queue_test] Error 1
make[1]: *** [caffe2/CMakeFiles/simple_queue_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_op_cache_cudnn_test] Error 1
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[1]: *** [caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/all] Error 2
make[2]: *** [bin/print_core_object_sizes] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/print_core_object_sizes.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/db_throughput] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/db_throughput.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/split_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/split_db.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/make_mnist_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/make_mnist_db.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/context_test] Error 1
make[1]: *** [caffe2/CMakeFiles/context_test.dir/all] Error 2
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/print_registered_core_operators] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/print_registered_core_operators.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/smart_tensor_printer_test] Error 1
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[1]: *** [caffe2/CMakeFiles/smart_tensor_printer_test.dir/all] Error 2
make[2]: *** [bin/make_cifar_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/make_cifar_db.dir/all] Error 2
[ 93%] Linking CXX executable ../bin/stats_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/event_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/event_gpu_test.dir/all] Error 2
[ 93%] Linking CXX executable ../../bin/speed_benchmark
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
[ 94%] Linking CXX executable ../bin/typeid_test
make[2]: *** [bin/stats_test] Error 1
make[1]: *** [caffe2/CMakeFiles/stats_test.dir/all] Error 2
[ 95%] Linking CXX executable ../bin/conv_to_nnpack_transform_test
[ 95%] Linking CXX executable ../bin/common_subexpression_elimination_test
[ 95%] Linking CXX executable ../bin/operator_gpu_test
[ 95%] Linking CXX executable ../bin/boolean_unmask_ops_test
[ 95%] Linking CXX executable ../bin/module_test
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/speed_benchmark] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/speed_benchmark.dir/all] Error 2
[ 95%] Linking CXX executable ../bin/text_file_reader_utils_test
[ 96%] Linking CXX executable ../bin/context_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/typeid_test] Error 1
make[1]: *** [caffe2/CMakeFiles/typeid_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_to_nnpack_transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/conv_to_nnpack_transform_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/common_subexpression_elimination_test] Error 1
make[1]: *** [caffe2/CMakeFiles/common_subexpression_elimination_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_gpu_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/boolean_unmask_ops_test] Error 1
make[1]: *** [caffe2/CMakeFiles/boolean_unmask_ops_test.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/workspace_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/module_test] Error 1
make[1]: *** [caffe2/CMakeFiles/module_test.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/parallel_net_test
CMakeFiles/text_file_reader_utils_test.dir/operators/text_file_reader_utils_test.cc.o: In function `caffe2::TextFileReaderUtilsTest_TokenizeTest_Test::TestBody()':
text_file_reader_utils_test.cc:(.text+0x1e03): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/text_file_reader_utils_test] Error 1
make[1]: *** [caffe2/CMakeFiles/text_file_reader_utils_test.dir/all] Error 2
[ 97%] Linking CXX executable ../../bin/core_overhead_benchmark
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/context_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/context_gpu_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/workspace_test] Error 1
make[1]: *** [caffe2/CMakeFiles/workspace_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/parallel_net_test] Error 1
make[1]: *** [caffe2/CMakeFiles/parallel_net_test.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/graph_test
[ 97%] Linking CXX executable ../bin/observer_test
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/core_overhead_benchmark] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/core_overhead_benchmark.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/operator_schema_test
[ 97%] Linking CXX executable ../bin/net_test
[ 97%] Linking CXX executable ../bin/math_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/graph_test] Error 1
make[1]: *** [caffe2/CMakeFiles/graph_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/observer_test] Error 1
make[1]: *** [caffe2/CMakeFiles/observer_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/net_test] Error 1
make[1]: *** [caffe2/CMakeFiles/net_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_schema_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_schema_test.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/fully_connected_op_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/math_test] Error 1
make[1]: *** [caffe2/CMakeFiles/math_test.dir/all] Error 2
[ 97%] Linking CXX executable ../bin/utility_ops_test
[ 97%] Linking CXX executable ../bin/reshape_op_gpu_test
[ 97%] Linking CXX executable ../bin/operator_fallback_gpu_test
[ 98%] Linking CXX executable ../bin/predictor_test
[ 98%] Linking CXX executable ../bin/conv_transpose_op_mobile_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/fully_connected_op_test] Error 1
make[1]: *** [caffe2/CMakeFiles/fully_connected_op_test.dir/all] Error 2
[ 98%] Linking CXX executable ../bin/string_ops_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/utility_ops_test] Error 1
make[1]: *** [caffe2/CMakeFiles/utility_ops_test.dir/all] Error 2
[ 98%] Linking CXX executable ../bin/transform_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/reshape_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/fully_connected_op_gpu_test
[ 99%] Linking CXX executable ../bin/utility_ops_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_fallback_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/elementwise_op_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/predictor_test] Error 1
make[1]: *** [caffe2/CMakeFiles/predictor_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_transpose_op_mobile_test] Error 1
make[1]: *** [caffe2/CMakeFiles/conv_transpose_op_mobile_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/elementwise_op_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/string_ops_test] Error 1
make[1]: *** [caffe2/CMakeFiles/string_ops_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/fully_connected_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/fully_connected_op_gpu_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/transform_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/utility_ops_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/math_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/elementwise_op_test] Error 1
make[1]: *** [caffe2/CMakeFiles/elementwise_op_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/pattern_net_transform_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/math_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/math_gpu_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pattern_net_transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
[ 99%] Linking CXX executable ../bin/operator_test
[ 99%] Linking CXX executable ../bin/blob_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_test.dir/all] Error 2
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/blob_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
[100%] Linking CXX executable ../bin/blob_test
CMakeFiles/blob_test.dir/core/blob_test.cc.o: In function `caffe2::(anonymous namespace)::TypedTensorTest_BigTensorSerialization_Test<float>::TestBody()':
blob_test.cc:(.text+0x441b1): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
../lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/blob_test] Error 1
make[1]: *** [caffe2/CMakeFiles/blob_test.dir/all] Error 2
[100%] Linking CXX shared module python/caffe2_pybind11_state_gpu.so
[100%] Built target caffe2_pybind11_state_gpu
[100%] Linking CXX shared module python/caffe2_pybind11_state.so
[100%] Built target caffe2_pybind11_state
make: *** [all] Error 2

============
system information:
OS: CentOS Linux release 7.4.1708 (Core) 
Driver: 384.81 (Volta GPU*8)
CUDA: V9.0.176
Cudnn: cudnn-9.0-linux-x64-v7-1
 cmake --version
cmake version 3.10.0

**Comment by pietern** [comment]
Can you post your CMake summary output?

The missing functions are part of NCCL2, so perhaps your install is trying to link an older version.

cc @slayton58

**Comment by beanliao** [comment]
Thanks, @pietern 
CMake summary as below. 
[cmake.log](https://github.com/caffe2/caffe2/files/1548742/cmake.log)

**Comment by pietern** [comment]
I think the following is happening: the `nccl.h` header file of NCCL 2.0 is in your include path, but CMake can't find it so it links the bundled version from third-party. Where do you have NCCL 2 installed?

**Comment by beanliao** [comment]
NCCL is installed In : 
/usr/local/cuda/lib64
And i added below paths in "/root/.bash_profile"
  export PATH
  export PATH=$PATH:/usr/local/cuda-9.0/bin
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64

**Comment by pietern** [comment]
CMake expects to find NCCL in a system path, or in $NCCL_ROOT_DIR.

You can pass the argument `-DNCCL_ROOT_DIR=/usr/local/cuda/` to CMake to fix your build.

If we change the default `NCCL_ROOT_DIR` to be equal to the CUDA root dir then this issue would have not happened in the first place. Are you interested in submitting a PR for this?

**Comment by beanliao** [comment]
Thanks, @pietern 
I tried "cmake -DNCCL_ROOT_DIR=/usr/local/cuda/ .." and i can build caffe2 with NCCL successfully.

**Comment by yaoing** [comment]
thanks to  @pietern .
I make a summary:
1.clean up the build dir
2.go to build directory
3.run command ```sudo cmake ../  -DNCCL_ROOT_DIR=/usr/local/cuda```
4.run command ```sudo make install  DNCCL_ROOT_DIR=/usr/local/cuda -j32```
over~
