### ISSUE TITLE
Bring back cuDNN 5.1 support

### ISSUE THREAD

**Issue by pietern** [facebookarchive/caffe2#1607]
This has disappeared since we're not testing for it, but it might be easy to bring back.

@slayton58 @yangqing Worth it?

**Comment by slayton58** [comment]
I would argue no. 5.1 is a full 2 major versions back

**Comment by Yangqing** [comment]
Fixed by https://github.com/caffe2/caffe2/commit/55f6fea3a93a4e9e1d1256e1ec51afa1d4ce6f70 .
