### ISSUE TITLE
how to use Caffe2 brew.concat()?

### ISSUE THREAD

**Issue by Markovcom** [facebookarchive/caffe2#1615]
If this is a build issue, please fill out the template below.

### System information

* Operating system:
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
******** Summary ********
<please paste summary output here>
```

**Comment by orionr** [comment]
Hi @Markovcom - brew is documented at https://caffe2.ai/docs/brew.html and the Concat operation is detailed at

https://caffe2.ai/docs/operators-catalogue.html#concat

We're looking to update our operator documentation in the near future, but for now feel free to look at the C++ source. Hope that helps.

**Comment by Markovcom** [comment]
@orionr  thanks, I have read the documentation, but there is not example of these operators, so I feel that it is difficult to use these operator.

**Comment by qinhuan** [comment]
@Markovcom  Hi, I encountered the same problem.  Do you know how to use Caffe2 brew.concat()?

**Comment by qinhuan** [comment]
@Markovcom  Hi, in [https://github.com/pytorch/pytorch/blob/master/caffe2/python/helpers/conv.py](https://github.com/pytorch/pytorch/blob/master/caffe2/python/helpers/conv.py) line 356-361, Here is an example. And I use concat() just like:
`concat, concat_dims = model.net.Concat(
        [A, B, C, ……],
        [blob_out,
         "_" + blob_out + "_concat_dims"],
        order=order
    )`
A,B,C means tensor, order is 'NCHW' in detectron.

**Comment by Markovcom** [comment]
@qinhuan thanks.

**Comment by pjavia-iterativescopes** [comment]
It would be really helpful if there is a better documentation where there is more clarity on arguments of definitions while using it with brew or helper.
For example, can I disable bias with brew.conv?
