### ISSUE TITLE
hash_set deprecated

### ISSUE THREAD

**Issue by thatguymike** [facebookarchive/caffe2#162]
From GCC deprecation page https://gcc.gnu.org/onlinedocs/libstdc++/manual/ext_sgi.html

 <hash_map>
 <hash_set>
 <rope>
 <slist>
 <rb_tree>

Annoyingly, this is buried in glog but throws a lot of deprecation warnings during build.  Not sure if we should just report to glog and silence the warning.

**Comment by Yangqing** [comment]
T_T glog :(

I guess we can put an -W message to suppress it? What specific deprecation warning are we getting?

**Comment by Yangqing** [comment]
Actually, it seems that glog already supports unordered_set instead of hash_set:

https://github.com/google/glog/blob/0472b91c5defdf90cff7292e3bf7bd86770a9a0a/src/glog/stl_logging.h.in#L41

Maybe this is due to the ubuntu apt-get package not properly compiled.

**Comment by slayton58** [comment]
We could also move glog to a submodule and compile it ourselves to solve this - slightly heavy-handed though...

**Comment by Yangqing** [comment]
Would you guys be fine with tolerating the warning message? :)

**Comment by pooyadavoodi** [comment]
I would prefer to properly get rid of the warning messages only because they are so many (hundreds) and I always ignore them all. This way we can notice new warning messages which could save us from bugs :)
http://www.cprogramming.com/tutorial/compiler_warnings.html

**Comment by thatguymike** [comment]
We can silence the warning for now.

**Comment by Yangqing** [comment]
@thatguymike Mike - what is the build environment you use? I cannot repro on my 16.04 so I probably need a VM.

**Comment by thatguymike** [comment]
14.04 fully updated

**Comment by Yangqing** [comment]
Should have been fixed in https://github.com/caffe2/caffe2/pull/172 - feel free to reopen this @thatguymike :)
