### ISSUE TITLE
Design Question: How can CPU Operator's Output Tensor Data be accessed by the subsequent GPU Operator as input ?

### ISSUE THREAD

**Issue by simpeng** [facebookarchive/caffe2#1626]
Sorry for disturbing you, while I get stuck on understanding part of Caffe2 memory design in the passing weeks, and searched around the web, but get nothing. So I have to ask someone for that. It would be great if you can share some insights about that. 
 
Op 1 <on CPU> -> op1_output -> op 2 <on GPU> -> op2_output -> op3 <on CPU> -> op3_output

If the example DAGNet (described in the above)  contains 3 operators, the 1st and 3rd one is on CPU for run, the 2nd is on GPU for run. The 1st operator’s output will be written in Memory (Tensor<CPUContext>), so how the 2nd operator get it from GPU Memory as an input? Do we have logic to help copy that?  ( I notice there are functions for copying from CPUContext and CUDAContext, but did not see anyone calls this during DAG net run).

**Comment by pietern** [comment]
This is possible, but you have to manually include copy ops to copy op1 output to GPU and copy op2 output back to CPU. The relevant ops are `CopyCPUToGPU` and `CopyGPUToCPU`.

**Comment by simpeng** [comment]
Got it!!!! thanks @pietern for the clarification! I was assuming all those steps were handled by the DAG run.
