### ISSUE TITLE
How to enable log in Android

### ISSUE THREAD

**Issue by xumengwei** [facebookarchive/caffe2#1641]
I failed to run all models except SqueezeNet on my Android device. Either it's stuck in Predictor intialization or during predicting. I've also noticed some other guys having the same issue but there is no solution yet:
[issue1](https://github.com/caffe2/caffe2/issues/1551),[issue2](https://github.com/caffe2/caffe2/issues/1511),[issue3](https://github.com/caffe2/caffe2/issues/944).
Since I cannot see any log from logcat, I cannot figure out what's going on. So anyone knows how to trigger logs so that I can see things via logcat?

**Comment by pietern** [comment]
Thanks for posting and linking related issue.

@bwasti Do you know what's going on here?

**Comment by xumengwei** [comment]
Hi @pietern, can you ask someone else to give an answer to this since several days have been gone? Even a negative one would help. Thanks.

**Comment by daquexian** [comment]
@pietern gentle ping. [This issue](https://github.com/caffe2/caffe2/issues/944) has already been open for 5 months.

**Comment by daquexian** [comment]
@pietern Sorry to bother. Do you plan to solve these issues? It has been a month since your last comment.

**Comment by jerryzh168** [comment]
we use glog, could you try the flags here? http://rpg.ifi.uzh.ch/docs/glog.html

**Comment by jerryzh168** [comment]
Not sure what are the logs you want to see, if you want to see LOG(INFO) then probably add GLOG_logtostderr=1, for VLOG, then GLOG_v=2, etc.

**Comment by jerryzh168** [comment]
Also, I believe the AI Camera Demo only works for squeezenet(maybe some other classification models that has the same input/output as squeezenet as well?). we don't have a demo that works for all vision models yet.

**Comment by orionr** [comment]
There is also a style transfer example at https://github.com/goldsborough/AICamera-Style-Transfer that is likely a bit more updated than @bwasti's SqueezeNet demo. Jerry is right, though, that we only have these two models supported. Let us know how it goes.

**Comment by Kika-Xumengwei** [comment]
@jerryzh168 @orionr Thanks for your replies, I will check the way you propose. But I am quite confused at the fact that only SqueezeNet is supported. I check the jni code of AI Camera Demo, there's no model-specific code. How come that other models cannot run on Android? Is it because some layers are not supported on Android?

**Comment by orionr** [comment]
Mostly it's about speed / performance and memory. Style transfer and SqueezeNet have been optimized for mobile. In any case, feel free to try any of the models you'd like. You're right that there shouldn't be anything preventing you from trying them. Good luck!

**Comment by orionr** [comment]
Closing. @xumengwei hopefully this helped you!
