### ISSUE TITLE
Unable to make caffe2 on Mac 

### ISSUE THREAD

**Issue by chriszeng87** [facebookarchive/caffe2#1643]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Mac OS 10.13.1
* Compiler version: Apple LLVM version 9.0.0 (clang-900.0.39.2)
* CMake version: 3.9.4
* CMake arguments: -DUSE_CUDA=OFF ..
* Relevant libraries/versions (e.g. CUDA): No

### CMake summary output

```
******** Summary ********
-- General:
--   Git version           : v0.8.1-863-g9e8fa564
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   C++ compiler version  : 9.0.0.9000039
--   Protobuf compiler     : /Users/qyvideo/anaconda3/bin/protoc
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /Users/qyvideo/anaconda3/envs/py2/lib/libpython2.7.dylib
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.11
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
```

and I got this:
[ 96%] Built target split_db
[ 96%] Built target convert_db
[ 97%] Built target speed_benchmark
[ 97%] Built target run_plan
[ 97%] Linking CXX executable ../../bin/make_image_db
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe2::Converter::run() in make_image_db.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/make_image_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/make_image_db.dir/all] Error 2
make: *** [all] Error 2

**Comment by pietern** [comment]
Looks like a mismatch between system OpenCV and Anaconda OpenCV to me...

Since you're using Anaconda I'm assuming you're trying to use OpenCV from Anaconda. It is possible that the compiler uses the headers from Anaconda and the linker uses the library from system, or vice versa. Can you retry with `-DCMAKE_VERBOSE_MAKEFILE=1` and post back the command that makes the linker fail?

**Comment by pietern** [comment]
cc @pjh5

**Comment by chriszeng87** [comment]
I retried with:
cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DUSE_CUDA=OFF ..
sudo make install
and the verbose is like this:
[ 97%] Linking CXX executable ../../bin/make_image_db
cd /Users/qyvideo/work/deep_learning/caffe2/build/caffe2/binaries && /usr/local/Cellar/cmake/3.9.4_1/bin/cmake -E cmake_link_script CMakeFiles/make_image_db.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/make_image_db.dir/make_image_db.cc.o  -o ../../bin/make_image_db  -L/usr/local/lib -Wl,-rpath,/usr/local/lib ../../lib/libcaffe2.dylib /usr/local/lib/libprotobuf.dylib /usr/local/lib/libprotobuf.dylib ../../lib/libnnpack.a ../../lib/libpthreadpool.a /usr/local/lib/libgflags.dylib /usr/local/lib/libglog.dylib /Users/qyvideo/anaconda3/envs/py2/lib/libopencv_highgui.2.4.11.dylib /Users/qyvideo/anaconda3/envs/py2/lib/libopencv_imgproc.2.4.11.dylib /Users/qyvideo/anaconda3/envs/py2/lib/libopencv_core.2.4.11.dylib -lglog -lgflags -lprotobuf 
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe2::Converter::run() in make_image_db.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/make_image_db] Error 1
make[1]: *** [caffe2/binaries/CMakeFiles/make_image_db.dir/all] Error 2
make: *** [all] Error 2

**Comment by pjh5** [comment]
Can you try adding opencv to `conda/meta.yaml` and then running `conda build conda` from your root caffe2 directory?

If you don't need both of these opencv, then uninstalling the one you don't want should also fix the problem.

**Comment by pjh5** [comment]
A recent merge should have made this easier. If you pull the latest code from Github and pass -DCMAKE_PREFIX_PATH=<path/to/your/conda/environment> to your cmake call then the installation should find all of opencv from Anaconda
