### ISSUE TITLE
Windows 10 builds fine but test tools will not run

### ISSUE THREAD

**Issue by ctraina** [facebookarchive/caffe2#1644]
### System information

* Operating system:  Windows 10
* Compiler version:  Visual Studio 2017 (15.4.4)
* CMake version:  3.1.0
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):  CPU only

### CMake summary output
    26 Warning(s)
    0 Error(s)

Time Elapsed 00:08:18.87
"Caffe2 built successfully"

******** Summary ********
Building using the two scripts (build_host_protoc.bat & build_windows.bat) works fine, but whenever I try to run any of the test tools or include caffe2.lib in my own project, I get an error saying that there is a problem with the build ("You might have made a build error...", thrown by the StaticLinkingProtector), even though I am using /WHOLEARCHIVE.  It appears that CPUOperatorRegistry()->Keys().size() is ALWAYS zero.  I don't know how the aforementioned operators are supposed to get registered or why they aren't on my system.

**Comment by Yangqing** [comment]
This is actually a Windows visual studio error at some point:

https://developercommunity.visualstudio.com/content/problem/155384/wholearchive-is-broken-the-linker-is-crazy.html

The most recent visual studio 2017 should have solved this issue.
