### ISSUE TITLE
Question: possible to run part of net? or better to have multiple nets?

### ISSUE THREAD

**Issue by keithmgould** [facebookarchive/caffe2#1649]
In some situations (such as reinforcement learning) you want to run only the forward pass ops repeatedly until an episode is complete, at which point you want to run the backward pass ops multiple times (say for each step of the forward pass).

The problem I'm facing is that if I build forward/backward into the same net, then I can't call `RunNet` during the episode because it will run both forward and backward ops.

With Caffe2, is the strategy to achieve the above to have multiple nets? As in a forward_net and a backward_net? Or is there a way to have a single net, and only run the forward ops until episode is complete, at which point I can have it run the backwards ops? Any examples out there?

PS: I'm aware of the [BlueWhale](https://github.com/caffe2/BlueWhale) project but my question is pretty basic, and the BlueWhale repo is cool but pretty abstract to a newb like me.

**Comment by MisterTea** [comment]
Hey Keith!  I sent you an email but let me paste it here so others can read:

Yes, you can have two nets: one that just does the forward pass and one that forward and backwards. We do this already in BlueWhale: there are times we need to get an action without yet knowing the reward.   There are two ways to do this: you can create a predictor (see the GridworldEvaluator class) or you can query the model directly, which is what we do for openai gym: https://github.com/caffe2/BlueWhale/blob/master/ml/rl/test/gym/open_ai_gym_environment.py#L111

**Comment by keithmgould** [comment]
Thank you Jason! 

Will close this issue.
