### ISSUE TITLE
VGG16 is slower on Titan V than 1080 Ti.  Resnet152 is barely faster

### ISSUE THREAD

**Issue by u39kun** [facebookarchive/caffe2#1653]
I was benchmarking VGG16 and Resnet152 on Caffe2 using NVIDIA's optimized docker image built from Caffe2 0.8.1 for CUDA 9.0 / CUDNN 7.0.0.5 (available at https://ngc.nvidia.com/registry/nvidia-caffe2: nvcr.io/nvidia/caffe2:17.12)

I did the same thing for PyTorch 0.3.0, and Titan V was performing better than 1080 Ti throughout, as expected.
However, with Caffe2, VGG16 is slower on Titan V than 1080 Ti.  For Resnet152, it is barely any faster.  Actually, I ran into a similar issue with PyTorch 0.3.0 (VGG16 being slower on Titan V) until I explicitly set `torch.backends.cudnn.benchmark = True` to enable the auto tuner for CuDNN to use the best algorithm.  I wonder if something similiar is going on with Caffe2, that CuDNN is not using the optimal algorithm.  Is there a similar flag in Caffe2?

My benchmark results and code is here: https://github.com/u39kun/deep-learning-benchmark

**Comment by Maratyszcza** [comment]
In Caffe2 you can pass `cudnn_exhaustive_search` parameter either when initializing `ModelHelper`, or to individual convolution operators (to enable it only for operators with fixed input sizes). See e.g. https://github.com/caffe2/caffe2/blob/master/caffe2/python/convnet_benchmarks.py#L120

**Comment by Maratyszcza** [comment]
@u39kun Did `cudnn_exhaustive_search` solve your problem?

**Comment by u39kun** [comment]
Hi @Maratyszcza Thanks for the tip!  I have not got a chance to test it out yet.  I will close this for now and reopen if I'm still seeing perf issues.
