### ISSUE TITLE
Build caffe2 got error: ld: library not found for -lglog

### ISSUE THREAD

**Issue by freezen** [facebookarchive/caffe2#1659]
It is a build issue, log as below:

**[100%] Linking CXX shared library ../../lib/libcaffe2_module_test_dynamic.dylib
ld: library not found for -lglog
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe2_module_test_dynamic.dylib] Error 1
make[1]: *** [modules/module_test/CMakeFiles/caffe2_module_test_dynamic.dir/all] Error 2
make: *** [all] Error 2**

I can not find the file: ../../lib/libcaffe2_module_test_dynamic.dylib in ~/lib, but I do not why.

### System information

* Operating system: Mac OS High Sierra
* Compiler version: Apple LLVM version 9.0.0 (clang-900.0.39), python 2.7.14
* CMake version: 3.7.0
* CMake arguments: -DUSE_CUDA=OFF
* Relevant libraries/versions (e.g. CUDA): No CUDA

### CMake summary output

* Summary *
-- General:
--   Git version           : v0.8.1-878-g73a22460
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   C++ compiler version  : 9.0.0.9000039
--   Protobuf compiler     : /Users/hua/caffe2/build/bin/protoc
--   CXX flags             :  -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -O2 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python library      : /Users/hua/anaconda2/lib/libpython2.7.dylib
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
CMake Warning at CMakeLists.txt:159 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.

-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   caffe2
   caffe2_module_test_dynamic
   nnpack_reference_layers

This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by pjh5** [comment]
You can't find libcaffe2_module_test_dynamic.dylib because it failed while linking that library.

Are you using anaconda?

Can you find libcaffe2.dylib and libglog with
`
find / -name libcaffe2.dylib 2>/dev/null` 
`
find / -name libglog* 2>/dev/null
`
and then run 
`otool -l <path to libcaffe2.dylib>`

**Comment by freezen** [comment]
Yup, I'm using "anaconda", but maybe there is something wrong with that. But when I run "anaconda" command or "python", it seems right. Logs as below:

-------------------------------------------------------------------------------------------
localhost:build hua$ anaconda
usage: anaconda [-h] [--show-traceback] [--hide-traceback] [-v] [-q] [--color]
                [--no-color] [-V] [-t TOKEN] [-s SITE]
                ...
anaconda: error: too few arguments
localhost:build hua$ find / -name libcaffe2.dylib 2>/dev/null
/Users/hua/caffe2/build/lib/libcaffe2.dylib
localhost:build hua$ find / -name libglog* 2>/dev/null
/usr/local/lib/pkgconfig/libglog.pc
/usr/local/lib/libglog.a
/usr/local/lib/libglog.0.dylib
/usr/local/lib/libglog.dylib
/usr/local/Cellar/glog/0.3.4/lib/pkgconfig/libglog.pc
/usr/local/Cellar/glog/0.3.4/lib/libglog.a
/usr/local/Cellar/glog/0.3.4/lib/libglog.0.dylib
/usr/local/Cellar/glog/0.3.4/lib/libglog.dylib
/Users/hua/Documents/projects/stock_react/node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libglog.so
/Users/hua/Documents/projects/stock_react/node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libglog_init.so
/Users/hua/Documents/projects/stock_react/node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libglog.so
/Users/hua/Documents/projects/stock_react/node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libglog_init.so
/Users/hua/anaconda2/pkgs/glog-0.3.5-0/lib/pkgconfig/libglog.pc
/Users/hua/anaconda2/pkgs/glog-0.3.5-0/lib/libglog.la
/Users/hua/anaconda2/pkgs/glog-0.3.5-0/lib/libglog.a
/Users/hua/anaconda2/pkgs/glog-0.3.5-0/lib/libglog.0.dylib
/Users/hua/anaconda2/pkgs/glog-0.3.5-0/lib/libglog.dylib
/Users/hua/anaconda2/lib/pkgconfig/libglog.pc
/Users/hua/anaconda2/lib/libglog.la
/Users/hua/anaconda2/lib/libglog.a
/Users/hua/anaconda2/lib/libglog.0.dylib
/Users/hua/anaconda2/lib/libglog.dylib
localhost:build hua$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 exit()
localhost:caffe2 hua$ otool -l /Users/hua/caffe2/build/lib/libcaffe2.dylib
/Users/hua/caffe2/build/lib/libcaffe2.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    17       2256 0x00918085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x00000000007a2000
  fileoff 0
 filesize 8003584
  maxprot 0x00000007
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000002ea0
      size 0x00000000006645b2
    offset 11936
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000000667452
      size 0x00000000000005b8
    offset 6714450
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000000667a0c
      size 0x000000000000095c
    offset 6715916
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x0000000000668368
      size 0x00000000000b6694
    offset 6718312
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000000071ea00
      size 0x0000000000028dc0
    offset 7465472
     align 2^6 (64)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000007477c0
      size 0x0000000000045c9f
    offset 7632832
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000000078d460
      size 0x0000000000014b68
    offset 7918688
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 952
  segname __DATA
   vmaddr 0x00000000007a2000
   vmsize 0x000000000003c000
  fileoff 8003584
 filesize 225280
  maxprot 0x00000007
 initprot 0x00000003
   nsects 11
    flags 0x0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x00000000007a2000
      size 0x0000000000000010
    offset 8003584
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 244 (index into indirect symbol table)
 reserved2 0
Section
  sectname __got
   segname __DATA
      addr 0x00000000007a2010
      size 0x0000000000007568
    offset 8003600
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 246 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000000007a9578
      size 0x00000000000007a0
    offset 8033656
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 4003 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA
      addr 0x00000000007a9d18
      size 0x0000000000000698
    offset 8035608
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x00000000007aa3b0
      size 0x000000000000f680
    offset 8037296
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000000007b9a30
      size 0x000000000001ec28
    offset 8100400
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __thread_vars
   segname __DATA
      addr 0x00000000007d8658
      size 0x0000000000000048
    offset 8226392
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000013
 reserved1 0
 reserved2 0
Section
  sectname __thread_data
   segname __DATA
      addr 0x00000000007d86a0
      size 0x0000000000000010
    offset 8226464
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000011
 reserved1 0
 reserved2 0
Section
  sectname __thread_bss
   segname __DATA
      addr 0x00000000007d86b0
      size 0x0000000000000019
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000012
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000000007d86d0
      size 0x0000000000002c48
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000000007db320
      size 0x0000000000002ac8
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000007de000
   vmsize 0x0000000000365000
  fileoff 8228864
 filesize 3555852
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 72
         name /Users/hua/caffe2/build/lib/libcaffe2.dylib (offset 24)
   time stamp 1 Thu Jan  1 08:00:01 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 8228864
    rebase_size 5648
       bind_off 8234512
      bind_size 6448
  weak_bind_off 8240960
 weak_bind_size 459608
  lazy_bind_off 8700568
 lazy_bind_size 10176
     export_off 8710744
    export_size 519672
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 9251344
   nsyms 29140
  stroff 9734572
 strsize 2050144
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 17453
     iextdefsym 17453
     nextdefsym 11361
      iundefsym 28814
      nundefsym 326
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 9717584
  nindirectsyms 4247
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 21470019-B9FE-3648-8DB2-38B2DF65F975
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 10.13
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/opt/gflags/lib/libgflags.2.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 2.1.2
compatibility version 2.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name /usr/local/opt/glog/lib/libglog.0.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libz.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1.2.11
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 400.9.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 08:00:02 1970
      current version 1252.0.0
compatibility version 1.0.0
Load command 15
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 9230416
 datasize 19560
Load command 16
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 9249976
 datasize 1368
localhost:caffe2 hua$ cd build

**Comment by freezen** [comment]
I think the problem is here:
----------------------------------
CMake Warning at CMakeLists.txt:159 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.


-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   caffe2
   caffe2_module_test_dynamic
   nnpack_reference_layers

**Comment by pjh5** [comment]
Your libcaffe2.dylib is looking for glog in /usr/local/opt, but your glog library is in /usr/local/lib (and you seem to have one under anaconda too).

Since you're using anaconda, try installing by running `conda build conda` from your caffe2 root directory (I think this will default to the copy of glog installed under anaconda). 

Or you can probably fix this by adding symlinks from /usr/local/opt/glog/lib to /usr/local/lib.

**Comment by freezen** [comment]
My glog lib path is "/usr/local/opt/glog", it is already a symlinks. You can see my capture. It link to glog root path :"/usr/local/Cellar/glog". So why caffe can not find it?
![capture](https://user-images.githubusercontent.com/1651050/34649010-e368c2ba-f3e0-11e7-9b84-aca6938f3d36.png)

**Comment by ipchikin** [comment]
@pjh5 I have tried conda build conda, but there is no build folder created. I found a tar file in /usr/local/anaconda2/conda-bld/osx-64/ instead. I unzipped the file and try to run python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" as your new instruction said. Failure returned.
This is the build folder structure
<img width="772" alt="screen shot 2018-01-08 at 5 33 44 pm" src="https://user-images.githubusercontent.com/7951697/34665210-4a1313e4-f49a-11e7-9dd4-277fc5bc6146.png">

**Comment by pjh5** [comment]
@freezen Sorry I misunderstood your problem at first. You're not able to find glog after libcaffe2.dylib has been built succesfully and installed; cmake then tries to link a simple module import test against caffe2, and it is this part that can't find glog. The "-lglog" in the error message means that it's looking for glog relative to the cmake prefix at that time (so the path to glog in libcaffe2.dylib is not relevant, sorry about the confusion). If you git pull, this "-lglog" flag has been changed to the full path to glog that is used in the rest of the cmake process. I think a git pull should fix this. Or, if you don't care about linking against caffe2 in the future you can just delete the last line of CMakeLists.txt (that adds the modules/module_test subdirectory).

**Comment by pjh5** [comment]
@ipchikin `conda build conda` only makes an ephemeral build folder. That command should be able to work with just the library installed, but some necessary flags may be missing from the installation instructions. I am investigating this now. 

If you want the build directory, you can try removing the final two lines from conda/build.sh and calling the script manually like
`CONDA_PREFIX=<your anaconda root directory> ./conda/build.sh`
If you call the script manually like this then you will have to make sure that the dependecies in conda/meta.yaml are all installed, but they should be if you have ever called `conda build` in the past.

**Comment by pjh5** [comment]
@ipchikin everything should work after running
`conda install caffe2 --use-local`
