### ISSUE TITLE
'caffe2/proto/caffe2.pb.h' file not found

### ISSUE THREAD

**Issue by varunlakshmanan** [facebookarchive/caffe2#1663]
The file is not found in logging.h. I have looked at other issues on this topic but none of them have a satisfactory answer. What am I missing here?

**Comment by varunlakshmanan** [comment]
In the end, I had to build the Windows version and transfer the file from there to the iOS installation.

**Comment by LaurentBerger** [comment]
@varunlakshmanan how do you solve your issue?

**Comment by varunlakshmanan** [comment]
@LaurentBerger I built the Windows version of Caffe2. All the files that I was missing were generated there, so I then transferred them to the folder of my iOS Caffe2 installation, and the errors went away.

**Comment by lllidan-yuandian** [comment]
you can find the solution in here: 
https://caffe2.ai/docs/cplusplus_tutorial.html
