### ISSUE TITLE
Insufficient documentation for the RecurrentNetwork op

### ISSUE THREAD

**Issue by MrGeva** [facebookarchive/caffe2#1664]
The [RecurrentNetwork op documentation](https://caffe2.ai/docs/operators-catalogue.html#recurrentnetwork) does not describe the op attributes and mechanisms.
Without proper documentation of all the attributes it is hard to use this op.

**Comment by orionr** [comment]
Hi @MrGeva - thank you for the feedback. We are looking to update the operator documentation as soon as possible. Definitely on our priority list.
