### ISSUE TITLE
How to build a image dataset for use in iOS

### ISSUE THREAD

**Issue by varunlakshmanan** [facebookarchive/caffe2#1672]
I have successfully built Caffe2, but am not sure how to use my own dataset of training images in the Xcode project (building for iOS). I've looked [here](https://caffe2.ai/docs/tutorial-create-your-own-dataset.html), but that seems to only refer to Python, and not Objective-C/Swift. How can I build a dataset of my own training images for use in a Caffe2 iOS application?

**Comment by orionr** [comment]
Hi @varunlakshmanan. Happy to help!

With caffe2, you typically will do your training with the image dataset you talk about on a server. For example, a Ubuntu server with a NVIDIA CUDA graphics card on EC2 is a great option. Once the model is trained you'll then export it to run on iOS. You can find more details on that and a demo at

https://caffe2.ai/docs/mobile-integration.html

Good luck!
