### ISSUE TITLE
SummarizeOp fails if using core.NameScope

### ISSUE THREAD

**Issue by pooyadavoodi** [facebookarchive/caffe2#168]
- core.NameScope adds a '/' to blobnames.
- SummarizeOp tries to create a file for each blob.
- In Linux, filenames can't have '/' in them.
- Thus, SummarizeOp fails when creating a file.

The error is like this:
`RuntimeError: [enforce fail at summarize_op.h:32] log_file_->good(). Failed to open summarize file for tensor gpu_0/conv_w. rdstate() = 4 `

We may need a regex solution for this operator as well.

**Comment by Yangqing** [comment]
Oh shoot, you are right - things get wrong because the "/" slash needs to be replaced. Maybe we can do a find and replace with "#"? I hope no one uses # in their variable names.

**Comment by pooyadavoodi** [comment]
I guess we want to keep the name scope in filename because different GPUs could have different stats. 

So, I agree we should replace '/' with something in SummarizeOp
Or simply change the separator '/' with another char.
