### ISSUE TITLE
please complete Slice operator

### ISSUE THREAD

**Issue by breadbread1984** [facebookarchive/caffe2#1680]
I am working on image segmentation. Most recent segmentation algorithm use crop operation. Even caffe1 has crop layer, but I found surprisely caffe2 has only partly functional crop operation provided by Slice operator. Please improve Slice operator to support multi dimension cropping. It is an important operation after FCN become popular and I dont want to downgrade to caffe1 for only one missing function. Thanks

**Comment by pietern** [comment]
Agree this is a good addition. We have been doing this asynchronously on the Python side so far (through numpy). I'm closing this in favor of the pull request you opened in #1699.
