### ISSUE TITLE
can i use caffe2 in ios 8?

### ISSUE THREAD

**Issue by sunfei** [facebookarchive/caffe2#1682]
i failed to compile  when  deployment target  is 8.x, and in ios 9.x has an error:

dyld: Symbol not found: _OBJC_CLASS_$_MTLFunctionConstantValues
  Referenced from: /var/containers/Bundle/Application/05C2F6EC-4E83-4C2F-B6F8-F0F862D246F4/testcaffe.app/testcaffe
  Expected in: /System/Library/Frameworks/Metal.framework/Metal
 in /var/containers/Bundle/Application/05C2F6EC-4E83-4C2F-B6F8-F0F862D246F4/testcaffe.app/testcaffe

**Comment by Maratyszcza** [comment]
Caffe2 Metal backend uses MPSCNN kernels, which were introduced in iOS 10. For earlier iOS versions, configure Caffe2 with `-DUSE_METAL=0` to disable Metal backend.
