### ISSUE TITLE
libcaffe2.so error when importing caffe2.python.core

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1688]
I am following the instruction in [here](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb). But when I try to import caffe2.python.core in Jupyter Notebook, it gives following errors:

CRITICAL:root:Cannot load caffe2.python. Error: libcaffe2.so: cannot open shared object file: No such file or directory
An exception has occurred, use %tb to see the full traceback.
SystemExit: 1

This works fine in python console. But when running in Ipynb, it shows the above error.
When I run %tb, the detailed messages are as follows:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/caffe2/python/_import_c_extension.py in <module>()
     27     try:
---> 28         from caffe2.python.caffe2_pybind11_state_gpu import *  # noqa
     29         if num_cuda_devices():  # noqa

ModuleNotFoundError: No module named 'caffe2.python.caffe2_pybind11_state_gpu'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/usr/local/caffe2/python/_import_c_extension.py in <module>()
     39         try:
---> 40             from caffe2.python.caffe2_pybind11_state import *  # noqa
     41         except ImportError as e:

ImportError: libcaffe2.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
<ipython-input-2-034c148775d0> in <module>()
----> 1 from caffe2.python import core

/usr/local/caffe2/python/core.py in <module>()
     28 
     29 from caffe2.proto import caffe2_pb2
---> 30 from caffe2.python import scope, utils, workspace
     31 from caffe2.python.control_ops_grad import \
     32     gen_do_gradient, gen_if_gradient, gen_while_gradient

/usr/local/caffe2/python/workspace.py in <module>()
     35 from caffe2.python import scope, utils
     36 
---> 37 import caffe2.python._import_c_extension as C
     38 
     39 logger = logging.getLogger(__name__)

/usr/local/caffe2/python/_import_c_extension.py in <module>()
     42             logging.critical(
     43                 'Cannot load caffe2.python. Error: {0}'.format(str(e)))
---> 44             sys.exit(1)
     45 
     46 # libcaffe2_python contains a global Workspace that we need to properly delete

SystemExit: 1

**Comment by orionr** [comment]
Hi @sueyhan. How did you install `caffe2` and `jupyter`? Did you use conda or pip? In both cases you should be able to do

```
cd caffe2/caffe2/python/tutorials
./start_ipython_notebook.sh
```

to start the Jupyter server with the library paths setup correctly. It looks like your load paths aren't set when you're running that notebook.

Let me know if that helps.

**Comment by ghost** [comment]
Thanks for your help! It seems like the PYTHONPATH problem. I have already had it fixed by running the above commands

**Comment by pjh5** [comment]
What instructions did you follow to build caffe2?
