### ISSUE TITLE
caffe2 cannot be imported from IPython but running well in Python

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1689]
I am still trying to follow instructions [here](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb)

Interesting thing is, after installing caffe2, its running well in python console. But when running in Jupyter notebook, which uses exactly the same python, it gives import error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-92caf88aa2df> in <module>()
      1 get_ipython().magic(u'matplotlib inline')
----> 2 from caffe2.proto import caffe2_pb2
      3 import numpy as np
      4 import skimage.io
      5 import skimage.transform

ImportError: No module named caffe2.proto

**Comment by orionr** [comment]
Hi @sueyhan - did you run Jupyter with

```
cd caffe2/caffe2/python/tutorials
./start_ipython_notebook.sh
```

Just verifying.

**Comment by ghost** [comment]
Thanks for your help! It seems like the PYTHONPATH problem. I have already had it fixed by running the above commands
