### ISSUE TITLE
Can not find caffe2_pybind11_state file after building successfully

### ISSUE THREAD

**Issue by MabinogiX** [facebookarchive/caffe2#1694]
* Operating system: Win10
* Compiler version: VS 2017
* CMake version: 3.10.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): CUDA9.1  cudnn9.1

### CMake summary output
```
"Caffe2 built successfully"
```

I executed build_windows.bat and built caffe2 successfully, but I cannot find any file named caffe2_pybind11_state, including caffe2_pybind11_state.dll and caffe2_pybind11_state.pyd in all the locations in my hard driver. Is this a bug?

**Comment by leemgs** [comment]
> but I cannot find any file named caffe2_pybind11_state, 

Note that you have to install [pybind11](https://github.com/pybind/pybind11) as a prerequisite to get  `caffe2_pybind11_state.{dll|so}`.

**Comment by MabinogiX** [comment]
In the official guidance to install caffe2 on windows 10, I find nothing about pybind11

**Comment by leemgs** [comment]
> In the official guidance to install caffe2 on windows 10, I find nothing about pybind11

If you try to install caffe2 from source on windows 10+, refer to https://github.com/pybind/python_example#windows-runtime-requirements
Then, I recommend that you contribute your experience by submitting an appropriate PR after fixing this issue in windows10.

**Comment by amh228** [comment]
I also found nothing about installing pybind in the perquisites docs.

Or Eigen..etc. There are mandatory and optional perquisites listed, are there others apart from those two lists?

**Comment by leemgs** [comment]
@amh228, [**FYI**] From my experience, your issue happens because the Caffe2 community bundles required packages in ./third_party/ folder to build Caffe2 from source. 
 * Eigen - https://github.com/RLovelett/eigen/tree/4e79cb69b9425f5f8c3a84be4350d4ab75b5fd9d
 * Pybind11 - https://github.com/pybind/pybind11/tree/86e2ad4f77442c3350f9a2476650da6bee253c52

**Comment by orionr** [comment]
@Mabinogiysk this is a silly question, but when you cloned the Caffe2 source repo did you use

```
git clone --recursive https://github.com/caffe2/caffe2.git
```

The `--recursive` is very important because it will clone all of the submodules inside `third_party`, which is where eigen and pybind11 should then be picked up by CMake.

If that's not the issue please paste your full build logs here and we'll take a look. Thanks.

**Comment by amh228** [comment]
Thanks! I tried that now, still getting some fatal errors even though like
you said it seems Eigen is now being downloaded. I have all the required
libraries and then some. It's pretty weird.

Here's a sample error:
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\filler_op.cc) [C:\Users\ahmed\
Source\caffe2\build\caffe2\caffe2.vcxproj]
  find_op.cc
  flatten_op.cc
  flexible_top_k.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\flexible_top_k.cc) [C:\Users\a
hmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  free_op.cc
  fully_connected_op.cc
  fused_rowwise_8bit_conversion_ops.cc
  gather_ranges_to_dense_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\fully_connected_op.cc) [C:\Use
rs\ahmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  generate_proposals_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\fused_rowwise_8bit_conversion_
ops.cc) [C:\Users\ahmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  given_tensor_fill_op.cc
  glu_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\gather_ranges_to_dense_op.cc)
[C:\Users\ahmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  gru_unit_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/eigen_utils.h(6): fatal error
C1083: Cannot open include file: 'Eigen/Core':
No such file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\generate_proposals_op.cc
) [C:\Users\ahmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  h_softmax_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\given_tensor_fill_op.cc) [C:\U
sers\ahmed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  half_float_ops.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\gru_unit_op.cc) [C:\Users\ahme
d\Source\caffe2\build\caffe2\caffe2.vcxproj]
  if_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\h_softmax_op.cc) [C:\Users\ahm
ed\Source\caffe2\build\caffe2\caffe2.vcxproj]
  im2col_op.cc
C:\Users\ahmed\Source\caffe2\caffe2/utils/math.h(36): fatal error C1083:
Cannot open include file: 'Eigen/Core': No suc
h file or directory (compiling source file
C:\Users\ahmed\Source\caffe2\caffe2\operators\im2col_op.cc) [C:\Users\ahmed\
Source\caffe2\build\caffe2\caffe2.vcxproj]

**Comment by amh228** [comment]
UPDATE I finally got the build to work. I set the Eigen3_DIR to the third
party subfolder for eigen, and ignored the errors at the beginning of the
cmake output about eigen.cmake configs not being found. I also put in
environment PATH variables for that same eigen path, and made sure to run
the caffe2 build with an admin priv shell (powershell).

It works.

Thanks for the tip about --recursive.



pybind is also in the third party library as you mentioned

**Comment by orionr** [comment]
Thanks @amh228 for the update! Hopefully it helps others. We're definitely working on improving the Windows install process, but it's great to hear you got it running.

I'm going to close this out, but feel free to open other issues if you have them.

**Comment by RyanCV** [comment]
@orionr @amh228 I use `git clone --recursive https://github.com/caffe2/caffe2.git` but got the following error: 
```
Checking connectivity... done.
Submodule path 'third_party/cub': checked out '285aeebaa34b0e8a7670867a2e66c1a52d998d6a'
Cloning into 'third_party/eigen'...
Username for 'https://github.com':  <-----why it requires username and pwd??
Password for 'https://@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path 'third_party/eigen' failed
```
I checked and found 'https://github.com/RLovelett/eigen.git/' is not a valid link any more. Anyone know how to solve this problem? Thanks.

**Comment by RyanCV** [comment]
@leemgs 

> Eigen - https://github.com/RLovelett/eigen/tree/4e79cb69b9425f5f8c3a84be4350d4ab75b5fd9d

This is not valid any more.

**Comment by orionr** [comment]
Hi @RyanCV - you should actually be cloning from the PyTorch repo now. So that would be `git clone --recursive https://github.com/pytorch/pytorch.git`. Please see the updated steps at https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#clone--build

**Comment by RyanCV** [comment]
@orionr thanks for your information.
