### ISSUE TITLE
Problem with running Multibox implementation

### ISSUE THREAD

**Issue by iurii-milovanov** [facebookarchive/caffe2#17]
Dear Yangqing,

Right now our data science group is working on image recognition project for one of our customers. Towards this, we tried to test the implementation of Google Multibox algorithm you had published on github using latest caffe2 build.

Unfortunately, we faced with an issue which looks like a problem with caffe2 framework. I will really appreciate your assistance with solving of this issue. Please let me know if you need any additional information.

Here is some debug information:

---

RuntimeError                              Traceback (most recent call last)
<ipython-input-6-32ba0248c8c0> in <module>()
     22 # Specify the device option of the network, and then create it.
     23 net.device_option.CopyFrom(DEVICE_OPTION)
---> 24 workspace.CreateNet(net)

/home/ubuntu/caffe2/gen/pycaffe2/workspace.py in CreateNet(net, input_blobs)
     96   for input_blob in input_blobs:
     97     CreateBlob(input_blob)
---> 98   return cc_CreateNet(StringfyProto(net))
     99 
    100 def RunOperatorOnce(operator):

RuntimeError: Cannot create network. See console log for error messages.

I1015 00:09:11.957850 30545 workspace.cc:46] Initializing network multibox
Key Conv not found.
Available keys:
Registry key: Allreduce
Registry key: Broadcast
Registry key: Iter
Registry key: LearningRate
A total of 4 registered keys.
Returning null pointer.Key Clip not found.
Available keys:
Registry key: Allreduce
Registry key: Broadcast
Registry key: Iter
Registry key: LearningRate
A total of 4 registered keys.
Returning null pointer.Key MaxPool not found.
Available keys:
Registry key: Allreduce
Registry key: Broadcast
Registry key: Iter
Registry key: LearningRate
A total of 4 registered keys.
Returning null pointer.Key Conv not found.
Available keys:
Registry key: Allreduce
Registry key: Broadcast
Registry key: Iter
Registry key: LearningRate
A total of 4 registered keys.

Thanks,
Iurii

**Comment by Yangqing** [comment]
It seems that caffe2 is not built completely - do you have missing dependencies? Could you post the output from running "make"?

**Comment by iurii-milovanov** [comment]
Hi Yangqing,

Thank you so much for your swift response. It definitely was a problem with some missing dependencies. I'd rebuilt "caffe2" from scratch and everything went well.

Regards,
Iurii

**Comment by michaelholm-ce** [comment]
Will you please share what dependencies you are missing?  I built caffe2 from scratch as well, but I am still having the exact same error as you.  Thank you for your help.
