### ISSUE TITLE
Build issues persist/Eigen/Opencv not found

### ISSUE THREAD

**Issue by amh228** [facebookarchive/caffe2#1703]
This is on Windows 10. I have OpenCV 1.65 installed and included in the PATH as OPENCV_DIR (and, separately  working in Visual Studio 2017, which is also installed) but the build system for Caffe2 can't seem to find it. 

Eigen seems to also cause a problem and crash the build_windows.bat build

I checked the third party folder that comes from caffe2 git repo and it is empty.

Eigen is not listed as a perquisite in your docs. What should I do?

Thanks. 

### System information

* Operating system: Win 10 x64 
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
******** Summary ********
-- Use custom protobuf build.
-- Using protobuf compiler C:\Users\ahmed\Source\caffe2\scripts\..\build_host_protoc\bin\protoc.exe
-- The BLAS backend of choice:Eigen
CMake Warning at cmake/Dependencies.cmake:241 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by amh228** [comment]
Update: I downloaded the latest Eigen3 as a hack solution and installed it by registering the path as Eigen3_DIR, in system environment variables, and actually running cmake in a directory above the one containing the Eigen3 cmake files that caffe2 builds look for. You MUST actually cmake the eigen3, it is not enough to register the main directory because it leads to incomplete configuration files. 



EDIT: Still can't compile because for some reason caffe2 build still can't see Eigen/Core and the other header files. 

I even included the %Eigen3_DIR%\eigen3   in PATH but still Eigen/Core cannot be found by the caffe2 build. Totally stumped here. This was nowhere in the installation docs.

**Comment by LaurentBerger** [comment]
About Eigen3 I installed Eigen3 using cmake and give full path Eigen3_Dir =G:/Lib/install/Eigen3/share/eigen3/cmake

**Comment by amh228** [comment]
This was a Windows install. The Eigen3_DIR I ended up providing as a environment variable in PATH was the default one under the third_party folder of cafffe2.

Notes on fixing issues:

--Run command prompts as Admin
--When in doubt, add paths to PATH or to the CMAKE paths if you can find the right file (good luck)
--When you clone the git repo caffe2, use the --recursive option or you wont get pybind and eigen downloaded under caffe2 (and all the others needed)
--Ignore initial errors from cmake and wait patiently for the build to finish; also delete the cmake Cache file under build folder every time you build if you want to be sure your changes are reflected.


Thanks folks.
