### ISSUE TITLE
undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'

### ISSUE THREAD

**Issue by DavidBrayford** [facebookarchive/caffe2#1705]
### System information
* Operating system:
SLES 12
* Compiler version:
gcc 7.2.0
* CMake version:
3.6.1
* CMake arguments:
-fpic
* Relevant libraries/versions (e.g. CUDA):
MKL, MPI, opencv protobuf, leveldb, snappy, lmdb, glog, gflags

### CMake summary output

```
******** Summary ********
I get the following linking error when trying to build caffe2 from the github repository

Linking CXX executable ../../bin/tutorial_blob
cd /home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build/caffe2/binaries && /lrz/mnt/sys.x86_sles12/tools/cmake/3.6.1/bin/cmake -E cmake_link_script CMakeFiles/tutorial_blob.dir/link.txt --verbose=1
/lrz/sys/compilers/gcc/7.2.0/bin/c++   -fpic -Wno-deprecated -fopenmp -std=c++11 -O2 -fPIC -Wno-narrowing -O3 -DNDEBUG -fpic   -Xlinker --enable-new-dtags  -Xlinker -rpath  -Xlinker /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt  -Xlinker -rpath  -Xlinker /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib  -Xlinker -rpath  -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt  -Xlinker -rpath  -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib  CMakeFiles/tutorial_blob.dir/tutorial_blob.cc.o  -o ../../bin/tutorial_blob  -L/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build/release/lib  -L/home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib -rdynamic -Wl,--no-as-needed ../../lib/libcaffe2.so -Wl,--as-needed ../../release/lib/libprotobuf.so ../../release/lib/libprotobuf.so -pthread -pthread -lmkl_rt ../../release/lib/libgflags.a /home/hpc/pr28fa/di72giz/CAFFE/GLOG/glog/build/release/lib64/libglog.a -llmdb ../../release/lib/libleveldb.so ../../release/lib/libsnappy.so /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib/libopencv_highgui.so.3.1.0 /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpicxx.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpifort.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt/libmpi.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpigi.a -ldl -lrt -lpthread -lgloo -lgloo -lgcc_s -lgcc -ldl /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib/libopencv_imgcodecs.so.3.1.0 /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib/libopencv_imgproc.so.3.1.0 /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib/libopencv_core.so.3.1.0 /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpicxx.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpifort.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt/libmpi.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpigi.a -ldl -lrt -lpthread -lpthread -Wl,-rpath,/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build/release/lib:/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build/lib:/home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib:/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib:/lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib:/lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt: -Wl,-rpath-link,/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/lib 
../../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
../../lib/libcaffe2.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status

**Comment by pietern** [comment]
@DavidBrayford Where do LevelDB and protobuf come from? The command line you included says it's from `../../release`, which is where I think the mismatch between headers and library is coming from.

**Comment by DavidBrayford** [comment]
I built the libraries in another directory and copied then into a single directory for convenience. I will modify the link line to point to the original directories for the packages and try again.

**Comment by DavidBrayford** [comment]
I've either rebuilt the libraries or used anaconda to install the additional libraries and still get a linking error below:

/lrz/sys/compilers/gcc/7.2.0/bin/c++   -fpic -std=c++11 -fopenmp -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -O3 -DNDEBUG   -Xlinker --enable-new-dtags  -Xlinker -rpath  -Xlinker /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt  -Xlinker -rpath  -Xlinker /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib  -Xlinker -rpath  -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt  -Xlinker -rpath  -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib  CMakeFiles/tutorial_blob.dir/tutorial_blob.cc.o  -o ../../bin/tutorial_blob  -L/home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib -rdynamic -Wl,--no-as-needed ../../lib/libcaffe2.so -Wl,--as-needed /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libprotobuf.so -pthread -pthread -lmkl_rt /home/hpc/pr28fa/di72giz/CAFFE2/GFLAGS/gflags/build/release/lib/libgflags.so /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libglog.so -llmdb /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libleveldb.so /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libsnappy.so /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/librocksdb.so /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libopencv_highgui.so.3.1.0 /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpicxx.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpifort.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt/libmpi.so /lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/libmpigi.a -ldl -lrt -lpthread -lgcc_s -lgcc -ldl /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libopencv_imgcodecs.so.3.1.0 /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libopencv_imgproc.so.3.1.0 /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib/libopencv_core.so.3.1.0 -Wl,-rpath,/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build/lib:/home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib:/home/hpc/pr28fa/di72giz/CAFFE2/GFLAGS/gflags/build/release/lib:/lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib:/lrz/sys/intel/studio2017_u4/impi/2017.3.196/intel64/lib/release_mt: -Wl,-rpath-link,/home/hpc/pr28fa/di72giz/Anaconda/anaconda3/lib 
../../lib/libcaffe2.so: undefined reference to `rocksdb::Slice::ToString[abi:cxx11](bool) const'
../../lib/libcaffe2.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::DB**)'
../../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libcaffe2.so: undefined reference to `rocksdb::Status::ToString[abi:cxx11]() const'
../../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
../../lib/libcaffe2.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
caffe2/binaries/CMakeFiles/tutorial_blob.dir/build.make:117: recipe for target 'bin/tutorial_blob' failed
make[2]: *** [bin/tutorial_blob] Error 1
make[2]: Leaving directory '/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build'
CMakeFiles/Makefile2:1074: recipe for target 'caffe2/binaries/CMakeFiles/tutorial_blob.dir/all' failed
make[1]: *** [caffe2/binaries/CMakeFiles/tutorial_blob.dir/all] Error 2
make[1]: Leaving directory '/home/hpc/pr28fa/di72giz/CAFFE2/caffe2/build'
Makefile:141: recipe for target 'all' failed

**Comment by pjh5** [comment]
Do you want to use both rocksdb and leveldb?

Do you have multiple versions of rockdb or leveldb on your machine?

Did you delete your build folder after you rebuilt the libraries to clear any caching effects?

If you are using Anaconda, you might want to try https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#anaconda-install-path . It's only been tested on ubuntu but it might work for sles with minimal changes. You will have to remove any -DUSE_XXX=OFF flags in conda/build.sh that you don't want and add packages you do want to the requirements lists in conda/meta.yaml

**Comment by pjh5** [comment]
I will move this discussion to #1980
