### ISSUE TITLE
Kernel always die while following the tutorial instruction

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1710]
I have successfully installed caffe2 onto my ubuntu. But when I tried to follow the [instrution](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb), the jupyter notebook always die while executing the following code:

`p = workspace.Predictor(init_net, predict_net)`
`results = p.run([img])`

I also tried it in python console, and the same thing happened. The console just exit itself with error info:

> Segmentation fault (core dumped)

Can somebody help explain to me what's going wrong?

**Comment by orionr** [comment]
Just as a sanity check can you try and run the MNIST tutorial first?

https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb

If that works it might have something to do with the models you are trying to load.

**Comment by ghost** [comment]
That works fine on my system. It seems that the models might be the problem. But it's still a little weird since I download the models using exactly the code in the tutorial:

`python -m caffe2.python.models.download -i squeezenet`

**Comment by orionr** [comment]
FYI to @pietern - it's likely time to get the python notebooks run automatically as part of CI.
