### ISSUE TITLE
How to build for Aarch64 with neon

### ISSUE THREAD

**Issue by breadbread1984** [facebookarchive/caffe2#1713]
I changed ANDROID_ABI to arm64-v8a but cant compile nnpack and mobilegl without neon support. How shall I setup the variable to enable neon?

**Comment by Maratyszcza** [comment]
#1740 would fix ARM64 Android build. Use `scripts/build_android.sh -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang`

**Comment by sanallen** [comment]
@breadbread1984 The device based on arm64-v8a, Neon is opened by default

**Comment by breadbread1984** [comment]
Thanks, I will try the fixed cmake script.

**Comment by Maratyszcza** [comment]
Should be fixed with bc3da2301d58548a721a2317514536e844adfc7b. Use `scripts/build_android.sh -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang` to build for ARM64.
