### ISSUE TITLE
How to create Caffe2-type lmdb?

### ISSUE THREAD

**Issue by xinqinglxl** [facebookarchive/caffe2#1735]
Hi, I'm new to Caffe2 and now working on my toy Caffe2 demo.
Firstly. I created a lmdb train-database followed the guide bellow.
-----------
 caffe2/python/examples/lmdb_create_example.py
ps: I read data from a real image instead of the dummy data in the guide.
-----------
When I use the lmdb database to train my AlexNet it seems works well.
In this AlexNet-demo I read the lmdb with the following method
```
def AddInput(model, batch_size, db, db_type):
    data_uint8, label = model.TensorProtosDBInput(
        [], ["data_uint8", "label"], batch_size=batch_size,
        db=db, db_type=db_type)
    data = model.Cast(data_uint8, "data", to=core.DataType.FLOAT)
    data = model.StopGradient(data, data)
    return data, label
```
After that I tried to train my model with multi-gpu followd the guide bellow.
---------------
caffe2/python/tutorials/Multi-GPU_Training.ipynb
---------------

But when I tried to read data from lmdb, an error occurred.
ps: This time I read the lmdb as the following method
```
def add_image_input_ops(model):
    # utilize the ImageInput operator to prep the images
    data, label = brew.image_input(
        model,
        reader,
        ["data", "label"],
        batch_size=batch_per_device,
        color=1,
        #use_caffe_datum=1,
        scale=256,
        crop=227,
        db_type='lmdb',
        is_test=False,
        mirror=1
    )
    # prevent back-propagation: optional performance improvement; may not be observable at small scale
    data = model.net.StopGradient(data, data)

reader = train_model.CreateDB(
    "train_reader",
    db=db_file,
    db_type='lmdb',
)
```
Then I thought maybe the lmdb I used is an caffe_datum lmdb, and I set the use_caffe_datum=1,
but it seems still didn't work, no error occurred this time, but the data read from lmdb became all zero data.

Then I download the lmdb from https://download.caffe2.ai/databases/resnet_trainer.zip and read it,
it seems the data in resnet_trainer.zip/imagenet_cars_boats_train is not float type data like I created but 
bytes-type like this:
[ '\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\x00\xff\xdb\x00C\x00\x03\x02\x02\x03\x02\x02\x03\x03\x03\x03\x04\x03\x03\x04\x05\x08\x05
... ...

Can anyone provide a way to create Caffe2-type lmdb that I can read it with brew.image_input

**Comment by breadbread1984** [comment]
if you are interested in how to create lmdb for caffe2 with C++. You can have a look at [this program](https://github.com/breadbread1984/Caffe2-C-LSTM-demo/blob/master/src/generate_trainset.cpp).

**Comment by xinqinglxl** [comment]
@breadbread1984 thanks for the reply.
By the way, since I have caffe installed, and the caffe provided a tool that can create lmdb from images(convert_imageset?),
I want to know whether I can create a lmdb with that tool, and use it in my Caffe2 multi-gpus training.
in other words, whether I can read the caffe-created lmdb with the following way.
```
def add_image_input_ops(model):
    # utilize the ImageInput operator to prep the images
    data, label = brew.image_input(
        model,
        reader,
        ["data", "label"],
        use_caffe_datum=1,
        ... ...
    )
```

ps: I tried read mnist-lmdb provided by tutorials "caffe2/python/tutorials/MNIST.ipynb",
     but the data read from mnist-lmdb still all-zero, is there anything wrong with my lmdb-read method?

**Comment by breadbread1984** [comment]
no you cant

**Comment by xinqinglxl** [comment]
Just found a way can solve the problem, close the issue.
