### ISSUE TITLE
How to load model trained with python

### ISSUE THREAD

**Issue by tblattner** [facebookarchive/caffe2#1737]
Hello,

I have an init_net.pb and predict_net.pb trained models and am trying to inference using these models.

I use the following code to load the model:
```
  CAFFE_ENFORCE(caffe2::ReadProtoFromFile(initNet, &initNetDef));
  CAFFE_ENFORCE(caffe2::ReadProtoFromFile(predictNet, &predictNetDef));

  initNetDef.mutable_device_option()->set_device_type(caffe2::CPU);
  predictNetDef.mutable_device_option()->set_device_type(caffe2::CPU);

  predictNetDef.mutable_device_option()->set_cuda_gpu_id(0);

  caffe2::Workspace workspace;
  workspace.RunNetOnce(initNetDef);

  workspace.CreateNet(predictNetDef);
```

I have also tried
`
std::unique_ptr<caffe2::NetBase> predict_net = caffe2::CreateNet(predictNetDef, &workspace);
`

and

`
caffe2::Predictor predictor(initNetDef, predictNetDef, &workspace);
`

With these i'm getting the following error, which occurs when calling CreateNet with predictNetDef:

>   what():  [enforce fail at operator.cc:181] op. Cannot create operator of type 'Conv' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "data" input: "conv1_w" input: "conv1_b" output: "conv1" name: "" type: "Conv" arg { name: "exhaustive_search" i: 0 } arg { name: "kernel" i: 7 } arg { name: "stride" i: 2 } arg { name: "order" s: "NCHW" } arg { name: "pad" i: 3 } device_option { device_type: 1 cuda_gpu_id: 2 } engine: "CUDNN" 

If I switch to 
```
  initNetDef.mutable_device_option()->set_device_type(caffe2::CUDA);
  predictNetDef.mutable_device_option()->set_device_type(caffe2::CUDA);
```

Then I get another error, which occurs when RunNetOnce with initNetDef:
>  terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at operator.cc:181] op. Cannot create operator of type 'GivenTensorFill' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "conv1_w" name: "" type: "GivenTensorFill" arg { name: "shape" ints: 64 ints: 1 ints: 7 ints: 7 } arg { name: "values"  ...... Then MANY floats 
 device_option { device_type: 1 } 

Is there something I am missing within exporting the model from python?

Below is the code that we are using in python to save the trained network:
```
def save_net(INIT_NET, PREDICT_NET, workspace, model):
    init_net, predict_net = mobile_exporter.Export(
        workspace, model.net, model.params
    )

    with open(PREDICT_NET, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    with open(INIT_NET, 'wb') as f:
        f.write(init_net.SerializeToString())
 ```

**Comment by Heightened** [comment]
I'm having the same issue, have you made any progress?
Specifically the GivenTensorFill error

edit:
This is what works for me
```c++
        DeviceOption option;
        option.set_device_type(caffe2::CUDA);
        option.set_cuda_gpu_id(0);
        new CUDAContext(option); // This line was missing before

        init_net.mutable_device_option()->CopyFrom(option);
        predict_net.mutable_device_option()->CopyFrom(option);
```

**Comment by tblattner** [comment]
It seems the error stemmed from the fact I had two different generation GPUs on my machine: (1) Titan Xp and (2) a Tesla K40. For some reason Caffe2 was having issues initializing the GPU contexts and was incredibly unstable. This in conjunction with the original model being trained on an entirely separate machine with 4 Tesla P100s. 

The fix in this case was to export the predict_net model into a pbtxt file, at which point I was able to manually modify the file to specify the specific GPU. For some reason when I was setting the DeviceOption, it was ignoring it, and only using the value set in the predict_net.

So really two main issues for me here. (1) the machine we were training on was using GPU ID 2, which does not exist on my machine, and (2) random errors popping up due to mismatch in GPU architectures!

I now have things working with the following code (along with completely removing the Tesla K40 from my box):

    caffe2::DeviceOption deviceOption;
    deviceOption.set_cuda_gpu_id(0);
    deviceOption.set_device_type(caffe2::CUDA);
    context = new caffe2::CUDAContext(deviceOption);
    CAFFE_ENFORCE(caffe2::ReadProtoFromFile(initNet, &initNetDef));
    CAFFE_ENFORCE(caffe2::ReadProtoFromFile(predictNet, &predictNetDef));
    initNetDef.mutable_device_option()->CopyFrom(deviceOption); //set_cuda_gpu_id(caffe2::CPU);
    predictNetDef.mutable_device_option()->CopyFrom(deviceOption); //set_device_type(caffe2::CPU);

    CAFFE_ENFORCE(workspace.RunNetOnce(initNetDef));
    CAFFE_ENFORCE(workspace.CreateNet(predictNetDef));

Glad you were able to find a solution in the meantime @Heightened 

Next up for me is seeing if its possible to copy a batch of Tensors asynchronously from inference.

Currently I am doing: 

    auto blob = workspace.GetBlob(inputName);
    blob->GetMutable<caffe2::TensorCUDA>()->CopyFrom(*cpuTensor, context);

I am considering having a separate thread to copy from my CPU tensor into the GPU tensor, and then pass the GPU tensor directly into the model rather than getting the CUDA tensor from the workspace. I'll post this question in a separate thread or on stackoverflow.

**Comment by BIGBALLON** [comment]
This demo works for me. see here for [more](https://github.com/BIGBALLON/Caffe2_Demo/blob/master/03_cpp_forward/main.cpp) details.

```cpp
void run(){

    // define a caffe2 Workspace
    Workspace workSpace;

    // define initNet and predictNet
    NetDef initNet, predictNet;

    // read protobuf
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_init_net, &initNet));
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_predict_net, &predictNet));

    // set device type
#ifdef USE_GPU
    predictNet.mutable_device_option()->set_device_type(CUDA);
    initNet.mutable_device_option()->set_device_type(CUDA);
#else
    predictNet.mutable_device_option()->set_device_type(CPU);
    initNet.mutable_device_option()->set_device_type(CPU);

    for(int i = 0; i < predictNet.op_size(); ++i){
        predictNet.mutable_op(i)->mutable_device_option()->set_device_type(CPU);
    }
    for(int i = 0; i < initNet.op_size(); ++i){
        initNet.mutable_op(i)->mutable_device_option()->set_device_type(CPU);
    }
#endif

    // load network
    CAFFE_ENFORCE(workSpace.RunNetOnce(initNet));
    CAFFE_ENFORCE(workSpace.CreateNet(predictNet));

    // load image from file, then convert it to float array.
    float imgArray[3 * 32 * 32];
    loadImage(FLAGS_file, imgArray);

    // define a Tensor which is used to stone input data
    TensorCPU input;
    input.Resize(std::vector<TIndex>({1, 3, 32, 32}));
    input.ShareExternalPointer(imgArray);

    // get "data" blob
#ifdef USE_GPU
    auto data = workSpace.GetBlob("data")->GetMutable<TensorCUDA>();
#else
    auto data = workSpace.GetBlob("data")->GetMutable<TensorCPU>();
#endif

    // copy from input data
    data->CopyFrom(input);

    // forward
    workSpace.RunNet(predictNet.name());

    // get softmax blob and show the results
    std::vector<std::string> labelName = {"airplane","automobile","bird","cat","deer",
        "dog","frog","horse","ship","truck"};

#ifdef USE_GPU
    auto softmax = TensorCPU(workSpace.GetBlob("softmax")->Get<TensorCUDA>());
#else
    auto softmax = workSpace.GetBlob("softmax")->Get<TensorCPU>();
#endif

    std::vector<float> probs(softmax.data<float>(),
        softmax.data<float>() + softmax.size());
    
    auto max = std::max_element(probs.begin(), probs.end());
    auto index = std::distance(probs.begin(), max);
    std::cout << "== predicted label: " << labelName[index] 
              << " ==\n== with probability: " << (*max * 100)
              << "% ==" << std::endl;
}
```

**Comment by semin-park** [comment]
It seems like `->set_device_type()` doesn't take in `caffe2::CPU` or `caffe2::CUDA` anymore. It expects `::google::protobuf::int32` now.. Does anyone know what integer I need to pass in?
