### ISSUE TITLE
Outdated API documentation

### ISSUE THREAD

**Issue by jistr** [facebookarchive/caffe2#1749]
The API docs at https://caffe2.ai/doxygen-c/html/ and https://caffe2.ai/doxygen-python/html/ say "Generated on Fri May 19 2017". Documentation for recent code is missing.

**Comment by orionr** [comment]
Thanks @jistr. We're working on this.

**Comment by orionr** [comment]
Updated documentation will land with https://github.com/caffe2/caffe2/pull/1759

**Comment by orionr** [comment]
And they are updated! We're working on automating this process. Thanks @jistr.

**Comment by jistr** [comment]
@orionr Thanks!
