### ISSUE TITLE
Model zoo downloader is broken

### ISSUE THREAD

**Issue by dzhulgakov** [facebookarchive/caffe2#1774]
Seems like `python -m caffe2.python.models.download squeezenet` doesn't work any more.

Reported in https://github.com/onnx/tutorials/issues/16

**Comment by orionr** [comment]
Looks like @kyoro1 might have an old version of caffe2 (~6 months old) installed. The URL where the models are stored changed from `https://s3.amazonaws.com/caffe2/models/...` to `https://s3.amazonaws.com/download.caffe2.ai/models/...` a while back. We'll track on the ONNX issue. I confirmed it works for me on latest source. Thanks!
