### ISSUE TITLE
Does make_image_db command format LMDB in NCHW or NHWC?

### ISSUE THREAD

**Issue by MatthewInkawhich** [facebookarchive/caffe2#1778]
I recently tried using this command to complete the MNIST tutorial (https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb) by downloading MNIST images as raw JPEGs and creating an LMDB using `make_image_db`, rather than just downloading a pre-created LMDB.

I believe that I successfully ran `make_image_db` to create an LMDB for training, testing and validation. However, when I try to run the tutorial code for training the net, I get errors regarding wrong dimensions. I changed my `arg_scope` for my nets from "NCHW" to "NHWC", and I get an error regarding having a 2-dimensional label matrix (it expects 1-D).

Any insight into what I might be doing wrong would be greatly appreciated.

**Comment by Yangqing** [comment]
Since we are not quite sure about the mnist data format you use - you might be better off downloading the original mnist and use the make_mnist_db utility:

https://github.com/caffe2/caffe2/blob/master/caffe2/binaries/make_mnist_db.cc

Original files can be found at http://yann.lecun.com/exdb/mnist/index.html

**Comment by MatthewInkawhich** [comment]
@Yangqing Thanks for the timely response. However, the purpose of my question was not to find a way to use the MNIST dataset. Rather, I want to use the `make_image_db` command to convert raw JPEG images into an LMDB usable by Caffe2 as shown in the MNIST tutorial. 

My point is that when I attempted to use the command with some JPEG images (in this case MNIST), the LMDB that was outputted does not seem formatted the same as the `mnist-train-nchw-lmdb` or  `mnist-test-nchw-lmdb`.

Overall, I was hoping you could inform me as to how the `mnist-train-nchw-lmdb` and  `mnist-test-nchw-lmdb` LMDBs were created.

Thanks
