### ISSUE TITLE
install caffe2 failed do I need reinstall libopencv_imgcodecs.so.3.1.0?

### ISSUE THREAD

**Issue by danfouer** [facebookarchive/caffe2#1783]
[ 75%] Linking CXX executable ../bin/elementwise_op_gpu_test
/usr/bin/ld: warning: libpng16.so.16, needed by /home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0, not found (try using -rpath or -rpath-link)
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `caffe2::Argument::set_name(char const*)':
elementwise_op_gpu_test.cc:(.text._ZN6caffe28Argument8set_nameEPKc[_ZN6caffe28Argument8set_nameEPKc]+0x36): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `google::protobuf::RepeatedPtrField<std::string>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<std::string>::TypeHandler>(google::protobuf::RepeatedPtrField<std::string>::TypeHandler::Type*)':
elementwise_op_gpu_test.cc:(.text._ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEPNT_4TypeES9_[_ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEPNT_4TypeES9_]+0x56): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEPNT_4TypeES9_[_ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldISsE11TypeHandlerEEEPNT_4TypeES9_]+0xf8): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `google::protobuf::RepeatedPtrField<caffe2::Argument>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<caffe2::Argument>::TypeHandler>(google::protobuf::RepeatedPtrField<caffe2::Argument>::TypeHandler::Type*)':
elementwise_op_gpu_test.cc:(.text._ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldIN6caffe28ArgumentEE11TypeHandlerEEEPNT_4TypeESB_[_ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldIN6caffe28ArgumentEE11TypeHandlerEEEPNT_4TypeESB_]+0x52): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldIN6caffe28ArgumentEE11TypeHandlerEEEPNT_4TypeESB_[_ZN6google8protobuf8internal20RepeatedPtrFieldBase3AddINS0_16RepeatedPtrFieldIN6caffe28ArgumentEE11TypeHandlerEEEPNT_4TypeESB_]+0xf0): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `caffe2::OperatorDef DefineOperator<caffe2::CUDAContext>(std::string const&)':
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x49): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0xed): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x17d): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x20d): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x3c0): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x3e0): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
elementwise_op_gpu_test.cc:(.text._Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs[_Z14DefineOperatorIN6caffe211CUDAContextEENS0_11OperatorDefERKSs]+0x400): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `void elementwiseNot<caffe2::CUDAContext>()':
elementwise_op_gpu_test.cc:(.text._Z14elementwiseNotIN6caffe211CUDAContextEEvv[_Z14elementwiseNotIN6caffe211CUDAContextEEvv]+0x85): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
elementwise_op_gpu_test.cc:(.text._Z14elementwiseNotIN6caffe211CUDAContextEEvv[_Z14elementwiseNotIN6caffe211CUDAContextEEvv]+0x175): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
elementwise_op_gpu_test.cc:(.text._Z14elementwiseNotIN6caffe211CUDAContextEEvv[_Z14elementwiseNotIN6caffe211CUDAContextEEvv]+0x8aa): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::string const&)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_create_read_struct@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_interlace_handling@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_IHDR@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::DecrementRecursionDepthAndPopLimit(int)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::UInt32Size(google::protobuf::RepeatedField<unsigned int> const&)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_get_io_ptr@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::OnShutdownDestroyMessage(void const*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloatArray(float const*, int, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint64Fallback()'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_longjmp_fn@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_gray_to_rgb@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_compression_level@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormat::ReadPackedEnumPreserveUnknowns(google::protobuf::io::CodedInputStream*, unsigned int, bool (*)(int), google::protobuf::UnknownFieldSet*, google::protobuf::RepeatedField<int>*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::IncrementRecursionDepthAndPushLimit(int)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_bgr@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_filter@PNG16_0'
../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_rgb_to_gray@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::TextFormat::ParseFromString(std::string const&, google::protobuf::Message*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::Int32Size(google::protobuf::RepeatedField<int> const&)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::Message::DebugString() const'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_init_io@PNG16_0'
../lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_destroy_read_struct@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_swap@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::OnShutdownDestroyString(std::string const*)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_get_IHDR@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_palette_to_rgb@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::RegisterAllTypes(google::protobuf::Metadata const*, int)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_compression_strategy@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_get_tRNS@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::InitProtobufDefaults()'
../lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::Message::ShortDebugString() const'
../lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_write_info@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::Message::SpaceUsedLong() const'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::SkipFallback(int, int)'
../lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned long)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteDoubleArray(double const*, int, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_packing@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_read_fn@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_create_info_struct@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_read_end@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback()'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_read_update_info@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_write_image@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_write_end@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_expand_gray_1_2_4_to_8@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_create_write_struct@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_read_image@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_read_info@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_strip_alpha@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::string const&, int*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_write_fn@PNG16_0'
../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString() const'
../lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::MessageLite::SerializeAsString() const'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_destroy_write_struct@PNG16_0'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_error@PNG16_0'
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
../lib/libcaffe2.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
/home/danfouer/anaconda3/envs/PY27/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `png_set_strip_16@PNG16_0'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:132: recipe for target 'bin/elementwise_op_gpu_test' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
CMakeFiles/Makefile2:1188: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pjh5** [comment]
It looks like you are using Anaconda 3 and installing to your Python 2 environment, and that these may be library version mismatches. Make sure that all the packages you need (in this case I see protobuf and opencv might be having problems) are installed in the PY27 environment; if they aren't installed in PY27 but installed in your base Anaconda environment then conda could pick them up from there, which can cause versioning problems.

Is this on mac or linux? 

If you pull the latest version and then follow the Anaconda install instructions here https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile should install correctly (add opencv to both requirement sections in meta.yaml before running `conda build` if you want to use it).

**Comment by danfouer** [comment]
@pjh5 Thanks a lot. This is on ubuntu 16.04, I will  follow the Anaconda install instructions

**Comment by danfouer** [comment]
danfouer@USAGTX1070:~/caffe2$ source activate PY27(PY27) danfouer@USAGTX1070:~/caffe2$ ^C
(PY27) danfouer@USAGTX1070:~/caffe2$ conda build conda
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/danfouer/anaconda3/envs/PY27/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
(PY27) danfouer@USAGTX1070:~/caffe2$ conda install caffe2 
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - caffe2

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by danfouer** [comment]
Now I am trying this way:
The problem is solved by building with the following command instead of simply mkdir build && cd build && cmake .. && make

mkdir build
cd build
cmake -DCUDNN_INCLUDE_DIR=path/to/cudnn/include -DCUDNN_LIBRARY=path/to/cudnn/lib64/libcudnn.so ..
make

**Comment by pjh5** [comment]
After running conda-build you have to call `conda install caffe2 --use-local` , the --use-local flag is necessary. But if your problems are fixed then I will close this issue.

**Comment by danfouer** [comment]
Scanning dependencies of target elementwise_op_gpu_test
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
[ 75%] Building CXX object caffe2/CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
[ 75%] Linking CXX executable ../bin/elementwise_op_gpu_test
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::string const&)'
../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
../lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString() const'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:132: recipe for target 'bin/elementwise_op_gpu_test' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
CMakeFiles/Makefile2:1188: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pjh5** [comment]
Are you on the most up to date code? The Anaconda installation instructions shouldn't build with leveldb https://github.com/caffe2/caffe2/blob/master/conda/build.sh#L31 .
