### ISSUE TITLE
Error of QT

### ISSUE THREAD

**Issue by vitiennam** [facebookarchive/caffe2#1785]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Linux 16.04
* Compiler version: 5.4
* CMake version:3.9
* CMake arguments: cmake .. -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF 

* Relevant libraries/versions (e.g. CUDA):

### CMake summary output
-- ******** Summary ********
-- General:
--   CMake version         : 3.9.0
--   CMake command         : /usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake
--   Git version           : v0.8.1-969-g1898ed3
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   CXX flags             :  -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/local/lib/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 5.1.10
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.13.5
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done

```
******** Summary ********
<please paste summary output here>
```

Hi I have problem with:
In file included from /media/code/MaskRCNN/Detectron/caffe2/caffe2/utils/threadpool/ThreadPool.cc:18:0:
/media/code/MaskRCNN/Detectron/caffe2/caffe2/utils/threadpool/WorkersPool.h: In static member function ‘static T* caffe2::AllocAligned<T>::alloc(Args&& ...) [with Args = {caffe2::BlockingCounter*}; T = caffe2::Worker]’:
/media/code/MaskRCNN/Detectron/caffe2/caffe2/utils/threadpool/WorkersPool.h:55:5: warning: ignoring return value of ‘int posix_memalign(void**, size_t, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     posix_memalign((void**)&p, kGEMMLOWPCacheLineSize, sizeof(T));
     ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
[ 54%] Linking CXX shared library ../lib/libcaffe2.so
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:6953: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:3089: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Please help me
Thanks,

**Comment by pietern** [comment]
I don't know where the linkage of Qt comes from. Is it possible that your version of OpenCV links with Qt?

**Comment by NamVi** [comment]
@pietern Thanks for your comment
You think this error is made by OpenCV?
So What OpenCV I should install and how I can do it?

I am just a new member about this, please teach me

Thanks,

**Comment by vitiennam** [comment]
@pietern Thanks for your comment
You think this error is made by OpenCV?
So What OpenCV I should install and how I can do it?

I am just a new member about this, please teach me

Thanks,

**Comment by vitiennam** [comment]
Hi all, I have fixed it

I remove all opencv in my computer and reinstall opencv follow caffe2 and now it can build with no error
