### ISSUE TITLE
Docker build returns a non-zero code: 1

### ISSUE THREAD

**Issue by Nick-Harvey** [facebookarchive/caffe2#1786]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Mac OSX
* Compiler version: Docker version 17.12.0-ce, build c97c6d6
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

running docker build fails when cloning into submodules

```
Cloning into 'tools/clang'...
Submodule path 'third_party/pybind11/tools/clang': checked out '254c7a91e3c6aa254e113197604dafb443f4d429'
Unable to checkout 'b1370adb972a8345de92e2d69e61daf7f9bce43e' in submodule path 'third_party/cub'
The command '/bin/sh -c git clone --branch v0.8.1 --recursive https://github.com/caffe2/caffe2.git' returned a non-zero code: 1
```

Exact command being run: 
`docker build -t caffe2:cuda8-cudnn7-all-options .`

**Comment by Nick-Harvey** [comment]
Fixed it by removing the `--branch v0.8.1` declaration in the dockerfile

**Comment by Maratyszcza** [comment]
cc @pietern @ezyang

**Comment by orionr** [comment]
Thanks @Nick-Harvey. @pietern should the docker containers just reference master for now? We can also create a new branch if that's valuable but that bad `cub` reference from third_party is definitely giving us problems...

**Comment by orionr** [comment]
Resolved with https://github.com/caffe2/caffe2/pull/1520
