### ISSUE TITLE
ubuntu16.04: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed

### ISSUE THREAD

**Issue by danfouer** [facebookarchive/caffe2#1788]
## System information

* Operating system: ubuntu16.04
* Compiler version: gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2) 
* CMake version: cmake version 3.5.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):CUDA8.0 cudnn 6.0

### CMake summary output

Scanning dependencies of target elementwise_op_gpu_test
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
[ 75%] Building CXX object caffe2/CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
[ 75%] Linking CXX executable ../bin/elementwise_op_gpu_test
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anacoSearch termnda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
../lib/libcaffe2.so: undefined reference to google::SetUsageMessage(std::string const&)' ../lib/libcaffe2.so: undefined reference toleveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
../lib/libcaffe2_gpu.so: undefined reference to google::base::CheckOpMessageBuilder::NewString()' ../lib/libcaffe2.so: undefined reference toleveldb::Status::ToString() const'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:132: recipe for target 'bin/elementwise_op_gpu_test' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
CMakeFiles/Makefile2:1188: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
******** Summary ********
<please paste summary output here>
```

**Comment by pjh5** [comment]
I think this is actually a leveldb issue, and unrelated to your GPU.

Are you using Anaconda?

If you don't need leveldb, then you can fix this real by passing -DUSE_LEVELDB=OFF to your cmake command. If you want to use leveldb, I think the old version in pip still works
`pip install leveldb==0.18`

**Comment by danfouer** [comment]
I changed gcc from gcc5.4 to gcc4.8.5), then new error occur：

[ 76%] Linking CXX executable ../bin/batch_matmul_op_gpu_test
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /home/danfouer/anaconda3/envs/PY27/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
CMakeFiles/batch_matmul_op_gpu_test.dir/operators/batch_matmul_op_gpu_test.cc.o: In function caffe2::(anonymous namespace)::BatchMatMulOpGPUTest::SetUp()': batch_matmul_op_gpu_test.cc:(.text+0x9ca): undefined reference togoogle::protobuf::internal::fixed_address_empty_string'
CMakeFiles/batch_matmul_op_gpu_test.dir/operators/batch_matmul_op_gpu_test.cc.o: In function caffe2::(anonymous namespace)::BatchMatMulOpGPUTest_BatchMatMulOpGPUBroadcastTest_Test::TestBody()': batch_matmul_op_gpu_test.cc:(.text+0x2c7f): undefined reference togoogle::protobuf::internal::fixed_address_empty_string'
../lib/libcaffe2.so: undefined reference to google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)' ../lib/libcaffe2.so: undefined reference togoogle::SetUsageMessage(std::string const&)'
../lib/libcaffe2.so: undefined reference to google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
../lib/libcaffe2.so: undefined reference to google::protobuf::Message::GetTypeName() const' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::MessageLite::SerializeToString(std::string*) const'
../lib/libcaffe2.so: undefined reference to google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))' ../lib/libcaffe2.so: undefined reference toleveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
../lib/libcaffe2.so: undefined reference to google::protobuf::TextFormat::ParseFromString(std::string const&, google::protobuf::Message*)' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::Message::DebugString() const'
../lib/libcaffe2_gpu.so: undefined reference to google::base::CheckOpMessageBuilder::NewString()' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::WireFormatLite::WriteBytes(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2.so: undefined reference to google::protobuf::internal::OnShutdownDestroyString(std::string const*)' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe2_gpu.so: undefined reference to google::protobuf::Message::ShortDebugString() const' ../lib/libcaffe2_gpu.so: undefined reference togoogle::protobuf::MessageLite::ParseFromString(std::string const&)'
../lib/libcaffe2.so: undefined reference to google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)' ../lib/libcaffe2_gpu.so: undefined reference togoogle::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::string const&, int*)'
../lib/libcaffe2.so: undefined reference to leveldb::Status::ToString() const' ../lib/libcaffe2_gpu.so: undefined reference togoogle::protobuf::MessageLite::SerializeAsString() const'
../lib/libcaffe2.so: undefined reference to google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)' ../lib/libcaffe2.so: undefined reference togoogle::protobuf::Message::InitializationErrorString() const'
collect2: error: ld returned 1 exit status

**Comment by pjh5** [comment]
This is a protobuf mismatch problem. See https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#null__protobuf-errors . 

It looks like you are using packages in Anaconda; can you use the Anaconda specific install instructions https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#anaconda-install-path ? You will have to remove the flags `-DUSE_CUDA=OFF` and `-DUSE_NCCL=OFF` from conda/build.sh before following those instructions. The Anaconda path should deal with differing protobuf versions

**Comment by pjh5** [comment]
This looks like the same issue as #1705 . I will close this as a duplicate.
