### ISSUE TITLE
Test fail on 9 - net_test

### ISSUE THREAD

**Issue by xwzy** [facebookarchive/caffe2#1790]
### System information

* Ubuntu 14.04
* g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
* cmake version 2.8.12.2
* Driver Version: 370.23, CUDA 8, CuDNN 5.1

```
98% tests passed, 1 tests failed out of 56

Total Test time (real) =  45.09 sec

The following tests FAILED:
	  9 - net_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by Yangqing** [comment]
Thanks for reporting this - could you paste the full output and reopen this issue? Specifically, if you run net_test manually, what is the output?
