### ISSUE TITLE
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu

### ISSUE THREAD

**Issue by ZhuXiongwei24** [facebookarchive/caffe2#1797]
If this is a build issue, please fill out the template below.

### System information

* Operating system:ubuntu16.04
* Compiler version:gcc5.4.0
* CMake version:3.5.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):cuda9.1 cudnn5.1

input:python -m caffe2.python.operator_test.relu_op_test
output:WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
E0124 17:31:58.010618 18145 init_intrinsics_check.cc:54] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0124 17:31:58.010640 18145 init_intrinsics_check.cc:54] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0124 17:31:58.010644 18145 init_intrinsics_check.cc:54] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.73821229, -0.73821229, -0.36917681, -0.73821229], dtype=float32), gc=, dc=[], engine=u'')

**Comment by pjh5** [comment]
Can you run these for me and paste the output?
`find / -name caffe2_pybind11_state* 2>/dev/null`
`echo $PYTHONPATH`

**Comment by ZhuXiongwei24** [comment]
this was the output！
find / -name caffe2_pybind11_state* 2>/dev/null
/home/zxw/.local/share/Trash/files/build/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/home/zxw/.local/share/Trash/files/build/caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir
/usr/local/caffe2/python/caffe2_pybind11_state.so
/usr/local/caffe2/CMakeFiles/caffe2_pybind11_state.dir
$ echo $PYTHONPATH
/usr/local::/home/zxw/caffe2/build

**Comment by pjh5** [comment]
Can you post your cmake output? If should be a two column list of things like
USE_CUDA         : ON
  CUDA version  : x.x.x

If USE_CUDA is set to OFF in this output, then Caffe2 didn't actually build with GPU support, and there must be another error during the build or installation phase.

**Comment by ZhuXiongwei24** [comment]
My problem has been solved when I used cuda 8.0 and cudnn 5.1 . Thank you!

**Comment by Dimlight** [comment]
I have faced similar kind of situations. my output for your command is 

find / -name caffe2_pybind11_state* 2>/dev/null

/usr/local/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
/usr/local/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so
/usr/local/lib/python2.7/site-packages/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/usr/local/lib/python2.7/site-packages/caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir
/usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state.so
/usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state_gpu.so
/usr/local/lib/python2.7/dist-packages/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/usr/local/lib/python2.7/dist-packages/caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir
/home/ekram/pytorch/cmake/caffe2/python/caffe2_pybind11_state.so
/home/ekram/pytorch/cmake/caffe2/python/caffe2_pybind11_state_gpu.so
/home/ekram/pytorch/cmake/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/home/ekram/pytorch/cmake/caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir
/home/ekram/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
/home/ekram/anaconda2/conda-bld/caffe2_1526101653752/work/build/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/home/ekram/anaconda2/conda-bld/caffe2_1526101653752/work/cmake/caffe2/python/caffe2_pybind11_state.so
/home/ekram/anaconda2/conda-bld/caffe2_1526101653752/work/cmake/caffe2/python/caffe2_pybind11_state_gpu.so
/home/ekram/anaconda2/conda-bld/caffe2_1526101653752/work/cmake/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/home/ekram/anaconda2/conda-bld/caffe2_1526101653752/work/cmake/caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir
/home/ekram/anaconda2/pkgs/caffe2-0.8.dev-py27_2018.05.11/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so

**Comment by pjh5** [comment]
@Dimlight this is not a problem unless you built Caffe2 with CUDA support and have CUDA support on your machine. If this is the case for you, then please post an issue to https://github.com/pytorch/pytorch/issues  instead of here.
