### ISSUE TITLE
Add examples to finetune parameters with Caffe2

### ISSUE THREAD

**Issue by Ian09** [facebookarchive/caffe2#18]
As the Inception net is released https://github.com/google/inception , many researcher would like to fine tune the parameters based on the pretrained model. However, there is no any examples about how to do it in Caffe2. It would be of great help if Yangqing could provide an simple example. Thanks very much!

**Comment by futurely** [comment]
There are no such examples yet.

**Comment by dyigitpolat** [comment]
Why is this issue closed?
