### ISSUE TITLE
Should we add "third_party/eigen" to caffe2_include_directories?

### ISSUE THREAD

**Issue by tianzhi0549** [facebookarchive/caffe2#1800]
I think we should add `caffe2_include_directories("third_party/eigen")` after the line below. Otherwise, the compiling will fail since it can not find `eigen`, in case the user does not have `eigen` in standard directories.
https://github.com/caffe2/caffe2/blob/6a938bb2dad1359dc5eb5a060946e93be79a9e40/cmake/Dependencies.cmake#L46

**Comment by pjh5** [comment]
This should be handled later in that file https://github.com/caffe2/caffe2/blob/6a938bb2dad1359dc5eb5a060946e93be79a9e40/cmake/Dependencies.cmake#L238-L248

Are you encountering an issue regarding eigen? If so please feel free to re-open this and post more details about your error.

**Comment by tianzhi0549** [comment]
@pjh5 Thank you for your reminder. The root cause is that I have a broken eigen in a standard directory. It's not caffe2's problem. Sorry for that.
