### ISSUE TITLE
"Caffe2 built successfully" on windows10 but where is caffe2_pybind11_state.dll???

### ISSUE THREAD

**Issue by shirishr** [facebookarchive/caffe2#1802]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Windows10
* Compiler version: VS2017
* CMake version: 3.10.2
* CMake arguments: None
* Relevant libraries/versions (e.g. CUDA): None

### CMake summary output

```
******** Summary ********
<please paste summary output here>
```

**Comment by orionr** [comment]
Hi @shirishr - looks like this might be similar to https://github.com/caffe2/caffe2/issues/1694 ?

Just to verify, when you pulled the Caffe2 source did you use

```
git clone --recursive https://github.com/caffe2/caffe2.git
```

?

The `--recursive` is very important because it will clone all of the submodules inside `third_party`, which is where eigen and pybind11 should then be picked up by CMake.

If that's not the issue please paste your full build logs here and we'll take a look. Thanks.

**Comment by shirishr** [comment]
@orionr 
I did use the recursive clone.
caffe2 was succefully built.
In build directory I see a "Release" folder only in a folder called "caffe2.dir"
There is no file of any type called caffe2_pybind11_state. Not .dll, or .pyb or .pyd. None.
CMakeOutput Log and CMakeError Log is attached
See if something catches your eye

[CMakeError.log](https://github.com/caffe2/caffe2/files/1664947/CMakeError.log)
[CMakeOutput.log](https://github.com/caffe2/caffe2/files/1664948/CMakeOutput.log)

**Comment by orionr** [comment]
@shirishr I took a look at the logs, but nothing obvious there... we were able to get through the Windows install on https://github.com/caffe2/caffe2/issues/1694 so maybe there are some pointers for you there. I'm going to see if I can get access to a Windows box over the next couple of days and try to repro.

**Comment by shirishr** [comment]
thanks @orionr 
There are two errors reported in CMakeError.log and build failed.
Is this error not caught in CmakeOutput?
Take a look when you get a chance

**Comment by kgmdgit** [comment]
I also got the same problem.
In build directory I see a "Release" folder only in a folder called "caffe2.dir"
caffe2\build\caffe2\caffe2.dir\Release

    94 Warning(s)
    0 Error(s)

Time Elapsed 00:42:30.85
"Caffe2 built successfully" 
Attached log file
[logfileforbuild_windows.txt](https://github.com/caffe2/caffe2/files/1682400/logfileforbuild_windows.txt)

**Comment by Yangqing** [comment]
Caffe2 is actually not built with python on windows at the moment - due to the many python installation paths we are yet to figure out a solution. Possible way is to use conda - if you get it working, please feel free to let us know!

**Comment by orionr** [comment]
Hi @shirishr. I've debugged further and it looks like Python bindings on Windows aren't enabled by default. I'm seeing if I can build locally, but you can also try editing `scripts/build_windows.bat` locally and switching to

```
-DBBUILD_PYTHON=ON ^
```
towards the end of the file.

**Comment by kgmdgit** [comment]
Thanks Yangqing and orion .. I have compiled with conda with -DBBUILD_PYTHON=ON in bat file and i am able to build the pyd file.

I am new to neural networks. Any suggestion to understand quickly  and start doing the prototypes?

**Comment by orionr** [comment]
@kgmdgit - great to hear. I would recommend going through some of the tutorials starting with https://caffe2.ai/docs/intro-tutorial.html and then maybe https://caffe2.ai/docs/tutorial-MNIST.html to get familiar with everything. Welcome!

**Comment by kgmdgit** [comment]
When i try to import proto , it shows error . it will not in the caffe2_pybind11_state.pyd file ?
Do i need to do anything ?

**Comment by kgmdgit** [comment]
its resolved . and I am able to run the given examples. I am not able to read the init_net.pb file getting the below error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 92: character maps to <undefined>
I tried with changing utf-8, still have problem. Please help

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 1: invalid start byte

**Comment by orionr** [comment]
Hi @kgmdgit  Unfortunately Windows is really only support as a runtime right now (C++ inference). Python support, for example, is something we are still figuring out. It's likely that the tutorials and other things related to training have issues too. We're working on it, but if you have the option, I'd highly recommend installing Ubuntu (maybe dual-boot) and do all of your training there and then just run the generated init_net and predict_net models through C++ on Windows (if that's needed in your use case).

@shirishr can you work with @kgmdgit to see if this solves your issue and this can be closed? Thanks.

**Comment by pjh5** [comment]
@kgmdgit What version of python do you have? I'm guessing that this is related to unicode, which made a drastic change from python 2 to python 3. See https://docs.python.org/3/howto/unicode.html and https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character .

**Comment by shirishr** [comment]
@orionr,
I think it can be closed.
I will work with @kgmdgit if I run into any issues.
I suspect my issue could be MSVC related.
