### ISSUE TITLE
No module named caffe2_pybind11_state_gpu

### ISSUE THREAD

**Issue by qiuliwang** [facebookarchive/caffe2#1807]
### System information

* Operating system: Mac OS
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):No cuda

### CMake summary output

```
******** Summary ********
I  build Caffe2 without Anaconda. But when I run  

cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"

It shows Failure. When I run a Python interpreter in the caffe2/build directory and then trying from caffe2.python import core, it tells me that

WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu

**Comment by pjh5** [comment]
This is just a warning to tell you that Caffe2 was not built with GPU support. Since you are on a Mac and don't have CUDA, you probably don't have a GPU. In this case there is no problem here. Caffe2 should work fine for you.

**Comment by toby5box** [comment]
Is there any way to improve this? It's a very confusing message. I just got it myself.

**Comment by pjh5** [comment]
I can add some documentation on the installation page, but I've found this warning to be very useful when using Caffe2 on Ubuntu boxes with GPUs.

**Comment by Yuliang-Zou** [comment]
@pjh5 I also encountered this issue. But I indeed set the USE_CUDA flag to True in CMakeList.txt. And the machine indeed has GPUs. So how can I fix this?

**Comment by pjh5** [comment]
@Yuliang-Zou if cmake cannot find CUDA then it will turn USE_CUDA to OFF, no matter what you set it to. Look through your cmake output for an error message and search through our issues for a fix. If you can't find what you need, then please open a new issue with your cmake output.

**Comment by Yuliang-Zou** [comment]
@pjh5 thanks. I know how to solve it. By checking camke ouput and set the corresponding environment variables can fix this.
