### ISSUE TITLE
Why it is so difficult to install caffe2???

### ISSUE THREAD

**Issue by SniperZhao** [facebookarchive/caffe2#1811]
It takes me 2 days to install caffe2. 
I was followed the instruction 100 persent and still stucking by the third-party dependence such as gflags or glog etc.
I don't understand why the installation of caffe2 is setting so complicated and inconvenient, especially compare with TensorFlow.
It's really frustrated and makes people stay away from caffe2.

By the way, it also taken me a lot of time to fix the error of caffe installation because of the mismatch of  matplot.
It seems that caffe always like to torture the users by some trivial third-party libraries.

**Comment by orionr** [comment]
Also, @SniperZhao, can you give more info on what environment you were installing on - Ubuntu/Windows, and whether it was Anaconda, pip, etc? Also, what your issue was with matplotlib? That can help us track issues and maybe resolve it for others. Thanks.

**Comment by orionr** [comment]
Actually looks like you also opened https://github.com/caffe2/caffe2/issues/1810 - I'll reply there.

**Comment by orionr** [comment]
@SniperZhao, I'm going to close this and focus on the other issue. Thanks.

**Comment by SniperZhao** [comment]
@orionr Thank you for your reply. I have installed several framework of deep learning, such as Tensorflow, Mxnet, pyTorch etc. However none of them drives me so crazy as Caffe/Caffe2 just did.
Right now there are fierce competition among deep learning frameworks. It's really bad for Caffe to lose this competition just because the inconvenient installation.

Anyway, thanks again for your kind reply and sorry for my excessive words.
Wish Caffe2 can release pre-built binary installs as soon as possible.

**Comment by mikaelfs** [comment]
My mileage somehow varied. Despite a small hiccup, the Caffe2 (+ Detectron) installation was completed smoothly by referencing to the installation guide. Still, with the recent merging of Caffe2 source into Pytorch, the documentation might need additional update.

Currently working configuration is Ubuntu 16.04, CUDA Toolkit 9.1, cuDNN 7.1, and Python 2.7. I have summarized the installation steps [in this article](http://tech.amikelive.com/node-706/comprehensive-guide-installing-caffe2-with-gpu-support-by-building-from-source-on-ubuntu-16-04/) as additional reference for others who face problems during installation.

The author installed with CentOS 7, which was different with the configuration that I have tested. I usually had good experience with CentOS but can't further confirm or rebuke until I proceed with the installation in that environment.

**Comment by dheera** [comment]
Bump! I use TensorFlow and MXnet extensively and both frameworks can be installed on a **vanilla Ubuntu install** with one command. Not 2, not 3, not 10 -- just 1 command.

> We only support Anaconda packages at the moment. If you do not wish to use Anaconda, then you must build Caffe2 from source.

This is extremely annoying. Among all the competing choices for package management, not everyone wishes to use Anaconda. I **strongly** suggest it be made as simple as the following:

    sudo apt-add-repository ppa:facebook/caffe2
    sudo apt-get update
    sudo apt-get install caffe2-cu90

OR

    sudo pip3 install caffe2-cu90

Making it low-friction and as universal as above would **definitely** speed-up adoption and improve the visibility of Caffe2 in the open-source community. This is especially true for busy researchers who really need to spend every minute they can get on designing, training, and testing models, not on installing frameworks.

**Comment by HWiese1980** [comment]
Any news about this? It's already been quite a while since the issue was opened.

**Comment by pjh5** [comment]
We are trying to provide a better install experience, and it really has been getting steadily better. Unfortunately we are still just spread a little thin. We are always welcoming PRs to help us out. 

If you're having troubles with building from source, read through https://caffe2.ai/docs/faq.html to make sure you understand which libraries you need and how to set up your Python installation correctly.

**Comment by Kaidanov** [comment]
This is an impossible task on my journey to DensPose
I can't install Caffe2 for not normal ammount of time..

Tried through cmd line and through cloning through VS2017  

Installed all the dependencies.. 

What a m I missing ? I can't understand the log files? 
Seems to be unsuccessfulbuild" because "AlwaysCreate" was specified. is the first problem .. 
From there it's just all down the hill..

SAVE ME!PLEASE!
Added log files. 


From cmd line running 

build_windows.bat changed a bit for vs2017 to run. Find attached.(just changed extention)
[build_windows.txt](https://github.com/caffe2/caffe2/files/2540944/build_windows.txt)



InitializeBuildStatus:

  Creating "cmTC_f4003.dir\Debug\cmTC_f4003.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.



[CMakeOutput.log](https://github.com/caffe2/caffe2/files/2540928/CMakeOutput.log)
[CMakeError.log](https://github.com/caffe2/caffe2/files/2540929/CMakeError.log)


From vs 2017 only runs when clone->url-> open existing local folder
Getting those errors

![image](https://user-images.githubusercontent.com/164266/47892522-dc5b5580-de60-11e8-8249-fbdfde891784.png)


I've changed the

**Comment by Kaidanov** [comment]
Also what is glog: need to build from source? 
Is it this one? -https://godoc.org/github.com/golang/glog?
Seems to just import.. 

Or this - https://github.com/google/glog ?

**Comment by Kaidanov** [comment]
Also done 
git submodule update --init --recursive
python setup.py install

Getting 
Building wheel torch-1.0.0a0+0fd176f
The support for PyTorch with Python 2.7 on Windows is very experimental.
Please set the flag `FORCE_PY27_BUILD` to 1 to continue build.

Where should I change it?

**Comment by Kaidanov** [comment]
> Please set the flag `FORCE_PY27_BUILD` to 1 to continue build

https://github.com/pytorch/pytorch/blob/master/README.md 
Seems that we have to run 
set FORCE_PY27_BUILD=1
and bunch of other commands.. Trying

**Comment by Kaidanov** [comment]
![image](https://user-images.githubusercontent.com/164266/47893325-22b2b380-de65-11e8-9d80-f4a26248f848.png)

Nightmare..

**Comment by Kaidanov** [comment]
> Also done
> git submodule update --init --recursive
> python setup.py install
> 
> Getting
> Building wheel torch-1.0.0a0+0fd176f
> The support for PyTorch with Python 2.7 on Windows is very experimental.
> Please set the flag `FORCE_PY27_BUILD` to 1 to continue build.
> 
> Where should I change it?

That  -submodule update  - didn't help
Still problem with cpuinfo

**Comment by orionr** [comment]
@Kaidanov looks like you are building on Windows? That is generally more difficult than Ubuntu or other Linux versions. I'd recommend trying Linux if you can. Also, FYI that DensePose will probably require a high-end GPU (GTX 1080 or higher) to run.

**Comment by Kaidanov** [comment]
So how can I built the right machine for it?
I have credits with AWS and Google clouds.. 

Is there predefined machine I could use?

**Comment by Kaidanov** [comment]
I have 8 gb of GPU out of 16 CPU
It's not enough?

It's dell g5 15

**Comment by orionr** [comment]
For cloud options (AWS and Azure) please take a look at https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=cloud

**Comment by Kaidanov** [comment]
After clean clone I am able to run a build of cmake of caffe to in vs2017
Getting those:

You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed.


Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed.	C:\WINDOWS\system32\CMakeLists.txt	D:\dev\ML\pytorch\aten\src\ATen\core\TensorImpl.h	1448	

And that's the note:

// Note [TensorImpl size constraints]
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Changed the size of TensorImpl?  If the size went down, good for
// you!  Adjust the documentation below and the expected size.
// Did it go up?  Read on...
//
// Struct size matters.  In some production systems at Facebook, we have
// 400M live tensors during a training run.  Do the math: every 64-bit
// word you add to Tensor is an extra 3.2 gigabytes in RAM.
//
// If you are a Facebook employee, you can check if the run in question
// has tipped you over the point using the command here:
// https://fburl.com/q5enpv98
//
// For reference, we OOMed at 160 bytes (20 words) per TensorImpl.
// This is not counting overhead from strides out-of-line allocation, and
// StorageImpl space.  We're currently comfortably under this number;
// let's keep it that way.  (One currently approved pending size
// increase is inlining sizes and strides as small vectors, to reduce
// dynamic allocations.)
//
// Our memory usage on 32-bit systems is suboptimal, but we're not checking
// for it at the moment (to help avoid rage inducing cycles when the
// 32-bit number is wrong).
//
// Current breakdown:
//
//    vtable pointer
//    strong refcount           TODO: pack these into one word
//    weak refcount
//    storage pointer
//    sizes vector (start)
//    sizes vector (end)
//    sizes vector (reserved)   TODO: get rid of me
//    strides pointer
//    storage offset
//    numel
//    data type pointer
//    miscellaneous bitfield
//
static_assert(sizeof(void*) != sizeof(int64_t) || // if 64-bit...
              sizeof(TensorImpl) == sizeof(int64_t) * 12,
              "You changed the size of TensorImpl on 64-bit arch."
              "See Note [TensorImpl size constraints] on how to proceed.");


Can I somehow go around it?

**Comment by Kaidanov** [comment]
![image](https://user-images.githubusercontent.com/164266/48009478-7b63a400-e124-11e8-83f6-ef27747cf428.png)

**Comment by orionr** [comment]
If you're trying to get Detectron working, maybe try the changes in https://github.com/pytorch/pytorch/pull/13550#issuecomment-435913149 . I just remembered that we do not support Detectron on Windows right now, but if you want to try and get it working that PR is your best chance.
