### ISSUE TITLE
Initializing model_helper 'params' when loading pre-trained model from .pb's

### ISSUE THREAD

**Issue by inkawhich** [facebookarchive/caffe2#1814]
**Does anyone know how I can initialize the params of a model_helper object (.params) when I am initializing the .net and .param_init_net members from saved .pb files?**

I am trying to retrain a model (MNIST) from saved pb files. The method I am using to initialize the model_helper with init.pb and predict.pb has worked for testing but I am running into problems when training. The model helper's 'params' member is not getting initialized so the optimizer cannot function. When I print the params of the train_model ('print train_model.params') from the MNIST tutorial I get: 

`[BlobReference("conv1_w"), BlobReference("conv1_b"), BlobReference("conv2_w"), BlobReference("conv2_b"), BlobReference("fc3_w"), BlobReference("fc3_b"), BlobReference("pred_w"), BlobReference("pred_b")]`

but when I try to print the params of the model I am initializing I get nothing. 

[#1768](https://github.com/caffe2/caffe2/issues/1768) shows how I am initializing the model helper from .pb files

I realize that one solution would be to write the equivalent of the "AddLeNetModel()" function from the MNIST tutorial but I do not think that is a good way. Is there a way to solve this issue without doing that, as that approach is not easily extendable to more complex models?

Thanks,
Nate

**Comment by harouwu** [comment]
Hi Nate,

Would you mind showing how do you try to print the params?

I would recommend doing

```
conv1_weight = workspace.FetchBlob('conv1_w')
print(conv1_weight)
```

**Comment by inkawhich** [comment]
harouwu,

After constructing the model helper object (train_model) and adding the predict and init nets from the .pbs as the .net and .param_init_net members, I was attempting to print the params like this:

```
print train_model.GetAllParams()
```

However, the list was empty. I **think** I solved the problem with the following code

```
for i,op in enumerate(init_net_proto.op):
	param_name = op.output[0]
	if param_name != 'data':
		assert(op.arg[0].name == "shape")
		print "initializing: ", param_name
		tags = (ParameterTags.WEIGHT if param_name.endswith("_w") else ParameterTags.BIAS)
		train_model.create_param(param_name=op.output[0], shape=op.arg[0].ints, initializer=initializers.ExternalInitializer(), tags=tags)
```
where I iterate through all of the ops from the init net protobuf and explicitly create the params in the model object with the same names, same shape, and specify that they will be externally initialized (as they will be in the workspace when the param_init_net is run).

Empirical evidence tells me that this works but please let me know if there is a flaw here or if there is a better way of doing this. The only potential issue I see is if the expected input to the model is not named 'data' but that seems like a common naming convention from what I have seen.

Nate
