### ISSUE TITLE
Missing sudo in installation guide cost me over an hour

### ISSUE THREAD

**Issue by tonxtonxtonx** [facebookarchive/caffe2#1816]

**Comment by orionr** [comment]
Apologies @adepace2 - thanks for the heads up. We're updating those right now.

**Comment by orionr** [comment]
Actually, @adepace2, I see that it was the **cd** that you had issue with. To confirm, are you saying the cd in this line failed for you?

```
make && cd build && sudo make install
```
If so, that's unexpected. You do need to make sure to use `sudo make install` to install it to the system location. Give me more details if you can. Thanks.
