### ISSUE TITLE
/system/bin/sh: /data/local/tmp/speed_benchmark: No such file or directory

### ISSUE THREAD

**Issue by Nanda0001** [facebookarchive/caffe2#1818]
### System information

* Operating system: Ubuntu 16.04, Android API 21 x84_64 elmulator
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
******** Summary ********
I'd like to execute the file super_resolution_with_caffe2.py

But I got some error form executable file in Mobile.

When I run the this code,

========================================================
os.system(
    'adb shell /data/local/tmp/speed_benchmark '                     # binary to execute
    '--init_net=/data/local/tmp/super_resolution_mobile_init.pb '    # mobile init_net
    '--net=/data/local/tmp/super_resolution_mobile_predict.pb '      # mobile predict_net
    '--input=9 '                                                     # name of our input image blob
    '--input_file=/data/local/tmp/input.blobproto '                  # serialized input image
    '--output_folder=/data/local/tmp '                               # destination folder for saving mobile output
    '--output=27,9 '                                                 # output blobs we are interested in
    '--iter=1 '                                                      # number of net iterations to execute
    '--caffe2_log_level=0 '
)
========================================================
 
I got
![2018-01-26 10-58-03](https://user-images.githubusercontent.com/17906324/35466108-61a15f3a-0344-11e8-852d-8c00fb433435.png)

Even though I have the executable file
![2018-01-26 10-55-23](https://user-images.githubusercontent.com/17906324/35466114-6de189be-0344-11e8-82e7-cd054ff0eb67.png)


I also have fastboot and adb. other things were going well
![2018-01-26 10-58-31](https://user-images.githubusercontent.com/17906324/35466123-7b424242-0344-11e8-9778-daa32ba43ec6.png)

![2018-01-26 11-00-24](https://user-images.githubusercontent.com/17906324/35466126-7fe9b078-0344-11e8-820d-f7931f3fb7de.png)



# One More Question:

I have 3 files for speed_benchmark in Caffe2 folder. Which one is the correct one for binary executable file?!

speed_benchmark

speed_benchmark.cc

speed_benchmark.cc.o
![2018-01-26 11-11-16](https://user-images.githubusercontent.com/17906324/35466135-96560ffa-0344-11e8-9492-e26bbe052b3e.png)



--



```

**Comment by Maratyszcza** [comment]
You are trying to run the executable `/data/local/tmp/speed_benchmark` on an Android device, but this executable does not exist on the device. You should copy it from Caffe2 `build_android` directory to device using `adb push` command.

**Comment by Nanda0001** [comment]
As you can see in this blog(http://kalten.tistory.com/253), I have already speed_benchmark file in `/data/local/tmp/speed_benchmark` 
![2018-01-26 10-55-23](https://user-images.githubusercontent.com/17906324/35466074-140196dc-0344-11e8-82fd-c3ef1c11c708.png)
![2018-01-26 10-58-03](https://user-images.githubusercontent.com/17906324/35466080-25752c8a-0344-11e8-94e0-6a0252f2cb47.png)

**Comment by Maratyszcza** [comment]
I think you built Caffe2 for your host system rather than for Android x86_64 ABI. I suggest you remove all `build*` directories in Caffe2 and rebuild it again with `./scripts/build_android.sh -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang`

**Comment by Nanda0001** [comment]
Thank you!  #Maratyszcza

But From
`./scripts/build_android.sh -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang`

I got
![2018-01-27 12-49-23](https://user-images.githubusercontent.com/17906324/35468423-8c35035c-0360-11e8-9565-a35acb29335f.png)

My NDK version is r14
Please, Can you Give me any help?!

**Comment by Maratyszcza** [comment]
You need to update Caffe2 repo `git pull && git submodule update`. We recently did some changes to support more Android ABIs

**Comment by Maratyszcza** [comment]
@Nanda0001 did it fix your problem?

**Comment by Nanda0001** [comment]
Unfortunately, I couldn't fix the problem.
After rebuild 

> ../scripts/build_android.sh -DANDROID_ABI=x86_64

, I also had same error 

> /system/bin/sh: /data/local/tmp/speed_benchmark: No such file or directory

But AIcamera is works for me @

**Comment by bubo0** [comment]
@Maratyszcza Hello Maratyszcza, I updated Caffe2 and executed `./scripts/build_android.sh -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang` as you said.  After that I could not find `speed_benchmark` in `build_android` directory. Did I missed anything?

**Comment by Maratyszcza** [comment]
@bubo0 Binaries are not built by default, add `-DBUILD_BINARY=ON` to CMake configuration to build them.

**Comment by bubo0** [comment]
@Maratyszcza  I replaced `-DBUILD_BINARY=OFF` with `-DBUILD_BINARY=ON` and it worked! Thanks!

**Comment by Crefeda** [comment]
Hi @Nanda0001 ,

I have been trying to run the speed_bechmark executable with the following arguments: 
./build/bin/speed_benchmark --init_net=/home/crefeda/caffe2/caffe2/python/models/squeezenet/init_net.pb  --net=/home/crefeda/caffe2/caffe2/python/models/squeezenet/predict_net.pb 
and I get..

Starting benchmark.
Running warmup runs.
Main runs.
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at tensor.h:662] dims_[i] < std::numeric_limits<int>::max(). 140475109243768 vs 2147483647 Error from operator: 
input: "data" input: "conv1_w" input: "conv1_b" output: "conv1" type: "Conv" arg { name: "stride" i: 2 } arg { name: "pad" i: 0 } arg { name: "kernel" i: 3 }
** while accessing input: data
*** Aborted at 1527093619 (unix time) try "date -d @1527093619" if you are using GNU date ***
PC: @     0x7fc2e8c38428 gsignal
*** SIGABRT (@0x3e8000029ca) received by PID 10698 (TID 0x7fc2eadabb40) from PID 10698; stack trace: ***
    @     0x7fc2e8c384b0 (unknown)
    @     0x7fc2e8c38428 gsignal
    @     0x7fc2e8c3a02a abort
    @     0x7fc2e948f84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fc2e948d6b6 (unknown)
    @     0x7fc2e948d701 std::terminate()
    @     0x7fc2e948d969 __cxa_rethrow
    @     0x7fc2ea15ebdb caffe2::Operator<>::Run()
    @     0x7fc2ea1fdbf8 caffe2::SimpleNet::Run()
    @     0x7fc2ea1fe0bc caffe2::SimpleNet::TEST_Benchmark()
    @           0x406048 main
    @     0x7fc2e8c23830 __libc_start_main
    @           0x4079c9 _start
    @                0x0 (unknown)
Aborted (core dumped)

I dont quite understand the arguments that need to be fed to this function. Could you point me in the right direction. It would be of great help!

Thanks,
Crefeda

**Comment by Crefeda** [comment]
Hi  @Nanda0001,

Is it possible to specify an input image directly as an argument to speed bechmark.cc instead of input.blobproto?

Thanks,
Crefeda
