### ISSUE TITLE
caffe_translator,ValueError: Protocol message has no singular "torch_pooling" field.

### ISSUE THREAD

**Issue by xqpinitial** [facebookarchive/caffe2#182]
when i use  caffe_translator to translate caffe.model to caffe2.pb ,there is a problem

 File "/home/xqp/caffe2/python/caffe_translator.py", line 122, in TranslateModel
    layer, pretrained_blobs, is_test)
  File "/home/xqp/caffe2/python/caffe_translator.py", line 67, in TranslateLayer
    layer, pretrained_blobs, is_test)
  File "/home/xqp/caffe2/python/caffe_translator.py", line 292, in TranslatePool
    if param.HasField('torch_pooling') and param.torch_pooling:
  File "/home/xqp/caffe2/build/third_party/protobuf/python/google/protobuf/internal/python_message.py", line 598, in HasField
    'Protocol message has no singular "%s" field.' % field_name)
ValueError: Protocol message has no singular "torch_pooling" field.

then i have not found 'torch' in .proto.
Next   i change it ,however,there is also aproblem
    #  if param.HasField('torch_pooling') and param.torch_pooling:
        # In the Facebook port of Caffe, a torch_pooling field was added to
        # map the pooling computation of Torch. Essentially, it uses
        #   floor((height + 2 * padding - kernel) / stride) + 1
        # instead of
        #   ceil((height + 2 * padding - kernel) / stride) + 1
        # which is Caffe's version.
        # Torch pooling is actually the same as Caffe2 pooling, so we don't
        # need to do anything.
     #   pass
  #  else:
  #      AddArgument(caffe_op, "legacy_pad",
             #      caffe2_legacy_pb2.CAFFE_LEGACY_POOLING)
    **AddArgument(caffe_op, "legacy_pad",
                 caffe2_legacy_pb2.CAFFE_LEGACY_POOLING)**

**Comment by Yangqing** [comment]
This should have already been fixed in the latest master. Could you do a git pull and verify?

**Comment by xqpinitial** [comment]
thanks for your advise。I have solved this problem

**Comment by Yangqing** [comment]
Glad it works :)

**Comment by xqpinitial** [comment]
for bvlc_reference_caffenet,I met a new **problem.

Traceback (most recent call last):
  File "/home/xqp/caffe2/caffe2/python/tutorial/mytest_train.py", line 113, in <module>
    workspace.RunNetOnce(net.SerializeToString())
  File "/home/xqp/Desktop/caffe2/build/caffe2/python/workspace.py", line 156, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at fully_connected_op.h:25] W.ndim() == 2. 4 Error from operator: 
input: "pool5" input: "fc6_w" input: "fc6_b" output: "fc6" type: "FC"

**Comment by Yangqing** [comment]
cc @bwasti - it seems to be basically changing these lines:

https://github.com/caffe2/caffe2/blob/master/caffe2/python/caffe_translator.py#L330-L332

to force it to be 2-dimensional?

**Comment by xqpinitial** [comment]
W0307 12:33:14.994684 12839 conv_pool_op_base.h:461] You are hitting a case where Caffe's legacy padding calculation is hit. This leads to inefficient and sometimes incorrect results. We are keeping this behavior for backward compatibility, but you are strongly recommended to move away from it.
W0307 12:33:14.994684 12839 conv_pool_op_base.h:461] You are hitting a case where Caffe's legacy padding calculation is hit. This leads to inefficient and sometimes incorrect results. We are keeping this behavior for backward compatibility, but you are strongly recommended to move away from it.
Traceback (most recent call last):
  File "/home/xqp/caffe2/caffe2/python/tutorial/mytest_train.py", line 113, in <module>
    workspace.RunNetOnce(net.SerializeToString())
  File "/home/xqp/Desktop/caffe2/build/caffe2/python/workspace.py", line 156, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at fully_connected_op.h:25] W.ndim() == 2. 4 Error from operator: 
input: "pool5" input: "fc6_w" input: "fc6_b" output: "fc6" type: "FC"

**Comment by ezineo** [comment]
Just like @Yangqing suggests,
changing
```
   weight = utils.NumpyArrayToCaffe2Tensor(
        pretrained_blobs[0], output + '_w'
```
to
```
   weight = utils.NumpyArrayToCaffe2Tensor(
        pretrained_blobs[0][0,0], output + '_w'
```
could work?

**Comment by xqpinitial** [comment]
@ezineo ,I test two caffemodels ,all past.Thanks

**Comment by Yangqing** [comment]
dimensions should have been fixed in this commit:

https://github.com/caffe2/caffe2/commit/5941bc7d66b9efbed0e0574fee8ae2a7aab12a28
