### ISSUE TITLE
Implement mask_rcnn from Detectron model in c++. Cannot find operator schema for AffineChannel. 

### ISSUE THREAD

**Issue by hxw111** [facebookarchive/caffe2#1823]
I want to compile the mask_rcnn in "caffe2 c++" and has saved the network as ".pb" file.
But when I run the net ,I get a error as follow:
E0126 19:19:52.502368 26315 operator.cc:130] Cannot find operator schema for AffineChannel. Will skip schema checking.terminate called after throwing an instance of 'caffe2::EnforceNotMet'
what(): [enforce fail at operator.cc:190] op. Cannot create operator of type 'AffineChannel' on the device 'CUDA'.

Are there any good solutions to solve the problem? This is my c++ code:
                
                   NetDef init_net, predict_net;
                   ModelUtil mask_rcnn_model(init_net, predict_net);
                   CAFFE_ENFORCE(ReadProtoFromFile(model_dir+"init_net.pb", &init_net));
                   CAFFE_ENFORCE(ReadProtoFromFile(model_dir+"predict_net.pb", &predict_net));
                   CAFFE_ENFORCE(workspace.RunNetOnce(mask_rcnn_model.init.net));
                   CAFFE_ENFORCE(workspace.CreateNet(mask_rcnn_model.predict.net));

Thanks!!!

**Comment by Maratyszcza** [comment]
Are you using the latest Caffe2 checkout? `AffineChannel` operator was added 9 days ago

**Comment by hxw111** [comment]
@Maratyszcza  Do you mean that my version of Caffe2  C++ is too low to support AffineChannel ？

**Comment by Maratyszcza** [comment]
@hxw111 This is possible

**Comment by samhodge** [comment]
If you share your code I can try, I built caffe2 from the master yesterday, under Ubuntu 16.04

**Comment by hxw111** [comment]
@samhodge The above is all of the C++ code.  Detectron's Python code has not been modified, and I just added a part of the code to save the.Pb file. Did you make a modification on the Python code of Detectron?
This is the python code to save the .pb file :

    model = infer_engine.initialize_model_from_cfg()
    c2_model = model.net.Proto()
    from caffe2.python import workspace
    from caffe2.python.predictor import mobile_exporter
    init_net, predict_net = mobile_exporter.Export(workspace, c2_model, c2_model.external_input)
    with open('init_net.pb', "wb") as fopen:
             fopen.write(init_net.SerializeToString())
    with open('predict_net.pb', "wb") as fopen:
             fopen.write(predict_net.SerializeToString())

**Comment by hxw111** [comment]
@Maratyszcza  But I can run the python program in caffe2  and c++ can't. Are there multiple different versions of caffe2 c++?

**Comment by orionr** [comment]
Hi @hxw111. Only some Detectron models (and associated operators) are currently supported for raw Caffe2 with only C++ ops. We have two right now in the Caffe2 model zoo

https://github.com/caffe2/models/tree/master/detectron

and we'll be adding more as they are supported.

If you're curious, the script used to convert those is

https://github.com/facebookresearch/Detectron/blob/master/tools/convert_pkl_to_pb.py

Hope that helps. I'm going to close this.
