### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by DecenWill** [facebookarchive/caffe2#1828]
If this is a build issue, please fill out the template below.

### System information

* Operating system: ubuntu14.04
* Compiler version: gcc 4.8.5  g++4.8.5
* CMake version: 3.1.0
* CMake arguments: 
* Relevant libraries/versions (e.g. CUDA): cuda8.0 

### CMake summary output
/caffe2/caffe2/operators/fused_rowwise_8bit_conversion_ops.h:84:32: error: ‘const ScalarMultipleReturnType’ has no member named ‘round’
                               .round()
/caffe2/caffe2/operators/fused_rowwise_8bit_conversion_ops.h:85:44: error: expected primary-expression before ‘>’ token
                               .cast<uint8_t>();
                                            ^
/home/ubuntu-lee/WangXD/caffe2/caffe2/operators/fused_rowwise_8bit_conversion_ops.h:85:46: error: expected primary-expression before ‘)’ token
                               .cast<uint8_t>();
                                              ^

```
******** Summary ********
<please paste summary output here>
```

**Comment by Yangqing** [comment]
What Eigen version are you using? From the code:

https://github.com/caffe2/caffe2/blob/afb4dbce17a28390b5de3bf23dfcc790237fbff3/caffe2/operators/fused_rowwise_8bit_conversion_ops.h#L84-L85

It seems to be invoking standard Eigen expressions, so it is likely that there is an old / incompatible Eigen version issue.

**Comment by DecenWill** [comment]
@Yangqing Thanks! I remove all the eigen in "\usr\inclue\", and it works.
