### ISSUE TITLE
Documentation missing 1 character

### ISSUE THREAD

**Issue by kwierman** [facebookarchive/caffe2#1837]
Under the page https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile in the "Install Dependencies" section, there is a '\' missing on line 16.

**Comment by orionr** [comment]
Thank you, @kwierman, for the heads up! Should be fixed in a few minutes.

**Comment by kwierman** [comment]
Much thanks! Makes the copypasta that much easier for us lazy folks.
