### ISSUE TITLE
Cannot Open libnvrtc.so.8.0 if not in 

### ISSUE THREAD

**Issue by dailycafi** [facebookarchive/caffe2#1838]
### System information

* Operating system: Ubuntu 16.04 LTS
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
* CMake version: 
* CMake arguments: No arguments
* Relevant libraries/versions (e.g. CUDA): CUDA 9.0 / CUDNN 6.0
* **I'm running caffe2 in conda venv** which is a python 2.7 env.

I have installed caffe2 successfully, and within /home/mm/Library/caffe2/build (where I installed caffe2), everything works correctly, 

python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"

Printed 'Success', GPU works correctly as well.

but if I'm not in that path, for example ~/, python print failure info as:

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnvrtc.so.8.0: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)

I guess it might be an environment  variable problem, I tried and add everything possible in ~/.bashrc, currently setting is:

export CUDA_HOME=/usr/local/cuda-9.0
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-9.0/bin:$PATH
export PATH=/home/mm/anaconda3/bin:$PATH
export PATH=/usr/local/caffe2:$PATH
export PATH=/home/mm/Library/caffe2:$PATH
export PATH=/home/mm/Library/caffe2/build:$PATH
export PYTHONPATH=/usr/bin/python
export PYTHONPATH=/usr/local:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:/home/mm/Library/caffe2/build

but not working.

What should I do ?

Thank you very much.

**Comment by pietern** [comment]
If you compiled against CUDA 9.0 and get an error message talking about libnvrtc.so.8.0 then something has gone wrong. You're either not compiling successfully against 9.0, or you're picking up an older version that is built against 8.0.

Can you post your CMake summary?

**Comment by dailycafi** [comment]
no error messages, I'll post soon.
Actually if I'm in the build folder everything works just fine, no libnvrtc error as well, so I guess it should be path error?

**Comment by dailycafi** [comment]
I fixed it thank you.
I changed 

export PYTHONPATH=$PYTHONPATH:/home/mm/Library/caffe2/build
to
export PYTHONPATH=/home/mm/Library/caffe2/build:$PYTHONPATH
