### ISSUE TITLE
Broken caffe2 documentation link

### ISSUE THREAD

**Issue by k22jung** [facebookarchive/caffe2#1852]
I am trying to follow this [link](https://caffe2.ai/doxygen-c/html/classcaffe2_1_1Blob.html) to get some information on `GetMutable` for C++, but it seems to be broken. Did it move elsewhere?

**Comment by orionr** [comment]
Thanks @k22jung for the heads up. We just updated our documentation to be lowercase and this is now at

https://caffe2.ai/doxygen-c/html/classcaffe2_1_1_blob.html

vs the link above which is

https://caffe2.ai/doxygen-c/html/classcaffe2_1_1Blob.html

I'll see if I can get GitHub pages to redirect mixed case links.

**Comment by orionr** [comment]
@k22jung Google has re-indexed our pages, so the links should be fixed. Thanks again for the heads up!
