### ISSUE TITLE
caffe2 installation failure!!

### ISSUE THREAD

**Issue by ccs1605** [facebookarchive/caffe2#1856]
![screenshot from 2018-02-01 12-20-33](https://user-images.githubusercontent.com/23208578/35661060-a2c3c75a-074a-11e8-8d8d-0c41dd240117.png)
i have been looking for a fix for days, could you guys check it out what the problem is?
it seems the environment variables are corrected. i use cuda 8.0 and cudnn6.0 on Ubuntu.

"from: can't read /var/mail/caffe2.python"  what does it mean?
thanks for reading.

**Comment by ccs1605** [comment]
solved by using default python2.7 environment. but now i got 
This caffe2 python run does not have GPU support. Will run in CPU only mode.

**Comment by ccs1605** [comment]
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
E0201 16:48:24.906817  6967 init_intrinsics_check.cc:54] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0201 16:48:24.906844  6967 init_intrinsics_check.cc:54] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0201 16:48:24.906848  6967 init_intrinsics_check.cc:54] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([[[[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]]],


       [[[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 ,  0.7018167 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]]],


       [[[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.51741445, -0.8319904 ,
           0.28073958]]],


       [[[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.51262856, -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
           0.1274675 ]]],


       [[[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [ 0.8868893 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]],

        [[-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ],
         [-0.8319904 , -0.8319904 , -0.8319904 , -0.8319904 ,
          -0.8319904 ]]]], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.26504746, -0.5852637 , -0.24198551,  0.9139152 ], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.73202604], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.05027767, 0.05027767], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.17020066, -0.17020066, -0.17020066], dtype=float32), gc=, dc=[], engine=u'CUDNN')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([[-0.29375032],
       [-0.29375032]], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.60619503, 0.6307493 , 0.586683  , 0.586683  , 0.586683  ],
      dtype=float32), gc=, dc=[], engine=u'CUDNN')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.15310226, -0.929295  ], dtype=float32), gc=, dc=[], engine=u'')
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([-0.788608  , -0.21373078,  0.4379274 ], dtype=float32), gc=, dc=[], engine=u'CUDNN')
.
----------------------------------------------------------------------
Ran 1 test in 0.177s

OK

**Comment by pjh5** [comment]
Can you post your cmake output? This should be a two-column list that include lines like "USE_CUDA    : ON" and "Cuda_version   : x.x"

Can you also run `find / -name caffe2_pybind11_state* 2>/dev/null` and post that output too?

The first problem that you had was missing the python package 'future'.
The second problem is either that Caffe2 was not compiled to use the GPU, or an error in environment variables / paths that prevents Caffe2 from finding the GPU at runtime.

**Comment by ccs1605** [comment]
thanks for answering!
`
ray@ray-MS-7996:~$ find / -name caffe2_pybind11_state* 2>/dev/null
/home/ray/caffe2/build/caffe2/python/caffe2_pybind11_state.so
/home/ray/caffe2/build/caffe2/CMakeFiles/caffe2_pybind11_state.dir
/usr/local/caffe2/python/caffe2_pybind11_state.so
/usr/local/caffe2/CMakeFiles/caffe2_pybind11_state.dir
`
you are right, it is wrong python environment for caffe2 finding GPU.

**Comment by pjh5** [comment]
This shouldn't be related to the python environment, as the needed GPU libraries cannot be installed with Python. See https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support for help installing with GPU. You will need to go follow instructions from your GPU provider

**Comment by ccs1605** [comment]
@pjh5 you are absolutely right. i switched to nvidia-docker and got the program started running.

**Comment by pjh5** [comment]
Glad it's working now. I will close this issue. Please open a new issue if you encounter any more problems.
