### ISSUE TITLE
/lib/libcaffe2_gpu.so: undefined reference to `cv::String::...'

### ISSUE THREAD

**Issue by PkuRainBow** [facebookarchive/caffe2#1864]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Ubuntu16.04
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* CMake version: 3.5.1
* CMake arguments: default
* Relevant libraries/versions (e.g. CUDA): CUDA8.0 cudnn6.0

### CMake summary output

**_[ 75%] Linking CXX executable ../bin/fully_connected_op_gpu_test
[ 75%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_mkl.cc.o
../lib/libcaffe2_gpu.so: undefined reference to `cv::String::allocate(unsigned long)'
../lib/libcaffe2_gpu.so: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
../lib/libcaffe2_gpu.so: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:131: recipe for target 'bin/elementwise_op_gpu_test' failed_**

I meet this error when excuting the make command in the caffe2 folder.

**Comment by pjh5** [comment]
Can you post your cmake output? It should be a two-column list of things like "USE_OPENCV     : ON"
Are you using opencv? If so what version? (the answer to this will be in the cmake output)

**Comment by PkuRainBow** [comment]
Like this ? I find the following log in the CMakeCache.txt.

So where is the make configure files that I can choose the Opencv path? I mean exactly which file under the caffe2 folder.

I find that OpenCVConfig.cmake file under the folder /usr/share/OpenCV and check the content, but I still can't figure out how to specify the Opencv path. 

I use python2.7 and install the opencv by "pip install opencv-python".  I have also tried to build the opencv from the source code and build it successfully. So how could I specify the building path for the opencv in the caffe2?

```
//Path where debug 3rdpaty OpenCV dependencies are located
OpenCV_3RDPARTY_LIB_DIR_DBG:PATH=

//Path where release 3rdpaty OpenCV dependencies are located
OpenCV_3RDPARTY_LIB_DIR_OPT:PATH=

OpenCV_CONFIG_PATH:FILEPATH=/usr/share/OpenCV

//The directory containing a CMake configuration file for OpenCV.
OpenCV_DIR:PATH=/usr/share/OpenCV

//Path where debug OpenCV libraries are located
OpenCV_LIB_DIR_DBG:PATH=

//Path where release OpenCV libraries are located
OpenCV_LIB_DIR_OPT:PATH=
```

**Comment by pjh5** [comment]
Our cmake build system tries to find your opencv installation with the find_package function https://cmake.org/cmake/help/latest/command/find_package.html at these lines in cmake/Dependencies.cmake https://github.com/caffe2/caffe2/blob/master/cmake/Dependencies.cmake#L210-L226 . It will try to build with opencv by default because of this flag https://github.com/caffe2/caffe2/blob/master/CMakeLists.txt#L45 , but explicitly passing -DUSE_OPENCV into the cmake command will cause the build process to fail if it can't find opencv (instead of just turning the feature off quietly).

The cmake output for Ubuntu will be early on in the output of the 'make' command, and not saved to a file. I'll change the instructions to make this a separate command.

**Comment by pjh5** [comment]
Can you post your opencv version? Along with `find / -name libopencv* 2>/dev/null` ?

**Comment by PkuRainBow** [comment]
It seems that I have installed multiple opencv............   Including Opencv3.4/  2.4.13 /

**Comment by pjh5** [comment]
Can you try uninstalling one of those OpenCVs so that there is only one working installation? It might be safest to uninstall both of them and then reinstall one.

You're not using Anaconda right?

**Comment by zimenglan-sysu-512** [comment]
hi @PkuRainBow,
have u solved this problem?

**Comment by PkuRainBow** [comment]
@zimenglan-sysu-512 Yes, you can remove most of the opencv library and reinstall it.
