### ISSUE TITLE
why caffe2 download needed library but make command can't find them?

### ISSUE THREAD

**Issue by robosina** [facebookarchive/caffe2#1866]
System Informaiton is:
* Operating system: `Ubuntu16.04.3`
* Compiler version: `gcc version: 5.4.0`
* CMake version: `cmake version 3.5.1`
* CMake arguments: 
* Relevant libraries/versions (e.g. CUDA):`using nvcc --version command`
**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44**

### CMake summary output

```
******** Summary ********
<-- Does not need to define long separately.
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY) 
-- Use custom protobuf build.
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY) (found version "1.2.8")
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing:  NNPACK_INCLUDE_DIR NNPACK_LIBRARY PTHREADPOOL_LIBRARY CPUINFO_LIBRARY) 
-- Brace yourself, we are building NNPACK
-- Cannot find gflags with config files. Using legacy find.
-- Could NOT find gflags (missing:  GFLAGS_LIBRARY) 
-- Cannot find glog. Using legacy find.
-- Could NOT find glog (missing:  GLOG_LIBRARY) 
-- Could NOT find LMDB (missing:  LMDB_LIBRARIES) 
-- Found LevelDB (include: /usr/include, library: /usr/local/lib/libleveldb.so)
-- Could NOT find Snappy (missing:  Snappy_LIBRARIES) 
-- Could NOT find RocksDB (missing:  RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
-- Configuring incomplete, errors occurred!
>
```

But it's strange to me because I Downloaded caffe using below command in my terminal( You can access the main tutorial via [this link](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support))

     sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libgtest-dev \
      libiomp-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libopenmpi-dev \
      libsnappy-dev \
      libprotobuf-dev \
      openmpi-bin \
      openmpi-doc \
      protobuf-compiler \
      python-dev \
      python-pip 
I see that this package has been installed but why make command can't find any of them?

Thanks

**Comment by pjh5** [comment]
Caffe2 can be built with lots of optional libraries, depending on your environment and use-cases. This cmake output is telling out about optional libraries that it did not find, and so it won't build with. The apt-get install instruction that you ran installed only required and recommended libraries.

**Comment by robosina** [comment]
@pjh5 , But my `make` command gave me error , So are you telling that even if we use `sudo apt install  libleveldb-dev ` command , it is usual that cmake cant find libdevel lib?

How I can fix it? I don't wan't to change my cmake options(if it is possible)
