### ISSUE TITLE
caffe2 build error

### ISSUE THREAD

**Issue by GeorgeBohw** [facebookarchive/caffe2#1877]
If this is a build issue, please fill out the template below.

### System information

* Operating system:
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
******** Summary ********
<please paste summary output here>
```
This is my summary:
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1033-g0379390-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 9.1
--     CuDNN version       : 7.0.2
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.70
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF

system:ubuntu16.04
Gpu:cuda8.0 
Cudnn:6.0

Error as following:
../lib/libcaffe2_gpu.so：对‘caffe2::EnforceNotMet::AppendMessage(std::string const&)’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_get_l4_cache’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<double, std::allocator<double> > caffe2::ArgumentHelper::GetRepeatedArgument<double>(std::string const&, std::vector<double, std::allocator<double> > const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::detail::extractNetDef(caffe2::OperatorDef const&, std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::Workspace::CreateBlob(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘long caffe2::TypeMeta::Id<std::string>()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::gRegisteredTypeNames()’未定义的引用
../lib/libcaffe2_gpu.so：对‘long caffe2::ArgumentHelper::GetSingleArgument<long>(std::string const&, long const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::detail::extractLinks(caffe2::OperatorBase*, std::string const&, std::string const&, std::string const&, std::string const&, std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> >*)’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::GetSingleArgument<bool>(std::string const&, bool const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::OpSchema::SetDoc(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::gTypeNames()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::StringToPadMode(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘double caffe2::ArgumentHelper::GetSingleArgument<double>(std::string const&, double const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&, void const*)’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<int>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<caffe2::NetDef>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘unsigned short caffe2::ArgumentHelper::GetSingleArgument<unsigned short>(std::string const&, unsigned short const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘int caffe2::ArgumentHelper::GetSingleArgument<int>(std::string const&, int const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::base::CheckOpMessageBuilder::NewString()’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<float>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::ArgumentHelper::HasArgument(std::string const&) const’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_get_l3_cache’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::protobuf::internal::StringTypeHandlerBase::New()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::OpSchemaRegistry::map()’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_isa’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::Workspace::GetBlob(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘short caffe2::ArgumentHelper::GetSingleArgument<short>(std::string const&, short const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::unique_ptr<caffe2::RecurrentNetworkExecutorBase, std::default_delete<caffe2::RecurrentNetworkExecutorBase> > caffe2::createRNNExecutor<caffe2::CUDAContext>(caffe2::NetDef const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >&, std::string, caffe2::ArgumentHelper)’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<bool, std::allocator<bool> > caffe2::ArgumentHelper::GetRepeatedArgument<bool>(std::string const&, std::vector<bool, std::allocator<bool> > const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::protobuf::Message::ShortDebugString() const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::protobuf::internal::empty_string_’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<long>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::detail::GetRecurrentMapping(std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> > const&, bool)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::TensorPrinter::TensorPrinter(std::string const&, std::string const&, int)’未定义的引用
../lib/libcaffe2_gpu.so：对‘signed char caffe2::ArgumentHelper::GetSingleArgument<signed char>(std::string const&, signed char const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::HasOutput(caffe2::OperatorDef const&, std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::GradientRegistry()’未定义的引用
../lib/libcaffe2_gpu.so：对‘float caffe2::ArgumentHelper::GetSingleArgument<float>(std::string const&, float const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘gloo::getCudaPCIBusID[abi:cxx11](int)’未定义的引用
../lib/libcaffe2_gpu.so：对‘unsigned char caffe2::ArgumentHelper::GetSingleArgument<unsigned char>(std::string const&, unsigned char const&) const’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_get_l2_cache’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<std::string, std::allocator<std::string> > caffe2::ArgumentHelper::GetRepeatedArgument<std::string>(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::CUDAOperatorRegistry()’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<float, std::allocator<float> > caffe2::ArgumentHelper::GetRepeatedArgument<float>(std::string const&, std::vector<float, std::allocator<float> > const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<std::string>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::string const&, int*)’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<long, std::allocator<long> > caffe2::ArgumentHelper::GetRepeatedArgument<long>(std::string const&, std::vector<long, std::allocator<long> > const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::detail::AddApplyLinkOps(std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> > const&, std::string, caffe2::DeviceOption const&, caffe2::NetDef*)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::GetArgument(caffe2::OperatorDef const&, std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::Workspace::GetNet(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::string caffe2::ArgumentHelper::GetSingleArgument<std::string>(std::string const&, std::string const&) const’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_get_l1d_cache’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<int, std::allocator<int> > caffe2::ArgumentHelper::GetRepeatedArgument<int>(std::string const&, std::vector<int, std::allocator<int> > const&) const’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_initialize’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::Demangle(char const*)’未定义的引用
../lib/libcaffe2.so：对‘cpuinfo_deinitialize’未定义的引用
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:132: recipe for target 'bin/utility_ops_gpu_test' failed
make[3]: *** [bin/utility_ops_gpu_test] Error 1
make[3]: Leaving directory '/home/george/project/caffe2/build'
CMakeFiles/Makefile2:1249: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
make[2]: Leaving directory '/home/george/project/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/george/project/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

i have uninstall protobuf and install it again，but i didn't work...

**Comment by GeorgeBohw** [comment]
find / -name libproto* 2>/dev/null  output:
/var/lib/dpkg/info/libprotoc9v5:amd64.list
/var/lib/dpkg/info/libprotoc9v5:amd64.triggers
/var/lib/dpkg/info/libprotobuf9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf-dev:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.list
/var/lib/dpkg/info/libprotobuf-c-dev.list
/var/lib/dpkg/info/libprotobuf9v5:amd64.triggers
/var/lib/dpkg/info/libprotobuf-c1.shlibs
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf9v5:amd64.list
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.triggers
/var/lib/dpkg/info/libprotoc9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-c1.list
/var/lib/dpkg/info/libprotobuf-c1.triggers
/var/lib/dpkg/info/libprotobuf-c1.md5sums
/var/lib/dpkg/info/libprotobuf-c-dev.md5sums
/var/lib/dpkg/info/libprotobuf-c1.symbols
/var/lib/dpkg/info/libprotoc9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf-dev:amd64.list
/var/cache/apt/archives/libprotobuf-dev_2.6.1-1.3_amd64.deb
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0.tar.bz2
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf.a
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf-lite.so.14
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf.so.14.0.0
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotoc.so.14
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf-lite.la
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotoc.so
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf.so.14
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf-lite.so
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf.la
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf-lite.a
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotoc.a
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotoc.so.14.0.0
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotoc.la
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf.so
/home/george/anaconda2_bak/pkgs/libprotobuf-3.4.0-0/lib/libprotobuf-lite.so.14.0.0
/home/george/anaconda2_bak/conda-meta/libprotobuf-3.4.0-0.json
/home/george/anaconda2_bak/lib/libprotobuf.a
/home/george/anaconda2_bak/lib/libprotobuf-lite.so.14
/home/george/anaconda2_bak/lib/libprotobuf.so.14.0.0
/home/george/anaconda2_bak/lib/libprotoc.so.14
/home/george/anaconda2_bak/lib/libprotobuf-lite.la
/home/george/anaconda2_bak/lib/libprotoc.so
/home/george/anaconda2_bak/lib/libprotobuf.so.14
/home/george/anaconda2_bak/lib/libprotobuf-lite.so
/home/george/anaconda2_bak/lib/libprotobuf.la
/home/george/anaconda2_bak/lib/libprotobuf-lite.a
/home/george/anaconda2_bak/lib/libprotoc.a
/home/george/anaconda2_bak/lib/libprotoc.so.14.0.0
/home/george/anaconda2_bak/lib/libprotoc.la
/home/george/anaconda2_bak/lib/libprotobuf.so
/home/george/anaconda2_bak/lib/libprotobuf-lite.so.14.0.0
/home/george/project/caffe2/third_party/protobuf/cmake/libprotobuf.cmake
/home/george/project/caffe2/third_party/protobuf/cmake/libprotobuf-lite.cmake
/home/george/project/caffe2/third_party/protobuf/cmake/libprotoc.cmake
/home/george/project/caffe2/third_party/protobuf/src/libprotobuf-lite.map
/home/george/project/caffe2/third_party/protobuf/src/libprotoc.map
/home/george/project/caffe2/third_party/protobuf/src/libprotobuf.map
/home/george/software/protobuf-2.5.0/vsprojects/libprotoc.vcproj
/home/george/software/protobuf-2.5.0/vsprojects/libprotobuf-lite.vcproj
/home/george/software/protobuf-2.5.0/vsprojects/libprotobuf.vcproj
/home/george/software/protobuf/cmake/libprotobuf.cmake
/home/george/software/protobuf/cmake/libprotobuf-lite.cmake
/home/george/software/protobuf/cmake/libprotoc.cmake
/home/george/software/protobuf/src/libprotobuf-lite.map
/home/george/software/protobuf/src/libprotoc.map
/home/george/software/protobuf/src/libprotobuf.map
/home/george/.linuxbrew/Library/Formula/libprotoident.rb
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/cmake/libprotobuf.cmake
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/cmake/libprotobuf-lite.cmake
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/cmake/libprotoc.cmake
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/src/libprotobuf-lite.map
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/src/libprotoc.map
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/external/protobuf_archive/src/libprotobuf.map
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotobuf_lite.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotoc_lib.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotobuf.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotobuf.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotobuf_lite.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/external/protobuf_archive/libprotoc_lib.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/core/libprotos_all_cc.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/core/libprotos_all_cc.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/core/libproto_text.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/core/libproto_text.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/external/protobuf_archive/libprotobuf_lite.pic.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/external/protobuf_archive/libprotobuf.pic.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/external/protobuf_archive/libprotobuf_lite.pic.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/external/protobuf_archive/libprotobuf.pic.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/libprotos_all_cc.pic.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/libproto_text.pic.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/libproto_text.pic.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/profiler/libprotos_all_cc.pic.a-2.params
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/profiler/libprotos_all_cc.pic.a
/home/george/.cache/bazel/_bazel_root/651d62b43db8fda539a55221c00c07a8/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/libprotos_all_cc.pic.a
/usr/local/MATLAB/R2017a/bin/glnxa64/libprotobuf.so.9.0.1
/usr/local/MATLAB/R2017a/bin/glnxa64/libprotobuf.so.9
/usr/local/MATLAB/R2017a/toolbox/compiler_sdk/mps_clients/c/glnxa64/lib/libprotobuf.so.9.0.1
/usr/local/MATLAB/R2017a/toolbox/compiler_sdk/mps_clients/c/glnxa64/lib/libprotobuf.so.9
/usr/local/MATLAB/R2017a/toolbox/compiler_sdk/mps_clients/c/glnxa64/lib/libprotobuf.so
/usr/local/lib/libprotobuf-lite.so.8
/usr/local/lib/libprotobuf.so.8.0.0
/usr/local/lib/libprotobuf.so.8
/usr/local/lib/libprotobuf-lite.so.8.0.0
/usr/local/lib/libprotoc.so.8.0.0
/usr/local/lib/libprotoc.so.8
/usr/share/doc/libprotobuf-c1
/usr/share/doc/libprotobuf-c-dev
/usr/share/doc/libprotobuf-lite9v5
/usr/share/doc/libprotobuf9v5
/usr/share/doc/libprotoc9v5
/usr/share/doc/libprotobuf-dev
/usr/lib/libreoffice/program/libprotocolhandlerlo.so
/usr/lib/x86_64-linux-gnu/libprotoc.so.9
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1
/usr/lib/x86_64-linux-gnu/libprotobuf-c.so
/usr/lib/x86_64-linux-gnu/libprotobuf.a
/usr/lib/x86_64-linux-gnu/libprotobuf.so.9.0.1
/usr/lib/x86_64-linux-gnu/libprotobuf.so.9
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
/usr/lib/x86_64-linux-gnu/libprotoc.so.9.0.1
/usr/lib/x86_64-linux-gnu/pkgconfig/libprotobuf-c.pc
/usr/lib/x86_64-linux-gnu/libprotobuf-c.so.1
/usr/lib/x86_64-linux-gnu/libprotobuf-c.a
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.a
/usr/lib/x86_64-linux-gnu/libprotobuf-c.so.1.0.0
/usr/lib/x86_64-linux-gnu/libprotobuf.so
/usr/lib/pulse-8.0/modules/libprotocol-cli.so
/usr/lib/pulse-8.0/modules/libprotocol-simple.so
/usr/lib/pulse-8.0/modules/libprotocol-http.so
/usr/lib/pulse-8.0/modules/libprotocol-native.so

what's wrong with it,anybody know it's solution?

**Comment by pjh5** [comment]
Are you trying to use your Anaconda environment? If not pass -DPRIORITIZE_ANACONDA to cmake your cmake command.

How did you install gloo? What commit of Caffe2 are you on?

**Comment by GeorgeBohw** [comment]
@pjh5 tanks for ur response,i never try anaconda,i will try it.
I think my caffe2 is the latest caffe2,i just git clone with this command:
git clone --recursive https://github.com/caffe2/caffe2.git.
Do i need to install gloo specially,i thought the "make" can install it automatically.

**Comment by GeorgeBohw** [comment]
@pjh5 I remembered that ever i typeed "make" with my Anaconda environment,the error is the same.

**Comment by pjh5** [comment]
If you don't want to use anaconda then I'd recommend removing the anaconda2_bak folder, which looks like a backup of your last Anaconda installation.

Have you also deleted your build folder before trying to make Caffe2 to remove any cached build artifacts? Also delete your old Caffe2 installations. These are probably in a location like /usr/local. You can find these with `find / -name caffe* 2>/dev/null`. This command will also find your caffe2 source directory, so be careful not to delete that too. Try making Caffe2 after these directories have been deleted.

If that doesn't work, could you remove some of your protobuf installations? You seem to have installations under your Caffe2 folder, from bazel, from tensorflow, in /usr/local/lib and in /usr/lib, in Matlab, and in other places I don't recognize. My best guess is that all these different protobuf versions are causing confusion.

**Comment by GeorgeBohw** [comment]
@pjh5 I delete all the protobuf ，so "find / -name libproto* 2>/dev/null" gives output：

/home/george/.linuxbrew/Library/Formula/libprotoident.rb
/usr/lib/libreoffice/program/libprotocolhandlerlo.so
/usr/lib/pulse-8.0/modules/libprotocol-cli.so
/usr/lib/pulse-8.0/modules/libprotocol-simple.so
/usr/lib/pulse-8.0/modules/libprotocol-http.so
/usr/lib/pulse-8.0/modules/libprotocol-native.so


Then i install it again,but error as following:
$ protoc --version
protoc: error while loading shared libraries: libprotoc.so.9: cannot open shared object file: No such file or directory
$ locate libprotoc.so.9
/usr/lib/x86_64-linux-gnu/libprotoc.so.9
/usr/lib/x86_64-linux-gnu/libprotoc.so.9.0.1
$ ls -al /usr/lib/x86_64-linux-gnu/libprotoc.so.9
ls: can't find '/usr/lib/x86_64-linux-gnu/libprotoc.so.9'

so what's wrong with it?
thanks for ur help!

**Comment by pjh5** [comment]
Protobuf comes in two parts, the protobuf libraries libprotobuf and libprotoc, and also a protobuf executable called protoc. Protoc needs libprotoc to run, but they exist as separate binaries, so protoc just knows where to look for libprotoc at runtime. If you delete libprotoc, protoc does not know that libprotoc no longer exists, and will continue to look for it in the same place. This is called dynamic linking if you want to learn more.

I should've given you a better command to run. `find / -name *proto* 2>/dev/null` will find all of the protobuf versions, but it will also probably find a lot of other things too. Or `find / -name protoc 2>/dev/null` may be all you need at this point. In my experience, it is usually only needed to delete the libproto* and the protoc. In the future, I'd recommend always trying to uninstall with package managers first, i.e.
`pip uninstall protobuf && conda uninstall protobuf && apt-get uninstall libprotobuf`

**Comment by GeorgeBohw** [comment]
@pjh5 Finally my computer can't start correctly, which makes me to reinstall ubuntu.
It seems that i find out the reason which i am validating now,i didn't install caffe2 according to the instructuions recommanded!
The wrong command i used is:
#git clone ...
# cd caff2
#make 

Thanks for ur help, great appreciate!

**Comment by pjh5** [comment]
I believe that github has messed up the formatting of your post.

But if it is working then I will close this issue. Please open another issue if any other problems arise.
