### ISSUE TITLE
Undefined reference to google::protobuf::internal::empty_string_[abi:cxx11]

### ISSUE THREAD

**Issue by acewjh** [facebookarchive/caffe2#1881]
I fixed a protobuf problem(**Undefined reference to google::protobuf::internal::empty_string_[abi:cxx11]**) while building caffe2 by reinstalling protobuf with official github code. However, when I successfully installed it and tried to import caffe2.python.core in python,  it first informed me **google.protobuf is not installed**, after I **conda installed** the package it turned out to be a CRITICAL error, these are the messages from the python interpreter:
**>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /home/wjh/workspace/caffe2/caffe2/build/lib/libcaffe2.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
CRITICAL:root:Cannot load caffe2.python. Error: caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E**
BTW, I also installed caffe2 with GPU support and didn't appear any problem in the whole installation process. This is my environment information:
**System: Ubuntu 16.04.4
Compiler: gcc 5.4.0
cmake: version 3.5.1
protobuf: version 3.5.1
CUDA: version 8.0.44
CUDNN: version 7.0.4**
I tried to google the problem but didn't find any help and I've been trying to fix it for the past few days, so any help is appreciated : ) !

**Comment by pjh5** [comment]
If you built Caffe2 with a system version of Protobuf and then later installed protobuf with conda, then I think Caffe2 will pick up the conda version before the system one, which will break if the conda version is different from the system one. Our cmake will always prefer Anaconda packages to system ones, unless -DPRIORITIZE_ANACONDA is passed to the cmake command (I don't recommend doing this).

Where are all of your protobuf installations? `find / -name libproto* 2>/dev/null` should tell you this.

Are you installing with the 'custom' Anaconda installation instructions or the conda-build ones? If using the custom ones, make sure to delete the build folder before trying to build again, as the build folder may cache artifacts built with a different protobuf version. Also, if using the custom path, what are you setting CMAKE_PREFIX_PATH and CMAKE_INSTALL_PATH to?

Are you installing Caffe2 into a specific Anaconda environment? If so, is there protobuf installed in that environment or in the default conda environment (`conda list protobuf` both when in that environment and when 'not' in any conda environment)?

**Comment by acewjh** [comment]
Thanks for help : ) , I didn't build with Anaconda but used the Ubuntu-source-code instructions from the Caffe2 website, which is because I tried conda-build and it failed (I noticed conda-build instructions on the website has changed, maybe I should rebuild it with Anaconda?).  Here's the cmake summary:

-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1039-gcb27e06
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf include path : /usr/local/include
--   Protobuf libraries    : optimized;/usr/local/lib/libprotobuf.so;debug;/usr/local/lib/libprotobuf.so;-lpthread
--   CXX flags             :  -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python library      : /home/wjh/anaconda2/lib/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 7.0.4
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.13
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF

And here are all protobuf files I found in /usr/local/lib path:

/usr/local/lib/libprotobuf-lite.la
/usr/local/lib/libprotobuf.so.15
/usr/local/lib/libprotobuf.so.15.0.0
/usr/local/lib/libprotobuf.la
/usr/local/lib/libprotobuf-lite.a
/usr/local/lib/libprotobuf-lite.so.15.0.1
/usr/local/lib/libprotoc.so
/usr/local/lib/libprotobuf.so
/usr/local/lib/libprotoc.so.15.0.1
/usr/local/lib/libprotobuf.so.15.0.1
/usr/local/lib/libprotoc.a
/usr/local/lib/libprotobuf-lite.so
/usr/local/lib/libprotoc.la
/usr/local/lib/libprotoc.so.15.0.0
/usr/local/lib/libprotobuf.a
/usr/local/lib/libprotobuf-lite.so.15
/usr/local/lib/libprotobuf-lite.so.15.0.0
/usr/local/lib/libprotoc.so.15

I built successfully with this protobuf installation but why it still can't find protobuf? The building process took a lot of time, is it possible that I fix it with configuration so that don't have to build again? Thanks for help.

**Comment by pjh5** [comment]
If you don't want to use Anaconda, then I would recommend removing it entirely, or using the DPRIORITIZE_ANACONDA flag and making sure anaconda is not in your path. It looks like you are using a system installed protobuf, but your python is from Anaconda, and I believe Anaconda's python version is set up with an internal PYTHONPATH pointing to Anaconda, which will then search for libraries under Anaconda at runtime before searching system locations. If there's a different version of protobuf in Anaconda than in /usr/local, this could cause the problem.

If you find your Caffe2 installation (`find / -name libcaffe2.* 2>/dev/null`), you could run 'ldd' on it to see where it thinks protobuf should be. This protobuf version needs to be compatible with the protobuf executable `protoc` that was used during the build of Caffe2.

The new Anaconda instructions using conda-build should work even if you have conflicting protobuf versions in Anaconda and as system libraries (I'd recommend it, it's more robust). Make sure to pull new code to use the new instructions. Note that using the new conda-build instructions will install Caffe2 into the current conda environment, insulated from other conda environments. 

Before building again in any way, I recommend deleting all build folders and old Caffe2 installations, as caching can exacerbate protobuf problems.

**Comment by pjh5** [comment]
For future updates on this, see #1980
