### ISSUE TITLE
[ 52%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o

### ISSUE THREAD

**Issue by YGHyuan** [facebookarchive/caffe2#1886]
If this is a build issue, please fill out the template below.

### System information

* Operating system:ubuntu17.10 server
* Compiler version:gcc version 6.4.0 20171010 (Ubuntu 6.4.0-8ubuntu1)
* CMake version:
* CMake arguments:cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH -D__GLIBCXX__=20160904" ..
* Relevant libraries/versions (e.g. CUDA):nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

### CMake summary output

```
******** Summary ********
[ 52%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o
/home/urfresh/caffe2/caffe2/core/common.h(232): error: namespace "std" has no member "to_string"
/home/urfresh/caffe2/caffe2/core/common.h(233): error: namespace "std" has no member "stoi"
/home/urfresh/caffe2/caffe2/core/common.h(234): error: namespace "std" has no member "stod"
3 errors detected in the compilation of "/tmp/tmpxft_000022a8_00000000-7_math_gpu.cpp1.ii".
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/urfresh/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/utils/./caffe2_gpu_generated_math_gpu.cu.o
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:1273: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o] Error 1
CMakeFiles/Makefile2:1919: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by pjh5** [comment]
It looks like we're also setting CMAKE_CXX_FLAGS here https://github.com/caffe2/caffe2/blob/0379390c7c995dca4388e9655fca7aba03157964/CMakeLists.txt#L102 . Do you know if the flags you're passing are working with the ones we set?

**Comment by YGHyuan** [comment]
@pjh5 ,thank you so much!
But I just have the operating system ubuntu16.04 instead. Finally,it succeeded.

**Comment by Gpwner** [comment]
I got the same error on ubuntu 16.04

**Comment by pjh5** [comment]
@Gpwner Can you post a new issue on the Pytorch issues page and give all the requested information in the issue template? https://github.com/pytorch/pytorch/issues

**Comment by Rahul-Venugopal** [comment]
I got the same issue during installing Caffe2 . 
@pjh5  Can you please help me to solve this ? (PS : I have posted my issue at #9181 
<  https://github.com/pytorch/pytorch/issues/9181 >

**Comment by Rahul-Venugopal** [comment]
@YGHyuan  Can you please share how you solved this issue ?

Thanks 
Rahul
