### ISSUE TITLE
where is caffe2_pybind11_state.dll

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#1889]
Trying to complete 'Python Configuration' step at https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile so that I can get Detectron running on my computer and then hopefully my app (boy installing this stuff takes ages - been at this for a whole day but have no background). Problem now is i can't find the .dll file (not searchable) and i don't appear to have a /Release folder

Says the file ("where is caffe2_pybind11_state.dll") should be at \caffe2\build\caffe2\binaries\Release however i don't have a release folder. Any suggestions on what to do?

Screen shot of what i have here:
![capture](https://user-images.githubusercontent.com/27135260/35806164-6f39aff8-0a33-11e8-9e51-b9df76de1e2c.PNG)

Been following this tutorial:
https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile
Taken me 4 hours to get this far and still have not completed the basic starting point to begin with https://github.com/facebookresearch/Detectron so would really appreciate any help/guidance. 

Thanks

* Operating system: windows 10
* Compiler version: 
* CMake version: 3.10.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): 

```

**Comment by pjh5** [comment]
This looks like a copy of https://github.com/caffe2/caffe2/issues/1802

Unfortunately the python side isn't supported very well on Windows right now. We're trying to hard to improve Windows support, but right now we recommend running a linux VM or dual-booting linux. Hopefully we'll have a better story soon.

**Comment by ghost** [comment]
ok thanks. Goal of installing on this machine was to use its Nvidia 1070Ti but ultimate goal is to demo Facebook's Detectron on a HMD (with light client and processing done on server/laptop). Do you think it's better to setup a AWS VM with GPU (if this is feasible?) for demoing around the place (but need 5G or v fast internet to demo otherwise latency will be too high for good HMD experience) or instead persisting with building server on local laptop with Nvidia (i.e. linux VM) and streaming via local 5g network? (sorry if this sounds bit random, am in uncharted waters and trying to figure out best approach for this app). Thanks

**Comment by orionr** [comment]
HI @roman3k - depending on your use case, I would say a local machine with Ubuntu (dual boot if you still need Windows) would be your best bet. You could then do tethered or not tethered with the HMD. Good luck!

I'm going to close as a duplicate of https://github.com/caffe2/caffe2/issues/1802 at this point. We'll be looking to update the Windows documentation in the near future. Stay tuned.

**Comment by ghost** [comment]
Thanks @orionr 
Challenge is I need Unity3D to run the system which doesn't support Ubuntu (very well). 
As @pjh5 suggests, could i:
1) run unity on windows 10 +
2) simultaneously run a linxuVM or Ubuntu VM on my windows10 machine to run Detectron ?
Not sure if this is feasible but could be an option so thought it worth asking. Thnx
