### ISSUE TITLE
no support GPU warning on tutorial with nvidia-docker 

### ISSUE THREAD

**Issue by netfish88** [facebookarchive/caffe2#1895]
I installed the Caffe2 by using docker as shown in the manual.
when I run the create_your_own_dataset on jupyter, it saids 

> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
> WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu

what should i do to make it GPU support after docker install ?
is there any other things to do for it?
how I can make sure whether the Caffe2 is running on GPU or CPU mode ?

I also use 1080ti x 2 cards on ubuntu 16.04 
running the jupyter with nvidia-docker 
> sudo nvidia-docker run -it -p 8888:8888 caffe2ai/caffe2 sh -c "jupyter notebook --allow-root --no-browser --ip 0.0.0.0 /caffe2/caffe2/python/tutorials"

any help please ?

**Comment by pjh5** [comment]
Can you link to the manual that you're using?

**Comment by netfish88** [comment]
@pjh5 it's official caffe2 install website. 
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=docker

according to the manual 

> If you wish to use GPU with Docker use nvidia-docker to run your image instead of regular docker. You can get nvidia-docker here.

I got nvidia-docker from https://github.com/NVIDIA/nvidia-docker

one thing exceptional case was, while I doing 
`sudo apt-get install -y nvidia-docker2` 

there was an error. 

> The following packages have unmet dependencies:
>  nvidia-docker2 : Depends: docker-ce (= 17.09.1~ce-0~ubuntu) but 17.11.0~ce-0~ubuntu is to be installed or
>                            docker-ee (= 17.09.1~ee-0~ubuntu) but it is not installable

according to an advice from https://github.com/NVIDIA/nvidia-docker/issues/502
I did it `sudo apt-get install docker-ce=17.09.1~ce-0~ubuntu`

and try again : sudo apt-get install -y nvidia-docker2

![image](https://user-images.githubusercontent.com/11173194/35893784-f4e41402-0bf2-11e8-8a18-0eda3d47e825.png)

the test sample code looks working. (I am not sure it is runs on GPU or CPU mode)

but sometimes when I run create_your_model tutorial on jupyter, those warnnings below is there. 

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu

problem is the warnning happens intermittently. 
so I want to know how can I check the caffe2 is really using GPU (or CPU)

**Comment by YGHyuan** [comment]
@netfish88 ,i have the same question.I am not sure it is runs on GPU or CPU mode.if you know,could you tell me?Thanks!

**Comment by pjh5** [comment]
I haven't used nvidia-docker before, the command I always use is 
`
docker run --runtime=nvidia -e CUDA_VERSION=native -it nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 /bin/bash
`
(and then I have to build Caffe2 from source or install with conda)

Could you run `find / -name caffe2_pybind11_state_gpu*` on the docker? If nothing is found, then the installation is broken and won't work with a GPU. Otherwise, try to add the file's location to PYTHONPATH and try running Caffe2 again.

**Comment by netfish88** [comment]
@pjh5 thanks for your advice.

![image](https://user-images.githubusercontent.com/11173194/35962774-f8a08d60-0cf5-11e8-9961-0a934bdf0201.png)

here is the result of find commend. looks like I have some files.
in this case, can I assume that it runs on gpu?

**Comment by netfish88** [comment]
@YGHyuan sorry but I don't know the exact way how it works. anyway are u korean ? 

(if u are korean, give me a FB message, there are not many korean researchers running Caffe2. ) 
( 한국분이시면 메세지 좀 주세요. 외롭게 연구중인데 Caffe2 하시려는 분과 인사 나눴으면 해서요.^^ https://www.facebook.com/netfish88 )

**Comment by YGHyuan** [comment]
@netfish88,thank you anyway!I'm Chinese.

**Comment by pjh5** [comment]
@netfish88 Try running `export PYTHONPATH=/usr/local:$PYTHONPATH` in your shell before trying to use Caffe2

**Comment by netfish88** [comment]
I found a solution on the tutorial. there was a comment in the source code. 
I would be helpful to others if there is some description in the public web site. 

```
# Configure how you want to train the model and with how many GPUs
# This is set to use two GPUs in a single machine, but if you have more GPUs, extend the array [0, 1, 2, n] 
gpus = [0]

``` 

thanks. all the comments above. I close this issue.

**Comment by pjh5** [comment]
@netfish88 are you still getting "WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu"? Did this line get rid of this error?

**Comment by groot-1313** [comment]
I am having a similar issue of `WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode`. When I run  ` sudo find / -name caffe2_pybind11_state_gpu*`, I get the following:

> anaconda3/pkgs/caffe2-cuda9.0-cudnn7-0.8.dev-py36hbcd9b4a_0/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so

Ubuntu 16.04, Cuda 9, Cudnn 7

**Comment by pjh5** [comment]
@groot-1313 is this on a nvidia-docker image? 

That file is an uninstalled anaconda package. If you ran `conda build conda/caffe2/cuda` then Anaconda will create a package on your machine but not install it. CHeck if caffe2 is installed in conda with `conda list`, and if it's not try `conda install caffe2-cuda9.0-cudnn7 --use-local`

**Comment by groot-1313** [comment]
`conda list` returns 

> caffe2-cuda9.0-cudnn7     0.8.dev          py36h643fba9_0    caffe2

I am able to  import caffe, but I get the following warning:

> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode

And my application needs caffe2 to run on GPU.

**Comment by groot-1313** [comment]
Hi, 
I ran the test. But it did not use the GPU. I installed from [here](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt) using `conda install -c caffe2 caffe2-cuda9.0-cudnn7 --use-local` as suggested by @pjh5

**Comment by pjh5** [comment]
@groot-1313 I don't think the docker images have conda on them. Since this doesn't seem related to docker, can you open up a new issue on the current issue page at https://github.com/pytorch/pytorch/issues and fill out the issue template there?

**Comment by groot-1313** [comment]
Hi, 
It worked with GPU when I built from source.
