### ISSUE TITLE
Does it exist any detail documents about caffe2?

### ISSUE THREAD

**Issue by huyangc** [facebookarchive/caffe2#1896]
I have seen the API document located at [here](https://caffe2.ai/doxygen-python/html/classcnn_1_1_c_n_n_model_helper.html). Did I find the wrong place for API document or it just like that?

I think it is a steep cliff for caffe2 newer with such kind of document. :(

**Comment by orionr** [comment]
HI @huyangc - there is definitely a learning curve and we understand. However, your best starting point is the tutorials and other content on caffe2.ai. For example

https://caffe2.ai/docs/intro-tutorial.html
https://caffe2.ai/docs/tutorial-models-and-datasets.html
https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb

Then, once you understand the basic parts of the framework (init_net, predict_net, predictor, workspaces, etc), you can look at the operator catalog at

https://caffe2.ai/docs/operators-catalogue.html

This is not exhaustive (we're working on that), but it should give you a good sense of what operators you can use in Caffe2. Also feel free to ask specific questions here.

Hope that helps.

**Comment by netfish88** [comment]
I agree that the caffe2 official site needs more document and information. 
as a new comer, is it helpful to look into the caffe1 website for understanding caffe2 ?

**Comment by huyangc** [comment]
@orionr Thanks for your detail reply first! 

I have read these documents before I ask the question here. I asked this question was just because when I  want to know the input and output of some operators like ``brew.concat``, it will be a little confused with that document. So I refer to the source code directly. It is very painful when you need some usages, and then you go to the source code first. And it may because I am not familiar with caffe2 as well.

And I am so happy to hear that you are working on the documents!
