### ISSUE TITLE
Unable to make , due to undefined reference to cv?

### ISSUE THREAD

**Issue by n3011** [facebookarchive/caffe2#19]
I am getting this error while compiling caffe2. Please help me out here. Previously I have installed and used caffe and opencv successfully. 

gen/caffe2/binaries/libconvert_encoded_to_raw_leveldb.a(convert_encoded_to_raw_leveldb.o): In function `caffe2::ConvertToRawDataset(std::string const&, std::string const&)':
convert_encoded_to_raw_leveldb.cc:(.text+0x47c): undefined reference to`cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status

**Comment by ghost** [comment]
@n3011 It might be related to this. I had similar error, i edited the BREW files and opencv third party file .
And the error was fixed. 
http://stackoverflow.com/questions/27890137/undefined-symbols-for-architecture-x86-64-for-caffe-build

I am still testing it, if it builds correctly but you need to add following library along with other opencv targets

cc_thirdparty_target(
  name="opencv_imgcodecs",
  srcs=["BREW"],
  commands=[],
  cc_obj_files=["-lopencv_imgcodecs"],
)

**Comment by Yangqing** [comment]
Thanks - let's discuss in the other issue #24 ? Closing this one.
