### ISSUE TITLE
GPU support test failed

### ISSUE THREAD

**Issue by zagwin** [facebookarchive/caffe2#1911]
### System information
* Operating system: Ubuntu 14
* Compiler version: 4.8.5
* CMake version: 2.8
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): cuda 8, cudnn 5.1

I usually use Caffe for long time, and I want to change to Caffe2 and have a try. I built the source, and success with
python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"

But when I test GPU support with python -m caffe2.python.operator_test.relu_op_test, it failed
Did I miss some packages, or some specially setting?
```
******** Summary ********
E0207 15:44:39.403973 22403 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0207 15:44:39.403993 22403 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0207 15:44:39.403998 22403 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.], dtype=float32), gc=, dc=[, device_type: 1], engine=u'')
*** Error in `python': munmap_chunk(): invalid pointer: 0x00007ffcf8801c10 ***
*** Aborted at 1518047079 (unix time) try "date -d @1518047079" if you are using GNU date ***
PC: @     0x7fac0482ec37 (unknown)
*** SIGABRT (@0x3e800005783) received by PID 22403 (TID 0x7fac04fdc740) from PID 22403; stack trace: ***
    @     0x7fac04bd1330 (unknown)
    @     0x7fac0482ec37 (unknown)
    @     0x7fac04832028 (unknown)
    @     0x7fac0486b2a4 (unknown)
    @     0x7fac04876007 (unknown)
    @     0x7fabe1327fd1 caffe2::enforce_detail::EnforceFailMessage::get_message_and_free()
    @     0x7fabe0485cb2 caffe2::Caffe2InitializeCuda()
    @     0x7fabe048b874 caffe2::(anonymous namespace)::Caffe2CudaInitializerHelper::Caffe2CudaInitializerHelper()
    @     0x7fabe0486dd3 caffe2::CUDAContext::CUDAContext()
    @     0x7fabe1c61363 caffe2::python::TensorFeeder<>::FeedTensor()
    @     0x7fabe1c1610f _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKSsNS_6objectES8_E38_bIS7_S8_S8_EINS_4nameENS_5scopeENS_7siblingEA1_cNS_3argESE_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNEST_
    @     0x7fabe1c3a6aa pybind11::cpp_function::dispatcher()
    @           0x4c7f54 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c8314 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c8314 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c8314 (unknown)
    @           0x4704ea (unknown)
    @           0x4c9aa5 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c9419 (unknown)
    @           0x4704ea (unknown)
    @           0x4c9aa5 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c9419 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c9419 (unknown)
    @           0x4cfedc (unknown)
    @           0x4c8314 (unknown)
    @           0x4cfedc (unknown)
Aborted (core dumped)
```

**Comment by pjh5** [comment]
Could you run `nvidia-smi` and give us more info about your GPU?

**Comment by pjh5** [comment]
If you try to import caffe2.python.core and get the following warning then Caffe2 is not using GPU. If there are no warnings then it should be using GPU.
`
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named 'caffe2.python.caffe2_pybind11_state_gpu'
`

**Comment by zagwin** [comment]
I confirmed these points:
1. from caffe2.python import core  without any warning, it seems I built caffe2 with gpu
2. the mnist tutorial use CPU mode by default, NO gpu usage when I train the model
3. when I added "model.param_init_net.RunAllOnGPU()  model.net.RunAllOnGPU()" to the tutorial code, to switch it to GPU mode as suggested [#374](https://github.com/caffe2/caffe2/issues/374) I got the same error

---------------
** Error in `/usr/bin/python': munmap_chunk(): invalid pointer: 0x00007ffc0c178c40 ***
*** Aborted at 1518057693 (unix time) try "date -d @1518057693" if you are using GNU date ***
PC: @     0x7f86e7dc4c37 (unknown)
*** SIGABRT (@0x3e80000622a) received by PID 25130 (TID 0x7f86e8572740) from PID 25130; stack trace: ***
    @     0x7f86e8167330 (unknown)
    @     0x7f86e7dc4c37 (unknown)
    @     0x7f86e7dc8028 (unknown)
    @     0x7f86e7e012a4 (unknown)
    @     0x7f86e7e0c007 (unknown)
    @     0x7f86a1236fd1 caffe2::enforce_detail::EnforceFailMessage::get_message_and_free()
    @     0x7f86a0394cb2 caffe2::Caffe2InitializeCuda()
    @     0x7f86a039a874 caffe2::(anonymous namespace)::Caffe2CudaInitializerHelper::Caffe2CudaInitializerHelper()
    @     0x7f86a0395dd3 caffe2::CUDAContext::CUDAContext()
    @     0x7f86a02da5bb caffe2::CreateDBOp<>::CreateDBOp()
    @     0x7f86a02daf9e caffe2::Registerer<>::DefaultCreator<>()
    @     0x7f86a123573f std::_Function_handler<>::_M_invoke()
    @     0x7f86a12d4573 caffe2::(anonymous namespace)::TryCreateOperator()
    @     0x7f86a12d5a79 caffe2::CreateOperator()
    @     0x7f86a12d15b0 caffe2::SimpleNet::SimpleNet()
    @     0x7f86a128c274 caffe2::CreateNet()
    @     0x7f86a128c9da caffe2::CreateNet()
    @     0x7f86a12c7baa caffe2::Workspace::RunNetOnce()
    @     0x7f86a1b26579 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE28_bIS8_EINS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESQ_
    @     0x7f86a1b496aa pybind11::cpp_function::dispatcher()

**Comment by pjh5** [comment]
I think that something about your particular configuration (Ubuntu 14 + CUDA 8 + cuDNN5.1) must be responsible for this. Is it possible for you to upgrade your CUDA and/or cuDNN versions to CUDA 9 or cuDNN 7? If you upgraded your Ubuntu to 16.04 that'd be even better. These versions are better tested by us.

Though I notice the problem comes from pybind. Can you give your c++, python, and pybind versions too?

**Comment by zagwin** [comment]
Thanks very much! I also thought about this, However, because it is a server, and many of our team members use it for caffe, I cannot upgrade Ubuntu. But I can try cuDNN higher version later.

this is the caffe2 Cmake summary

-- ******** Summary ********
-- General:
--   CMake version         : 2.8.12.2
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1059-g6ade370-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.5
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   :
--
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.6
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 5.1.10
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               :
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.8
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF

**Comment by zagwin** [comment]
Thanks very much! I also thought about this, However, because it is a server, and many of our team members use it for caffe, I cannot upgrade Ubuntu. But I can try cuDNN higher version later.

Sorry, how can I check pybind version? I googled, but did not found it

this is the caffe2 Cmake summary

-- ******** Summary ********
-- General:
-- CMake version : 2.8.12.2
-- CMake command : /usr/bin/cmake
-- Git version : v0.8.1-1059-g6ade370-dirty
-- System : Linux
-- C++ compiler : /usr/bin/c++
-- C++ compiler version : 4.8.5
-- Protobuf compiler : /usr/bin/protoc
-- Protobuf include path : /usr/include
-- Protobuf libraries : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
-- CXX flags : -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
-- Build type : Release
-- Compile definitions :
-- BUILD_BINARY : ON
-- BUILD_DOCS : OFF
-- BUILD_PYTHON : ON
-- Python version : 2.7.6
-- Python library : /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- BUILD_SHARED_LIBS : ON
-- BUILD_TEST : ON
-- USE_ATEN : OFF
-- USE_ASAN : OFF
-- USE_CUDA : ON
-- CUDA version : 8.0
-- CuDNN version : 5.1.10
-- CUDA root directory : /usr/local/cuda
-- CUDA library : /usr/lib/x86_64-linux-gnu/libcuda.so
-- CUDA NVRTC library : /usr/local/cuda/lib64/libnvrtc.so
-- CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
-- CUDA include path : /usr/local/cuda/include
-- NVCC executable : /usr/local/cuda/bin/nvcc
-- CUDA host compiler : /usr/bin/cc
-- USE_EIGEN_FOR_BLAS : 1
-- USE_FFMPEG : OFF
-- USE_GFLAGS : ON
-- USE_GLOG : ON
-- USE_GLOO : ON
-- USE_LEVELDB : ON
-- LevelDB version : 1.15
-- Snappy version : 1.1.0
-- USE_LITE_PROTO : OFF
-- USE_LMDB : ON
-- LMDB version : 0.9.10
-- USE_METAL : OFF
-- USE_MKL :
-- USE_MOBILE_OPENGL : OFF
-- USE_MPI : ON
-- USE_NCCL : ON
-- USE_NERVANA_GPU : OFF
-- USE_NNPACK : ON
-- USE_OBSERVERS : ON
-- USE_OPENCV : ON
-- OpenCV version : 2.4.8
-- USE_OPENMP : OFF
-- USE_PROF : OFF
-- USE_REDIS : OFF
-- USE_ROCKSDB : OFF
-- USE_THREADS : ON
-- USE_ZMQ : OFF

**Comment by zagwin** [comment]
Thanks @pjh5 , it works good now after I upgrade c++ to 5.4
