### ISSUE TITLE
Tutorial recommends installing nonexistent python packages

### ISSUE THREAD

**Issue by durka** [facebookarchive/caffe2#1914]
I'm using Python 2.7 on Ubuntu 16.04 and installing from source (no Anaconda).

The [tutorials introduction](https://caffe2.ai/docs/tutorials.html#tutorials-installation) has a list of Python packages to install, but two of them (`unzip` and `zeromq`) don't exist.

I don't know what `unzip` is supposed to refer to. Maybe `zeromq` should be [`pyzmq`](https://pypi.python.org/pypi/pyzmq)?

The rest of the packages installed without issues and the basic examples at least seem to run OK. Should these two packages simply be taken out of the instructions?

**Comment by pjh5** [comment]
Thanks for pointing this out. We'll fix this soon. These packages are using in some tutorials; it might just be one tutorial, but I forget which one. You won't need this unless you get an import error complaining that one of them isn't found.

**Comment by pjh5** [comment]
This should be fixed now.

**Comment by durka** [comment]
As a newcomer, the note that's in the tutorial now...

```
# These aren't in pip. Try to install them with another package manager
# unzip
# zeromq
```

...is equally unhelpful. It doesn't give me any idea of which tutorial need those or what I might be looking for in "another package manager". I'd keep this open hoping for a better fix if I were you.

**Comment by pjh5** [comment]
@durka This was changed shortly after the first update.

**Comment by durka** [comment]
Great, looks much better now!
