### ISSUE TITLE
How can i import weights parameters from numpy array ?

### ISSUE THREAD

**Issue by leeys888** [facebookarchive/caffe2#1922]
Hello.
I have pre-trained model with tensorflow. **I want to convert it to a caffe2 model.**
So, i try to extract a weights of tensorflow model with numpy for each layer.

_ex) tensorflow conv1 weight (shape = 3x3x16x32 ) --> numpy array (3x3x16x32)_

and then,  I want to  import the numpy array as the weight value of each layer of caffe2.

_ex) numpy array (3x3x16x32) --> caffe2 conv1 layer weights_

I want get your advice.
Thank you.

**Comment by jimmyoic** [comment]
1) draw your net (predict_net) by the caffe2 API, such as cnnModel or brew. You can find plenty of examples in the caffe2 tutorial.

2) create your own init_net according your pre-trained weight. To do so, you can create the operator used to fill your weight into the workspace by the blob name:

`init_net = caffe2_pb2.NetDef()`

create ops to fill weights for all layers:

`op = core.CreateOperator("GivenTensorFill", [], [param],arg=[ utils.MakeArgument("shape", workspace.FetchBlob(param).shape),utils.MakeArgument("values", workspace.FetchBlob(param))])`

where param is the name of your blob (this should be done for all layers of your pre-trained net), and arg indicates the shape and the values you want to fill. In your case, the param is "conv1", and the shape should be 3x3x16x32.

If you want to save weights into init_net.pb, try:

`with open(outputFileName+'_init_net.pb', 'wb') as f:`
`   f.write(init_net.SerializeToString())`

Similarly, save your predict_net.pb as well.

**Comment by leeys888** [comment]
Thank you. i  solved it.
