### ISSUE TITLE
Conda build faild

### ISSUE THREAD

**Issue by zeshaoaaa** [facebookarchive/caffe2#1924]
When I typed "conda build conda" on terminal trying to install caffe2, following information will occur.  I've tried every solution I found on Google and Github, how can I fix that? Thanks in advance.

If my description is not clear enough, please tell me.

### System information

* Operating system: OS X 10.12
* CMake version: 3.10.2
* Relevant libraries/versions (e.g. CUDA): CUDA 9.0

### CMake summary output
-- Configuring incomplete, errors occurred!
See also "/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518185545421/work/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518185545421/work/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/jay/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1122, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 676, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 672, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/jay/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518185545421/work/conda_build.sh']' returned non-zero exit status 1.
```
******** Summary ********

[CMakeOutput.log](https://github.com/caffe2/caffe2/files/1711314/CMakeOutput.log)
[CMakeError.log](https://github.com/caffe2/caffe2/files/1711315/CMakeError.log)

```

**Comment by pjh5** [comment]
Sorry I forgot to update the documentation around this.

On the most recent code your conda directory should be split into a cuda folder and a no_cuda folder. If you want to use conda-build with cuda then the correct command is 
`conda build conda/cuda`

The error you posted is conda-build failing because the underlying cmake failed. Can you post the cmake error instead? Posting all of the cmake output will help me see what's wrong.

**Comment by zeshaoaaa** [comment]
@pjh5 

When I trying to build caffe2 use "conda build conda/cuda", following error information will occur.
If there is missing the file you need, please tell me the filename.

=======================================================================

-- OpenCV found (/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/OpenCV)
-- Found system Eigen at /usr/local/include/eigen3
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "3.6.4", minimum required is "2.7") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
CMake Error at /Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION)
Call Stack (most recent call first):
  /Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindNumPy.cmake:50 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:258 (find_package)
  CMakeLists.txt:88 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/work/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/work/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/jay/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1122, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 676, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/Users/jay/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 672, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/Users/jay/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/jay/anaconda3/conda-bld/caffe2-cuda_1518227062021/work/conda_build.sh']' returned non-zero exit status 1.

=======================================================================

[CMakeOutput.log](https://github.com/caffe2/caffe2/files/1712893/CMakeOutput.log)
[CMakeError.log](https://github.com/caffe2/caffe2/files/1712894/CMakeError.log)

**Comment by pjh5** [comment]
@zeshaoaaa is your caffe2/conda/meta.yaml file the same as https://github.com/caffe2/caffe2/blob/master/conda/cuda/meta.yaml ?

These two lines of output look very very strange to me
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7")
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "3.6.4", minimum required is "2.7")
Since you're using Anaconda, conda should definitely pick up it's own version of python before the system version. I'm guessing that this error is directly caused by numpy not being installed for your system python, though it really shouldn't be using system python in the first place. Do you have any specific conda configurations in place? Does `which python` return a path into Anaconda? Is Anaconda's bin directory (e.g. ~/anaconda2/bin on my machine) on your PATH ?

**Comment by terry2tan** [comment]
I have the same problem.
os: ubuntu 16.04
python: 2.7
cuda: 8.0
cudnn: 7.0

**Comment by pjh5** [comment]
@terry2tan what is the error that you're getting?

**Comment by qk-huang** [comment]
so anyone can tell me how to slove this problem?

**Comment by pjh5** [comment]
@Ken-Con what instructions did you run and what error are you getting?
