### ISSUE TITLE
Dectectron error == cudaSuccess. 2 vs 0. Error at: /root/caffe2/caffe2/core/context_gpu.cu:343

### ISSUE THREAD

**Issue by OlivierOR** [facebookarchive/caffe2#1936]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Ubuntu 16.04.3 LTS
* Compiler version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
* CMake version: cmake version 3.5.1
* CMake arguments: "cmake .." was launched in the build directory.
* Relevant libraries/versions (e.g. CUDA): - Cuda compilation tools, release 9.1, V9.1.85
- cudnn-9.1-linux-x64-v7

### CMake summary output

```
******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1074-g6734eb8
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   CXX flags             :  -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 9.1
--     CuDNN version       : 7.0.5
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.9.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /root/caffe2/build
```
### nvidia-smi output

```
nvidia-smi 
Sat Feb 10 12:22:32 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.12                 Driver Version: 390.12                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 650M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   31C    P8    N/A /  N/A |    195MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

```
Hello, after i have installed Detectron, i tried to launch it with this command : 

python tools/infer_simple.py \
--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
--output-dir demo/output \
--image-ext jpg \
--wts \
model_final.pkl \
demo

but i got this error after : 

E0210 12:19:55.705307 19120 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  57: Loading weights from: model_final.pkl
I0210 12:19:57.652631 19120 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000218138 secs
I0210 12:19:57.652958 19120 net_dag.cc:61] Number of parallel execution chains 63 Number of operators = 402
I0210 12:19:57.682595 19120 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000187826 secs
I0210 12:19:57.682878 19120 net_dag.cc:61] Number of parallel execution chains 30 Number of operators = 358
I0210 12:19:57.685269 19120 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.5849e-05 secs
I0210 12:19:57.685303 19120 net_dag.cc:61] Number of parallel execution chains 5 Number of operators = 18
INFO infer_simple.py: 110: Processing demo/people-ashley-et-mary-kate-olsen-2407215_3008.jpg -> demo/output/people-ashley-et-mary-kate-olsen-2407215_3008.jpg.pdf
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /root/caffe2/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res4_16_branch2a" input: "gpu_0/res4_16_branch2b_w" output: "gpu_0/res4_16_branch2b" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1518261598 (unix time) try "date -d @1518261598" if you are using GNU date ***
PC: @     0x7fcad3129428 gsignal
*** SIGABRT (@0x4ab0) received by PID 19120 (TID 0x7fca667fc700) from PID 19120; stack trace: ***
    @     0x7fcad31294b0 (unknown)
    @     0x7fcad3129428 gsignal
    @     0x7fcad312b02a abort
    @     0x7fcacc6e184d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fcacc6df6b6 (unknown)
    @     0x7fcacc6df701 std::terminate()
    @     0x7fcacc70ad38 (unknown)
    @     0x7fcad34c56ba start_thread
    @     0x7fcad31fb41d clone
    @                0x0 (unknown)
Aborted (core dumped)

I have difficulties to understand what might goes wrong at this final point despite everything before went well : installation of nvidia-driver, cuda 9.1, Cudnn libraries, caffe2 compilation. (Following your documentation to install caffe2 on Ubuntu 16.04)

Thanks for your help, 

regards.

NB: The error occurred also with option(USE_NATIVE_ARCH “Use -march=native” ON) and caffe2 CMakefile.

**Comment by orionr** [comment]
Hi @OlivierOR - looks like you are getting an out of memory. It looks like you are on a GT 650M, which likely doesn't have enough memory to run these models. There is some work being done on reducing memory usage in Detectron, but I'm not sure when that will land. I'd recommend using a desktop GPU (or AWS instance) if you have access to one.

**Comment by OlivierOR** [comment]
Hi @orionr, yes it is ! It is an out of memory error. Thank you very much for your lights.
I tried to kill lightgdm and any tty that which hold memory onto the card. 
I could get free of all memory use on the GT 650 M, so 1999 MB free to use for Detectron. But yet i ran out of memomry while i could cheked it grow quickly with nvidia-smi -L command.

Isn't it possible to reduce the memory use in the source code ? (But i dont know where) Or make it with CUDA support ? 
Or may be i can create my own model (I am new to Dectectron and AI) that will be able to use the capacity of my laptop memory card.

I think many people would be glad to be able to use Detectron with any Geforce which allow 3.0 compute and have 2GO of memory.

**Comment by orionr** [comment]
There is some work on creating lower memory models (SqueezeNet, ShuffleNet, and MobileNet are examples), but that's just focused on the inference / prediction time rather than training. In fact, all of the Detectron models should run quickly when you're just running it for inference - it's the training that's expensive.

Training these models require (at a minimum) a GTX 1080 card or higher with 8 GB+ memory, which you'd need to use a desktop for.

Some ideas on how to create your own box are at

https://www.oreilly.com/learning/build-a-super-fast-deep-learning-machine-for-under-1000
https://towardsdatascience.com/build-a-deep-learning-rig-for-800-4434e21a424f
http://www.dk-lab.com/budget-friendly-deep-learning-home-pc/

Also, this is using CUDA, so you're basically doing most of the optimizations you can at that point. Amazon EC2 can give you a machine that can train these models and be pretty reasonable from a price standpoint if you only bring it up when you need it.

Also, if you want to check out some of the pre-trained models, go over to our model zoo at https://github.com/caffe2/models

I'm going to close this, since there's not much more we can do, but hopefully you find a machine you can use. Good luck!

**Comment by OlivierOR** [comment]
Hi @orionr, thank you very much, im very grateful for your help !

**Comment by sdalxn** [comment]
@orionr I have met the same question. But I use a desktop computer.
I use Dell precision Tower 5810, 32G memory. The GPU is Titan X pascal.
My custom dataset about 1000 images whose resolution is 2448*3264.
My model configs with file "Detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml". But only one GPU.

Do you think I need extend my memory size to 64G or more large?

**Comment by sdalxn** [comment]
@orionr I have met the same question when I train my own dataset.
But My computer is a desktop one and its GPU is Titan X pascal. It has 32 G memory also.
My custom dataset has about 1000 pictures whose size is 3264 *2448 and I want to train only 650 pictures, test 360 images.

Do you mean I need to extend my memory size to 64G or more large?

**Comment by sdalxn** [comment]
nvidia-smi

Mon Apr  9 17:04:55 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.42                 Driver Version: 390.42                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:03:00.0  On |                  N/A |
| 24%   46C    P2    52W / 250W |    359MiB / 12188MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1520      G   /usr/lib/xorg/Xorg                           231MiB |
|    0      2541      G   compiz                                        49MiB |
|    0      3813      G   ...-token=F249A0E7B34E9F5F2564766E8518DABB    76MiB |
+-----------------------------------------------------------------------------+


Or do you mean the memory size of GPU is smaller?

**Comment by wenhe-jia** [comment]
@orionr I met another cuda problem instead，I tried to train a maskrcnn model with Detectron. The training progress goes well at the begining, but alone with the training continues, the training time for each iter grows progressly, after handreds or thousands of iterations, the training broke down with the cuda error below:

> E0628 19:13:22.730840  3624 net_dag.cc:195] Exception from operator chain starting at '' (type 'Concat'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: unspecified launch failure Error from operator:
> input: "gpu_3/roi_feat_3rd" input: "gpu_3/fc1_3rd_w" input: "gpu_3/fc1_3rd_b" output: "gpu_3/fc1_3rd" name: "" type: "FC" arg { name: "use_cudnn" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "cudnn_exhaustive_search" i: 0 } device_option { device_type: 1 cuda_gpu_id: 3 }
> E0628 19:13:22.730844  3631 net_dag.cc:195] Secondary exception from operator chain starting at '' (type 'WeightedSum'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: unspecified launch failure Error from operator:
> input: "gpu_3/fc1_2nd_w_grad" input: "gpu_3/one" input: "gpu_3/fc1_2nd_w" input: "gpu_3/wd" output: "gpu_3/fc1_2nd_w_grad" name: "" type: "WeightedSum" device_option { device_type: 1 cuda_gpu_id: 3 }
> E0628 19:13:22.730901  3635 net_dag.cc:195] Secondary exception from operator chain starting at '' (type 'Concat'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: unspecified launch failure Error from operator:
> input: "gpu_3/_[mask]_fcn1" output: "gpu_3/_[mask]_fcn1" name: "" type: "Relu" arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 cuda_gpu_id: 3 } engine: "CUDNN"
> F0628 19:13:22.730955  3631 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> F0628 19:13:22.730959  3624 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.730976  3635 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731009  3632 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3636 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3628 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731050  3626 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731067  3630 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731077  3622 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731089  3633 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731108  3634 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731112  3627 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731127  3623 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731139  3637 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3629 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3625 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> F0628 19:13:22.730959  3624 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.730976  3635 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731009  3632 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3636 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3628 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731050  3626 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731067  3630 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731077  3622 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731089  3633 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731108  3634 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731112  3627 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731127  3623 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731139  3637 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3629 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3625 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***
> F0628 19:13:22.730959  3624 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.730976  3635 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731009  3632 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3636 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3628 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731050  3626 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731067  3630 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731077  3622 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731089  3633 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731108  3634 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731112  3627 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731127  3623 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731139  3637 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3629 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3625 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> F0628 19:13:22.730959  3624 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.730976  3635 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731009  3632 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3636 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3628 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731050  3626 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731067  3630 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731077  3622 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731089  3633 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731108  3634 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731112  3627 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731127  3623 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731139  3637 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3629 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3625 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> F0628 19:13:22.730959  3624 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.730976  3635 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731009  3632 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3636 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731016  3628 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731050  3626 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731067  3630 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731077  3622 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731089  3633 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731108  3634 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731112  3627 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731127  3623 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731139  3637 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3629 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 19:13:22.731155  3625 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***

I googled this error, it seems like something about GPU memory leak, but during training time, GPU memory usage are stable and normal until the progress broke down. I tried to reboot my server but it didn't work, can you help me out with this?
I checked the context_gpu.h at line 107, the code is:

```
~ThreadLocalCUDAObjects() noexcept {
 99     for (int i = 0; i < CAFFE2_COMPILE_TIME_MAX_GPUS; ++i) {
100       for (auto& handle : cublas_handles_[i]) {
101         if (handle) {
102           CUBLAS_CHECK(cublasDestroy(handle));
103         }
104       }
105       for (auto& stream : cuda_streams_[i]) {
106         if (stream) {
107           CUDA_CHECK(cudaStreamDestroy(stream));
108         }
109       }
110       for (auto& handle : cudnn_handles_[i]) {
111         if (handle) {
112           CUDNN_CHECK(cudnnDestroy(handle));
113         }
114       }
115     }
116   }
```

I am using Ubuntu14.04, with 4 GTX TITAN XP, cuda-8.0, cudnn-6.0.21.
