### ISSUE TITLE
Compiling error, nvcc fatal

### ISSUE THREAD

**Issue by weipengxumpi** [facebookarchive/caffe2#1937]
Dear all,

I've got a compiling error saying 
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.Release.cmake:203
Thanks in advance for help!

### System information

* Operating system: Linux
* Compiler version: gcc version 4.9.2 (Debian 4.9.2-10)
* CMake version: cmake version 3.6.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): nvcc

### CMake summary output

```
******** Summary ********
 [  0%] Built target pthreadpool
[  1%] Built target nnpack_reference_layers
[  4%] Built target cpuinfo
[  8%] Built target nnpack
[  8%] Built target gtest
[  8%] Built target gtest_main
[ 10%] Built target benchmark
[ 10%] Built target Caffe_PROTO
[ 10%] Built target python_copy_files
[ 11%] Built target Caffe2_PROTO
[ 11%] Built target Caffe2_perfkernels_avx
[ 12%] Built target Caffe2_perfkernels_avx2
[ 50%] Built target caffe2
[ 50%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.Release.cmake:203 (message):
  Error generating
  /bla/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/utils/./caffe2_gpu_generated_math_gpu.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o] Error 1
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:721: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
CMakeFiles/Makefile2:2160: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make: *** [all] Error 2
Makefile:138: recipe for target 'all' failed

```

**Comment by pjh5** [comment]
Can you enable verbose output by passing VERBOSE=1 to your make command? If you are using conda-build, then edit the build.sh to find the make command. Then post your verbose output, which should include the full linking command.

Do you have any spaces in the path to your CUDA installation, or to the nvcc compiler?

**Comment by yinghai** [comment]
This is a known issue. Updating cmake to >=7.0.2 will work around it. Check https://github.com/caffe2/caffe2/tree/master/cmake/Modules_CUDA_fix

**Comment by weipengxumpi** [comment]
@pjh5 @yinghai , thanks for the advice. after a few trails, I managed to compile it with cmake 3.5.1.

Best,
Weipeng

**Comment by wuzhenyujack** [comment]
hello ,my friend,can you tell me how do you solve it ? thank you very much
