### ISSUE TITLE
Library not loaded: libcaffe2.dylib

### ISSUE THREAD

**Issue by jhw6976** [facebookarchive/caffe2#1942]
* Operating system: OSX 10.13.3 (High Sierre)
* Relevant libraries/versions (e.g. CUDA): CUDA=OFF

**when I try to import caffe2** , 
%matplotlib inline
from caffe2.proto import caffe2_pb2
import numpy as np
import skimage.io
import skimage.transform
from matplotlib import pyplot
import os
from caffe2.python import core, workspace, models
import urllib2
print("Required modules imported.")

**Got below error**
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(/Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so, 10): Library not loaded: libcaffe2.dylib
  Referenced from: /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
  Reason: image not found

Note: 
- I compile caffe2 using brew/pip on MacPro. I disabled GPU by -DUSECUBA=OFF
- I always got WARNING message 
        "WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode."
         "WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu"
- I tried ran on caffe2 test without issue, such as "python -m caffe2.python.operator_test.relu_op_test"
- I can see ./lib/libcaffe2.dylib under python virtualenv directory 

Question, do I miss any environment setup when I ran caffe2 under virtualenv?

**Comment by pjh5** [comment]
I'm not sure if you need extra setup for virtualenv. 

Does this path exist? /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so

What is your PYTHONPATH? Is that the same PYTHONPATH in the jupyter notebook? This SO post suggests how to echo your PYTHONPATH while running python https://stackoverflow.com/questions/1489599/how-do-i-find-out-my-python-path-using-python .

**Comment by jhw6976** [comment]
Does this path exist? /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
==> yes, the so is there. by the way "/Users/admin/projects/caffe-virtaulenv" is virtualenv root directory

What is your PYTHONPATH?
==> it points to "/Users/admin/projects/caffe-virtaulenv"

I think the problem is that caffe2_pybind11_state.so can not load libcaffe2.dylib. 
but I can find libcaffe2.dylib under /Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib

**Comment by pjh5** [comment]
Can you run `otool -L` on both /Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib and /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so ?

**Comment by jhw6976** [comment]
here are the information, seems both link to same libs

_otool -L /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so_
/Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so:
	libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/protobuf/lib/libprotobuf.15.dylib (compatibility version 16.0.0, current version 16.1.0)
	/usr/local/opt/gflags/lib/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.1)
	/usr/local/opt/glog/lib/libglog.0.3.5.dylib (compatibility version 0.3.5, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)


__otool -L /Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib_
/Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib:_
	libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/protobuf/lib/libprotobuf.15.dylib (compatibility version 16.0.0, current version 16.1.0)
	/usr/local/opt/gflags/lib/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.1)
	/usr/local/opt/glog/lib/libglog.0.3.5.dylib (compatibility version 0.3.5, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

**Comment by pjh5** [comment]
Can you also run `otool -l` (lowercase L) on those two libraries? 

Your caffe2_pybind11_state.so doesn't appear to know where libcaffe2.dylib is (all the other libraries it links to have absolute paths in the otool output). Can you try setting LD_LIBRARY_PATH to /Users/admin/projects/caffe-virtaulenv/lib/  ?

**Comment by jhw6976** [comment]
- It seems libcaffe2.dylib does not include absolute path in side caffe2_pybind11_state.so. see detail in end of this comment.

Load command 9
          cmd LC_LOAD_DYLIB
      cmdsize 40
         name libcaffe2.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0

- I set up  LD_LIBARAY_PATH then launch the Jupiter notebook, I still faced same error.
echo $LD_LIBRARY_PATH
/Users/admin/projects/caffe-virtaulenv/lib/

++++++++++++++++++++++++++++++++

otool -l /Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib
/Users/admin/projects/caffe-virtaulenv/lib/libcaffe2.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    17       2184 0x00918085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000735000
  fileoff 0
 filesize 7557120
  maxprot 0x00000007
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000002b20
      size 0x0000000000607dfb
    offset 11040
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x000000000060a91c
      size 0x0000000000000702
    offset 6334748
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x000000000060b020
      size 0x0000000000000b64
    offset 6336544
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x000000000060bb84
      size 0x00000000000acab8
    offset 6339460
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000000006b8640
      size 0x0000000000022f00
    offset 7046720
     align 2^6 (64)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000006db540
      size 0x0000000000047d7f
    offset 7189824
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x00000000007232c0
      size 0x0000000000011d2c
    offset 7484096
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 872
  segname __DATA
   vmaddr 0x0000000000735000
   vmsize 0x0000000000038000
  fileoff 7557120
 filesize 180224
  maxprot 0x00000007
 initprot 0x00000003
   nsects 10
    flags 0x0
Section
  sectname __got
   segname __DATA
      addr 0x0000000000735000
      size 0x0000000000004c80
    offset 7557120
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 299 (index into indirect symbol table)
 reserved2 0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x0000000000739c80
      size 0x0000000000000010
    offset 7576704
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 2747 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000000739c90
      size 0x0000000000000958
    offset 7576720
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 2749 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA
      addr 0x000000000073a5e8
      size 0x0000000000000720
    offset 7579112
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x000000000073ad10
      size 0x000000000000c420
    offset 7580944
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000000747130
      size 0x0000000000019b58
    offset 7631152
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __thread_vars
   segname __DATA
      addr 0x0000000000760c88
      size 0x0000000000000030
    offset 7736456
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000013
 reserved1 0
 reserved2 0
Section
  sectname __thread_bss
   segname __DATA
      addr 0x0000000000760cb8
      size 0x0000000000000019
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000012
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000000760ce0
      size 0x0000000000009778
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x000000000076a460
      size 0x0000000000002880
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x000000000076d000
   vmsize 0x00000000002e7000
  fileoff 7737344
 filesize 3041488
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 40
         name libcaffe2.dylib (offset 24)
   time stamp 1 Wed Dec 31 19:00:01 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 7737344
    rebase_size 5752
       bind_off 7743096
      bind_size 6968
  weak_bind_off 7750064
 weak_bind_size 337712
  lazy_bind_off 8087776
 lazy_bind_size 16296
     export_off 8104072
    export_size 348056
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 8469328
   nsyms 26457
  stroff 8904832
 strsize 1874000
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 18131
     iextdefsym 18131
     nextdefsym 7936
      iundefsym 26067
      nundefsym 390
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 8892640
  nindirectsyms 3048
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid F78D94B0-4EA7-3A91-BC45-6DC5C909A9FB
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 10.13
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /usr/local/opt/protobuf/lib/libprotobuf.15.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 16.1.0
compatibility version 16.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/opt/gflags/lib/libgflags.2.2.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 2.2.1
compatibility version 2.2.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/opt/glog/lib/libglog.0.3.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.3.5
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 400.9.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 1252.0.0
compatibility version 1.0.0
Load command 15
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 8452128
 datasize 16448
Load command 16
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 8468576
 datasize 752

otool -l /Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
/Users/admin/projects/caffe-virtaulenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           8    17       2024 0x00018085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000095000
  fileoff 0
 filesize 610304
  maxprot 0x00000007
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000000000026b0
      size 0x00000000000735a0
    offset 9904
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000000075c50
      size 0x0000000000000744
    offset 482384
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000000076394
      size 0x0000000000000c04
    offset 484244
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x0000000000076f98
      size 0x0000000000015e2c
    offset 487320
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000000008cdd0
      size 0x0000000000002700
    offset 576976
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x000000000008f4d0
      size 0x00000000000038c9
    offset 586960
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000000092d9c
      size 0x0000000000002260
    offset 601500
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 712
  segname __DATA
   vmaddr 0x0000000000095000
   vmsize 0x0000000000003000
  fileoff 610304
 filesize 12288
  maxprot 0x00000007
 initprot 0x00000003
   nsects 8
    flags 0x0
Section
  sectname __got
   segname __DATA
      addr 0x0000000000095000
      size 0x00000000000002b0
    offset 610304
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 310 (index into indirect symbol table)
 reserved2 0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x00000000000952b0
      size 0x0000000000000010
    offset 610992
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 396 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000000000952c0
      size 0x00000000000009b0
    offset 611008
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 398 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA
      addr 0x0000000000095c70
      size 0x0000000000000008
    offset 613488
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x0000000000095c80
      size 0x00000000000003f0
    offset 613504
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000000096070
      size 0x0000000000001908
    offset 614512
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x0000000000097978
      size 0x0000000000000008
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000000097980
      size 0x0000000000000280
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000098000
   vmsize 0x0000000000048000
  fileoff 622592
 filesize 294520
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 622592
    rebase_size 376
       bind_off 622968
      bind_size 5016
  weak_bind_off 627984
 weak_bind_size 920
  lazy_bind_off 628904
 lazy_bind_size 15368
     export_off 644272
    export_size 632
Load command 4
     cmd LC_SYMTAB
 cmdsize 24
  symoff 646880
   nsyms 2544
  stroff 690416
 strsize 226696
Load command 5
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 2113
     iextdefsym 2113
     nextdefsym 12
      iundefsym 2125
      nundefsym 419
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 687584
  nindirectsyms 708
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 6
     cmd LC_UUID
 cmdsize 24
    uuid 219A6BD8-C093-354D-81EF-44EEB49F59D5
Load command 7
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 10.13
Load command 8
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 9
          cmd LC_LOAD_DYLIB
      cmdsize 40
         name libcaffe2.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /usr/local/opt/protobuf/lib/libprotobuf.15.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 16.1.0
compatibility version 16.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/opt/gflags/lib/libgflags.2.2.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 2.2.1
compatibility version 2.2.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/opt/glog/lib/libglog.0.3.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.3.5
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 400.9.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 1252.0.0
compatibility version 1.0.0
Load command 15
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 644904
 datasize 1968
Load command 16
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 646872
 datasize 8

**Comment by jhw6976** [comment]
Thank you Paul giving hints.

I found the solution. instead of set LD_LIBRARY_PATH. I set DYLD_LIBRARY_PATH=~/projects/caffe-virtaulenv/lib/. it work for me now
