### ISSUE TITLE
link error while building android executable

### ISSUE THREAD

**Issue by breadbread1984** [facebookarchive/caffe2#1972]
I build caffe2 static library successfully. But when I link the static library with 
```Bash
-lcaffe2 -lcaffe2_module_test_dynamic -lcpufeatures -lcpuinfo -lprotobuf -lprotobuf-lite -lpthreadpool -lnnpack -lnnpack_reference_layers -lc -ldl -llog -lgnustl_shared
```
I get undefined reference to caffe2::EnforceNotMet::EnforceNotMet(... error. I check symbols provided in libcaffe2.a and find several symbols with the same name. Is there any other arguments necessary for linking against caffe2 static library?

**Comment by orionr** [comment]
@Maratyszcza any thoughts on this one?

**Comment by Maratyszcza** [comment]
Probably a link order problem? @breadbread1984 Did you try to put `-lcaffe2` to the end of the line?

**Comment by breadbread1984** [comment]
thx, I will try it.

**Comment by breadbread1984** [comment]
@Maratyszcza sorry for my late reply. I tried it but it does not work. I still get the following error message.

> run_plan.o: In function `main':
run_plan.cpp:(.text+0x2d4): undefined reference to `caffe2::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, void const*)'
run_plan.cpp:(.text+0x420): undefined reference to `caffe2::Workspace::RunPlan(caffe2::PlanDef const&, std::__ndk1::function<bool (int)>)'
run_plan.o: In function `caffe2::(anonymous namespace)::Caffe2FlagParser_plan::Caffe2FlagParser_plan(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
run_plan.cpp:(.text+0x650): undefined reference to `bool caffe2::Caffe2FlagParser::Parse<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:10: run_plan] Error 1

I compile the library on my laptop with cross compiler and compile my project and link with caffe2 on termux. I can share my compiled caffe2 library and project if you need more information.

**Comment by breadbread1984** [comment]
@Maratyszcza I found the problem was caused by building caffe2 with headers of libgnustl_static.a. But termux builds everything with headers of libc++.a. The difference is that headers of libc++ put everything of stl in a subnamespace called __ndk1. I want to know is it possible to build caffe2 with headers of libc++ rather than ones of libgnustl_static?

**Comment by Maratyszcza** [comment]
Yes, Caffe2 uses toolchain file from Android NDK, and thus supports all options documented [here](https://developer.android.com/ndk/guides/cmake.html). To build with `libc++` STL, use `scripts/build_android.sh -DANDROID_STL=c++_static`.
