### ISSUE TITLE
Build Caffe2 on Windows failed

### ISSUE THREAD

**Issue by zeshaoaaa** [facebookarchive/caffe2#1982]
When I run build_windows.bat, following errors will occur. Is there anyone know how to fix this problem? If there is missing the information you need, or my description is not clear enough, please tell me, thanks in advance.
### System information

* Operating system:Win10
* CMake version:3.10.2
* Compiler version: N/A
* CMake arguments: N/A
* Relevant libraries/versions (e.g. CUDA): CUDA v9.1

### CMake summary output
```
C:\Users\Administrator\Documents\Projects\caffe2\scripts>build_windows.bat
CAFFE2_ROOT=C:\Users\Administrator\Documents\Projects\caffe2\scripts\..
CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
CMAKE_BUILD_TYPE=Release
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
-- Need to define long as a separate typeid.
-- Current compiler supports avx2 extention. Will build perfkernels.
CMake Warning (dev) at cmake/MiscCheck.cmake:108 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Protobuf (missing: Protobuf_DIR)
-- Use custom protobuf build.
-- The BLAS backend of choice:Eigen
CMake Warning at cmake/Dependencies.cmake:260 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


-- Did not find system Eigen. Using third party subdirectory.
-- NumPy ver. 1.14.0 found (include: E:/Programs/Python/Python35/lib/site-packages/numpy/core/include)
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
CMake Warning at cmake/Dependencies.cmake:319 (message):
  Not compiling with MPI.  Suppress this warning with -DUSE_MPI=OFF
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


CMake Warning at cmake/Dependencies.cmake:387 (message):
  If not using cuda, one should not use NCCL either.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


CMake Warning at cmake/Dependencies.cmake:412 (message):
  Gloo can only be used on Linux.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


CMake Warning at cmake/Dependencies.cmake:472 (message):
  mobile opengl is only used in android or ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


CMake Warning at cmake/Dependencies.cmake:492 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)


-- NCCL operators skipped due to no CUDA support
-- CUDA RTC operators skipped due to no CUDA support
-- Excluding image processing operators due to no opencv
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- MPI operators skipped due to no MPI support
-- Include Observer library
CMake Warning (dev) at cmake/Utils.cmake:176 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  cmake/Utils.cmake:193 (caffe_add_whole_archive_flag)
  caffe2/CMakeLists.txt:104 (caffe_add_linker_flag)
This warning is for project developers.  Use -Wno-dev to suppress it.

ERROR Failed to remove indentation from:
"""

      from distutils import sysconfig
      print(sysconfig.get_python_lib(prefix=''))

"""
    Python dedent failed with error code: 系统找不到指定的文件。
CMake Error at cmake/Utils.cmake:320 (message):
   Python dedent failed with error code: 系统找不到指定的文件。
Call Stack (most recent call first):
  cmake/Utils.cmake:343 (dedent)
  caffe2/CMakeLists.txt:193 (pycmd)
```

**Comment by TheCreativeMind** [comment]
I am having the same issue. Did you find a work around yet?

**Comment by onebitbrain** [comment]
I am having the same problem.  I was trying to follow the appveyor build log step by step.  Seems to be related to this recent commit c20584e07c4a75d27f829fd60bf7a3 maybe @Erotemic could tell us what dedent is doing? and if it is necessary?

**Comment by Erotemic** [comment]
The dedent function is a wrapper around python's `textwrap.dedent` function. Dedent simply removes common leading indentation from a block of text. For instance it would transform 

```python
text = '''
    def foo():
        return bar
'''
```

info 

```python
text = '''
def foo():
    return bar
'''
```

I use it with the pycmd utility because it is useful for defining python code within CMake without having to break your current indentation scheme (otherwise you will get indentation errors when you try to run it). 


I'm not sure why it is causing errors. What does 系统找不到指定的文件。 mean? Knowing that would help. 


The above command should be equivalent to running this in bash: 

```bash
echo "

      from distutils import sysconfig
      print(sysconfig.get_python_lib(prefix=''))

" | python -c "import sys; from textwrap import dedent; print(dedent(sys.stdin.read()))"
```

can you do that?

Now that I type it I realize that windows uses cmd.exe, not bash. Perhaps CMake's `execute_process` is not piping the way I expect it to be on windows. Perhaps there is a way to use `INPUT_FILE` instead of `echo` to send standard input to the "python -c ..." command.

**Comment by Erotemic** [comment]
A workaround would be to remove the dedent function and change the pycmd so the entire command is on the same line. Having dedent is a nicety, but if it causes problems it can be removed.


To do this remove the dedent function and change the line `dedent(_dedent_cmd "${cmd}")` in pycmd to `set(_dedent_cmd "${cmd}")`

Then in all instances where pycmd is used change the argument from the multiline string to `from distutils import sysconfig; print(sysconfig.get_python_lib(prefix=''))`.

**Comment by onebitbrain** [comment]
> Now that I type it I realize that windows uses cmd.exe, not bash. Perhaps CMake's execute_process is not piping the way I expect it to be on windows.

Lol, now that you typed that I realized why following appveyor's console output might not work.  And why appveyor doesn't get this error, I think its using PowerShell instead of cmd to build.  Can someone more familiar with appveryor confirm this? (@FeodorFitsner)  Last time I looked into setting up powershell with vcvarsall it was a mess.  Easier to use cmd since that is how Visual Studio ships with dev command prompts and native tools command prompts still using cmd.

**Comment by onebitbrain** [comment]
~~I can confirm this is a cmd error after changing my x64 native tools [shortcut](https://stackoverflow.com/a/28217558) and running build_windows.bat in the resulting powershell environment the dedent error goes away.~~ Nvm, I'm an idiot.  I forgot I modified utils.cmake after I did a git pull the error came back.

**Comment by zeshaoaaa** [comment]
@Erotemic Sorry, I forgot to translate the meaning of "系统找不到指定的文件". It means "System can't find the specified file.

**Comment by LaurentBerger** [comment]
try to use git bash on windows

**Comment by Erotemic** [comment]
@zeshaoaaa So, I actually tested this on my windows box, but I was unable to reproduce the error when running via `cmd.exe`. Do you have python installed? Is python on the path?

What happens if you download this file: 
https://github.com/Erotemic/misc/blob/master/cmake/utils.cmake 

and then run `cmake -P utils.cmake`?

**Comment by zeshaoaaa** [comment]
@Erotemic The problem was disappeared after I reinstalled Windows 10, but there is another new problem occurred. I think I should open a new issue. However, thanks for your help. :)
