### ISSUE TITLE
Ruby API

### ISSUE THREAD

**Issue by arjunmenon** [facebookarchive/caffe2#1983]
Hey
1. Is there a support planned for interfacing with Ruby? It would be good.

2. Can you tell good starting point to to add Ruby support?

**Comment by orionr** [comment]
Hi @arjunmenon. No plan for Ruby support at this point, but you could likely look at wrapping the C++ API. We use pybind11 on the Python side, but ultimately you would need to create an extension like

http://www.rubyinside.com/how-to-create-a-ruby-extension-in-c-in-under-5-minutes-100.html

Another alternative is to run Caffe2 as a service and have your Ruby code contact that service (running in Python), but it depends on what you want to do. Hope that helps.
