### ISSUE TITLE
No handlers could be found for logger "caffe2.python.net_drawer"

### ISSUE THREAD

**Issue by walterwang** [facebookarchive/caffe2#1988]
I am able to build the gpu version and get a success message,  in addition, caffe2 detected the number of gpu that I have :
> python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
>1 

I think I have a build error, because when I run the tests for detectron (mask-rcnn), python2 tests/test_spatial_narrow_as_op.py 

I get this message:
```
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
...
----------------------------------------------------------------------
Ran 3 tests in 0.893s

OK
```

### System information

* Operating system: ubuntu 16.04
* Compiler version: gcc 5.4.0
* Relevant libraries/versions (e.g. CUDA):  CUDA 8.0, cudnn 6.0

**Comment by pjh5** [comment]
@walterwang do you have pydot installed? Try installing it with pip or conda and then trying again
