### ISSUE TITLE
can't create operators implemented in detectron module

### ISSUE THREAD

**Issue by breadbread1984** [facebookarchive/caffe2#1990]
I want to use operators provided in detectron module. I tried UpsampleNearest and got the following error message.

> E0221 11:07:40.414309  1997 operator.cc:130] Cannot find operator schema for UpsampleNearest. Will skip schema checking.
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at operator.cc:190] op. Cannot create operator of type 'UpsampleNearest' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "tensor1" output: "tensor2" type: "UpsampleNearest" arg { name: "scale" f: 2 } device_option { device_type: 1 }

The following code is what I tested.

```Protobuf
name: "test"
network {
name: "network1"
op {
	type: "GivenTensorFill"
	output: "tensor1"
	arg {
		name: "shape"
		ints: 1
		ints: 2
		ints: 3
		ints: 3
	}
	arg {
		name: "values"
		floats: 13
		floats: 22
		floats: 3
		floats: 14
		floats: 53
		floats: 26
		floats: 7
		floats: 38
		floats: 9
		
		floats: 11
		floats: 41
		floats: 15
		floats: 10
		floats: 54
		floats: 22
		floats: 92
		floats: 2
		floats: 8
	}
}
op {
	type: "UpsampleNearest"
	input: "tensor1"
	output: "tensor2"
	arg {
		name: "scale"
		f: 2
	}
}
op {
	type: "Print"
	input: "tensor2"
	arg {
		name: "to_file"
		i: 1
	}
}
device_option {
	device_type: 1
}
}
execution_step {
	network: "network1"
	num_iter: 1
}
```

**Comment by breadbread1984** [comment]
How to enable detectron operators at least in run_plan?

**Comment by orionr** [comment]
Unfortunately, for Detectron, I think you need to use the legacy Caffe2 install process which includes a `build` directory under your Caffe2 checkout. For example, this works for me:

```
cd <caffe2 checkout dir>
mkdir build && cd build
cmake ..
make
export LD_LIBRARY_PATH="<caffe2 checkout dir>/build/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="<caffe2 checkout dir>/build:${PYTHONPATH}"
cd <detectron checkout dir>
python tests/test_spatial_narrow_as_op.py
```
Let me know if that helps.

**Comment by breadbread1984** [comment]
@orionr I installed caffe2 in this way. I program with caffe2 in C++, so I have to install caffe2 this way. I tried to use detectron operators in run_plan and C++. But neither works out. You may try the above code with
```Base
run_plan  --plan  path/to/the/code
```
I think the cmakelist.txt doesn't link the caffe2 toolset properly.

**Comment by breadbread1984** [comment]
I figure it out. detectron operators can be created after execution of the following code.
```C++
LoadModule("","/path/to/libcaffe2_detectron_ops_gpu.so");
```
Hope that it can be added to run_plan.cc to allow the latest operators in run_plan.
