### ISSUE TITLE
setup.py does not install detectron ops

### ISSUE THREAD

**Issue by ddkang** [facebookarchive/caffe2#1999]
When installing in a virtual environment using either `pip install .` or `python setup.py install` the detectron ops are not installed.

**Comment by orionr** [comment]
Unfortunately, for Detectron, I think you need to use the legacy Caffe2 install process which includes a `build` directory under your Caffe2 checkout. For example, this works for me:

```
cd <caffe2 checkout dir>
mkdir build && cd build
cmake ..
make
export LD_LIBRARY_PATH="<caffe2 checkout dir>/build/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="<caffe2 checkout dir>/build:${PYTHONPATH}"
cd <detectron checkout dir>
python tests/test_spatial_narrow_as_op.py
```
Let me know if that helps.

**Comment by ddkang** [comment]
Installing via cmake does solve this problem, but I think it would be much nicer for users to be able to run in a virtual environment.

**Comment by orionr** [comment]
@ddkang completely agreed. Eventually we want to update the Detectron env scripts to make this a non-issue. I've filed an issue up there to track. Thanks.
