### ISSUE TITLE
can't decode byte ....ordinal not in range(128)

### ISSUE THREAD

**Issue by mfranco650** [facebookarchive/caffe2#2001]
I am trying to run the RNN for creating a chatbot (per these instructions: https://caffe2.ai/docs/RNNs-and-LSTM-networks.html ) except I am using my own .txt file that I saved in ascii and every time try to run 
python char_rnn.py --train_data myexample.txt
in my terminal, I get the following error:
____
'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
_____
and then it makes reference to line 255 in char_rnn.py like this:
_____
char_rnn.py(255)GenerateText()
-> text += ch
____

For reference I am using Python 2.7 on a Mac OS.

Any ideas would be very much appreciated. Thank you!

**Comment by Maratyszcza** [comment]
Probably your `myexample.txt` file has non-ASCII symbols (e.g. symbols with accent, caron, umlaut)?

**Comment by mfranco650** [comment]
@Maratyszcza thank you for your answer! I actually just solved the issue by deleting 

" from __future__ import unicode_literals " from char_rnn.py and now it is running!

**Comment by Maratyszcza** [comment]
Glad you found the solution. I'm closing the issue then.
