### ISSUE TITLE
Can't run when built with Debug information

### ISSUE THREAD

**Issue by kampelmuehler** [facebookarchive/caffe2#2023]
When compiling with `-DCMAKE_BUILD_TYPE=Debug`, caffe2 won't run. It works like a charm without Debug flags enabled, and in both cases I got the same PATHs setup.

Builds without any apparent issues.

Trying to import in Python gives:

```
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
CRITICAL:root:Cannot load caffe2.python. Error: No module named caffe2_pybind11_state
```

Also tested with CUDA8.0 and CUDNN5.1 without any success.

Any ideas?

### System information

* Operating system: Ubuntu 16.04
* CMake version: 3.5.1
* CMake arguments: -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.1 -DCUDNN_ROOT_DIR=/usr/local/cuda-9.1 -DCMAKE_BUILD_TYPE=Debug

* Relevant libraries/versions: CUDA 9.1, CUDNN7.1, OpenCV3.4

**Comment by pjh5** [comment]
Going to track this in #2208 instead
