### ISSUE TITLE
Done building project "INSTALL.vcxproj" -- FAILED.

### ISSUE THREAD

**Issue by zeshaoaaa** [facebookarchive/caffe2#2046]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Windows 10
* Compiler version: N/A
* CMake version: 3.10
* CMake arguments: N/A
* Relevant libraries/versions (e.g. CUDA): CUDA 9.0

### CMake summary output
19>------ Build started: Project: speed_benchmark, Configuration: Debug x64 ------
19>Building Custom Rule C:/Users/Administrator/Documents/Projects/caffe2/caffe2/binaries/CMakeLists.txt
19>CMake does not need to re-run because C:/Users/Administrator/Documents/Projects/caffe2/build/caffe2/binaries/CMakeFiles/generate.stamp is up-to-date.
19>Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64
19>Copyright (C) Microsoft Corporation.  All rights reserved.
19>
19>cl /c /IC:\Users\Administrator\Documents\Projects\caffe2\build /IC:\Users\Administrator\Documents\Projects\caffe2 /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\protobuf\src /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\eigen /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\pybind11\include /Zi /W3 /WX- /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"speed_benchmark.dir\Debug\\" /Fd"speed_benchmark.dir\Debug\vc141.pdb" /Gd /TP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4355 /wd4506 /wd4661 /wd4800 /wd4996 /wd4141 /wd4503 /wd4554 /wd4805 /wd4273 /errorReport:prompt  /bigobj /bigobj C:\Users\Administrator\Documents\Projects\caffe2\caffe2\binaries\speed_benchmark.cc
19>
19>speed_benchmark.cc
19>LINK : the 32-bit linker (d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe) failed to do memory mapped file I/O on `C:/Users/Administrator/Documents/Projects/caffe2/build/lib/Debug/caffe2.lib' and is going to restart linking with a 64-bit linker for better throughput
19>LINK : failed to locate a 64-bit linker on %PATH%; continue the current linking
14>make_cifar_db.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\make_cifar_db.exe
20>------ Build started: Project: split_db, Configuration: Debug x64 ------
20>Building Custom Rule C:/Users/Administrator/Documents/Projects/caffe2/caffe2/binaries/CMakeLists.txt
20>CMake does not need to re-run because C:/Users/Administrator/Documents/Projects/caffe2/build/caffe2/binaries/CMakeFiles/generate.stamp is up-to-date.
20>Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64
20>Copyright (C) Microsoft Corporation.  All rights reserved.
20>
20>cl /c /IC:\Users\Administrator\Documents\Projects\caffe2\build /IC:\Users\Administrator\Documents\Projects\caffe2 /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\protobuf\src /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\eigen /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\pybind11\include /Zi /W3 /WX- /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"split_db.dir\Debug\\" /Fd"split_db.dir\Debug\vc141.pdb" /Gd /TP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4355 /wd4506 /wd4661 /wd4800 /wd4996 /wd4141 /wd4503 /wd4554 /wd4805 /wd4273 /errorReport:prompt  /bigobj /bigobj C:\Users\Administrator\Documents\Projects\caffe2\caffe2\binaries\split_db.cc
20>
20>split_db.cc
20>LINK : the 32-bit linker (d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe) failed to do memory mapped file I/O on `C:/Users/Administrator/Documents/Projects/caffe2/build/lib/Debug/caffe2.lib' and is going to restart linking with a 64-bit linker for better throughput
20>LINK : failed to locate a 64-bit linker on %PATH%; continue the current linking
17>print_registered_core_operators.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\print_registered_core_operators.exe
21>------ Build started: Project: tutorial_blob, Configuration: Debug x64 ------
21>Building Custom Rule C:/Users/Administrator/Documents/Projects/caffe2/caffe2/binaries/CMakeLists.txt
21>CMake does not need to re-run because C:/Users/Administrator/Documents/Projects/caffe2/build/caffe2/binaries/CMakeFiles/generate.stamp is up-to-date.
21>Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64
21>Copyright (C) Microsoft Corporation.  All rights reserved.
21>
21>cl /c /IC:\Users\Administrator\Documents\Projects\caffe2\build /IC:\Users\Administrator\Documents\Projects\caffe2 /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\protobuf\src /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\eigen /IC:\Users\Administrator\Documents\Projects\caffe2\third_party\pybind11\include /Zi /W3 /WX- /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"tutorial_blob.dir\Debug\\" /Fd"tutorial_blob.dir\Debug\vc141.pdb" /Gd /TP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4355 /wd4506 /wd4661 /wd4800 /wd4996 /wd4141 /wd4503 /wd4554 /wd4805 /wd4273 /errorReport:prompt  /bigobj /bigobj C:\Users\Administrator\Documents\Projects\caffe2\caffe2\binaries\tutorial_blob.cc
21>
21>tutorial_blob.cc
21>LINK : the 32-bit linker (d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe) failed to do memory mapped file I/O on `C:/Users/Administrator/Documents/Projects/caffe2/build/lib/Debug/caffe2.lib' and is going to restart linking with a 64-bit linker for better throughput
21>LINK : failed to locate a 64-bit linker on %PATH%; continue the current linking
18>run_plan.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\run_plan.exe
19>speed_benchmark.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\speed_benchmark.exe
20>split_db.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\split_db.exe
21>tutorial_blob.vcxproj -> C:\Users\Administrator\Documents\Projects\caffe2\build\bin\Debug\tutorial_blob.exe
22>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
22>Building Custom Rule C:/Users/Administrator/Documents/Projects/caffe2/CMakeLists.txt
22>CMake does not need to re-run because C:/Users/Administrator/Documents/Projects/caffe2/build/CMakeFiles/generate.stamp is up-to-date.
23>------ Build started: Project: INSTALL, Configuration: Debug x64 ------
23>-- Install configuration: "Debug"
23>CMake Error at third_party/protobuf/cmake/cmake_install.cmake:37 (file):
23>  file cannot create directory: C:/Program Files/Caffe2/lib.  Maybe need
23>  administrative privileges.
23>Call Stack (most recent call first):
23>  cmake_install.cmake:37 (include)
23>
23>
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: "D:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
23>d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
23>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 22 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Summary
I am trying to build the 'INSTALL' module with VS2017, but it failed, is there anyone know what happen? If my description is not clear enough, please tell me. Thanks in advance.

**Comment by luca-heltai** [comment]
>-- Install configuration: "Debug"
23>CMake Error at third_party/protobuf/cmake/cmake_install.cmake:37 (file):
23> file cannot create directory: C:/Program Files/Caffe2/lib. Maybe need
23> administrative privileges.

this indicates that you may need to run Visual Studio with administrative privileges. Alternatively, change the installation destination to another, non-system, location.

**Comment by zeshaoaaa** [comment]
@luca-heltai Thanks for your reply. There is no more error after I open VS with administrator privileges. But I didn't found the 'caffe2_pybind11_state.dl' that mentioned in the [doc](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile). Do you know why?

**Comment by luca-heltai** [comment]
no, sorry. I just knew the answer to this question, but I don't use this software myself... :)

**Comment by zeshaoaaa** [comment]
@luca-heltai However, thanks for your help 👍
