### ISSUE TITLE
error while loading shared libraries: libcaffe2.so: cannot enable executable stack 

### ISSUE THREAD

**Issue by samarjeet** [facebookarchive/caffe2#2048]
Hi , I am trying to test with a very simple basic line

``
#include <caffe2/core/init.h>
#include <caffe2/core/net.h>
#include

namespace caffe2 {
void run() {
std::cout << "Hello world\n" ;
Workspace workspace("tmp");
}
}

int main(int argc, char **argv) {
caffe2::run();
}

I compile it with

> g++ -std=c++11 -L/usr/local/lib -v testCaffe2.cpp -lcaffe2

The code compiles but has problem with loading shared libraries at runtime.

> ./a.out: error while loading shared libraries: libcaffe2.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by Maratyszcza** [comment]
I recently fixed this problem in Caffe2. You need to get recent version of Caffe2 and update submodules:
```
cd caffe2
git pull origin master
git submodule update
```

**Comment by samarjeet** [comment]
I should have mentioned that I get this error only on the Ubuntu on Windows10. It runs fine on normal Ubuntu. I had looked at your recent patch and built caffe2 after pulling it in. However, it doesn't solve the issue yet. Thank you so much for looking into it.

**Comment by Maratyszcza** [comment]
@samarjeet Did you try to explicitly disable executable stack in Caffe2 (`execstack --clear-execstack /path/to/libcaffe2.so`)?

**Comment by samarjeet** [comment]
Yes. it solves the issue but gives a libdc1394 error. Seems like the error might be benign for now. Thank you !

**Comment by roggerFigueroaQuintero** [comment]
It seems that the linker can not find these libraries even if they are in the correct folder, ie "/ usr / local / bin". To solve this error I update the "ldconfig":

sudo /sbin/ldconfig -v

This page helped me solve the problem:

https://itsfoss.com/solve-open-shared-object-file-quick-tip/

**Comment by lushihan** [comment]
@roggerFigueroaQuintero Your method works! Thanks a lot!
