### ISSUE TITLE
How to run pretrained resnet50 from the model zoo

### ISSUE THREAD

**Issue by johnbroughton2017** [facebookarchive/caffe2#2052]
Hi all,

I am a bit new to caffe2. I followed this python tutorial on running pretrained models and can make it work with alexnet, squeezenet, etc.:
https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb

But it does not work with the pretrained resnet50 model here:
https://github.com/caffe2/models/tree/master/resnet50

![screenshot from 2018-02-25 10-19-55](https://user-images.githubusercontent.com/36822292/36644901-bae7d492-1a15-11e8-99b1-8c42d39b7994.png)

I looked at its predict_net.pbtxt (below) which is different from alexnet's:
op {
  input: "gpu_0/data"
  input: "gpu_0/conv1_w"
  output: "gpu_0/conv1"
  name: "
  type: "Conv"
  arg {
  ...

If I just change {"data":img} to {"gpu_0/data":img}, another error pops up:
![screenshot from 2018-02-25 10-22-41](https://user-images.githubusercontent.com/36822292/36644918-fafbb44a-1a15-11e8-91b2-5961ddba8998.png)

Can anyone suggest the right way to run this model? Thanks a lot in advance.

-- J

**Comment by SteveCruz** [comment]
Has your input image the correct dimensions? Here you can find the specification:

https://github.com/caffe2/models/blob/master/resnet50/value_info.json

I can reproduce your error when I set my image dimension to 227x227 pixels. When I change the crop dimension to 224x224 pixels, then resnet50 works without errors. 

Can you try to change the dimension (after cropping) to be 224x224 pixels and 3 channels?

**Comment by johnbroughton2017** [comment]
@SteveCruz Absolutely you are right. Thanks a lot.

-- J

**Comment by orionr** [comment]
Thanks @SteveCruz for the assist on this one. Closing.

**Comment by 3DMM-ICME2023** [comment]
@SteveCruz  @orionr 
I can get the right prediction using the squeezenet, but when i deploy resnet50 to predict the label of some images, all of are predicted incorrectly as spotlight, could you please tell me the reason?
BTW, I use  224x224 pixels and 3 channels and change {"data":img} to {"gpu_0/data":img}.
