### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70'

### ISSUE THREAD

**Issue by zy2008cn** [facebookarchive/caffe2#2074]
If this is a build issue, please fill out the template below.

### System information

* Operating system: ubuntu16.04
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):CUDA8.0 CUDA9.1

### CMake summary output

```
******** Summary ********
<please paste summary output here>

CMake Error at gloo_cuda_generated_nccl.cu.o.Release.cmake:218 (message):
  Error generating

```

**Comment by p0wdrdotcom** [comment]
Hi,

You are most probably using a Volta arch GPU.

Ensure you use CUDA 9.1 and cuDNN 7.1.1

**Comment by JackLongKing** [comment]
Cmake program will detect GPU capacity and auto set  compute by default, such as compute_70. To avoid this error, try to modify pytorch/cmake/public/cuda.cmake file.
Modify 285th line
/***************************************************/ 
elseif(${CUDA_ARCH_NAME} STREQUAL "Auto")
    caffe2_detect_installed_gpus(__cuda_arch_bin)
/***************************************************/ 
to 
/***************************************************/ 
elseif(${CUDA_ARCH_NAME} STREQUAL "Auto")
    set(__cuda_arch_bin "60")
/***************************************************/ 
Hope to help you!

**Comment by NIEYALI** [comment]
@JackLongKing I met similar problem 
nvcc fatal   : Unsupported gpu architecture 'compute_75'
System Ubuntu 16, cuda9, cudnn7 and two GPU 2080
I think the cuda.cmake file update, now I couldn't find ant line related to arch_bin. So any ideas?Thanks a lot.

**Comment by pietern** [comment]
Also see pytorch/pytorch#12679. You need CUDA 10 to compile for the Turing GPUs.

**Comment by ou525** [comment]
@NIEYALI How did you solve it?
