### ISSUE TITLE
ubuntu14.04 CMake Error at cmake/External/nccl.cmake:56 (add_dependencies)

### ISSUE THREAD

**Issue by NBJ2017** [facebookarchive/caffe2#2097]
If this is a build issue, please fill out the template below.

### System information

* Operating system:ubuntu14.04
* Compiler version:5.4.1
* CMake version:3.2.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):cuda 8.0 cudnn 5.1.10

### CMake summary output
-- Does not need to define long separately.
-- Turning off deprecation warning due to glog.
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Caffe2: Found protobuf with old-style protobuf targets.
-- Caffe2 protobuf include directory: 
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing:  NNPACK_INCLUDE_DIR NNPACK_LIBRARY PTHREADPOOL_LIBRARY CPUINFO_LIBRARY) 
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /home/irsa/anaconda2/bin/python (found version "2.7.14") 
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- Could NOT find RocksDB (missing:  RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
CMake Warning at cmake/Dependencies.cmake:187 (message):
  Not compiling with RocksDB.  Suppress this warning with -DUSE_ROCKSDB=OFF
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- OpenCV found (/home/irsa/anaconda2/share/OpenCV)
CMake Warning at cmake/Dependencies.cmake:251 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- Did not find system Eigen. Using third party subdirectory.
-- Found PythonInterp: /home/irsa/anaconda2/bin/python (found suitable version "2.7.14", minimum required is "2.7") 
-- NumPy ver. 1.11.3 found (include: /home/irsa/anaconda2/lib/python2.7/site-packages/numpy/core/include)
-- Could NOT find pybind11 (missing:  pybind11_INCLUDE_DIR) 
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI LINK flags path: 
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so/usr/lib/x86_64-linux-gnu/libdl.so/usr/lib/x86_64-linux-gnu/libhwloc.so
CMake Warning at cmake/Dependencies.cmake:305 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- Caffe2: CUDA detected: 8.0
-- Found cuDNN: v5.1.10  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Automatic GPU detection returned 6.1.
-- Added CUDA NVCC flags for: sm_61
-- Could NOT find NCCL (missing:  NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
CMake Error at cmake/External/nccl.cmake:56 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "__caffe2_nccl".

Call Stack (most recent call first):
  cmake/Dependencies.cmake:362 (include)
  CMakeLists.txt:93 (include)

-- Could NOT find CUB (missing:  CUB_INCLUDE_DIR) 
-- Could NOT find Gloo (missing:  Gloo_INCLUDE_DIR Gloo_LIBRARY) 
-- MPI include path: /usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so/usr/lib/x86_64-linux-gnu/libdl.so/usr/lib/x86_64-linux-gnu/libhwloc.so
-- CUDA detected: 8.0
-- Found libcuda: /usr/lib/x86_64-linux-gnu/libcuda.so
-- Found libnvrtc: /usr/local/cuda-8.0/lib64/libnvrtc.so
CMake Warning at cmake/Dependencies.cmake:439 (message):
  mobile opengl is only used in android or ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

CMake Warning at cmake/Dependencies.cmake:524 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- GCC 5.4.1: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- Include Observer library
CMake Error at cmake/public/utils.cmake:4 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "caffe2_library".

Call Stack (most recent call first):
  caffe2/CMakeLists.txt:87 (caffe2_interface_library)

CMake Error at cmake/public/utils.cmake:4 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "caffe2_gpu_library".

Call Stack (most recent call first):
  caffe2/CMakeLists.txt:110 (caffe2_interface_library)
```
******** Summary ********
<please paste summary output here>
```
-- ******** Summary ********
-- General:
--   CMake version         : 3.2.2
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1201-gb30b518
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   Protobuf compiler     : /home/irsa/anaconda2/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 5.1.10
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/gcc-5
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring incomplete, errors occurred!
See also "/home/irsa/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/irsa/caffe2/build/CMakeFiles/CMakeError.log".

**Comment by August2018** [comment]
hi NBJ2017,
I also encountered this issue!!!
Do you solve the issue?

**Comment by pjh5** [comment]
This may be a bug. I am investigating. @Yangqing seems relevant to recent cmake changes.

**Comment by NBJ2017** [comment]
@August2018  
hi, August2018, 
I haven't solved this problem when you reply to me, and you can see agilmor's reply. 
Thank you for your reply.

**Comment by NBJ2017** [comment]
@pjh5 
Thanks for your attention and I will try other solutions before you reply to me again.
Looking forward your deep and clear explanation for this bug.

**Comment by NBJ2017** [comment]
@agilmor 
Thanks for your reply, and I will try to solve it following your solution.

**Comment by NBJ2017** [comment]
@August2018 
You are right! I solve this bug when I install install cmake 3.10.2. Thank you!

**Comment by NBJ2017** [comment]
@August2018 
hi, you can follow the solution from @agilmor , and I think it will be helpful. Thank you!

**Comment by SylviaHolic** [comment]
I have this bug too, whatever Cmake Version I install, this bug always happens

**Comment by NBJ2017** [comment]
@agilmor 
You are right! I solve this bug when I install install cmake 3.10.2. Thank you!
