### ISSUE TITLE
cublasGetStream_v2' is defined in DSO  libcublas.so.8.0 and could not read symbols: Invalid operation

### ISSUE THREAD

**Issue by YIFanH** [facebookarchive/caffe2#2174]
System is centos-7 &  cuda-8.0 & g++ 4.8.4
I cmake successfuly，the flowing make is Error as follows：

usr/bin/ld: CMakeFiles/context_gpu_test.dir/core/context_gpu_test.cc.o: undefined reference to symbol 'cublasGetStream_v2'
/usr/bin/ld: note: 'cublasGetStream_v2' is defined in DSO ***cuda-8.0/lib64/libcublas.so.8.0 so try adding it to the linker command line ***cuda-8.0/lib64/libcublas.so.8.0: could not read symbols: Invalid operation

usr/bin/ld: CMakeFiles/core_overhead_benchmark.dir/core_overhead_benchmark.cc.o: undefined reference to symbol 'cudaEventCreateWithFlags'
/usr/bin/ld: note: 'cudaEventCreateWithFlags' is defined in DSO ***/cuda-8.0/lib64/libcudart.so.8.0 so try adding it to the linker command line ***/cuda-8.0/lib64/libcudart.so.8.0：: could not read symbols: Invalid operation
make: *** [all] Error 2

but with ldd ./lib/libcaffe2_gpu.so, the libcublas.so.8.0 && libcudart.so.8.0 can found.

**Comment by pjh5** [comment]
Sorry for the late reply. Can you run `nm <cudalib> | grep -E '(cublasGetStream|cudaEventCreateWithFlags)'`
where <cudalib> is the full path to libcublas.so.8.0 and libcudart.so.8.0 ? You can find those full paths with `find /usr -name libcublas.so.8.0`

**Comment by YIFanH** [comment]
thanks  for your reply, the question is solved, I modified cuda.cmake file，changed add_liabrary and set_property to the same way; for example: change dd_library(caffe2::cublas INTERFACE IMPORTED) to add_library(caffe2::cublas UNKNOWN IMPORTED)  and  set_property( TARGET caffe2::cublas PROPERTY INTERFACE_LINK_LIBRARIES ${CUDA_CUBLAS_LIBRARIES}) to set_property( TARGET caffe2::cublas PROPERTY IMPORTED_LOCATION ${CUDA_CUBLAS_LIBRARIES});  the precondition is find_library

**Comment by pjh5** [comment]
Thanks for giving your solution. I'll look into this.

**Comment by pjh5** [comment]
@YIFanH I'm not sure why your fix worked. Our code around the cublas targets looks correct to me. If you still have a build of this that fails, could you pass VERBOSE=1 to the make command and give us the output? It will help us repro and root cause this issue
