### ISSUE TITLE
Compilation issue: cuda pow<double, float> undefined

### ISSUE THREAD

**Issue by edubois** [facebookarchive/caffe2#2183]
I'm not able to compile caffe2 v0.8.1 on windows using VS2015, cuda 9.1, cudnn 7.1.

5>D:/_DEV/3rdParties/caffe2/modules/detectron/softmax_focal_loss_op.cu(80): error : calling a __host__ function("pow<double, float> ") from a __global__ function("caffe2::_NV_ANON_NAMESPACE::SoftmaxFocalLossKernel") is not allowed
5>
5>D:/_DEV/3rdParties/caffe2/modules/detectron/softmax_focal_loss_op.cu(80): error : identifier "pow<double, float> " is undefined in device code
5>
5>  2 errors detected in the compilation of "C:/Users/*****/AppData/Local/Temp/tmpxft_0002319c_00000000-10_softmax_focal_loss_op.cpp1.ii".

I changed this line caffe2/modules/detectron/softmax_focal_loss_op.cu +81:
```
      losses[i] =
          -(pow(1.0 - Pdata[idx], gamma) *
          log(max(Pdata[idx], FLT_MIN))) * z;

```
to:
```
      losses[i] =
          -(pow(1.0f - Pdata[idx], gamma) *
          log(max(Pdata[idx], FLT_MIN))) * z;

```
It now compiles fine. Not sure if this is a compilation bug or if it's really intended.

### System information

* Operating system: Windows 
* Compiler version: Visual Studio 2015
* CMake version: 3.10
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): 9.1

**Comment by pjh5** [comment]
@edubois thanks so much for finding this for us. This is indeed a bug. Our windows coverage is pretty spotty right now, so your help is really appreciated.

**Comment by edubois** [comment]
It should also be slightly faster ;D
