### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by filipetrocadoferreira** [facebookarchive/caffe2#2195]
If this is a runtime error

### System information

* Operating system: 17.04
* Compiler version: 5.4.1
* CMake version: 3.7.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):
Cuda 8
Cudnn 6

### CMake summary output

```
******** Summary ********
-- General:
--   CMake version         : 3.7.2
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1194-gd6757e34e
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   Protobuf compiler     : 
--   Protobuf include path : 
--   Protobuf libraries    : 
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : 0
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.20
--     Snappy version      : 1.1.4
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.70
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
CMake Warning at CMakeLists.txt:206 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.


-- Configuring done

```

I get this error running Detectron after a while : 

`*** Error in `python': double free or corruption (out): 0x00007fdca6fdbf50 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7fddb161b08b]
/lib/x86_64-linux-gnu/libc.so.6(+0x82c3a)[0x7fddb1624c3a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fddb1628d2c]
/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so(+0x1edef)[0x7fddb05a9def]
/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so(+0x22028)[0x7fddb05ad028]
python(PyEval_EvalFrameEx+0x6232)[0x557cc0874342]
python(PyEval_EvalFrameEx+0x5eef)[0x557cc0873fff]
python(PyEval_EvalCodeEx+0x255)[0x557cc086c8c5]
python(+0x11568e)[0x557cc088968e]
python(PyObject_Call+0x43)[0x557cc085af63]
python(+0x12ba0e)[0x557cc089fa0e]
python(PyObject_Call+0x43)[0x557cc085af63]
python(PyEval_CallObjectWithKeywords+0x30)[0x557cc0878860]
/home/fferreira/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so(+0x76397)[0x7fdd7bd0a397]
/home/fferreira/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so(+0x781d1)[0x7fdd7bd0c1d1]
/home/fferreira/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so(+0x4325b)[0x7fdd7bcd725b]
/home/fferreira/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so(+0x8905a)[0x7fdd7bd1d05a]
/home/fferreira/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so(+0x85745)[0x7fdd7bd19745]
/usr/local/lib/libcaffe2.so(_ZN6caffe26DAGNet5RunAtEiRKSt6vectorIiSaIiEE+0x5a)[0x7fdd77b3abaa]
/usr/local/lib/libcaffe2.so(_ZN6caffe210DAGNetBase14WorkerFunctionEv+0x37c)[0x7fdd77b39f4c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbbc20)[0x7fddac825c20]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76da)[0x7fddb19706da]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x5f)[0x7fddb16aad7f]
`

**Comment by pjh5** [comment]
Can you give the python command you ran that resulted in this error?

**Comment by filipetrocadoferreira** [comment]
Running ./infer from Detectron (multiple times). So the error does not appear from the first call, but after several ones

**Comment by pjh5** [comment]
Did this make any core dumps on your machine that you could upload?

@orionr do you have any ideas here?

**Comment by pjh5** [comment]
This seems like it could be caused by a few things, possibly memory errors, possibly an invalid input of some sort. Regardless, can you ask this on Detectron's issue tracker at https://github.com/facebookresearch/Detectron ? I will close this issue on our side for now. Please reopen if it starts to look like this is a bug on our side.

**Comment by filipetrocadoferreira** [comment]
I run the same code in a 16.04 machine and it does not break. In mine 17.04 it always breaks. The trace is related to caffe2... I will try to post the complete error trace
