### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by bhack** [facebookarchive/caffe2#22]
Do you think that you will go ahead with this after tensorflow release?

**Comment by jyegerlehner** [comment]
I would like to know too. It looks somewhat Tensorflowy.

**Comment by jreniecki** [comment]
I'm also curious...

**Comment by bhack** [comment]
The issue was create after reading this in the readme "I (Yangqing) would also like to personally thank Google, my current employer, to allow me to continue devoting my personal time to work on open-source projects like Caffe." but now @Yangqing is at Facebook so I don't know if this issue still has a sense. Probably could we change the title with Torch?

**Comment by Yangqing** [comment]
@bhack please.

**Comment by bhack** [comment]
It was only a question if make  sense  to contribute in this cause caffe seems quite in MIA and you are the only contributor here.

**Comment by bhack** [comment]
Is it legitimate to ask if you plan to work on this only in your spare time? There will be there others Caffe dev involved?
