### ISSUE TITLE
TensorCPU planar or interleaved?

### ISSUE THREAD

**Issue by edubois** [facebookarchive/caffe2#2206]
Hi,
I'm trying to map boost::gil views pointers into TensorCPU. So let's take an example of an RGB image.
I just wanted to know: are caffe2 tensors defined as planar:
RRRR
RRRR
RRRR
GGGG
GGGG
BBBB
BBBB
BBBB

Or interleaved:
RGBRGBRGBRGB
RGBRGBRGBRGB
RGBRGBRGBRGB

?

I guess it's planar, but just want to be sure.

This is important to know especially for the convolutions.

**Comment by Maratyszcza** [comment]
Caffe2 supports both, we call "planar" format NCHW and "interleaved" format - NHWC. By default, all CNN operators (convolution, deconvolution, pooling, etc) expect NCHW. If you want to work with NHWC, add `order`: `NHWC` argument to CNN operators.

**Comment by edubois** [comment]
Ok, thanks.

Which one is faster in the C++ code? Is there any transpose?

Thanks.
