### ISSUE TITLE
caffe2 debug mode not working

### ISSUE THREAD

**Issue by renganxu** [facebookarchive/caffe2#2208]
If this is a build issue, please fill out the template below.

### System information

* Operating system: RHEL 7.3
* Compiler version:  GCC 4.8.5
* CMake version: 3.10.2
* CMake arguments:  cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_CUDA=ON -DUSE_REDIS=ON -DUSE_GLOO=ON -DUSE_NNPACK=ON -USE_MPI=ON 
* Relevant libraries/versions (e.g. CUDA): 9.0.176

### CMake summary output

```
******** Summary ********
-- General:
--   Git version           : v0.8.1-592-gc261942-dirty
--   System                : Linux
--   C++ compiler          : /bin/c++
--   C++ compiler version  : 4.8.5
--   Protobuf compiler     : /bin/protoc
--   CXX flags             :  -fopenmp -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing
--   Build type            : Debug
--   Compile definitions   :
--
--   BUILD_BINARY          : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.5
--     Python library      : //lib64/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 9.0
--     CuDNN version       : 7.0.1
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.12
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.18
--   USE_METAL             : OFF
--   USE_MKL               :
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.5
--   USE_OPENMP            : ON
--   USE_REDIS             : ON
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/caffe2/build_intelmpi_debug

```
There is no building error, but it has runtime error:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
 WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
 CRITICAL:root:Cannot load caffe2.python. Error: No module named caffe2_pybind11_state
```
This is because the building step added "d" to some shared libraries: libcaffe2.so, libcaffe2_gpu.so, caffe2_pybind11_state.so and caffe2_pybind11_state_gpu.so, so that they become:
```
libcaffe2d.so
libcaffe2_gpud.so
caffe2_pybind11_stated.so
caffe2_pybind11_state_gpud.so
```
So that the runtime cannot find caffe2_pybind11_state.so anymore. How to fix this issue?

**Comment by yinghai** [comment]
You can remove `-DCMAKE_BUILD_TYPE=Debug` in your cmake command. If you want to build debugged version, you can symbolic link `caffe2_pybind11_state.so` to `caffe2_pybind11_stated.so`.

**Comment by kampelmuehler** [comment]
I've got the same issue, duplicate of #2023

**Comment by pjh5** [comment]
I think symlinking the libcaffe2.so -> libcaffe2d.so, caffe2_pybind11_state.so -> caffe2_pybind11_stated.so, etc is a good suggestion. Have you tried that @hfutxrg and @kampelmuehler .

@kampelmuehler I'm going to close your original issue because this one has more comments on it.

**Comment by renganxu** [comment]
Hi @pjh5 and @kampelmuehler, I have tried the symlink and it works. Thanks very much!

**Comment by kampelmuehler** [comment]
Thanks for the hack @yinghai, it seems to be working so far.

Have any of you been able to debug the c++ part of caffe2 in a python implementation?

**Comment by pjh5** [comment]
@kampelmuehler do you mean debugging c++ code? I believe that you would need a c++ debugger rather than a python debugger.

**Comment by kampelmuehler** [comment]
@pjh5 yes I do. I was trying to attach a c++ debugger (CLion) to the local python process (running the python code in pycharm), but it is not stopping at any breakpoints in the c++ code. Do you have suggestions on how to make this work?

**Comment by pjh5** [comment]
@kampelmuehler I do not know how to do this. I suggest you look on SO and other resources, as I'm sure people have asked before. Perhaps http://johntfoster.github.io/posts/debugging-cc%2B%2B-libraries-called-by-python.html will be useful to you. I will close this issue because the original problem has been resolved.
