### ISSUE TITLE
Fine-tune example?

### ISSUE THREAD

**Issue by ilkarman** [facebookarchive/caffe2#2220]
Hi, I am struggling to find an example that will help me do something like this:

I load pre-trained models from [here](https://github.com/leonardvandriel/caffe2_models) and then extract the features from 'pool5' like so:

```
def load_net(INIT_NET, PREDICT_NET, device_opts):
    init_def = caffe2_pb2.NetDef()
    with open(INIT_NET, 'rb') as f:
        init_def.ParseFromString(f.read())
        init_def.device_option.CopyFrom(device_opts)
        workspace.RunNetOnce(init_def.SerializeToString())
    net_def = caffe2_pb2.NetDef()
    with open(PREDICT_NET, 'rb') as f:
        net_def.ParseFromString(f.read())
        net_def.device_option.CopyFrom(device_opts)
        workspace.CreateNet(net_def.SerializeToString(), overwrite=True)
    return net_def.name

def predict_fn(classifier, data, batchsize, device_opts):
    """ Return features from classifier """
    out = np.zeros((len(data), RESNET_FEATURES), np.float32)
    for idx, dta in yield_mb_X(data, batchsize):
        workspace.FeedBlob("data", dta, device_option=device_opts)
        workspace.RunNet(classifier, 1)
        out[idx*batchsize:(idx+1)*batchsize] = workspace.FetchBlob('pool5').squeeze()
    return out
```

However, if I wanted to attach a new FC onto this model to retrain on my own dataset, something like this:

`classifier = brew.fc(resnet50, 'pool5', 'fc1', dim_in=2048, dim_out=MY_CLASSES)`

Where I take pool5 output from the pre-trained model as input to my new dense-layer (which should be randomly initialised) - I'm struggling a bit with the current model format to do that?

Thank you, ilia

**Comment by SteveCruz** [comment]
I found that the following tutorial was very helpful for me to undersand how one could fine-tune the last layer in a pre-trained network (using a single CPU or GPU):

https://nbviewer.jupyter.org/gist/kyamagu/6cff70840c10ca374e069a3a7eb00cb4/dogs-vs-cats.ipynb

This tutorial was not done by me. I found it at #716

**Comment by ilkarman** [comment]
That's perfect, thanks a lot!
