### ISSUE TITLE
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaGetDevice'

### ISSUE THREAD

**Issue by leon532** [facebookarchive/caffe2#2229]
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMallocPitch'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaRuntimeGetVersion'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventDestroy'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMemcpy2D'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaHostAlloc'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `__cudaUnregisterFatBinary'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventCreateWithFlags'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `__cudaRegisterFatBinary'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMemset2D'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaGetLastError'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMemset2DAsync'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMalloc'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `__cudaRegisterVar'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamWaitEvent'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamCreate'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaGetDeviceProperties'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamQuery'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaDriverGetVersion'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventQuery'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaConfigureCall'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamSynchronize'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamAddCallback'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaSetDevice'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaMemGetInfo'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaHostUnregister'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaLaunch'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventElapsedTime'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaGetErrorString'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaStreamDestroy'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventSynchronize'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaGetDeviceCount'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaDeviceReset'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `__cudaRegisterFunction'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaHostGetDevicePointer'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaHostRegister'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaFree'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaEventRecord'
/usr/local/lib/libopencv_core.so.3.2: undefined reference to `cudaSetupArgument'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/run_plan] Error 1
make[1]: *** [binaries/CMakeFiles/run_plan.dir/all] Error 2
make: *** [all] Error 2

**Comment by pjh5** [comment]
@absurdliyang what operating system is this? Are you building with CUDA?

It looks like your opencv version is 3.2 . Where was this installed from (apt-get? conda?)? What is your CUDA version?

**Comment by leon532** [comment]
Thanks. I have found the solution. It is because of lacking .so files of opencv in the /usr/local/lib  @pjh5 .
