### ISSUE TITLE
AttributeError in Caffe_Translator

### ISSUE THREAD

**Issue by ezineo** [facebookarchive/caffe2#224]
Hi,
when I run Caffe_translator.ipynb with the latest master caffe2 to this cell,
```python
# We will first specify the device option: how we want to run the network.
#net.device_option.device_type = caffe2_pb2.CPU
# If you want to use cuda, use the following commands
net.device_option.device_type = caffe2_pb2.CUDA
net.device_option.cuda_gpu_id = 0

# Here we will simply use the Model object to host the model.
model = workspace.Model(net, pretrained_params, ["data"], ["prob"])
print 'Network created sucessfully.'
```
I meet AttributeError:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-813210097dbd> in <module>()
      6 
      7 # Here we will simply use the Model object to host the model.
----> 8 model = workspace.Model(net, pretrained_params, ["data"], ["prob"])
      9 print 'Network created sucessfully.'

AttributeError: 'module' object has no attribute 'Model'
```
Thanks for reply!

**Comment by aaronmarkham** [comment]
The Model function was removed in favor of Predictor (wrapping C++). We're updating the notebook soon to reflect the update. If you want to see Predictor in action and make the adjustment, take a look at [Loading Pre-Trained Models](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb) in code block 4.

Also note that you have another route for translating old Caffe models:

```
python -m caffe2.python.caffe_translator deploy.prototxt pretrained.caffemodel
```

**Comment by aaronmarkham** [comment]
We've removed the translator tutorial in favor of this simple command line approach. If you run into trouble with a converting an old caffemodel with this, then you might have a model using an older version of Caffe model structure which would need to be upgraded first. Check out the binaries in https://github.com/BVLC/caffe/tree/master/tools which can upgrade prototxt files.
