### ISSUE TITLE
A failure to download ~/squeezenet/init_net.pb and predict_net.pb

### ISSUE THREAD

**Issue by miaoshuyu** [facebookarchive/caffe2#2299]
when I do as follows
python -m caffe2.python.models.download squeezenet

There is a error as follow.
C:\Users\miaos>python -m caffe2.python.models.download -i squeezenet
Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [HTTP Error] 404: Not Found.
Cleaning up...

and when i go to download them on S3 .But there is nothing in it and appears an error.
How can i solve it ,Thank you very much.
my platform is VS2017+Cmake3.1+Python3.6+caffe2

**Comment by SteveCruz** [comment]
You could alternatively download the model (and others) manually from:

https://github.com/caffe2/models

**Comment by pjh5** [comment]
@orionr is this where the models are still located?

**Comment by orionr** [comment]
@pjh5 is right - the download location is wrong. Looks like you have an old version of Caffe2 installed?

Compare that to

https://github.com/caffe2/caffe2/blob/master/caffe2/python/models/download.py

which downloads from

https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/predict_net.pb

Please update your version of Caffe2.

**Comment by miaoshuyu** [comment]
@orionr   is right. Looks like i have installed an old version of caffe2 installed. Is there a more convenient way to install caffe2，instead of installing caffe2 from the beginning。

**Comment by pjh5** [comment]
@miaoshuyu what do you mean by "installing caffe2 from the beginning"?

You will always need to update your Caffe2 installation periodically to receive the most recent features and bug fixes. We do not have binary packages available on Windows yet, so you will have to recompile Caffe2 from source whenever you do this.

**Comment by miaoshuyu** [comment]
@pjh5  Thank you for your answer. It solved my problem very well.
