### ISSUE TITLE
No such file or directory: 'gen/caffe2/mpi/mpi_common.h'

### ISSUE THREAD

**Issue by dongb5** [facebookarchive/caffe2#23]
This is the error happened when I typed 'make'. What's the problem?

**Comment by Yangqing** [comment]
Could you send me the complete build log? You can get it via (under Bash)

```
make 2>&1 | tee log.txt
```

**Comment by dongb5** [comment]
Never mind. I reinstalled the dependencies and the problem is solved.

**Comment by Yangqing** [comment]
Thanks - let me know if further problems pop up.
