### ISSUE TITLE
module 'caffe2.python.models.squeezenet' has no attribute 'init_net'

### ISSUE THREAD

**Issue by miaoshuyu** [facebookarchive/caffe2#2301]
After I download  init_net.pb and predict_net.pb of squeezenet and put them into "C:\Program Files\Caffe2\caffe2\python\models\squeezenet".
when I run the code as follow:
![tim 20180318221706](https://user-images.githubusercontent.com/26992220/37566907-56e59bc8-2afa-11e8-99e8-1e147a651128.jpg)
There is an error as pictures.The problem has confused me so long time!
How can I solve it.Thank you very much.

**Comment by yinghai** [comment]
This is not right. Pb files are not python modules. They are serialized protobuf files. You can just load the init_net with
```
from caffe2.proto import caffe2_pb2
init_net = caffe2_pb2.NetDef()
with open('init_net.pb', 'rb') as f:
    init_net.ParseFromString(f.read())
```
Similarly, you can load `predict_net`. 

Btw, how did you come up with your code? Is it in our tutorial?

**Comment by orionr** [comment]
@yinghai is right that the above is the more standard way to load models. However, we do have special syntactic sugar for models downloaded from the model zoo based on @bwasti's code at

https://github.com/caffe2/caffe2/blob/master/caffe2/python/models/__sym_init__.py
https://github.com/caffe2/caffe2/blob/master/caffe2/python/models/download.py

that allows for importing the model directly from python as documented in the model zoo at https://github.com/caffe2/models so the above should have worked. @miaoshuyu maybe try this other approach and see if it works for you?
