### ISSUE TITLE
Link error on macOS

### ISSUE THREAD

**Issue by peastman** [facebookarchive/caffe2#2311]
I'm trying to use the Caffe2 C++ API.  I installed it with conda.  `conda list` shows the installed version as 0.8.dev.  I'm using macOS 10.12.8.

I'm starting with a trivial program that just calls `GlobalInit()`, then cleanly shuts down and exits without doing anything else.  Here is the code.

```C++
#include <caffe2/core/init.h>

int main(int argc, char** argv) {
  caffe2::GlobalInit(&argc, &argv);
  google::protobuf::ShutdownProtobufLibrary();
  return 0;
}
```

I compile and run it like this:

```
$ c++ -I/Users/peastman/miniconda3/include -L/Users/peastman/miniconda3/lib -lcaffe2 -lprotobuf -std=c++11 CaffeTest.cpp
$ export DYLD_LIBRARY_PATH=/Users/peastman/miniconda3/lib
$ ./a.out
```

It fails with this error:

```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/peastman/miniconda3/lib/libjpeg.9.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Abort trap: 6
```

I tried `conda update jpeg` just to make sure I have the latest version.  That didn't make a difference.  Any idea what's wrong?

**Comment by pjh5** [comment]
It looks like it's looking for jpeg version 9 explicitly. What version of jpeg do you have?

Did you install Caffe2 into a brand new conda environment? Or did you install it in an environment that already had opencv installed? 

Can you run `conda list | grep -E '(opencv|jpeg)'`

**Comment by peastman** [comment]
Here's what it shows:

```
jpeg                      9b                   he5867d9_2  
opencv                    3.3.1            py36h60a5f38_1  
```

I didn't specifically install opencv—it's a dependency of caffe2, so it got pulled in automatically.  If I try to remove it, then caffe2 will get removed as well.

```
$ conda remove opencv
Solving environment: done

## Package Plan ##

  environment location: /Users/peastman/miniconda3

  removed specs: 
    - opencv


The following packages will be REMOVED:

    caffe2: 0.8.dev-py36hbf6519f_0 caffe2
    opencv: 3.3.1-py36h60a5f38_1         

Proceed ([y]/n)?
```

**Comment by peastman** [comment]
> Was there anything in your DYLD_LIBRARY_PATH before running these commands?

Nothing.  Opening a new terminal window and typing `printenv DYLD_LIBRARY_PATH` shows nothing.

```
$ otool -L /Users/peastman/miniconda3/lib/libcaffe2.dylib
/Users/peastman/miniconda3/lib/libcaffe2.dylib:
	@rpath/libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.1)
	@rpath/libglog.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/liblmdb.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libleveldb.dylib.1.20 (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsnappy.1.dylib (compatibility version 1.0.0, current version 1.1.7)
	@rpath/libopencv_highgui.3.3.dylib (compatibility version 3.3.0, current version 3.3.1)
	@rpath/libopencv_videoio.3.3.dylib (compatibility version 3.3.0, current version 3.3.1)
	@rpath/libopencv_imgcodecs.3.3.dylib (compatibility version 3.3.0, current version 3.3.1)
	@rpath/libopencv_imgproc.3.3.dylib (compatibility version 3.3.0, current version 3.3.1)
	@rpath/libopencv_core.3.3.dylib (compatibility version 3.3.0, current version 3.3.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

**Comment by peastman** [comment]
After a bit of detective work, I determined that the version of libjpeg it's supposed to be using is the one in `/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/`.  The version installed by conda is overriding it, producing an incompatibility with the system framework.

So I tried

```
export DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:/Users/peastman/miniconda3/lib
```

That leads to another error:

```
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /Users/peastman/miniconda3/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
Abort trap: 6
```

It looks like it's supposed to be using the one in `/usr/lib`, but the conda installed one is overriding it.  Ok, so I tried

```
export DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:/usr/lib:/Users/peastman/miniconda3/lib
```

That fails with

```
dyld: Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Users/peastman/miniconda3/lib/libtiff.5.dylib
  Reason: Incompatible library version: libtiff.5.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6
```

At this point I'm stuck.  liblzma comes from the xz conda package.  I verified that I have the very latest version of both the xz and libtiff packages.  I seem to be stuck in some kind of mess of incompatible libraries, but I don't know why.  Everything is the current versions installed by conda.

**Comment by pjh5** [comment]
Do you know what is trying to use /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO ? 

Can you run `otool -l /Users/peastman/miniconda3/lib/libcaffe2.dylib` (that's a lowercase L) and see what @rpath will evaluate to? There should be some lines in that output that look like
`
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/ (offset 12)` <- what is this value?

It should be @loader_path, just as it is here, which means that libcaffe2.dylib will only look for @rpath/somepackage libraries in the same library folder as libcaffe2.dylib itself, which should be /Users/peastman/miniconda3/lib/ , which should be what you want. 

What is `which python` and `which protoc` ?

My understanding is that all of those @rpaths/ should ignore DYLD_LIBRARY_PATH, but that DYLD_LIBRARY_PATH is used by the linker for all other cases. Can you specify these two flags "-lcaffe2 -lprotobuf" as full paths to their actual locations without modifying DYLD_LIBRARY_PATH and see if that works?

What happens if you don't set DYLD_LIBRARY_PATH at all?

**Comment by peastman** [comment]
> Do you know what is trying to use /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO ?

I'm not sure if this is the only chain that leads to it, but libcaffe2.dylib uses libopencv_videoio.3.3.dylib, which uses the CoreMedia framework, which uses ImageIO.

> There should be some lines in that output that look like
cmd LC_RPATH cmdsize 32 path @loader_path/ (offset 12) <- what is this value?

There's only one occurrence of LC_RPATH in the output:

```
Load command 26
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/ (offset 12)
```

> What is which python and which protoc ?

```
$ which python
/Users/peastman/miniconda3/bin/python
$ which protoc
/Users/peastman/miniconda3/bin/protoc
```

> Can you specify these two flags "-lcaffe2 -lprotobuf" as full paths to their actual locations

How do I do that?  I tried `-l/Users/peastman/miniconda3/lib/libprotobuf/libprotobuf.a`, but that just produces an error message.

> What happens if you don't set DYLD_LIBRARY_PATH at all?

Then I get the error

```
dyld: Library not loaded: @rpath/libcaffe2.dylib
  Referenced from: /Users/peastman/caffe/./a.out
  Reason: image not found
Abort trap: 6
```

**Comment by peastman** [comment]
>  I tried -l/Users/peastman/miniconda3/lib/libprotobuf/libprotobuf.a, but that just produces an error message.

Sorry, that should have been `-l/Users/peastman/miniconda3/lib/libprotobuf.a`.  But ld still reports it couldn't find it.

**Comment by pjh5** [comment]
Does `otool -L a.out` have @rpath/libcaffe2.dylib in it? If so, then can you move it to /Users/peastman/miniconda3/lib/ and try running it there?

**Comment by peastman** [comment]
```
$ otool -L a.out 
a.out:
	@rpath/libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

Moving it to `miniconda3/lib` and running it from there doesn't seem to make any difference.

**Comment by pjh5** [comment]
@peastman when you move it to miniconda3/lib are you running the version in miniconda3/lib ?

`
dyld: Library not loaded: @rpath/libcaffe2.dylib
  Referenced from: /Users/peastman/caffe/./a.out
  Reason: image not found
Abort trap: 6
`

This problem shouldn't happen if a.out is in miniconda3/lib . (And don't have your DYLD_LIBRARY_PATH set to anything)

**Comment by pjh5** [comment]
Wait I see the problem.

`
a.out:
	@rpath/libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2
`

It's looking for protobuf and Caffe2 AND libc++ in the same directory that it is run from. The first two lines `@rpath/libcaffe2.dylib` and `@rpath/libprotobuf.dylib` will only work if `libcaffe2.dylib` and `libprotobuf.dylib` are located in the same directory as a.out . It should not also be looking for libc++ in the same directory.

**Comment by peastman** [comment]
Is there a different option I should be specifying when compiling it?

**Comment by pjh5** [comment]
@peastman did you figure this out?

I don't actually know the answer to this. But if you decide to use cmake, then you _should_ be able to link against Caffe2 easily with a simple ```target_link_libraries(<your_project> caffe2::caffe2)``` and some boilerplate, or something similar.

**Comment by peastman** [comment]
No, I never figured it out.  I'll give cmake a try and get back to you.

**Comment by peastman** [comment]
That did it!  Here's what I ended up with as my CMake script:

```
cmake_minimum_required(VERSION 3.5)
project(CaffeTest)
set(CMAKE_CXX_STANDARD 11)
find_package(caffe2)
add_executable(CaffeTest CaffeTest.cpp)
include_directories(/Users/peastman/miniconda3/include)
target_link_libraries(CaffeTest caffe2)
```

And for reference here's what `otool -L` gives on the executable:

```
CaffeTest:
	@rpath/libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.1)
	@rpath/libglog.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```

Still no idea why invoking `c++` directly didn't work, but now I can move forward.  Thanks so much for your help.  You are awesome!

**Comment by pjh5** [comment]
Glad it's working! You can look through the files that cmake generates to find the linking command that it uses.
