### ISSUE TITLE
caffe2_pybind11_state.so: undefined symbol: _ZN6caffe216TimeObserverBaseINS_12OperatorBaseEE5StartEv

### ISSUE THREAD

**Issue by ateymour** [facebookarchive/caffe2#2337]
Building was successful without any notable issues. However when testing it I get the following error :

```
python
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
CRITICAL:root:Cannot load caffe2.python. Error: /usr/local/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6caffe216TimeObserverBaseINS_12OperatorBaseEE5StartEv
```
I have already checked suggestions at [#1543](https://github.com/caffe2/caffe2/issues/1543),[#197](https://github.com/caffe2/caffe2/issues/197) and [#346](https://github.com/caffe2/caffe2/issues/346) but no luck.  Any help is appreciated.

### System information

* Operating system: Ubuntu 16.04
* python: 2.7.12
* gcc: 5.4.0 

The build is without GPU support, without anaconda, using MKL.

**Comment by pjh5** [comment]
How did you install Caffe2?
Can you give me the output of
`nm -A /usr/local/lib/* 2>/dev/null | grep TimeObserverBase`
