### ISSUE TITLE
undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

### ISSUE THREAD

**Issue by joey3639570** [facebookarchive/caffe2#2347]
I'm using Centos 6.9, gcc 4.8.5, Cuda9.0, Cudnn 7.1.1 NCCL 2.1.0 
I installed my caffe2 through `conda install -c caffe2 caffe2-cuda9.0-cudnn7-gcc4.8`
In python, I encountered a problem as shown below. 
You can see that there is no problem importing caffe2 and caffe2.python.
However, when importing core from caffe2.python, the problem showed up.

Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe2
>>> import caffe2.python
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2_protos.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
CRITICAL:root:Cannot load caffe2.python. Error: /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2_protos.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

I also tried to `ldd` my libcaffe2_protos.so. It showed the message down below.

```
[root@B03 ~]# ldd /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2_protos.so
ldd: warning: you do not have execution permission for `/root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2_protos.so'
	linux-vdso.so.1 =>  (0x00007ffd8f5fd000)
	libprotobuf.so.15 => /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../.././libprotobuf.so.15 (0x00007efea75ac000)
	libstdc++.so.6 => /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../.././libstdc++.so.6 (0x00007efea7271000)
	libgcc_s.so.1 => /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../.././libgcc_s.so.1 (0x00007efea705b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007efea6c7d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efea6a60000)
	libz.so.1 => /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../././libz.so.1 (0x00007efea6849000)
	/lib64/ld-linux-x86-64.so.2 (0x00000035ae200000)
	libm.so.6 => /lib64/libm.so.6 (0x00007efea6546000)

```

**Comment by pjh5** [comment]
The root cause of this is #1980 

You have installed a package that built for gcc 4.8 but your gcc looks like it's 7.2

Can you install caffe2 caffe2-cuda9.0-cudnn7 instead of caffe2 caffe2-cuda9.0-cudnn7-gcc4.8?

EDIT: I notice you said that you have gcc 4.8.5, but your Anaconda thinks you have gcc 7.2 .
```
Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec 7 2017, 17:05:42)
[GCC 7.2.0] on linux2
```
I'm not sure if this is normal. 

Can you give me `conda list protobuf` and then `conda search --info <protobuf>` on the exact version of protobuf you have? e.g. if you have 
```
$ conda list protobuf
# Name                    Version                   Build  Channel
libprotobuf               3.4.1                h326466f_0
protobuf                  3.4.1                    py36_0    conda-forge
```
then run
```conda search --info protobuf=3.4.1=py36_0 -c conda-forge```
You might have to upgrade your conda for that command to work. 

Then can you also run (the last letters are lowercase L)
```nm /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2_protos.so | grep cxx11 | wc -l```
and 
```nm /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../../.././libprotobuf.so.15 | grep cxx11 | wc -l```

**Comment by joey3639570** [comment]
@pjh5 Thanks for your reply. I now using Ubuntu v16.04, and it works well with 
`conda install -c caffe2 caffe2-cuda9.0`
Somehow my Centos computer works well with it too.  Thank you so much for your reply.
