### ISSUE TITLE
cannot load caffe2.python Error:libgflags.so.2.2 :can not open shared object file 

### ISSUE THREAD

**Issue by JiYuanFeng** [facebookarchive/caffe2#2363]
If this is a build issue, please fill out the template below.

### System information

* Operating system:LINUX
* Compiler version:   cuda-9.0 cudnn7.0 via conda enviroment 
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): cuda9.0 cudnn 7.0

### CMake summary output
>>> from caffe2.python import workspace
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libgflags.so.2.2: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: libgflags.so.2.2: cannot open shared object file: No such file or directory

```
******** Summary ********
<please paste summary output here>
locating the libgflags.so
and got the print:
yuanfeng@dlnode08:~/Desktop$ locate libgflags.so
/usr/lib/x86_64-linux-gnu/libgflags.so
/usr/lib/x86_64-linux-gnu/libgflags.so.2
/usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2

so it's the problem of my version of libgflag?

**Comment by JiYuanFeng** [comment]
OK! 
the reason for this problem was caused by the gflags you got from some conda source channel ,which build the package in gcc 5.X ,and you should install the package from the channel based on gcc-7

**Comment by Marcovaldong** [comment]
@JiYuanFeng I got this error, how can i get the package from the channel based on gcc-7?
