### ISSUE TITLE
How to use caffe.lib and caffe_gpu.lib in new visual stidio 2015 project in prediction process?

### ISSUE THREAD

**Issue by syshensyshen** [facebookarchive/caffe2#2369]
* Operating system: windows 7
when i use caffe.lib and caffe_gpu.lib in prediction process, encounter error in caffe2/core/operator.h, erroris: 
         "You might have made a build error: the Caffe2 library does not seem "
        "to be linked with whole-static library option. To do so, use "
        "-Wl,-force_load (clang) or -Wl,--whole-archive (gcc) to link the "
        "Caffe2 library.";

**Comment by yinghai** [comment]
How did you get/generate those libs?

**Comment by syshensyshen** [comment]
@yinghai  visual stidio 2015 build caffe2 generate many static library， including caffe2.lib and caffe2_gpu.lib, also has caffe2_detectron_ops_gpu.dll

**Comment by yinghai** [comment]
You need to whole link the caffe2 libraries in order to register all the operators. In MSVC, check 
https://msdn.microsoft.com/en-us/library/mt732963.aspx
