### ISSUE TITLE
Can I just 'make' and not 'make install'?

### ISSUE THREAD

**Issue by wanderingpj** [facebookarchive/caffe2#2391]
I do not want to change the directory of '/usr/' ,so can I just 'make'? Is there any problem with this?

And I‘ve met the following problem.Is it because of not making install?

![qq 20180323102716](https://user-images.githubusercontent.com/24189081/37808876-b1e4aca4-2e87-11e8-81ee-14f497d0fc21.png)

**Comment by pjh5** [comment]
```make``` compiles and links the Caffe2 libraries. ```make install``` places these libraries into locations where other libraries and Python can find them. Depending on how you built Caffe2, the libraries may expect to find their dependent libraries (such as Protobuf) relative to their own location.

If you want to install into a custom directory, your best chance is to pass CMAKE_INSTALL_PREFIX to your cmake command to where you want to install. You will also probably have to set LD_LIBRARY_PATH and PYTHONPATH if you do this. This answer https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2 may give helpful details on how installation usually works.

**Comment by wanderingpj** [comment]
So I can't just make which may cause some mistakes like the picture shows above. But I can make install to my own directory.@pjh5

**Comment by wanderingpj** [comment]
I've done what you said,but still have the problem:

@pjh5

**Comment by wanderingpj** [comment]
I've done what you said,but still have the problem:
![qq 20180323174428](https://user-images.githubusercontent.com/24189081/37822679-1d58ca4e-2ec2-11e8-876d-f914be78ce25.png)
@pjh5

**Comment by wanderingpj** [comment]
I've done what you said,but still have the problem:
![qq 20180323174809](https://user-images.githubusercontent.com/24189081/37822743-513cf9fc-2ec2-11e8-8225-6c4dba29306b.png)
@pjh5

**Comment by pjh5** [comment]
@wanderingpj what were the commands you used to install? What flags did you pass to cmake? What is the output of cmake?

**Comment by wanderingpj** [comment]
## Commands
 ```jsx
cmake -D CMAKE_INSTALL_PREFIX=/home/pengjing/caffe2_install ..
make install

export PYTHONPATH=/home/pengjing/caffe2_install:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:/home/pengjing/caffe2/build
export LD_LIBRARY_PATH=/home/pengjing/caffe2_install/lib:$LD_LIBRARY_PATH
 ```
## Cmake summary output
 ```jsx
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1388-g858c5fb-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.4
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/libprotobuf.so;debug;/usr/lib/libprotobuf.so;-pthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
--
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.6
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.11
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pengjing/caffe2/build
 ```
@pjh5

**Comment by wanderingpj** [comment]
## Commands
cmake -D CMAKE_INSTALL_PREFIX=/home/pengjing/caffe2_install ..
make install
## Cmake summary output
`-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1388-g858c5fb-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.4
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/libprotobuf.so;debug;/usr/lib/libprotobuf.so;-pthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.6
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib64/stubs/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.11
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pengjing/caffe2/build`

**Comment by pjh5** [comment]
The libcaffe2.so (should be at /home/pengjing/caffe2_install/lib/libcaffe2.so ) needs to be able to find all of its dependencies. Run ```ldd /home/pengjing/caffe2_install/lib/libcaffe2.so``` and make sure that libcaffe2.so can find all of its dependencies. It's probably looking for libraries in the same directory that it is in, in which case you will need to install those libraries alongside libcaffe2 or provide symlinks to their system install locations.

Don't add /home/pengjing/caffe2/build to your PYTHONPATH

**Comment by wanderingpj** [comment]
Thanks very much for your help! I've solved this problem, there's something wrong with the installation of protobuf(symbol_database.py is not involved in google/protobuf). But I still have another problem ：

![qq 20180327104402](https://user-images.githubusercontent.com/24189081/37943801-b53fdc76-31ab-11e8-88fe-4766fe38fced.png)

@pjh5

**Comment by LiunxPaisley** [comment]
It's because the version of Python's protobuf  is inconsistent with the version of  C++ protobuf. Using command `protoc --version` and `pip list | grep protobuf` to check the versions of both. Then update the expired one.
