### ISSUE TITLE
there are some erros when cmake

### ISSUE THREAD

**Issue by block98k** [facebookarchive/caffe2#2399]
cmake: /home/imsn-s/anaconda2/lib/libcurl.so.4: no version information available (required by cmake)
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64 - Success
-- Does not need to define long separately.
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Success
-- NUMA is available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Success
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Build type not set - defaulting to Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found protobuf with old-style protobuf targets.
-- Caffe2 protobuf include directory: /home/imsn-s/.conda/envs/py2caffe2/include
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing:  NNPACK_INCLUDE_DIR NNPACK_LIBRARY PTHREADPOOL_LIBRARY CPUINFO_LIBRARY) 
-- Brace yourself, we are building NNPACK
CMake Error at cmake/External/nnpack.cmake:73 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/NNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:103 (include)

CMake Error at cmake/External/nnpack.cmake:78 (set_property):
  set_property could not find TARGET nnpack.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:103 (include)

CMake Error at cmake/External/nnpack.cmake:79 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:103 (include)

CMake Error at cmake/External/nnpack.cmake:80 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:103 (include)

CMake Error at cmake/Dependencies.cmake:100 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/cpuinfo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Error at cmake/Dependencies.cmake:105 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /home/imsn-s/.conda/envs/py2caffe2/include  
-- Caffe2: Found glog (include: /home/imsn-s/.conda/envs/py2caffe2/include, library: /home/imsn-s/.conda/envs/py2caffe2/lib/libglog.so)
CMake Error at cmake/Dependencies.cmake:155 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/googletest

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Error at cmake/Dependencies.cmake:162 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/benchmark

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

-- Found LMDB: /home/imsn-s/.conda/envs/py2caffe2/include  
-- Found lmdb    (include: /home/imsn-s/.conda/envs/py2caffe2/include, library: /home/imsn-s/.conda/envs/py2caffe2/lib/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /home/imsn-s/.conda/envs/py2caffe2/include  
-- Found Snappy  (include: /home/imsn-s/.conda/envs/py2caffe2/include, library: /home/imsn-s/.conda/envs/py2caffe2/lib/libsnappy.so)
-- Found Numa: /usr/include  
-- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
-- Found CUDA: /usr/local/cuda (found suitable exact version "9.0") 
-- OpenCV found (/usr/local/share/OpenCV)
CMake Warning at cmake/Dependencies.cmake:273 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

-- Did not find system Eigen. Using third party subdirectory.
-- Found PythonInterp: /home/imsn-s/.conda/envs/py2caffe2/bin/python2.7 (found suitable version "2.7.13", minimum required is "2.7") 
-- Found PythonLibs: /home/imsn-s/.conda/envs/py2caffe2/lib/libpython2.7.so (found suitable version "2.7.13", minimum required is "2.7") 
-- Found NumPy: /home/imsn-s/.conda/envs/py2caffe2/lib/python2.7/site-packages/numpy/core/include (found version "1.13.1") 
-- NumPy ver. 1.13.1 found (include: /home/imsn-s/.conda/envs/py2caffe2/lib/python2.7/site-packages/numpy/core/include)
-- Could NOT find pybind11 (missing:  pybind11_INCLUDE_DIR) 
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
CMake Warning at cmake/Dependencies.cmake:327 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Found CUDNN: /usr/local/cuda/include  
-- Caffe2: CUDA detected: 9.0
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Automatic GPU detection returned 3.7 3.7 3.7 3.7.
-- Added CUDA NVCC flags for: sm_37
-- Found NCCL: /usr/include  
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
-- Could NOT find CUB (missing:  CUB_INCLUDE_DIR) 
-- Could NOT find Gloo (missing:  Gloo_INCLUDE_DIR Gloo_LIBRARY) 
CMake Error at cmake/Dependencies.cmake:420 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/gloo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Warning at cmake/Dependencies.cmake:460 (message):
  mobile opengl is only used in android or ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Warning at cmake/Dependencies.cmake:536 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Error at cmake/Dependencies.cmake:569 (add_subdirectory):
  The source directory

    /home/imsn-s/caffe2/third_party/onnx

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

CMake Error at cmake/public/utils.cmake:7 (get_target_property):
  get_target_property() called with non-existent target "onnx".
Call Stack (most recent call first):
  cmake/Dependencies.cmake:572 (caffe2_interface_library)
  CMakeLists.txt:103 (include)

-- GCC 5.4.0: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- Include Observer library
-- Using lib/python2.7/site-packages as python relative installation path
-- Automatically generating missing __init__.py files.
-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1399-g30a1c04-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /home/imsn-s/.conda/envs/py2caffe2/bin/protoc
--   Protobuf include path : /home/imsn-s/.conda/envs/py2caffe2/include
--   Protobuf libraries    : optimized;/home/imsn-s/.conda/envs/py2caffe2/lib/libprotobuf.so;debug;/home/imsn-s/.conda/envs/py2caffe2/lib/libprotobuf.so;-lpthread
--   BLAS                  : Eigen
--   CXX flags             :  -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python includes     : /home/imsn-s/.conda/envs/py2caffe2/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 9.0
--     CuDNN version       : 7.0.4
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : ..
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.21
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.4.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring incomplete, errors occurred!
See also "/home/imsn-s/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/imsn-s/caffe2/build/CMakeFiles/CMakeError.log"

--------------------------------------------
so please give me some advices,thanks

**Comment by pjh5** [comment]
https://caffe2.ai/docs/faq.html#the-source-directory-does-not-contain-a-cmakeliststxt-file

**Comment by CF2220160244** [comment]
i have the same error,  how did you slove this error? @block98k

**Comment by orionr** [comment]
@CF2220160244 please run `git submodule update --init` to make sure all the submodules are checked out. Let us know if that doesn't work.

**Comment by CF2220160244** [comment]
@orionr thank you very much, but when i run 
git submodule update --init
it happen such problem:

..........
Checking connectivity... done.
Submodule path 'third_party/cub': checked out '285aeebaa34b0e8a7670867a2e66c1a52d998d6a'
Cloning into 'third_party/eigen'...
Username for 'https://github.com': CF2220160244
Password for 'https://CF2220160244@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path 'third_party/eigen' failed

**Comment by orionr** [comment]
@CF2220160244 - got it. In that case, looks like you're still on the caffe2/caffe2 GitHub repository. Eigen has moved to a different repository, for example. All the latest code is being developed in conjunction with PyTorch, so you'll want to do

```
cd ~
git clone https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init --recursive
python setup.py install
```
More details at https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

You can still build with CMake too if you'd like.

**Comment by Kaidanov** [comment]
not working
what can I do ?


D:\dev\ML\pytorch>git submodule update --init --recursive
Submodule 'third_party/QNNPACK' (https://github.com/pytorch/QNNPACK) registered for path 'third_party/QNNPACK'
Submodule 'third_party/fbgemm' (https://github.com/pytorch/fbgemm) registered for path 'third_party/fbgemm'
Submodule 'third_party/gemmlowp/gemmlowp' (https://github.com/google/gemmlowp.git) registered for path 'third_party/gemmlowp/gemmlowp'
Submodule 'third_party/neon2sse' (https://github.com/intel/ARM_NEON_2_x86_SSE.git) registered for path 'third_party/neon2sse'
Cloning into 'D:/dev/ML/pytorch/third_party/QNNPACK'...
Cloning into 'D:/dev/ML/pytorch/third_party/fbgemm'...
Cloning into 'D:/dev/ML/pytorch/third_party/gemmlowp/gemmlowp'...
Cloning into 'D:/dev/ML/pytorch/third_party/neon2sse'...
Cloning into 'D:/dev/ML/pytorch/third_party/protobuf'...
Cloning into 'D:/dev/ML/pytorch/third_party/psimd'...
Cloning into 'D:/dev/ML/pytorch/third_party/pthreadpool'...
Cloning into 'D:/dev/ML/pytorch/third_party/pybind11'...
Cloning into 'D:/dev/ML/pytorch/third_party/python-enum'...
Cloning into 'D:/dev/ML/pytorch/third_party/python-peachpy'...
Cloning into 'D:/dev/ML/pytorch/third_party/python-six'...
Cloning into 'D:/dev/ML/pytorch/third_party/sleef'...
Cloning into 'D:/dev/ML/pytorch/third_party/zstd'...
Submodule path 'third_party/ComputeLibrary': checked out '292227986edb37b01061afcad6df18ba9d6ccbeb'
Submodule path 'third_party/QNNPACK': checked out '85e21ce260ea04a8dc024c4efe6115fd59ac45d4'
Submodule path 'third_party/benchmark': checked out '505be96ab23056580a3a2315abba048f4428b04e'
Submodule path 'third_party/catch': checked out '0a34cc201ef28bf25c88b0062f331369596cb7b7'
Submodule path 'third_party/cub': checked out '285aeebaa34b0e8a7670867a2e66c1a52d998d6a'
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Total 65 (delta 54), reused 54 (delta 54), pack-reused 11
Unpacking objects: 100% (65/65), done.
From https://github.com/eigenteam/eigen-git-mirror
   d10e1f03d..a826c4090  master           -> origin/master
   fad3f27d4..2bb20745a  branches/3.3     -> origin/branches/3.3
   d10e1f03d..a826c4090  branches/default -> origin/branches/default
From https://github.com/eigenteam/eigen-git-mirror
 * branch                f59336cee358f92b959de6a0daf07c4ab2318022 -> FETCH_HEAD
Submodule path 'third_party/eigen': checked out 'f59336cee358f92b959de6a0daf07c4ab2318022'
Submodule path 'third_party/fbgemm': checked out 'e85b5a12254fa47ca6b56236489253a68fd32104'
Submodule path 'third_party/gemmlowp/gemmlowp': checked out '8416bab644641a5c0a81ecf91a5cda804af0aee1'
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 73 (delta 53), reused 71 (delta 53), pack-reused 0
Unpacking objects: 100% (73/73), done.
From https://github.com/facebookincubator/gloo
   7a26270..0df388b  master     -> origin/master
Submodule path 'third_party/gloo': checked out '6af8272a9533a51b5c2d5a303f16a80c207270fb'
Submodule path 'third_party/googletest': checked out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 21 (delta 17), reused 21 (delta 17), pack-reused 0
Unpacking objects: 100% (21/21), done.
From https://github.com/NVIDIA/nccl
   3202d6b..b56650c  master     -> origin/master
 * [new tag]         v2.3.7-1   -> v2.3.7-1
Submodule path 'third_party/nccl/nccl': checked out 'b56650c7f59b8cd40d18809784a6d6be38ef8acb'
Submodule path 'third_party/neon2sse': checked out '97a126f08ce318023be604d03f88bf0820a9464a'
Submodule path 'third_party/onnx': checked out 'f8828e532da4795e8ea15f5850a37c5179917b9b'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/onnx/third_party/benchmark'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/onnx/third_party/pybind11'
Cloning into 'D:/dev/ML/pytorch/third_party/onnx/third_party/benchmark'...
Cloning into 'D:/dev/ML/pytorch/third_party/onnx/third_party/pybind11'...
Submodule path 'third_party/onnx/third_party/benchmark': checked out 'e776aa0275e293707b6a0901e0e8d8a8a3679508'
Submodule path 'third_party/onnx/third_party/pybind11': checked out 'a1041190c8b8ff0cd9e2f0752248ad5e3789ea0c'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/onnx/third_party/pybind11/tools/clang'
Cloning into 'D:/dev/ML/pytorch/third_party/onnx/third_party/pybind11/tools/clang'...
Submodule path 'third_party/onnx/third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'third_party/onnx-tensorrt': checked out 'fa0964e8477fc004ee2f49ee77ffce0bf7f711a9'
Submodule 'third_party/onnx' (https://github.com/onnx/onnx.git) registered for path 'third_party/onnx-tensorrt/third_party/onnx'
Cloning into 'D:/dev/ML/pytorch/third_party/onnx-tensorrt/third_party/onnx'...
Submodule path 'third_party/onnx-tensorrt/third_party/onnx': checked out 'b4072194c2e6ef90693bcfdea4c6f45cf30bb65e'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/onnx-tensorrt/third_party/onnx/third_party/benchmark'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11'
Cloning into 'D:/dev/ML/pytorch/third_party/onnx-tensorrt/third_party/onnx/third_party/benchmark'...
Cloning into 'D:/dev/ML/pytorch/third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11'...
Submodule path 'third_party/onnx-tensorrt/third_party/onnx/third_party/benchmark': checked out 'e776aa0275e293707b6a0901e0e8d8a8a3679508'
Submodule path 'third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11': checked out 'a1041190c8b8ff0cd9e2f0752248ad5e3789ea0c'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'
Cloning into 'D:/dev/ML/pytorch/third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'...
Submodule path 'third_party/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'third_party/protobuf': checked out '2761122b810fe8861004ae785cc3ab39f384d342'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
Cloning into 'D:/dev/ML/pytorch/third_party/protobuf/third_party/benchmark'...
Submodule path 'third_party/protobuf/third_party/benchmark': checked out '360e66c1c4777c99402cf8cd535aa510fee16573'
Submodule path 'third_party/psimd': checked out '90a938f30ba414ada2f4b00674ee9631d7d85e19'
Submodule path 'third_party/pthreadpool': checked out '13da0b4c21d17f94150713366420baaf1b5a46f4'
Submodule path 'third_party/pybind11': checked out '5c8746ff135abb390bf95944be593e895a586a50'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/pybind11/tools/clang'
Cloning into 'D:/dev/ML/pytorch/third_party/pybind11/tools/clang'...
Submodule path 'third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'third_party/python-enum': checked out '4cfedc426c4e2fc52e3f5c2b4297e15ed8d6b8c7'
Submodule path 'third_party/python-peachpy': checked out '07d8fde8ac45d7705129475c0f94ed8925b93473'
Submodule path 'third_party/python-six': checked out '15e31431af97e5e64b80af0a3f598d382bcdd49a'
Submodule path 'third_party/sleef': checked out '6ff7a135a1e31979d1e1844a2e7171dfbd34f54f'
Submodule path 'third_party/zstd': checked out 'aec56a52fbab207fc639a1937d1e708a282edca8'

D:\dev\ML\pytorch>python setup.py install
Building wheel torch-1.0.0a0+0fd176f
The support for PyTorch with Python 2.7 on Windows is very experimental.
Please set the flag `FORCE_PY27_BUILD` to 1 to continue build.

D:\dev\ML\pytorch>set DISTUTILS_USE_SDK=1

D:\dev\ML\pytorch>set MSSdk=1

D:\dev\ML\pytorch>set FORCE_PY27_BUILD=1

D:\dev\ML\pytorch>set "CUDAHOSTCXX=%VS140COMNTOOLS%\..\..\VC\bin\amd64\cl.exe"

D:\dev\ML\pytorch>call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
'"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\vcvarsall.bat"' is not recognized as an internal or external command,
operable program or batch file.

D:\dev\ML\pytorch>python setup.py install
Building wheel torch-1.0.0a0+0fd176f
running install
setup.py::run()
running build_deps
setup.py::build_deps::run()
Could not find D:\dev\ML\pytorch\third_party\cpuinfo\CMakeLists.txt
Did you run 'git submodule update --init'?

D:\dev\ML\pytorch>cd third_party

D:\dev\ML\pytorch\third_party>git submodule add https://github.com/pytorch/cpuinfo
'third_party/cpuinfo' already exists in the index

D:\dev\ML\pytorch\third_party>git submodule add https://github.com/pytorch/cpuinfo --force
Cloning into 'D:/dev/ML/pytorch/third_party/--force'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 4887 (delta 9), reused 17 (delta 7), pack-reused 4868
Receiving objects: 100% (4887/4887), 4.35 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (3669/3669), done.

D:\dev\ML\pytorch\third_party>cd..

D:\dev\ML\pytorch>git submodule update --init

D:\dev\ML\pytorch>python setup.py install
Building wheel torch-1.0.0a0+0fd176f
running install
setup.py::run()
running build_deps
setup.py::build_deps::run()
Could not find D:\dev\ML\pytorch\third_party\cpuinfo\CMakeLists.txt
Did you run 'git submodule update --init'?

D:\dev\ML\pytorch>

**Comment by Kaidanov** [comment]
Discovered it's empty
![image](https://user-images.githubusercontent.com/164266/47897329-f5bccb80-de79-11e8-829c-e348a10c6594.png)

**Comment by pjh5** [comment]
Could you try a fresh checkout? Or update Git maybe? I've never seen this issue before but it looks like something is wrong with Git or with Git's metadata in your checkout.
