### ISSUE TITLE
ImportError: cannot import name caffe2_pb2

### ISSUE THREAD

**Issue by ezreal1129** [facebookarchive/caffe2#2404]
If this is a build issue, please fill out the template below.

### System information

* Operating system: ubuntu 14.04
* Compiler version: 5.4.1
* CMake version:3.9.4
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):cuda 8.0 cudnn 6.0.21

### CMake summary output
 General:
--   CMake version         : 3.9.4
--   CMake command         : /usr/local/bin/cmake
--   Git version           : v0.8.1-1414-g9c1d513
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf include path : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.so;-pthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python includes     : /home/amax/anaconda2/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amax/caffe2/build
```
******** Summary ********
<please paste summary output here>
```amax@amax-workstation:~/caffe2$ python caffe2/python/operator_test/relu_op_test.py
Traceback (most recent call last):
  File "caffe2/python/operator_test/relu_op_test.py", line 21, in <module>
    from caffe2.python import core
  File "/home/amax/caffe2/caffe2/python/core.py", line 29, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name caffe2_pb2
amax@amax-workstation:~/caffe2$ ^C
amax@amax-workstation:~/caffe2$ cd build/
#

**Comment by ezreal1129** [comment]
@pjh5

**Comment by wendal** [comment]
```
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"
```

**Comment by pjh5** [comment]
You have already commented on #2099
