### ISSUE TITLE
how can i convert the pkl file to pb file

### ISSUE THREAD

**Issue by JiYuanFeng** [facebookarchive/caffe2#2420]
In facebook 's detectron repository, we can downland the powerful backbone model such as the Densenet and ResNeXt.
And I found the convert_pkl_to_pb seems can't help us to convert the backbone model to the PB file.
so what can I do for it?
or are there any way to visualize the network structure?
Thank you!

**Comment by orionr** [comment]
Hi @JiYuanFeng. The pkl format from Detectron includes Python operators. Some of these can be converted to pure C++ operators (you'll see this being done for GenerateProposals in the convert_pkl_to_pb code, for example), but not all of them can be converted yet. We're working on it. In the meantime, Detectron models need to be run on a GPU and within Detectron. For visualizing structure, feel free to ask in the Detectron repository at https://github.com/facebookresearch/Detectron/issues

**Comment by IgorKasianenko** [comment]
Hi,
I was looking for example of usage of convert_pkl_to_pb.py but couldn't find one. How do I run it for test model, that is provided in [tutorial](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md)?
I have model in pkl e.g. model_final.pkl and -cfg e2e_mask_rcnn_R-101-FPN_2x.yaml

**Comment by orionr** [comment]
HI @IgorKasianenko - FPN isn't currently supported by pure Caffe2 / pb files yet. It's a work in progress. To see how to convert a model with a ResNet-50 backbone, though, take a look at https://github.com/caffe2/models/blob/master/scripts/import_models_from_detectron.sh#L150-L152

In the future, please open issues at https://github.com/pytorch/pytorch/issues . Thanks
