### ISSUE TITLE
lost math_functions.hpp

### ISSUE THREAD

**Issue by Ericargus** [facebookarchive/caffe2#2422]
If this is a build issue, please fill out the template below.

### System informatiom 

* Operating system: Mint
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):CUDA9.1, cudnn7.05

### CMake summary output
When i write make in the Terminal, it will get error  which say I don't have math_functions.hpp 

```
******** Summary ********
<please paste summary output here>
```

**Comment by sclarkson** [comment]
See https://github.com/caffe2/caffe2/issues/2485
