### ISSUE TITLE
question: can i use caffe2's docker image to do the distributed training?

### ISSUE THREAD

**Issue by GoodJoey** [facebookarchive/caffe2#2446]
any introduce or samples to do that?
thanks.

**Comment by pjh5** [comment]
I don't think we have any samples or tutorials for that. You _can_ run distributed training off of docker containers, but you'd have to figure out the correct networking setup for all of the docker containers, which will be tricky if you haven't worked with that before. The exact steps you have to take will depend a lot on the environment setup that you want to run this in.

**Comment by GoodJoey** [comment]
yes, setting the network will be very tricky.
i know a little bit about mpi, but no clue about the gloo.
i will try to run the image on host mode to see whether it's worked, deploying with docker on multiple nodes will save a lot of efforts.
