### ISSUE TITLE
CHECK failed: generated_database_->Add(encoded_file_descriptor, size):

### ISSUE THREAD

**Issue by TianFuKang** [facebookarchive/caffe2#2457]
# python ../caffe2/python/caffe_translator.py /opt/tfk/*/*/deploy.prototxt /opt/tfk/*/*/*.caffemodel --init_net=testinit.pb --predict_net=testpredict.pb

[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
已放弃 (核心已转储)

How to solve？

**Comment by yinghai** [comment]
Interesting. Looks like you are loading two dynamic libraries that contains the caffe protobuf symbol. Are you on Linux or Windows?

**Comment by zhangw864680355** [comment]
@TianFuKang I also have this problem when I redownload caffe2 to compile！I try to remove libprotobuf-dev python-protobuf protobuf-compiler and install protobuf 3.5.1  and it doest not work. Do you solve it?if successing, please tell me ! Thanks!

**Comment by yinghai** [comment]
@zhangwei147258 Check if you have installed Caffe (not Caffe2) before?

**Comment by zhangw864680355** [comment]
@yinghai yes ,I have installed the caffe and caffe2 in the same machine.

**Comment by yinghai** [comment]
Ok. That explains why you have protobuf conflicts for Caffe. Try uninstalling Caffe?

**Comment by yinghai** [comment]
Closing as we understand the issue.
