### ISSUE TITLE
ImportError: No module named caffe2.python

### ISSUE THREAD

**Issue by ptzheng** [facebookarchive/caffe2#2461]
I have installed caffe2 with build from source. But when I try to see see if my Caffe2 installation was successful, it failed. I used `python -c 'from caffe2.python import core'` to find the reason, and it showed:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named caffe2.python

I have searched the problem in google and read [https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2](url), but I am still confused about the problem. 
I installed python by `sudo apt-get python-dev` at first and I installed  anaconda later. The result of `which python`  is  **/home/ptzheng/anaconda2/bin/python** . The python information is:
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
However, I didn't use anaconda to install caffe2. When I check the directory of python, I am sure that my caffe2 was installed in the **/usr/locol** one, but not in the **anaconda** one. 
I think if it is a environment variable problem. How can I solve it?Can anyone give me some advices?  Please instruct me as detailed as possible. Thanks.

System Information:Ubuntu 14.04

**Comment by wdgj-xy** [comment]
hi!
I have the same problem as ptzheng!

**Comment by youngxiao** [comment]
@ptzheng I met the same problem with you. I am still struggling on it. Do you solve it?

**Comment by bigfly1994** [comment]
Hi!
I met the same problem with you. Do you solve it?

**Comment by nazlitemur** [comment]
Any solution ?  I have the same problem.

**Comment by lianuo** [comment]
same problem.
