### ISSUE TITLE
Vary fast implement of 3x3 conv on CPU with padding = 0, stride, dilation = 1

### ISSUE THREAD

**Issue by wasd96040501** [facebookarchive/caffe2#2492]
Hello, everyone.
I have implemented a vary fast version of 3x3 convolution with padding = 0, stride, dilation = 1 on CPU.
I know it can not come into use now, I just want to share my idea with you.(https://github.com/wasd96040501/conv3x3)
Here are some benchmark results compared to caffe2 CPU implement of conv_op. 
Platform: ubuntu 16.04, haswell intel i7-4702MQ @2.20GHz
```
test case: 0
out_channel: 8 in_channel: 4 out_height: 32 out_width: 32
error:0
GFLOPS by Eigen is: 7.70078
GFLOPS by direct-conv  is: 15.2591

test case: 3
out_channel: 16 in_channel: 16 out_height: 64 out_width: 64
error:0
GFLOPS by Eigen is: 11.8056
GFLOPS by direct-conv  is: 29.8521

test case: 6
out_channel: 48 in_channel: 64 out_height: 256 out_width: 256
error:0
GFLOPS by Eigen is: 8.32179
GFLOPS by direct-conv  is: 27.3182
```

My idea is simple, just skip im2col to obtain a higher rate of operation / (load, store)
Welcome to visit the page mentioned above for more detail.

**Comment by yinghai** [comment]
Caffe2 has been moved to https://github.com/pytorch/pytorch . Please post your issue at https://github.com/pytorch/pytorch/issues and include [Caffe2] in the beginning of your issue title.
