### ISSUE TITLE
C++ How to copy from TensorCUDA to TensorCPU

### ISSUE THREAD

**Issue by tblattner** [facebookarchive/caffe2#2544]
I recently installed the latest version of Caffe2 (0.8.2 according to the VERSION_NUMBER file), and my method for copying a TensorCUDA into a TensorCPU appears to no longer be valid.

Here is how I had structured the code before:
```
  workspace.RunNet(predictNetDef.name());

  auto output = workspace.GetBlob(outputName);

  caffe2::TensorCPU cpuOutput(output->Get<caffe2::TensorCUDA>());

  float *outputData = cpuOutput.data<float>();
```

The error I am getting is:
> error: no matching function for call to ‘caffe2::Tensor::Tensor(caffe2::Tensor*&)’

I've tried a number of combinations, but I can't seem to find the right way to get the data back onto the CPU using the Tensor API. I searched around, but was unable to locate examples for doing this.

What is the correct method for copying from TensorCUDA into TensorCPU?

I am considering just allocating my own CPU memory and using cudaMemcpy, but would prefer to just use the Caffe2 API.

Edit:
Tried this and got it to work:
`  caffe2::TensorCPU cpuOutput(output->Get<caffe2::TensorCUDA>(), caffe2::DeviceType::CPU);
`

**Comment by beichen2012** [comment]
caffe2::TensorCPU* ot = new caffe2::TensorCPU(caffe2::DeviceType::CPU);                                                                                                           
caffe2::TensorCUDA* data = w_.GetBlob(i)->GetMutableTensor(caffe2::DeviceType::CUDA);                                                                                             
ot->CopyFrom(*data);
float *outputData = ot->mutable_data<float>();
