### ISSUE TITLE
CMakeFiles/Makefile2:1436: recipe for target 'caffe2/CMakeFiles/test_parallel.dir/all' failed

### ISSUE THREAD

**Issue by mzh1993** [facebookarchive/caffe2#2551]
Hi,everyone,The error occurred when I following the Build from Source tutorial, how can I fix it?

- /home/mzh/anaconda2/conda-bld/caffe2-cuda9.0-cudnn7_1535533042294/work/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GlobalMPIComm()'
/home/mzh/anaconda2/conda-bld/caffe2-cuda9.0-cudnn7_1535533042294/work/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::MPIMutex()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/test_parallel.dir/build.make:101: recipe for target 'bin/test_parallel' failed
make[2]: *** [bin/test_parallel] Error 1
CMakeFiles/Makefile2:1436: recipe for target 'caffe2/CMakeFiles/test_parallel.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/test_parallel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/mzh/anaconda2/conda-bld/caffe2-cuda9.0-cudnn7_1535533042294/work/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GlobalMPIComm()'
/home/mzh/anaconda2/conda-bld/caffe2-cuda9.0-cudnn7_1535533042294/work/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::MPIMutex()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/atest.dir/build.make:101: recipe for target 'bin/atest' failed
make[2]: *** [bin/atest] Error 1
CMakeFiles/Makefile2:1357: recipe for target 'caffe2/CMakeFiles/atest.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/atest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/mzh/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 2168, in build_tree
    notest=notest,
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1408, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 300, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/mzh/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/mzh/anaconda2/conda-bld/caffe2-cuda9.0-cudnn7_1535533042294/work/conda_build.sh']' returned non-zero exit status 2

**Comment by dbc148** [comment]
I'm getting a similar problem (replacing my full home directory with ~, using a python 2.7 conda environment with Cuda 8.0, CuDNN 6.0.21,  and NCCL, and installing from ~/pytorch with the conda env active):

[ 98%] Linking CXX executable ../bin/basic
~/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GlobalMPIComm()'
~/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::MPIMutex()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/basic.dir/build.make:106: recipe for target 'bin/basic' failed
make[2]: *** [bin/basic] Error 1
CMakeFiles/Makefile2:2383: recipe for target 'caffe2/CMakeFiles/basic.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/basic.dir/all] Error 2

Any help is greatly appreciated!

**Comment by orionr** [comment]
@mzh1993 and @dbc148, thank you for the reports! Can you see if the changes at https://github.com/pytorch/pytorch/pull/11037 resolve your problem?

**Comment by dbc148** [comment]
That worked for me.  Thanks a lot!

**Comment by mzh1993** [comment]
That worked for me too. Thanks a lot!
Change the code with [caffe2/mpi/mpi_common.h](https://github.com/pytorch/pytorch/pull/11037/commits/10322d92c9ceea02d693696235e45e6adda4a999), then recompile.
