### ISSUE TITLE
how workspcae process  the operater with type =Python 

### ISSUE THREAD

**Issue by wxy656** [facebookarchive/caffe2#2552]
the operater is : 

input: "gpu_0/rpn_cls_probs_fpn2"
input: "gpu_0/rpn_bbox_pred_fpn2"
input: "gpu_0/im_info"
output: "gpu_0/rpn_rois_fpn2"
output: "gpu_0/rpn_roi_probs_fpn2"
name: "GenerateProposalsOp:gpu_0/rpn_cls_probs_fpn2,gpu_0/rpn_bbox_pred_fpn2,im_info"
type: "Python"
arg {
  name: "grad_input_indices"
}
arg {
  name: "token"
  s: "forward"
}
arg {
  name: "spatial_scale"
  f: 0.25
}
arg {
  name: "grad_output_indices"
}
device_option {
  device_type: 1
  cuda_gpu_id: 0
}

when I run  workspace.RunOperatorOnce(op),An error has occurred：
RuntimeError: [enforce fail at pybind_state.cc:165] gRegistry().count(token). Python operator for forward is not available. If you use distributed training it probably means that python implementation has to be registered in each of the workers Error from operator:

**Comment by orionr** [comment]
Caffe2 has been moved to https://github.com/pytorch/pytorch . Please post your issue at https://github.com/pytorch/pytorch/issues and include [Caffe2] in the beginning of your issue title.
