### ISSUE TITLE
CRITICAL:root:Cannot load caffe2.python. Error: /usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZTIN6caffe27NetBaseE

### ISSUE THREAD

**Issue by chr10003566** [facebookarchive/caffe2#2554]
![screenshot from 2018-08-30 16-14-27](https://user-images.githubusercontent.com/8433954/44838864-d3d37c80-ac6f-11e8-95b2-32611e1eddbb.png)

I bulided caffe2 according to the  [installation instructions](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile).

When I proceed to this step, I got a error and find a lot of issues, but no luck, Can anyone help? Thank you very much~

**Comment by seelikat** [comment]
The same happens for me. Any solutions?

**Comment by orionr** [comment]
@kateiyas, can you confirm you have the latest checkout from `pytorch/pytorch` master and that you've done `git submodule update --init` as well?

Once you've done that, can you confirm `NetBase` has a `CAFFE2_API` prefix in `caffe2/core/net.h` like this?

```
class CAFFE2_API NetBase : public Observable<NetBase>
```

You might also want to do `git clean -fdx` and then run `python setup.py build_deps` to rebuild and see if it gets past the linking error.

**Comment by seelikat** [comment]
@orionr Thanks for the immediate response. After not being able to get very far in compiling myself (most notably OpenCV) I have decided to merely follow the installation instructions with prebuilt binaries as follows: 

`conda install pytorch torchvision -c pytorch`

`conda install -c caffe2 caffe2`

Please let me know if you think it is safer to built from scratch.. The error occurs when I run `extract_features.py` from here: https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/feature_extraction.md

**Comment by orionr** [comment]
If you install the nightlies that will give you effectively what we have in master:

```
conda install pytorch-nightly torchvision -c pytorch
```
No need to install caffe2 separately now, since it's all available in the above.

**Comment by seelikat** [comment]
@orionr Thanks, the installation of the nightly got me around the error mentioned in the title of this thread.

**Comment by lanpa** [comment]
@orionr This happens again:
https://travis-ci.org/lanpa/tensorboardX/jobs/446541153
However, it works well on my azure machine (without GPU) or my local machine (with GPU).
It might be a system lib linking problem.
