### ISSUE TITLE
How can I fix "/lib64/libc.so.6: version `GLIBC_2.14'" error 

### ISSUE THREAD

**Issue by BasselAli1** [facebookarchive/caffe2#2569]
Hi guys :sweat_smile:  :sweat_smile:  I have a question but I don't know if this the right place to ask or not.
I am using pytorch and I wanted to use detectron and they are saying that I have to install caffe2 first and I did so but when type `from caffe2.python import core`, I see this 
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /home/qwe123/data/conda_packages/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so)` 
I tried other solutions I found on here but I could not get this to work. I only installed caffe2 because I wanted to use detectron, Can I use it with pytorch without the need of caffe2? My version of pytorch of 4.0, Should I download pytorch version 1.0 to use detectron with it?

**Comment by orionr** [comment]
You'll definitely need PyTorch 1.0 to use Detectron (which is based on Caffe2). Also, you'll need to have a GPU to run most of the Detectron code - something like a 1080 or above. Hope that helps! Feel free to open an issue on pytorch/pytorch in the future.

**Comment by BasselAli1** [comment]
@orionr :sweat_smile: that is part of the error. I have a GPU tesla K80 and I train NN on it using pytorch but I see this error when I use caffe2 `This caffe2 python run does not have GPU support`. Anyways, if I can use detectron with pytorch 1.0, I'll do it. :+1: thank you so much for the immediate replay
