### ISSUE TITLE
Build Caffe2 on windows failed

### ISSUE THREAD

**Issue by yiwsun** [facebookarchive/caffe2#261]
I was trying to install Caffe2 on Windows Server 2016 (VM) with CMake, Visual Studio 2017 Community Edition, Python 3.5 (Anaconda 4.2.0) installed. When running Script\Build_Windows.bat, got the following error:

"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\Caffe2_CPU.vcxproj" (default target) (3) ->
"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\proto\Caffe2_PROTO.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2/proto/caffe2.pb.h(12): fatal error C1189: #error:  This file
 was generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\proto\Ca
ffe2_PROTO.vcxproj]
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2/proto/caffe2_legacy.pb.h(12): fatal error C1189: #error:  Th
is file was generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\p
roto\Caffe2_PROTO.vcxproj]
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2/proto/hsm.pb.h(12): fatal error C1189: #error:  This file wa
s generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\proto\Caffe
2_PROTO.vcxproj]
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2/proto/metanet.pb.h(12): fatal error C1189: #error:  This fil
e was generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\proto\C
affe2_PROTO.vcxproj]
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2/proto/predictor_consts.pb.h(12): fatal error C1189: #error:
 This file was generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe
2\proto\Caffe2_PROTO.vcxproj]

"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe2\Caffe2_CPU.vcxproj" (default target) (3) ->
"C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe\proto\Caffe_PROTO.vcxproj" (default target) (5) ->
  C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe/proto/caffe.pb.h(12): fatal error C1189: #error:  This file w
as generated by a newer version of protoc which is [C:\Users\sqlpythonadmin\Source\Repos\caffe2\build\caffe\proto\Caffe
_PROTO.vcxproj]

    6 Warning(s)
    6 Error(s)

How could I resolve these errors? 

To give some context, initially I installed protobuf using command:
*conda install -c conda-forge protobuf=3.2.0*
but when running build script, it reports a CMake Error: The source directory "C:/Users/sqlpythonadmin/Source/Repos/caffe2/third_party/protobuf/cmake" does not exist. Hence end up build protobuf locally using .sln in Visual Studio 2017

**Comment by ezineo** [comment]
Do you have ran 
`git clone --recursive https://github.com/caffe2/caffe2.git` ?
And check out your **C:/Users/sqlpythonadmin/Source/Repos/caffe2/third_party/protobuf** path, where **protobuf** source code exists.

**Comment by yiwsun** [comment]
yes, I did, by using Git Plugin in Visual Studio with "recursive clone submodules" checked. 
Is there a way to remove all existing caffe2 stuff and restart the process again? Would remove C:/Users/sqlpythonadmin/Source/Repos/caffe2 folder be enough?

**Comment by yiwsun** [comment]
After remove caffe2 folder, and another folder where protobuf was installed using conda install, rerun build_windows.bat, the issue with protobuf seems gone. But came another issue:
C:\Users\sqlpythonadmin\Source\Repos\caffe2\python\pybind_state.cc(194): error C3861: 'PyString_AsString': identifier
not found [C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\caffe2_pybind11_state.vcxproj]
C:\Users\sqlpythonadmin\Source\Repos\caffe2\python\pybind_state.cc(196): error C3861: 'PyString_AsString': identifier
not found [C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\caffe2_pybind11_state.vcxproj]
C:\Users\sqlpythonadmin\Source\Repos\caffe2\python\pybind_state.cc(314): error C3861: 'PyString_Check': identifier not
 found [C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\caffe2_pybind11_state.vcxproj]
C:\Users\sqlpythonadmin\Source\Repos\caffe2\python\pybind_state.cc(819): error C3861: 'PyString_Check': identifier not
 found [C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\caffe2_pybind11_state.vcxproj]
  pybind_state_mkl.cc
  Generating Code...
Done Building Project "C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\caffe2_pybind11_state.vcxproj" (default targe
ts) -- FAILED.

A quick search indicates "PyString_AsString" is defined in Python2, but I have installed Python3.5.2. Does it mean Caffe2 only works with Python2? Thanks.

**Comment by ezineo** [comment]
Yes, you get it.
Caffe2 doesn't support Python3 yet. You could use Anaconda2 instead.

**Comment by yiwsun** [comment]
Thank you ezineo! I managed to replace some deprecated Python2 methods with Python3 ones. and the caffe2 build pass. But when trying to import Caffe2 in Python:
from caffe2.python import core, workspace
from caffe2.proto import caffe2_pb2
 it reported an error "ImportError: No module named 'caffe2'". Some discussion mentioned about pycaffe, but I was not able to find pycaffe in the build. Did I miss installing something?

**Comment by Yangqing** [comment]
Could you recursively list the files under the build folder, and especially where all the .so files are located?

**Comment by yiwsun** [comment]
There is no .so files under \build. 
Attaching the output
[Caffe2 build folder files-recursive listing.txt](https://github.com/caffe2/caffe2/files/922985/Caffe2.build.folder.files-recursive.listing.txt)

**Comment by yiwsun** [comment]
Search results showed that even Caffe2.exe was not existing. So the "Build succeeded" message must be a false positive one. 
Attaching the build output message. Could you help figure out what is missing? Is it due to I am using Python 3?
[build_windows_bat_outpu-fixedProtobuft_fixedPyString_AsString.txt](https://github.com/caffe2/caffe2/files/923145/build_windows_bat_outpu-fixedProtobuft_fixedPyString_AsString.txt)
Thanks!

**Comment by Yangqing** [comment]
Ah yeah, right now C2 does not support python3 yet, stay tuned - that is coming in the near future. For now switching to python 2.7 might be the easiest option.

**Comment by yiwsun** [comment]
Thank you Yangqing for the confirmation. I actually tried to install Caffe2 on another VM (windows server 2016 with Python2.7 (Anaconda2), VS2017Community). But it was not able to build caffe2.exe either, with CMakeError like:
* *C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\cmTC_71456.vcxproj]*
* *C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\Debug\cmTC_01d7c.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\cmTC_01d7c.vcxproj]*
* *C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\src.cxx(4): error C3861: '__builtin_cpu_supports': identifier not found [C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\cmTC_a31f6.vcxproj]*
* *C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\src.cxx(1): fatal error C1083: Cannot open include file: 'glog/stl_logging.h': No such file or directory [C:\Users\pythonadmin\Source\Repos\caffe2\build\CMakeFiles\CMakeTmp\cmTC_22aa6.vcxproj]*

Did you experience similar errors while testing on Windows? Any suggestions on how to resolve it?

**Comment by Yangqing** [comment]
Hmm, these all seem to be normal cmake check errors, other than the last line which seems to suggest that glog/stl_logging.h cannot be found. Are you building with glog on Windows? That is a path we have not verified before, so I wonder if you pass in -DUSE_GLOG=OFF things can pass.

**Comment by yiwsun** [comment]
Thanks for your suggestion Yangqing. Finally figured out, I missed an environment variable PYTHONPATH, after adding it, caffe2 works.

**Comment by paninian** [comment]
Can you please specify which "PYTHONPATH" you are refering. Is it Anaconda PythonPath or Caffe Python folder path

**Comment by paninian** [comment]
I have Ananconda Python running from $USER\AppData\Local\Continuum\Anaconda2\python.exe ( on Windows 10 machine) so that is my PATH and PYTHONPATH sys env variable

I have also copied "caffe2_pybind11_state.pyd" and "caffe2_pybind11_state_gpu.pyd" copied from "caffe2\build\caffe2\python\Release" folder to "$USER\AppData\Local\Continuum\Anaconda2\DLLs"...

I've restarted the machine, but when I try to import caffe2 module   
">>from caffe2.python import core".....it still throws the error "No module named caffe2.python"

**Comment by radla001** [comment]
Can you please specify which PYTHONPATH have you added.... I have anaconda installed in "$USER\AppData\Local\Continuum\Anaconda2\python.exe" which is my PYTHONPATH in Windows 10 Desktop.

Also I can confirm that I have copied "caffe2_pybind11_state*.pyd" files to "$USER\AppData\Local\Continuum\Anaconda2\DLLs" 

But no luck when I try to import caffe2  ">>from caffe2.python import core" 
"ImportError: No Module named caffe2.python"

**Comment by yiwsun** [comment]
Add caffe2/build path to your PYTHONPATH. It was mentioned in the install tutorial for Ubuntu. Perhaps worth mentioning in the windows version too.

**Comment by radla001** [comment]
Thanks....it works for me now

**Comment by SWX-TJ** [comment]
I also have this question, when I try to import caffe2 ">>from caffe2.python import core"
"ImportError: No Module named caffe2.python",I have add caffe2/build PYTHONPATH in windows environment,but it didn't work,how can i do?
