### ISSUE TITLE
FullyConnectedOP issue

### ISSUE THREAD

**Issue by ezineo** [facebookarchive/caffe2#262]
Hi, 
Noticed that when 4D-tensor flows through the FC Op, it will become a 2D-tensor.
But if I want to follow a FC Op with another Op, i.e. BatchNorm Op, it will report a **memory overflow** bug because BatchNorm Op needs **input(0)** to be a 4D-tensor
```c++
  DCHECK_EQ(X.ndim(), 4);
  const int N = X.dim32(0);
  const int C = (order_ == StorageOrder::NCHW ? X.dim32(1) : X.dim32(3));
  const int H = (order_ == StorageOrder::NCHW ? X.dim32(2) : X.dim32(1));
  const int W = (order_ == StorageOrder::NCHW ? X.dim32(3) : X.dim32(2));
```
@Yangqing , Do you have any idea about how to fix that?

**Comment by Yangqing** [comment]
Yeah, because after FC, it is understood that the output will be a simple feature vector. You can add a Reshape operator after that to do following spatial ops. If the network is fully convolutional then you might want to replace FC with a Conv.
