### ISSUE TITLE
Issues trying to run multibox without GPU support

### ISSUE THREAD

**Issue by HenriqueC89** [facebookarchive/caffe2#27]
This is the error that i am getting:

[E operator.cc:83] Output size 2 not in range [min=1, max=1].
[E operator.cc:86] Error at operator :MaxPool
[E net.cc:55] Failed to verify operator.
[E workspace.cc:60] Error when setting up network multibox
Traceback (most recent call last):
  File "multibox.py", line 69, in <module>
    workspace.CreateNet(net)
  File "/home/henrique/Documents/Projeto/caffe2/gen/pycaffe2/workspace.py", line 99, in CreateNet
    return cc_CreateNet(StringfyProto(net))
RuntimeError: Cannot create network. See console log for error messages.

And here are the warnings when caffe2 is built:

WARNING: Not all dependencies have succeeded. Skipping build. Failed dependencies: 
WARNING: ['//caffe2/core:core_gpu']
WARNING: Failed to build:
WARNING: //caffe2/binaries:inspect_gpus
WARNING: //caffe2/core:core_cudnn
WARNING: //caffe2/core:core_gpu
WARNING: //caffe2/core:core_gpu_test
WARNING: //caffe2/core:cuda_memorypool_test
WARNING: //caffe2/cuda_rtc:rtc_ops
WARNING: //caffe2/end_to_end_test:end_to_end_tests
WARNING: //caffe2/image:image_ops_gpu
WARNING: //caffe2/mpi:mpi_gpu_test
WARNING: //caffe2/mpi:mpi_ops_gpu
WARNING: //caffe2/operators:core_ops_cudnn
WARNING: //caffe2/operators:core_ops_gpu
WARNING: //caffe2/operators:core_ops_gpu_cu
WARNING: //caffe2/operators:core_ops_test
WARNING: //caffe2/sgd:sgd_ops_gpu
WARNING: //caffe2/utils:math_gpu
WARNING: //third_party/cnmem:cnmem

**Comment by Yangqing** [comment]
This is due to a non-backward-compatible change in MaxPool for caffe2 - I'll try to do a fix in the next few days.

**Comment by rhythm9229** [comment]
multibox is broken on latest caffe2 ,please resolve the issue, the error gets fixed by using older version of caffe2

**Comment by Yangqing** [comment]
I did a quick fix in my forked repo which you can check out here:

https://github.com/Yangqing/multibox

I've left Google so I will not be able to directly update the original repository.

**Comment by rhythm9229** [comment]
thank you :) @Yangqing

**Comment by YantianZha** [comment]
Hi Yangqing,
Could you let me know how you solved it? I met the same problem when using[ the inception googlenet](https://github.com/google/inception). I want to fix it up on my own (but need your suggestions). Thanks!

**Comment by YantianZha** [comment]
I solved it. Add the following lines after the line "tensors.ParseFromString(open('...": 
for op in net.op:
    if op.type == 'MaxPool':
        del op.output[1:]

**Comment by mason2012** [comment]
YantianZha's method worked for me on google's [inception_v1](https://github.com/google/inception).
This bug confused me for two days and I'm so happy to find the correct method to solve it.
I'm not sure whether this bug is cause by the inception_v1 or Caffe2.
Hope somebody can explain it.
