### ISSUE TITLE
Relationship to Caffe?

### ISSUE THREAD

**Issue by ferrouswheel** [facebookarchive/caffe2#274]
It'd be great if there was some documentation describing the relationship between Caffe2 and Caffe. As far as I can tell there is none (from 10 minutes of browsing docs and the source tree), but there are tools to convert a trained model from caffe to caffe2?

If this is the case it'd be great to justify why a unique name wasn't chosen, as I'm sure I'm not the only one who'll be confused!

If there is some deeper relationship, e.g. ex-contributors to caffe wanting to do a rewrite, collaboration with BVLC, or some ancestral git commit that links the two repos, then that would also be great to make clear.

**Comment by ferrouswheel** [comment]
Having the question ["How is Caffe2 different from PyTorch?"](http://caffe2.ai/docs/caffe-migration.html#how-is-caffe2-different-from-pytorch) but no mention about the relationship to Caffe on the same page makes me more confused :-(

Is caffe2 more closely related to PyTorch than to Caffe? There is [this comment](https://www.reddit.com/r/MachineLearning/comments/664ufi/n_facebook_releases_new_deep_learning_framework/dgfrm0s/) on reddit that suggests that it is.

**Comment by Yangqing** [comment]
Yep, Caffe2 is the natural child of Caffe, with quite a few ideas already floating around back in 2015 in our CVPR tutorial: http://tutorial.caffe.berkeleyvision.org/caffe-cvpr15-improving.pdf

The codebase is different enough that we do not want to create pain for existing users, and hence we made a conscious choice to put it in a separate repo. There are migration tools such as caffe translator if you would like to use Caffe2 to drive existing Caffe models. If you find an issue, please let us know - we'll fix it.

/cc @shelhamer , who is my awesome colleague back at Berkeley and is the lead developer on Caffe.

**Comment by shelhamer** [comment]
That's right: Caffe2 is informed by a lot of our experience with Caffe and its direction has been guided by discussion with BVLC/BAIR. We're all collaborating on a migration path from Caffe 1.0 to Caffe2 for those who choose it. We decided on a new line of development so that Caffe 1.0 could continue on with the good old methods of brewing while Caffe2 takes on new designs and approaches unfettered by the past. The decision to fork was made to better serve the whole community by channeling conversations about the converging development of Caffe 1.0 and the future development of Caffe2 to their respective homes. This way Caffe 1.0 usage and development go on uninterrupted and Caffe2 progress goes on unrestrained.

High five to @Yangqing on the latest brew!

Don't worry—we all like our coffee ☕️

**Comment by ferrouswheel** [comment]
Thanks heaps for the background! I look forward to seeing where Caffe2 goes :-)

**Comment by ahrnbom** [comment]
I don't think this question has been answered. On concrete terms, what does Caffe2 do better than Caffe? Is it faster? Is the API cleaner? Does it support new things that Caffe didn't? And so on.

**Comment by Yangqing** [comment]
Pasting a few more details here about how it improve on the original Caffe?

* The  original Caffe framework was useful for large-scale product use cases,  especially with its unparalleled performance and well tested C++ codebase. 
*  But, Caffe has some design choices that is inherited from its original use case: conventional CNN applications. As new computation patterns have emerged,  especially distributed computation, mobile, reduced precision computation,  and more non-vision use cases, its design has shown some limitations.
* Caffe2 improves Caffe in a series of directions: first-class support for large-scale distributed training, mobile deployment, new hardware support (in addition to CPU and CUDA), and flexibility for future directions such as quantized computation. It is also stress tested by the vast scale of Facebook applications.
* At  Facebook, our use of Caffe gave us ideas for how we could design  a better deep learning platform. By early 2016, we had an early version of  Caffe2 that made improvements on Caffe, particularly a modern computation  graph design, minimalist modularity, and flexibility to port to multiple  platforms with ease.

**Comment by shelhamer** [comment]
To point out one further contrast, Caffe 1.0 and Caffe2 differ in the strong/weak typing of the layer/op schema:

- Caffe 1.0 defines a message type for every layer type in its schema. This documents the existing layers and their arguments, but requires re-compilation on modification and causes contention when adding new layers, which both make extension more painful than it should be.
- Caffe2 defines a generic type and argument schema that is invariant to the number, types, and configurability of ops. This falls back to op definition for documentation, but that's no problem, and makes it simple to add or drop ops for a given project or deployment.

This is made evident by the [caffe.proto](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto) weighing in at 1000+ lines and the [caffe2.proto](https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2.proto) only needing 300 lines. The Caffe2 arrangement is more extensible and requires less coordination of contributions.

**Comment by megs05** [comment]
@shelhamer  @Yangqing
I also came across articles where its mentioned that Caffe2 supports multiple precision (compared to Caffe): float, float16, int8 and other quantized models
Is there an article or a repository you can point to where the network is discussing/doing quantization/pruning and I can test and run it?
