### ISSUE TITLE
Compile error in core/context_gpu.cu

### ISSUE THREAD

**Issue by dbermond** [facebookarchive/caffe2#278]
I'm getting the following error when trying to compile caffe2:
```
[ 57%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o
[ 58%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/core/Caffe2_GPU_generated_context_gpu.cu.o
[ 58%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/image/Caffe2_GPU_generated_transform_gpu.cu.o
[ 57%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_accumulate_op.cu.o
/home/user/abs/caffe2-bak/src/caffe2-0.7.0/caffe2/core/context_gpu.cu(228): error: no instance of constructor "cub::CachingDeviceAllocator::CachingDeviceAllocator" matches the argument list
            argument types are: (google::int32, google::int32, google::int32, size_t, __nv_bool, const __nv_bool)

1 error detected in the compilation of "/tmp/tmpxft_00002742_00000000-7_context_gpu.cpp1.ii".
CMake Error at Caffe2_GPU_generated_context_gpu.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/user/abs/caffe2-bak/src/caffe2-0.7.0/build/caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o


make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/build.make:65: caffe2/CMakeFiles/Caffe2_GPU.dir/core/Caffe2_GPU_generated_context_gpu.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:597: caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

System information:
**OS:** Arch Linux x86_64
**caffe2:** 0.7.0 (also happens with caffe2 git master, currently at 0.7.0.r7.gc2f5e14b)
**CUDA:** 8.0.61
**cuDNN:** 6.0.20
**Using GCC:** 5.4.0

Steps to reproduce and complete output are attached.
[steps.txt](https://github.com/caffe2/caffe2/files/931508/steps.txt)
[output.txt](https://github.com/caffe2/caffe2/files/931510/output.txt)

**Comment by schmatz** [comment]
I've also managed to reproduce a similar issue on Ubuntu 16.04 with nvidia-375 drivers and a 980 Ti card.

**Comment by Yangqing** [comment]
Interesting, thanks so much for the bug report! We don't have an Arch Linux to reproduce the error, but it seems to be an easy fix by changing the line to:

    g_cub_allocator.reset(new cub::CachingDeviceAllocator(
        static_cast<unsigned int>(FLAGS_caffe2_cub_bin_growth),
        static_cast<unsigned int>(FLAGS_caffe2_cub_min_bin),
        static_cast<unsigned int>(FLAGS_caffe2_cub_max_bin),
        static_cast<size_t>(-1),
        false,
        k_cub_debug));

according to the cub source code here: https://github.com/NVlabs/cub/blob/master/cub/util_allocator.cuh#L276

Would you mind checking if this works? And if this fixes the issue, please kindly consider sending a PR :)

**Comment by dbermond** [comment]
@Yangqing 
Thank you for the reply.

I tried your suggested implementation but it still gives a similar error:
```
/home/user/abs/caffe2-bak/src/caffe2-0.7.0/caffe2/core/context_gpu.cu(228): error: no instance of constructor "cub::CachingDeviceAllocator::CachingDeviceAllocator" matches the argument list
            argument types are: (unsigned int, unsigned int, unsigned int, size_t, __nv_bool, const __nv_bool)
```

Also tested using the latest git master 0.7.0.r26.g010890cb.

**Comment by Yangqing** [comment]
Seems that you might need to change the last one (k_cub_debug) from const bool to bool - maybe do a `bool(k_cub_debug)`?

**Comment by bramton** [comment]
I noticed `-DCUDA_NVCC_FLAGS:STRING="-I/opt/cuda/include/thrust/system/cuda/detail"`
This points to an outdated version of cub. If you grab version 1.6.4 from [NVlabs](https://github.com/NVlabs/cub) it will work.

**Comment by dbermond** [comment]
It worked by using the method pointed by @bramton . The **cub** version that comes with **CUDA** 8.0 is outdated.
Placing the uptodate **cub** source tree in directory `third_party/cub` makes it to work.

Thank you @Yangqing and @bramton for the answers.
