### ISSUE TITLE
When you guys offer a caffe2 paper??

### ISSUE THREAD

**Issue by chibai** [facebookarchive/caffe2#281]
So when we work by the caffe2 framework, we can cite your paper~thank you

**Comment by Yangqing** [comment]
Not sure if we will have a paper - but that is definitely a good suggestion, thanks!

For now, if you can kindly put the caffe2 link in your paper notes, like "We used the Caffe2 library[1]" and footnote "[1] http://caffe2.ai/", we definitely appreciate that.
