### ISSUE TITLE
how is caffe2's speed compare to tensorflow?

### ISSUE THREAD

**Issue by suiyuan2009** [facebookarchive/caffe2#282]
are there any experiments?

**Comment by Yangqing** [comment]
I am not aware of that right now. Internally we measure the performance by looking at the theoretical peak possible (like the scaling efficiency when you use distributed training). C2 has been doing pretty well; if you find performance degradations - especially compared to Caffe - please do let us know by sending an issue. We are usually very good to figure out perf.
