### ISSUE TITLE
Caffe2 OpenCLv1.x/OpenCLv2.0 etc.. support for Mobile GPUs

### ISSUE THREAD

**Issue by c00lrain** [facebookarchive/caffe2#283]
Congratulation open Caffe2 github.
But surprisingly still no solution for Mobile GPUs which from Qualcomm, Imagination and ARM.
Many Android and iOS mobile devices have GPU and ready to accelerate Tensor processing.
Like a DL framework history Caffe2 also follow CUDA only?
Even Intel-Altera and Xilinx FPGA offer OpenCL based HDL compiler for their FPGA embedded solution.
OpenCL on the Roadmap or out of sight?

**Comment by Yangqing** [comment]
Thanks - cc @ajtulloch 

For the Qualcomm SNPE integration that we announced, we will be rolling out the code and Qualcomm will set their official SNPE release, probably in June or July.

For iOS, we will also push out the metal gpu code soon - there are some build script / sync issues to be sorted out.

For OpenCL / HDL / FPGA - these are definitely interesting directions to pursue. Right now we don't have a definitive roadmap yet, though. Will update when new info pops up.

**Comment by jquave** [comment]
@Yangqing Is there a way the community can contribute to the Metal integration for iOS?

**Comment by Yangqing** [comment]
@jquave - thanks, this is definitely going to be valuable. Currently, as mentioned in #298 we are in the process of pushing our metal code proper as promised. After that we would definitely love to build the metal work together!

**Comment by Yangqing** [comment]
#298 now contains the pointers for metal and snpe - cmake scripts would be the first thing calling for contribution.

**Comment by ThatAIGeek** [comment]
Just came to say that OpenCL support is much needed, and I'd love to see and use it as part of Caffe2!

**Comment by futurely** [comment]
https://community.arm.com/graphics/b/blog/posts/arm-compute-library-for-computer-vision-and-machine-learning-now-publicly-available
