### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kmario23** [facebookarchive/caffe2#287]
I think there is a typo in [README](https://github.com/caffe2/caffe2/blob/master/README.md#ubuntu) which mentions `Ubuntu 16.06`. But, I think it meant to say `Ubuntu 16.04` actually.

**Comment by aaronmarkham** [comment]
Fixed the typo and removed install instructions on the README in favor of having them only on the docs site here:
http://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile
Thanks!
