### ISSUE TITLE
Need help! when I build caffe2 in my mac os system, I  meet with an error.

### ISSUE THREAD

**Issue by zjjzby** [facebookarchive/caffe2#289]
[ 19%] Built target Caffe2_PROTO
[ 71%] Built target Caffe2_CPU
[ 71%] Linking CXX executable binaries/make_image_db
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe2::ConvertImageDataset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in make_image_db.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [caffe2/binaries/make_image_db] Error 1
make[1]: *** [caffe2/CMakeFiles/make_image_db.dir/all] Error 2
make: *** [all] Error 2

Is there anyone meet with the problem?

**Comment by Yangqing** [comment]
Could you post the full cmake output? It seems that this is because opencv is not linked in properly. Do you have opencv2 or opencv3?

**Comment by pietern** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info.
