### ISSUE TITLE
redundant letter "c" in caffe2/core/loggin_is_google_glog.h Line 20

### ISSUE THREAD

**Issue by seed93** [facebookarchive/caffe2#29]
A small mistake in caffe2/core/loggin_is_google_glog.h Line 20.

Two more suggestions:
1. Maybe it is better to control log level of GLOG using the same flag caffe2_log_level. And FLAG_alsologtostderr is better to be 1 by default.
1. caffe2_log_level is unnecessary declared in caffe2/core/loggin_is_not_google_glog.h

**Comment by Yangqing** [comment]
Thanks! This should be fixed in https://github.com/Yangqing/caffe2/commit/acac788c31ba323770c69cb2c64c8f89fbe099eb. I added a todo item for the glog case.
