### ISSUE TITLE
compatibility with ubuntu 16.04

### ISSUE THREAD

**Issue by seed93** [facebookarchive/caffe2#30]
gcc after 5.0 is not supported by CUDA 7.5. Some confusing problems may occur.
1. std::vector<int> X(1, 1); // fail to compile
   std::vector<int> X(1, double(1)); // succeed
2. CHECK_EQ(vector<int>, vector<int>); // fail to compile
   CHECK(vector<int == vector<int>); // succeed

**Comment by Yangqing** [comment]
Thanks for letting me know - I am yet to imstall 16.04 and gcc5 yet, but in the meantime if you have a PR feel free to send it :) Closing it for now.
