### ISSUE TITLE
'ext/slist' file not found when compiling on Mac 10.10.5

### ISSUE THREAD

**Issue by formath** [facebookarchive/caffe2#300]
Env: Mac 10.10.5 
To add -stdlib=libstdc++ may solve it. But I am not clear about where to add. Thanks.
@Yangqing 

```
[ 15%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/core/blob_serialization.cc.o
In file included from /Users/jpl/github/caffe2/caffe2/core/blob_serialization.cc:1:
In file included from /Users/jpl/github/caffe2/caffe2/core/blob_serialization.h:9:
In file included from /Users/jpl/github/caffe2/caffe2/core/blob.h:13:
In file included from /Users/jpl/github/caffe2/caffe2/core/logging.h:24:
In file included from /Users/jpl/github/caffe2/caffe2/core/logging_is_google_glog.h:12:
/usr/local/include/glog/stl_logging.h:56:11: fatal error: 'ext/slist' file not found
# include <ext/slist>
          ^
1 error generated.
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/core/blob_serialization.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by formath** [comment]
Have found it.

**Comment by formath** [comment]
After adding -stdlib=libstdc++, a new error occur. @Yangqing 

```
/Users/jpl/github/caffe2/caffe2/core/blob_serialization.h:5:10: fatal error: 'future' file not found
#include <future>
```

**Comment by Yangqing** [comment]
Interesting, this seems to be because -std=c++11 is not turned on:

http://stackoverflow.com/questions/26051148/clang-failed-to-find-c11-headers

Could you paste your cmake output as well as settings? If you specify -DCMAKE_VERBOSE_MAKEFILE=1 to inspect the flags.

**Comment by formath** [comment]
Located at an old libc++. Changing to a new one fixed it. http://stackoverflow.com/questions/7031126/switching-between-gcc-and-clang-llvm-using-cmake

**Comment by jawaid2018** [comment]
Hello,what to say,I'm perceiveing it after the perception,I shall be able to say until then await,be happy.
