### ISSUE TITLE
Build on Mac OS X failed

### ISSUE THREAD

**Issue by HugoTian** [facebookarchive/caffe2#301]
I try to build on Mac OS X, and it get following error:

    Undefined symbols for architecture x86_64: "cv::imread(std::__1::basic_string<char,    std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", 
    referenced from: caffe2::ConvertImageDataset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) 
    in make_image_db.cc.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code

And here is some of the summary of Cmake

    -- ******** Summary ********
    -- General:
    --   Git version           : v0.7.0-11-gb5705a42-dirty
    --   System                : Darwin
    --   C++ compiler         /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    --   Protobuf compiler     : /usr/local/bin/protoc
    --   CXX flags             :  -std=c++11 -fPIC -Wno-narrowing
    --   Build type            : Release
    --   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY;CAFFE2_UNIQUE_LONG_TYPEMETA
    -- 
    --   BUILD_SHARED_LIBS     : ON
    --   BUILD_PYTHON          : ON
    --     Python version      : 2.7.13
    --     Python library      : ~/anaconda2/lib/libpython2.7.dylib
    --   USE_CUDA              : OFF
    --   USE_NERVANA_GPU       : OFF
    --   USE_GLOG              : ON
    --   USE_GFLAGS            : ON
    --   USE_LMDB              : ON
    --     LMDB version        : 0.9.19
    --   USE_LEVELDB           : ON
    --     LevelDB version     : 1.20
    --     Snappy version      : 1.1.4
    --   USE_OPENCV            : ON
    --     OpenCV version      : 2.4.11
    --   USE_ZMQ               : OFF
    --   USE_ROCKSDB           : OFF
    --   USE_MPI               : OFF
    --   USE_NCCL              : OFF
    --   USE_NNPACK            : OFF
    --   USE_OPENMP            : OFF
    --   USE_REDIS             : OFF
    --   USE_GLOO              : OFF

Thanks in advance

**Comment by bwasti** [comment]
is it possible to build without OpenCV?  Try adding this flag: `-DUSE_OPENCV=OFF` to cmake. Something like this:

`cmake .. -DUSE_OPENCV=OFF`

**Comment by HugoTian** [comment]
It works , Thanks
