### ISSUE TITLE
Are there any plans to support Caffe2 on Windows 7?

### ISSUE THREAD

**Issue by inspire99** [facebookarchive/caffe2#304]
Currently, from http://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile,

it looks like Windows 10 or greater is required to run Caffe2.

Are there any future milestones to support Windows 7?

**Comment by Yangqing** [comment]
We actually haven't tried Caffe2 on Windows 7 yet. In principle, the codebase should be runnable, but one will need to figure out the proper build scripts etc. If the community would love to contribute to this, it would be super awesome :)

A good start is the current build_windows.bat file under scripts/. Depending on different compiler versions you might need to update a few parts of the codebase.

**Comment by Yangqing** [comment]
I am closing this for now - for more details on Windows build support, see https://github.com/caffe2/caffe2/issues/774
