### ISSUE TITLE
No opencl? So grateful of nvidia crossplatform CUDA

### ISSUE THREAD

**Issue by IvanTurgenev** [facebookarchive/caffe2#305]

**Comment by pietern** [comment]
Please see #275 for another comment about OpenCL.. It is not supported right now. I hope this answers your question.

**Comment by TechnikEmpire** [comment]
lol how much did nvidia pay the author of this ticket to write it? That's hilarious. Anyone look at CUDA/cuDNN licenses lately? Filled with notices about all the great open source software they rely on, then followed by droves of binding restrictions about how you're screwed using it for anything but as a researcher or privately. Lets not forget that Nvidia isn't the only GPU in the world.
