### ISSUE TITLE
CPU Affinity on macOS

### ISSUE THREAD

**Issue by farrell236** [facebookarchive/caffe2#306]
Thanks for releasing caffe2! I tried building caffe2 on macOS 10.11.6 with CUDA 8.0.61 and cuDNN v5.0.5, but its failing with the following error:

```
Scanning dependencies of target Caffe2_GPU
[ 53%] Built target gmock_main
[ 53%] Built target python_copy_files
[ 53%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/core/net_gpu.cc.o
caffe2/caffe2/core/net_gpu.cc:271:5: error: unknown type name 'cpu_set_t'
    cpu_set_t mask;
    ^
caffe2/caffe2/core/net_gpu.cc:275:37: error: use of undeclared identifier 'cpu_set_t'
    if (sched_setaffinity(0, sizeof(cpu_set_t), &mask)) {
                                    ^
2 errors generated.
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/core/net_gpu.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make: *** [all] Error 2
```

I examined the offending file and found the TODO mentioning that set CPU affinity has no affect in windows but the code is correct. [According to Apple](https://developer.apple.com/library/content/releasenotes/Performance/RN-AffinityAPI/index.html#//apple_ref/doc/uid/TP40006635), they apparently have their own Thread Affinity API.

A quick hack to fix this issue is to add `#if !defined(_MSC_VER) && !defined(__APPLE__)` in caffe2/caffe2/core/net_gpu.cc, this will allow caffe2 to continue to build. Is it safe to do this as a temporary fix?

**Comment by Yangqing** [comment]
Yes, this sounds like a perfect solution - please kindly send a pull request :)
