### ISSUE TITLE
Recipe for target 'all' failed.

### ISSUE THREAD

**Issue by sayakpaul** [facebookarchive/caffe2#313]
I am giving the error trace when it starts:

[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
/home/sayak/caffe2/caffe2/python/pybind_state.cc: In member function ‘virtual bool caffe2::python::PythonOpBase::RunOnDevice()’:
/home/sayak/caffe2/caffe2/python/pybind_state.cc:202:74: error: ‘PyString_AsString’ was not declared in this scope
             PyString_AsString(trace_vec[i]->tb_frame->f_code->co_filename);
                                                                          ^
/home/sayak/caffe2/caffe2/python/pybind_state.cc: In lambda function:
/home/sayak/caffe2/caffe2/python/pybind_state.cc:322:41: error: ‘PyString_Check’ was not declared in this scope
             if (PyString_Check(arg.ptr())) { // string
                                         ^
/home/sayak/caffe2/caffe2/python/pybind_state.cc: In lambda function:
/home/sayak/caffe2/caffe2/python/pybind_state.cc:824:37: error: ‘PyString_Check’ was not declared in this scope
         if (PyString_Check(arg.ptr())) { // string
                                     ^
caffe2/CMakeFiles/caffe2_pybind11_state.dir/build.make:62: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o' failed
make[3]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o] Error 1
make[3]: Leaving directory '/home/sayak/caffe2/build'
CMakeFiles/Makefile2:2609: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/all] Error 2
make[2]: Leaving directory '/home/sayak/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sayak/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dzhulgakov** [comment]
I think you're linking with python3. Python3 support is going to land in the coming weeks. For now try python2.7 to see whether it works.

**Comment by Yangqing** [comment]
Closing and please follow #315  for updates.
