### ISSUE TITLE
[Question] Getting Involved: Operators

### ISSUE THREAD

**Issue by milewis1** [facebookarchive/caffe2#314]
Good afternoon. I've been playing around with Caffe2 for an iOS project I'm working on and as part of testing my project I've had to port Caffe's Batch Normalization operator to Caffe2 and I have some questions:

1. It was unclear to me how data from a trained caffe model was being converted by caffe_translator. Is there any documentation available for that?
2. A side from implementing the test that your documentation recommends does anyone have any other suggestions for how to compare the inputs/outputs of my operator to Caffe's?
3. Would it be easier for everyone to answer these question if I just go ahead and submit a pull request, even if I'm not 100% convinced it is working correctly yet?

Thanks,
Mike

**Comment by aaronmarkham** [comment]
Hi Mike, did you take a look at this document that covers writing custom operators?
http://caffe2.ai/docs/custom-operators.html

**Comment by milewis1** [comment]
Yes, I did. It turns out I just had a problem with the translation layer, which another user has kindly figured out for me. I'll close this request.
