### ISSUE TITLE
[Python3] Python3 update master task

### ISSUE THREAD

**Issue by Yangqing** [facebookarchive/caffe2#315]
Currently, Caffe2 is supporting 2.7 only and python3 support is coming. Setting up this task to have a single point for status checking and updates.

**Comment by rachitgarg91** [comment]
Hello,

python --version shows 2.7, however, caffe2 uses python from another path:

-- Found PythonInterp: /Users/Innovate/anaconda/bin/python (found version "3.5.2")
...
--   BUILD_PYTHON          : ON
--     Python version      : 3.5.2
--     Python library      : /Users/Innovate/anaconda/lib/libpython3.5m.dylib

>which python
/Users/Innovate/anaconda/envs/py3k/bin/python

Where to set the path to python for caffe2?

Thanks!

**Comment by eddy-ilg** [comment]
One criteria for our switch to Caffe2 or using a non-caffe framework instead is Python3. I don't want to bother, but do you have an estimate of when it might be available? (Weeks, Months, Years ... ;)

**Comment by lukeyeager** [comment]
Once Python2 testing is enabled with https://github.com/caffe2/caffe2/pull/817, it should be pretty simple to add another target to test python3 with every commit.

**Comment by dheera** [comment]
Any update on python3 support? Our entire system is python3 and it would be a pity to not be able to use caffe2 because of this. caffe, tensorflow, and pretty much all other frameworks support python3.
```
:) python3 -c 'from caffe2.python import core'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ImportError: No module named 'past'
```

**Comment by Yangqing** [comment]
Hey guys, quick update - our internal testing of python3 support seems to suggest that we are python3 compatible, so with a few more tests we will mark this resolved. If you'd like to give it a short, please do and let us know if things work incorrectly.

@dheera - your issue is because you'll need to install future:

https://pypi.python.org/pypi/future

**Comment by pietern** [comment]
We now run Python 3 builds for every commit. I think it's safe to close this issue now.

**Comment by dheera** [comment]
Awesome thanks all!

**Comment by moskomule** [comment]
Hello, I'm using Python3.6 and when I import `onnx_caffe2` I got an error below.

```python
In [3]: import onnx_caffe2.backend as backend
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-401d8c4e960a> in <module>()
----> 1 import onnx_caffe2.backend as backend

/opt/.miniconda/lib/python3.6/site-packages/onnx_caffe2/backend.py in <module>()
     11
     12 import caffe2
---> 13 from caffe2.python import core, workspace
     14 from caffe2.proto import caffe2_pb2
     15 import caffe2.python.utils

/usr/local/caffe2/python/core.py in <module>()
     22
     23 from collections import namedtuple, OrderedDict, defaultdict
---> 24 from past.builtins import basestring
     25 from future.utils import viewitems, viewkeys, viewvalues
     26 from itertools import chain

ModuleNotFoundError: No module named 'past'
```

There is no mudule `past` for Python3.6 and so I think caffe2 can't run on, at least, Python3.6.

If there exists any solution for this, let me know. Thank you.

**Comment by garvita-tiwari** [comment]
I am still getting this error
Makefile:4: recipe for target 'all' failed
I tried with python 3 and 2 both.
Any suggestions?
