### ISSUE TITLE
Will there be a build for watchOS (armv7k)? 

### ISSUE THREAD

**Issue by solidua** [facebookarchive/caffe2#316]

**Comment by Yangqing** [comment]
To be honest, we never tried it, but it might be possible. The build script is dependent on ios-cmake, which delegates to apple builder to compile stuff. The switch seems to be similar enough:

Our current ios cmake setting: https://github.com/Yangqing/ios-cmake/blob/master/toolchain/iOS.cmake#L62-L77

A watchOS supporting setting from virgil-crypto: https://github.com/VirgilSecurity/virgil-crypto/blob/master/cmake/apple.toolchain.cmake#L106-L138

Seems like a fun hack-a-day project?

**Comment by Yangqing** [comment]
Guess what, this is really easy - see #321 .

Of course you may still want to follow a few optimization tricks similar to the normal mobile scenarios: #285
