### ISSUE TITLE
The version ('80100') of the host compiler ('Apple clang') is not supported

### ISSUE THREAD

**Issue by encorechow** [facebookarchive/caffe2#318]
I tried to install caffe2 today and configured everything. During installation I got this:
```
[ 56%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/utils/threadpool/ThreadPool.cc.o
[ 56%] Linking CXX shared library libCaffe2_CPU.dylib
[ 56%] Built target Caffe2_CPU
[ 56%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o
nvcc fatal   : The version ('80100') of the host compiler ('Apple clang') is not supported
CMake Error at Caffe2_GPU_generated_math_gpu.cu.o.Release.cmake:218 (message):
  Error generating
  /Users/zhengzhou/Developing/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o


make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o] Error 1
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

Does anyone know I to solve it? Thanks!

**Comment by mjohnst** [comment]
CUDA 8.x doesn't support versions of clang >= 8.0.0.
You can go to the Apple Developers portal and download Command Line Tools for XCode 7.3 (https://developer.apple.com/download/more/)
Mount the DMG and run the PKG - it won't look like anything has happened.

Run `sudo xcode-select --switch /Library/Developer/CommandLineTools`
until your output is something with `Apple LLVM version 7.3.0 (clang-703.0.29)`
It took me 1 or 2 runs of the command for whatever reason.

To switch back to clang v8, open XCode -> Preferences -> Locations and use the dropdown for the Command Line Tools version (for me shows a blank selection when on v7)

**Comment by mjohnst** [comment]
`-DUSE_CUDA=OFF` may also work. Didn't try it though.

**Comment by hlzz** [comment]
@mjohnst @encorechow Don't have to be Xcode 7.3. Xcode 8.2 with NVCC 8.0.61 will work.

**Comment by Yangqing** [comment]
As @hlzz mentioned - this is a NVCC and cuda version conflict. Turning off cuda with -DUSE_CUDA=OFF also helps.

**Comment by encorechow** [comment]
Thanks!

**Comment by encorechow** [comment]
@mjohnst @Yangqing btw, where should I add the -DUSE_CUDA=OFF though?

**Comment by hlzz** [comment]
@encorechow It's a cmake option. In your build directory (I assume it's inside the caffe2 root directory), type:

`cmake -DUSE_CUDA=OFF ..`

**Comment by paulrigor** [comment]
Hi, are there any updates on this issue? Thanks!
