### ISSUE TITLE
Can't open http://caffe2.ai/

### ISSUE THREAD

**Issue by formath** [facebookarchive/caffe2#319]
please fix it.

**Comment by Sundrops** [comment]
GFW.......

**Comment by formath** [comment]
@Sundrops Sure? I have been using VPN.

**Comment by ghost** [comment]
i can't open it too..... but i can open it through google translate.......

**Comment by Yangqing** [comment]
If you are in mainland China this might have been blocked - we use github page and this is a bit unfortunate. Anyone know a reliable workaround?

**Comment by akakcolin** [comment]
https://caffe2.ai/  + VPN can fix it
