### ISSUE TITLE
generate_alexnet dumped

### ISSUE THREAD

**Issue by seed93** [facebookarchive/caffe2#32]
`test_net.AddGradientOperators(first=2)` goes wrong, first id not recognized.
When I change 'first' to 'skip', I get segmentation fault. It breaks in AddGradientOperators
`for forward_op, current_fwd_metadata in zip(operators[::-1], fwd_metadata[::-1]):`
13th iteration.

**Comment by Yangqing** [comment]
(should be fixed in the most recent version)
