### ISSUE TITLE
Caffe2 Build failed on MacOS

### ISSUE THREAD

**Issue by rachitgarg91** [facebookarchive/caffe2#322]
Hello,

I am trying to build caffe2 on Mac but I am getting following build issue:
...
[ 51%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o
nvcc fatal   : The version ('80100') of the host compiler ('Apple clang') is not supported
CMake Error at Caffe2_GPU_generated_math_gpu.cu.o.cmake:203 (message):
  Error generating
  /Users/Innovate/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o

-- ******** Summary ********
-- General:
--   Git version           : v0.7.0-30-g93c35c8
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   Protobuf compiler     : /Users/Innovate/anaconda/bin/protoc
--   CXX flags             :  -Wno-deprecated -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY;CAFFE2_FORCE_FALLBACK_CUDA_MPI;CAFFE2_UNIQUE_LONG_TYPEMETA
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--     Python version      : 3.5.2
--     Python library      : /Users/Innovate/anaconda/lib/libpython3.5m.dylib
--   USE_CUDA              : ON
--     CUDA version        : 7.5
--   USE_CNMEM             : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--   USE_GFLAGS            : ON
--   USE_LMDB              : ON
--     LMDB version        : 0.9.14
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.12
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : ON
--   USE_NCCL              : OFF
--   USE_NNPACK            : OFF
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_GLOO              : OFF

Is there a specific version of clang needed to compile?

Thanks!

**Comment by hlzz** [comment]
see #318

**Comment by Yangqing** [comment]
(closing in favor of merging discussion to #318)
