### ISSUE TITLE
caffe2 in Raspberry pi3

### ISSUE THREAD

**Issue by YuehChuan** [facebookarchive/caffe2#325]
Hi, saw this attractive line "...Learn to train and deploy models for iOS, Android, and Raspberry Pi..", 
Wonder is there a kickoff tutorial for deploy caffe2 on Raspberry pi3.  Such as tensor flow on pi3 https://github.com/samjabrahams/tensorflow-on-raspberry-pi
And is it possible to to say what kind of applications it could reach? Once I found out, I'll post here too.
Thanks 😃

**Comment by pietern** [comment]
You can build Caffe2 on Raspbian (Debian for RaspberryPi), see [this page](https://caffe2.ai/docs/getting-started.html?platform=raspbian&configuration=compile).

If you end up writing a tutorial, please let us know :)
