### ISSUE TITLE
output of get_python_cmake_flags.py

### ISSUE THREAD

**Issue by kindloaf** [facebookarchive/caffe2#326]
Hi,
It seems that the following script is used to display compilation flags:
https://github.com/caffe2/caffe2/blob/master/scripts/get_python_cmake_flags.py
But it doesn't have any output.
Should there be a "print(flags)" at the end of the script?
Also, there are no spaces between the flags. Should we add spaces?

**Comment by Yangqing** [comment]
cc @bwasti for a look

**Comment by bwasti** [comment]
@kindloaf that is quite odd sorry, it seems an older and broken version of that script slipped in.  it has been fixed [here](https://github.com/caffe2/caffe2/commit/62830d613b8b3d6ac8f0bd60f1998992b7a1c853)

**Comment by kindloaf** [comment]
@bwasti Thanks for the fix!
