### ISSUE TITLE
speed_benchmark usage

### ISSUE THREAD

**Issue by kindloaf** [facebookarchive/caffe2#328]
Hi there,
I'm using speed_benchmark to test squeeze-net (from the model zoo) on Android. I copied the binary and the two .pb files into the device, and run the following:
```
adb shell 'cd /data/local/tmp; ./speed_benchmark --net predict_net.pb --init_net init_net.pb'
```
And I saw the following error:
```
Abort message: '[F tensor.h:595] Check failed: i < dims_.size() Exceeding ndim limit
```
The error happens around `ConvOp<T, Context>::RunOnDeviceWithOrderNCHW()`:
```
const int N = X.dim32(0), C = X.dim32(1);
```
The input tensor X has dimension (1,), although the expected dimensions should be [N, C, H, W].
I used the python API to run same .pb files and it worked fine.

Any advice?

**Comment by Yangqing** [comment]
Ah yeah, speed_benchmark requires you to explicitly initialize the input in the init_net.pb as well, which probably caused the issue. We have a mobile speed benchmark script that somehow got out of sync to the main repo. It's a small difference from the current speed benchmark:

https://gist.github.com/Yangqing/b9e4df1d0573734b3112bac259f2e3a0

Note that this is intended to test input as uint8 data, if your model takes in float, you will need to change line 43 to float.

**Comment by kindloaf** [comment]
@Yangqing Thanks for quick turnaround. It works now.
By the way, it seems that the changes are not specific to mobile - I assume it works for server as well.
