### ISSUE TITLE
Reinforcement learning examples

### ISSUE THREAD

**Issue by miguelgfierro** [facebookarchive/caffe2#330]
Are you going to introduce some examples of reinforcement learning? If yes, do you have an estimate on when you will add them?

**Comment by Yangqing** [comment]
We don't have any yet - right now the focus is to get the framework solid and performant. I think you should be able to construct RL logics in a high-level language - like Python / PyTorch - while calling Caffe2 for the neural network parts.

**Comment by miguelgfierro** [comment]
Thank you, will do
