### ISSUE TITLE
CNN Class [CNNModelHelper] misleading name.

### ISSUE THREAD

**Issue by cbalint13** [facebookarchive/caffe2#332]
Hi,

  Would not be better to rename ```CNNModelHelper``` to simply ```NNModelHelper```, whithout the ```C``` part meaning "convolutional"  ? It's misleading to have it with "convolutional" since it holds more than just convolution layers e.g. LSTM and others.

* The docs: http://caffe2.ai/docs/cnn.html

Thanks !

BTW, **caffe2** looks owesome, true masterpiece !

**Comment by harouwu** [comment]
Hi cbalint13,

Thanks for pointing out that. In fact, we totally agree with you on `CNNModelHelper` being misleading in naming. As you can see, `CNNModelHelper` now contains parameters, net protobuf and helper functions all in 1 class. It is a big model, with helper functions, and definitely not just CNN.

So, to make Caffe2 more flexible, we about to release a new change in API very soon. In this change, we will separate the concept of building operators from a model. We will introduce a new python module containing all helper functions to build ops(name not decided yet, maybe you can help us with that). At the same time, the `ModelHelperBase` and `CNNModelHelper` will be renamed. They will only contains net define and and parameters.

Hope this change will solve your concern. And please stay in touch with Caffe2 :)

Thanks

**Comment by futurely** [comment]
How soon? Do you have a planned release cycle or roadmap? For example, TensorFlow release every 1.5 months or so.

**Comment by harouwu** [comment]
Hi @futurely , Caffe2 is on a daily base sync. You will always have the latest version :)

**Comment by futurely** [comment]
new resnet building with brew https://github.com/caffe2/caffe2/commit/b0c463b644b958e30e4949d69ec5596004754a42
brew module in MNIST tutorial https://github.com/caffe2/caffe2/commit/6e560ee47eaa021539db9e4b20895bc1a6afc18c

**Comment by cbalint13** [comment]
@harouwu, 

Thank you for clarifications!  
Now we have Brew module: https://caffe2.ai/docs/brew.html
