### ISSUE TITLE
[need help] got error when compiling caffe2 in centos6.9 

### ISSUE THREAD

**Issue by sparrow0629** [facebookarchive/caffe2#335]
I compile caffe2 in centos 6.9 according to 
http://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud
what's more, I update gcc to 4.8.5
when I run "make -j8 install", i got this error:

[  7%] Built target benchmark
[  7%] Building CXX object third_party/benchmark/test/CMakeFiles/basic_test.dir/basic_test.cc.o
Linking CXX executable basic_test
../src/libbenchmark.so.0.0.0: undefined reference to `clock_gettime'

how can i solve this problem?

**Comment by Yangqing** [comment]
Seems that this is a bug in the benchmark framework - clock_gettime is from rt.

http://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim

You can disable building it with `-DBUILD_TEST=OFF`
