### ISSUE TITLE
cannot install ios version 

### ISSUE THREAD

**Issue by lgyStoic** [facebookarchive/caffe2#338]
execute  `./scripts/build_ios.sh`

but show that message 

caffe2/third_party/protobuf/cmake: is a directory

how to solve that problem

**Comment by Yangqing** [comment]
Did you do

`git submodule update --recursive`

?

**Comment by lun0522** [comment]
I encountered the same problem, and `git submodule update --recursive` did not solve it. But after executing
```
brew install \
automake \
cmake \
git \
glog \
protobuf
```
on Mac (according to [MacOS X install](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile)), `./scripts/build_ios.sh` works! Maybe `cmake` or something else is also required on Mac before we build the iOS version? @lgyStoic @Yangqing

**Comment by Yangqing** [comment]
Ah yeah, cmake is needed to build any version since it is our default build solution.

You won't need glog and protobuf - build_ios.sh will not need glog and protobuf is built from source.

**Comment by lgyStoic** [comment]
as @lun0522  method ,it works, thx
