### ISSUE TITLE
Caffe_translator.py Error

### ISSUE THREAD

**Issue by michaelholm-ce** [facebookarchive/caffe2#342]
Caffe2 build was successful, following instructions from the caffe2 website.

Command:  
`python ./build/caffe2/python/caffe_translator.py deploy.prototxt model.caffemodel`

Error:  
`[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:954] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
Aborted (core dumped)`

I have searched for clues on fixing this issue, but have not found any solutions.  Any help or advice appreciated.

**Comment by Yangqing** [comment]
Ah - do you have Caffe installed on the same machine? It might be that the protobuf source files of the installed Caffe and the Caffe2 version are diverging a bit.

**Comment by wiselylan** [comment]
I also got a translation error:

`KeyError: 'No translator registered for layer: name: "slice1"\ntype: "Slice"\nbottom: "conv1"\ntop: "slice1_1"\ntop: "slice1_2"\nslice_param {\n slice_dim: 1\n|\n yet. '`

I seems that slice layer is not in the python translator script.
How should I fix it? Thanks.

**Comment by michaelholm-ce** [comment]
@Yangqing Yes, I have caffe installed on the same machine and use it quite a lot.  I was installing caffe2 to see how its performance might compare with caffe in terms of execution speed and cpu usage, if any.  

Is there a way to fix this without me removing caffe?

**Comment by nyyznyyz1991** [comment]
@michaelholm-ce  @Yangqing 
I meet the same problem, i change the libprotobuf link about caffe and caffe2 from dynamic to static, and succeed !
Besides, you shouldn't do " import caffe"  in caffe2's python script, because you have set the caffe's python path before, so it will make computer confused

**Comment by aaronmarkham** [comment]
@wiselylan check out #589 

This issue seems to be protobuf related and is fixed as in @michaelholm-ce suggestion. Please re-open if this isn't the case.

**Comment by ShangxuanWu** [comment]
@nyyznyyz1991 still confused. Can you tell me how to change the protobuf link? Thanks!

**Comment by pyotr777** [comment]
I also had this error 
```
nvidia@tegra-ubuntu-2:~/caffe/models/bvlc_googlenet$ python -m caffe2.python.caffe_translator deploy.prototxt bvlc_googlenet.caffemodel
[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
Aborted (core dumped)
```

Caffe and Caffe2 installed on same machine.

Removing Caffe from PYTHONPATH environment variable fixed it for me.
```
export PYTHONPATH="/home/nvidia/caffe2/build"
```

**Comment by chronos-ctrl** [comment]
@michaelholm-ce did you manage to solve the problem of caffe2 and caffe conflict ? I'm getting the same error: 

[libprotobuf ERROR google/protobuf/descriptor_database.cc:110] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1275] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
Aborted (core dumped)

**Comment by ikoc** [comment]
I have the same problem with @wiselylan 
> KeyError: 'No translator registered for layer: name: "slice1"\ntype: "Slice"\nbottom: "conv1"\ntop: "slice1_1"\ntop: "slice1_2"\nslice_param {\n  slice_dim: 1\n}\n yet.'

I have only installed Caffe2 with following these decription
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile
So i think problem is not about diverging two framework.  I tried to upgrade protobuf version and reinstall Caffe2 but again not work. 

I didn't understand the solution which @nyyznyyz1991  gave, how can we do that in python
>  change the libprotobuf link about caffe and caffe2 from dynamic to static, and succeed !

What can i do to solve it?

**Comment by pradeephike** [comment]
I also got a translation error: @wiselylan @jamisawyer 

KeyError: 'No translator registered for layer: name: "mvn1"\ntype: "MVN

It seems that mvn layer is not in the python translator script.
How should I fix it? Thanks.

**Comment by Vinograduss** [comment]
@aminm2a I use caffe and caffe2 in my project  and I have the same problem:
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
Aborted (core dumped)
```

I fixed problem by modifying cmake file for caffe2.
Problem:
Caffe2 and Caffe uses the same file: caffe/proto/caffe.proto (in caffe2 it's a copy of file from caffe project)

Solution 
1) remove caffe_proto from caffe2, 
in file  /caffe2/CMakeLists.txt I changed line
-add_library(caffe2 ${Caffe2_CPU_SRCS} $<TARGET_OBJECTS:Caffe_PROTO> $<TARGET_OBJECTS:Caffe2_PROTO>)
+add_library(caffe2 ${Caffe2_CPU_SRCS} $<TARGET_OBJECTS:Caffe2_PROTO>)

2) add headers from caffe to caffe2
in file  /caffe2/CMakeLists.txt add line after  add_library(caffe2 ....) with path to caffe 
+target_include_directories(caffe2 PUBLIC "/opt/caffe/include/")

3) check that you link caffe library to your project (it was done before fix)

**Comment by blateyang** [comment]
@Vinograduss I meet the same problem. I try to use your solution but I want to confirm whether "/opt/caffe/include/" is the Caffe path in step 2. Besides, in step3, how to check that I have linked caffe library to my project? Can you explain it more clear? Thank you in advance!

**Comment by yibeihuang** [comment]
I had the same error but still did not find the answer. I tried to use the solutions from @Vinograduss but I didn't have caffe_proto in my caffe2 or any line with the keyword '{Caffe2_CPU_SRCS}' in CMakeLists.txt.
Has anyone found the solution? Many thanks.
