### ISSUE TITLE
is multi-model GPU training supported with python interface?

### ISSUE THREAD

**Issue by hondaathma** [facebookarchive/caffe2#345]
Can I split a single large caffe model in 2 GPUS?

**Comment by pietern** [comment]
Yes, you could try applying data parallelism. See http://caffe2.ai/docs/SynchronousSGD.html for more info.

**Comment by hondaathma** [comment]
@pietern ..Sorry I do not mean data parallelism.I am aware even experimental caffe v1 builds had those.

I am talking about model parallelism. For example a modified version of resnet152 is more than 12Gb for me(eg:- larger image size).I only have two 12GB GPUS...What I mean is I want to assign some parts of resnet152 to GPU1 and others to GPU2. Data parallelism will copy multiple versions of resnet152 to each GPU.Tensorflow supports assigning each layers to a separate layer.

I was wondering if that is supported in caffe 2?
