### ISSUE TITLE
python -m caffe2.python.operator_test.relu_op_test failed

### ISSUE THREAD

**Issue by dongshuhao** [facebookarchive/caffe2#346]
I compiled C2 on ubuntu 16.04, GCC 5.4.0, CUDA 8.0, cuDNN 5.1 successfully. However, I cannot  import caffe2.python.core. The error is very similiar to the issue "cannot import caffe2.python.core #197". Any hints about how to solve it?

**Comment by hiszpanski** [comment]
Check that your build directory is in your `PYTHONPATH`

**Comment by dongshuhao** [comment]
@thinkski Yes, it is in my PYTHONPATH. Thanks!

I figured out why I had the error. I used anaconda2/bin/python instead of /usr/bin/python.  If I use /usr/bin/python, then everything works. Is there any way I can build C2 with anaconda2? Thanks!

**Comment by Yangqing** [comment]
Interesting, anaconda does have a few tricky issues, could you paste the full error message?

**Comment by dongshuhao** [comment]
@Yangqing here is the error message:
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /opt/intel/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_sparse_d_csr__g_n_syrk_notr_row_struct_i8
CRITICAL:root:Cannot load caffe2.python. Error: /opt/intel/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_sparse_d_csr__g_n_syrk_notr_row_struct_i8

I built C2 with Eigen. Not sure the error messages related MKL

**Comment by Yangqing** [comment]
Hmm, interesting, I know that anaconda might be using MKL from numpy, I wonder if that causes conflicts. Does import numpy or import scipy work correctly?

Also, if you do `ldd build/caffe2/python/caffe2_pybind_state.so` and `ldd build/caffe2/libCaffe2_CPU.so` do you see MKL dependencies?

**Comment by dongshuhao** [comment]
Yes, I can import numpy and scipy normally.

in my build/caffe2/python, I do not have caffe2_pybind_state.so, I do have
caffe2_pybind11_state.so. It has mkl dependencies. The output is as follow:
libmkl_intel_lp64.so => /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
(0x00007f92844d8000)
libmkl_sequential.so => /opt/intel/mkl/lib/intel64/libmkl_sequential.so
(0x00007f928373f000)
libmkl_core.so => /opt/intel/mkl/lib/intel64/libmkl_core.so
(0x00007f9281c4c000)

The libCaffe2_CPU.so also has mkl dependencies.

**Comment by poodarchu** [comment]
I have the same problem, them I found solution here. https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/712495 @Yangqing @dongshuhao

**Comment by pjh5** [comment]
The Anaconda build instructions have changed significantly since this issue was created and should work with mkl fine. If you encounter any other problems on up-to-date Caffe2 then please open another issue.
