### ISSUE TITLE
make_mnist_db doesn't generate db files

### ISSUE THREAD

**Issue by yiwsun** [facebookarchive/caffe2#349]
When running tutorial MNIST.ipynb, the function GenerateDB() runs fine, no error reported but it did not generate files mnist-train-nchw-leveldb or mnist-test-nchw-leveldb.

While calling make_mnist_db directly from command line, it reported an error:
* *Caffe2 flag error: Cannot convert argument to bool: --db
Note that if you are passing in a bool flag, you need to explicitly specify it, like --arg=True or --arg True. Otherwise, the next argument may be inadvertently used as the argument, causing the above error.
Caffe2 flag: illegal argument: --channel_first*

Any thoughts how to fix it?

I am using Caffe2 on windows server 2016 with python2.7. Running tutorial Basics.ipynb works.

**Comment by aaronmarkham** [comment]
There's some output from the function that shows the binary command and params. Can you copy that here? I'm thinking file path issues...

**Comment by yiwsun** [comment]
Here is the output in the Jupyter notebook run:
Looks like you ran this before, so we need to cleanup those old workspace files...
DB name:  C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\mnist-train-nchw-leveldb
Creating database with:  C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\binaries\Release\make_mnist_db.exe --channel_first --db leveldb --image_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\train-images-idx3-ubyte --label_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\train-labels-idx1-ubyte --output_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\mnist-train-nchw-leveldb
DB name:  C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\mnist-test-nchw-leveldb
Creating database with:  C:\Users\sqlpythonadmin\Source\caffe2\build\caffe2\binaries\Release\make_mnist_db.exe --channel_first --db leveldb --image_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\t10k-images-idx3-ubyte --label_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\t10k-labels-idx1-ubyte --output_file C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist\mnist-test-nchw-leveldb
training data folder:C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_data\mnist
workspace root folder:C:\Users\sqlpythonadmin\Source\caffe2\caffe2\python\tutorials\tutorial_files\tutorial_mnist

**Comment by aaronmarkham** [comment]
Paths seem ok. 
Can you describe your build (pre-requisites and dependencies you installed) so I can try to replicate on a cloud server? 
Thanks!

**Comment by yiwsun** [comment]
Thank you Aaron for offering the help!
The OS is an Azure VM (Windows Server 2016 without GPU). Basically followed this tutorial: http://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile 
			ii. Install Anaconda 2 4.3.1 (Python 2.7)
			iii. Install VS 2017 Community
			iv. Install Cmake
			v. Install git for windows
			vi. Install caffe2
				1) Git clone
				2) Build-windows.bat
3) Copy caffe2_pybind11_state.pyd to C:\ProgramData\Anaconda2\DLLs
4) Add an env PYTHONPATH, reboot
vii. To make Basics.ipynb working:
			1) pip install protobuf
			2) pip install pydot, 
			3) Conda install graphviz,  
4) add C:\ProgramData\Anaconda2\Library\bin\graphviz to PATH, reboot

**Comment by yiwsun** [comment]
forgot to mention:
before vi, conda install -y numpy
after vii, conda install -y --channel https://conda.anaconda.org/willyd leveldb

**Comment by ghost** [comment]
Did you get any further with this? I got past the above error by adding 'True' after '--channel_first' like the error message suggests, however the program still crashes, this time without any useful error. Running through the code line by line, each of the 'CAFFE_ENFORCE' lines seems to cause a crash, but with these commented out it still crashes at 'std::unique_ptr<db::Transaction> transaction(mnist_db->NewTransaction());'

**Comment by yiwsun** [comment]
Unfortunately no. I was hoping Aaron could shed some light.

**Comment by ghost** [comment]
My problem was fixed by rebuilding caffe2 with leveldb support. The qdb branch (https://github.com/bureau14/leveldb) works on Windows.

**Comment by yiwsun** [comment]
@m00nkeh, thanks for the note. Could you elaborate how to build Boost specifying static libraries (the default is shared) and 64 bit if necessary (32 bit is default) ( I found these hints in your other posts)? I downloaded Boost 1.64, and was following instruction here https://codeyarns.com/2014/06/06/how-to-build-boost-using-visual-studio/ but it just hang at the compilation step forever. Besides, it doesn't mention how to build static libraries. 
Thanks!

**Comment by ghost** [comment]
When you run b2 you should use the arguments link=static and address-model=64. Boost is massive so takes a long time to compile, but leveldb should only need the libraries date_time, filesystem and system, so to save time building you could add the arguments --with-date_time --with-filesystem --with-system.

**Comment by yiwsun** [comment]
Thank you @m00nkeh . It turns out I have to manually add the path of cl.exe in the file project-config.jam, and then Boost can build. Now move on to leveldb, I downloaded qdb branch, run CMake then build leveldb with Visual Studio (Runtime Library is set to ‘Multi-Threaded(/MT)'. but it failed: 
```
2>Using the /RTC option without specifying a debug runtime will lead to linker errors
2>Hint: go to the code generation options and switch to one of the debugging runtimes
2>C:\Users\sqlpythonadmin\Source\boost_1_64_0\boost/config/auto_link.hpp(111): fatal error C1189: #error:  "Incompatible build options"
2>Generating Code...
2>Done building project "leveldb.vcxproj" -- FAILED.
```
Any suggestion how to fix it?

**Comment by yiwsun** [comment]
Never mind. Should select "release" instead of "debug" when build leveldb in VS.

**Comment by yiwsun** [comment]
Thank you @m00nkeh . Could you elaborate how to build Caffe2 with leveldb? I set   -DUSE_LEVELDB=ON in script\build_windows.bat. but when running it, it still shows:
--   USE_LEVELDB           : OFF

**Comment by ghost** [comment]
You need to provide values for levelDB_INCLUDE and levelDB_LIBRARY. You also need to install Snappy and provide its include and lib paths. It might be easier to use the CMake GUI, I had lots of problems with build_windows.bat.

**Comment by cgpoh** [comment]
I added LEVELDB_ROOT and SNAPPY_ROOT_DIR in my environment variables to point to the respective directories and modified FindSnappy.cmake to call $ENV{SNAPPY_ROOT_DIR} instead of ${SNAPPY_ROOT_DIR}. I did the same for both GFlags and GLog and managed to build caffe2 successfully.

**Comment by yiwsun** [comment]
Thank you @cgpoh ! Your approach makes caffe2's build recognize leveldb's path, but when running build_windows.bat, it reports another error:
fatal error LNK1104: cannot open file 'libboost_filesystem-vc141-mt-s-1_64.lib'
Although the file is in the boost\stage\lib directory. Any thoughts?

**Comment by cgpoh** [comment]
I have to add BOOST_ALL_NO_LIB preprocessor to leveldb project and add the required boost libraries in Linker-> input -> Additional Dependencies.

By the way, I didn't use glog as it gives me another set of problem and by skipping glog, I don't know whether it causes caffe2.python unable to load problem. I'm trying to switch to Anaconda to see whether it works. It's really difficult to build in windows.

**Comment by cgpoh** [comment]
@yiwsun Below are the steps that I follow to build successfully on Windows, see whether it helps you

- Follow the steps on [caffe2 installation](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) but with some modifications.

- Initially, I tried going the regular python install way but failed to get caffe2 working and so I removed my python installation and installed Anaconda 2 instead.

- After installing Anaconda 2, follow the [Anaconda install](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) but install more packages by using the following command:
`conda install -y --channel https://conda.anaconda.org/conda-forge  graphviz hypothesis numpy pydot-ng python-lmdb requests zeromq future gflags protobuf=3.2.0`

- For leveldb, modified the leveldb visual studio project to disable Boost auto linking by defining the preprocessor symbol
`BOOST_ALL_NO_LIB`
and add the following libraries (your version may be different from mine) in Librarian->General->Additional Dependencies
`libboost_date_time-vc140-mt-s-1_59.lib`
`libboost_filesystem-vc140-mt-s-1_59.lib`
`libboost_system-vc140-mt-s-1_59.lib`

- I have to modify FindSnappy.cmake and FindGFlags.cmake in order for CMake to work and also add `GFLAGS_ROOT_DIR` and `SNAPPY_ROOT_DIR` to Windows environment variables.
FindSnappy.cmake modification:
```
# Find the Snappy libraries
#
# The following variables are optionally searched for defaults
#  SNAPPY_ROOT_DIR:    Base directory where all Snappy components are found
#
# The following are set after configuration is done:
#  SNAPPY_FOUND
#  Snappy_INCLUDE_DIR
#  Snappy_LIBRARIES

find_path(Snappy_INCLUDE_DIR NAMES snappy.h
                             PATHS $ENV{SNAPPY_ROOT_DIR} $ENV{SNAPPY_ROOT_DIR}/include)

find_library(Snappy_LIBRARIES NAMES snappy64
                              PATHS $ENV{SNAPPY_ROOT_DIR} $ENV{SNAPPY_ROOT_DIR}/lib)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Snappy DEFAULT_MSG Snappy_INCLUDE_DIR Snappy_LIBRARIES)

if(SNAPPY_FOUND)
  message(STATUS "Found Snappy  (include: ${Snappy_INCLUDE_DIR}, library: ${Snappy_LIBRARIES})")
  mark_as_advanced(Snappy_INCLUDE_DIR Snappy_LIBRARIES)
  caffe_parse_header(${Snappy_INCLUDE_DIR}/snappy-stubs-public.h
                     SNAPPY_VERION_LINES SNAPPY_MAJOR SNAPPY_MINOR SNAPPY_PATCHLEVEL)
  set(Snappy_VERSION "${SNAPPY_MAJOR}.${SNAPPY_MINOR}.${SNAPPY_PATCHLEVEL}")
endif()
```
and FindGFlags.cmake modification:
```
# - Try to find GFLAGS
#
# The following variables are optionally searched for defaults
#  GFLAGS_ROOT_DIR:            Base directory where all GFLAGS components are found
#
# The following are set after configuration is done:
#  GFLAGS_FOUND
#  GFLAGS_INCLUDE_DIRS
#  GFLAGS_LIBRARIES
#  GFLAGS_LIBRARYRARY_DIRS

include(FindPackageHandleStandardArgs)

#set(GFLAGS_ROOT_DIR "" CACHE PATH "Folder contains Gflags")

# We are testing only a couple of files in the include directories
if(WIN32)
    find_path(GFLAGS_INCLUDE_DIR gflags/gflags.h
        PATHS $ENV{GFLAGS_ROOT_DIR})
else()
    find_path(GFLAGS_INCLUDE_DIR gflags/gflags.h
        PATHS $ENV{GFLAGS_ROOT_DIR})
endif()

if(MSVC)
    find_library(GFLAGS_LIBRARY_RELEASE
        NAMES gflags
        PATHS $ENV{GFLAGS_ROOT_DIR}
        PATH_SUFFIXES Lib)

    find_library(GFLAGS_LIBRARY_DEBUG
        NAMES gflagsd
        PATHS $ENV{GFLAGS_ROOT_DIR}
        PATH_SUFFIXES Lib)

    set(GFLAGS_LIBRARY optimized ${GFLAGS_LIBRARY_RELEASE} debug ${GFLAGS_LIBRARY_DEBUG})
else()
    find_library(GFLAGS_LIBRARY gflags)
endif()

find_package_handle_standard_args(GFlags DEFAULT_MSG GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)


if(GFLAGS_FOUND)
    set(GFLAGS_INCLUDE_DIRS ${GFLAGS_INCLUDE_DIR})
    set(GFLAGS_LIBRARIES ${GFLAGS_LIBRARY})
    message(STATUS "Found gflags  (include: ${GFLAGS_INCLUDE_DIR}, library: ${GFLAGS_LIBRARY})")
    mark_as_advanced(GFLAGS_LIBRARY_DEBUG GFLAGS_LIBRARY_RELEASE
                     GFLAGS_LIBRARY GFLAGS_INCLUDE_DIR GFLAGS_ROOT_DIR)
endif()
```
- Run `build_windows.bat` and once it build successfully, remember to set `PYTHONPATH` to your caffe2 build directory in the Windows environment variable.

I hope it helps :)

**Comment by yiwsun** [comment]
Thank you @cgpoh this is really helpful. Now build Caffe2 works smooth. But when I launch Jupyter Notebook for even the basics.ipnb tutorial, it failed. It keeps telling me "i cannot find a kernel matching Python 2". I did copy caffe2_pybind11_state.pyb to my python path (it is Python 3.5 not 2) and added PYTHONPATH. Previously without installing leveldb, the basics tutorial used to work. Any thoughts?

**Comment by ghost** [comment]
I don't think it should work with Python 3.5, as far as I know, Caffe2 requires Python 2, so I'm not sure how it worked before.

**Comment by yiwsun** [comment]
The db can be generated now, but when train the model workspace.CreateNet(train_model.net), it failed with an error:
[operator_schema.cc:65] Input index 0 (iter) and output idx 0 (mnist_train/Iter) are not in-place but should be as required by op Iter
what's causing the error?

**Comment by yiwsun** [comment]
Managed to get the tutorial working. Thank you all!

**Comment by cgpoh** [comment]
Hi @m00nkeh, possible to share the URL for Snappy? I'm using this [link](https://snappy.machinezoo.com/) and I'm having problem with the db conversion 
`Caffe2 flag error: Cannot convert argument to bool: --db
Note that if you are passing in a bool flag, you need to explicitly specify it, like --arg=True or --arg True. Otherwise, the next argument may be inadvertently used as the argument, causing the above error.
Caffe2 flag: illegal argument: --channel_first`

**Comment by ghost** [comment]
I used the zip file from the Bitbucket here: https://bitbucket.org/robertvazan/snappy-visual-cpp/downloads/

However I don't think the problem you're having relates to that; I had the same error and fixed it by changing the line `...make_mnist_db --channel_first --db leveldb...` to `...make_mnist_db --channel_first True --db leveldb...`

**Comment by cgpoh** [comment]
@m00nkeh I still can't get it to work even after adding "True" and rebuilding caffe2. There's no error output and I can't tell what went wrong. I have the `mnist-test-nchw-leveldb` folder created with 3 empty files (`LOG`, `LOCK `and `LOG.old`) and from ProcessMonitor, the process exit with `exit status: -1073741819`

**Comment by ghost** [comment]
Is there any output from Jupyter Notebook in the command window you launched it from? Have you changed the syscall line to the correct location of the make_mnist_db executable? ie "/usr/local/binaries/make_mnist_db" changed to something like "C:/caffe2/build/binaries/make_mnist_db.exe" (for example)

**Comment by cgpoh** [comment]
I have no output in the command window and I have changed the syscall line to call the correct make_mnist_db.exe. I can see the make_mnist_db process window pop up and stop responding after few seconds (the usual app not responding windows prompt asking whether you want to debug or close the program).

**Comment by QinZiwen** [comment]
@m00nkeh After "sudo make install ", there is no the "binaries" folder in "/usr/local/"

**Comment by aostruszka** [comment]
What are up to date build/installation instructions on Ubuntu 16.04?
I'm asking since I've built caffe2 from source (following official instructions) with CUDA support.  After couple attempts I've managed to have it working (the suggested ReLU test passes without any problems) and now I wanted to run this mnist tutorial but ... make_mnist_db is not installed (which is not a problem) but the version built in "build" directory crashes:
```
$ ../caffe2/build/caffe2/binaries/binaries/make_mnist_db --channel_first --db leveld --image_file train-images-idx3-ubyte --label_file train-labels-idx1-ubyte --output_file mnist-train-nchw-leveldb 
*** Aborted at 1497891458 (unix time) try "date -d @1497891458" if you are using GNU date ***
PC: @           0x404774 caffe2::convert_dataset()
*** SIGSEGV (@0x0) received by PID 4438 (TID 0x7fc41abdab00) from PID 0; stack trace: ***
    @     0x7fc418f954b0 (unknown)
    @           0x404774 caffe2::convert_dataset()
    @           0x4036ee main
    @     0x7fc418f80830 __libc_start_main
    @           0x403729 _start
    @                0x0 (unknown)
zsh: segmentation fault (core dumped)  ../caffe2/build/caffe2/binaries/binaries/make_mnist_db --channel_first --db  
```
Is this a known issue?

**Comment by aaronmarkham** [comment]
@QinZiwen you are correct. There was a recent change that moved the installation directory away from `/usr/local/binaries` to `/usr/local/bin` instead. Installation and builds don't remove anything from /usr/local/... so if you had a build of Caffe2 prior to this update, these binaries would exist in both places.

So, @aostruszka in the meantime you can update the mnist tutorial code to point to the location where the binaries are now installed. I'll loop around and fix any references to the old installation folder.

**Comment by aaronmarkham** [comment]
I'm going to close this since I think the original issue was really around how to build Caffe2 with LevelDB support on Windows and the earlier responses seem to have solved that issue.

The followup issue was related to the binaries location moving to /bin, and I've updated the IPython notebooks accordingly with #836.

**Comment by LaurentBerger** [comment]
I have got same issue : 

> Caffe2 flag error: Cannot convert argument to bool: --db
> Note that if you are passing in a bool flag, you need to explicitly specify it, like --arg=True or --arg True. Otherwise, the next argument may be inadvertently used as the argument, causing the above error.
> Caffe2 flag: illegal argument: --channel_first

In debug I can see that program is looking for  one argument with --channel_first and argument is next argv[] : it is --db
I insert an argument after --channel_first : 
`--channel_first 0 --db leveldb --image_file G:\Lib\caffe\data\mnist\train-images-idx3-ubyte --label_file G:\Lib\caffe\data\mnist\train-labels-idx1-ubyte --output_file mnist-train-nchw-leveldb `
and program run and create a folder mnist-train-nchw-leveldb

![image](https://user-images.githubusercontent.com/3591626/34447192-eabb21b2-ece1-11e7-80bb-3d10b0a81bbe.png)

May be it is good... I am a newbie in deep learning and caffe2
