### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lunasdejavu** [facebookarchive/caffe2#350]
I installed it from source under ubuntu 16.04 
Cuda compilation tools, release 8.0, V8.0.61
cuDNN v5.1
python 2.7

then my computer crashed when the setup was still going, but i didn't do other work ate the same time.
then I did "make clean" delete the folder caffe2 and it showed the message like this
[ 75%] Linking CXX executable binaries/print_core_object_sizes
make[3]: Leaving directory '/home/lunasdejavu/caffe2/build'
[ 75%] Built target print_core_object_sizes
make[3]: Entering directory '/home/lunasdejavu/caffe2/build'
Scanning dependencies of target inspect_gpus
make[3]: Leaving directory '/home/lunasdejavu/caffe2/build'
make[3]: Entering directory '/home/lunasdejavu/caffe2/build'
[ 75%] Building CXX object caffe2/CMakeFiles/inspect_gpus.dir/binaries/inspect_gpus.cc.o
[ 75%] Linking CXX executable binaries/inspect_gpus
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
libCaffe2_GPU.so: undefined reference to `google::protobuf::MessageLite::SerializeAsString[abi:cxx11]() const'
libCaffe2_CPU.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
libCaffe2_GPU.so: undefined reference to `google::protobuf::Message::ShortDebugString[abi:cxx11]() const'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
libCaffe2_GPU.so: undefined reference to `google::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libCaffe2_GPU.so: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libCaffe2_CPU.so: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
libCaffe2_CPU.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
libCaffe2_GPU.so: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
libCaffe2_CPU.so: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
libCaffe2_GPU.so: undefined reference to `google::protobuf::TextFormat::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Message*)'
libCaffe2_CPU.so: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
libCaffe2_CPU.so: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/inspect_gpus.dir/build.make:136: recipe for target 'caffe2/binaries/inspect_gpus' failed
make[3]: *** [caffe2/binaries/inspect_gpus] Error 1
make[3]: Leaving directory '/home/lunasdejavu/caffe2/build'
CMakeFiles/Makefile2:1529: recipe for target 'caffe2/CMakeFiles/inspect_gpus.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/inspect_gpus.dir/all] Error 2
make[2]: Leaving directory '/home/lunasdejavu/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lunasdejavu/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
can someone help me please?

**Comment by Yangqing** [comment]
Hmm, try removing the build folder completely and redo the build?

**Comment by pectinid16** [comment]
I am building on Ubuntu 16.04 using Cuda 8.0 and meet the same errors.

**Comment by blefaudeux** [comment]
Same here, Ubuntu 16.10 and Cuda 8. Looks like protobuf needs to be built and installed beforehand (see the third-party folder, and [protobuf build instructions](https://github.com/google/protobuf/blob/master/src/README.md)).
Edit: I'm guessing that you'll need to build protobuf with GCC4.8 beforehand, pre-built binary that you may have got otherwise are probably not ABI-compatible if built with a more recent GCC -> linker error
Edit2: confirmed, works (although the same needs to be done for rocksdb, leveldb, etc..)

**Comment by aaronmarkham** [comment]
You might find some help from these protobuf-related scripts in [/caffe2/scripts/](https://github.com/caffe2/caffe2/tree/master/scripts):
* [build_host_protoc.sh](https://github.com/caffe2/caffe2/blob/master/scripts/build_host_protoc.sh)
* [diagnose_protobuf.py](https://github.com/caffe2/caffe2/blob/master/scripts/diagnose_protobuf.py)

**Comment by lccurious** [comment]
Same here, Ubuntu 16.04. Looks like if using anaconda you could copy libprotobuf.so etc into anaconda lib folder for solving protobuf error.

**Comment by go-bears** [comment]
Ubuntu 16.04
CUDNN 5.1
CUDA 8.0
Trying to install in an Anaconda environment set to python 2.7

I'm having similar installation problems. Installing protobuf from google went a long way, and i checked that anaconda lib in the caffe2 env has libprotobufl.so files (it does). I've deleted and redone the build. And the build is still dying on inspect_gpus

![image](https://cloud.githubusercontent.com/assets/6887377/25553743/b8373bcc-2c70-11e7-8aac-443eb4d7f6b5.png)



Here's the summary from the make command
![image](https://cloud.githubusercontent.com/assets/6887377/25553762/1f517a8e-2c71-11e7-8b81-f4f1976fcac1.png)


Thanks for any guidance you can share!

**Comment by jwatte** [comment]
It looks like building with gcc5 doesn't work yet, because somehow protobuf builds with gcc4 compatible ABI, even if you build it yourself.

**Comment by Yangqing** [comment]
This is probably due to the fact that you are using a newer version of gcc and linking with an older version of library. Try compile with additional flag -D_GLIBCXX_USE_CXX11_ABI=0 and see if it fixes your issue. For more details, see here:

https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by jwatte** [comment]
But that shouldn't matter, because the default build scripts build protobuf as bundled with the caffe2 code.
However, the build scripts then are configured to use the protoc executable it builds, but pick up the system protocol buffer libraries. The system protocol buffer libraries are in turn a dependency of the system shell on modern Ubuntu, and thus if you install the protocol buffer libraries built by caffe2, your Linux GUI breaks.
A better solution is to remove the protobuf build from the build script, and also remove the define for what protoc executable to use when calling cmake. Make sure you have protocol (and the development libs/tools) installed for your system and then build.

**Comment by pjh5** [comment]
I will move this discussion to #1980
