### ISSUE TITLE
Python Import caffe2.python.core failed

### ISSUE THREAD

**Issue by yoershine** [facebookarchive/caffe2#353]
I try to import caffe2 module in python, but there is a error. Here is the error code.

----> 1 import caffe2.python.core

/usr/local/caffe2/python/core.py in <module>()
      9 from collections import OrderedDict
     10 
---> 11 from caffe2.proto import caffe2_pb2
     12 from collections import defaultdict
     13 from caffe2.python import scope, utils, workspace

/usr/local/caffe2/proto/caffe2_pb2.py in <module>()
     21   package='caffe2',
     22   syntax='proto2',
---> 23   serialized_pb=_b('\n\x19\x63\x61\x66\x66\x65\x32/proto/caffe2.proto\x12\x06\x63\x61\x66\x66...
    24 )     
    25 _sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeError: __init__() got an unexpected keyword argument 'syntax

And I try the verified command : python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure". It returns "Failure". 

My system is ubuntu16.04, I follows the install tutorials step by step. How to fix this error?

**Comment by Yangqing** [comment]
It looks like a protobuf versioning difference. Could you run `scripts/diagnose_protobuf.py` and see if the versions match?

**Comment by yoershine** [comment]
The protobuf is indeed mismatch in my system. It seems that  the version of protobuf is v2.6.1, which is installed by  command "sudo apt-get install  libprotobuf-dev protobuf-compiler ".  And the version of python protobuf is v3.2.0, installed by command "pip install protobuf". I have compiled protobuf from source, hope it works!

Thanks for your great work.

**Comment by Yangqing** [comment]
Glad it worked!
