### ISSUE TITLE
Link Not found on Website

### ISSUE THREAD

**Issue by tarunjainsagar** [facebookarchive/caffe2#355]
On Page : https://caffe2.ai/docs/workspace.html

In Example Usage, On Line : For more examples of the basics of workspaces, check out the **basics tutorial.**

Link pointed by **basic tutorial** is not found. It redirects to following url : https://caffe2.ai/tutorials/basics.ipynb

**Comment by Yangqing** [comment]
Ah sorry this is a runaway link:

https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Basics.ipynb

/cc @aaronmarkham

**Comment by tarunjainsagar** [comment]
Please also update this link in Tutorial at : http://caffe2.ai/docs/tutorials.html#null__models-and-datasets---a-primer

Beginners#
`Models and Datasets - a Primer` - redirects to  Page NOT found at https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Models_and_Datasets.ipynb

**Comment by tarunjainsagar** [comment]
Also update **LAST LINE** at this page: `http://caffe2.ai/docs/tutorials.html`

When your browser opens with your local Jupyter server (default is http://localhost:8888), browse to the Caffe2 repository and look for them in the **tutorials directory**. Opening them this way will launch their interactive features.

redirects to Page Not found : `https://caffe2.ai/tutorials`

**Comment by aaronmarkham** [comment]
Updated. Thanks!
