### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by rachitgarg91** [facebookarchive/caffe2#356]
Hello,
The build seems to be failing on Mac OS. Here is the log. 

Scanning dependencies of target convert_caffe_image_db
[ 78%] Building CXX object caffe2/CMakeFiles/convert_caffe_image_db.dir/binaries/convert_caffe_image_db.cc.o
[ 79%] Linking CXX executable binaries/convert_caffe_image_db
[ 79%] Built target convert_caffe_image_db
Scanning dependencies of target caffe2_pybind11_state
[ 79%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
/Users/Innovate/caffe2/caffe2/python/pybind_state.cc:202:13: error: use of undeclared identifier 'PyString_AsString'
            PyString_AsString(trace_vec[i]->tb_frame->f_code->co_filename);
            ^
/Users/Innovate/caffe2/caffe2/python/pybind_state.cc:204:13: error: use of undeclared identifier 'PyString_AsString'
            PyString_AsString(trace_vec[i]->tb_frame->f_code->co_name);
            ^
/Users/Innovate/caffe2/caffe2/python/pybind_state.cc:322:17: error: use of undeclared identifier 'PyString_Check'; did you mean 'PyMapping_Check'?
            if (PyString_Check(arg.ptr())) { // string
                ^~~~~~~~~~~~~~
                PyMapping_Check
/Users/Innovate/anaconda/include/python3.5m/abstract.h:1152:22: note: 'PyMapping_Check' declared here
     PyAPI_FUNC(int) PyMapping_Check(PyObject *o);
                     ^
/Users/Innovate/caffe2/caffe2/python/pybind_state.cc:824:13: error: use of undeclared identifier 'PyString_Check'; did you mean 'PyMapping_Check'?
        if (PyString_Check(arg.ptr())) { // string
            ^~~~~~~~~~~~~~
            PyMapping_Check
/Users/Innovate/anaconda/include/python3.5m/abstract.h:1152:22: note: 'PyMapping_Check' declared here
     PyAPI_FUNC(int) PyMapping_Check(PyObject *o);
                     ^
/Users/Innovate/caffe2/caffe2/python/pybind_state.cc:889:2: warning: "Compiling without AVX2. Please consider upgrading your version of Clang." [-W#warnings]

The version of clang is:
>clang --version
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Thanks,
Rachit Garg

**Comment by Yangqing** [comment]
This seems to be a python 3 support issue - we are on our way to supporting python 3. Please check #315 for updates.
