### ISSUE TITLE
Can't show the network structure with "display.Image(graph.create_png(), width=800)"

### ISSUE THREAD

**Issue by issac8huxley** [facebookarchive/caffe2#358]
I test the Toy Regression tutorials, but there is no figure of network structure when I input following sentence:

graph = net_drawer.GetPydotGraph(train_net.Proto().op, "train", rankdir="LR")
display.Image(graph.create_png(), width=800)

**Comment by Yangqing** [comment]
Is there some ipython error message? If not, it might be an matplotlib issue as well.

I wonder if setting `%matplotlib inline` helps in this case.

Also see this: http://stackoverflow.com/questions/35145509/why-is-ipython-display-image-not-showing-in-output

**Comment by Yangqing** [comment]
Similar to #381 ? Closing for now, feel free to reopen.
