### ISSUE TITLE
Build error on ubuntu 14.04 

### ISSUE THREAD

**Issue by silrep2** [facebookarchive/caffe2#359]
Hi everyone, I want to compile Caffe2 on OdroidXu4 board. I followed [https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile](url) to compile source code but meet some errors.
This is my system info:
Linux odroid 3.10.69 #1 SMP PREEMPT  armv7l armv7l armv7l GNU/Linux

I have installed all Required Dependencies, some Optional Dependencies(for example I can't find  libiomp-dev)
Then I use make. while 27%, errors occurred.
It seems somethings wrong with std::max. I am using gcc version 4.8.2 (Ubuntu/Linaro 4.8.2-19ubuntu1). Should I choose another version of gcc?
Thanks a lot.

_In file included from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:5:0:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h: In constructor ‘gloo::AllreduceRingChunked<T>::AllreduceRingChunked(const std::shared_ptr<gloo::Context>&, const std::vector<T*>&, int, const gloo::ReductionFunction<T>*)’:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: **error: no matching function for call to ‘max(const long unsigned int&, std::size_t)’
     chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);**
                                                                    ^
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: note: candidates are:
In file included from /usr/include/c++/4.8/algorithm:61:0,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.h:3,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note:   template argument deduction/substitution failed:
In file included from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:5:0:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::size_t {aka unsigned int}’)
     chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);
                                                                    ^
In file included from /usr/include/c++/4.8/algorithm:61:0,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.h:3,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note:   template argument deduction/substitution failed:
In file included from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:5:0:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::size_t {aka unsigned int}’)
     chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);
                                                                    ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.h:3,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:1:
/usr/include/c++/4.8/bits/stl_algo.h:4231:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4231:5: note:   template argument deduction/substitution failed:
In file included from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:5:0:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
     chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);
                                                                    ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.h:3,
                 from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:1:
/usr/include/c++/4.8/bits/stl_algo.h:4236:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4236:5: note:   template argument deduction/substitution failed:
In file included from /home/odroid/zxz/3rdparty/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:5:0:
/home/odroid/zxz/3rdparty/caffe2/third_party/gloo/gloo/allreduce_ring_chunked.h:38:68: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
     chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);
                                                                    ^
make[3]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/allreduce_ops.cc.o] Error 1
make[3]: Leaving directory `/home/odroid/zxz/3rdparty/caffe2/build'
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make[2]: Leaving directory `/home/odroid/zxz/3rdparty/caffe2/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/odroid/zxz/3rdparty/caffe2/build'
make: *** [all] Error 2_

**Comment by silrep2** [comment]
I changed 
```
chunkSize_ = std::max(minSize, (count_ + chunks_ - 1) / chunks_);

//to

chunkSize_ = std::max(minSize, static_cast<unsigned long>((count_ + chunks_ - 1) / chunks_));
```
seems fix the build error.

**Comment by bwasti** [comment]
This is an error within the gloo framework.  I'll open the issue there for you and close this one. https://github.com/facebookincubator/gloo/issues/28

**Comment by pietern** [comment]
This is an error because you're using a 32 bit system. We only run our continuous builds for 64 bit.

That said, we can probably disable compiling Gloo altogether if you're on 32 bit.

You can "fix" this by disabling Gloo by passing the USE_GLOO=OFF option to CMake.
