### ISSUE TITLE
Cannot run multi-node with MPI (with GPUs on 2 different machine)

### ISSUE THREAD

**Issue by ambujpd** [facebookarchive/caffe2#360]
Hi, 

I'm unable to run the Resnet50 model on 2 machines with GPUs. I'm successfully able to train on single machine having 2 GPUs.

Command:
`mpirun -n 1 -host 172.17.27.12 python resnet50_trainer.py --train_data=<PATH> --num_shards=2 --shard_id=0  --file_store_path=<PATH_NFS> : -n 1 -host 172.17.27.13 python resnet50_trainer.py --train_data=<PATH> --num_shards=2 --shard_id=1 --file_store_path=<PATH_NFS>`

I'm receiving the following error:
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1499968
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
**WARNING:data_parallel_model:Distributed computed params all-reduce not implemented yet**
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Add initial parameter sync
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger optimization took 0.0126869678497 secs
Traceback (most recent call last):
  File "resnet50_trainer.py", line 390, in <module>
    main()
  File "resnet50_trainer.py", line 386, in main
    Train(args)
  File "resnet50_trainer.py", line 310, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/nfs/AMBUJ/Caffe2/caffe2/build/caffe2/python/workspace.py", line 161, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
**RuntimeError: [enforce fail at /nfs/AMBUJ/Caffe2/caffe2/third_party/gloo/gloo/transport/tcp/device.cc:109] ifa != nullptr. Unable to find interface for: [127.0.1.1]**

What is the correct way to launch multi-node training with GPUs on different machines? Caffe2 uses Gloo internally which can be run using MPI.

@pietern Can you please help?

**Comment by ambujpd** [comment]
I figured that this could be a hostname error (https://github.com/facebookincubator/gloo/issues/26). 

After updating the hostname to IP address I'm facing a different error: 

```
Traceback (most recent call last):
  File "resnet50_trainer.py", line 390, in <module>
    main()
  File "resnet50_trainer.py", line 386, in main
    Train(args)
  File "resnet50_trainer.py", line 310, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/nfs/AMBUJ/Caffe2/caffe2/build/caffe2/python/workspace.py", line 161, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at /nfs/AMBUJ/Caffe2/caffe2/third_party/gloo/gloo/rendezvous/store.h:38] false. Store::wait() does not support timeout
```

UPDATE: This should be rectified by https://github.com/facebookincubator/gloo/commit/7805ac9098c7477447f45071b86a545042d89079

**Comment by ambujpd** [comment]
The earlier issue was resolved by using the latest commit on store.h file. The GIT submodule linked for Gloo in Caffe2 is older.

Resolving previous error has landed me to this:
```
...
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger optimization took 0.0133321285248 secs
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /nfs/AMBUJ/Caffe2_LatestGLOO/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:498] optval == 0. 111 vs 0. SO_ERROR: Connection refused
*** Aborted at 1493048200 (unix time) try "date -d @1493048200" if you are using GNU date ***
PC: @     0x7f7631f41c37 (unknown)
*** SIGABRT (@0x3f000000bfe) received by PID 3070 (TID 0x7f75417ef700) from PID 3070; stack trace: ***
    @     0x7f76322e3330 (unknown)
    @     0x7f7631f41c37 (unknown)
    @     0x7f7631f45028 (unknown)
    @     0x7f75c1743535 (unknown)
    @     0x7f75c17416d6 (unknown)
    @     0x7f75c1741703 (unknown)
    @     0x7f75c1794af5 (unknown)
    @     0x7f76322db184 start_thread
    @     0x7f7632008bed (unknown)
    @                0x0 (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 3070 on node 172.17.27.13 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
Why is the connection getting refused? Sample MPI applications work on these two nodes.

**Comment by Yangqing** [comment]
@pietern is this a known issue possibly? Maybe we can have a simply diagnosis util script?

@talk2ap001 this looks related: http://stackoverflow.com/questions/2558801/i-o-errorsocket-error-errno-111-connection-refused

**Comment by ambujpd** [comment]
@pietern @Yangqing 

The **test_cuda** sample provided with gloo also gives me the same error occasionally, when run multiple times. (Running on 1 machine with 2 GPUs)
```
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/sayantan/gloo_GIT/gloo/gloo/transport/tcp/pair.cc:498] optval == 0. 111 vs 0. SO_ERROR: Connection refused
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 29013 on node 172.17.27.12 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
Alternatively, I get this error at times:
```
unknown file: Failure
C++ exception with description "[/home/sayantan/gloo_GIT/gloo/gloo/transport/tcp/pair.cc:135] bind: Address already in use" thrown in the test body.
[mAllreduceHalvingDoublingPipelined/CudaAllreduceTest.MultiPointerAsync/14, where GetParam() = (32, 64, 32-byte object <80-C9 28-03 00-00 00-00 B8-EA 2A-03 00-00 00-00 D0-BA 4B-00 00-00 00-00 60-B8 4B-00 00-00 00-00>)
```
And at times it succeeds.

Log files:
[Failure_1node_1.txt](https://github.com/caffe2/caffe2/files/954811/Failure_1node_1.txt)
[Failure_1node_2.txt](https://github.com/caffe2/caffe2/files/954812/Failure_1node_2.txt)
[Failure_1node_3.txt](https://github.com/caffe2/caffe2/files/954813/Failure_1node_3.txt)

UPDATED:
[Stacktrace_GDB.txt](https://github.com/caffe2/caffe2/files/958173/Stacktrace_GDB.txt)

**Comment by pietern** [comment]
Hi @talk2ap001, thanks for bringing up this issue.

While Gloo has _some_ support for being run through MPI, it's not all the way wired up. Looking at the command you're running, it looks like you're already specifying a path to a shared filesystem for trainer rendezvous. And I think you're only using mpirun to launch the processes, nothing else, right?

The warning you see about "Distributed computed params all-reduce not implemented yet" is benign, though it may have to be implemented at some point (cc @akyrola).

For the connection refused error, do you happen to have a firewall enabled on these machines? For example, Ubuntu uses ufw, which is may or may not enable by default...

**Comment by ambujpd** [comment]
Hi @pietern. Yes, I'm already specifying the shared path for rendezvous and mpirun is just intended to launch the process. In fact the resnet50_trainer.py script is unchanged.

There is no firewall enabled on any of these machines. And I checked the status of ufw and its says _inactive_.

On the side, is there any support or plan to use MPI altogether in Caffe2 for distributed training in place of gloo, and/or giving an option against gloo?

Also, if you could help, how else can I correctly train a model, say resnet50_trainer.py on 2 different machines without MPI. I didn't find any example or tutorial that explains training on different _machines_ on Caffe2 's website. That would be very helpful as scaling is an essential necessity. CC @Yangqing

**Comment by ambujpd** [comment]
With latest Gloo and Caffe2, I'm now getting one of these two errors, every time, when run through mpirun (command same as previous):

```
...
INFO:memonger:Memonger memory optimization took 0.0139429569244 secs
Traceback (most recent call last):
  File "resnet50_trainer.py", line 395, in <module>
    main()
  File "resnet50_trainer.py", line 391, in main
    Train(args)
  File "resnet50_trainer.py", line 315, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/nfs/AMBUJ/Caffe2_LatestGLOO2/caffe2/build/caffe2/python/workspace.py", line 161, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [/nfs/AMBUJ/Caffe2_LatestGLOO2/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:611] Connect timeout [172.17.27.13]:27023
--------------------------------------------------------------------------
mpirun.openmpi noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
```

OR

```
INFO:memonger:Memonger memory optimization took 0.014378786087 secs
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /nfs/AMBUJ/Caffe2_LatestGLOO2/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:592] fd_ == FD_INVALID. 46 vs -1. File descriptor not closed
*** Aborted at 1493389176 (unix time) try "date -d @1493389176" if you are using GNU date ***
PC: @     0x7f37b1eedc37 (unknown)
*** SIGABRT (@0x3f000008c93) received by PID 35987 (TID 0x7f37b2679740) from PID 35987; stack trace: ***
    @     0x7f37b228f330 (unknown)
    ....
    @     0x7f37419f6915 (unknown)
    @     0x7f374277f496 gloo::transport::tcp::Pair::changeState()
    @     0x7f374277f6f9 gloo::transport::tcp::Pair::~Pair()
    @     0x7f374277f7f9 gloo::transport::tcp::Pair::~Pair()
    @     0x7f37427788f6 gloo::rendezvous::Context::connectFullMesh()
    @     0x7f3747d10a79 caffe2::gloo::CreateCommonWorld<>::RunOnDevice()
    @     0x7f3749595775 caffe2::Operator<>::Run()
    @     0x7f374247419a caffe2::SimpleNet::Run()
    @     0x7f37424a1ee2 caffe2::Workspace::RunNetOnce()
    @     0x7f374956fbbf _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlPNS_6detail15function_recordENS_6handleESR_SR_E1_clESQ_SR_SR_SR_.isra.1409
    @     0x7f374956fdf7 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlPNS_6detail15function_recordENS_6handleESR_SR_E1_4_FUNESQ_SR_SR_SR_
    @     0x7f3749578512 pybind11::cpp_function::dispatcher()
    @           0x523f6d (unknown)
    ....
    @           0x465bf4 (unknown)
    @           0x46612d (unknown)
    @           0x466d92 (unknown)
    @     0x7f37b1ed8f45 (unknown)
--------------------------------------------------------------------------
mpirun.openmpi noticed that process rank 0 with PID 35987 on node 172.17.27.13 exited on signal 6 (Aborted).
```

**Comment by ambujpd** [comment]
Hi @pietern,
The patch you made for gloo still didn't resolve the issue here. It still fails every time. With **mpirun**
 I'm now getting :
```
RuntimeError: [/nfs/AMBUJ/Caffe2_LatestGLOO3/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:507] connect [172.17.27.13]:42436: Connection refused
OR
RuntimeError: [/nfs/AMBUJ/Caffe2_LatestGLOO3/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:631] Connect timeout [172.17.27.13]:42436
```

However, leaving MPI aside, if I simply launch the application on 2 machines (just manually via shell, one after the other), with the following command (only shard_id differs):
`python resnet50_trainer.py --train_data=<PATH> --num_shards=2 --shard_id=0 --run_id=10 --file_store_path=<PATH_NFS>`
I get the following error on both terminals:
```
....
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20170502-181901.11306!INFO:resnet50_trainer:Starting epoch 0/1000
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /nfs/AMBUJ/Caffe2_LatestGLOO3/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:691] rv. Write must always succeed in sync mode
*** Aborted at 1493729372 (unix time) try "date -d @1493729372" if you are using GNU date ***
PC: @     0x7f2dcff00c37 (unknown)
*** SIGABRT (@0x3f000002c2a) received by PID 11306 (TID 0x7f2d46ffd700) from PID 11306; stack trace: ***
    @     0x7f2dd02a2330 (unknown)
    ....
    @                0x0 (unknown)
Aborted (core dumped)
```

Can you please take a look? Thanks.

**Comment by pietern** [comment]
@talk2ap001 Thanks for the update. Trying to repro with smaller OS level TCP buffers and then patching it. Continuing this particular issue in https://github.com/facebookincubator/gloo/issues/34.

**Comment by pietern** [comment]
@talk2ap001 Continuing the discussion here.

The write timeout you're seeing is caused by the different processes trying to execute different algorithms. As the trainer is multithreaded, this means there is empty intersection between the allreduce algorithms executed by processes A and B. This is odd, since we protect against this by inserting control blobs to impose a partial order, exactly to prevent this from happening.

Could you try removing the following lines and try again? https://github.com/caffe2/caffe2/blob/cbe8f22f2fd1eefe58acb45826acf8cd3c579f93/caffe2/contrib/gloo/common_world_ops.h#L42-L48

This means we will no longer see a write timeout since incoming writes are handled by a separate thread. If the problem I described above is what's going on then you should see a read timeout next.

Appreciate your help in tracking this down.

**Comment by ambujpd** [comment]
@pietern 
Doing the above actually started training on multiple machines!

**Comment by pietern** [comment]
@talk2ap001 Great news! :)

Now I'm curious what the original cause is when the pairs **are** in sync mode. It must mean some mismatch between allreduce operators being executed, but by default there are enough threads to execute them. And since you use `resnet50_trainer` everything will default to values that work for me...

**Comment by sergey-serebryakov** [comment]
@pietern Confirming this fix works for my own code (not the `resnet50_trainer`) at least for one NN configuration. Will check others later today. 
Thanks!

**Comment by pietern** [comment]
@sergey-serebryakov Thanks! You are using `data_parallel_model` through right?

**Comment by pietern** [comment]
I'm updating the gloo bindings so sync mode is optional. This will fix this issue regardless of TCP buffer size.

**Comment by sergey-serebryakov** [comment]
@pietern That's true.

**Comment by ambujpd** [comment]
@pietern Thanks for the help! At least I could start with distributed training.

However in preliminary runs, I'm not seeing good performance. I need to look into it in more depth.

By the way, how we can make use of IBVERBS with Gloo in Caffe2 (resnet50 example)? Can we select the transport manually?

**Comment by thyeros** [comment]
I cannot run resnet50_trainer.py example either out of the box. I used this command:

mpirun -n 1  -host x6,x6 python resnet50_trainer.py  --train_data=<IMAGENET> --num_shards=2 --shar=0 --file_store_path=/tmp : -n 1  -host x6,x6 python resnet50_trainer.py   --train_data=<IMAGENET> --num_shards=2 --shar=1 --file_store_path=/tmp

Then, got this error
Traceback (most recent call last):                                                                                
  File "resnet50_trainer.py", line 455, in <module>                                                               
    main()                                                                                                        
  File "resnet50_trainer.py", line 451, in main                                                                   
    Train(args)                                                                                                   
  File "resnet50_trainer.py", line 346, in Train                                                                  
    workspace.RunNetOnce(train_model.param_init_net)                                                              
  File "/ZZZZZZ/caffe2/build/caffe2/python/workspace.py", line 163, in RunNetOnce
    return C.run_net_once(StringifyProto(net))                                                                      
RuntimeError: [enforce fail at no_default_engine_op.h:29] . The operator CreateCommonWorld does not have a default engine implementation. Please specify an engine explicitly for this operator. Error from operator: 
input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"    

When I built caffe2, I set DUSE_GLOO=OFF, so not sure why engine is "GLOO". When I look at the https://github.com/caffe2/caffe2/blob/master/caffe2/operators/communicator_op.cc, obviously there is no default engine, but there is also mpi_op.cc. Thus allreduce should work on MPI. 

Can anyone help me fix this and get going?

**Comment by pietern** [comment]
@minsikcho The resnet50_trainer example only works with Gloo, so this is expected. It does not work with the MPI ops in `caffe2/mpi/`. If it did, and you would patch the trainer to use the MPI ops, you would have to compile with `-DUSE_MPI=ON` (I don't recall if this is default if MPI is found).

I'm closing this issue, as the primary reason for opening is has been addressed a while ago.
