### ISSUE TITLE
Model parallelism for GPU training supported with python interface in caffev2? 

### ISSUE THREAD

**Issue by hondaathma** [facebookarchive/caffe2#371]
I am talking about **model parallelism**. For example a modified version of resnet152 is more than 12Gb for me(eg:- larger image size).I only have two 12GB GPUS...What I mean is I want to assign some parts of resnet152 to GPU1 and others to GPU2. 

**Data parallelism** will copy multiple versions of resnet152 to each GPU.Tensorflow supports assigning each layers to a separate layer.

I was wondering if that is supported in caffe 2?

#345  PS: My original question on model parallelism was closed as it was thought of as Data parallelism

**Comment by akyrola** [comment]
First, try passing 'optimize_gradient_memory=True' to data_parallel_model (even if using just one GPU), to see if you can fit that on your GPU. For ResNets it is very effective. You can also run the 'memonger' algorithm yourself (see how data_parallel_model:OptimizeGradientMemory is implemented).

But Caffe2 also supports model parallelism, but pretty manually. You can assign each operator to different GPU by using DeviceScope:

   with scope.DeviceScope(core.DeviceOption(caffe2_pb2.CUDA, gpu_id)):
         model.FC(...)
         model.Conv()

(I might have made a typo in above, see again data_parallel_model.py code and look for usages of DeviceScope).


Then, I think, it should just work if inputs from several GPUs are combined in an op (for example to compute the final loss). If not, you can insert a Copy() op with appropriate device option.
