### ISSUE TITLE
Caffe2 iOS documentation

### ISSUE THREAD

**Issue by ankghost0912** [facebookarchive/caffe2#373]
Hi @Yangqing, I'm really impressed by caffe2, especially it's mobile first approach. However, I was wondering if you planned on writing a tutorial or documentation showing how to use caffe2 c++ API on iOS. I've been through the source code of the AICamera app by @bwasti but there no clear tutorial as to how one would use caffe2's c++ API in a task like object detection.

Thanks and great work!

**Comment by abjurato** [comment]
There is one another issue on this topic, check https://github.com/caffe2/caffe2/issues/298 for updates.

**Comment by RobertBiehl** [comment]
@ankghost0912 you can try [Caffe2Kit](https://github.com/RobertBiehl/caffe2-ios) to get it integrated into any iOS project in minutes.

**Comment by RobertBiehl** [comment]
@bwasti I think this issue can be closed as the discussion continues in #298
