### ISSUE TITLE
How to change the CPU mode to GPU mode?

### ISSUE THREAD

**Issue by raininglixinyu** [facebookarchive/caffe2#374]
The given MNIST python demo is  under  the cpu mode right？How can i change this to GPU mode?

**Comment by futurely** [comment]
model.param_init_net.RunAllOnGPU()
model.net.RunAllOnGPU()

**Comment by slayton58** [comment]
Or you can explicitly do this on model creation by putting your operators inside a `with core.DeviceScope(device):` scope:

```
with core.DeviceScope(core.DeviceOption(caffe2_pb2.CUDA, 0)):
    model.Op(...)
    model.OtherOp(...)
```

**Comment by raininglixinyu** [comment]
@futurely @slayton58 really thanks！problem has been resolved!

**Comment by tarunjainsagar** [comment]
How to convert MNIST python demo for 
    1. More than 1 GPU. ( Multi-GPU)
    2. distributed training ( multi-node , each node having multiple GPU) ??
@slayton58 @futurely

**Comment by rribani** [comment]
@slayton58  What about using brew? Can I still use with core.DeviceScope(device):?

**Comment by xpngzhng** [comment]
@futurely where to add
model.param_init_net.RunAllOnGPU()
model.net.RunAllOnGPU()
?

I try
```python
arg_scope = {"order": "NCHW"}
train_model = model_helper.ModelHelper(name="mnist_train", arg_scope=arg_scope)
train_model.param_init_net.RunAllOnGPU()
train_model.net.RunAllOnGPU()
data, label = AddInput(
     train_model, batch_size=64,
     db=os.path.join(data_folder, 'mnist-train-nchw-lmdb'),
     db_type='lmdb')
softmax = AddLeNetModel(train_model, data)
AddTrainingOperators(train_model, softmax, label)
AddBookkeepingOperators(train_model)
```

it does not work, then I use core.DeviceScope
```python
arg_scope = {"order": "NCHW"}
train_model = model_helper.ModelHelper(name="mnist_train", arg_scope=arg_scope)
with core.DeviceScope(core.DeviceOption(caffe2_pb2.CUDA, 0)):
    data, label = AddInput(
        train_model, batch_size=64,
        db=os.path.join(data_folder, 'mnist-train-nchw-lmdb'),
        db_type='lmdb')
    softmax = AddLeNetModel(train_model, data)
    AddTrainingOperators(train_model, softmax, label)
    AddBookkeepingOperators(train_model)
```
this works

**Comment by youngxiao** [comment]
@XupingZHENG I tried core.DeviceScope, it really works. Which should `from caffe2.proto import caffe2_pb2`
