### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by vingovan** [facebookarchive/caffe2#375]
I run "python -c 'from caffe2.python import core'"
but i get error:
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
Thanks.

**Comment by vingovan** [comment]
Seem,  there is many different python, so i got that error.

**Comment by aaronmarkham** [comment]
Check the troubleshooting info at the bottom of the install page. Take a look at PYTHONPATH. Try doing export PYTHONPATH=/usr/bin
Or if that doesn't work, point it to caffe2's build folder.
If that doesn't work you may have installed to a different python. Ways to solve this is to use Python environments, or eradicate all other Pythons, then reinstall.

**Comment by vingovan** [comment]
Yes, I removed one of them.
I used caffe2.
Thank you.

**Comment by walter211** [comment]
@ViNgoVan hi，how you sloved this，I met the same.

**Comment by lucasjinreal** [comment]
Same issue, I install from official site prebuild binary of macOS, `Caffe2-0.7.0-cp27-cp27m-macosx_10_12_x86_64.whl`, maybe this is build with GPU? My mac has only CPU.

**Comment by ShangxuanWu** [comment]
same issue here, and same question with @jinfagang

**Comment by j-holub** [comment]
Same thing here. I'm using a **virtual-env** running Python **2.7.13**.´, which is recommended by the install page.
Running on MacOS 10.12 and installed the prebuild binary via **pip install**.

Can't even import core from caffe2.python.

**Comment by lucasjinreal** [comment]
I given up, try using directly from C++.

**Comment by j-holub** [comment]
That's too bad. I mean I like C++ as well but it just shouldn't be that way. I always wonder why every deep learning framework I ever used is such a pain in the butt. TensorFlow too.

**Comment by lucasjinreal** [comment]
@00SteinsGate00  Pal, you are just saying into my deep heart, so many deep learning framework are so mess at least in building networks, I quiet like keras which let you only take attention on design networks rather than meaningless abstraction stuff. May be keras is what we should stick
