### ISSUE TITLE
Mac OS X build problem: leveldb, libCaffe2_CPU.dylib Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by nayoo** [facebookarchive/caffe2#377]
I followed all the steps in https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile

The Mac OS X build failed with the following error message:

`[ 71%] Linking CXX shared library libCaffe2_CPU.dylib
Undefined symbols for architecture x86_64:
  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      caffe2::db::LevelDB::LevelDB(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe2::db::Mode) in leveldb.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [caffe2/libCaffe2_CPU.dylib] Error 1
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
`

OS X El Capitan, Version 10.11.16

**Comment by nayoo** [comment]
Tried: `brew install leveldb` and rebuilt again by `make && cd build && sudo make install`.

The _same_ error message resulted.

The following is the summary of caffe2's build configuration output:

> -- ******** Summary ********
-- General:
--   Git version           : v0.7.0-50-gfeed706
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   Protobuf compiler     : /Users/nayoo/anaconda/bin/protoc
--   CXX flags             :  -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY;CAFFE2_UNIQUE_LONG_TYPEMETA;CAFFE2_NO_BUILTIN_CPU_SUPPORTS
-- 
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /Users/nayoo/anaconda/lib/libpython2.7.dylib
--   USE_CUDA              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--   USE_GFLAGS            : ON
--   USE_LMDB              : ON
--     LMDB version        : 0.9.18
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.4
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.8
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NNPACK            : OFF
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_GLOO              : OFF

The output of `brew --config`

> HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2318f7d2176734af260db3959229941fb17c150
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /Users/nayoo/anaconda/bin/perl
Python: /Users/nayoo/anaconda/bin/python => /Users/nayoo/anaconda/bin/python2.7
Ruby: /Users/nayoo/.rbenv/shims/ruby => /Users/nayoo/.rbenv/versions/2.2.3/bin/ruby
Java: 1.8.0_31
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
MacPorts/Fink: /opt/local/bin/port

**Comment by ardavank** [comment]
+1

**Comment by RachelZheng** [comment]
+1

**Comment by aaronmarkham** [comment]
The default version of leveldb that comes with the conda install via conda-forge is compatible. Try this:

```
brew uninstall leveldb
conda install -y --channel https://conda.anaconda.org/conda-forge leveldb
```

If you don't want to use Anaconda, you might try using pip, but you may have to force an earlier version. Something like `pip install leveldb==0.18`.

**Comment by Yangqing** [comment]
As this is a leveldb issue we can't really fix it... For now, use @aaronmarkham 's solution or turn off leveldb by `-DUSE_LEVELDB=OFF`.
