### ISSUE TITLE
Convert TensorFlow models into Caffe2 format

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#378]
TensorFlow is currently the [most starred](https://github.com/search?o=desc&q=stars%3A%3E1&s=stars&type=Repositories&utf8=%E2%9C%93) and [most forked](https://github.com/search?o=desc&q=stars%3A%3E1&s=forks&type=Repositories&utf8=%E2%9C%93) machine learning framework on GitHub. To help users migrate from TensorFlow to Caffe2, [existing models](https://github.com/tensorflow/models) need to be converted [easily](https://github.com/caffe2/caffe2/blob/master/caffe2/python/caffe_translator.py).

**Comment by pribadihcr** [comment]
+1

**Comment by atilaorh** [comment]
+1

**Comment by RSly** [comment]
+1
also this can help bring more community to caffe2 which can play a big role in the future!

**Comment by albert-92** [comment]
+1

**Comment by raininglixinyu** [comment]
+1

**Comment by jordanhart** [comment]
+1

**Comment by karaspd** [comment]
+1

**Comment by Digital2Slave** [comment]
+1

**Comment by lhCheung1991** [comment]
So, is it there any tool for this task issue?

**Comment by erik-dreyer** [comment]
+1.  Tensorflow is my preferred framework for rapid model prototyping and experimentation on custom datasets, but I would like the option to deploy trained models using Caffe2.

**Comment by gcmike** [comment]
+1

**Comment by futurely** [comment]
Example implementation: https://github.com/Tencent/ncnn/tree/master/tools/tensorflow

**Comment by orionr** [comment]
This is pretty old, so I'm going to close it. Going through ONNX (https://github.com/onnx/onnx-tensorflow) is probably going to be the supported solution here although still a work in progress.
