### ISSUE TITLE
Build from sources failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by hannan-sultan** [facebookarchive/caffe2#380]
I'm trying to install Caffe2 on Ubuntu 16.04, getting a build error. I have deleted the build folder and tried again but the same problem.
`[ 97%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
/home/hannan/caffe2/caffe2/python/pybind_state.cc: In member function ‘virtual bool caffe2::python::PythonOpBase::RunOnDevice()’:
/home/hannan/caffe2/caffe2/python/pybind_state.cc:202:74: error: ‘PyString_AsString’ was not declared in this scope
             PyString_AsString(trace_vec[i]->tb_frame->f_code->co_filename);
                                                                          ^
/home/hannan/caffe2/caffe2/python/pybind_state.cc: In lambda function:
/home/hannan/caffe2/caffe2/python/pybind_state.cc:322:41: error: ‘PyString_Check’ was not declared in this scope
             if (PyString_Check(arg.ptr())) { // string
                                         ^
/home/hannan/caffe2/caffe2/python/pybind_state.cc: In lambda function:
/home/hannan/caffe2/caffe2/python/pybind_state.cc:824:37: error: ‘PyString_Check’ was not declared in this scope
         if (PyString_Check(arg.ptr())) { // string
                                     ^
caffe2/CMakeFiles/caffe2_pybind11_state.dir/build.make:62: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o' failed
make[3]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o] Error 1
make[3]: Leaving directory '/home/hannan/caffe2/build'
CMakeFiles/Makefile2:3304: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/all] Error 2
make[2]: Leaving directory '/home/hannan/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/hannan/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by ThyrixYang** [comment]
I encountered the same error today, with ubuntu 16.04

**Comment by november2011** [comment]
Same error. It may be the python-path of 'sudo pip' inconsistency with default path, I solved this problem by removing the path of python3.5 in '.bashrc' ,  hope useful for you.

**Comment by kendricktan** [comment]
Hi there, had the same problem, solved it by using a virtualenv with python2.7 instead of python 3.5
