### ISSUE TITLE
Build failing on Jetson TK1

### ISSUE THREAD

**Issue by rachitgarg91** [facebookarchive/caffe2#383]
Hello,
 Build seems to be failing on nvidia jetson TK1. Here is the log: 

-- ******** Summary ********
-- General:
--   Git version           : v0.7.0-50-gfeed706
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   Protobuf compiler     : /usr/bin/protoc
--   CXX flags             :  -Wno-deprecated -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY;CAFFE2_FORCE_FALLBACK_CUDA_MPI;CAFFE2_UNIQUE_LONG_TYPEMETA;CAFFE2_NO_BUILTIN_CPU_SUPPORTS
-- 
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.6
--     Python library      : /usr/lib/arm-linux-gnueabihf/libpython2.7.so
--   USE_CUDA              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--   USE_GFLAGS            : ON
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.13
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : ON
--   USE_NCCL              : OFF
--   USE_NNPACK            : OFF
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_GLOO              : ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/caffe2/build
[  1%] Built target gmock
[  2%] Built target gmock_main
[  2%] Built target gtest
[  7%] Built target benchmark
[  8%] Built target output_test_helper
[  8%] Built target Caffe_PROTO
[  8%] [  8%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/mpi/context.cc.o
[ 12%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o
Built target Caffe2_PROTO
[ 13%] Built target gtest_main
[ 14%] Built target basic_test
[ 14%] Built target benchmark_test
[ 14%] Built target complexity_test
[ 14%] Built target cxx03_test
Scanning dependencies of target diagnostics_test
[ 15%] Building CXX object third_party/benchmark/test/CMakeFiles/diagnostics_test.dir/diagnostics_test.cc.o
Linking CXX executable diagnostics_test
[ 15%] Built target diagnostics_test
Scanning dependencies of target donotoptimize_test
[ 15%] Building CXX object third_party/benchmark/test/CMakeFiles/donotoptimize_test.dir/donotoptimize_test.cc.o
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc: In member function ‘void gloo::mpi::Context::connectFullMesh(std::shared_ptr<gloo::transport::Device>&)’:
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: error: no matching function for call to ‘max(long unsigned int&, std::vector<char>::size_type)’
     maxLength = std::max(maxLength, address.size());
                                                   ^
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: note: candidates are:
In file included from /usr/include/c++/4.8/memory:62:0,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/context.h:12,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.h:12,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:10:
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:216:5: note:   template argument deduction/substitution failed:
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::vector<char>::size_type {aka unsigned int}’)
     maxLength = std::max(maxLength, address.size());
                                                   ^
In file included from /usr/include/c++/4.8/memory:62:0,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/context.h:12,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.h:12,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:10:
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:260:5: note:   template argument deduction/substitution failed:
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::vector<char>::size_type {aka unsigned int}’)
     maxLength = std::max(maxLength, address.size());
                                                   ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:12:
/usr/include/c++/4.8/bits/stl_algo.h:4231:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4231:5: note:   template argument deduction/substitution failed:
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
     maxLength = std::max(maxLength, address.size());
                                                   ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:12:
/usr/include/c++/4.8/bits/stl_algo.h:4236:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algo.h:4236:5: note:   template argument deduction/substitution failed:
/home/ubuntu/caffe2/third_party/gloo/gloo/mpi/context.cc:63:51: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
     maxLength = std::max(maxLength, address.size());
                                                   ^
make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/mpi/context.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target filter_test
[ 15%] Building CXX object third_party/benchmark/test/CMakeFiles/filter_test.dir/filter_test.cc.o
Linking CXX executable donotoptimize_test
[ 15%] Built target donotoptimize_test
Scanning dependencies of target fixture_test
[ 15%] Building CXX object third_party/benchmark/test/CMakeFiles/fixture_test.dir/fixture_test.cc.o
make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable filter_test
[ 15%] Built target filter_test
Linking CXX executable fixture_test
[ 15%] Built target fixture_test
[ 15%] Built target python_copy_files
make: *** [all] Error 2

Thanks.

**Comment by Yangqing** [comment]
Looks like failure from gloo - kindly build with -DUSE_GLOO=OFF. I'll update the tk1 scripts to turn off that.

**Comment by pietern** [comment]
The TK1 is 32 bit, so Gloo will be disabled automatically when #401 is committed.
