### ISSUE TITLE
Caffe2 users group for not-an-issue question? + qustion example

### ISSUE THREAD

**Issue by ZlodeiBaal** [facebookarchive/caffe2#384]
Hi!
Greate project. I hope it can cure main Caffe1 problems. 
My first main question. Do you have some "Caffe2 users group" like one that Caffe 1 have? Forum, yahoo|google group/ telegram|slack|viber channel?
You have completely new system with different logic. You have great documentation that outperform caffe1 documentation. But documentation yet incomplete. And you will have a lot of dumb users with silly question, like me/

For example this question below:) 
I pretty sure that it's not an "issue". But i don't know how to workout it.
In you "Loading Pre-Trained Models" example you load net by using:
```
 p=workspace.Predictor(init_net, predict_net)
 results = p.run([img])
```
If i am correct - this function don't load network into you workspace complectly. When i try this after load predictor:
` workspace.Blobs()`
It return empty list. I can't read/load blobs directly using their names, either:
```
 workspace.FetchBlob("pool10")
 workspace.FeedBlob("data", img)
```
I tryed load net's directly in workspace, but this not working:
```
 with open(INIT_NET) as f:
    init_net = f.read()
 with open(PREDICT_NET) as f:
    predict_net = f.read()
 workspace.CreateNet(init_net, predict_net)
```

So, the question: what the easy way to acess blob's in loaded network/how to load network in workspace?

**Comment by futurely** [comment]
https://caffe2.ai/docs/intro-tutorial.html#null__executing

**Comment by aaronmarkham** [comment]
This meetup is happening next week in the Bay Area:
https://www.meetup.com/Caffe2-Bay-Area/events/239836290/

There's also this new Facebook group started here:
https://www.facebook.com/groups/caffe2ai/
