### ISSUE TITLE
make issue on Arch Linux 

### ISSUE THREAD

**Issue by sleeplessai** [facebookarchive/caffe2#387]
I work very well with Caffe framework on Arch Linux for a long time using AUR-maintained package caffe-cpu. Currently, I wanna update to Caffe 2 framework by compiling it from sources. 
Unfortunately, something goes wrong and I got an error below as copied from 
 `~/caffe2/build/CMakeFiles/CMakeError.log`
How could I solve this ? XD

------CMakeError.log-------
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/molasses/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_8c16f/fast"
make[1]: Entering directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_8c16f.dir/build.make CMakeFiles/cmTC_8c16f.dir/build
make[2]: Entering directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8c16f.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_8c16f.dir/CheckSymbolExists.c.o   -c /home/molasses/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_8c16f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8c16f.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_8c16f.dir/CheckSymbolExists.c.o  -o cmTC_8c16f -rdynamic 
CMakeFiles/cmTC_8c16f.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cmTC_8c16f.dir/build.make:98: cmTC_8c16f] Error 1
make[2]: Leaving directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
make[1]: *** [Makefile:126: cmTC_8c16f/fast] Error 2
make[1]: Leaving directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'

File /home/molasses/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/molasses/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_52631/fast"
make[1]: Entering directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_52631.dir/build.make CMakeFiles/cmTC_52631.dir/build
make[2]: Entering directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_52631.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_52631.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.7/Modules/CheckFunctionExists.c
Linking C executable cmTC_52631
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_52631.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_52631.dir/CheckFunctionExists.c.o  -o cmTC_52631 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cmTC_52631.dir/build.make:98: cmTC_52631] Error 1
make[2]: Leaving directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
make[1]: *** [Makefile:126: cmTC_52631/fast] Error 2
make[1]: Leaving directory '/home/molasses/caffe2/build/CMakeFiles/CMakeTmp'
---------End of file----------

**Comment by liliburnett** [comment]
Same issue here, it's very cryptic. Fails on 99% made.

Also on Arch Linux, ran previous caffe compiled myself with ease. Mine in addition to same as above has at the bottom of the error log
`Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 failed with the 
following output:
Change Dir: /home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a2c32/fast"
/usr/bin/make -f CMakeFiles/cmTC_a2c32.dir/build.make CMakeFiles/cmTC_a2c32.dir/
build
make[1]: Entering directory '/home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp
'
Building CXX object CMakeFiles/cmTC_a2c32.dir/src.cxx.o
/usr/bin/g++-5     -std=c++11 -Wall -Wextra -Wshadow -pedantic -pedantic-errors -DHAVE_CXX_FLAG_WSHORTEN_64_TO_32 -Wshorten-64-to-32   -Wshorten-64-to-32 -o CMakeFiles/cmTC_a2c32.dir/src.cxx.o -c /home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp/src.cxx
g++-5: error: unrecognized command line option '-Wshorten-64-to-32'
g++-5: error: unrecognized command line option '-Wshorten-64-to-32'
make[1]: *** [CMakeFiles/cmTC_a2c32.dir/build.make:66: CMakeFiles/cmTC_a2c32.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp'
make: *** [Makefile:126: cmTC_a2c32/fast] Error 2

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WTHREAD_SAFETY failed with the following output:
Change Dir: /home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d5cd9/fast"
/usr/bin/make -f CMakeFiles/cmTC_d5cd9.dir/build.make CMakeFiles/cmTC_d5cd9.dir/build
make[1]: Entering directory '/home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_d5cd9.dir/src.cxx.o
/usr/bin/g++-5     -std=c++11 -Wall -Wextra -Wshadow -pedantic -pedantic-errors -Wfloat-equal -fstrict-aliasing -Wzero-as-null-pointer-constant -Wstrict-aliasing -DHAVE_CXX_FLAG_WTHREAD_SAFETY -Wthread-safety   -Wthread-safety -o CMakeFiles/cmTC_d5cd9.dir/src.cxx.o -c /home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp/src.cxx
g++-5: error: unrecognized command line option '-Wthread-safety'
g++-5: error: unrecognized command line option '-Wthread-safety'
make[1]: *** [CMakeFiles/cmTC_d5cd9.dir/build.make:66: CMakeFiles/cmTC_d5cd9.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/daenerys/deepdream/caffe2/CMakeFiles/CMakeTmp'
make: *** [Makefile:126: cmTC_d5cd9/fast] Error 2

Source file was:
int main() { return 0; }`


the original error before checking logs was
`make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/build.make:63: caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3519: caffe2/CMakeFiles/caffe2_pybind11_state.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/build.make:63: caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3599: caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/all] Error 2
make: *** [Makefile:139: all] Error 2`

I have built pybind from third_party folder

**Comment by slayton58** [comment]
@daydreamcoder Error is: `(.text+0x16): undefined reference to pthread_create' and `/usr/bin/ld: cannot find -lpthreads`. Do you have the pthreads library installed? 

@liliburnett Your errors look different: `g++-5: error: unrecognized command line option '-Wshorten-64-to-32'`, `g++-5: error: unrecognized command line option '-Wthread-safety'`. Your compiler doesn't seem to support these flags, but I don't know why that's the case.

**Comment by liliburnett** [comment]
I was able to compile by not including mpi and NNPACK, and by using my distro's gcc to compile but using gcc-5 for CUDA_HOST_COMPILER. I used ccmake to set my own variables.
I also did not use Arch Linux's openmp package, I compiled my own with CUDA support from their website.

**Comment by habibrk** [comment]
I am trying to install caffe2 on, tegra tx1 - aarch64, and getting same error as @daydreamcoder 

Building C object CMakeFiles/cmTC_e1be4.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_e1be4.dir/CheckSymbolExists.c.o   -c /media/ubuntu/disk/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_e1be4
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e1be4.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_e1be4.dir/CheckSymbolExists.c.o  -o cmTC_e1be4 -rdynamic
CMakeFiles/cmTC_e1be4.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x18): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e1be4.dir/build.make:97: recipe for target 'cmTC_e1be4' failed
make[2]: *** [cmTC_e1be4] Error 1
make[2]: Leaving directory '/media/ubuntu/disk/caffe2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e1be4/fast' failed
make[1]: *** [cmTC_e1be4/fast] Error 2
make[1]: Leaving directory '/media/ubuntu/disk/caffe2/build/CMakeFiles/CMakeTmp'



I am using Ubuntu 16.04 and lpthreads should be installed bydeafult, no?

**Comment by sleeplessai** [comment]
What u said, lpthreads is not a library. When u coding with the system thread module header, <pthread.h>, the compiler need this parameter to 'load' its lib. Such, in Ubuntu OS, compiler makes -lpthread as default option, but different in Arch or others. Thus, makefile make this mistake.

**Comment by habibrk** [comment]
@daydreamcoder were you able to resolve this problem? if yes then can you please let me know the output of the following command
$ldconfig -p | grep pthread

**Comment by sleeplessai** [comment]
@habibrk 
In fact, I didn't try to solve after several failures anymore. :) 
Fortunately, I found someone has maintained an AUR-version for Caffe 2.
Just see and yaourt this [caffe2 0.7.0-3](https://aur.archlinux.org/packages/caffe2/)

**Comment by pietern** [comment]
@habibrk If this still is an issue for you, please open an new issue with your build environment, CMake summary, and observed errors.
