### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by zhangqianhui** [facebookarchive/caffe2#39]
info:

WARNING: Build failed: //third_party:nccl. Fail messages are as follows:
nvcc fatal   : Unsupported gpu architecture 'compute_61'

what's meaning?

@Yangqing

**Comment by zhangqianhui** [comment]
I  have solved the problem now , You can close it .

**Comment by weak-orange-wind** [comment]
@zhangqianhui Hello！ I want to know how to solve this problem, can you help me?
