### ISSUE TITLE
How to compile for android 

### ISSUE THREAD

**Issue by zhangqianhui** [facebookarchive/caffe2#40]
make android ? some errors occurs,

**Comment by Yangqing** [comment]
(Cleaning up old Issues)

Now you can do scripts/build_android.sh which should work reasonably OK.

**Comment by leemgs** [comment]
Please, refer to the below webpages. 
* https://caffe2.ai/docs/mobile-integration.html
* https://github.com/caffe2/caffe2/blob/master/scripts/build_android.sh
