### ISSUE TITLE
Windows: CMake overwrites runtime library

### ISSUE THREAD

**Issue by crohkohl** [facebookarchive/caffe2#403]
Hi,

in the file https://github.com/caffe2/caffe2/blob/master/CMakeLists.txt#L108 the runtime library is always set to static, i.e. 

```
if (NOT ${BUILD_SHARED_LIBS})
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
  endif()
```

This is not a desired behaviour, as this needs to be set by the developer according to the software environment.

I think this setting should be configured by the user or left as it is.
In the protobuf library this is solved as follows:

```
  if (MSVC AND protobuf_MSVC_STATIC_RUNTIME)
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
  endif (MSVC AND protobuf_MSVC_STATIC_RUNTIME)
```

- Christopher

**Comment by crohkohl** [comment]
The same invalid assumption is in the cuda.cmake file: https://github.com/caffe2/caffe2/blob/master/cmake/Cuda.cmake#L242

Just because you want to build a static lib, does not mean you want the static runtime.

Further, shared libraries for windows are not supported anyway as no symbols are exported. Maybe this should give an error if a user attempts to build it?

**Comment by Yangqing** [comment]
Related to https://github.com/caffe2/caffe2/issues/1217 and #774 . Thanks for the idea - yeah, we will adopt a way similar to protobuf and allow the user to choose the runtime.

**Comment by Yangqing** [comment]
(Closing this and I'll update #774 as the solution is out)
