### ISSUE TITLE
caffe2 compile error!!!   math_gpu.cu(136):error: identifier "CUDA_R_16F" is undefined

### ISSUE THREAD

**Issue by peterwkl2017** [facebookarchive/caffe2#409]
my system is ubuntu14.04, use gpu , when compile,then ouput below,  how to solve this problem ?  thank you !

/home/wsn/caffe2/caffe2/utils/conversions.h(137): warning: variable "r" was declared but never referenced

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(136): error: identifier "CUDA_R_16F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(312): error: identifier "CUDA_R_16F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(496): error: identifier "CUDA_R_16F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(496): error: identifier "CUDA_R_32F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(496): error: identifier "cublasDotEx" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(740): error: identifier "CUDA_R_16F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(740): error: identifier "CUDA_R_32F" is undefined

/home/wsn/caffe2/caffe2/utils/math_gpu.cu(740): error: identifier "cublasAxpyEx" is undefined

**Comment by Yangqing** [comment]
Ah you might be using cuda 7 still, after the recent fp16 support Caffe2 now requires cuda 8 - kindly update cuda.
