### ISSUE TITLE
Multibox : Error from operator input: "avgpool7"

### ISSUE THREAD

**Issue by jpmerc** [facebookarchive/caffe2#41]
I get an error whenever I try to run multibox. I'm trying to run it on CPU with gcc 5.4. The error happens when I call this :  `workspace.RunNet("multibox")` . It says there are 4 dimensions instead of 2, but I don't know how to solve this problem.

Here's the error I get in the terminal :

I0824 22:32:45.188304 24099 workspace.cc:105] Initializing network multibox
E0824 22:32:46.356940 24099 logging.cc:59] [enforce fail at fully_connected_op.h:25] W.ndim() == 2. 4
E0824 22:32:46.357280 24099 logging.cc:64] Error from operator input: "avgpool7"
input: "nn0_w"
input: "nn0_b"
output: "nn0_pre_relu6"
type: "FC"
device_option {
  device_type: CPU
}
Traceback (most recent call last):
  File "code_multibox.py", line 109, in <module>
    location, confidence = RunMultiboxOnImage("not-penguin.jpg", LOCATION_PRIOR)
  File "code_multibox.py", line 96, in RunMultiboxOnImage
    workspace.RunNet("multibox")
RuntimeError: [enforce fail at fully_connected_op.h:25] W.ndim() == 2. 4Error from operator input: "avgpool7"
input: "nn0_w"
input: "nn0_b"
output: "nn0_pre_relu6"
type: "FC"
device_option {
  device_type: CPU
}

It would be appreciated if someone can help me on this. 
Thanks!

**Comment by slayton58** [comment]
Use the code from here as an example: https://github.com/caffe2/caffe2/blob/master/caffe2/python/convnet_benchmarks.py#L151-L155 - you should be able to specify the flattened dimensions
