### ISSUE TITLE
Caffe2 compile issue - nvcc fatal   : Path to libdevice library not specified

### ISSUE THREAD

**Issue by ravargs** [facebookarchive/caffe2#410]
I am building Caffe2 on Ubuntu 14.04 and it fails with the following error. So far I tried setting the path for the $NVVMIR_LIBRARY_DIR and by editing the  nvcc.profile file.

> [ 14%] Building CXX object third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/pair.cc.o
> Linking CXX static library libgloo.a
> [ 14%] Built target gloo
> [ 14%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
> nvcc fatal   : Path to libdevice library not specified
> CMake Error at gloo_cuda_generated_nccl.cu.o.cmake:260 (message):
>   Error generating file
>   /usr/local/src/caffe2/caffe2/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o
> 
> 
> make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o] Error 1
> make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all] Error 2
> make: *** [all] Error 2

Cuda version details
```
root@01:/usr/local/src/caffe2/caffe2# which nvcc
/usr/local/bin/nvcc
root@01:/usr/local/src/caffe2/caffe2# ls -l /usr/local/bin/nvcc
lrwxrwxrwx 1 root root 28 Mar  7 18:05 /usr/local/bin/nvcc -> /usr/local/cuda-8.0/bin/nvcc
root@01:/usr/local/src/caffe2/caffe2#
root@01:/usr/local/src/caffe2/caffe2# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

```

**Comment by Yangqing** [comment]
Related issues seem to suggest this is a cuda installation issue:
https://devtalk.nvidia.com/default/topic/804501/libdevice-library-not-found-by-nvcc/
https://github.com/cudamat/cudamat/issues/40

**Comment by ravargs** [comment]
Removed the standalone version and reinstalled though apt-get and got it worked..

Thanks
