### ISSUE TITLE
caffe2 install fail

### ISSUE THREAD

**Issue by Cv9527** [facebookarchive/caffe2#413]
I have install protobuf 2.6.1 in ubuntu 16. when make caffe2, it encounter the follow errors, how to solve them?

[  1%] Built target nccl_external
[  1%] Built target python_copy_files
[  2%] Built target gmock
[  3%] Built target gmock_main
[  3%] Built target gtest
[  4%] Built target gtest_main
[  7%] Built target benchmark
[  7%] Built target output_test_helper
[  8%] Built target reporter_output_test
[  9%] Built target multiple_ranges_test
[  9%] Built target cxx03_test
[  9%] Built target map_test
[ 10%] Built target benchmark_test
[ 10%] Built target basic_test
[ 10%] Built target complexity_test
[ 11%] Built target diagnostics_test
[ 12%] Built target options_test
[ 13%] Built target skip_with_error_test
[ 14%] Built target fixture_test
[ 14%] Built target donotoptimize_test
[ 15%] Built target filter_test
[ 16%] Built target register_benchmark_test
[ 20%] Built target gloo
[ 21%] Built target gloo_cuda
[ 22%] Running C++/Python protocol buffer compiler on /home/ubuntu/caffe2/caffe/proto/caffe.proto
/bin/sh: 1: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: not found
caffe/proto/CMakeFiles/Caffe_PROTO.dir/build.make:61: recipe for target 'caffe/proto/caffe.pb.cc' failed
make[2]: *** [caffe/proto/caffe.pb.cc] Error 127
CMakeFiles/Makefile2:1281: recipe for target 'caffe/proto/CMakeFiles/Caffe_PROTO.dir/all' failed
make[1]: *** [caffe/proto/CMakeFiles/Caffe_PROTO.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Yangqing** [comment]
Did you install protobuf with `sudo apt-get install libprotobuf-dev`? If so, you can install the corresponding compiler with `sudo apt-get install protobuf-compiler`.

**Comment by RitwikGopi** [comment]
Hi I installed both the packages still getting same Error.
