### ISSUE TITLE
Operator modules

### ISSUE THREAD

**Issue by hgaiser** [facebookarchive/caffe2#416]
A big caveat in Caffe's modularity is that it didn't allow layers to be added dynamically, through modules. I had spent some time making [a system](https://github.com/BVLC/caffe/pull/5294) for this in Caffe and it is currently under review. I have been using it for some time now and it makes adding a new layer very easy. (vanilla) Caffe is installed as a system dependency (with the layer modules PR) and if I need a 'third-party' layer from a PR or some project, I wrap it in its own CMake project, create a module and it's good to go. That way I can run for instance Faster RCNN using upstream Caffe instead of the outdated Faster RCNN version of Caffe.

Looking at the documentation it seems that Caffe2 is suffering from the exact same caveat. I've been going through the documentation but it seems that in order to add a new operator one must clone Caffe2, add the operator and then compile and deploy that special version of Caffe2?

I could try to implement a similar system as with Caffe layer modules, but then Caffe2's operator modules. I was hoping to get some feedback on the suggestion before I spend time on this however.

**Comment by slayton58** [comment]
Take a look at this repo: [caffe2/caffe2_bhtsne](https://github.com/caffe2/caffe2_bhtsne) - it sounds like an example of what you're after.

**Comment by hgaiser** [comment]
> Take a look at this repo: caffe2/caffe2_bhtsne - it sounds like an example of what you're after.

Seems you are correct! Thank you for your response.

**Comment by nnop** [comment]
Could it also apply to caffe? @slayton58 @hgaiser

**Comment by hgaiser** [comment]
@nnop , big sigh...

https://github.com/BVLC/caffe/pull/5294

**Comment by nnop** [comment]
Thanks for your contribution and pointing out.
