### ISSUE TITLE
Listing all layers

### ISSUE THREAD

**Issue by TimZaman** [facebookarchive/caffe2#42]
Is there a possibility of easily listing all layers and their settings? Maybe to a protobuf? If not, any ideas how I would go about most robustly implementing this?

**Comment by slayton58** [comment]
Look at caffe2/binaries/print_registered_core_operators.cc (and the compiled binary) - it prints out all registered operators.

**Comment by TimZaman** [comment]
Thanks, that's a great functionality. Does anything exist like that for caffe(1)?

**Comment by lukeyeager** [comment]
Is this what you're looking for? https://github.com/BVLC/caffe/pull/2930

**Comment by TimZaman** [comment]
Ooph @lukeyeager, that's the closest thing so far. But it only gives me the layers names. I was just browsing for something reflecting the content of the `caffe.proto`.

**Comment by lukeyeager** [comment]
Ever since https://github.com/BVLC/caffe/pull/1694 there hasn't been a way to enumerate the layers just by looking at `caffe.proto`.

**Comment by TimZaman** [comment]
Fair enough. A _dirty_ combination of (1) listing all layers with your function and (2) regexing all variables within the parameters of caffe.proto will do the trick for now. Thanks!

**Comment by TimZaman** [comment]
For anyone interested, the parsed `.proto` to `.json` looks like this: 
[caffe.proto.json on pastebin](http://pastebin.com/jHc5xsBN)
Might be quite handy for third party packages that make use of caffe. I'll return here when caffe2 has matured. Thanks all. Closing for now.

**Comment by ajtulloch** [comment]
@TimZaman  fwiw, you can introspect on protobufs using the https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor-module, etc API, which might make the above file easier to generate in the future.

**Comment by TimZaman** [comment]
Nice one, didn't find that on my quest. Will come in handy.
