### ISSUE TITLE
Failure when running Caffe2 Zoo model "ImageNet ILSVRC13 RCNN"

### ISSUE THREAD

**Issue by mjohnst** [facebookarchive/caffe2#421]
I am attempting to run the [ImageNet ILSVRC13 RCNN](https://github.com/BVLC/caffe/blob/80f44100e19fd371ff55beb3ec2ad5919fb6ac43/models/bvlc_reference_rcnn_ilsvrc13/readme.md) model in Caffe2. I've downloaded the pre-trained `pb` files and loaded the model into a `Predictor`.

When I run with some image input, I receive this error:
```
terminating with uncaught exception of type caffe2::EnforceNotMet: [enforce fail at fully_connected_op.h:32] W.ndim() == 2. 4 Error from operator: 
input: "pool5" input: "fc6_w" input: "fc6_b" output: "fc6" type: "FC"
```

It's failing on the first `CAFFE_ENFORCE` from `fully_connected_op.h -> DoRunWithType()`:
```
const auto& X = Input(0);
const auto& W = Input(1);
const auto& b = Input(2);
auto* Y = Output(0);
CAFFE_ENFORCE(W.ndim() == 2, W.ndim());
CAFFE_ENFORCE(b.ndim() == 1, b.ndim());
```

Is the model formatted incorrectly? It seems like FC layers expect the weights to have 2 dimensions, but there are 4 in this case.

Here are (I think) the relevant layers from the `deploy.prototxt`:
```
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "conv5"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "fc6"
  type: "InnerProduct"
  bottom: "pool5"
  top: "fc6"
  inner_product_param {
    num_output: 4096
  }
}
```

**Comment by ezineo** [comment]
Maybe you need to use the new **caffe_translator.py** to translate the model.

**Comment by mjohnst** [comment]
The model I'm using is listed in the Zoo as Caffe2 (comes with `exec_net.pb` and `predict_net.pb`).
I'll try running the model conversion myself from the original `caffemodel` to see if that makes a difference.

**Comment by mjohnst** [comment]
Running the `caffe_translator.py` on the `caffemodel` myself seemed to help - runs now without enforce error. 
@ezineo any reasoning behind why my translation worked, but the translated model in the Zoo did not?
