### ISSUE TITLE
cmake error on TX1(tegra x1)

### ISSUE THREAD

**Issue by xhzzhang** [facebookarchive/caffe2#422]
**1. cmake error output**
....
-- CUDA detected: 7.0
-- Added CUDA NVCC flags for: sm_53
-- Found libcuda:
/usr/lib/aarch64-linux-gnu/libcuda.so
CMake Error at cmake/Cuda.cmake:221 (message):
Cannot find libnvrtc.so.  Please file an
issue on
https://github.com/caffe2/caffe2 with your
build output.
Call Stack (most recent call first):
cmake/Dependencies.cmake:253 (include)
CMakeLists.txt:85 (include)

-- Configuring incomplete, errors
occurred!
See also

**And show content of caffe2/build/CMakeFiles/CMakeError.log as below**

Determining if the pthread_create exist failed with the following output:
Change Dir: /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec3276313348/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec3276313348.dir/build.make CMakeFiles/cmTryCompileExec3276313348.dir/build
make[1]: Entering directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3276313348.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec3276313348.dir/CheckSymbolExists.c.o   -c /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec3276313348
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3276313348.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec3276313348.dir/CheckSymbolExists.c.o  -o cmTryCompileExec3276313348 -rdynamic 
CMakeFiles/cmTryCompileExec3276313348.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x18): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: Leaving directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec3276313348] Error 1
make: *** [cmTryCompileExec3276313348/fast] Error 2

File /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec1192195251/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1192195251.dir/build.make CMakeFiles/cmTryCompileExec1192195251.dir/build
make[1]: Entering directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1192195251.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec1192195251.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-2.8/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec1192195251
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1192195251.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec1192195251.dir/CheckFunctionExists.c.o  -o cmTryCompileExec1192195251 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: Leaving directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec1192195251] Error 1
make: *** [cmTryCompileExec1192195251/fast] Error 2

Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 failed with the following output:
Change Dir: /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec4124383914/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec4124383914.dir/build.make CMakeFiles/cmTryCompileExec4124383914.dir/build
make[1]: Entering directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec4124383914.dir/src.cxx.o
/usr/bin/c++    -std=c++11 -Wall -Wextra -Wshadow -pedantic -pedantic-errors -DHAVE_CXX_FLAG_WSHORTEN_64_TO_32 -Wshorten-64-to-32   -Wshorten-64-to-32 -o CMakeFiles/cmTryCompileExec4124383914.dir/src.cxx.o -c /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wshorten-64-to-32'
c++: error: unrecognized command line option '-Wshorten-64-to-32'
make[1]: *** [CMakeFiles/cmTryCompileExec4124383914.dir/src.cxx.o] Error 1
make[1]: Leaving directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec4124383914/fast] Error 2

Source file was:
int main() { return 0;}
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WTHREAD_SAFETY failed with the following output:
Change Dir: /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec3067405402/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec3067405402.dir/build.make CMakeFiles/cmTryCompileExec3067405402.dir/build
make[1]: Entering directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec3067405402.dir/src.cxx.o
/usr/bin/c++    -std=c++11 -Wall -Wextra -Wshadow -pedantic -pedantic-errors -Wfloat-equal -fstrict-aliasing -Wzero-as-null-pointer-constant -Wstrict-aliasing -DHAVE_CXX_FLAG_WTHREAD_SAFETY -Wthread-safety   -Wthread-safety -o CMakeFiles/cmTryCompileExec3067405402.dir/src.cxx.o -c /mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wthread-safety'
c++: error: unrecognized command line option '-Wthread-safety'
make[1]: *** [CMakeFiles/cmTryCompileExec3067405402.dir/src.cxx.o] Error 1
make[1]: Leaving directory `/mnt/WORK/Caffe2/src/caffe2/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec3067405402/fast] Error 2

Source file was:
int main() { return 0;}

**Comment by bwasti** [comment]
It seems you'll need to install [NVRTC](http://docs.nvidia.com/cuda/nvrtc/index.html)

**Comment by xhzzhang** [comment]
Thanks so much!

**Comment by ghost** [comment]
I also meet this problem. Can you tell me how to fix it?
