### ISSUE TITLE
How to build caffe2 with debug option?

### ISSUE THREAD

**Issue by Primus-zhao** [facebookarchive/caffe2#428]
Hi guys,
How can i build caffe2 so that i can use gdb to debug it?

**Comment by bwasti** [comment]
You can set CMAKE_BUILD_TYPE to Debug

**Comment by Cv9527** [comment]
Can I use IDE, such as qt, codeblocks, to debug caffe2?

**Comment by Primus-zhao** [comment]
@bwasti , got it! thks!

**Comment by bwasti** [comment]
@Cv9527 please open a new issue with your question and further details or examples of what such usage would look like
