### ISSUE TITLE
distributed training questiones

### ISSUE THREAD

**Issue by formath** [facebookarchive/caffe2#429]
I am confused with those questiones about distributed training of caffe2 and can not find any documents.
1. Caffe2 use `gloo` to support distributed training, so does it just run on `mpi` cluster?  Could it run on `yarn` cluster and read data from `hdfs`?
2. Does Caffe2 support `async-sgd`?
3. Other dnn frameworks, like `mxnet` and `tensorflow`,  have a parameter server to save and update parameters. In Caffe2, how the parameters be stored and updated? 
Thanks.

@Yangqing

**Comment by pietern** [comment]
I'll try to answer:

1. Yes, it can run on MPI cluster, it just won't use the MPI primitives for parameter synchronization. Gloo uses its own transport layer, so as soon as Caffe2 has initialized and all participating nodes have found each other, Gloo will take over and establish direct connections between all peers. This also means you can run it on non-MPI clusters. As long as the nodes can find each other through some rendezvous mechanism (e.g. a shared filesystem can also be used), Gloo can establish connections, and the collectives can be used.
2. We don't support distributed async SGD today, perhaps later (not on the immediate roadmap).
3. There's no parameter server available for Caffe2 yet. For the synchronous SGD case every node holds a copy of the parameters and participates in updating them.

**Comment by fanyangCS** [comment]
@pietern does caffee2 support HDFS?
