### ISSUE TITLE
nvcc fatal: Unknown option '-expt-relaxed-constexpr' on Jetson TX1

### ISSUE THREAD

**Issue by xhzzhang** [facebookarchive/caffe2#441]
Hello, 
    I build fail on TX1, below is output message:

 59%] [ 59%] [ 59%] [ 59%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/image/./Caffe2_GPU_generated_transform_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_local_response_normalization_op.cu.o
nvcc fatal   : Unknown option '-expt-relaxed-constexpr'
nvcc fatal   : Unknown option '-expt-relaxed-constexpr'
CMake Error at Caffe2_GPU_generated_math_gpu.cu.o.cmake:202 (message):
  Error generating
  /home/ubuntu/Works/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o

CMake Error at Caffe2_GPU_generated_transform_gpu.cu.o.cmake:202 (message):
  Error generating
  /home/ubuntu/Works/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/image/./Caffe2_GPU_generated_transform_gpu.cu.o

nvcc fatal   : Unknown option '-expt-relaxed-constexpr'
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at Caffe2_GPU_generated_context_gpu.cu.o.cmake:202 (message):
  Error generating
  /home/ubuntu/Works/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o

make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o] Error 1
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/image/./Caffe2_GPU_generated_transform_gpu.cu.o] Error 1
nvcc fatal   : Unknown option '-expt-relaxed-constexpr'
CMake Error at Caffe2_GPU_generated_local_response_normalization_op.cu.o.cmake:202 (message):
  Error generating
  /home/ubuntu/Works/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_local_response_normalization_op.cu.o

make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_local_response_normalization_op.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make: *** [all] Error 2

**Comment by xhzzhang** [comment]
When i disable option '-expt-relaxed-constexpr' in cmake/Cuda.cmake, then i got below error:

Linking CXX shared library libCaffe2_CPU.so
[ 59%] Built target Caffe2_CPU
[ 59%] [ 59%] [ 60%] [ 60%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/image/./Caffe2_GPU_generated_transform_gpu.cu.o
Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_local_response_normalization_op.cu.o
/mnt/WORK/Caffe2/src/caffe2/caffe2/core/context_gpu.cu(364): error: more than one instance of overloaded function "max" matches the argument list:
            function "max(int, int)"
            function "max(unsigned int, unsigned int)"
            function "max(int, unsigned int)"
            function "max(unsigned int, int)"
            function "max(long long, long long)"
            function "max(unsigned long long, unsigned long long)"
            function "max(long long, unsigned long long)"
            function "max(unsigned long long, long long)"
            function "max(float, float)"
            function "max(double, double)"
            function "max(float, double)"
            function "max(double, float)"
            argument types are: (caffe2::TIndex, caffe2::TIndex)

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/conversions.h(137): warning: variable "r" was declared but never referenced

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(136): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(136): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(136): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(312): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(312): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(312): error: argument of type "cudaDataType_t" is incompatible with parameter of type "cublasDataType_t"

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(496): error: identifier "cublasDotEx" is undefined

/mnt/WORK/Caffe2/src/caffe2/caffe2/utils/math_gpu.cu(740): error: identifier "cublasAxpyEx" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00000831_00000000-7_context_gpu.cpp1.ii".
CMake Error at Caffe2_GPU_generated_context_gpu.cu.o.cmake:260 (message):
  Error generating file
  /mnt/WORK/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o


make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
8 errors detected in the compilation of "/tmp/tmpxft_00000842_00000000-7_math_gpu.cpp1.ii".
CMake Error at Caffe2_GPU_generated_math_gpu.cu.o.cmake:260 (message):
  Error generating file
  /mnt/WORK/Caffe2/src/caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o


make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make: *** [all] Error 2

**Comment by pietern** [comment]
If this issue is still current, please feel free to reopen or create a new issue.

While there are some folks who successfully use Caffe2 on a TX1, I'm not familiar with their environment.
