### ISSUE TITLE
How to time the speed of each layer in caffe2?

### ISSUE THREAD

**Issue by KeyKy** [facebookarchive/caffe2#444]
How to time the speed of each layer in caffe2 and how to exclude the data layer? I want to know the speed of Alexnet run in caffe2. Could someone help me with this.

**Comment by RSly** [comment]
I m also intrested in this comparison!
@keyky, how do you calculate the timing per layer in caffe1? do you have already some benchmark scripts?

**Comment by KeyKy** [comment]
@RSly caffe1 has a tool in tools folder and you can use ./build/tools/caffe time --gpu

**Comment by KeyKy** [comment]
I have found a solution of this problem.
```
C.benchmark_net('AlexNet', 10, 10, True)
```
