### ISSUE TITLE
macOS Sierra ipython issue: Attempt to free invalid pointer

### ISSUE THREAD

**Issue by vallard** [facebookarchive/caffe2#449]
Thanks for all your work on this.  Very cool project.  I'm pretty new to all this.  I'm using anaconda and ipython 5.3.0 on macOS sierra.  When I run: 
```
In [1]: from caffe2.python import core, cnn, net_drawer, workspace, visualize
   ...: import numpy as np
   ...: from IPython import display
   ...: from matplotlib import pyplot
```
All is good, but then when I run the following I get some attempt to free invalid pointer error.  When I run in the jupyter notebook the kernel restarts. 

```
In [2]: init_net = core.Net("init")

src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7fb45371ee80
Abort trap: 6
```
Funny thing is, it works fine in my normal python environment, but to do the tutorials and all, I want to follow along with the ipython notebook.  Thanks for any help and sorry for such a dumb question.

**Comment by vallard** [comment]
still can't get this to work.  :-(

**Comment by vallard** [comment]
Ok, dumb python issue.  I had a pip installed version of ipython 5.3 that wasn't the one installed by anaconda.  pip removing the other ipython made this work. 
```
from caffe2.python import core, cnn, net_drawer, workspace, visualize
init_net = core.Net("init")
```

**Comment by wang3t** [comment]
I ran into the similar issue "src/tcmalloc.cc:283] Attempt to free invalid pointer ...", but can't find a way out. How do you locate the old ipython ?
Note: I used to use ipython on 2.7.10 & (3.4 removed) but switched to anaconda.

**Comment by anshchauhan** [comment]
I have same question...and I only have one version of ipython which was installed via anaconda. :(
