### ISSUE TITLE
CudaAllreduceHalvingDoubling writev error

### ISSUE THREAD

**Issue by sergey-serebryakov** [facebookarchive/caffe2#450]
Hi!
There's something wrong with my hardware/software setup I cannot figure out. I tried to run `resnet50_trainer.py` (no modifications) on single (2xK-80) and multiple nodes with REDIS rendezvous. It fails. In single device mode (`num_shards=1` ) it works OK.
It fails (soon after it has started) performing CudaAllReduceHalvingDoubling Gloo operation (transport - TCP). The method that fails is Pair::write in Gloo library. It turns out at some point in time, it wants to send 4096040 bytes, waits for some time (sending??? - here something is wrong), and  returning from `writev` call with number of bytes sent = 1376004. The call to Pair::write that fails is not the first one. Some previous calls work correct.
Could you guys guide me what should I pay attention to to resolve it. 
Thanks!
PS: This is what works OK:

1. Caffe and Caffe2 run OK on 1, 2 and 4 GPUs (data parallel schema).
2. p2pBandwidthTest from CUDA samples runs OK.
3. Benchmarks from Gloo library run OK.
4. Firewalls are disabled.

**Comment by sergey-serebryakov** [comment]
Have not had a chance to investigate this issue yet, but one thing that I noticed is that the code that does sending data with `writev` system call looks like [this](https://github.com/facebookincubator/gloo/blob/master/gloo/transport/tcp/pair.cc):
```
for (;;) {
    rv = writev(fd_, iov.data(), ioc);
    if (rv == -1) {
      if (errno == EAGAIN) {
        if (sync_) {
          // Blocking call returning with EAGAIN indicates timeout
          signalIoFailure(GLOO_ERROR_MSG("Write timeout ", peer_.str()));
        } else {
          // Async. This write is done.
          return false;
        }
      }

      // Retry on EINTR
      if (errno == EINTR) {
        continue;
      }

      // Unexpected error
      signalIoFailure(
          GLOO_ERROR_MSG("writev ", peer_.str(), ": ", strerror(errno)));
    }
    break;
  }
```
As I understand, however, `writev` as `write` can actually send less bytes than requested under certain conditions. This is a normal situation and can easily be handled by advancing corresponding data pointers. The relevant discussion thread is [here](https://groups.google.com/forum/#!topic/comp.unix.programmer/yvGs0TbrXLY). Will try to dig into this this weekend.

**Comment by pietern** [comment]
Thanks for bringing this to my attention on the gloo repository @sergey-serebryakov.

Closing this issue to consolidate.
