### ISSUE TITLE
Compiling on Arch Linux

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#456]
I managed to get 82% through the compilation on Arch (dependencies installed, per the [website](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) and [Installation.md](https://github.com/caffe2/caffe2/blob/master/docs/installation.md): `yaourt -S atlas-lapack cmake cuda gcc5 gflags 
google-glog gtest leveldb libpthread-stubs opencv openmp openmpi protobuf python-gflags python-pip python-pydot 
snappy` and `sudo pip install flask graphviz hypothesis jupyter matplotlib pydot python-nvd3 pyyaml requests scikit-image scipy setuptools tornado`), however, I ran into three issues:

**1:** 
`/opt/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!`

I was able to resolve this by doing:
```
export CC=/usr/sbin/gcc-5
export CXX=/usr/sbin/g++-5
```
However, this is a bad idea to do manually; it should probably be set at compile time automatically with something like:
```
 if [[ `uname -a` == *"ARCH"* ]]; then
     path_to_gcc5=$(which gcc-5)
     if [ -x "$path_to_gcc5" ]; then
       export CC="$path_to_gcc5"
     else
       echo "Warning: GCC v5 not found. CUDA v8 is incompatible with GCC v6, if installation fails, consider running \$ pacman -S gcc5"
     fi
     path_to_g++5=$(which g++-5)
     if [ -x "$path_to_g++5" ]; then
       export CXX="$path_to_g++5"
     else
       echo "Warning: GCC v5 not found. CUDA v8 is incompatible with GCC v6, if installation fails, consider running \$ pacman -S gcc5"
     fi
 fi
```
**2:**
Despite having installed `gflags` and `python-gflags` earlier, gflags isn't detected; I'm not certain why, I was not able to resolve this issue. 

```
-- Could NOT find GFlags (missing:  GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)
CMake Warning at cmake/External/gflags.cmake:10 (message):
  gflags is not found.  Caffe2 will build without gflags support but it is
  strongly recommended that you install gflags.
Call Stack (most recent call first):
  cmake/External/glog.cmake:2 (include)
  cmake/Dependencies.cmake:64 (include)
  CMakeLists.txt:85 (include)
```

**3:**
This one is a bit beyond me. I'm not sure what's going wrong.
```
[ 82%] Building CXX object caffe2/CMakeFiles/fb_run_plan_mpi.dir/binaries/fb_run_plan_mpi.cc.o
/home/junko/caffe2/caffe2/binaries/fb_run_plan_mpi.cc: In function ‘int main(int, char**)’:
/home/junko/caffe2/caffe2/binaries/fb_run_plan_mpi.cc:59:7: error: ‘FLAGS_plan’ was not declared in this scope
   if (FLAGS_plan == "") {
       ^
/home/junko/caffe2/caffe2/binaries/fb_run_plan_mpi.cc:59:7: note: suggested alternative:
In file included from /home/junko/caffe2/caffe2/core/init.h:5:0,
                 from /home/junko/caffe2/caffe2/binaries/fb_run_plan_mpi.cc:10:
/home/junko/caffe2/caffe2/core/flags.h:118:10: note:   ‘caffe2::FLAGS_plan’
     type FLAGS_##name = default_value;                                         \
          ^
/home/junko/caffe2/caffe2/core/flags.h:142:3: note: in expansion of macro ‘CAFFE2_DEFINE_typed_var’
   CAFFE2_DEFINE_typed_var(string, name, default_value, help_str)
   ^
/home/junko/caffe2/caffe2/binaries/fb_run_plan_mpi.cc:20:1: note: in expansion of macro ‘CAFFE2_DEFINE_string’
 CAFFE2_DEFINE_string(plan, "", "The given path to the plan protobuffer.");
 ^
make[3]: *** [caffe2/CMakeFiles/fb_run_plan_mpi.dir/build.make:63: caffe2/CMakeFiles/fb_run_plan_mpi.dir/binaries/fb_run_plan_mpi.cc.o] Error 1
make[3]: Leaving directory '/home/junko/caffe2/build'
make[2]: *** [CMakeFiles/Makefile2:1652: caffe2/CMakeFiles/fb_run_plan_mpi.dir/all] Error 2
make[2]: Leaving directory '/home/junko/caffe2/build'
make[1]: *** [Makefile:139: all] Error 2
make[1]: Leaving directory '/home/junko/caffe2/build'
make: *** [Makefile:4: all] Error 2
```

**Comment by thyu** [comment]
For (3) it is probably some minor bugs:
```
--- a/caffe2/binaries/fb_run_plan_mpi.cc
+++ b/caffe2/binaries/fb_run_plan_mpi.cc
@@ -56,7 +56,7 @@ int main(int argc, char** argv) {
 
   // Only check if plan is specified AFTER MPI setup such that we can test
   // whether or not MPI setup works without having a plan to run.
-  if (FLAGS_plan == "") {
+  if (caffe2::FLAGS_plan == "") {
     std::cerr << "No plan defined! Exiting...\n";
     return 0;
   }
```

**Comment by dbermond** [comment]
For 1:
CMake doesn't like the autoconf environment variables. For CMake you should use its own options:
```
-DCMAKE_CXX_COMPILER=/usr/bin/g++-5 \
-DCMAKE_C_COMPILER=/usr/bin/gcc-5 \
-DCUDA_HOST_COMPILER:FILEPATH=/usr/bin/gcc-5
```

For 2:
Place the source tree of all third party components in their corresponding subdirectories inside the `third_party` directory and all these _not found_ warnings will be gone.

If you want something ready to go, I started to maintain caffe2 packages for Arch Linux on the [AUR](https://aur.archlinux.org/). They are as follows:

**caffe2** (release version, gpu enabled):
[https://aur.archlinux.org/packages/caffe2/](https://aur.archlinux.org/packages/caffe2/)

**caffe2-git** (git master version, gpu enabled):
[https://aur.archlinux.org/packages/caffe2-git/](https://aur.archlinux.org/packages/caffe2-git/)

**caffe2-cpu** (release version, cpu only):
[https://aur.archlinux.org/packages/caffe2-cpu/](https://aur.archlinux.org/packages/caffe2-cpu/)

**caffe2-cpu-git** (git master version, cpu only):
[https://aur.archlinux.org/packages/caffe2-cpu-git/](https://aur.archlinux.org/packages/caffe2-cpu-git/)

**Comment by sleeplessai** [comment]
So lucky! It's glad to see caffe2-* version on AUR... so kind of it ...

**Comment by dbermond** [comment]
@daydreamcoder 
Enjoy :)

**Comment by ghost** [comment]
It's nice that it's on the AUR, but I feel it's probably best that 1 and 3 are fixed in the caffe2 upstream so we're not relying on an external maintainer that may eventually not have the time/ability to update it, or making manual edits every time.

**Comment by dbermond** [comment]
@Hikari-chin 
In my humble opinion, there is nothing to fix in 1 by upstream.
CUDA stuff currently will not compile with gcc6 or later because CUDA 8.0 requires gcc5. That's not related to Caffe2, but to CUDA. So using CMake options to tell it to use gcc5 seems the way to go.

Regarding 3, I can't say for sure, but I have a felling that placing third_party components in the expected folders will solve it too. I made a horde of compilation tests and this error never appeared to me. Just a felling.

edit: fixed typo

**Comment by pietern** [comment]
We can add a check for gcc-5 in the CMake files. It will become the default on more and more systems as time goes on, so having a check doesn't hurt.

As for 3, the file is not used by anything, so removing it.

Thanks for reporting and pitching in :+1:

**Comment by pietern** [comment]
Addressing 1 in #504.
