### ISSUE TITLE
Ubuntu,make error!

### ISSUE THREAD

**Issue by MrZhangCF** [facebookarchive/caffe2#460]
Freshman,new to the caffe2. meet this error,what should i do? plz~~
![22](https://cloud.githubusercontent.com/assets/26785691/25561220/70a20308-2d99-11e7-9b6d-7a999bb1832b.png)

**Comment by sergey-serebryakov** [comment]
Does it say that `sleep_for` is not a member of `std::this_thread`? What versions of Ubuntu and gcc do you have?

**Comment by MrZhangCF** [comment]
Ubuntu 16.04  gcc4.7

**Comment by sergey-serebryakov** [comment]
You can try to pass `_GLIBCXX_USE_NANOSLEEP` flag to your compiler. Some details are explained [here](http://stackoverflow.com/questions/12523122/what-is-glibcxx-use-nanosleep-all-about).

**Comment by MrZhangCF** [comment]
@sergey-serebryakov  thanks for your advice,i update my gcc to the version 5.4,and it works right now!

**Comment by sleeplessai** [comment]
看来Ubuntu得天独厚啊，换到Ubuntu 17.04了。

**Comment by pietern** [comment]
@MrZhangCF Sounds like this is resolved. Closing the issue.
