### ISSUE TITLE
Windows 10: error in lmdb.cc

### ISSUE THREAD

**Issue by matzeox** [facebookarchive/caffe2#462]
Hello together,

there seems to be an error in the file lmdb.cc in line 141, when you compile it under windows respectively VS2015:
```
if (mode == NEW) {
    CAFFE_ENFORCE_EQ(
        mkdir(source.c_str(), 0744), 0, "mkdir ", source, " failed");
  }
```
The function mkdir is deprecated in VS (see: https://msdn.microsoft.com/en-us/library/ms235326.aspx). Thus, I get an error if I compile caffe2 with lmdb support. A possible fix at least in VS could be:

```
  if (mode == NEW) {
    CAFFE_ENFORCE_EQ(
        _mkdir(source.c_str()), 0, "mkdir ", source, " failed");
  }
```

**Comment by sleeplessai** [comment]
Maybe you can compile lmdb though sources, have you tried this ?

**Comment by gfursin** [comment]
I encountered the same problem on Windows 10. LMDB compiled from sources (I use [ctuning/ck](CK package manager) to compile all Caffe deps from sources on Windows ) but it seems to be unrelated. As @matzeox said mkdir is "_mkdir" on Windows, but you also need to have direct.h included. I created a pull request which should hopefully fix that: https://github.com/caffe2/caffe2/pull/539
