### ISSUE TITLE
build ios failed

### ISSUE THREAD

**Issue by xuefeng7** [facebookarchive/caffe2#465]
Running build_ios.sh failed with error:

`
Caffe2 codebase root is: /Users/xxx/xxx/caffe2-master
Build Caffe2 ios into: /Users/xxx/xxx/caffe2-master/build_ios
Building protoc
/Users/xxx/xxx/caffe2-master/scripts/build_host_protoc.sh: line 18: 
/Users/xxx/xxx/caffe2-master/third_party/protobuf/cmake: No such file or directory
third_party/protobuf/cmake: No such file or directory
`

Operating System: MacOS 10.12.3

**Comment by bwasti** [comment]
`git submodule init && git submodule update` should fix it, feel free to reopen if it doesn't!
