### ISSUE TITLE
caffe/caffe2 Performance benchmark.

### ISSUE THREAD

**Issue by yoershine** [facebookarchive/caffe2#473]
I have tested the forward-only performance comparison between caffe and caffe2. Below is the results:
The caffe tests follows soumith's way, while caffe2 tests follows python/convnet_benchmarks.py。

Unit: ms
Env: I7-4790K 8 Core 32G Memory

Results are the average forward-only time by executing 10 iterations.

|Framework|alexnet|googlenet |overfeat  |   vggnet |squeezenet	|
| ------|------|------|------|------|------|
|caffe		|415.3	 	|10109	|8917.99	|14020.1	|22.4192	|
caffe2	|87.3275	|	560.776	|217.623	|342.77	|46.9 |

I'm wonder that why caffe2 is 20 times faster than caffe  in some networks. However, caffe2 is almost 2 times slower than caffe when executing squeezenet.  Is there problems in my test results? And can you give me some tips on how caffe2's acceleration works?

**Comment by bwasti** [comment]
I went ahead and reformatted your comment for clarity.  Would you mind linking to the exact tests you ran and specifying the command line arguments?

**Comment by yoershine** [comment]
Caffe tests command line is like below:
` ./caffe/build/tools/caffe time --model=./imagenet_winners/alexnet.prototxt --iterations=10  `
`./caffe/build/tools/caffe time --model=./imagenet_winners/overfeat.prototxt --iterations=10`
`./caffe/build/tools/caffe time --model=./imagenet_winners/vgg_a.prototxt --iterations=10 `
`./caffe/build/tools/caffe time --model=./imagenet_winners/googlenet.prototxt --iterations=10  `

Caffe2 tests command line is like below:
` python convnet_benchmarks.py --batch_size 1 --model AlexNet  --cpu --forward_only True ` 
` python convnet_benchmarks.py --batch_size 1 --model OverFeat  --cpu --forward_only True ` 
` python convnet_benchmarks.py --batch_size 1 --model VGGA  --cpu --forward_only True ` 
` python convnet_benchmarks.py --batch_size 1 --model Inception  --cpu --forward_only True ` 

Here is the convnet_benchmarks I used. I have added squeezenet symbol into it.
[convnet_benchmarks.txt](https://github.com/caffe2/caffe2/files/969513/convnet_benchmarks.txt)

**Comment by austingg** [comment]
@yoershine What about the batchsize in the benchmark of caffe? If the alexnet.prototxt is just from the caffe model (or for ImageNet challenge) , the default batch size is 10.

**Comment by yoershine** [comment]
@austingg. The batch size is indeed 10. I used alexnet.deploy rather than alexnet.trainprototxt.

**Comment by twmht** [comment]
@yoershine 

why closing this issue?

**Comment by mattgruenke** [comment]
> @yoershine
> 
> why closing this issue?

Because batching has a substantial impact on performance.  It would've been nice if @yoershine had repeated the caffe2 tests with `--batch_size 10` and posted _those_ results.
