### ISSUE TITLE
Caffe Translator Error: Crop

### ISSUE THREAD

**Issue by lbin** [facebookarchive/caffe2#475]
I tried to convert a segnet from caffe to caffe2, but there is no crop translator, how to translate this layer?

**Comment by iteal** [comment]
Same here! I would like to convert this network :
https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/

google.protobuf.text_format.ParseError: 38:80 : Enum type "caffe.V1LayerParameter.LayerType" has no value named CROP.

**Comment by futurely** [comment]
Unofficial layers have to converted with custom function.
```python
@TranslatorRegistry.Register("Crop")
def TranslateCrop(layer, pretrained_blobs, is_test):
```
https://github.com/caffe2/caffe2/blob/master/caffe2/python/caffe_translator.py#L379

**Comment by aaronmarkham** [comment]
Would going from Crop to the ImageInput Op work for you?
https://caffe2.ai/docs/operators-catalogue.html#imageinput

**Comment by Kowasaki** [comment]
I need to translate a couple of crop layers from a FCN (https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/voc-fcn8s). Can someone provide me an example of what this function would look like given a layer such as:

`layer {
  name: "score"
  type: "Crop"
  bottom: "upscore8"
  bottom: "data"
  top: "score"
  crop_param {
    axis: 2
    offset: 31
  }
}`

@aaronmarkham any tips on using the imageinput op would be greatly appreciated!

**Comment by gsrujana** [comment]
Hi, I am facing the same problem trying to convert ResNet 152. Were any of you successful with the translation? Any help would be appreciated! Thank you

**Comment by steven5401** [comment]
I have same problem as you. Is there any example with ImageInput Op?

**Comment by beichen2012** [comment]
Any solution??????????????????????????
