### ISSUE TITLE
An error occurred  when running resnet50_trainer.py on multi-machine

### ISSUE THREAD

**Issue by ing907** [facebookarchive/caffe2#476]
Hello.

I'm trying to train ResNet-50 with CAFFE2 model on multi-machine environment refer to the guideline. (https://caffe2.ai/docs/distributed-training.html)

I installed CAFFE2 successfully but faced some problems.

1.  
I ran the example with :

python resnet50_trainer.py --train_data PATH --gpus 0 --batch_size 32 --num_labels 10 --epoch_size 50000 --num_epoch 10 -- numshards 2 -- shard_id 0 -- reds_host IP_OF_HOST --redis_port PORT_OF_HOST

But I face an error with below message

![th_kakaotalk_photo_2017-05-02-16-31-43](https://cloud.githubusercontent.com/assets/26485491/25619406/b31aaa62-2f85-11e7-896e-2ff96763e0e6.png)

I found that Operator 'RedusStoreHandlerCreate' seems not registered.
Is that the cause of the error?

2. The object file of redis_store_handler_op_gpu doesn't exist in my CAFFE2/build folder while file_store_handler_op_gpu exists.

**Would someone inform me why it isn't put this into makefile list. And how to fix the error.**

Did developers just forget this or is there a problem so they couldn't register it?
<img width="867" alt="2017-05-02 4 24 36" src="https://cloud.githubusercontent.com/assets/26485491/25619274/407b29fa-2f85-11e7-9b06-7d2712c7ca8f.png">

3.
I also tried it by using NFS but it also doesn't work.
**Would you tell us what’s wrong and how to fix it.**

<img width="876" alt="2017-05-02 4 26 36" src="https://cloud.githubusercontent.com/assets/26485491/25619140/beb60ca0-2f84-11e7-98a1-f03744072ec0.png">

**Comment by sergey-serebryakov** [comment]
Could you check that you've installed `libhiredis-dev` (Ubuntu) or `hiredis-devel` (RedHat, CentOS) and compiled Caffe2 with -DUSE_REDIS=ON (the output of configure will tell if Caffe is actually about to be linked against hiredis library.
Can I ask you for something else? Could you please share if you will successfully run Caffe2 in distributed environment? I am observing some weird errors in `Gloo` library and cannot figure out what the cause is. Thanks!

**Comment by sergey-serebryakov** [comment]
Ohh, I did not pay attention to your last screenshot. It seems I am observing the same issue - write must always succeed in sync mode. I asked the question [here](https://github.com/caffe2/caffe2/issues/450).

**Comment by ambujpd** [comment]
@sergey-serebryakov @pietern 
I'm facing issue while running multi-machine with redis. I have redis installed and compiled Caffe2 with redis support.

Command:
`python resnet50_trainer.py --train_data=<PATH> --num_shards=2 --shard_id=0 --run_id=10 --redis_host=172.17.27.13 --redis_port=6379`

Error:
```
Traceback (most recent call last):
  File "resnet50_trainer.py", line 395, in <module>
    main()
  File "resnet50_trainer.py", line 391, in main
    Train(args)
  File "resnet50_trainer.py", line 315, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/nfs/AMBUJ/Caffe2_LatestGLOO4_redis/caffe2/build/caffe2/python/workspace.py", line 161, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at redis_store_handler.cc:45] reply->integer == 1. 0 vs 1. Value at allreduce_0_cw_op/0/1 was already set Error from operator:
input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
```
Individually, redis works and I've tested a master/slave connection on two machines.

**Comment by sergey-serebryakov** [comment]
@talk2ap001 I think the reason is that every run must have its own unique identifier (in your case - `--run_id=10`). You can either try to use different ID or flush database. In my experiments (in which I have not succeeded yet), I just flush entire database in scripts used to run workers.

**Comment by ambujpd** [comment]
@sergey-serebryakov 
Ok, thanks. Using a different Run ID produced the same error with redis:
`what(): [enforce fail at /nfs/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:691] rv. Write must always succeed in sync mode`

**Comment by sergey-serebryakov** [comment]
@talk2ap001 Ok, it seems there are at least 4 people who get this error message. BTW, in the latest version of `glow` you'll see different error (timeout) which is basically the same.

**Comment by pietern** [comment]
Thanks for helping out investigating/triaging this @sergey-serebryakov and @talk2ap001.

**Comment by pietern** [comment]
Let's continue in #360.

**Comment by leye7755** [comment]
@ing907 hey, could you tell us how you solve this problem finally?thank you so much
