### ISSUE TITLE
Installation Errors on CentOS

### ISSUE THREAD

**Issue by aplumb3000** [facebookarchive/caffe2#478]
I've already installed the original caffe on this machine following the original instructions successfully.  Our devs now want to try Caffe2.  I've performed all of the steps, but when I try the cd build && cmake3 ..
" step, I get the following error:

CMake Error at proto/CMakeLists.txt:7 (caffe2_protobuf_generate_cpp_py):
  Unknown CMake command "caffe2_protobuf_generate_cpp_py".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.6)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/developer/caffe-deps/caffe2/caffe2/build/CMakeFiles/CMakeOutput.log".

Help please!

Thanks

**Comment by bwasti** [comment]
hmm, it sounds like you are not in the right directory.  make sure you are in the top level of the repo before creating a build folder.  there is also a useful makefile that you can use instead.

this is the command I used to build caffe2:
`git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2 && make`

feel free to reopen if this does not fix the issue
