### ISSUE TITLE
build iOS failed even after updating submodule

### ISSUE THREAD

**Issue by xuefeng7** [facebookarchive/caffe2#480]
Running

`./scripts/build_ios.sh`

returns

`
Caffe2 codebase root is: /Users/XXX/XXX/Projects/Caffe2+iOS/caffe2
Build Caffe2 ios into: /Users/XXX/XXX/Projects/Caffe2+iOS/caffe2/build_ios
Building protoc
Other flags passed to cmake: -DCMAKE_C_FLAGS=-fembed-bitcode -DCMAKE_CXX_FLAGS=-fembed-bitcode
/Users/XXX/XXX/Projects/Caffe2+iOS/caffe2/scripts/build_host_protoc.sh: line 40: /Users/XXX/XXX/Projects/Caffe2+iOS/caffe2/third_party/protobuf/cmake: is a directory
`

I tried `git submodule init && git submodule update`, but still get this issue.

**Comment by abjurato** [comment]
Just a guess: that can happen because of "+" in path. Could you try with placing caffe2 into another directory, without "+" in path?

**Comment by bwasti** [comment]
this is quite a cryptic error (going to leave this issue open until it is changed) but it is because you don't have cmake installed (or at least the bash script can't find it).

either install homebrew and do `brew install cmake` or check out https://cmake.org/install/

hope that fixes it :)

**Comment by xuefeng7** [comment]
That's true, it works after installing cmake... Thanks!
