### ISSUE TITLE
Caffe Translator Fails 

### ISSUE THREAD

**Issue by afshindn** [facebookarchive/caffe2#482]
I tried the translator on a costume model and I got the following error. The same error with pre-trained model provided in model zoo. 

python -m caffe2.python.caffe_translator deploy.prototxt model.caffemodel

INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer relu1
INFO:caffe_translator:Translate layer norm1
INFO:caffe_translator:Translate layer conv2
INFO:caffe_translator:Translate layer relu2
INFO:caffe_translator:Translate layer norm2
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer conv3
INFO:caffe_translator:Translate layer relu3
INFO:caffe_translator:Translate layer pool2
INFO:caffe_translator:Translate layer conv4
INFO:caffe_translator:Translate layer relu4
INFO:caffe_translator:Translate layer pool3
INFO:caffe_translator:Translate layer conv5
INFO:caffe_translator:Translate layer relu5
INFO:caffe_translator:Translate layer pool4
INFO:caffe_translator:Translate layer fc
INFO:caffe_translator:Translate layer prob
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
  "__main__", fname, loader, pkg_name)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
  exec code in run_globals
File "/usr/local/caffe2/python/caffe_translator.py", line 612, in <module>
  init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
File "/usr/local/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
  utils.MakeArgument("values", tensor.float_data)])
File "/usr/local/caffe2/python/utils.py", line 101, in MakeArgument
  (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[-0.22154687345027924,

**Comment by sherifshehata** [comment]
I have the same error, which looks like:


`ValueError: Unknown argument type: key=values value=[0.11257877945899963, ..., 0.13431508839130402], value type=<class'google.protobuf.internal.containers.RepeatedScalarFieldContainer'>`


Do you have the same type in your error?

**Comment by afshindn** [comment]
Yes mine is the same.

**Comment by sherifshehata** [comment]
My guess is that it is an issue with protobuf, since it fails from the first iteration in "ConvertTensorProtosToInitNet". But i am not able to pinpoint the exact problem.

**Comment by xhsoldier** [comment]
I met the same error, any solutions?

**Comment by xhsoldier** [comment]
when running: python -m caffe2.python.caffe_translator deploy.prototxt bvlc_alexnet.caffemodel 
Any ideas?
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/caffe2/python/caffe_translator.py", line 723, in <module>
    init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
  File "/usr/local/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
    utils.MakeArgument("values", tensor.float_data)])
  File "/usr/local/caffe2/python/utils.py", line 101, in MakeArgument
    (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[-0.02831534668803215, -0.0067626256495714188, ..., -0.040649808943271637], value type
=<class 'google.protobuf.internal.containers.RepeatedScalarFieldContainer'>
```

**Comment by hallelulius** [comment]
Had the same issue and solved it with:
`pip install --upgrade protobuf`

**Comment by afshindn** [comment]
@hallelulius: You're right.  I did the same but forgot to post it here. I was running on `2.6.1` and upgraded to `3.3.0`
```
brew upgrade protobuf
```
I had to build caffe2 again after upgrading protobuf. 

I'll go ahead and close this issue.

**Comment by gjm441** [comment]
@afshindn Thanks.I met the same problem, and fixed it as you said. Upgrade the protobuf to 3.3.0, and keep the protoc and python-protobuf  the same version.

**Comment by whasyt** [comment]
The root cause is Util can't recognize type of class'google.protobuf.internal.containers.RepeatedScalarFieldContainer', while arrays can be recognized by Util.

You can just change

> utils.MakeArgument("values", tensor.float_data)

to

> utils.MakeArgument("values", tensor.float_data._values)

Hope it helps.
