### ISSUE TITLE
How to save model as init_net.pb and predict_net.pb

### ISSUE THREAD

**Issue by lzx1413** [facebookarchive/caffe2#487]
I follow the tutorial https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST-light.ipynb and I want to know how to save the trained models like models in the model zoo. Anyone can help me? thanks.

**Comment by sergey-serebryakov** [comment]
Just a guess
```
with open(file_name, "wb") as f:
    f.write(net_def.SerializeToString())
```

**Comment by bwasti** [comment]
Quick overview:
Predictors take in an init_net and a predict_net.  In python [Predictor](https://github.com/caffe2/caffe2/blob/master/caffe2/python/pybind_state.cc#L545) takes in raw, unparsed protobufs and in C++ [Predictor](https://github.com/caffe2/caffe2/blob/master/caffe2/core/predictor.cc#L34) takes in the NetDefs themselves.  For both the interface is the same: init_net.pb is run once on instantiation and predict_net.pb is run with Predictor.{r,R}un in {Python, C++}.

The input to the run function is a vector of tensors (list of arrays in Python).  This vector populates the predict_net's [external_inputs](https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2.proto#L203) in order (such that if you pass in only 1 tensor but there are 2 external_inputs only the first is populated and the rest are presumably handled by init_net).  Here's an [example of using the C++ interface](https://github.com/bwasti/AICamera/blob/master/app/src/main/cpp/native-lib.cpp#L131-L135).

That being said, you can create init_nets and predict_nets in various ways as long as you follow that convention.  I am working on a Python helper that takes in one trained network and splits it into init_net and predict_net and will close this issue once that lands.

**Comment by raininglixinyu** [comment]
@bwasti @lzx1413 I am also curious about that, i'm trying to do the inference work on my iphone, so the init_net.pb and predict_net.pb is necessary right？

**Comment by dongliya** [comment]
我也想知道咋整，不知道该怎么输出模型呀......

**Comment by wannabehero** [comment]
@bwasti any progress on the Python helper?

May be you can just explain how one can convert the net (e.g. from MNIST example mentioned above) to init_net.pb and predict_net.pb?

It looks like init_net might be model.param_init_net.Proto() serialized to string? Or it's model.net.Proto()?
Then what is predict_net exactly? Because essentially model after the training contains weights for each parameter. Should we serialize these weights and biases? So it can then can be re-constructed by the predictor?

**Comment by dongliya** [comment]
@bwasti @spronin +1

**Comment by raininglixinyu** [comment]
@bwasti @spronin +1

**Comment by ThomasGueldner** [comment]
@bwasti @spronin +1

**Comment by lzx1413** [comment]
https://github.com/caffe2/caffe2/blob/master/caffe2/python/predictor/mobile_exporter.py
