### ISSUE TITLE
Error generating  gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o

### ISSUE THREAD

**Issue by Dasona** [facebookarchive/caffe2#488]
Is this wrong with cuda version ? 
I use cuda 8.0.

This is my error log .

[ 20%] Building CXX object third_party/benchmark/test/CMakeFiles/reporter_output_test.dir/reporter_output_test.cc.o
Building CXX object third_party/benchmark/test/CMakeFiles/skip_with_error_test.dir/skip_with_error_test.cc.o
cc: error trying to exec 'cc1plus': execvp: No such file or directory
CMake Error at gloo_cuda_generated_nccl.cu.o.cmake:202 (message):
  Error generating
  /home/mxnet/caffe2/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o

make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o] Error 1
make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable multiple_ranges_test
Linking CXX executable options_test
[ 20%] Built target multiple_ranges_test
[ 20%] Built target options_test
Linking CXX executable register_benchmark_test
[ 20%] Built target register_benchmark_test
Linking CXX executable skip_with_error_test
[ 20%] Built target skip_with_error_test
Linking CXX executable reporter_output_test
[ 20%] Built target reporter_output_test
[ 20%] Built target Caffe2_PROTO
[ 20%] Built target Caffe_PROTO
make: *** [all] Error 2

**Comment by bwasti** [comment]
This seems like a compiler issue, or an issue with gloo.  Here is a [related issue](http://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory).  If that does not help and the issue can't be resolved on the [gloo github](https://github.com/facebookincubator/gloo), feel free to reopen this issue.
