### ISSUE TITLE
Error in Example on Website

### ISSUE THREAD

**Issue by tarunjainsagar** [facebookarchive/caffe2#490]
@aaronmarkham Add the **workspace.CreateNet(net)** in the **last example** at page https://caffe2.ai/docs/tutorial-basics-of-caffe2.html as shown below:

```
# It seems that %timeit magic does not work well with
# C++ extensions so we'll basically do for loops
start = time.time()
for i in range(1000):
    workspace.RunNetOnce(net)
end = time.time()
print('Run time per RunNetOnce: {}'.format((end - start) / 1000))

start = time.time()
```
`**workspace.CreateNet(net)**`
```
for i in range(1000):
    workspace.RunNet(net.Proto().name)
end = time.time()
print('Run time per RunNet: {}'.format((end - start) / 1000))
```

**Comment by tarun1325** [comment]
Also, Update the same at this tutorial : https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Basics.ipynb

**Comment by tarunjainsagar** [comment]
Also, update on this page https://caffe2.ai/docs/tutorial-MNIST.html
Code Block No. 3 - for downloading data

Making the changes shown below won't give error if we run this code snippet multiple times

Add at Line No. 11
```
leveldb_train_folder = os.path.join(data_folder, 'mnist-train-nchw-leveldb')
leveldb_test_folder = os.path.join(data_folder, 'mnist-test-nchw-leveldb')
```
Add At Line No. 32-33
```
# Generate the leveldb database
if not os.path.exists(leveldb_train_folder):
        GenerateDB(image_file_train, label_file_train, "mnist-train-nchw-leveldb")

if not os.path.exists(leveldb_test_folder):
        GenerateDB(image_file_test, label_file_test, "mnist-test-nchw-leveldb")

```

**Comment by aaronmarkham** [comment]
[Fixed](https://github.com/caffe2/caffe2/commit/6f454c93f7f77c62498b23e232cf7249bc8732a2)
