### ISSUE TITLE
Executable linker error: undefined reference to google::FlagRegisterer::FlagRegisterer

### ISSUE THREAD

**Issue by peterneher** [facebookarchive/caffe2#491]
Hi everyone,

when building Caffe2 I get linker erros of the following kind: 
`CMakeFiles/make_cifar_db.dir/binaries/make_cifar_db.cc.o: In function __static_initialization_and_destruction_0(int, int):
/src/Caffe2/caffe2/binaries/make_cifar_db.cc:20: undefined reference to google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)`

The same errors occur for all executables that are linked. I attached the full output. Any idea what might be causing this?

Cheers,
Peter
[Caffe2Errors.log.zip](https://github.com/caffe2/caffe2/files/972906/Caffe2Errors.log.zip)

**Comment by bwasti** [comment]
Hey Peter,

What platform, compiler and version of cmake are you using?

**Comment by peterneher** [comment]
Hi, I,'m using Ubuntu 16.04 and cmake 3.5.1

**Comment by peterneher** [comment]
libgflags-dev and libgflags2v5 is version 2.1.2-3

**Comment by peterneher** [comment]
Seems to be a gfalgs version issue. If I build 2.2 from source Caffe2 builds fine. 
Some of the third party projects needed for Caffe2 are built automatically during the Caffe2 build, right? E.g. gloo. Maybe gfalgs should also be included there.

**Comment by matzeox** [comment]
I have a similiar problem if i build caffe2 with Gflags (without gflags caffe2 builds without errors).
I use gflags 2.2.0 and it was built from source.

```
7>C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2\core\blob_serialization.cc(12): error C2059: syntax error: 'constant'
7>C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2\core\blob_serialization.cc(12): warning C4273: 'fLI::FLAGS_caffe2_tensor_chunk_size': inconsistent dll linkage
7>  C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2/core/blob_serialization.h(15): note: see previous definition of 'FLAGS_caffe2_tensor_chunk_size'
7>C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2\core\blob_serialization.cc(12): error C2512: 'google::FlagRegisterer': no appropriate default constructor available
7>  C:\VSIDependencies\x64\vs2015\gflags-2.2.0\Include\gflags/gflags.h(432): note: see declaration of 'google::FlagRegisterer'
7>C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2\core\blob_serialization.cc(9): error C2143: syntax error: missing ';' before ','
7>C:\Users\ochs\Workspace\Sources\caffe2-master\caffe2\core\blob_serialization.cc(9): error C2059: syntax error: ','
```
The same error occurs in many other files as well, but I have posted only one example. It seems to me that there is an error/bug/conflict in core/flags.h if you build caffe2 with gflags support.

**Comment by gfursin** [comment]
I have the same issue when building caffe2 on Windows 10 with gflags 2.2.0 built from sources (trying to use [Collective Knowledge package manager](https://github.com/ctuning/ck) with VS2015). For now had to turn gflags off to continue (-DUSE_GFLAGS=OFF). Now face #462 issue :( ...

**Comment by SniperZhao** [comment]
@matzeox have you fix that problem?

**Comment by pjh5** [comment]
I think this error is the same as #1980

**Comment by yanxiangyi** [comment]
If you're using conda, try `conda uninstall gflags`.
