### ISSUE TITLE
Compiling on ubuntu 16.04

### ISSUE THREAD

**Issue by NHZlX** [facebookarchive/caffe2#492]
home/xzl/hg/caffe/caffe2/caffe2/queue/rebatching_queue.cc:66:76: error: ‘split’ function uses ‘auto’ type specifier without trailing return type
 auto split(CPUContext& context, const std::vector<const TensorCPU*>& inputs) {
                                                                            ^
/home/xzl/hg/caffe/caffe2/caffe2/queue/rebatching_queue.cc:66:76: note: deduced return type only available with -std=c++1y or -std=gnu++1y
[ 81%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/sgd/adagrad_op.cc.o
[ 81%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/sgd/rmsprop_op.cc.o
caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:3458: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/queue/rebatching_queue.cc.o' failed
make[3]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/queue/rebatching_queue.cc.o] Error 1
make[3]: *** 正在等待未完成的任务....
make[3]: Leaving directory '/home/xzl/hg/caffe/caffe2/build'
CMakeFiles/Makefile2:1284: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make[2]: Leaving directory '/home/xzl/hg/caffe/caffe2/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/xzl/hg/caffe/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

There must be something about c++ 11, but I don't know where to configure it?

**Comment by notimesea** [comment]
You can fix it by changing `c++11` to `c++14` in this line https://github.com/caffe2/caffe2/blob/master/CMakeLists.txt#L105

**Comment by NHZlX** [comment]
@notimesea  thanks, it works
