### ISSUE TITLE
macOS 10.12.4 Build Error

### ISSUE THREAD

**Issue by winterbesos** [facebookarchive/caffe2#493]
[  0%] Built target python_copy_files
[  1%] Built target gmock
[  2%] Built target gmock_main
[  3%] Built target gtest
[  3%] Built target gtest_main
[  8%] Built target benchmark
[  8%] Built target cxx03_test
[  9%] Built target output_test_helper
[ 10%] Built target reporter_output_test
[ 10%] Built target map_test
[ 11%] Built target register_benchmark_test
[ 11%] Built target multiple_ranges_test
[ 12%] Built target fixture_test
[ 12%] Built target donotoptimize_test
[ 13%] Built target complexity_test
[ 14%] Built target skip_with_error_test
[ 15%] Built target filter_test
[ 16%] Built target basic_test
[ 17%] Built target options_test
[ 17%] Built target benchmark_test
[ 18%] Built target diagnostics_test
[ 18%] Built target Caffe_PROTO
[ 22%] Built target Caffe2_PROTO
[ 22%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/queue/rebatching_queue.cc.o
/XXX/caffe2/caffe2/queue/rebatching_queue.cc:66:1: error: 'auto' return without trailing return type; deduced return
      types are a C++14 extension
auto split(CPUContext& context, const std::vector<const TensorCPU*>& inputs) {
^
/XXX/caffe2/caffe2/queue/rebatching_queue.cc:94:10: error: no viable conversion from returned value of type
      'std::vector<std::vector<TensorCPU> >' (aka 'vector<vector<Tensor<caffe2::CPUContext> > >') to function return type 'int'
  return outputs;
         ^~~~~~~
/XXX/caffe2/caffe2/queue/rebatching_queue.cc:176:18: error: no viable overloaded '='
  splittedInputs = split(context, inputs);
  ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:553:13: note:
      candidate function not viable: no known conversion from 'int' to 'const
      std::__1::vector<std::__1::vector<caffe2::Tensor<caffe2::CPUContext>, std::__1::allocator<caffe2::Tensor<caffe2::CPUContext> > >,
      std::__1::allocator<std::__1::vector<caffe2::Tensor<caffe2::CPUContext>, std::__1::allocator<caffe2::Tensor<caffe2::CPUContext> >
      > > >' for 1st argument
    vector& operator=(const vector& __x);
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:565:13: note:
      candidate function not viable: no known conversion from 'int' to
      'std::__1::vector<std::__1::vector<caffe2::Tensor<caffe2::CPUContext>, std::__1::allocator<caffe2::Tensor<caffe2::CPUContext> >
      >, std::__1::allocator<std::__1::vector<caffe2::Tensor<caffe2::CPUContext>,
      std::__1::allocator<caffe2::Tensor<caffe2::CPUContext> > > > >' for 1st argument
    vector& operator=(vector&& __x)
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:572:13: note:
      candidate function not viable: no known conversion from 'int' to 'initializer_list<value_type>' (aka
      'initializer_list<std::__1::vector<caffe2::Tensor<caffe2::CPUContext>, std::__1::allocator<caffe2::Tensor<caffe2::CPUContext> > >
      >') for 1st argument
    vector& operator=(initializer_list<value_type> __il)
            ^
3 errors generated.
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/queue/rebatching_queue.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make: *** [all] Error 2

**Comment by Shoshin23** [comment]
This is EXACTLY the same error I'm getting. I was just about to open a ticket for this. Would love some help on this!

**Comment by bwasti** [comment]
this should be [fixed](https://github.com/caffe2/caffe2/commit/ba4c9977c5e76f5dd51bcf762f9ba5dd4a6e9fcc)

feel free to reopen if that is not the case :)

**Comment by Shoshin23** [comment]
Hey @bwasti, this works for me. Was able to build caffe2 for ios successfully. Thanks!
