### ISSUE TITLE
error occurred in the CMake phase when run build_android.sh

### ISSUE THREAD

**Issue by dyt001** [facebookarchive/caffe2#494]
Hello,

I'm following this tutorial for running the build_android.sh and error occurred in the CMake phase:

CMake Error at /usr/share/OpenCV/OpenCVConfig.cmake:45 (include):
  include could not find load file:

    /usr/share/OpenCV/OpenCVModules_armeabi_v7a.cmake

Does someone know how to solve it? Thank you.

**Comment by amadeuzou** [comment]
-DUSE_OPENCV=OFF

**Comment by dyt001** [comment]
This solved the error, thank you!
