### ISSUE TITLE
Caffe2 installation error while building

### ISSUE THREAD

**Issue by sriharsha0806** [facebookarchive/caffe2#508]
I am getting the following error while running cmake.. as mentioned in the following website ["http://www.nvidia.com/object/caffe2-installation.html"] or caffe2 installation page. My os is ubuntu 16.04

cmake ..
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing:  NNPACK_INCLUDE_DIR NNPACK_LIBRARY) 
-- Will try to build NNPACK from source. If anything fails, follow the NNPACK prerequisite installation steps.
CMake Warning at cmake/External/nnpack.cmake:157 (message):
  NNPACK is chosen to be installed, but confu and ninja that are needed by it
  are not installed.  As a result we won't build with NNPACK.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:52 (include)
  CMakeLists.txt:85 (include)

CMake Warning at cmake/Dependencies.cmake:57 (message):
  Not compiling with NNPACK.  Suppress this warning with -DUSE_NNPACK=OFF
Call Stack (most recent call first):
  CMakeLists.txt:85 (include)

-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found system gflags install.
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found system glog install.
-- Found PythonInterp: /home/sriharsha/miniconda3/bin/python (found version "3.6") 
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- Could NOT find RocksDB (missing:  RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
CMake Warning at cmake/Dependencies.cmake:131 (message):
  Not compiling with RocksDB.  Suppress this warning with -DUSE_ROCKSDB=OFF
Call Stack (most recent call first):
  CMakeLists.txt:85 (include)

-- OpenCV found (/usr/share/OpenCV)
-- Found PythonInterp: /home/sriharsha/miniconda3/bin/python (found suitable version "3.6", minimum required is "2.7") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindNumPy.cmake:50 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:188 (find_package)
  CMakeLists.txt:85 (include)

-- Configuring incomplete, errors occurred!
See also "/home/sriharsha/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/sriharsha/caffe2/build/CMakeFiles/CMakeError.log".

I checked the previous post but they are not helpful. Please let me know how to resolve the issue.

or else can anyone provide docker instructions on how to install the following file "caffe2ai/caffe2:c2.tutorial.0.7.1"

**Comment by hgaiser** [comment]
It seems you are missing numpy. Perhaps you did install it (in python2) but by the looks if it, caffe2 is trying to build with python3 in your case, which doesn't yet work. I'm working on getting some python3 fixes for caffe2 but until then it's best to make sure caffe2 compiles with python2.

**Comment by Yangqing** [comment]
@sriharsha0806 if you'd like to try with the most recent caffe2 vertion that would be great - it should be py3 compatible.

**Comment by sara-eb** [comment]
I could solve it by `python -m pip install numpy`
