### ISSUE TITLE
Questions about DAGNet?

### ISSUE THREAD

**Issue by machoji** [facebookarchive/caffe2#511]
when run googlenet,  two SimpleNet are created. My question is  caffe2 source code contains SimpleNet and DAGNet and many differences between them.  Could you give me more information about them and which net(googlenet is not) uses DAGNet, thank you!!!

**Comment by pietern** [comment]
They are different ways to execute a net. SimpleNet uses a single thread and runs operators sequentially. The DAGNet uses multiple threads to run operators in parallel, where possible. You can set the "num_workers" property on the DAGNet to set the number of threads to use.

You can modify any net to use either SimpleNet or DAGNet. It doesn't depend on the model you use.

**Comment by machoji** [comment]
thank you very much for your answer.
