### ISSUE TITLE
Facing issue in building caffe2 with BLAS=MKL

### ISSUE THREAD

**Issue by aksgnit** [facebookarchive/caffe2#514]
I am facing issue while building caffe2 with BLAS=MKL

i am using .....
cmake . -DCMAKE_INSTALL_PREFIX=/home/ashish/dp/caffe2/caffe2_install_mklblas -DBLAS=MKL -DMKL_INCLUDE_DIR=/cm/shared/intel_2017/compilers_and_libraries_2017.1.132/linux/mkl/include -DMKL_ROOT=/cm/shared/intel_2017/compilers_and_libraries_2017.1.132/linux/mkl

[ 34%] [ 35%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/image/image_input_op.cc.o
Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/mkl_operator.cc.o
[ 35%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/mklmemory_serialization.cc.o
[ 35%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/operators/conv_op.cc.o
[ 36%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/operators/conv_op_mkldnn.cc.o
[ 36%] [ 36%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/operators/fully_connected_op.cc.o
Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/operators/local_response_normalization_op.cc.o
[ 37%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/mkl/operators/operator_fallback_mkl.cc.o
In file included from /home/ashish/dp/caffe2/caffe2/utils/mkl_utils.h:63:0,
                 from /home/ashish/dp/caffe2/caffe2/mkl/mklmemory_serialization.cc:3:
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h: In function ‘dnnError_t caffe2::mkl::dnnBatchNormalizationCreateForward_v2(_uniPrimitive_s**, dnnPrimitiveAttributes_t, dnnLayout_t, float, unsigned int) [with T = float; dnnPrimitive_t = _uniPrimitive_s*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = _dnnLayout_s*]’:
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h:1102:62: error: ‘dnnBatchNormalizationCreateForward_v2_F32’ was not declared in this scope
       pBatchNormalization, attributes, dataLayout, eps, flags);
                                                              ^
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h: In function ‘dnnError_t caffe2::mkl::dnnBatchNormalizationCreateForward_v2(_uniPrimitive_s**, dnnPrimitiveAttributes_t, dnnLayout_t, float, unsigned int) [with T = double; dnnPrimitive_t = _uniPrimitive_s*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = _dnnLayout_s*]’:
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h:1111:62: error: ‘dnnBatchNormalizationCreateForward_v2_F64’ was not declared in this scope
       pBatchNormalization, attributes, dataLayout, eps, flags);
                                                              ^
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h: In function ‘dnnError_t caffe2::mkl::dnnBatchNormalizationCreateBackward_v2(_uniPrimitive_s**, dnnPrimitiveAttributes_t, dnnLayout_t, float, unsigned int) [with T = float; dnnPrimitive_t = _uniPrimitive_s*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = _dnnLayout_s*]’:
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h:1127:62: error: ‘dnnBatchNormalizationCreateBackward_v2_F32’ was not declared in this scope
       pBatchNormalization, attributes, dataLayout, eps, flags);
                                                              ^
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h: In function ‘dnnError_t caffe2::mkl::dnnBatchNormalizationCreateBackward_v2(_uniPrimitive_s**, dnnPrimitiveAttributes_t, dnnLayout_t, float, unsigned int) [with T = double; dnnPrimitive_t = _uniPrimitive_s*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = _dnnLayout_s*]’:
/home/ashish/dp/caffe2/caffe2/utils/mkl/mkl_dnn_cppwrapper.h:1137:62: error: ‘dnnBatchNormalizationCreateBackward_v2_F64’ was not declared in this scope
       pBatchNormalization, attributes, dataLayout, eps, flags);

**Comment by matzeox** [comment]
I get exact the same error. The problem is that the function dnnBatchNormalizationCreateBackward_v2_F32 is not included anymore into the current version of MKL 2017. 

Some other guys (which are not related to caffe2) have similiar problems:
https://github.com/dmlc/mxnet/issues/4505

So I don't know if this function can be replaced with dnnBatchNormalizationCreateBackward_F32 in caffe2. This function seem to be integrated in the current version of MKL.

**Comment by jaymahesh** [comment]
Hi all, I am facing the same problem as stated below. I am using CentOS. Kindly help me with a solution, thanks !!

error: ‘dnnBatchNormalizationCreateBackward_v2_F32’ was not declared in this scope

**Comment by awan-10** [comment]
@jaymahesh - I also encountered this error but it will go away if you use the Intel MKL 2017 Update 3. 

The _v2_ variants are available in the header file for MKL Update 3.

**Comment by pietern** [comment]
FWIW, we run continuous builds/tests with MKL 2018.1.

If there is a reason to support older versions please let us know :)
