### ISSUE TITLE
[Raspbian] ImportError: No module named caffe2.proto 

### ISSUE THREAD

**Issue by choonkiattay** [facebookarchive/caffe2#522]
I successfully build caffe2 on rpi3 by following the installation guide from caffe2.ai
when i try to follow tutorials, it complains

`pi@raspberrypi:~/caffe2/build/caffe2/python $ python workspace_test.py 
Traceback (most recent call last):
  File "workspace_test.py", line 5, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: No module named caffe2.proto
`
Any additional step after ./scripts/build_raspbian.sh ?

**Comment by astroli** [comment]
I do not install caffe2, but use PYTHONPATH to locate it.
Run test at caffe2 root directory.
~/caffe2 $ export PYTHONPATH=build
~/caffe2 $ python build/caffe2/python/workspace_test.py

**Comment by choonkiattay** [comment]
@astroli 
export PYHONPATH on build is working but raspbian seems do not remember PYTHONPATH

I edited .bashrc to make it remember PYTHONPATH.
`git clone --recursive https://github.com/caffe2/caffe2.git

cd caffe2
./scripts/build_raspbian.sh

#at home directory
leafpad .bashrc

#Scroll until the end then insert PYTHONPATH here
export PYTHONPATH=${PYTHONPATH}:/home/pi/caffe2/build/

source .bashrc

#Check PYTHONPATH
$echo PYTHONPATH

#Confirm the build by 
~/caffe2 $ python build/caffe2/python/workspace_test.py`
