### ISSUE TITLE
Docker File Improvement

### ISSUE THREAD

**Issue by gavinhub** [facebookarchive/caffe2#53]
**Rocksdb installation**
Since the current script installs the HEAD version of rocksdb, it may brings in error while building. Please use a stable release version instead.

[code related](https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/docker-ubuntu-14.04/Dockerfile#L52):
`git clone https://github.com/facebook/rocksdb.git`

**Comment by Yangqing** [comment]
Thanks! Yeah, so right now we are going to update the docker script a little bit and will be recommending 16.04 - in which case you should be able to do apt-get install rocksdb.
