### ISSUE TITLE
How do we access the weight by Python API?

### ISSUE THREAD

**Issue by jimmyoic** [facebookarchive/caffe2#535]
Somehow we may need to check the distribution or modify the weight for some reason like debugging or research 
How do we get the weight value?

**Comment by ezineo** [comment]
```python
weight = Workspace.FetchBlob('weight_name')
```

**Comment by jimmyoic** [comment]
But is it possible to modify it like zero it or doing some clipping?
Thanks!

**Comment by ezineo** [comment]
```python

Just do something on weight...

Workspace.FeedBlob(weight, 'weight_name')
```
