### ISSUE TITLE
make error !!  caffe2/core/context.h(45):  exception specification

### ISSUE THREAD

**Issue by nyyznyyz1991** [facebookarchive/caffe2#536]
[ 54%] Built target Caffe2_CPU
make[3]: Entering directory `/home/fengbailan/tools/caffe2-master/build'
[ 54%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/image/Caffe2_GPU_generated_transform_gpu.cu.o
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/core/Caffe2_GPU_generated_context_gpu.cu.o
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_accumulate_op.cu.o
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_accuracy_op.cu.o
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_batch_matmul_op.cu.o
[ 56%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_cast_op.cu.o
[ 56%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_clip_op.cu.o
/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): **# error:** exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator_schema.h(247): error: class "std::map<std::string, caffe2::OpSchema, std::less<std::string>, std::allocator<std::pair<const std::string, caffe2::OpSchema>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator_schema.h(247): error: class "std::map<std::string, caffe2::OpSchema, std::less<std::string>, std::allocator<std::pair<const std::string, caffe2::OpSchema>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator_schema.h(247): error: class "std::map<std::string, caffe2::OpSchema, std::less<std::string>, std::allocator<std::pair<const std::string, caffe2::OpSchema>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator_schema.h(247): error: class "std::map<std::string, caffe2::OpSchema, std::less<std::string>, std::allocator<std::pair<const std::string, caffe2::OpSchema>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator_schema.h(247): error: class "std::map<std::string, caffe2::OpSchema, std::less<std::string>, std::allocator<std::pair<const std::string, caffe2::OpSchema>>>" has no member "emplace"

2 errors detected in the compilation of "/tmp/tmpxft_00007e09_00000000-19_transform_gpu.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_transform_gpu.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/image/./Caffe2_GPU_generated_transform_gpu.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/image/Caffe2_GPU_generated_transform_gpu.cu.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/fengbailan/tools/caffe2-master/caffe2/core/net.h(128): error: exception specification for virtual function "caffe2::DAGNetBase::~DAGNetBase" is incompatible with that of overridden function "caffe2::NetBase::~NetBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/net.h(128): error: exception specification for virtual function "caffe2::DAGNetBase::~DAGNetBase" is incompatible with that of overridden function "caffe2::NetBase::~NetBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/net.h(128): error: exception specification for virtual function "caffe2::DAGNetBase::~DAGNetBase" is incompatible with that of overridden function "caffe2::NetBase::~NetBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/net.h(128): error: exception specification for virtual function "caffe2::DAGNetBase::~DAGNetBase" is incompatible with that of overridden function "caffe2::NetBase::~NetBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator.h(401): error: class "std::map<int32_t, caffe2::OperatorRegistry *, std::less<int>, std::allocator<std::pair<const int32_t, caffe2::OperatorRegistry *>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/net.h(128): error: exception specification for virtual function "caffe2::DAGNetBase::~DAGNetBase" is incompatible with that of overridden function "caffe2::NetBase::~NetBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator.h(401): error: class "std::map<int32_t, caffe2::OperatorRegistry *, std::less<int>, std::allocator<std::pair<const int32_t, caffe2::OperatorRegistry *>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator.h(401): error: class "std::map<int32_t, caffe2::OperatorRegistry *, std::less<int>, std::allocator<std::pair<const int32_t, caffe2::OperatorRegistry *>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator.h(401): error: class "std::map<int32_t, caffe2::OperatorRegistry *, std::less<int>, std::allocator<std::pair<const int32_t, caffe2::OperatorRegistry *>>>" has no member "emplace"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/operators/batch_matmul_op.h(18): error: exception specification for virtual function "caffe2::BatchMatMulOp<T, Context, Engine>::~BatchMatMulOp [with T=float, Context=caffe2::CUDAContext, Engine=caffe2::DefaultEngine]" is incompatible with that of overridden function "caffe2::Operator<Context>::~Operator [with Context=caffe2::CUDAContext]"

/home/fengbailan/tools/caffe2-master/caffe2/operators/batch_matmul_op.h(18): error: exception specification for virtual function "caffe2::BatchMatMulOp<T, Context, Engine>::~BatchMatMulOp [with T=float, Context=caffe2::CUDAContext, Engine=caffe2::DefaultEngine]" is incompatible with that of overridden function "caffe2::OperatorBase::~OperatorBase"

/home/fengbailan/tools/caffe2-master/caffe2/core/operator.h(401): error: class "std::map<int32_t, caffe2::OperatorRegistry *, std::less<int>, std::allocator<std::pair<const int32_t, caffe2::OperatorRegistry *>>>" has no member "emplace"

2 errors detected in the compilation of "/tmp/tmpxft_00007e17_00000000-19_context_gpu.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_context_gpu.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/core/./Caffe2_GPU_generated_context_gpu.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/core/Caffe2_GPU_generated_context_gpu.cu.o] Error 1
/home/fengbailan/tools/caffe2-master/caffe2/core/context.h(45): error: exception specification for virtual function "caffe2::DefaultCPUAllocator::~DefaultCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

/home/fengbailan/tools/caffe2-master/caffe2/core/context_gpu.h(243): error: exception specification for virtual function "caffe2::PinnedCPUAllocator::~PinnedCPUAllocator" is incompatible with that of overridden function "caffe2::CPUAllocator::~CPUAllocator"

5 errors detected in the compilation of "/tmp/tmpxft_00007e28_00000000-19_clip_op.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_clip_op.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_clip_op.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_clip_op.cu.o] Error 1
5 errors detected in the compilation of "/tmp/tmpxft_00007e20_00000000-19_accuracy_op.compute_61.cpp1.ii".
7 errors detected in the compilation of "/tmp/tmpxft_00007e2a_00000000-19_batch_matmul_op.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_accuracy_op.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_accuracy_op.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_accuracy_op.cu.o] Error 1
5 errors detected in the compilation of "/tmp/tmpxft_00007e2f_00000000-19_accumulate_op.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_batch_matmul_op.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_batch_matmul_op.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_batch_matmul_op.cu.o] Error 1
CMake Error at Caffe2_GPU_generated_accumulate_op.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_accumulate_op.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_accumulate_op.cu.o] Error 1
5 errors detected in the compilation of "/tmp/tmpxft_00007e33_00000000-19_cast_op.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_cast_op.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_cast_op.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_cast_op.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_00007e59_00000000-19_math_gpu.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_math_gpu.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/fengbailan/tools/caffe2-master/build/caffe2/CMakeFiles/Caffe2_GPU.dir/utils/./Caffe2_GPU_generated_math_gpu.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/utils/Caffe2_GPU_generated_math_gpu.cu.o] Error 1
make[3]: Leaving directory `/home/fengbailan/tools/caffe2-master/build'
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make[2]: Leaving directory `/home/fengbailan/tools/caffe2-master/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/fengbailan/tools/caffe2-master/build'
make: *** [all] Error 2

**Comment by Knight-X** [comment]
Could you post your compiler and its version, operating system ?
As I know, std::map::emplace() and noexcept are features that were added  in the 2011 C++ Standard and g++ 4.7.3 does not support std::map::emplace().

**Comment by nyyznyyz1991** [comment]
After I update the gcc version, I succeed, thanks!
