### ISSUE TITLE
Difference in speed performance of C++ and python

### ISSUE THREAD

**Issue by Devin0202** [facebookarchive/caffe2#540]
Hi all, I used the same net and image for detecting in both C++ codes and python, but the cost time has large gap between the two(nearly 20X).
In python, inference codes as "results = p.run([img_2])"  time cost ~ 1ms 
In C++, inference codes as "predictor->run(inputVec, &outputVec)"  time cost ~ 20ms 

So, need I take some additional modification or settings in C++ side for reaching the same speed?
Thanks.

**Comment by futurely** [comment]
GPU vs CPU?

`using TensorVector = std::vector<TensorCPU*>;`
https://github.com/caffe2/caffe2/blob/9901bdb7a42cf8dd843159f34bf3835c89a99d0c/caffe2/core/predictor.h

**Comment by huangynn** [comment]
Mac only support cpu, so the condition should be the same , what's cause the difference between python & c++ ?

**Comment by MrZhangCF** [comment]
@DevinHiscene  Can i see your C++ codes ? i want to have a try too..

**Comment by Devin0202** [comment]
The reason for the time cost gap is that optimal Flag.
In my caffe2 source, the default one is DEBUG.
After I set "-O3", the gap was disappeared.
