### ISSUE TITLE
Import both caffe and caffe2 in python

### ISSUE THREAD

**Issue by honamida** [facebookarchive/caffe2#555]
Hi,
for some reasons I need to use both the interface of caffe and caffe2
But once I import the library (the order is not matter) it turns out something's wrong with the protobuff

import caffe
from caffe2.python import core, cnn, net_drawer, workspace, visualize

![image](https://cloud.githubusercontent.com/assets/28566795/25939021/fa9f44a8-3663-11e7-9f7e-767c6c2461d3.png)

Any ideas about the problem?
Thanks!

**Comment by pietern** [comment]
It is not supported to load both caffe and caffe2 in the same process. You might be able to hack around problems you encounter, but this is not a mode we can guarantee will work or keeps working.
