### ISSUE TITLE
No module named caffe2_pybind11_state_gpu on macOS 10.12.4

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#557]
I have compiled caffe2 without CUDA support on macOS 10.12.4
but when I run `python -c 'from caffe2.python import core'`, it appears such error: 

$python -c 'from caffe2.python import core'
Python 2.7.11 (default, Feb  1 2016, 14:03:04) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Fatal Python error: PyThreadState_Get: no current thread
[1]    12234 abort      python -c 'from caffe2.python import core'

And my path is set as follow:

export PATH=$HOME/bin:/usr/local/bin:$HOME/anaconda/bin:$PATH
export PYTHONPATH=~/usr/local:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:$HOME/caffe2/build
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

How do I correct it?

**Comment by chenrz925** [comment]
Me too.

**Comment by hgaiser** [comment]
Is it possible you are running with python3?

**Comment by ghost** [comment]
@hgaiser  No,I am running with python 2.7.11

Python 2.7.11 (default, Feb  1 2016, 14:03:04) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by raphael-attie** [comment]
same issue here, although since I was in mac os (Sierra 10.12.5), I had setup the DYLD_LIBRARY_PATH instead of the LD_LIBRARY_PATH. 

Any update on this?

**Comment by raphael-attie** [comment]
Fixed. In my case this was due to not activating my virtual environment before doing the build. I guess this caused some inconsistencies with different versions of pythons. I did not even need to set the (DY)LD_LIBRARY_PATH anywhere.

**Comment by ShangxuanWu** [comment]
@WaaallEEE I am running in local python, not anaconda or other virtual environments. Yet this error continues. Is there any method to fix this? Thanks!

**Comment by ccs1605** [comment]
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
`
just got warning without gpu support.
how to solve this? thanks!

**Comment by bddppq** [comment]
The original error in this thread `Fatal Python error: PyThreadState_Get: no current thread` is a typical error when the version of libpython linked at build time is different with the one at runtime. **This error should not happen anymore in the newest version of caffe2** since we have changed to not link with libpython at build time, please update to the newest version.
@ccs1605 Your case is different, and in fact the warnings you are seeing is expected as your Mac doesn't have cuda compatible gpu.

**Comment by ccs1605** [comment]
@bddppq, thanks for workaround. I am not running on Mac. It is a PC. Please advise!
