### ISSUE TITLE
MNIST Tutorial

### ISSUE THREAD

**Issue by startakovsky** [facebookarchive/caffe2#558]
In the first cell of [this](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb) `ipynb`, `caffe2_root` is set, but never used throughout the entire notebook. What is the purpose of this variable and how is it utilized in the caffe2 code.

**Comment by aaronmarkham** [comment]
That can be removed! Was used in an earlier version...
