### ISSUE TITLE
How to use ConvTranspose in python? 

### ISSUE THREAD

**Issue by raininglixinyu** [facebookarchive/caffe2#561]
I am try to build a end-to-end network. So the transpose convolution will be used. Now, i am confused about the `convTranspose` API,  how can i use it? And how can i do the upsampling?

**Comment by iteal** [comment]
Sorry did you figure it out? I want to do upsampling too and convTranspose alone is not enough.

**Comment by raininglixinyu** [comment]
@laetitiahebert ConvTranspose has include the upsampling work.

**Comment by iteal** [comment]
Do you have a code sample @raininglixinyu  ? How to set the scale or the filter?

I have this:
upconv = brew.conv_transpose(model, "data", "upconv", dim_in=1, dim_out=64, kernel=2)

**Comment by iteal** [comment]
I found it sorry! I was missing the parameters "stride=2"
upconv = brew.conv_transpose(model, "data", "upconv", dim_in=1, dim_out=64, kernel=2, stride=2)

thanks!

**Comment by ghost** [comment]
Are you only using the one input data blob? Do you know how bias and filter blobs are added?

**Comment by xingyuanbu** [comment]
Maybe [UpsampleNearestOp ](https://caffe2.ai/doxygen-c/html/upsample__nearest__op_8cc_source.html) is what you need~
