### ISSUE TITLE
Build Issue in ubuntu 16.04

### ISSUE THREAD

**Issue by dakshthapar** [facebookarchive/caffe2#562]
i have cuda-8.0 installed on my machine but it says found unsuitable cuda-8.0 but required 7.5.
but the documentation says it should work with cuda-8.0

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "8.0", but required is exact
  version "7.5" (found /usr/local/cuda-8.0)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:949 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:105 (find_host_package)
  cmake/Dependencies.cmake:164 (find_package)
  CMakeLists.txt:82 (include)

-- Configuring incomplete, errors occurred!
See also "/home/biometric/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/biometric/caffe2/build/CMakeFiles/CMakeError.log".
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by futurely** [comment]
sudo rm -rf /usr/local/share/OpenCV

**Comment by pietern** [comment]
Looks like this was caused by a custom OpenCV version.

**Comment by PkuRainBow** [comment]
@futurely Thanks for your answer!

**Comment by sonuanjali2005** [comment]
I am facing the same issue help out
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
  version "9.0" (found /usr)
