### ISSUE TITLE
Issue with Build on Ubuntu 16.04 

### ISSUE THREAD

**Issue by mkamrao** [facebookarchive/caffe2#563]
Hi 

I followed the instructions as mentioned in:
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

I got error after Clone & Build:
make && cd build && sudo make install

------------------------------------------------------------------------------------------------------------
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "8.0", but required is exact
  version "7.5" (found /usr/local/cuda-8.0)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:949 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:105 (find_host_package)
  cmake/Dependencies.cmake:164 (find_package)
  CMakeLists.txt:82 (include)

-- Configuring incomplete, errors occurred!
See also "/home/uurmi/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/uurmi/caffe2/build/CMakeFiles/CMakeError.log".
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
---------------------------------------------------------------------------------------------------

I am using Ubuntu 16.04. 
Initially, I tried with Cuda 8.0 and then with Cuda 7.5.
The error is same with both versions. 

Can you suggest what could be the issue?

Thanks
Kamrao

**Comment by Knight-X** [comment]
I think the error is because of the version of cuda is wrong. Could you remove the cuda library and reinstall Cuda-8.0 ?

**Comment by futurely** [comment]
sudo rm -rf /usr/local/share/OpenCV

**Comment by aaronmarkham** [comment]
Please try this again. If you follow [NVIDIA's CUDA installation guide](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#axzz4im3KJJth) and also make sure you've fully removed the old version of CUDA, you should be fine. Please reopen if you have this issue again.
