### ISSUE TITLE
Import pytorch models

### ISSUE THREAD

**Issue by kineticz** [facebookarchive/caffe2#564]
Would be nice to be able to import output from `torch.save(model.state_dict(), "/path/to/model_file")`.

**Comment by futurely** [comment]
Convert PyTorch to Torch by reverting the example script below.
https://github.com/clcarwin/convert_torch_to_pytorch/blob/master/convert_torch.py

https://caffe2.ai/docs/caffe-migration.html#null__converting-from-torch

**Comment by pietern** [comment]
This can now be done through [ONNX](https://onnx.ai/).

Clearly this issue was ahead of its time! :smile: 

cc @jamesr66a @bddppq @dzhulgakov
