### ISSUE TITLE
No module named caffe2.python

### ISSUE THREAD

**Issue by MrZhangCF** [facebookarchive/caffe2#569]
when i run the mnist tutorial in the ipython notebook ,it shows that No module named caffe2.python,what should i do ?
![caffe2](https://cloud.githubusercontent.com/assets/26785691/26026519/5891c0b4-382f-11e7-8a80-a735e63eb2bc.png)

**Comment by suxiaoxinxin** [comment]
Maybe you could set pythonpath where caffe2 is installed, or use sys.append.

**Comment by MrZhangCF** [comment]
@suxiaoxinxin thanks~,you are right, i add the pythonpath in the .bashrc, it works now!
