### ISSUE TITLE
running build_android.sh gets a very large library file

### ISSUE THREAD

**Issue by linhj07** [facebookarchive/caffe2#571]
build_android.sh file runs successfully, but the generated libCaffe2_CPU.a under build_android/caffe2 directory is about 248MB. Why it is so large? I am compiling under Mac OS X 10.12.

**Comment by lzx1413** [comment]
@linhj07 Maybe a whitelist used in cmake may help a lot, #285 mentioned something about it

**Comment by apktstgithub** [comment]
Hi HJ, I had problem to build for the android #498, do you know how to solve this issue? Thank you.

**Comment by lsn2000** [comment]
I guess it is the proper size. I get the same size.

**Comment by tlhchutang** [comment]
try to add -O3 in build flags

**Comment by linhj07** [comment]
@tlhchutang thx:) Problem solved. With -O3 flag, the generated library is only 35MB.

**Comment by chengaohua** [comment]
@linhj07 how to add -O3 flag? could you show the code that you modified.

**Comment by lsn2000** [comment]
open CMakeLists.txt under caffe2 root folder, insert flags
 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11 -O3")

before these flags:

if(NOT MSVC)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing")

**Comment by lzx1413** [comment]
if(NOT MSVC)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing")
I think this is the right answer.
@lsn2000
