### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by xiaohuizheng** [facebookarchive/caffe2#574]
-- Could NOT find Protobuf (missing:  Protobuf_INCLUDE_DIR) 
-- Using protobuf compiler /usr/local/protobuf/bin/protoc.
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing:  NNPACK_INCLUDE_DIR NNPACK_LIBRARY) 
-- Will try to build NNPACK from source. If anything fails, follow the NNPACK prerequisite installation steps.
CMake Warning at cmake/External/nnpack.cmake:157 (message):
  NNPACK is chosen to be installed, but confu and ninja that are needed by it
  are not installed.  As a result we won't build with NNPACK.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:52 (include)
  CMakeLists.txt:82 (include)
-- Could NOT find Glog (missing:  GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CMake Warning at cmake/External/glog.cmake:13 (message):
  glog is not found.  Caffe2 will build without glog support but it is
  strongly recommended that you install glog.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:64 (include)
  CMakeLists.txt:82 (include)

-- Could NOT find LevelDB (missing:  LevelDB_INCLUDE LevelDB_LIBRARY) 
-- Could NOT find Snappy (missing:  Snappy_INCLUDE_DIR Snappy_LIBRARIES) 
CMake Warning at cmake/Dependencies.cmake:119 (message):
  Not compiling with LevelDB.  Suppress this warning with -DUSE_LEVELDB=OFF
Call Stack (most recent call first):
  CMakeLists.txt:82 (include)
,i'm sure i have these libraries ,but they can't be found ,i don't know why?

**Comment by lsn2000** [comment]
you probably need to set the environment variables in the CMake files to allow cmake find the paths

**Comment by xiaohuizheng** [comment]
@lsn2000 I should set the environment variables in which CMake files ? I dont understand what you said

**Comment by lsn2000** [comment]
actually a better idea is to  turn those stuff off, i.e. do not build unused libraries.
in caffe2/scripts/build_android.sh 

cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake \
    -DCMAKE_INSTALL_PREFIX=../install \
    -DANDROID_NDK=$NDK_ROOT \
    -DCMAKE_BUILD_TYPE=Release \
    -DANDROID_ABI="arm64-v8a" \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -DUSE_CUDA=OFF \
    -DBUILD_TEST=OFF \
    -DUSE_LMDB=OFF \
    -DUSE_LEVELDB=OFF \
    -DUSE_OPENCV=OFF \
    -DUSE_NNPACK=OFF \
    -DBUILD_PYTHON=OFF \
    -DPROTOBUF_PROTOC_EXECUTABLE=$CAFFE2_ROOT/build_host_protoc/bin/protoc \
    -DCMAKE_VERBOSE_MAKEFILE=1 \
    -DUSE_MPI=OFF \
    -DUSE_OPENMP=OFF \
    -DBUILD_SHARED_LIBS=ON \
    || exit 1
make

make sure NDK_ROOT is correct

**Comment by lsn2000** [comment]
also make sure you check out the project using git clone --recursive, otherwise the third party modules under caffe2/third_party folder will be missing, and that may create a lot of trouble.

**Comment by WinfredHuang** [comment]
I'm strongly against this solution, since LMDB and LEVELDB are so frequently used in tutorials. Although they're not necessary by Caffe2's official requirements, they're highly recommended to be installed on the computer to begin with.

**Comment by pietern** [comment]
Not an issue, closing.
