### ISSUE TITLE
convert model from caffe1 to caffe2 error!

### ISSUE THREAD

**Issue by MrZhangCF** [facebookarchive/caffe2#575]
i use the 
`python -m caffe2.python.caffe_translator deploy.prototxt pretrained.caffemodel` of the tutorial to convert the model to caffe2,but it shows the error as follows:
![lsls](https://cloud.githubusercontent.com/assets/26785691/26046078/cf9bbcd6-397f-11e7-8d7b-827d13af5ed9.png)
any idea? thanks!

**Comment by lzx1413** [comment]
@MrZhangCF type AbsVal is not supported by this scrip now

**Comment by MrZhangCF** [comment]
@lzx1413  you are right,i change it to ReLU, thanks!

**Comment by xonobo** [comment]
Is there a work around to get abs value of the input by using the ReLU layer with specific parameters?

Or is there any progress to support AbsVal layers in caffe2 conversion?

**Comment by xonobo** [comment]
Here I found the relu config to get an absVal.

layer {
  name: "abs1"
  type: "ReLU"
  bottom: "conv1"
  top: "abs1"
  relu_param {
    negative_slope: -1
  }
}
