### ISSUE TITLE
Unify the operator API with numpy/tensorflow

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#577]
https://github.com/caffe2/caffe2/blob/134d992daf908b23c2ce2244071406e588499cd6/caffe2/python/operator_test/reshape_ops_test.py#L62
```python
old_shape = (4, 2, 1)
new_shape = (1, 8)
X = np.random.rand(*old_shape).astype(np.float32)
```
It takes 3 lines in Caffe2 to reshape a tensor.
```python
net = core.Net('net')
net.GivenTensorFill([], 'X', shape=old_shape, values=X.flatten())
# if the users really need old_shape, they should call X.shape() or caffe2.shape(X) directly.
X_reshaped, out_old_shape = net.Reshape(['X'], ['X_out', 'old_shape'], shape=new_shape)
```
The numpy and tensorflow API is much simpler.
```
X_reshaped = np.reshape(X, new_shape)
X_reshaped = tf.reshape(X, new_shape)
```

**Comment by mfawzymkh** [comment]
@futurely,  is the ask here to provide a reshape API like TF to simplify the boiler plate code ?
this is equivalent of creating a helper python function that wraps that 3 lines in Caffe2, correct?

**Comment by futurely** [comment]
Yes, it is. The recently introduced brew module is where such helper functions can be implemented.

**Comment by mfawzymkh** [comment]
@futurely , the reshape is done through a single call today .
net.Reshape(['X'], ['X_out', 'old_shape'], shape=new_shape)

so adding a brew wrapper add little value here, it would look like 
brew.reshape("X", "X_out",  new_shape) 

do you think there is a value in that?

**Comment by futurely** [comment]
Not much.
