### ISSUE TITLE
Compiling Caffe2 on a Mac OS X 10.10.5: Caffe symbols not found for architecture x84_64 (types.cc)

### ISSUE THREAD

**Issue by andreazanetti** [facebookarchive/caffe2#58]
Hello, I am trying to compile Caffe 2 on mac mini 64 bits (2.6 GHz Intel Core i5) running OS-X 10.10.5. So CPU only with no GPU. I think I have installed all the dependencies excluding CUDA. I have changed in build.py the optimization flag to -O2 as -O2+ was causing me problems. Along the compilation process, the first error of the kind described in the title (symbols not found) is the one reported below. What am i doing wrong? Thanks very much

LOG: Building //caffe2:core_test
WARNING: Build failed: //caffe2:core_test. Fail messages are as follows:

clang: warning: argument unused during compilation: '-pie'
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "long caffe2::TypeMeta::Id<std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > >()", referenced from:
      std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >* caffe2::Blob::GetMutable<std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > >(bool*) in libcore_test.a(parallel_net_test.o)
  "long caffe2::TypeMeta::Id<long>()", referenced from:
      bool caffe2::DispatchHelper<caffe2::TensorTypes<double, int, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::call<caffe2::FindDuplicateElementsOp<caffe2::CPUContext> >(caffe2::FindDuplicateElementsOp<caffe2::CPUContext>*, caffe2::TypeMeta const&) in libcore_ops.a(find_duplicate_elements_op.o)
      long const* caffe2::Tensor<caffe2::CPUContext>::data<long>() const in libcore_ops.a(find_duplicate_elements_op.o)
      bool caffe2::DispatchHelper<caffe2::TensorTypes<float, double, int, long> >::call<caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput> >(caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput>*, caffe2::TypeMeta const&) in libcore_ops.a(negative_op.o)
      bool caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput>::DoRunWithType<long>() in libcore_ops.a(negative_op.o)
      long const* caffe2::Tensor<caffe2::CPUContext>::data<long>() const in libcore_ops.a(negative_op.o)
      caffe2::(anonymous namespace)::PackSegmentsOp<caffe2::CPUContext>::RunOnDevice() in libcore_ops.a(pack_segments.o)
      caffe2::(anonymous namespace)::UnpackSegmentsOp<caffe2::CPUContext>::RunOnDevice() in libcore_ops.a(pack_segments.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and then also:

LOG: Building //caffe2:caffe2_core
WARNING: Build failed: //caffe2:caffe2_core. Fail messages are as follows:

clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "long caffe2::TypeMeta::Id<long>()", referenced from:
      bool caffe2::DispatchHelper<caffe2::TensorTypes<double, int, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::call<caffe2::FindDuplicateElementsOp<caffe2::CPUContext> >(caffe2::FindDuplicateElementsOp<caffe2::CPUContext>*, caffe2::TypeMeta const&) in libcore_ops.a(find_duplicate_elements_op.o)
      long const* caffe2::Tensor<caffe2::CPUContext>::data<long>() const in libcore_ops.a(find_duplicate_elements_op.o)
      bool caffe2::DispatchHelper<caffe2::TensorTypes<float, double, int, long> >::call<caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput> >(caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput>*, caffe2::TypeMeta const&) in libcore_ops.a(negative_op.o)
      bool caffe2::UnaryElementwiseWithArgsOp<caffe2::TensorTypes<float, double, int, long>, caffe2::CPUContext, caffe2::WithDefaultConstructor<caffe2::NegativeCPUFunctor>, caffe2::SameTypeAsInput>::DoRunWithType<long>() in libcore_ops.a(negative_op.o)
      long const* caffe2::Tensor<caffe2::CPUContext>::data<long>() const in libcore_ops.a(negative_op.o)
      caffe2::(anonymous namespace)::PackSegmentsOp<caffe2::CPUContext>::RunOnDevice() in libcore_ops.a(pack_segments.o)
      caffe2::(anonymous namespace)::UnpackSegmentsOp<caffe2::CPUContext>::RunOnDevice() in libcore_ops.a(pack_segments.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andreazanetti** [comment]
Hello, I have tried to install Caffe2 also on a different Mac, Mac OS X 10.11, on Mac Book Air with the same processor. I have run into very similar problem, with Caffe2 symbols not found as above. I cannot figure out what is the problem, as if I grep for the symbols that were not found the entire Caffe2 tree, I only find the reference from the "calling" point (so into the libraries that are referencing to it), but not the definition of it. I might be wrong, but I would expect to find a place where these symbols are defined, and that should be the missing library that does not get linked. Any help appreciated. thanks!!

**Comment by andreazanetti** [comment]
It seems that in types.cc file some Caffe2 supported types along with some mappings are defined. Just adding the support for the "long" type in this file reduces the number of compilation errors. I wonder why I see this on mac os x and my colleagues using Linux have no troubles of this kind. Any hint will be of help, thanks!

**Comment by bwasti** [comment]
This is fixed in the `cmake` branch: https://github.com/caffe2/caffe2/commit/5c981ddedfa48b59fee6a0ee369f11a8fc3c53f6

I'll close this when that migrates over to master

**Comment by Yangqing** [comment]
Another fix that would make it addressed by all other platforms that might have this issue too: https://github.com/caffe2/caffe2/commit/51f1e3fb4312287b8e936c6147b51dbc8d5aa182#diff-14a1e48dc3f5986c82c5098f5436f3d8

And since we have moved to cmake, hopefully building the library becomes easier now - feel free to reopen if you encounter issues!
