### ISSUE TITLE
Implement more math operators

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#581]
At least the operators below are missing in the current [operators catalogue](https://caffe2.ai/docs/operators-catalogue.html).
```
abs
greater_than
less
square
```

https://www.tensorflow.org/api_guides/python/math_ops

**Comment by akyrola** [comment]
greater_than = GT
less = LT
square = Sqr

Absolute value seems indeed missing, will create one.

**Comment by futurely** [comment]
Thanks！

Please try search "greater than", "greater", "gt" or ">" on the operators catalogue page. It is clearly very difficult to find the needed operators. Related to https://github.com/caffe2/caffe2/issues/415.

**Comment by akyrola** [comment]
Yeah, the operator docs need some love. Let me try to improve docs for those ops at least.

**Comment by akyrola** [comment]
FYI: https://github.com/caffe2/caffe2/commit/e6c8e0e40506192c48e175bd87b2fcf3f0cedcce

**Comment by xshwen** [comment]
which one is square root?

**Comment by xshwen** [comment]
@akyrola Which one in the current operators catalogue refers to the square root?
