### ISSUE TITLE
Add support to implement operators in Python

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#582]
to reduce the development cost in the research prototype phase.

https://github.com/dmlc/mxnet/blob/master/docs/how_to/new_op.md

**Comment by mfawzymkh** [comment]
There is a Python Operator 
https://caffe2.ai/docs/operators-catalogue.html#python

Here is an example of how you could use it 
https://github.com/caffe2/caffe2/blob/master/caffe2/python/python_op_test.py#L46

**Comment by futurely** [comment]
Thanks!
