### ISSUE TITLE
Implement operator to get tensor size

### ISSUE THREAD

**Issue by futurely** [facebookarchive/caffe2#583]
, i.e. the number of elements.

https://www.tensorflow.org/api_docs/python/tf/size

**Comment by mfawzymkh** [comment]
We have the Shape operator 
https://caffe2.ai/docs/operators-catalogue.html#shape
The size can be calculated easily from it. 

Do you think there is value to make size as an operator in C2 (i.e. is this common enough?) 
Thanks

**Comment by futurely** [comment]
How to calculate the product of each value of the returned shape tensor? The value is to reduce at least two functions calls to one.

**Comment by mfawzymkh** [comment]
I see your point.  An alternative solution is to write a python op that would produce the product of the returned tensor from the Shape op, but I can see how this is painful if this is a common operation. 

I'll add a size operator. 
thanks for brining this up.

**Comment by mfawzymkh** [comment]
@futurely , this is implemented now 
https://github.com/caffe2/caffe2/commit/dcef8c682baf8b09de181a637213ec57e796e83b
Please let me know if you have any questions. 
Thanks

**Comment by futurely** [comment]
Thanks!
