### ISSUE TITLE
caffe_translator.py doesn't support "Slice" layer ?

### ISSUE THREAD

**Issue by MaeThird** [facebookarchive/caffe2#589]
When I use caffe_translator.py  to translate my model exported by caffe to Caffe2's  *.pb file, I got an issue  and this layer' type is "Slice".Like:
KeyError: 'No translator registered for layer: name: "slice1"\ntype: "Slice"\nbottom: "conv1"\ntop: "slice1_1"\ntop: "slice1_2"\nslice_param {\n  slice_dim: 1\n}\n yet.

This script doesn't support "Slice" layer by default ?

**Comment by ShangxuanWu** [comment]
This error still exists. Can you re-open this issue?
@MaeThird  Did you find a way to solve this?

**Comment by ikoc** [comment]
I have also encountered same problem. There are related just 2 issue and i could'nt find any answer. Have you solve the problem @ShangxuanWu ?

**Comment by EJShim** [comment]
not solved yet?? :(

**Comment by MaximArtemev** [comment]
Same error here
