### ISSUE TITLE
caffe2 android Could NOT find RocksDB,Glog,CUDA,what is the problem 

### ISSUE THREAD

**Issue by akbarxie** [facebookarchive/caffe2#590]
I am compiling caffe2 on android ,ndk version is android-ndk-r12b
but I got the problems as flows:

-- Could NOT find GFlags (missing:  GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY) 
CMake Warning at cmake/External/gflags.cmake:10 (message):
  gflags is not found.  Caffe2 will build without gflags support but it is
  strongly recommended that you install gflags.
Call Stack (most recent call first):
  cmake/External/glog.cmake:2 (include)
  cmake/Dependencies.cmake:64 (include)
  CMakeLists.txt:82 (include)

-- Could NOT find Glog (missing:  GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CMake Warning at cmake/External/glog.cmake:13 (message):
  glog is not found.  Caffe2 will build without glog support but it is
  strongly recommended that you install glog.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:64 (include)
  CMakeLists.txt:82 (include)

CMake Warning at cmake/Dependencies.cmake:70 (message):
  Not compiling with glog.  Suppress this warning with -DUSE_GLOG=OFF
Call Stack (most recent call first):
  CMakeLists.txt:82 (include)

CMake Warning at cmake/Dependencies.cmake:83 (message):
  Not compiling with gflags.  Suppress this warning with -DUSE_GFLAGS=OFF
Call Stack (most recent call first):
  CMakeLists.txt:82 (include)

-- Could NOT find RocksDB (missing:  RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
CMake Warning at cmake/Dependencies.cmake:131 (message):
  Not compiling with RocksDB.  Suppress this warning with -DUSE_ROCKSDB=OFF
Call Stack (most recent call first):
  CMakeLists.txt:82 (include)

CMake Error at /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (include):
  include could not find load file:

    /usr/local/share/OpenCV/OpenCVModules_armeabi_v7a.cmake
Call Stack (most recent call first):
  cmake/Dependencies.cmake:164 (find_package)
  CMakeLists.txt:82 (include)

CMake Error at /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found suitable exact
  version "8.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.4/Modules/FindCUDA.cmake:953 (find_package_handle_standard_args)
  third_party/android-cmake/android.toolchain.cmake:1546 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:276 (find_host_package)
  cmake/Dependencies.cmake:164 (find_package)
  CMakeLists.txt:82 (include)

-- Configuring incomplete, errors occurred!
See also "/home/kevin/Documents/caffe2/build_android/CMakeFiles/CMakeOutput.log

thanks in advance.

**Comment by lzx1413** [comment]
these package will be set off while building the android version

**Comment by akbarxie** [comment]
I find that ,I just set off 
//Use Cuda
USE_CUDA:BOOL=OFF
//Use openCV
USE_OPENCV:BOOL=OFF
and I pass the errors
thanks all the same

**Comment by ghost** [comment]
Is it possible to build on Android with Cuda? I'd like to run on an Nvidia Shield tablet.

**Comment by akbarxie** [comment]
maybe you can have a try ,and tell us the results,but you may get errors like me .
