### ISSUE TITLE
Convert the caffe model to the caffe2,how to get the mean_file (xxx.npy)?

### ISSUE THREAD

**Issue by MrZhangCF** [facebookarchive/caffe2#591]
i converted my caffe model to the caffe2 as the tutorial,but it did't generate the mean_file. how can i get this?

**Comment by dzyong** [comment]
@MrZhangCF How do you solve this problem?

I have tried to use Caffe's mean file directly in Caffe2, but it complain the mean file doesn't contain qtensor fields.
Is there any way to translate Caffe's mean file to Caffe2's?
I submited a new issue for this in:
https://github.com/pytorch/pytorch/issues/7945
