### ISSUE TITLE
build for ubuntu 14.04 fail

### ISSUE THREAD

**Issue by xhsoldier** [facebookarchive/caffe2#592]
Error msg below:
Linking CXX executable binaries/blob_gpu_test
libCaffe2_CPU.so: undefined reference to `XXH64'
libCaffe2_CPU.so: undefined reference to `caffe2::signalFailure(caffe2::Blob*, gloo::IoException&)'

**Comment by yuhengqiu** [comment]
Me too. I got following error msg:
-------
[ 86%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/learning_rate_op_gpu.cc.o
Linking CXX shared library libCaffe2_GPU.so
make[3]: Leaving directory `/home/caffe2/build'
[ 86%] Built target Caffe2_GPU
make[3]: Entering directory `/home/caffe2/build'
Scanning dependencies of target blob_gpu_test
make[3]: Leaving directory `/home/caffe2/build'
make[3]: Entering directory `/homecaffe2/build'
[ 87%] Building CXX object caffe2/CMakeFiles/blob_gpu_test.dir/core/blob_gpu_test.cc.o
Linking CXX executable binaries/blob_gpu_test
libCaffe2_CPU.so: undefined reference to `XXH64'
collect2: error: ld returned 1 exit status
make[3]: *** [caffe2/binaries/blob_gpu_test] Error 1
make[3]: Leaving directory `/home/caffe2/build'
make[2]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
make[2]: Leaving directory `/home/caffe2/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/caffe2/build'
make: *** [all] Error 2

**Comment by NicoMittenzwey** [comment]
Same problem here, however I'm running CentOS 7.3 and CUDA 8.0.61.
This function is defined in xxhash: http://www.xxhash.com However, don't have the time to include that properly in the code atm.

**Comment by pietern** [comment]
@xhsoldier Thanks for reporting!

@andrewwdye Fixed this in f24c1b8d8c0da1309dd447fa90d77c2432847d9b
