### ISSUE TITLE
no such include file : xxhash.h 

### ISSUE THREAD

**Issue by yonghenglh6** [facebookarchive/caffe2#594]
./caffe2/operators/funhash_op.h:#include <xxhash.h>
./caffe2/operators/sparse_funhash_op.h:#include <xxhash.h>

These two file is just added to master from experiment 12 hours ago. 
But xxhash doesnot exists both in third_party or system.

Please fix this.  
Thanku

**Comment by pietern** [comment]
Thanks for posting. Reverting the offending commit.

**Comment by pietern** [comment]
Reverted in b1aaba12f787589f44e4a3837f6cbf2735170ecf.
