### ISSUE TITLE
Saving/Exporting a CNN as "init_net.pb" and "predict_net.pb" after first time creation and training with Python and how to and Re-train it (CNN: lenet (MNIST))

### ISSUE THREAD

**Issue by ThomasGueldner** [facebookarchive/caffe2#597]
Hi guys!

I need your kind help with this little thing here. 
My post is referring to another post #487, but since this one is rather old, I would like to bring this topic back again since there still might be people outside with the same question(s).

Let's get to my issue(s):
I have been checking the caffe2 homepage and google for quite some time to get some valuable information about how to **export/save** a model after it has been created and trained with Python. 

I have been working through the online MNIST tutorial on the caffe2 page, which is - by the way - nice :). But to my regrets, this tutorial doesn't cover, how I could ever convert my created and trained model into the above mentioned persistent .pb-format using Python. I know that the created model in that tutorial is not really complex and therefore doesn't necessarily need to be exported, but for the sake of my experience and understating the improved philosophy of caffe2 I would like to do so. Is there any workflow on that?

The company I am working for is currently working on a CNN project which intends to change their using caffe1-model into caffe2. We know how to convert the model using the caffe_translater.py, but we are wondering, **how we can **re-train** a caffe2 model (init_net.pb and predict_net.ob) once it has been successfully converted? Does someone have any ideas or experiences with that**?

For any sort of useful information regarding the issue(s) here, I will extremely appreciate it! :)

**Comment by raininglixinyu** [comment]
+1 ,  I am also curious about this question.

**Comment by raininglixinyu** [comment]
+1 , I am also curious about this question.

**Comment by peterneher** [comment]
Wondering this too. Meanwhile there are three github issues where people are asking how to perform a basic task like saving trained models and nobody seems to be able to answer it ...

**Comment by ThomasGueldner** [comment]
Yes, I just want to do a quite basic task in caffe2. I wished, this one also would have been covered in the caffe2 tutorial section on the caffe2's offical homepage. Well, caffe2 has been made public just in April 2017, so this whole thing is still "young" and need some more time to provide information for caffe2-beginners (like me ^^).
 
However, my experience with caffe1 just seems to be not enough to successfully solve my issue(s) with the model saving and re-training in caffe2. My coworker and I, we recently have been trying together, to somehow get the MNIST lenet-model saved so that we can use it then for re-training (by loading the pb-files) and the prediction stuff. But we failed to do so since there is still not enough information outside on how to successfully accomplish it. Unfortunately, we also haven't found any example on the internet yet which exactly describes how to do it. ...Means, keep searching, studying and also waiting ^^. I won't give up the hope that someone here will enlighten us with his/her wisdom about this issue :).

**Comment by ThomasGueldner** [comment]
A good answer - given by the user @peterneher - can be found here #642. Therefore, I am gonna close this issue here.

**Comment by iteal** [comment]
@ThomasGueldner did you manage to save again a retrained network as init_net and predict_net? I have a problem training again from loaded values I explained in #1068
