### ISSUE TITLE
caffe_translator

### ISSUE THREAD

**Issue by zlbing** [facebookarchive/caffe2#599]
how could i know the caffe2 model is translated correctly through the original caffe model?

**Comment by lzx1413** [comment]
same input ,same output?

**Comment by zlbing** [comment]
Same input, different output.
I convert YOLO  from caffe model, and  it shows the caffe2 model has the same structure and params with caffe model. However, the outputs of caffe and caffe2 model are different.

**Comment by lzx1413** [comment]
try to check the feature maps layer by layer

**Comment by tlhchutang** [comment]
#595 I have met the same issue, I think this issue is caused by that your  leakyReLU layers in your network

**Comment by tlhchutang** [comment]
I added a solution in #595 , you could try whether it works or not.
@zlbing

**Comment by zlbing** [comment]
@tlhchutang  I have tried your solution, It does works. thank you. : )
