### ISSUE TITLE
Importing data in Windows

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#604]
I'm trying to run the MNIST notebook tutorial on a Windows machine, but it fails at the point where it is meant to build the database. I've run the tutorial successfully on an Ubuntu virtual machine and copied the database files over, however it fails at the point it runs the net:

`return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at db.h:174] db_. Cannot open db: E:\nets\tutorials\tutorial_data\mnist\mnist-train-nchw-leveldb of type leveldb Error from operator:
output: "dbreader_E:\\nets\\tutorials\\tutorial_data\\mnist\\mnist-train-nchw-leveldb" name: "" type: "CreateDB" arg { name: "db_type" s: "leveldb" } arg { name: "db" s: "E:\\nets\\tutorials\\tutorial_data\\mnist\\mnist-train-nchw-leveldb"}`

Presumably this is because caffe2 was built without leveldb, as it is supposedly not available on Windows. I tried using an lmdb database instead, but the same error occurs. I was unable to build caffe2 with lmdb support, so presumably this is the reason.

So my question is: is it possible to build caffe2 on Windows with either leveldb or lmdb support, and if not what other options are there for importing data into caffe2 on Windows?

**Comment by ghost** [comment]
I think I've solved it. If anyone's interested, Caffe2 can be built on Windows with leveldb if you do the following:

- Download Boost and build it, specifying static libraries (the default is shared) and 64 bit if necessary (32 bit is default)
- Get the qdb branch of leveldb: https://github.com/bureau14/leveldb
- Build leveldb, ensuring Runtime Library is set to 'Multi-Threaded (/MT)' in properties,C/C++ for both the leveldb and leveldbutil projects
- Download the Windows port of Snappy for C++

**Comment by aaronmarkham** [comment]
Thanks @m00nkeh I'll add these notes to the Windows build instructions.
