### ISSUE TITLE
build_android.sh   ANDROID_NATIVE_API_LEVEL=19  build failed

### ISSUE THREAD

**Issue by xueyedamo** [facebookarchive/caffe2#608]
Can Caffe2 support  ANDROID_NATIVE_API_LEVEL 19? 
I use Android 4.4 so i want compile caffe2 for Android 19.
When i set  "ANDROID_NATIVE_API_LEVEL=19" in build_android.sh  and i get compile error.  /opt/android/ndk/android-ndk-r10c/sources/androidufeaturesu-features.c:525:14: error: expected ';' before '_rc'
/opt/android/ndk/android-ndk-r10c/sources/androidufeaturesu-features.c:525:14: error: '_rc' undeclared (first use in this function)

**Comment by lsn2000** [comment]
r10c is pretty old, did you try r14b?

**Comment by xueyedamo** [comment]
Sorry,the error is same with r10c.

/opt/android/ndk/android-ndk-r14b/sources/android/cpufeatures/cpu-features.c:551:14: error: expected ';' before '_rc'
     int fd = TEMP_FAILURE_RETRY(open(filepath, O_RDONLY));
              ^
/opt/android/ndk/android-ndk-r14b/sources/android/cpufeatures/cpu-features.c:551:14: error: '_rc' undeclared (first use in this function)
     int fd = TEMP_FAILURE_RETRY(open(filepath, O_RDONLY));

**Comment by lzx1413** [comment]
https://stackoverflow.com/questions/32917185/how-do-i-get-past-ndk-build-failure-in-cpu-features-c, this helps. @xueyedamo but will lead to new problem.

**Comment by lsn2000** [comment]
in caffe2/scripts/build_android.sh I have

cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake \
    -DCMAKE_INSTALL_PREFIX=../install \
    -DANDROID_NDK=$NDK_ROOT \
    -DCMAKE_BUILD_TYPE=Release \
    -DANDROID_ABI="arm64-v8a" \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -DUSE_CUDA=OFF \
    -DBUILD_TEST=OFF \
    -DUSE_LMDB=OFF \
    -DUSE_LEVELDB=OFF \
    -DUSE_OPENCV=OFF \
    -DUSE_NNPACK=OFF \
    -DBUILD_PYTHON=OFF \
    -DPROTOBUF_PROTOC_EXECUTABLE=$CAFFE2_ROOT/build_host_protoc/bin/protoc \
    -DCMAKE_VERBOSE_MAKEFILE=1 \
    -DUSE_MPI=OFF \
    -DUSE_OPENMP=OFF \
    -DBUILD_SHARED_LIBS=ON \
    || exit 1


you may want to change  -DANDROID_ABI and -DANDROID_NATIVE_API_LEVEL according to your device type. try several different values 


in caffe2/CMakeLists.txt I have

# ---[ Build flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11 -O3")

if(NOT MSVC)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing")
else()
  if (NOT ${BUILD_SHARED_LIBS})
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
  endif()
endif()

which seems to work for my device.

**Comment by Maratyszcza** [comment]
With PR #1957 Caffe2 builds for API 19 just fine. As we switched to android.cmake.toolchain from Android NDK, you'd need to specify API 19 target as `-DANDROID_PLATFORM=android-19`
