### ISSUE TITLE
"file INSTALL cannot find" error when executing make install

### ISSUE THREAD

**Issue by ckeyever** [facebookarchive/caffe2#612]
I‘m building caffe2 for android, and I successfully run scripts/build_android.sh. But error occurs when I execute make install in caffe2/build_android. The error is list bellow:
Install the project...
/usr/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Up-to-date: /home/chengbin/caffe-pkg/caffe2-b1aaba12f787589f44e4a3837f6cbf2735170ecf/build_android/../install/lib/libprotobuf-lite.a
-- Up-to-date: /home/chengbin/caffe-pkg/caffe2-b1aaba12f787589f44e4a3837f6cbf2735170ecf/build_android/../install/lib/libprotobuf.a
CMake Error at third_party/protobuf/cmake/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/chengbin/caffe-pkg/caffe2-b1aaba12f787589f44e4a3837f6cbf2735170ecf/build_android/third_party/protobuf/cmake/libprotoc.a".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)

It failed to find third_party/protobuf/cmake/libprotoc.a while libprotobuf-lite.a and libprotobuf.a is OK. It goes well when I comment line 44 in third_party/protobuf/cmake/cmake_install.cmake.

Can anyone help me to fix it?

**Comment by zfc929** [comment]
you shild copy  to /build_android/third_party/protobuf/cmake

**Comment by mynameischaos** [comment]
I have the same problem.

**Comment by Yangqing** [comment]
This might be a cmake problem mixing EXCLUDE_FROM_ALL and install: fix should be in https://github.com/caffe2/caffe2/pull/1157/
