### ISSUE TITLE
Caffe2 build from source gives from caffe2.proto import caffe2_pb2 error

### ISSUE THREAD

**Issue by ajayvohra2005** [facebookarchive/caffe2#620]
caffe2 build from Github source succeeds and following binary test succeeds:

~/caffe2/build/caffe2/binaries$ ./elementwise_op_gpu_test
Running main() from gtest_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from ElementwiseGPUTest
[ RUN      ] ElementwiseGPUTest.And
[       OK ] ElementwiseGPUTest.And (2974 ms)
[ RUN      ] ElementwiseGPUTest.Or
[       OK ] ElementwiseGPUTest.Or (2 ms)
[ RUN      ] ElementwiseGPUTest.Xor
[       OK ] ElementwiseGPUTest.Xor (1 ms)
[ RUN      ] ElementwiseGPUTest.Not
[       OK ] ElementwiseGPUTest.Not (2 ms)
[----------] 4 tests from ElementwiseGPUTest (2979 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (2979 ms total)
[  PASSED  ] 4 tests.

However the import of python module caffe2.proto.caffe2_pb fails, specifically as follows:

~/caffe2/build/caffe2/python$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.proto import caffe2_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/caffe2/build/caffe2/proto/caffe2_pb2.py", line 23, in <module>
    x84\x01\n\tBlobProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12#\n\x06tensor\x18\x03 \x01(\x0b\x32\x13.caffe2.TensorProto\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12%\n\x07qtensor\x18\x05 \x01(\x0b\x32\x14.caffe2.QTensorProto\"K\n\rDBReaderProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x62_type\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t*A\n\nDeviceType\x12\x07\n\x03\x43PU\x10\x00\x12\x08\n\x04\x43UDA\x10\x01\x12\n\n\x06MKLDNN\x10\x02\x12\x14\n\rONLY_FOR_TEST\x10\xc5\xde\xfb\t')
TypeError: __init__() got an unexpected keyword argument 'syntax'
>>> 

I built and installed latest Google protocol buffer from source before building caffe2

~/caffe2/build/caffe2/python$ protoc --version
libprotoc 3.3.0
ubuntu@ip-172-31-18-176:~/caffe2/build/caffe2/python$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf

**Comment by ajayvohra2005** [comment]
I found the problem. The latest version of Google protocol buffer at this time, version 3.3.0, is incompatible with latest version of caffe2. Once I used a compatible version of Google protocol buffer, version 2.6.1,  the issue was resolved.

**Comment by TianBo-Timothy** [comment]
@ajayvohra2005 I do not think this issue should be closed in this way.

If follow the documentation provided in https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile, you are expected to get the latest version of Google protocol buffer. Is it not better to make some changes in caffe2 to follow up the change in protobuf? Or at least, please mention it in the documentation that the user should install version 2.6.1 instead.
  
Besides, compiling caffe (not caffe2) does not suffer from this error.
