### ISSUE TITLE
Raspberry !RuntimeError: Net definition should have a name

### ISSUE THREAD

**Issue by MrZhangCF** [facebookarchive/caffe2#623]
when i try the tutorial [Loading Pre-trained Model](https://caffe2.ai/docs/tutorial-loading-pre-trained-models.html) in the raspberry,it shows that Traceback:
Traceback(most recent call last):
    File "age.py",line 103,in <module>
        p = workspace.Predictor(int_net,predict_net)
RuntimeError: [enforce fail at workspace.cc:260] net_def.has_name().Net definition should have a name.
how to fix this ?

**Comment by MrZhangCF** [comment]
@Yangqing  sorry to disturb! and you know the solution?

**Comment by Seanberite** [comment]
Hi, I have the same problem. How did you solve this?

**Comment by MrZhangCF** [comment]
@Seanberite  yes ,actually i solved this problem by reinstalling the system of raspberry,it is complex but works,hope helpful for you !
