### ISSUE TITLE
Build on Windows 10: build folder incomplete

### ISSUE THREAD

**Issue by citiZenStef** [facebookarchive/caffe2#632]
From running the unmodified build_windows script, all I get is:

caffe2/build/CMakeFiles
caffe2/build/third_party
caffe2/build CMakeCache.txt

-- Could NOT find Git (missing:  GIT_EXECUTABLE)
CMake Error at cmake/ProtoBuf.cmake:21 (message):
  To build protobufs locally (required for Android/iOS/Windows), you will
  need to manually specify a PROTOBUF_PROTOC_EXECUTABLE.  See
  scripts/build_host_protoc.{sh,bat} for more details.

**Comment by ezineo** [comment]
It means your build is incomplete. Maybe you should check the output message in cmd.

**Comment by citiZenStef** [comment]
OK thx I got lazy here...
I was missing git.exe
and I needed to add a PROTOBUF_PROTOC_EXECUTABLE

All ok now.

**Comment by mathCrazyy** [comment]
the same error with you , you said you got lazy here??where?  and add aPROTOBUF_PROTOC_EXECTTABLE，how to do it ,can you share your experience,thank you
