### ISSUE TITLE
What is the different between core.Net and NetDef ?

### ISSUE THREAD

**Issue by honamida** [facebookarchive/caffe2#645]
Both class is about the design of the net.
NetDef can be serialized to string, while core.Net can't.
Can someone explain what is the difference between these two class?

Is there any method to serialize the content of core.Net by Python or C++ API?

Thanks!

**Comment by dzhulgakov** [comment]
core.Net is just a python wrapper around NetDef with some convenient helper functions (e.g. ability to add operators with .Operator syntax). You can always access underlying proto with `.Proto` method. Same goes for other python wrappers, e.g. Plan or ExecutionStep.
