### ISSUE TITLE
Is caffe2 able to use multi-GPUs during test process?

### ISSUE THREAD

**Issue by XhqGlorry11** [facebookarchive/caffe2#646]
Hi all, I remember caffe can use multi-GPUs during train process and only 1 GPU(ordinal 0) during test process. And I'd like to know is caffe2 able to use multi-GPUs during test process?

**Comment by aaronmarkham** [comment]
Hi, you should checkout this multi-GPU tutorial: https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Multi-GPU_Training.ipynb

Note this section:

```
dpm.Parallelize_GPU(
    test_model,
    input_builder_fun=add_image_input_ops,
    forward_pass_builder_fun=create_resnet50_model_ops,
    param_update_builder_fun=None,
    devices=gpus,
)
```

Since Parallelize_GPU is getting called on test_model, it will use the GPUs defined by the `devices` parameter.
