### ISSUE TITLE
Which model should i choose?

### ISSUE THREAD

**Issue by szbach** [facebookarchive/caffe2#661]
i just want to classify the bank invoices ... do anyone could tell me which model (e.g. vggnet, alexnet etc.) i should choose?

**Comment by ShangxuanWu** [comment]
Both are okay.  You can start with alexnet.

**Comment by futurely** [comment]
https://github.com/caffe2/caffe2/blob/master/caffe2/python/models/resnet.py
https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/resnet50_trainer.py

**Comment by szbach** [comment]
@futurely do you mean resnet could deal with it?

**Comment by futurely** [comment]
ResNet has been successfully applied to almost all kinds of compute vision tasks.

https://scholar.google.com.hk/scholar?safe=strict&bav=on.2,or.&biw=1242&bih=602&dpr=1.1&um=1&ie=UTF-8&lr&cites=9281510746729853742
