### ISSUE TITLE
Ubuntu 16.04 install: make fails on contrib/gloo/allreduce_ops.cc.o

### ISSUE THREAD

**Issue by aeonstasis** [facebookarchive/caffe2#671]
I'm attempting to install caffe2 on Ubuntu 16.04 following the installation instructions from [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile). I'm not enabling optional GPU support.

The error trace is below:
```
Scanning dependencies of target Caffe2_CPU
[ 26%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/allreduce_ops.cc.o
/home/aaron/caffe2/caffe2/contrib/gloo/allreduce_ops.cc:6:24: fatal error: gloo/types.h: No such file or directory
compilation terminated.
caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:62: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/allreduce_ops.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/allreduce_ops.cc.o] Error 1
CMakeFiles/Makefile2:1684: recipe for target 'caffe2/CMakeFiles/Caffe2_CPU.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
[2]
```

I also noticed `-- Could NOT find Gloo (missing:  Gloo_INCLUDE_DIR Gloo_LIBRARY)`.

Do I need to manually add a subdirectory of the caffe2 project to an include path?

**Comment by pietern** [comment]
Thanks for reporting. Working on fixing this in #672. Now verifying if this indeed fixes the problem.

**Comment by pietern** [comment]
Can you retry off of master? For me it's working again.

**Comment by aeonstasis** [comment]
Needed to explicitly use `pip2 install protobuf`, but now works, thanks!

**Comment by StatML** [comment]
Hi @pietern, I meet the same problem. It still not be solved...

**Comment by auroua** [comment]
Hi @pietern, I meet the same problem too.
