### ISSUE TITLE
Operator Registry keys

### ISSUE THREAD

**Issue by Voax001** [facebookarchive/caffe2#683]
The following C++ code will fail to run:
```
caffe2::DeviceOption option;
option.set_device_type(caffe2::CUDA);
caffe2::CUDAContext context(option);

caffe2::OperatorDef reludef;
reludef.set_name("Relu");
reludef.add_input("X");
reludef.add_output("Y_pred");
reludef.set_type("Relu");
reludef.mutable_device_option()->set_device_type(caffe2::CUDA);

workspace.RunOperatorOnce(reludef);
```

The reason for this is that the cuda operator registry does not contain a "Relu" operator, but only a "Relu_ENGINE_CUDNN" operator. Several other operators also only have an "_ENGINE_CUDNN" registered. If I use `reludef.set_type("Relu_ENGINE_CUDNN");` it does work.

```
for (auto & key : caffe2::gDeviceTypeRegistry()->at(caffe2::CUDA)->Keys())
    std::cout << key << std::endl;
```
(Partial) Result:
<img width="315" alt="relu" src="https://cloud.githubusercontent.com/assets/26622572/26506244/1e8fc4a2-424c-11e7-860c-0a7e53687c79.png">

Is this working as intended? And does this mean that if I create a network in python which interleaves conv and (normal) "Relu" operators (since Relu_ENGINE_CUDNN does not appear in the operator catalogue) that it will copy data back and forth from the gpu to the cpu to perform the relu operation?

I'm on windows by the way, and had to jump through a few hoops to get operators linked in (/WHOLEARCHIVE crashes the compiler so I link obj files directly), but I don't suppose that's causing this.

**Comment by ezineo** [comment]
It means that you didn't link obj compiled by nvcc.

**Comment by Voax001** [comment]
You're right, that was the problem. Thanks!

Note for others linking to caffe2 with MSVC, link in the object files found in:
```
caffe2/build/caffe2/caffe2_cpu.dir/release/*.obj
caffe2/build/caffe2/caffe2_gpu.dir/release/*.obj
caffe2/build/caffe2/cmakefiles/caffe2_gpu.dir/*/release/*.obj
```
