### ISSUE TITLE
Prediction in C++ with GPU

### ISSUE THREAD

**Issue by peterneher** [facebookarchive/caffe2#694]
Hi everyone, 

I managed to train my networks in python, saving them as .pb file tuple, loading them in C++ and perform a prediction. I have two issues now:

### 1. Using TensorCUDA
Unfortunately I am only able to perform prediction using TensorCPU as input, but not using TensorCUDA. 
If I want to fill my input tensor of type TensorCUDA with data by accessing the data using the pointer 
`float* data = t.mutable_data<float>();`
I get the following errors:
`undefined reference to caffe2::CUDAContext::New(unsigned long)`
`undefined reference to `caffe2::CUDAContext::Delete(void*)`

It works fine when using TensorCPU. Also, it seems like caffe2::Predictor is only implemented for TensorCPU but not for TensorCUDA.

### 2. Training a network using CPU and predicting using GPU (and vice versa)
This does not work and fails with the following error:
`terminate called after throwing an instance of caffe2::EnforceNotMet`
`what():  [enforce fail at operator.cc:110] op. Cannot create operator of type Conv on the device CUDA`

This happens when initializing the network with 
`caffe2::Workspace ws;`
`ws.CreateNet(predict_net, true);`
After loading predict_net with `ReadProtoFromFile`.

Any ideas? Thank you!
Peter

**Comment by futurely** [comment]
What happens if TensorCPU is replaced with TensorCUDA in caffe2::Predictor?

**Comment by peterneher** [comment]
I basically did that in case 1 by implementing the methods of `caffe2::Predictor` myself (see https://github.com/MITK/MITK/blob/master/Modules/DiffusionImaging/DeepDiffusion/cmdapps/Caffe2Test.cpp#L93 (of course locally not commented out) and https://github.com/MITK/MITK/blob/master/Modules/DiffusionImaging/DeepDiffusion/cmdapps/Caffe2Test.cpp#L123-L147). 
But when using 'caffe2::TensorCUDA' [this line](https://github.com/MITK/MITK/blob/master/Modules/DiffusionImaging/DeepDiffusion/cmdapps/Caffe2Test.cpp#L61) cause the errors mentioned above as well as
`undefined reference to long 'caffe2::TypeMeta::Id<caffe2::Tensor<caffe2::CUDAContext> >()'`

**Comment by futurely** [comment]
```cpp
caffe2::TensorCUDA cuda_input(std::vector<int>({1, c, h, w}));
CPUContext cpu_context;
caffe2::TensorCPU cpu_input(cuda_input, &cpu_context);
float* tensor_data = tensor.template mutable_data<float>(cpu_input);
```
https://github.com/caffe2/caffe2/blob/14480d63e3f5cf83e58317499d4de9515e92a7e0/caffe2/core/tensor.h#L105

**Comment by peterneher** [comment]
Thank you for the tip (@futurely), but unfortunately I get the following linker errors when trying this:
`error: undefined reference to 'cudaSetDevice'`
`error: undefined reference to 'cudaGetErrorString'`
`error: undefined reference to 'caffe2::GetCurrentGPUID()'`
and more.

The same is the case if try to do it the other way round by first creating and filling a `caffe2::TensorCPU `and creating a new  `caffe2::TensorCUDA` using the `caffe2::CUDAContext`. Here the ritical line is actually `caffe2::CUDAContext cuda_context;`.

Am I missing a library that I should link?

**Comment by futurely** [comment]
The errors are related to the CUDA libraries and CMake flag [USE_CUDA](https://github.com/caffe2/caffe2/blob/63d4a406be041e04ade70e41f59a66fca197b8b2/CMakeLists.txt#L41).
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#optional-gpu-support

**Comment by peterneher** [comment]
Sure, the question is how...
Maybe since I'm using caffe2 as external project I am missing to link some of the cuda libraries.

**Comment by futurely** [comment]
Add these compilation flags: `-lcudart -lcuda -lcaffe2` or ` -lcaffe2 -lcudart -lcuda`.
https://devtalk.nvidia.com/default/topic/514679/compiling-error-undefined-reference-to-cudamalloc-39-/

**Comment by peterneher** [comment]
Hi @futurely 
Tank you for your help. Everything seems to link correctly now. Nevertheless, I still get errors using caffe2::TensorCUDA during execution:

(1) first approach

```C++
int w,h,c; w=64; h=64; c=1;
caffe2::TensorCUDA input(std::vector<int>({1, h, w, c}));
float* input_data = input.mutable_data<float>();
int counter = 0;
for (int x = 0; x < h; x++)
    for (int y = 0; y < w; y++)
        for (int j = 0; j < c; j++)
        {
          input_data[counter] = 0;
          counter++;
        }
```
This results in a crash when writing to input_data (`input_data[counter] = 0;`)

Then I tried the approach you indicated above:
```C++
int w,h,c; w=64; h=64; c=1;
caffe2::TensorCUDA input(std::vector<int>({1, h, w, c}));
caffe2::CPUContext cpu_context;
caffe2::TensorCPU cpu_input(input, &cpu_context);
float* input_data = cpu_input.template mutable_data<float>();
int counter = 0;
for (int x = 0; x < h; x++)
    for (int y = 0; y < w; y++)
        for (int j = 0; j < c; j++)
        {
          input_data[counter] = 0;
          counter++;
        }
```
This yields the following error:

```
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at tensor.h:531] meta_.id() != 0. Calling raw_mutable_data() without meta, but the current meta is of unknown type. 
```

Again, everything works fine when only using caffe2::TensorCPU. Do I need to initialize caffe2::TensorCUDA in a different way than caffe2::TensorCPU?

Thank you!
Peter

**Comment by futurely** [comment]
Caffe2 is positioned to be an efficient runtime on the mobile platforms. There are some alternatives frameworks to predict with CUDA.

**Comment by peterneher** [comment]
Am I understanding correctly that you are telling me that Caffe2 actually does not "really" support GPU prediction? I guess some of the caffe2 developers (@akyrola, @bwasti, @salexspb ) might object here :-)

In light of the claims on the corresponding webpages, this would seem kind of strange:

> Caffe2 is fine tuned from the ground up to take full advantage of the latest NVIDIA Deep Learning SDK libraries, cuDNN , cuBLAS and NCCL , to deliver high-performance, multi-GPU acceleration for desktop, data centers, and embedded edge devices 

or 

> You can bring your creations to scale using the power of GPUs in the cloud or to the masses on mobile with cross- platform libraries.

**Comment by salexspb** [comment]
I recommend not using Predictor as of right now and just run networks directly (like workspace->RunNet), it will give you more flexibility if Predictor interface doesn't work for you. As you could see, it is a very thin wrapper on top of normal Caffe2 nets. 

As of dealing with Cuda tensors - I don't think direct access is supported. You need Caffe2 nets to populate them. For example, you could use CopyCPUToGPU operator. 

Let me know if this helps!

**Comment by alexge233** [comment]
I'm asking the same question on [stackoverflow](https://stackoverflow.com/q/45484051/499699) and referencing this issue. It would be extremely useful to be able to allocate CUDA tensors directly, since I do a lot of image pre-processing using OpenCV's CUDA API.

**Comment by leugenea** [comment]
Month since last reply… Does anyone have success on running on GPU using C++ API?

**Comment by breadbread1984** [comment]
include <caffe2/core/context_gpu.h> and add following code before create any NetDef objects.
`DeviceOption option;`
`option.set_device_type(CUDA);`
`new CUDAContext(option);`

**Comment by alexge233** [comment]
@breadbread1984 Can you please provide an example of how to assign CUDAContext directly? Preferably from a kernel?

**Comment by breadbread1984** [comment]
please refer to my project at https://github.com/breadbread1984/Caffe2-C-demo

**Comment by alexge233** [comment]
@breadbread1984 Hi, I'm sorry but your code seems to upload a CPU tensor to a GPU tensor. Do you know how to directly assign/copy/allocate data to a CUDA Tensor?

**Comment by breadbread1984** [comment]
@alexge233 there is only a data bus between cpu and gpu. there are no adress bus and control bus between them. this means that you can't assign values to gram directly. you can only load data from ram to gram.

**Comment by breadbread1984** [comment]
oh sorry, did you mean Nvidia Tegra K1's unified memory pointer? I don't know how to develop with Tegra.

**Comment by alexge233** [comment]
@breadbread1984 
No I meant any CUDA device. I wasn't clear, I've opened a similar issue #1004, and a [stackoverflow question](https://stackoverflow.com/questions/45484051/caffe2-tensorcudacontext-assignment-construction-or-copy). My data has already been allocated on device memory after pre-processing using OpenCV's GPU kernels. The data is split, and ready to be assigned to a CUDA vector. Surely there must be a way to do this, other than downloading it from the device to host, only to re-upload it to the device from the host, which is what's happening with all the examples I've seen so far.

**Comment by salexspb** [comment]
Answered on #1004 about the new question. Let me close this issue as I see there is enough information about generally running nets on GPU here. If there are new more specific questions, please open new issues. Thanks!

**Comment by beichen2012** [comment]
@salexspb, where is the "CopyCPUToGPU" operator?

**Comment by salexspb** [comment]
https://github.com/pytorch/pytorch/search?q=CopyCPUToGPU&unscoped_q=CopyCPUToGPU
