### ISSUE TITLE
I can translate your Docs to Korean to improve the accessibility of Korean users!

### ISSUE THREAD

**Issue by ASTONISHER** [facebookarchive/caffe2#702]
Hello, I am a college student from Korea who is interested in using Caffe2. I want to participate in the project as part of the school ‘open source practice project’, so I leave the issue! Maybe I can translate your homepage(http://caffe2.ai) Docs tutorial into Korean. May I release it to improve the accessibility of Korean users?

**Comment by aaronmarkham** [comment]
That would be great! We're currently working on a translation management setup that will allow us to keep track of each translation, however, don't let that hold you up. We can always fit your translations in later and in the meantime link to them from the English page... maybe we can even do some default language detection on the webpage itself.
When you create a translated document, just tag me and I'll help you get it posted and linked up.

**Comment by ASTONISHER** [comment]
Thanks a lot! I'll bring it up several days later! 😄
