### ISSUE TITLE
Convert to caffe2 from caffe1

### ISSUE THREAD

**Issue by roysG** [facebookarchive/caffe2#704]
Hi,
I have model that predict the age, the problem is that it run very slow for my needs.

for instance:
I go over 200 images in 1 minute.

My computer info is: 
i7,16GB Memory,gtx 1070.

If i will convert the model to caffe2, the speed may be improve?
Thanks for your help.

**Comment by Yangqing** [comment]
It seems to be that your Caffe2 build might be slow - did you turn on typical optimization options? Caffe's installation page might be a good start:

http://caffe.berkeleyvision.org/installation.html

Basically, C and C2 during inference time, using the same library, may give one very similar performance.

**Comment by roysG** [comment]
Hi @Yangqing, can you expand or give a link for the optimization options, thanks.
