### ISSUE TITLE
Iterate through memory rather than DB

### ISSUE THREAD

**Issue by ilkarman** [facebookarchive/caffe2#705]
In the [MNIST tutorial](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST-light.ipynb) a leveldb file is created from the text-data; and on the [website ](https://caffe2.ai/docs/tutorial-create-your-own-dataset.html)it's shown how to create your own database. 

I have enough RAM to avoid this IO operation and wanted to replace:

`data_uint8, label = train_model.TensorProtosDBInput()`

With just a numpy array (obs x channels x height x width). However, I'm having a hard time locating code to help me do this

**Comment by peterneher** [comment]
I emplemented an example for classification with numpy arrays instead of leveldb input: https://github.com/peterneher/peters-stuff/blob/master/Caffe2Scripts/classification_no_db_example.py
