### ISSUE TITLE
Failed in test after build

### ISSUE THREAD

**Issue by roysG** [facebookarchive/caffe2#712]
@roy:~/caffe2/build$ sudo pip install numpy protobuf:

The directory '/home/roy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/roy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/dist-packages (from protobuf)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools->protobuf)

------------------
python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
"Failure"

------------------------
 python -m caffe2.python.operator_test.relu_op_test

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/roy/caffe2/build/caffe2/python/operator_test/relu_op_test.py", line 6, in <module>
    from caffe2.python import core
  File "caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ImportError: No module named past.builtins

**Comment by ChiFang** [comment]
it seem that you just miss past module.
if  you use python 2.x, just use 
`"$ pip install future` to install according [package index](https://pypi.python.org/pypi/past/)
it work for me~~~

**Comment by rudy-letote** [comment]
it is strange.no module named past,but we need to install future.thanks to your answers,it solve my problem perfectly

**Comment by rudy-letote** [comment]
> it seem that you just miss past module.
> if you use python 2.x, just use
> `"$ pip install future` to install according [package index](https://pypi.python.org/pypi/past/)
> it work for me~~~

it is strange.no module named past,but we need to install future.thanks to your answers,it solve my problem perfectly
