### ISSUE TITLE
IndexError when use gpus [4,5,6,7]

### ISSUE THREAD

**Issue by madongyu** [facebookarchive/caffe2#714]
When I use four gpus [0,1,2,3] to train, it works, but I change to [4,5,67], it throw like that

  File "/usr/local/caffe2/python/data_parallel_model.py", line 149, in Parallelize_GPU
    _AllReduceGradients(devices, model_helper_obj, rendezvous, use_nccl)
  File "/usr/local/caffe2/python/data_parallel_model.py", line 599, in _AllReduceGradients
    _AllReduceGradientsSingleHost(devices, model, use_nccl)
  File "/usr/local/caffe2/python/data_parallel_model.py", line 741, in _AllReduceGradientsSingleHost
    devices, model, model.net, grad_name, use_nccl, last_out
  File "/usr/local/caffe2/python/data_parallel_model.py", line 529, in _AllReduce
    sum2(0, 1)
  File "/usr/local/caffe2/python/data_parallel_model.py", line 517, in sum2
    [blobs_group[d1], blobs_group[d2]], [blobs_group[d1]],
IndexError: list index out of range

I read the code in  data_parallel_model.py

    def sum2(d1i, d2i):
        d1 = model._devices[d1i]
        d2 = model._devices[d2i]
        device_opt = core.DeviceOption(caffe2_pb2.CUDA, d1)
        with core.DeviceScope(device_opt):
            net.Sum(
                [blobs_group[d1], blobs_group[d2]], [blobs_group[d1]],
                name="dpm",
            )

the value of d1 is 4， however, then len of blobs_group is 4, I think

**Comment by lukeyeager** [comment]
I wonder if this is related to https://github.com/caffe2/caffe2/pull/674?
/cc @akyrola 

Also, it might be worth updating your build to include my refactoring in https://github.com/caffe2/caffe2/pull/659. I don't think it would change anything, but it's worth a try.

**Comment by madongyu** [comment]
@lukeyeager  I have fix this problem after pull the latest master branch
the reduce function of  sum2  is change to sumN
thanks for help
