### ISSUE TITLE
LSTM Examples?

### ISSUE THREAD

**Issue by ilkarman** [facebookarchive/caffe2#722]
It seems that [brew ](https://caffe2.ai/docs/brew.html)doesn't wrap a helper-function around creating LSTMs.

Apart from the char-RNN example is there anything around that would help creating an LSTM for classification (rather than generating text) e.g. MNIST?

**Comment by akyrola** [comment]
caffe2/python/models/seq2seq/train.py is a more involved example, have a look at that?

**Comment by faj2007** [comment]
someone figure out this? I am also working on this, but it seem that lack of documentation. It is hard to debug for me. I can train the classification by the modified charRNN.py. But the testing part is quite different with the generate_text function.

**Comment by faj2007** [comment]
I figure out how to train and test the LSTM networks now. If some one interested in training the LSTM classifier in caffe2 and have some problems, maybe I can help.

**Comment by LouiseAbela** [comment]
@faj2007 sorry to jump in. I'm trying to do a classification for activity recognition using LSTMs. I tried to change charRNN.py, but have some problems with the output and inference part. Would it be possible to help me please?

**Comment by faj2007** [comment]
Do you mean you have problems in the testing part? In charRNN it is in generate model, at time T, it outputs its values value_output as the input of next time T+1. You need to rewrite this part(GenerateText function) for the classification problem. Also one important thing is change the output dimensions in the training network. output dimensions=output classes you need.

**Comment by faj2007** [comment]
@LouiseAbela

**Comment by faj2007** [comment]
Then I haven't try it yet. may be the prepare_state and predictions are the things you need to handle. Sorry about that, good luck!

**Comment by LouiseAbela** [comment]
I figured it out thanks :D, I just used the mobile_exporter

**Comment by ycAlex11** [comment]
@LouiseAbela  I am current trying to modify char_rnn.py, but I got problem to save the model to .pb file. I have viewed the tut, but I am sucks on get the deploy_model for mobile_exporter. could u give a hand. 
cheers

**Comment by LouiseAbela** [comment]
I don't get the question sorry. What didn't you get?

**Comment by ycAlex11** [comment]
@LouiseAbela  sorry for confuse u, let me make this simple, I got issue to save the model after training.. that is it

**Comment by LouiseAbela** [comment]
If you want pb file you can use [https://github.com/caffe2/caffe2/blob/master/caffe2/python/predictor/predictor_exporter.py](url). In the you will need to use save_to_db after creating a predictor_exoirt_meta. I built the method from the test, but don't have access to that code currently. Hope this helps!

**Comment by LouiseAbela** [comment]
Hi, Sorry, I don't have access to it now, and for now I can't as it's my
thesis code :/. When I have time I will make a dummy example that I can
share but it might take a while. But if you read the test part of the
PredictorExporter you should be able to do it.

There you go https://github.com/camel007/caffe2-mobilenet/blob/master/mobile_net_trainer.py, I found you a good example

**Comment by LouiseAbela** [comment]
There you go [`https://github.com/camel007/caffe2-mobilenet/blob/master/mobile_net_trainer.py`](url), I found you a good example

**Comment by ycAlex11** [comment]
@LouiseAbela  thanks for your reply, I will try and hope I can figure it out

**Comment by ycAlex11** [comment]
@LouiseAbela  one more thing, what you mean the test part of PredictorExporter? in which file?

**Comment by LouiseAbela** [comment]
For each of the files there is test, but if you use the example I gave you
in the last link it will be almost copy and paste. Of course you have to
change inputs, and outputs and paths.
