### ISSUE TITLE
How to use NNPACK or EIGEN for conv process in C++ codes?

### ISSUE THREAD

**Issue by Devin0202** [facebookarchive/caffe2#726]
After implementing inference with Caffe2 C++ codes, I found that even if choosing "NNPACK ON", 
Caffe2 do the conv process of inference  finally with "conv_op_impl.h", 
and it seemed that it is not using NNPACK or EIGEN.
Besides, I think the NNPACK for conv is written in "nnpack_ops.cc", EIGEN in "conv_op_eigen.cc", but in my project, it never use functions in them.
Is this problem involved with net construction?
How can I use EIGEN or NNPACK for doing conv process?
Thanks.

**Comment by zfc929** [comment]
I working in c++ codes, I don't know how to set conv engine “NNPACK ” ,did you solve the problem ?
Could you share your code?

**Comment by ezineo** [comment]
Here is an operator example in predict_net.pbtxt:
```python
op {
  input: "data"
  input: "conv1_w"
  input: "conv1_b"
  output: "conv1"
  type: "Conv"
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "kernel"
    i: 3
  }
  engine: "NNPACK"
}
```
You can use `ReadProtoFromFile` in your c++ code to make that effect.

**Comment by Devin0202** [comment]
Hi， @ezineo 
When I used *caffe_translator.py* for converting Caffe1 to Caffe2,
It only got *predict_net.pb* as binary file.
How can I get the file as you mentioned above *predict_net.pbtxt*?
After I get this one, May I set the **engine: "NNPACK"** for using NNPACK or not?
Thank you!

**Comment by zfc929** [comment]
hi @DevinHiscene  @ezineo 
I used caffe_translator.py for converting Caffe1 to Caffe2 too
the predict_net.pb as binary file,
I don't to how to set NNPACK

**Comment by zfc929** [comment]
I used caffe_translator.py for converting Caffe1 to Caffe2  on using NNPACK
modify predictor_verifier.cc:  std::cout<<predictor->def().DebugString() <<std::endl;
and written  predictor->def().DebugString() to file:temp.txt,
then Manual modify the temp.txt  :add engine: "NNPACK"
use ReadProtoFromFile in your c++ code to make that effect.

**Comment by Devin0202** [comment]
Hi @zfc929,
Your suggestion is very helpful!
And the result(*.txt*) is easy for human reading and modifying.
But one doubt, have you tested that the manual modify is whether effective?

Neverthless, you may use following codes for using NNPACK for Conv:
```
if ("Conv" == predict_net.op(i).type()){
    predict_net.mutable_op(i)->set_engine("NNPACK");
    //std::cout << "Conv engine used:" << predict_net.op(i).has_engine() << std::endl;
    //std::cout << "Conv engine set:" << predict_net.op(i).engine() << std::endl;
}
```
And I have checked that it really run NNPACK conv method.
Thank you.

**Comment by KaiHu-KH** [comment]
I can use NNPACK for my model, but I want to set the thread pool which default is the total CPU's cores. What should I do?
