### ISSUE TITLE
Kernel Restarting - src/tcmalloc.cc:283] Attempt to free invalid pointer

### ISSUE THREAD

**Issue by wang3t** [facebookarchive/caffe2#728]
Q1: Any suggestion to resolve this ?

Using Jupyter notebook with two tutorial on macOS Sierra(10.12.5)
1. Basics.ipynb
2. Tutorial_3_MNIST.ipynb
Having same/similar issues Kernel Restarting with similar MSG at different address
  src/tcmalloc.cc:283] Attempt to free invalid pointer

For Tutorial_3_MNIST, it contains more info
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x1004b4270 
*** Aborted at 1496414515 (unix time) try "date -d @1496414515" if you are using GNU date ***
PC: @     0x7fff8d79ad42 __pthread_kill
*** SIGABRT (@0x7fff8d79ad42) received by PID 82928 (TID 0x700007183000) stack trace: ***
    @     0x7fff8d87bb3a _sigtramp
    @     0x7000071805c0 (unknown)
    @     0x7fff8d700420 abort
    @        0x10f7e4369 tcmalloc::Log()
    @        0x10f7f41f3 tc_free
    @        0x104685bc2 sqlite3MemFree
    @        0x10468700f sqlite3_free
    @        0x10468715a sqlite3DbFree
    @        0x1046c1b64 vdbeMemClear
    @        0x1046c1bc9 sqlite3VdbeMemRelease
    @        0x1046cd945 vdbeUnbind
    @        0x1046cda19 bindText
    @        0x1046cdea7 sqlite3_bind_text
    @        0x10055d1d3 pysqlite_statement_bind_parameter
    @        0x10055d4e6 pysqlite_statement_bind_parameters
    @        0x10055ba7b _pysqlite_query_execute
    @        0x10000c761 PyObject_Call
    @        0x1000a1874 PyEval_CallObjectWithKeywords
    @        0x1005590a5 pysqlite_connection_execute
    @        0x1000a3302 PyEval_EvalFrameEx
    @        0x1000ac7dc PyEval_EvalCodeEx
    @        0x1000ac988 fast_function
    @        0x1000a338a PyEval_EvalFrameEx
    @        0x1000ac7dc PyEval_EvalCodeEx
    @        0x100035c1b function_call
    @        0x10000c761 PyObject_Call
    @        0x1000a3cea PyEval_EvalFrameEx
    @        0x1000ac7dc PyEval_EvalCodeEx
    @        0x1000ac988 fast_function
    @        0x1000a338a PyEval_EvalFrameEx
    @        0x1000ac7dc PyEval_EvalCodeEx
    @        0x1000ac988 fast_function
[I 07:41:57.840 NotebookApp] KernelRestarter: restarting kernel (1/5)

**Comment by wang3t** [comment]
// 1. re-build without LEVELDB, 
$ cmake -DUSE_CUDA=OFF -DUSE_LEVELDB=OFF .. 

// 2. Following tutorials work !
- Basics.ipynb
- Tutorial_3_MNIST.ipynb

**Comment by aaronmarkham** [comment]
Hi @wang3t, this seems to work to get past the leveldb/tcmalloc problem on MacOS, but then you can't run the main [MNIST tutorial](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb) which uses LevelDB. It could be possible though to switch the database type to minidb and run the tutorial without LevelDB until this tcmalloc problem is sorted out.
`/usr/local/binaries/make_mnist_db --channel_first --db leveldb`... that would be one change there on the `--db` flag plus cleaning up the db naming to reflect minidb instead.

**Comment by moderato** [comment]
@wang3t  I got the same bug when I was using matcaffe. Using this method and rebuilding caffe works for me. Thanks!

**Comment by aywi** [comment]
@wang3t This works for matcaffe too. Thanks!
