### ISSUE TITLE
MNIST learning issue

### ISSUE THREAD

**Issue by szbach** [facebookarchive/caffe2#731]
i run the cells of MNIST.ipynb by using jupyter notebook and get the following issue:
from IPython import display
graph = net_drawer.GetPydotGraph(train_model.net.Proto().op, "mnist", rankdir="LR")
display.Image(graph.create_png(), width=800)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-a7aab8e0a5af> in <module>()
      1 from IPython import display
----> 2 graph = net_drawer.GetPydotGraph(train_model.net.Proto().op, "mnist", rankdir="LR")
      3 display.Image(graph.create_png(), width=800)

/usr/local/caffe2/python/net_drawer.py in GetPydotGraph(operators_or_net, name, rankdir, node_producer)
     88         node_producer = GetOpNodeProducer(False, **OP_STYLE)
     89     operators, name = _rectify_operator_and_name(operators_or_net, name)
---> 90     graph = pydot.Dot(name, rankdir=rankdir)
     91     pydot_nodes = {}
     92     pydot_node_counts = defaultdict(int)

AttributeError: 'NoneType' object has no attribute 'Dot'

Any advice to solve it? thanks.

**Comment by szbach** [comment]
i install python-nvd3 and it works...

**Comment by lxltaibo** [comment]
‘pip install pydot’ may be works.

**Comment by yanxiangyi** [comment]
`sudo apt-get install graphviz` and `pip install pydot`.
