### ISSUE TITLE
Could not find any working toolchain in the NDK

### ISSUE THREAD

**Issue by 408550969** [facebookarchive/caffe2#732]
There is an error when I compile the build_android.sh: 
Building caffe2
CMake Error at third_party/android-cmake/android.toolchain.cmake:616 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:3 (project)

CMake Error: CMAKE_CXX_COMPIL
ER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

I have used android-studio installed android NDK at /home/c408550969/Android/Sdk/ndk-bundle, and I have changed the NDK address of build_android.sh.As follows:
NDK_VERSION="$(ls -1 /home/c408550969/Android/Sdk/ndk-bundle/ | sort | tail -1)"
NDK_ROOT=/home/c408550969/Android/Sdk/ndk-bundle/$NDK_VERSION/

**Comment by dyt001** [comment]
Have you solved this problem? I got the same error. I have tried https://github.com/FreeRDP/FreeRDP/pull/1178 but not work. And change NDK version to r10b (as android.toolchain.cmake needed) did not work either.

**Comment by 408550969** [comment]
The address is incorrect or the folder name is wrong.The name of  folder must be like android-ndk-r14b.
This is my  NDK_VERSION: "$(ls -1 /opt/ | sort | tail -1)"  ,and I put the file in /opt/android-ndk-r14b 
This is my  NDK_ROOT: /opt/$NDK_VERSION/
