### ISSUE TITLE
using caffe2 on android,does anyone knows delete middle layer output in android???

### ISSUE THREAD

**Issue by akbarxie** [facebookarchive/caffe2#742]
I am using caffe2 on android,but I often got out of memory on big image than 400x400 image .when program enter:

` _predictor->run(input_vec,&output_vec);`
and it end on:

![image](https://cloud.githubusercontent.com/assets/17984011/26821522/483cb716-4ad9-11e7-8395-e568b3168482.png)
so,I wander if I need to delete something intermediate output in caffe2 android???

thanks, in advance.

**Comment by chinazhangwenwei** [comment]
hello , yesterday I build Caffe2 by build_android.sh successfully(Ubuntu 14.04.5).but i can not find the result file. why? could you help me ? thank you!!
wwzhang@wwzhang-All-Series:~/caffe2$ ./scripts/build_android.sh ?
make[2]:正在离开目录 `/home/wwzhang/caffe2/build_android'
/usr/bin/cmake -E cmake_progress_report /home/wwzhang/caffe2/build_android/CMakeFiles  100
[100%] Built target tutorial_blob
make[1]:正在离开目录 `/home/wwzhang/caffe2/build_android'
/usr/bin/cmake -E cmake_progress_start /home/wwzhang/caffe2/build_android/CMakeFiles 0

**Comment by akbarxie** [comment]
caffe2 目录下应该一个build_android，你查一下，如果有那就ok。如果没有的话可能需要看一下错误代码
