### ISSUE TITLE
Please add in CMake export targets for users to use find_package(caffe2) in config mode

### ISSUE THREAD

**Issue by jasjuang** [facebookarchive/caffe2#747]
Please add in cmake [export](https://cmake.org/cmake/help/v3.0/command/export.html) functionality so that when I am using caffe2 for my own project I don't have to write my own Findcaffe2.cmake.

As shown in [here](https://cmake.org/cmake/help/v3.0/command/find_package.html), if I write my own  Findcaffe2.cmake I am using "module" mode, but I can avoid writing it if I can use "config" mode which requires cmake export from caffe2.

The old caffe has this and would be very great to have this in caffe2 as well

**Comment by Yangqing** [comment]
Sorry for coming back late in this. After #1354 we have now added the configuration files and when you do make install, they should be also added in the installed folder at share/cmake/Caffe2. If you'd like to give it a shot and share your feedback, that would be super helpful.
