### ISSUE TITLE
Installing caffe2 on mac

### ISSUE THREAD

**Issue by raslann** [facebookarchive/caffe2#749]
I have been trying to install caffe and I get the following error: 

> "error This file was generated by a newer version of protoc which is #error This file was generated by a newer version of protoc which is: error: #error incompatible with your Protocol Buffer headers. Please update
>  #error incompatible with your Protocol Buffer headers.  Please update" 
> 

I have tried to delete the older version of protobuf and install the newer using brew, I have also tried to delete the old header files. But, I think all my trials are wrong because whatever version I install, I still get the same protobuf version: 

`protoc --version 
libprotoc 3.2.0`

Would someone please give concrete advice to solve this issue? Thanks a lot.

**Comment by aaronmarkham** [comment]
Make sure you’ve installed protobuf in both of these two ways: brew install protobuf && sudo pip install protobuf OR brew install protobuf && conda install -y --channel https://conda.anaconda.org/conda-forge protobuf=3.2.0

You can also use the helper scripts in /scripts.
Try out the diagnose_protobuf.py script.
Try the build_host_protoc.sh script.

**Comment by pietern** [comment]
Also see #1328. Closing this issue.
