### ISSUE TITLE
How to Make Pycaffe on Caffe2

### ISSUE THREAD

**Issue by keithoys** [facebookarchive/caffe2#752]
> make: *** No rule to make target 'pycaffe'.  Stop.

May I seek any advice in installing pycaffe with this version of Caffe2 please? :)

**Comment by deepali-c** [comment]
Just `make `.

From the [Getting Started tutorial](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile)
```
git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2
make && cd build && sudo make install
python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
```
