### ISSUE TITLE
Infinite loop in checkpoint_test.py

### ISSUE THREAD

**Issue by lukeyeager** [facebookarchive/caffe2#758]
Causes timeout when running Python tests on TravisCI: https://travis-ci.org/lukeyeager/caffe2/jobs/240150765

It's super easy to reproduce locally:
```
pytest -v caffe2/python/checkpoint_test.py
```
This test is pretty convoluted. I tried to dig in and figure out what the test is supposed to be doing, but I'm going to give up and let the authors of this code figure it out.

/cc @boryiingsu

**Comment by boryiingsu** [comment]
Thanks for reporting. I am looking into this problem. Will update once this problem is solved.

**Comment by lukeyeager** [comment]
Appears to be fixed by https://github.com/caffe2/caffe2/commit/14bda514f78abcc5a4dfe1d5d232f203dfd53a1b and https://github.com/caffe2/caffe2/commit/2f49ef3729abe009ddd458ddf613bd15f86a363d. Thanks!
