### ISSUE TITLE
Build with OpenBlas tries to link with cblas (and fails if you don't have one)

### ISSUE THREAD

**Issue by AlexanderEfremovArm** [facebookarchive/caffe2#763]
Hi,

I'm trying to build caffe2 (release v0.7.0) with OpenBlas support:

```
# Configure
cmake -D CMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} \
<...>
-D BLAS=OpenBLAS \
-D OpenBLAS_INCLUDE_DIR=/src/dependencies/include \
-D OpenBLAS_LIB=/src/dependencies/lib/libopenblas.so \
<...>
${SRC_PATH}
```
The build fails on the stage of shared lib libCaffe2_CPU.so creation because it tries to link with cblas.
```
<...>/bin/ld.bfd: cannot find -lcblas
collect2: error: ld returned 1 exit status
```
I don't have libcblas and I'm not sure why it is needed when I have provided OpenBlas implementation which has all the stuff.

Cblas  comes from here:
cmake/Dependencies.cmake:36
```
...
32: elseif(BLAS STREQUAL "OpenBLAS")
33:   find_package(OpenBLAS REQUIRED)
34:   include_directories(SYSTEM ${OpenBLAS_INCLUDE_DIR})
35:   list(APPEND Caffe2_DEPENDENCY_LIBS ${OpenBLAS_LIB})
36:   list(APPEND Caffe2_DEPENDENCY_LIBS cblas)
...
```
If I comment out this line, then the build will produce perfectly usable library for me.

By the way, caffe1 did not need cblas when using OpenBlas lib.

**Comment by smileForCode** [comment]
@AlexanderEfremovArm how to user libcaffe_cpu.so？

**Comment by xkszltl** [comment]
Confirmed this on CentOS 7.
ATLAS from base repo and OpenBLAS from epel repo do not come with libcblas.so
