### ISSUE TITLE
warning: statement is unreachable

### ISSUE THREAD

**Issue by QinZiwen** [facebookarchive/caffe2#764]
When I compile caffe2, some warning show : 
```
caffe2/core/operator_schema.h(277): warning: statement is unreachable
```
later, " cd build && sudo make install". In "/usr/local", there is no the folder of " binaries "

**Comment by lukeyeager** [comment]
:+1: for the annoying warnings. Would be nice to find a cross-platform way to avoid that warning.

For your second point, see this note: https://github.com/caffe2/caffe2/pull/640#discussion_r118301074. Maybe there's some documentation that needs to be updated?
