### ISSUE TITLE
More than 3 channels of input data

### ISSUE THREAD

**Issue by camel007** [facebookarchive/caffe2#771]
I find this function for input "ImageInput" 
> color	Number of color channels (1 or 3). Defaults to 1  

But my data have 7 channels.

**Comment by aaronmarkham** [comment]
That Op has several internal functions that don't really take color channels into account. You might be able to go ahead and use 7 but do a little patch here and there to get around the constraint to 1 or 3. As you're probably aware, you don't have to use that Op. You can [make your own custom op](https://caffe2.ai/docs/custom-operators.html) that takes seven!

Just curious... what's in the other channels?

**Comment by camel007** [comment]
Thanks for ur reply.
I am implementing some online chinese character recognition paper. They use path signature as input.
