### ISSUE TITLE
Problem reading database

### ISSUE THREAD

**Issue by mgp1994** [facebookarchive/caffe2#773]
Hello, I'm new here.

I am trying reading a lmdb database with this function:

def read_db_with_caffe2(db_file,bs,nombre):
    print(">>> Read database...")
    model = cnn.CNNModelHelper(order="NCHW", name=nombre)
    data, label = model.TensorProtosDBInput([], ["data", "label"],  batch_size=bs, db=db_file, db_type="lmdb")
    return data,label

Then, in main program:

........
arg_scope = {"order": "NCHW"}
train_model = model_helper.ModelHelper(name="prueba_train", arg_scope=arg_scope)
data,label=read_db_with_caffe2('/home/ubuntu/Prueba1/input/train_lmdb_1',256,"lmdbtrain")
.....
workspace.CreateNet(train_model.net, overwrite=True)
.......

Error is: 

RuntimeError: [enforce fail at operator.cc:26] blob != nullptr. op Conv: Encountered a non-existing input blob: data 

Could you help me?

Thank you

**Comment by aaronmarkham** [comment]
Were you able to run this script on its own?
https://github.com/caffe2/caffe2/blob/da75962a2e2d45bce80a989f52e4e18fae897b6e/caffe2/python/examples/lmdb_create_example.py

**Comment by mgp1994** [comment]
I tried to run the script. Therefore, when I run it with the same form, there is a error when you are creating the database. Then, I used another lmdb database and I reused the function to read de database. And, nothing.........

 Could you tell me about other similar scripts? A script which can create and read databases easily?

Sorry for my english level.

Thank you, @aaronmarkham.

**Comment by marcelogarcia94** [comment]
I have the same problem @mgp1994. If you know something, tell me please.

**Comment by slayton58** [comment]
In your `read_db_with_caffe2` method you create a new network, add the input to that, and then pass back references to blobs that the model created in the main program doesn't know anything about. Try modifying your code to:

```
def read_db_with_caffe2(model, db_file,bs,nombre):
    print(">>> Read database...")
    data, label = model.TensorProtosDBInput([], ["data", "label"], batch_size=bs, db=db_file, db_type="lmdb")
    return data, label

def main():
    arg_scope = {"order": "NCHW"}
    train_model = model_helper.ModelHelper(name="prueba_train", arg_scope=arg_scope)
    data,label=read_db_with_caffe2(train_model, '/home/ubuntu/Prueba1/input/train_lmdb_1',256,"lmdbtrain")
```

**Comment by aaronmarkham** [comment]
I think @slayton58 answered the question here, and it looks like a scope issue in your code. For more reference, if you run the [lmdb_create_example.py](https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/lmdb_create_example.py) it also has a read function that you can follow. Here's the example output:
```
$:~/c2m/caffe2/python/examples$ python lmdb_create_example.py --output_file test-lmdb
>>> Write database...
Inserted 0 rows
Inserted 16 rows
Inserted 32 rows
Inserted 48 rows
Inserted 64 rows
Inserted 80 rows
Inserted 96 rows
Inserted 112 rows
Checksum/write: 1743534
>>> Read database...
Checksum/read: 1743534
```
Also, we've just updated the [MNIST tutorial](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb) to use lmdb and it shows a similar pattern for reading.
