### ISSUE TITLE
You will find the Caffe2 binary， but it is empty after running build_windows.bat

### ISSUE THREAD

**Issue by danfouer** [facebookarchive/caffe2#775]
This time I got no error from running build_windows.bat

You will find the Caffe2 binary in $USER\Source\Repos (if that’s where you put the caffe2 source) \caffe2\build\caffe2\binaries\Release, 
however, it is empty

**Comment by mattm401** [comment]
I am having the same issue as @danfouer; were you ever able to  solve the problem?

**Comment by Yangqing** [comment]
Possibly due to Windows bug? See #1644 . I could not repro the problem on my local machine with VS2015 and VS2017 15.5, so I assume this is addressed.
