### ISSUE TITLE
Declaring an operator with multiple outputs

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#777]
I'm trying to create a MaxPoolWithIndex operator in Python, which should take 1 input blob then output a data tensor and a mask. How do I declare the two outputs? I've tried the following but get the errors shown below:

`pool1 = brew.max_pool_with_index(model, relu1_2, "pool1", "pool1_mask")`
TypeError: max_pool_with_index() got multiple values for keyword argument 'order'

`pool1 = brew.max_pool_with_index(model, relu1_2, ["pool1", "pool1_mask"])`
TypeError: can only concatenate list (not "unicode") to list

**Comment by asaadaldien** [comment]
Brew only returns the pooled value blob (see : caffe2/python/helpers/pooling.py:38)
The index will be the same name as the blob with _index suffix. For example :
`pool1 = brew.max_pool_with_index(model, relu1_2, "pool1")`
You will have pool1 and pool1_index.

**Comment by ShangxuanWu** [comment]
Hi, I met a similar issue. I want to use split layer, but I am not sure of the output layer names. How should I call it using brew()? Thanks!

**Comment by CarlosYeverino** [comment]
Hi @ShangxuanWu ,

did you know how to use the split layer?
