### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sebastiangonsal** [facebookarchive/caffe2#781]
I installed all dependences including `protobuf` dependencies. The compiler detected is `g++` and `protoc` is detected in `/usr/bin/protoc`. 

However, on doing `make` and at a progress of 91% i hit the following error:
````
undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
````

I tried to rename `/usr/bin/protoc` in the hope that caffe2 tries to compile its own `protobuf `(I saw it in the thirdparty I think) but it led to further errors.

Any hints anyone?

**Comment by pjh5** [comment]
Sorry this never got answered. I will now move this to #1980
