### ISSUE TITLE
Converting Caffe Python Layers to Caffe2

### ISSUE THREAD

**Issue by alex-jw-brooks** [facebookarchive/caffe2#792]
I have some layers that aren't addressed in the migration tutorial, but I have been able to implement operators to suit my needs for most of them. Unfortunately, I am at a bit of a loss with the Python layer.

In Caffe, my Python layer is the typical class + 4 methods. How can I address these 4 methods (setup, reshape, forward, backward) in a custom operator to convert my entire network? Is this even possible?

UPDATE: I converted the layer, although I'm not sure it done correctly (by creating custom operators in the translator). That being said, when I try to run the module, it blows up because my custom operators are no longer defined. Is there a way to permanently add these operators to the workspace through the Python API?

**Comment by Feynman27** [comment]
@abrooks9944 Were you able to get this to work permanently?

**Comment by RSly** [comment]
can you give some details how ro do it?

**Comment by alex-jw-brooks** [comment]
I was indeed able to get this working properly. Unfortunately, I no longer have access to the code I was developing, or a machine with Caffe/Caffe2. 

As far as I remember, this is what I did. My apologies if it is not helpful, but hopefully it will be.
1. Create a translate function for your layer and register it to the translator using the decorator.

2. Inside of that translate function, define another function. It actually doesn't appear to matter what is in the function body here, but I believe that I put what I wanted in the forward step for consistency (you will need to redefine the functionality later, it seem like this step is basically a placeholder, not the real definition).

3. Below the nested function definition, use the the CreatePythonOperator function (for the definition, see here: https://github.com/caffe2/caffe2/blob/master/caffe2/python/core.py) and assign the nested function object to it. Assuming your inputs/outputs are correct, you should be able to get your initializer/predictor files.

4. When you actually try to use the Caffe2 model, you need to redefine the custom operators and their functionality. You can do this in an identical manner to steps 2 and 3 (without the decorator of course). If I remember correctly, you want to create a function with the same name as the function object that you assigned to CreatePythonOperator in the translator, and assign it to CreatePythonOperator _again_. If it doesn't have the same name, it won't be able to find the definition when it opens the model (not sure why). The function object that is passed into CreatePythonOperator _here_ (after your model has already been translated) should be the one that determines the behavior.

I hope that this helps; sorry if parts of this process are wrong. The documentation is very weak and this was the only way I could figure out how to make the model run correctly.
