### ISSUE TITLE
AttributeError: 'OperatorDef' object has no attribute 'uuid'

### ISSUE THREAD

**Issue by kasiabozek** [facebookarchive/caffe2#796]
When calling:
`db_reader = model.CreateDB("dbreader", db=data_file, db_type="minidb")`

**Comment by Giszy** [comment]
@kasiabozek  You should update caffe2.proto and compile it.

**Comment by kasiabozek** [comment]
It works. There is some copying between the original and the installation folder that caused the previous version to be kept. Thank you.
