### ISSUE TITLE
Why don‘t you guys adopt the GPU implementation of  Eigen's Tensor'?

### ISSUE THREAD

**Issue by gangliao** [facebookarchive/caffe2#798]
I found you adopt `Eigen::Tensor` in CPU implementation of caffe2 [`XX.cc`].

 Why don't you adopt the GPU implementation of Eigen's Tensor?  Are there any potential weaknesses I am not aware?  On the flip side, when I go through TensorFlow, It seems that works pretty well under the GPU of that.

Thanks.

**Comment by Yangqing** [comment]
We actuallly have a few but in general many of our fast paths (like nnpack) is not using Eigen at the moment. A few implementations - like conv_op_eigen.cc - does use Eigen though. If you'd like to add Eigen as an optional backend engine, please feel free to send us PRs - that would be much appreciated!
