### ISSUE TITLE
accuracy alway be 1.0

### ISSUE THREAD

**Issue by chenriwei** [facebookarchive/caffe2#806]
I train a resnet50 with num_label = 2，but when trianing the accuracy alway be 1.0, use the same Dataset  training on caffe1.0 version  with googlenet v1, I can only get accuracy not more than 0.85.

what's the problem it may be ?

follow is some log

INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/100
INFO:resnet50_trainer:Finished iteration 1/1562 of epoch 0 (34.41 images/sec)
INFO:resnet50_trainer:Training loss: 0.693147480488, accuracy: 1.0
INFO:resnet50_trainer:Finished iteration 2/1562 of epoch 0 (477.39 images/sec)
INFO:resnet50_trainer:Training loss: 0.602652907372, accuracy: 1.0
INFO:resnet50_trainer:Finished iteration 3/1562 of epoch 0 (549.62 images/sec)
INFO:resnet50_trainer:Training loss: 0.495978534222, accuracy: 1.0
INFO:resnet50_trainer:Finished iteration 4/1562 of epoch 0 (574.50 images/sec)
INFO:resnet50_trainer:Training loss: 0.390794098377, accuracy: 1.0
INFO:resnet50_trainer:Finished iteration 5/1562 of epoch 0 (572.76 images/sec)
INFO:resnet50_trainer:Training loss: 0.298585027456, accuracy: 1.0
....

**Comment by neobarney** [comment]
I'm having the same pb. However, when running it from the multi gpu training tutorial, accuracy seems to be correct. Still inquiring what's the difference between the 2 codes

**Comment by chenriwei** [comment]
DUP with #810 , we find that all data and label blobs fetch from workspace is 0

**Comment by neobarney** [comment]
Ok, so just change use_caffe_datum in "brew.image_input" in resnet50_trainer.py to "False" if you're using input data in caffe2 format, and it will work !

**Comment by chenriwei** [comment]
thanks @neobarney , I thank you can send a pull request.
