### ISSUE TITLE
is there mobilenet in caffe2?

### ISSUE THREAD

**Issue by KeyKy** [facebookarchive/caffe2#812]
https://github.com/Zehaos/MobileNet I found that the cpu speed of mobilenet is about 50ms!!!

**Comment by lanzhzh** [comment]
+1

**Comment by yedideep** [comment]
has caffe1 ,but i find not caffe2

**Comment by tianyoul** [comment]
I translated the model given by shicai in https://github.com/shicai/MobileNet-Caffe using the caffe2 translator. It works well on my computer and mobile device.

https://drive.google.com/file/d/0B-q03jmMkN8lV21RZkFNYTJjeE0/view?usp=sharing

https://drive.google.com/file/d/0B-q03jmMkN8lZzNjcmVSUmdyTVE/view?usp=sharing

**Comment by austingg** [comment]
@tianyoul how about the speed?  if no custom depthwise conv op, the mobilenet seem not so fast when implemented by group method

**Comment by zvadaszi** [comment]
I can convert the model from here https://github.com/shicai/MobileNet-Caffe but gives me error when using it. If I change the batchnorm layers _not_ to be in place with their corresponding bottom convolution it works fine.
@tianyoul did you also had to do this change to work in caffe2?

**Comment by lhCheung1991** [comment]
Hi, 
I encountered the following error when I tried to run the  mobilenet model of Caffe2, exported from my server, 
on Android.

`08-11 09:17:57.012 14428-14498/facebook.f8demo E/F8DEMO: Couldn't parse net from data.
08-11 09:17:57.058 14428-14498/facebook.f8demo E/F8DEMO: done.
08-11 09:17:57.058 14428-14498/facebook.f8demo E/F8DEMO: Instantiating predictor...
08-11 09:17:58.000 14428-14498/facebook.f8demo A/native: [F given_tensor_fill_op.h:27] Check failed: output->size() == values_.size() output size: 2359296 given size: 1144986
08-11 09:17:58.000 14428-14498/facebook.f8demo A/native: terminating.
08-11 09:17:58.000 14428-14498/facebook.f8demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14498 (AsyncTask #1)`

I implement the depthwise convolution via group_conv.

Have you guys met this problem? Any suggestion will be appreciated. 

@zvadaszi @tianyoul

**Comment by zvadaszi** [comment]
[deploy.prototxt.txt](https://github.com/caffe2/caffe2/files/1217111/deploy.prototxt.txt)
@lhCheung1991 , find attached the deploy.prototxt that worked for me to convert the caffemodel from here https://github.com/shicai/MobileNet-Caffe
The only difference to shicai's mobilenet_deploy.prototxt is that I had to change all batchnorms not to be in place with the bottom convolutions, otherwise it did not work in Caffe2 for me.

Yes, group=num_input_channels should be used for depthwise convolutions.

**Comment by lhCheung1991** [comment]
Get. Thank you @zvadaszi.
I wrote the code to build the mobilenet with Caffe2 brew.group_conv(). It seems work correctly on my cloud server but sucks on Android for batchnorms... Once I removed the batchnorms, it will work.

**Comment by Anubhav7** [comment]
I have been trying various models in caffe2 and the speeds, across the board, are much poor than those achieved on caffe. For instance, if one tries different models at https://github.com/onnx/models , the timings are nowhere near what are reported in different papers. Could I be doing something wrong?

**Comment by yushanshan05** [comment]
@austingg  I have the same problem.If I use group convolution,not depthwise convolution,it is so slow. I found implement of group convolution using for loop. So  how to solve this problem in caffe2? Thanks!
