### ISSUE TITLE
what's the most suitable way to support multi-task leaning?

### ISSUE THREAD

**Issue by chenriwei** [facebookarchive/caffe2#821]
Hi, I want to using caffe2 to support multi-task leaning like face age and gender classification.
I look into the codes and found that the recommended way of `brew.image_input` only support 1d scare label? I know I can modify the `image_input` operator to support multi-d label, after that, using `Split` operator to split the label.

My Question is 

 **Is there any more straightforward way to support multi-task learning in caffe2?**

Thanks in advance.

**Comment by chenriwei** [comment]
ok, not one response, I had try this way and made it work.

**Comment by camel007** [comment]
Hi, @RiweiChen  I have the same issue
I want to generate multi-label database, can you share your solution with me? Thank you

**Comment by chenriwei** [comment]
@camel007 ，what I do is follow：
1、make LMDB datasets with multi-dim label, for my problem is age and gender;
2、modify the image_input operator, so that it 's output label wound contain multi-label
3、split the multi-label
