### ISSUE TITLE
Why the MNIST tutorial test accuracy is very low?

### ISSUE THREAD

**Issue by camel007** [facebookarchive/caffe2#822]
I install c2 in ubuntu 14.04, and run "caffe2/caffe2/python/tutorials/MNIST.ipynb"
Training process:
![download](https://user-images.githubusercontent.com/4254753/27272319-38c15b48-54fc-11e7-9046-f9e69295249e.png)
The test accuracy is very low.
looks like did not load trained model

**Comment by Devin0202** [comment]
#790 give you the workaround method.
#824 give you the root-cause.
I‘m just a carrier. ^_^

**Comment by camel007** [comment]
@DevinHiscene 
Thanks a lot!
