### ISSUE TITLE
How to update caffe2 changes?

### ISSUE THREAD

**Issue by demon450** [facebookarchive/caffe2#835]
I saw constantly upodates made on Caffe2, how do I update Caffe2 locally? Just pull? any command needed? 
Is there a uninstall command for Caffe2 in case something wrong happens that I can re-install?
Thanks

**Comment by aaronmarkham** [comment]
If you've just cloned Caffe2 like in the instructions, a `git pull` will get you updated, but you should still rebuild. 
To rebuild and install:
Go to /caffe2/build and do `sudo make -j8 install` where the 8 is the number of processors you have (optional to use the -j but it is faster).

To cleanup the old build and reinstall:
If you get some errors, you can try a clean rebuild. Note older versions of Caffe2 installed into /usr/local/caffe2 and also may have put some binaries in /usr/local/binaries. You may want to manually delete /usr/local/caffe2 before trying to do a clean rebuild and install. Then delete the build folder, /caffe2/build/. Sudo is likely required for this.
`sudo rm -rf /usr/local/caffe2`
From the source directory /caffe2/:
`sudo rm -rf build`

Then you can do a build like when you first built Caffe2. From the caffe2 source directory use: 
`make -j8` 
and if that compiles all the way to 100%, then 
`cd build && sudo make -j8 install`.
If that also gets to 100% you should be good to go!
