### ISSUE TITLE
Anaconda Install not detecting dependencies

### ISSUE THREAD

**Issue by jerrin92** [facebookarchive/caffe2#851]
I tried anaconda install caffe2 as per the official documentation. However, since glog, gflag, leveldb, cuda and cudnn were all installed with conda install they are not detected by cmake. But dependencies related to python such as protobuf is detected during cmake.

~~~~
--   USE_CUDA              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : OFF
--   USE_GFLAGS            : OFF
--   USE_LMDB              : OFF
--   USE_LEVELDB           : OFF
--   USE_OPENCV            : OFF
--   USE_FFMPEG            : 
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NNPACK            : OFF
--   USE_OPENMP            : ON
--   USE_REDIS             : OFF
~~~~

**Comment by aaronmarkham** [comment]
You need to still install system-level dependencies and not just Python dependencies. So if you're on Ubuntu, you'll want to follow:
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#required-dependencies

And for cuda and cudnn:
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#optional-gpu-support

It does seem like you're doubling up when you use both conda and apt-get to install the "same" package, but they're different levels of installation. Beware that as packages such as brew, pip, and conda get updated by their maintainers things like protobuf aren't necessarily the same version. 
conda install protobuf != pip install protobuf != brew install protobuf
