### ISSUE TITLE
compile error caffe2_GPU

### ISSUE THREAD

**Issue by kalfenxu** [facebookarchive/caffe2#875]
3>C:/path/git/caffe2\caffe2/operators/top_k_radix_selection.cuh(359): error : a value of type "caffe2::TIndex *" cannot be used to initialize an entity of type "long *"

**Comment by cuepi** [comment]
Same here:

[ 60%] Building NVCC (Device) object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_top_k.cu.o
/Users/cuepi/Documents/Devel/MacOSDev/AppSamples/Caffe2/caffe2/operators/top_k_radix_selection.cuh(359): error: a value of type "caffe2::TIndex *" cannot be used to initialize an entity of type "long *"
          detected during instantiation of "void caffe2::gatherTopK<T,Order,IndicesType>(const T *, int, int, int, T *, IndicesType *) [with T=float, Order=true, IndicesType=caffe2::TIndex]" 
/Users/cuepi/Documents/Devel/MacOSDev/AppSamples/Caffe2/caffe2/operators/top_k.cu(117): here

1 error detected in the compilation of "/var/folders/kz/zznwkd1n6_v_00zw9fbygqlh0000gn/T//tmpxft_00007e45_00000000-19_top_k.compute_61.cpp1.ii".
CMake Error at Caffe2_GPU_generated_top_k.cu.o.Release.cmake:278 (message):
  Error generating file
  /Users/cuepi/Documents/Devel/MacOSDev/AppSamples/Caffe2/build/caffe2/CMakeFiles/Caffe2_GPU.dir/operators/./Caffe2_GPU_generated_top_k.cu.o

make[3]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/operators/Caffe2_GPU_generated_top_k.cu.o] Error 1
make[2]: *** [caffe2/CMakeFiles/Caffe2_GPU.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**********************************************************

-- ******** Summary ********
-- General:
--   Git version           : 
--   System                : Darwin
--   C++ compiler          : /Library/Developer/CommandLineTools/usr/bin/c++
--   C++ compiler version  : 8.0.0.8000042
--   Protobuf compiler     : /usr/local/bin/protoc
--   CXX flags             :  -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY;CAFFE2_UNIQUE_LONG_TYPEMETA;CAFFE2_NO_BUILTIN_CPU_SUPPORTS
-- 
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /Users/cuepi/anaconda/lib/libpython2.7.dylib
--   BUILD_TEST            : ON
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--   USE_CNMEM             : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--   USE_GFLAGS            : ON
--   USE_LMDB              : ON
--     LMDB version        : 0.9.21
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.20
--     Snappy version      : 1.1.4
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_FFMPEG            : 
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : ON
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NNPACK            : ON
--   USE_OPENMP            : OFF
--   USE_REDIS             : OFF
--   USE_GLOO              : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cuepi/Documents/Devel/MacOSDev/AppSamples/Caffe2/build

**Comment by matzeox** [comment]
I have exaclty the same problem ;(

**Comment by cuepi** [comment]
I solved compilation problem but I am unsure if it broke anything else. At least I can move on.

File: caffe2/operators/top_k_radix_selection.cuh
Line: 359

Change

`
long* indicesSliceStart = &indicesPtr[slice * outputSliceSize];
`

for 

`
IndicesType* indicesSliceStart = &indicesPtr[slice * outputSliceSize];
`

**Comment by davinwang** [comment]
@kalfenxu
I encounter this issue too,and it has been fixed in #985 .
@cuepi
You may fire a pull request if you can solve it.

**Comment by pietern** [comment]
Has been fixed for a while, closing.
