### ISSUE TITLE
How to run Caffe2 in distributed setting with multiple machines?

### ISSUE THREAD

**Issue by sparkwoo** [facebookarchive/caffe2#895]
The document about distributed training (https://caffe2.ai/docs/SynchronousSGD.html) looks only talk about how to run it on multiple GPUs in the single machine. And also, to run Caffe2 on multiple machines, can I not use MPI?

**Comment by asaadaldien** [comment]
You can run multi machine distributed training by passing a rendezvous object to ParallelizeGPU method. See resnet50 example (caffe2/python/examples/resnet50_trainer.py) 
You don't have to use MPI caffe2 will use GLOO if you set `engine='GLOO'` in the rendezvous.

**Comment by sparkwoo** [comment]
Thank you very much. I browsed resnet50 example. Looks like I need to prepare a file describing the machine list taking part in the data parallel computation. However,  seems there is no example about the concrete format of the machine list file.

**Comment by asaadaldien** [comment]
No you just need run the trainer on each machine independently with a unique (shard_id). and number of machines (num_shards).
Those machines are going to find each other. to do this you need redis server or a shared file system (NFS, GlusterFS,...etc) where you  provide a path to a shared directory (file_store_path in the resnet50 example).

**Comment by sparkwoo** [comment]
I see. Got it. Thanks a lot.

**Comment by leye7755** [comment]
@asaadaldien @sparkwoo how can i build the enviroment for distributed train. now i use docker  and report that cannot create operator of type 'RedisStoreHandleCreate' for multi-machine.

**Comment by thyeros** [comment]
@asaadaldien 

I like to use the "native" MPI implementation in caffe2, not GLOO. However, it looks such MPI implementation is not fully complete? Is GLOO the only way to do distributed training?

If there is a way to exercise the caffe2 MPI (not GLOO), can you provide me an example on how to properly run?

**Comment by bkovalev** [comment]
+1

**Comment by thatwist** [comment]
@leye7755 have you solved that issue with Redis-related error?

**Comment by manofmountain** [comment]
@asaadaldien @thyeros 

i wonder if your above question have got a answer and i'm also interested on knowing if there is a way to exercise caffe2 MPI without using GLOO.
