### ISSUE TITLE
About speed of distributed learning with resnet50_trainer.py

### ISSUE THREAD

**Issue by ing907** [facebookarchive/caffe2#902]
Hello. I read a paper about caffe2 distributed learning a few weeks ago.
(Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour)

I tried to run distributed, multi GPU leaning through the resnet50_trainer.py (with 2~3 computers).
But it doesn't faster than single machine, multi GPU learning.

So I just wonder whether resnet50_trainer.py uses exactly same way that the paper "Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour" used or not.

If yes, I would like to know is there a something wrong such as missed flags or wrong installation that reduce learning speed and what is it.

**Comment by wesolwsk** [comment]
Hello, could you post your hardware specifications and the input parameters you used to run the trainer?

**Comment by ing907** [comment]
I don't know the exact detailed hardware specifications since some reason but as I know, it is fast enough.
I run with two machines with 4 GTX 1080Ti for each machine.
Training data was CIFAR-10 and single machine 8 GPUs learning processed around (1200images/sec) but 2 machine distributed learning, which has 4 GPUs for each machine, processed around (130images/sec)


**input parameters :** 

(1st machine)
resnet50_trainer.py --train_data /PATH/OF/TRAINING/DATA --gpus 0,1,2,3 --batch_size 128 --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2 --shard_id 0 --run_id 1234 --redis_host REDIS.SERVER.IP.ADDRESS

(2nd machine)
resnet50_trainer.py --train_data** /PATH/OF/TRAINING/DATA --gpus 0,1,2,3 --batch_size 128 --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2 --shard_id 1 --run_id 1234 --redis_host REDIS.SERVER.IP.ADDRESS

**Comment by wesolwsk** [comment]
So, with a single 8 GPU machine you were getting 1200 img/s, but with two 4 GPU machines you get 130 img/s (9x worse)? What is the performance running on a single 4 GPU node.

Can you run iperf3 between the two nodes and report the observed bandwidth? Also, default concurrency settings were recently updated, so you may want to pull the latest changes and retry.

**Comment by leye7755** [comment]
@ing907  hello, I want to  use caffe2 distribute train about the example for resnet50_trainer.py,but could run for the reason that  Operator 'RedusStoreHandlerCreate' seems not registered. thank you so much for you help.

**Comment by ing907** [comment]
I should do something in this weekend and then try it again.
I will let you know after all job is finished.  Thank you for your attention.

**Comment by leye7755** [comment]
@ing907 hello,can you leave you email for  contacting, I have got some problem in  distributed learning,and you should have been met. thank you so much.

**Comment by ing907** [comment]
@leye7755 ing907@naver.com

**Comment by renganxu** [comment]
@ing907 @leye7755 Have you figured out the reason of the slow performance? I also observed similar behavior. I got ~700 images/sec within 1 node with has 4 GPUs, but with 2 nodes, the speed is only 250 images/sec per node. I noticed all the data went through Ethernet interface although my nodes are connected with 100Gbps Infiniband. I tried to compile Caffe2 with -DUSE_IBVERBS_DEFAULT=ON, but still no success.

**Comment by ing907** [comment]
@hfutxrg @wesolwsk I tested resnet50_trainer with 2 machines connected with 100Gbps Infiniband. but there was still slow performance. Could you guys solve this problem or does it not use the same method that paper used?

**Comment by llhe** [comment]
Is the problem identified or solved?

**Comment by ing907** [comment]
@llhe Unfortunately, No.

**Comment by llhe** [comment]
I made a test which which can achieve 7+ speedup compared to 1 GPU(M40), here is the result:
```
1 host, 1 gpu     (batch size = 32):       91 images/sec
1 host, 4 gpu     (batch size = 128):     340 images/sec
2 host, 4*2 gpu  (batch size = 128*2):   330*2 images/sec
```
Plain 10Gbps eithernet is used and the occupied bandwidth is around 2Gbps.

The binary we use is compiled with redis enabled from souce with commit: b6f29a96a6c7978b00f2c2e09f4bd67e357dee2e

**Comment by FredericMao** [comment]
@ing907 @hfutxrg Seems that Caffe2 chooses the network adapter based on the output of Linux's "hostname" command, which could be the management network in a Infiniband-based cluster environment. [https://github.com/facebookincubator/gloo/issues/70](url) added a new function that will allow you to choose network interface. I modified caffe2/caffe2/contrib/gloo/common_world_ops_gpu.cc and common_world_ops.cc by adding "attr.iface="ib0";" after "::gloo::transport::tcp::attr attr;" This will allow Caffe2 to use IPoIB for the communication. (I do a ifconfig to figure out the name of the IB interface I want to use).

**Comment by renganxu** [comment]
@powerreactor @ing907 I have already been able to scale Caffe2 across 4 nodes. With 16 GPUs across 4 nodes, I got 12.5x speedup which is pretty good. But that was still using IPoIB instead of IBverbs library. There is still bug in Caffe2 of using IBverbs library https://github.com/caffe2/caffe2/issues/616. It would be better if that bug is fixed.

**Comment by pietern** [comment]
Using IB and GPUDirect is possible without having to modify the Gloo bindings since last month.

Also see [my comment on #616](https://github.com/caffe2/caffe2/issues/616#issuecomment-337631430).

If there is a more specific issue still pending, please feel free to open a new issue.
