### ISSUE TITLE
ConvTranspose & conv_transpose require square kernels

### ISSUE THREAD

**Issue by colincsl** [facebookarchive/caffe2#908]
I'm trying to use conv_transpose (or ConvTranspose) for 1D (time-series) data. Both functions, however, only accept integer values for the kernel size. This integer is used for both the kernel height and width.

For example, with normal convolutions I use:
`layer = brew.conv_nd(model, layer, name, dim_in=in_dim, dim_out=n_filters, kernel=[1,length])`

I would like to apply transposed convolutions like this:
`layer = conv_transpose(model, layer, name, dim_in=dim_in, dim_out=dim_out, kernel=[1,length])`

I tried looking through the code but couldn't figure out how to change this. I tried modifying conv_tranpose in `caffe2/python/helpers/conv.py` by changing 

```
    return model.net.ConvTranspose(
        [blob_in, weight, bias],
        blob_out,
        kernel=kernel,
        order=order,
        **kwargs
```

to 

```
    return model.net.ConvTranspose(
        [blob_in, weight, bias],
        blob_out,
        kernels=[kernel_h, kernel_w],
        order=order,
        **kwargs
```
However this results in the following error:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-142-135d0377a287> in <module>()
     34 duration = 50
     35 workspace.RunNetOnce(model.param_init_net)
---> 36 workspace.CreateNet(model.net, overwrite=True)

/Users/clea/anaconda/envs/py2/lib/python2.7/site-packages/caffe2/python/workspace.pyc in CreateNet(net, overwrite, input_blobs)
    145     return C.create_net(StringifyProto(net), overwrite)
    146 
--> 147 
    148 def RunOperatorOnce(operator):
    149     return C.run_operator_once(StringifyProto(operator))

RuntimeError: [enforce fail at conv_transpose_unpool_op_base.h:51] kernel_h_ > 0.  
```

Any ideas?

**Comment by colincsl** [comment]
I posed this elsewhere and was suggested to explicitly set kernel_h and kernel_w in the conv_tranpose function in ``caffe2/python/helpers/conv.py``:

model.net.ConvTranspose(
        [blob_in, weight, bias],
        blob_out,
        kernel_h=kernel_h, 
        kernel_w=kernel_w,
        order=order,
        **kwargs
)

This worked for me.

**Comment by XiongChengxin** [comment]
Hi@colincsl , did you define kernel_h and kernel_w?

**Comment by XiongChengxin** [comment]
Hi@colincsl , do you have any suggestions if I want to do 3D convtranspose? Any help would be appreciated.

**Comment by XiongChengxin** [comment]
I mean, how should I modify the shape of weight and bias and so on.

**Comment by colincsl** [comment]
Hi Xiong,

Sorry for the delay. Unfortunately I haven't touched this in a year and don't think I can do much to help. 

Best,
Colin
