### ISSUE TITLE
problem of distribute train for example

### ISSUE THREAD

**Issue by leye7755** [facebookarchive/caffe2#914]
I  used docker (docker pull caffe2ai/caffe2:c2.tutorial.0.7.1) .
When running resnet50_trainer.py . it report me that cannot create operator of type 'RedisStoreHandleCreate' for multi-machine.
Therefore.And I found that CMakeList.txt ( option(USE_REDIS "Use Redis" OFF) ). I change it for ON. But it report that it have not found Hiredis and still set Redis OFF. but i have build hiredis. I dont know whether is this problem or not? thank you for help.
@talk2ap001 @sergey-serebryakov @Yangqing

**Comment by pietern** [comment]
You can specify the path to your hiredis build using the `HIREDIS_ROOT_DIR` CMake variable.

Run CMake with `-DHIREDIS_ROOT_DIR=<path/to/hiredis>` and then try rebuilding.

**Comment by Luo-Liang** [comment]
I have the same problem.
I got this when i try -DHIREDIS_ROOT_DIR
CMake Warning:
  Manually-specified variables were not used by the project:

    HIREDIS_ROOT_DIR
