### ISSUE TITLE
error with redis when distributed training on multiple nodes

### ISSUE THREAD

**Issue by renganxu** [facebookarchive/caffe2#918]
I try to use resnet_50_trainer.py example to train on 2 nodes. The commands are as follows:
on node 0: 
`python resnet50_trainer.py --train_data /database/caffe/ilsvrc12_train_lmdb/ --test_data /database/caffe/ilsvrc12_val_lmdb/ --gpus 0,1,2,3 --batch_size 256 --epoch_size 1280000 --num_epochs 1 --num_shards 2 --shard_id 0 --run_id 1234 --redis_host 10.149.0.9`

on node 1:
`python resnet50_trainer.py --train_data /database/caffe/ilsvrc12_train_lmdb/ --test_data /database/caffe/ilsvrc12_val_lmdb/ --gpus 0,1,2,3 --batch_size 256 --epoch_size 1280000 --num_epochs 1 --num_shards 2 --shard_id 1 --run_id 1234 --redis_host 10.149.0.11`

But the execution has the following error on node 0:
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 1280000
Traceback (most recent call last):
  File "resnet50_trainer.py", line 462, in <module>
    main()
  File "resnet50_trainer.py", line 458, in main
    Train(args)
  File "resnet50_trainer.py", line 236, in Train
    prefix=args.run_id,
  File "/cm/shared/apps/caffe2/build/caffe2/python/workspace.py", line 153, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at redis_store_handler.cc:22] redis_->err == 0. 1 vs 0. **Connection refused Error from operator**:
output: "store_handler" name: "" type: "RedisStoreHandlerCreate" arg { name: "host" s: "10.149.0.9" } arg { name: "prefix" s: "1234" } arg { name: "port" i: 6379 }

node 1 has the same error, just with different host ip address.

Here it has connection refused error, but these two nodes can ssh without password. Is there anything wrong with the command or is this a bug in Caffe2?

**Comment by leye7755** [comment]
hello.did you solve this problem?

**Comment by wesolwsk** [comment]
The --redis_host value on node 0 and node 1 should be the same. Please retry using the same redis host/port on both nodes.

**Comment by renganxu** [comment]
@wesolwsk @leye7755 Yes I used the same redis server ip and port on both node 0 and node 1, but it still has connection refused error. Since I was using RHEL OS, now I am trying to use Ubuntu to see whether it works.

**Comment by wesolwsk** [comment]
@hfutxrg try starting redis-server with --protected-mode no

**Comment by renganxu** [comment]
@wesolwsk I have already did that. 
I change the following fields in the redis.conf:
`bind 10.149.0.12`
`protected-mode no`
`daemonize yes`

Here the bind IP is the redis server IP which is node 0. node 1 is the client. Then I started the server:
`redis-server redis.conf`

On the client side, if I execute:
`redis-cli -h 10.149.0.12 -p 6379`
`> ping`
`pong`

It means they can be connected. 

But if run gloo benchmark with the commands:
server: 
`./benchmark --size 2 --rank 0 --redis-host 10.149.0.12 --redis-port 6379 --prefix 1300 --transport ibverbs --elements -1 allreduce_ring_chunk`
client:
`./benchmark --size 2 --rank 1 --redis-host 10.149.0.12 --redis-port 6379 --prefix 1300 --transport ibverbs --elements -1 allreduce_ring_chunk`

Then it has the above error. But it's working correctly if "--transport **tcp**" is used.

**Comment by pietern** [comment]
@hfutxrg What kind of error did you see when using `--transport ibverbs`?

We recently merged an ibverbs related bugfix to Gloo. Could you try again with the latest Gloo version?

**Comment by renganxu** [comment]
Hi @pietern, I tried the latest gloo library and it works with that benchmark.

Caffe2 works well and scales well on multiple nodes if in each node all GPUs have Peer-to-Peer (P2P) accesses. However, if not all GPUs have P2P accesses, then caffe2/gloo will have the following error:
 
`` terminate called after throwing an instance of 'gloo::EnforceNotMet' 
 44   what():  [enforce fail at /cm/shared/scratch/rengan/caffe2/third_party/gloo/gloo/cuda_collectives_device.h:81] 1 == canAccessPeer. 1     vs 0. GPU 0 does not have peer access to GPU 3 ``

So why gloo does not work on multiple nodes if in each node not all GPUs have P2P accesses? Many servers have 4 GPUs in each node, where 2 GPUs have the same PCIe root but not 4 GPUs have the same PCIe root. To make it more explicit, Caffe2/gloo works on the following configuration B but not on configuration G.

![config_g](https://user-images.githubusercontent.com/3160803/29099075-888e67b8-7c68-11e7-9d35-88399f3b7d64.png ) 
![config_b](https://user-images.githubusercontent.com/3160803/29099080-8ea678ac-7c68-11e7-9db7-851400c86dd0.png)

**Comment by pietern** [comment]
@hfutxrg I missed the update. I'll prioritize this and fix it in Gloo.

**Comment by pietern** [comment]
This is solved if you use NCCL for intra-node collectives.

The open issue in Gloo for the p2p access problem is facebookincubator/gloo#64

Closing this issue.
