### ISSUE TITLE
Why distributed train must use at least one GPU?

### ISSUE THREAD

**Issue by leye7755** [facebookarchive/caffe2#936]
By the way , have anyone know the implementation of each machine find other machine by gloo.
Many thanks for your help.
@pietern @zpao @ezyang @thinxer @tomdz

**Comment by pietern** [comment]
Machines can find each other by using the same "run ID" (you can specify this as argument to `resnet50_trainer.py`, see its source code to see how the argument is passed to the relevant operators). Then that run ID is used to scope variables in a shared key/value space. This shared space can either be a shared filesystem (e.g. NFS), or a shared Redis key/value server. Every process writes keys with predefined names to this store and waits for other processes to do the same. Once every process has started and finds all of its peers are available as well, it sets up TCP connections to its peers.

Also see https://github.com/facebookincubator/gloo/blob/master/docs/rendezvous.md for more info.
