### ISSUE TITLE
Unable to make Caffe2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by kushagraagrawal** [facebookarchive/caffe2#952]
After cloning from github and installing the dependencies. When I run make the following error shows - 
CMakeFiles/make_image_db.dir/make_image_db.cc.o: In function `caffe2::ConvertImageDataset(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
make_image_db.cc:(.text+0xcbc): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
caffe2/binaries/CMakeFiles/make_image_db.dir/build.make:110: recipe for target 'caffe2/binaries/binaries/make_image_db' failed
make[3]: *** [caffe2/binaries/binaries/make_image_db] Error 1
make[3]: Leaving directory '/home/skywalker/caffe2/build'
CMakeFiles/Makefile2:3118: recipe for target 'caffe2/binaries/CMakeFiles/make_image_db.dir/all' failed
make[2]: *** [caffe2/binaries/CMakeFiles/make_image_db.dir/all] Error 2
make[2]: Leaving directory '/home/skywalker/caffe2/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/skywalker/caffe2/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

Please help

**Comment by ghost** [comment]
Hi kushagraagrawal, 

I built it with no issues, are you building this in a docker container, or just bare metal on Ubuntu 16.04?

**Comment by kushagraagrawal** [comment]
I was building it from source

**Comment by deepali-c** [comment]
Yes, even I could it without any issues. Are you using code from the `master` branch? If so could you please try with the latest release tag?

**Comment by slayton58** [comment]
Somethings wrong with your opencv dependency: `undefined reference to cv::imread`

**Comment by Yangqing** [comment]
This is probably due to the fact that you are using a newer version of gcc and linking with an older version of library. Try compile with additional flag -D_GLIBCXX_USE_CXX11_ABI=0 and see if it fixes your issue. For more details, see here:

https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by pjh5** [comment]
This will now be tracked in #1980

**Comment by Tshzzz** [comment]
Have you ever solved this problem? I meet the problem too.
