### ISSUE TITLE
RuntimeError: [enforce fail at redis_store_handler.cc:44] reply->type == REDIS_REPLY_INTEGER. 6 vs 3

### ISSUE THREAD

**Issue by githubgsq** [facebookarchive/caffe2#969]
I'm running distributed version of caffe2 example:resnet50_trainer.py.
Right now, I tested an instance on 2 nodes with mpirun
and the command is: 
mpirun -n 1 --host 192.126.232.56  python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/  --num_shards=2 --shard_id=0 --db_type lmdb --gpus=0,1 --batch_size 32 --epoch_size 6400  --num_epochs 1 --redis_host="192.126.232.53"  --redis_port=6379 --run_id=01000111 : -n 1 --host 192.126.232.53  python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/  --num_shards=2 --shard_id=0 --db_type lmdb --gpus=0,1 --batch_size 32 --epoch_size 6400  --num_epochs 1 --redis_host="192.126.232.53"  --redis_port=6379 --run_id=01001000

and then error occured:
RuntimeError: [enforce fail at redis_store_handler.cc:44] reply->type == REDIS_REPLY_INTEGER. 6 vs 3 Error from operator:
input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

Is error correlated with redis and gloo?
Can anyone help me analyze this problem please?
I have installed redis on host 192.126.232.53 and used default redis_port 6379. Just a single redis instance, no cluster. Thanks!

**Comment by githubgsq** [comment]
Issue above has been addressed by altering redis config file.
I found similar problems accross https://github.com/facebookincubator/gloo/issues/21
and modified redis.config as follows:
bind redis_server_IP_Addr
port 6379
pidfile /var/run/redis_6379.pid
daemonize yes

But another problem arised:
E0727 00:16:14.436970 28789 common_world_ops.h:75] Caught store handler timeout exception: [/home/caffe2Env/caffe2/caffe2/distributed/redis_store_handler.cc:110] Wait timeout for name(s): allreduce_0_cw_op/1
E0727 00:16:14.443244 28789 net.cc:143] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 4 } engine: "GLOO"
E0727 00:16:14.443269 28789 workspace.cc:217] Error when running network resnet50_init

all hosts are IP addr, I have no idea how to improve the situation.
@pietern hi, pietern, do you have any advice please?
btw, "/home/caffe2Env/caffe2/caffe2/distributed/" is the remote machine dir

**Comment by Yangqing** [comment]
@pietern

**Comment by githubgsq** [comment]
I tried nfs and run the command below, similar errors still

mpirun -n 1 --host 10.102.37.15 python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/ --num_shards=2 --shard_id=0 --db_type lmdb --gpus=4,5,6,7 --batch_size 32 --epoch_size 6400 --num_epochs 1  --file_store_path=/home/nfscache/resnet50_rendezvous --run_id=00001100 : -n 1 --host 10.102.37.16 python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/ --num_shards=2 --shard_id=0 --db_type lmdb --gpus=4,5,6,7 --batch_size 32 --epoch_size 6400 --num_epochs 1 --file_store_path=/home/nfscache/resnet50_rendezvous --run_id=00001101

error info:
E0727 13:21:33.335722  3331 common_world_ops.h:75] Caught store handler timeout exception: [/home/caffe2Env/caffe2/caffe2/distributed/file_store_handler.cc:132] Wait timeout for name(s): allreduce_0_cw_op/1
E0727 13:21:33.341861  3331 net.cc:143] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 4 } engine: "GLOO"
"/home/caffe2Env/caffe2/caffe2/distributed/" is the remote machine directory on which caffe2 was compiled.

**Comment by githubgsq** [comment]
I tried nfs and run the command below, similar errors still

mpirun -n 1 --host 192.126.232.56 python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/ --num_shards=2 --shard_id=0 --db_type lmdb --gpus=0,1 --batch_size 32 --epoch_size 6400 --num_epochs 1 --file_store_path=/home/nfscache/resnet50_rendezvous --run_id=00001100 : -n 1 --host 192.126.232.53  python /home/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/projects/practice/resnet/imagenet_cars_boats_train/ --num_shards=2 --shard_id=0 --db_type lmdb --gpus=0,1 --batch_size 32 --epoch_size 6400 --num_epochs 1 --file_store_path=/home/nfscache/resnet50_rendezvous --run_id=00001101

error info:
E0727 13:21:33.335722 3331 common_world_ops.h:75] Caught store handler timeout exception: [/home/caffe2Env/caffe2/caffe2/distributed/file_store_handler.cc:132] Wait timeout for name(s): allreduce_0_cw_op/1
E0727 13:21:33.341861 3331 net.cc:143] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 4 } engine: "GLOO"
"/home/caffe2Env/caffe2/caffe2/distributed/" is the remote machine directory on which caffe2 was compiled.

**Comment by githubgsq** [comment]
I attempted to modify the timeout value in file /home/caffe2Env/caffe2/caffe2/distributed/file_store_handler.cc,
![image](https://user-images.githubusercontent.com/23164715/28655633-bd2d8780-72cf-11e7-8428-460ef8ec31ee.png)
with regret, it didn't work.
then, the bottleneck should be allreduce_0_cw_op.

**Comment by githubgsq** [comment]
I attempted to modify the timeout value in file /home/caffe2Env/caffe2/caffe2/distributed/file_store_handler.cc,
![image](https://user-images.githubusercontent.com/23164715/28656273-9449d0ea-72d3-11e7-826e-3670f16e4256.png)
with regret, it didn't work.
then, the bottleneck should be allreduce_0_cw_op.
“allreduce_0_cw_op” was searched but no result
grep -r "allreduce_0_cw_op" /home/caffe2/
grep -r "allreduce_0_cw_op" /home/openmpi
Anyone know how "allreduce_0_cw_op" work please?

**Comment by githubgsq** [comment]
hi, I copied runnable caffe2 to another machine instead of the one on which caffe2 was compiled, and nfs version run successfully!!  unbelievable!
Maybe some dependencies were needed before~ 
no timeout value changed, I didn't know, it just worked......
this share may inspire others who met the similar problems

**Comment by pietern** [comment]
@githubgsq I think some of the issues mentioned here are similar as the ones in #984. Closing.
