### ISSUE TITLE
Compile error 'this file was generated by an older version of protoc' on Win10

### ISSUE THREAD

**Issue by davinwang** [facebookarchive/caffe2#978]
I'm compiling caffe2 with Win10 + VS2015 x64 + CPU mode + Anaconda.

I encounter following issue on both master and v0.8.0 branch. I retried by deleting build and build_host_protoc folder, but it recurs. Any help is appreciated, thanks.

`“C:\Users\Davin\Documents\SAAS_NG\caffe2\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caffe2\Caffe2_CPU.vcxproj”(默认目标)
 (3) ->
“C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caffe2\proto\Caffe2_PROTO.vcxpro
j”(默认目标) (4) ->
(ClCompile 目标) ->
  C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caffe2/proto/caffe2.pb.h(17): f
atal error C1189: #error:  This file was generated by an older version of proto
c which is (compiling source file C:\Users\Davin\Documents\SAAS_NG\caffe2\build
\caffe2\proto\caffe2.pb.cc) [C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caff
e2\proto\Caffe2_PROTO.vcxproj]
  C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caffe2/proto/hsm.pb.h(17): fata
l error C1189: #error:  This file was generated by an older version of protoc w
hich is (compiling source file C:\Users\Davin\Documents\SAAS_NG\caffe2\build\ca
ffe2\proto\hsm.pb.cc) [C:\Users\Davin\Documents\SAAS_NG\caffe2\build\caffe2\pro
to\Caffe2_PROTO.vcxproj]`

**Comment by ezineo** [comment]
Delete `protoc.exe` in your PATH and delete `C:\Users\Davin\Documents\SAAS_NG\caffe2\build`, then rebuild.

**Comment by davinwang** [comment]
@ezineo  thanks but it doesn't work. I noticed they are under `caffe` subfolder not `caffe2` subfolder, is there way to get around these files? I don't need caffe migration at this time.

**Comment by ezineo** [comment]
Maybe it's an anaconda's issue, you could run in cmd:
```bash
conda remove protobuf
```

**Comment by davinwang** [comment]
@ezineo I'm pretty sure I remove the protobuf 3.2.0 before rebuild... it doesn't work. thanks anyway

**Comment by davinwang** [comment]
@ezineo Your suggestion enlighten me and I finally resolved this issue.
`conda remove protobuf` is not enough, I still found a copy of protoc.exe under `C:\ProgramData\Anaconda2\Library\bin`. So I manually replaced it and those header files with the one under `caffe2\build_host_protoc`
