### ISSUE TITLE
caffe2 for android

### ISSUE THREAD

**Issue by rhythm9229** [facebookarchive/caffe2#98]
Are there plans for porting caffe2 for android? Will caffe2Go be opensourced soon?

**Comment by Yangqing** [comment]
Right now you can use cmake to build an Android .so file that you can then import into an Android project. We are updating the scripts to make it easier, but the command would look something like this (you'll need to adjust paths):

  cmake .. -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake -DANDROID_NDK=/opt/android_ndk/android-ndk-r12b/ -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_TEST=OFF -DUSE_LMDB=OFF -DUSE_LEVELDB=OFF -DBUILD_PYTHON=OFF -DPROTOBUF_PROTOC_EXECUTABLE=protoc -DCMAKE_VERBOSE_MAKEFILE=1 -DUSE_MPI=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS_RELEASE=-s

**Comment by rhythm9229** [comment]
thanks Yangqing :)
