### ISSUE TITLE
Warning MaxPool being not recognized byModelHelper

### ISSUE THREAD

**Issue by knipping** [facebookarchive/caffe2#981]
Each time I build a max pool operator  I get a runtime warning `WARNING:root:You are creating an op that the ModelHelper does not recognize: MaxPool.`. 

In spite of this message  the max pool operator is working perfectly well. (I only tested it for applying the network on inputs so far, no training phase.) So the message is no big deal, just a bit annoying.

Example excerpt from code causing the message:
 ```
mhelper = model_helper.ModelHelper(name=NAME)
....
mhelper.MaxPool(in_name, layer_name, kernels=[2,2], strides=strides, pads=pads)
```

**Comment by slayton58** [comment]
You should be using the `brew` interface for adding operators: `brew.max_pool(model, ...)` is what you need

**Comment by ShangxuanWu** [comment]
Thanks! @slayton58

**Comment by knipping** [comment]
Thanks for your feedback, slayton58. 

As far as I understood the brew-interface just offers an alternative way to build the network. So far, I did all with the mhelper calls and all operators work fine so far. I just get the warning output which cannot be true as the max pool is added to the layer and operated fine. So far I prefer to stick to the mhelper calls as I do not want to change a functioning setup.

**Comment by slayton58** [comment]
The warning isn't false - `ModelHelper` has (or at least used to have) a list of operators that it knew about, and knew how to handle, back prior to the great `brew` refactoring.

All it's saying is "I don't recognize a specific way of dealing with this operator", it doesn't mean the op doesn't exist, it doesn't mean there's an error, it doesn't mean it isn't added to the net.

**Comment by knipping** [comment]
I see, thanks for the explanation. 

Personally I still think the message is a bit misleading.  Anyway, as everything works fine, I will just ignore it.

**Comment by jwatte** [comment]
Note that some of the tutorials still use model_helper rather than brew (for example, multi-GPU training)
