### ISSUE TITLE
Caught gloo IO exception: [/home/gaosiqi/caffe2Env/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:528] connect [192.126.232.53]:896: Connection refused

### ISSUE THREAD

**Issue by githubgsq** [facebookarchive/caffe2#984]
When I run multi-machine caffe2 example resnet50_trainer.py, 
mpirun --host 192.126.232.53,192.126.232.56 -npernode 1  python /home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/gaosiqi/projects/practice/resnet/imagenet_cars_boats_train/ --num_shards=2 --db_type lmdb --gpus=0,1 --batch_size 32 --epoch_size 6400 --num_epochs 1  --file_store_path=/home/nfscache/gaosiqi/resnet50_rendezvous
errors occured:

E0728 14:21:02.400169  1573 common_world_ops.h:87] Caught gloo IO exception: [/home/gaosiqi/caffe2Env/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:528] connect [192.126.232.53]:896: Connection refused
E0728 14:21:02.405755  1573 net.cc:143] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 4 } engine: "GLOO"
E0728 14:21:02.405782  1573 workspace.cc:217] Error when running network resnet50_init
Traceback for operator 1069 in network resnet50_init
/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/data_parallel_model.py:998
/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/data_parallel_model.py:1049
/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/data_parallel_model.py:1062
/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/data_parallel_model.py:959
/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/data_parallel_model.py:237
/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:312
/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:461
/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:465
Traceback (most recent call last):
  File "/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 465, in <module>
    main()
  File "/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 461, in main
    Train(args)
  File "/home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 353, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/workspace.py", line 183, in RunNetOnce
    StringifyProto(net),
  File "/home/gaosiqi/caffe2Env/caffe2/build/caffe2/python/workspace.py", line 166, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:859] gWorkspace->RunNetOnce(def).
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

I only run the resnet50-trainer example successfully once before, error above occured when run more times.
@pietern have you ever met such problem?
   how gloo influenced?  caffe2 is the latest version.
   mpirun process only exists on local machine and remote machine has no mpirun instance.
   But when I print hostname with mpirun, mpirun process exist on both machines, it's ok.
   I'm using openmpi-1.10.3.

**Comment by githubgsq** [comment]
I found each time connection confused, the listening port number is different. how to guarantee the tcp port is always usable?

**Comment by Yangqing** [comment]
@pietern

**Comment by pietern** [comment]
The problem is that you run more than once with the *same* rendezvous path. The result is that the second time around the processes will try to connect to the ports that were used in the *previous* run. You can fix this by using a different rendezvous path every time you try to run.

That is, specify `--file_store_path=/home/nfscache/gaosiqi/resnet50_rendezvous/XYZ` where XYZ is different for every run. If you have a launcher script you can use `uuid` for example.

**Comment by githubgsq** [comment]
nfs version is ok now, thanks a lot! You are so nice @Yangqing @pietern

**Comment by githubgsq** [comment]
However, when I tried redis version with command:
mpirun -n 1 --host 192.126.232.54  python /home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/gaosiqi/projects/practice/resnet/imagenet_cars_boats_train/  --num_shards=2 --shard_id=0 --db_type lmdb --num_gpus 4 --batch_size 32 --epoch_size 6400  --num_epochs 1 --redis_host="192.126.232.53"  --redis_port=6379 --run_id=00111000 :  -n 1 --host 192.126.232.56 python /home/gaosiqi/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data=/home/gaosiqi/projects/practice/resnet/imagenet_cars_boats_train/  --num_shards=2 --shard_id=1  --db_type lmdb --num_gpus 4 --batch_size 32 --epoch_size 6400  --num_epochs 1 --redis_host="192.126.232.53"  --redis_port=6379 --run_id=00111001

redis store handler timeout occured.
RuntimeError: [enforce fail at pybind_state.cc:859] gWorkspace->RunNetOnce(def).
E0802 19:17:11.892320 15026 common_world_ops.h:90] Caught store handler timeout exception: [/home/gaosiqi/caffe2Env/caffe2/caffe2/distributed/redis_store_handler.cc:110] Wait timeout for name(s): allreduce_0_cw_op/1
E0802 19:17:11.897864 15026 net.cc:143] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

I run ./redis-cli -h 192.126.232.53 -p 6379 on host 192.126.232.54,192.126.232.56 respectively, redis-cli works. then, the redis server can be visited by other hosts. But why redis store handler timeout?
btw, the run id is **different** each time
@Yangqing @pietern

**Comment by pietern** [comment]
@githubgsq The run ID must be different per *run*, but for a single run on multiple machines it must be the same. Think of it as the identifier for your distributed run. It is used by all participating processes to find each other.

**Comment by pietern** [comment]
@githubgsq FYI, you can use the `--prefix` argument for `--file_store_path` since 47e1820c809a5365a2c6ca284fd01303546a8f57

**Comment by githubgsq** [comment]
@pietern hi, pietern, now the redis version runs successfully! HAPPY O(∩_∩)O  THANKS!

**Comment by picctree** [comment]
hi, @githubgsq ,I can run MPI on one node with gpu, but when I run two node ,  errors occur,  it`s RunNetOnce, could you share how to run the redis version?
