### ISSUE TITLE
class comment of Context seems out-of-update with the code

### ISSUE THREAD

**Issue by wangkuiyi** [facebookarchive/caffe2#988]
The [comment](https://github.com/caffe2/caffe2/blob/master/caffe2/core/context.h#L100) explains that the following two functions are to be implemented in a sub-class of `Context`:

```cpp
 * - static void* New(size_t nbytes): allocates memory.
 * - static void Delete(void* data): deletes memory.
```

However, it seems from the code that what is required is the following function:

```cpp
static std::pair<void*, MemoryDeleter> New(size_t nbytes);
```

**Comment by Yangqing** [comment]
Thanks - will merge.
