### ISSUE TITLE
TPU support

### ISSUE THREAD

**Issue by tampler** [facebookarchive/caffe2#996]
Hi I wanna add support for my Tensor Processing Unit chip in Caffe2 for my customers. TPU is implemented as an accelerator for ARM v7 32bit processor and implements multiple arithmetic kernels, similar to GPU.

I'm not currently aware about the scope of work, but believe that should not be that complex, given open examples from GPU vendors.

Does anybody interested in working on this project? How can I contribute to Caffe2 core to add extensions for custom effective hardware and accelerators?

Thank you

**Comment by pkrush** [comment]
Just curious, what is your TPU?

**Comment by charles-r-earp** [comment]
I think you want to create a custom Context class, ie TPUContext. https://github.com/caffe2/caffe2/blob/master/caffe2/core/context.h
This is used as a template argument for Tensors, and Operators interact with the context to do ops. Also look at GPUContext for another example. https://github.com/caffe2/caffe2/blob/master/caffe2/core/context_gpu.h

**Comment by tampler** [comment]
@pkrush  > Just curious, what is your TPU?
FPGA Chip and board for embedded vision and autopilots
