### ISSUE TITLE
Exception when creating the gradient for [Scale]: Unable to cast Python instance to C++ type

### ISSUE THREAD

**Issue by renganxu** [facebookarchive/caffe2#999]
Hi All,

I am trying to use Caffe2-0.8.0. The compilation is fine, but it has runtime error **"Exception: Exception when creating the gradient for [Scale]: Unable to cast Python instance to C++ type (compile in debug mode for details)."**

I was using NCCL 1.3.4 and CUDNN 6.0, and ran resnet 50 example with ImageNet data using the following command:
`export PYTHONPATH=/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build:$PYTHONPATH`
`python resnet50_trainer.py \`
     `--train_data /cm/shared/scratch/rengan/database/caffe/ilsvrc12_train_lmdb/ \`
     `--test_data /cm/shared/scratch/rengan/database/caffe/ilsvrc12_val_lmdb/ \`
    ` --gpus 0,1,2,3 \`
     `--batch_size 256 \`
     `--epoch_size 1280000 \`
     `--num_epochs 1 >& resnet50_4P100.log`

 The detailed output is as follows:
  1 INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
  2 INFO:resnet50_trainer:Using epoch size: 1280000
  3 INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
  4 INFO:data_parallel_model:Create input and model training operators
  5 INFO:data_parallel_model:Model for GPU : 0
  6 INFO:data_parallel_model:Model for GPU : 1
  7 INFO:data_parallel_model:Model for GPU : 2
  8 INFO:data_parallel_model:Model for GPU : 3
  9 INFO:data_parallel_model:Adding gradient operators
 10 Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
 11 Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
 12 Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
 13 Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
 14 Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
 15 Traceback (most recent call last):
 16   File "resnet50_trainer.py", line 465, in <module>
 17     main()
 18   File "resnet50_trainer.py", line 461, in main
 19     Train(args)
 20   File "resnet50_trainer.py", line 312, in Train
 21     cpu_device=args.use_cpu,
 22   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/data_parallel_model.py", line 200, in Parallelize
 23     _AddGradientOperators(devices, model_helper_obj, losses_by_gpu)
 24   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/data_parallel_model.py", line 644, in _AddGradientOperators
 25     model.AddGradientOperators(loss_grad)
 26   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/model_helper.py", line 331, in AddGradientOperators
 27     self.grad_map = self.net.AddGradientOperators(*args, **kwargs)
 28   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/core.py", line 1769, in AddGradientOperators
 29     self._net.op[skip:], ys)
 30   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/core.py", line 1075, in GetBackwardPass
 31     return ir.GetBackwardPass(ys)
 32   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/core.py", line 950, in GetBackwardPass
 33     forward_op_idx, all_input_to_grad)
 34   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/core.py", line 900, in _GenerateGradientsForForwardOp
 35     forward_op, g_output)
 36   File "/cm/shared/scratch/rengan/Caffe2/caffe2-0.8.0/build/caffe2/python/core.py", line 1048, in GetGradientForOp
 37     format(op.type, e)
 38 Exception: Exception when creating the gradient for [Scale]: Unable to cast Python instance to C++ type (compile in debug mode for details).

Anyone know why this error happened and how to fix it? 

Thanks
Rengan

**Comment by mfawzymkh** [comment]
can you please try building caffe2 in debug mode to see if we can get more information about this issue ?

**Comment by renganxu** [comment]
@mfawzymkh The debug mode does not give more information. Someone else also has the same issue and has the output in debug mode:  https://github.com/caffe2/caffe2/issues/889

I noticed that this error appears in RHEL OS. In Ubuntu OS, there is no such error.

**Comment by pietern** [comment]
@hfutxrg I commented in #889. Let's continue there since your issue is identical.
